using System;
using System.Collections.Generic;
using Rewired.ComponentControls.Data;
using Rewired.Internal;
using Rewired.Utils.Attributes;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.Events;
using UnityEngine.UI;

namespace Rewired.ComponentControls
{
	[Serializable]
	[AddComponentMenu("Rewired/Touch Pad")]
	[RequireComponent(typeof(Image))]
	[DisallowMultipleComponent]
	public sealed class TouchPad : TouchInteractable, IPointerDownHandler, IPointerUpHandler, IEventSystemHandler
	{
		public enum AxisDirection
		{
			Both = 0,
			Horizontal = 1,
			Vertical = 2
		}

		public enum TouchPadMode
		{
			Delta = 0,
			ScreenPosition = 1,
			VectorFromCenter = 2,
			VectorFromInitialTouch = 3
		}

		public enum ValueFormat
		{
			Pixels = 0,
			Screen = 1,
			Physical = 2,
			Direction = 3
		}

		private class BjQchuDpsjpUADTukfkHQSfjZMku
		{
			private class FugKRvtpMJacjmRIyJjrynuDqcb
			{
				public float DbmCTGndrOlYXlcWefJllTlFqRN;

				public float lTnovSFCgiTewMUMLUDTbGuvTRJ;

				public uint CTbukiGSFbIYRBXjfdOtKogKTIf;
			}

			private int EGxQQtrfmQBziQxHHWDUoDoqTZk;

			private FugKRvtpMJacjmRIyJjrynuDqcb[] dUqaGcCfoWKXVGjiiebOuLeBmxHO;

			private int bjflEjOceXoNSbWyZHEtmnfxUuN;

			public BjQchuDpsjpUADTukfkHQSfjZMku(int maxSmoothFrames)
			{
			}

			public void ynAzaTrXmpuZxcXTbTqTnIHFxKo(float P_0, float P_1)
			{
			}

			public Vector2 sFxupHnHPuUEibVMJneLOdRbVJJ()
			{
				return default(Vector2);
			}

			private void uHUDqPdvMaqfQwwHwktOKmQROPg()
			{
			}

			private static int EMSMTWNjUJslVkXqDRgXBgDNlnc(int P_0, int P_1)
			{
				return 0;
			}

			private int xTBtStxrKGodJJRJqhOrrMJQANG(int P_0, int P_1)
			{
				return 0;
			}

			private static bool lezBWNOkCyzpnsBEvcoDlUUbWlZ(uint P_0, uint P_1)
			{
				return false;
			}
		}

		[Serializable]
		public class ValueChangedEventHandler : UnityEvent<Vector2>
		{
		}

		[Serializable]
		public class TapEventHandler : UnityEvent
		{
		}

		[Serializable]
		public class PressDownEventHandler : UnityEvent
		{
		}

		[Serializable]
		public class PressUpEventHandler : UnityEvent
		{
		}

		private const int SMOOTH_DELTA_FRAME_COUNT = 3;

		[Tooltip("The Custom Controller element that will receive input values from the touch pad's X axis.")]
		[SerializeField]
		[CustomObfuscation(rename = false)]
		private CustomControllerElementTargetSetForFloat _horizontalAxisCustomControllerElement;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		[Tooltip("The Custom Controller element that will receive input values from the touch pad's Y axis.")]
		private CustomControllerElementTargetSetForFloat _verticalAxisCustomControllerElement;

		[SerializeField]
		[Tooltip("The Custom Controller element that will receive input values from touch pad taps.")]
		[CustomObfuscation(rename = false)]
		private CustomControllerElementTargetSetForBoolean _tapCustomControllerElement;

		[Tooltip("The Custom Controller element that will receive input values from touch pad presses.")]
		[CustomObfuscation(rename = false)]
		[SerializeField]
		private CustomControllerElementTargetSetForBoolean _pressCustomControllerElement;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		[Tooltip("The axis directions in which movement is allowed. You can restrict movement to one or both axes.")]
		private AxisDirection _axesToUse;

		[Tooltip("The mode of the touch pad.\n\nDelta - Returns the change in position of the touch from the previous to the current frame.\n\nScreen Position - Returns the absolute position of the touch  on the screen.\n\nVector From Center - Returns a vector from the center of the Touch Pad to the current touch position.\n\nVector From Initial Touch - Returns a vector from the intial touch position to the current touch position.")]
		[SerializeField]
		[CustomObfuscation(rename = false)]
		private TouchPadMode _touchPadMode;

		[Tooltip("The format of the resulting data generated by the touch pad.\n\nPixels - Screen pixels.\n\nScreen - The proportion of the value to screen size in the corresponding dimension. 1 unit = 1 screen length (width for X, height for Y).\n\nPhysical - 1 unit = 1/100th of an inch. The resulting value will be consistent across different screen resolutions and sizes. IMPORTANT: This relies on the value returned by UnityEngine.Screen.dpi. If the device does not return a value, a reference resolution of 96 dpi will be used.\n\nDirection - A normalized direction vector.")]
		[SerializeField]
		[CustomObfuscation(rename = false)]
		private ValueFormat _valueFormat;

		[Tooltip("If enabled, when swiped and released, the value will slowly fall toward zero based on the Friction value. This only has an effect if Touch Pad Mode is set to Position Delta.")]
		[SerializeField]
		[CustomObfuscation(rename = false)]
		private bool _useInertia;

		[Tooltip("Determines how quickly a swipe value will fall toward zero when Use Inertia is enabled.")]
		[FieldRange(0f, float.MaxValue)]
		[CustomObfuscation(rename = false)]
		[SerializeField]
		private float _inertiaFriction;

		[SerializeField]
		[Tooltip("If true, the touch pad can be activated by a touch swipe that began in an area outside the touch pad region. If false, the touch pad can only be activated by a direct touch.")]
		[CustomObfuscation(rename = false)]
		private bool _activateOnSwipeIn;

		[Tooltip("If true, the touch pad will stay engaged even if the touch that activated it moves outside the touch pad region. If false, the touch pad will be released once the touch that activated it moves outside the touch pad region.")]
		[CustomObfuscation(rename = false)]
		[SerializeField]
		private bool _stayActiveOnSwipeOut;

		[Tooltip("Should taps on the touch pad be processed?")]
		[SerializeField]
		[CustomObfuscation(rename = false)]
		private bool _allowTap;

		[FieldRange(0f, float.MaxValue)]
		[CustomObfuscation(rename = false)]
		[Tooltip("The maximum touch duration allowed for the touch to be considered a tap. A touch that lasts longer than this value will not trigger a tap when released.")]
		[SerializeField]
		private float _tapTimeout;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		[FieldRange(-1, int.MaxValue)]
		[Tooltip("The maximum movement distance allowed in pixels since the touch began for the touch to be considered a tap. [-1 = no limit]")]
		private int _tapDistanceLimit;

		[SerializeField]
		[Tooltip("Should presses (continual press like a button) on the touch pad be processed?")]
		[CustomObfuscation(rename = false)]
		private bool _allowPress;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		[Tooltip("Time the touch pad must be touched before it will be considered a press.")]
		private float _pressStartDelay;

		[Tooltip("The maximum movement distance allowed in pixels since the touch began for the touch to be considered a press. Any movement beyond this value will cancel the press. [-1 = no limit]")]
		[SerializeField]
		[FieldRange(-1, int.MaxValue)]
		[CustomObfuscation(rename = false)]
		private int _pressDistanceLimit;

		[CustomObfuscation(rename = false)]
		[Tooltip("If enabled, the control will be hidden when gameplay starts.")]
		[SerializeField]
		private bool _hideAtRuntime;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		[Tooltip("The underlying Axis 2D.")]
		private StandaloneAxis2D _axis2D;

		[CustomObfuscation(rename = false)]
		[Tooltip("Event sent when the value changes.")]
		[SerializeField]
		private ValueChangedEventHandler _onValueChanged;

		[CustomObfuscation(rename = false)]
		[Tooltip("Event sent when the touch pad is tapped. This event will only be sent if allowTap is True.")]
		[SerializeField]
		private TapEventHandler _onTap;

		[SerializeField]
		[Tooltip("Event sent when the touch pad is initally pressed. This event is for the Press button simulation which must be enabled by setting Press Allowed to True. This event will only be sent if allowPress is True.")]
		[CustomObfuscation(rename = false)]
		private PressDownEventHandler _onPressDown;

		[SerializeField]
		[Tooltip("Event sent when the touch pad is released after a press. This event is for the Press button simulation which must be enabled by setting Press Allowed to True. This event will only be sent if allowPress is True.")]
		[CustomObfuscation(rename = false)]
		private PressUpEventHandler _onPressUp;

		private bool _useXAxis;

		private bool _useYAxis;

		private int _pointerId;

		private int _realMousePointerId;

		[NonSerialized]
		private bool NyqjlerkFIBOqcrEsbpspnhzlBWn;

		[NonSerialized]
		private bool iYqRpkmMnUjFyaotbVhGmoqkshir;

		private bool _pointerDownIsFake;

		private Vector2 _touchStartPosition;

		private float _touchStartTime;

		private Vector3 _currentCenter;

		private Vector2 _previousTouchPosition;

		private int _lastTapFrame;

		private bool _isEligibleForTap;

		private bool _isEligibleForPress;

		private bool _pressValue;

		private BjQchuDpsjpUADTukfkHQSfjZMku _smoothDelta;

		private Dictionary<int, PointerEventData> __fakePointerEventData;

		public CustomControllerElementTargetSetForFloat horizontalAxisCustomControllerElement => null;

		public CustomControllerElementTargetSetForFloat verticalAxisCustomControllerElement => null;

		public CustomControllerElementTargetSetForBoolean tapCustomControllerElement => null;

		public CustomControllerElementTargetSetForBoolean pressCustomControllerElement => null;

		public AxisDirection axesToUse
		{
			get
			{
				return default(AxisDirection);
			}
			set
			{
			}
		}

		public TouchPadMode touchPadMode
		{
			get
			{
				return default(TouchPadMode);
			}
			set
			{
			}
		}

		public ValueFormat valueFormat
		{
			get
			{
				return default(ValueFormat);
			}
			set
			{
			}
		}

		public bool useInertia
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		public float inertiaFriction
		{
			get
			{
				return 0f;
			}
			set
			{
			}
		}

		public bool activateOnSwipeIn
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		public bool stayActiveOnSwipeOut
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		public bool allowTap
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		public float tapTimeout
		{
			get
			{
				return 0f;
			}
			set
			{
			}
		}

		public int tapDistanceLimit
		{
			get
			{
				return 0;
			}
			set
			{
			}
		}

		public bool allowPress
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		public float pressStartDelay
		{
			get
			{
				return 0f;
			}
			set
			{
			}
		}

		public int pressDistanceLimit
		{
			get
			{
				return 0;
			}
			set
			{
			}
		}

		public bool hideAtRuntime
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		public int pointerId
		{
			get
			{
				return 0;
			}
			set
			{
			}
		}

		public bool hasPointer => false;

		public Vector2 touchStartPosition => default(Vector2);

		public Vector2 touchPosition => default(Vector2);

		public AxisCalibration horizontalAxisCalibration => null;

		public AxisCalibration verticalAxisCalibration => null;

		public Axis2DCalibration axis2DCalibration => null;

		internal StandaloneAxis2D axis2D => null;

		private int effectivePointerId => 0;

		private bool tapValue => false;

		public event UnityAction<Vector2> ValueChangedEvent
		{
			add
			{
			}
			remove
			{
			}
		}

		public event UnityAction TapEvent
		{
			add
			{
			}
			remove
			{
			}
		}

		public event UnityAction PressDownEvent
		{
			add
			{
			}
			remove
			{
			}
		}

		public event UnityAction PressUpEvent
		{
			add
			{
			}
			remove
			{
			}
		}

		[CustomObfuscation(rename = false)]
		private TouchPad()
		{
		}

		[CustomObfuscation(rename = false)]
		internal override void Awake()
		{
		}

		[CustomObfuscation(rename = false)]
		internal override void OnValidate()
		{
		}

		internal override bool kCtpTQnECPegKfokmmotHswhcCLu()
		{
			return false;
		}

		internal override void UvjCYqPOLWYwPPujGcXEXxRteLL()
		{
		}

		internal override void iagGGZhzoHvsifYztDyhsUjnGQZ()
		{
		}

		internal override void ILfKseeIovFotfIwVedwwNJgiCCt()
		{
		}

		internal override void uljBdNGgTHBIuJdsRFrEMcxJEVjD()
		{
		}

		public override void ClearValue()
		{
		}

		private void bvTAFhqERolFHfOeXbNxGuHwuYYG()
		{
		}

		private void JqSYEAvMLbujqgZqBunTkBEGTIA()
		{
		}

		private void RAwVOuyBQJuvJvLRvcPYIZubZdn(AxisDirection P_0)
		{
		}

		private void qKybyEPGwquHThgDXJohAlSJcPG()
		{
		}

		private void ddXZyOkVTesPStJCPWrPOGVfyBs()
		{
		}

		private void uhDWldUJcnmhlmOihECVhuLIqWIb()
		{
		}

		private void pwLaYzBVIiqkUhccepNvaokEGAka()
		{
		}

		private void HYweATHlStojINOgIkruJkTcjkg(ref Vector2 P_0)
		{
		}

		private void ileuEfeutMYAjmPmUZlUmHYnbTv(ref Vector2 P_0)
		{
		}

		private void rinAJBjlXrMVXptKQtFXWNjHfwZc()
		{
		}

		private Vector2 bmRaQCAyWvBkpwPphJSFvfzgmAw(Vector2 P_0)
		{
			return default(Vector2);
		}

		private void ZyDUWBGxnTalAEXJuooczSNkThH(bool P_0)
		{
		}

		private void rwILpGMLcDAnggJJPjnFKJmjkkV(PointerEventData P_0)
		{
		}

		private void KGnHQyTRRAYZywAdMqcQwDPfPo(PointerEventData P_0)
		{
		}

		private void KPfYwTlNHSewjMThVCToyjhHCFha(PointerEventData P_0)
		{
		}

		private void oPNajkGScOUePgaQHAZNNGaQujNJ(PointerEventData P_0)
		{
		}

		private void UTotXmLEdaIKmhEhaohsrCOmSKj(int P_0, Vector2 P_1)
		{
		}

		private void DVJysEZaYwGncINoyinUaozQRsmT()
		{
		}

		internal override void OnPointerUp(PointerEventData eventData)
		{
		}

		internal override void OnPointerDown(PointerEventData eventData)
		{
		}

		internal override void OnPointerEnter(PointerEventData eventData)
		{
		}

		internal override void OnPointerExit(PointerEventData eventData)
		{
		}

		private void sXRDhAKcRFVqpujuicGMzkcbLvk()
		{
		}

		private bool RIWUjwTZXIFAvqiJqzsRmjKEWiX(int P_0)
		{
			return false;
		}

		private PointerEventData zACIGkzGfCcuTSbrwFEaWnJTawo(int P_0, GameObject P_1)
		{
			return null;
		}

		private PointerEventData uoyOzXVzLHclcmqgACYXhWOOSwg(int P_0, GameObject P_1)
		{
			return null;
		}

		private PointerEventData yJILvFKbUrQLqAqCnfxIaCOgTVXa(int P_0)
		{
			return null;
		}

		private void UEsNkFZcANbClMtwGXPrJWRikHg(PointerEventData P_0)
		{
		}

		private PointerEventData AftRdPGjJPVnaLvMfBHcloCgtOW(int P_0)
		{
			return null;
		}
	}
}
