<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Timberborn.DemolishingUI</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Timberborn.BuilderPrioritySystemUI">
      <HintPath>..\..\Assemblies\Timberborn.BuilderPrioritySystemUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.CoreUI">
      <HintPath>..\..\Assemblies\Timberborn.CoreUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Localization">
      <HintPath>..\..\Assemblies\Timberborn.Localization.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.InputSystem">
      <HintPath>..\..\Assemblies\Timberborn.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TooltipSystem">
      <HintPath>..\..\Assemblies\Timberborn.TooltipSystem.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BaseComponentSystem">
      <HintPath>..\..\Assemblies\Timberborn.BaseComponentSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SingletonSystem">
      <HintPath>..\..\Assemblies\Timberborn.SingletonSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Rendering">
      <HintPath>..\..\Assemblies\Timberborn.Rendering.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.CameraSystem">
      <HintPath>..\..\Assemblies\Timberborn.CameraSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BlueprintSystem">
      <HintPath>..\..\Assemblies\Timberborn.BlueprintSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Demolishing">
      <HintPath>..\..\Assemblies\Timberborn.Demolishing.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Common">
      <HintPath>..\..\Assemblies\Timberborn.Common.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Planting">
      <HintPath>..\..\Assemblies\Timberborn.Planting.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TerrainSystem">
      <HintPath>..\..\Assemblies\Timberborn.TerrainSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.AreaSelectionSystem">
      <HintPath>..\..\Assemblies\Timberborn.AreaSelectionSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.AreaSelectionSystemUI">
      <HintPath>..\..\Assemblies\Timberborn.AreaSelectionSystemUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.ToolSystemUI">
      <HintPath>..\..\Assemblies\Timberborn.ToolSystemUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BlockSystem">
      <HintPath>..\..\Assemblies\Timberborn.BlockSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TemplateInstantiation">
      <HintPath>..\..\Assemblies\Timberborn.TemplateInstantiation.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TerrainPhysics">
      <HintPath>..\..\Assemblies\Timberborn.TerrainPhysics.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EntityPanelSystem">
      <HintPath>..\..\Assemblies\Timberborn.EntityPanelSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.PrioritySystemUI">
      <HintPath>..\..\Assemblies\Timberborn.PrioritySystemUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.StatusSystem">
      <HintPath>..\..\Assemblies\Timberborn.StatusSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.ToolSystem">
      <HintPath>..\..\Assemblies\Timberborn.ToolSystem.dll</HintPath>
    </Reference>
    <Reference Include="Bindito.Core">
      <HintPath>..\..\Assemblies\Bindito.Core.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TickSystem">
      <HintPath>..\..\Assemblies\Timberborn.TickSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EntitySystem">
      <HintPath>..\..\Assemblies\Timberborn.EntitySystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.UIFormatters">
      <HintPath>..\..\Assemblies\Timberborn.UIFormatters.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BuilderPrioritySystem">
      <HintPath>..\..\Assemblies\Timberborn.BuilderPrioritySystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.PrioritySystem">
      <HintPath>..\..\Assemblies\Timberborn.PrioritySystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BlockObjectModelSystem">
      <HintPath>..\..\Assemblies\Timberborn.BlockObjectModelSystem.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>