namespace Restory.UserInterface
{
	public enum GUICursorState
	{
		DEFAULT = 0,
		INACTIVE = 10,
		BASE_ACTION = 20,
		INTERACTION_CIRCLE = 30,
		IS_NOT_READY_FOR_INTERACTION = 40,
		IS_BLOCKED = 50,
		TAKE_ITEM_ACTION = 60,
		DRAG_ITEM_ACTION = 70,
		QUICK_ACTION_CONNECT_CABLE = 80,
		OPEN_BUILDING_BLANK_RESOURCES_ADDING_MENU = 85,
		QUICK_ACTION_TRANSFER_CARRY_LOOT_TO_BUILDING_BLANK = 90,
		IN_BUILDING_BLANK_PLACEMENT_ACTION = 100,
		SET_MINION_DESTINATION_ACTION = 110,
		TURNED_OFF = 120,
		LONG_EXECUTION_ACTION = 130
	}
}
