<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\MegaBonk\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\MegaBonk\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Splines">
      <HintPath>..\MegaBonk\Unity.Splines.dll</HintPath>
    </Reference>
    <Reference Include="System.Numerics" />
    <Reference Include="Discord">
      <HintPath>..\MegaBonk\Discord.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\MegaBonk\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="Rewired_Core">
      <HintPath>..\MegaBonk\Rewired_Core.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Localization">
      <HintPath>..\MegaBonk\Unity.Localization.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\MegaBonk\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>..\MegaBonk\com.rlabrecque.steamworks.net.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\MegaBonk\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\MegaBonk\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>..\MegaBonk\System.Core.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\MegaBonk\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreFontEngineModule">
      <HintPath>..\MegaBonk\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\MegaBonk\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\MegaBonk\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Postprocessing.Runtime">
      <HintPath>..\MegaBonk\Unity.Postprocessing.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\MegaBonk\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="Coffee.UIParticle">
      <HintPath>..\MegaBonk\Coffee.UIParticle.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>..\MegaBonk\UnityEngine.TerrainModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.AI.Navigation">
      <HintPath>..\MegaBonk\Unity.AI.Navigation.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>..\MegaBonk\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>..\MegaBonk\Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="Unity.VisualScripting.Core">
      <HintPath>..\MegaBonk\Unity.VisualScripting.Core.dll</HintPath>
    </Reference>
    <Reference Include="MK.Toon">
      <HintPath>..\MegaBonk\MK.Toon.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\MegaBonk\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="Rewired_Windows">
      <HintPath>..\MegaBonk\Rewired_Windows.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\MegaBonk\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SharedInternalsModule">
      <HintPath>..\MegaBonk\UnityEngine.SharedInternalsModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ResourceManager">
      <HintPath>..\MegaBonk\Unity.ResourceManager.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>