<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>NSubstitute</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net45</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Core" />
    <Reference Include="System.Threading.Tasks.Extensions">
      <HintPath>..\..\Assemblies\System.Threading.Tasks.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="Castle.Core">
      <HintPath>..\..\Assemblies\Castle.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>