using System;

namespace Assets.Scripts.Saves___Serialization.Progression.Stats
{
	[Serializable]
	public enum EMyStat
	{
		kills = 0,
		goldEarned = 1,
		goldSpent = 2,
		chestsOpened = 3,
		itemsPickedUp = 4,
		eliteKills = 5,
		bossKills = 6,
		xpGained = 7,
		skeletonKills = 8,
		damageReductionArmorAsKnight = 9,
		damageReductionArmor = 10,
		projectilesFired = 11,
		evades = 12,
		potsBroken = 13,
		shrineSucc = 14,
		fireKills = 15,
		shrineCharge = 16,
		lifestealHealing = 17,
		shrineChallenge = 18,
		crits = 19,
		chestsBought = 20,
		minibossKills = 21,
		runs = 22,
		silverEarned = 23,
		cactusKillsWithThorns = 24,
		lightningKills = 25,
		standingStillKills = 26,
		bloodMagicProcs = 27,
		finalBossKills = 28,
		icecubeFreezes = 29,
		foxWispsKills = 30,
		powerupsUsed = 31,
		goblinKills = 32,
		minibossKillsCalcium = 33,
		killsInTornadoWithTornado = 34,
		moldyCheeseProcs = 35,
		questsCompleted = 36,
		challengesCompleted = 37,
		wallhugs = 38,
		unlocksPurchased = 39,
		shrineChargeSandstorm = 40,
		aegisBlocks = 41,
		silver = 42,
		microwavesExploded = 43,
		shadyGuysBlack = 44,
		shadyGuysBlue = 45,
		shadyGuysPink = 46,
		shadyGuysGold = 47,
		quinsMaskKillsAsAthena = 48,
		kevinPunches = 49,
		birdoFlyingMinesKills = 50
	}
}
