internal class OoMOZEqfXndBIZKQcgmHDZDrhUwEA : gDrCmzJNXwFvGTMAYKGQspUqeYD
{
	protected readonly AomZkhATSIadYOOLVfcgOnNtMQBs cjQPccnIYmSeKouGbcODBVBCOzvT;

	private readonly string JrsvlSVekgWnsqofWgIElwIBbkcw;

	private readonly string IESEnoclSffblaIcZezOPpCscHnW;

	private string UfpfOkQXQEoHepleJZRmOICETMbs;

	private readonly string ZnHMlntRGanYWWqtfMdTJaYhEVQZ;

	private int IQrbKTwWhUcCfkfGJrQdLvjsheSbb;

	public AomZkhATSIadYOOLVfcgOnNtMQBs JLFYlpbldhaAwtjOCdSYZmwoESgjA => null;

	string gDrCmzJNXwFvGTMAYKGQspUqeYD.keyCategory => null;

	string gDrCmzJNXwFvGTMAYKGQspUqeYD.scriptingName => null;

	string gDrCmzJNXwFvGTMAYKGQspUqeYD.nonLocalizedDescriptiveName
	{
		get
		{
			return null;
		}
		set
		{
		}
	}

	string gDrCmzJNXwFvGTMAYKGQspUqeYD.key => null;

	int gDrCmzJNXwFvGTMAYKGQspUqeYD.autoGeneratedValueFlags
	{
		get
		{
			return 0;
		}
		set
		{
		}
	}

	public string keyCategory => null;

	public string scriptingName => null;

	public string aVVdhXOnPqdAnZNJpkXLKIdxbTax => null;

	public string nonLocalizedDescriptiveName => null;

	public string key => null;

	public OoMOZEqfXndBIZKQcgmHDZDrhUwEA(AomZkhATSIadYOOLVfcgOnNtMQBs P_0, string P_1, string P_2, string P_3, string P_4)
	{
	}

	public virtual bool ONNbteXxuydDDSwvcgYKyVMQOdPh(OoMOZEqfXndBIZKQcgmHDZDrhUwEA P_0, bool P_1)
	{
		return false;
	}
}
