using System;

internal class dBejqobAKxMNrcOhZnQrQTWkdQOw : AIHwxHYiZBEVvZOJUhghGWlTpYhGA
{
	protected readonly pbjvuCPUSoxkvbSHfHZTgPpvxwgh gkTTVodtQxfQDGMxpgdkHoaahErLA;

	private readonly string fqjvIhtDgdHuOcCAvPhfjIDTOxRi;

	private readonly string jhLdUXYbbZxoEgzlqUbuHijGeazm;

	private int vjdQuGSHUKZQrTGWoSCXaelDouNb;

	public pbjvuCPUSoxkvbSHfHZTgPpvxwgh UcpcurXRPBjIKaMHLLwrdwKePvaf => gkTTVodtQxfQDGMxpgdkHoaahErLA;

	string AIHwxHYiZBEVvZOJUhghGWlTpYhGA.keyCategory => fqjvIhtDgdHuOcCAvPhfjIDTOxRi;

	string AIHwxHYiZBEVvZOJUhghGWlTpYhGA.key => jhLdUXYbbZxoEgzlqUbuHijGeazm;

	int AIHwxHYiZBEVvZOJUhghGWlTpYhGA.autoGeneratedValueFlags
	{
		get
		{
			return vjdQuGSHUKZQrTGWoSCXaelDouNb;
		}
		set
		{
			vjdQuGSHUKZQrTGWoSCXaelDouNb = value;
		}
	}

	public string keyCategory => fqjvIhtDgdHuOcCAvPhfjIDTOxRi;

	public string key => jhLdUXYbbZxoEgzlqUbuHijGeazm;

	public dBejqobAKxMNrcOhZnQrQTWkdQOw(pbjvuCPUSoxkvbSHfHZTgPpvxwgh P_0, string P_1, string P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException();
		}
		gkTTVodtQxfQDGMxpgdkHoaahErLA = P_0;
		fqjvIhtDgdHuOcCAvPhfjIDTOxRi = P_1;
		jhLdUXYbbZxoEgzlqUbuHijGeazm = P_2;
		P_0.JBtKTUACafaihxMYlnsjoyoqpDOe(this);
	}

	public virtual bool FQZWMKbFOFaPGRzEyAcatLzKIFv(dBejqobAKxMNrcOhZnQrQTWkdQOw P_0)
	{
		if (P_0 == null)
		{
			return false;
		}
		if ((object)GetType() != P_0.GetType())
		{
			return false;
		}
		if (!gkTTVodtQxfQDGMxpgdkHoaahErLA.tFwNistcfiNLBsTMMnssjhRVlqOG(P_0.gkTTVodtQxfQDGMxpgdkHoaahErLA))
		{
			return false;
		}
		return true;
	}
}
