using System;
using Rewired;
using Rewired.Internal.Localization;

internal abstract class eYHlPtwpJoIPfXzbZKxlaBzhwzfV : AomZkhATSIadYOOLVfcgOnNtMQBs
{
	protected readonly LocalizedString PqbpkCPKXpCXORlpKNNwfZegKUSt;

	protected readonly LocalizedString zvTDQGflTtzrCKZQkcvYzgZRNcRDA;

	public abstract string zPNcigbiryaPgXbjyaoZNShrqVUfb { get; }

	public abstract string RLbUDlHGeFvGjHacKFOBoouLwnJJ { get; }

	protected eYHlPtwpJoIPfXzbZKxlaBzhwzfV(fyQKArxdnRgBFXnCTGFifmqgwogRA P_0, OUxgQpuZIuwKyJEylNPLslOwBwNAA P_1)
		: base(P_0, P_1)
	{
		PqbpkCPKXpCXORlpKNNwfZegKUSt = new LocalizedString();
		zvTDQGflTtzrCKZQkcvYzgZRNcRDA = new LocalizedString();
	}

	protected eYHlPtwpJoIPfXzbZKxlaBzhwzfV(mQQEUnWrvIENJEQHDjPIUvhAyczkA P_0, fyQKArxdnRgBFXnCTGFifmqgwogRA P_1, OUxgQpuZIuwKyJEylNPLslOwBwNAA P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
		PqbpkCPKXpCXORlpKNNwfZegKUSt = new LocalizedString();
		zvTDQGflTtzrCKZQkcvYzgZRNcRDA = new LocalizedString();
	}

	protected virtual void QnkvEZPvZNbKVaoBHubOJPETogYG()
	{
		LkQRPNtLZxlSRESaPGkQjrNILfSL();
	}

	public virtual void XWfvaEmnrLftNIKrWfnvpXbfECHIA(mQQEUnWrvIENJEQHDjPIUvhAyczkA P_0)
	{
		GDNPdTRkvkcYBsFVTOaYnLSpXXKh(P_0);
	}

	public virtual void HJtCwlKhYBfUYYkdyfBJAnKZekpZ(gDrCmzJNXwFvGTMAYKGQspUqeYD P_0)
	{
		base.GDNPdTRkvkcYBsFVTOaYnLSpXXKh(P_0);
		if (!(P_0 is mQQEUnWrvIENJEQHDjPIUvhAyczkA))
		{
			throw new ArgumentException("value must implement " + typeof(mQQEUnWrvIENJEQHDjPIUvhAyczkA));
		}
	}

	public virtual void ENathmEgqelvRPnBtkULXfIUaJffA()
	{
		TDKmJIWOjsfmrjGxkDYGHhJupxzKA();
		PqbpkCPKXpCXORlpKNNwfZegKUSt.Clear();
		zvTDQGflTtzrCKZQkcvYzgZRNcRDA.Clear();
	}

	public virtual void bCgCgUKZpzfINrqFGLaggABGwwMlB()
	{
		lhdOvYLoqhTkAKWLCfmALaqDPClT();
		PqbpkCPKXpCXORlpKNNwfZegKUSt.Clear();
		zvTDQGflTtzrCKZQkcvYzgZRNcRDA.Clear();
	}

	public void mztjgSvtWyiKAVslVXeHfueYismq()
	{
		PqbpkCPKXpCXORlpKNNwfZegKUSt.Clear();
		idImOmuzvdGLOotALUOanCfXIOuS(lZwSneskMjdcCDRCpckhVVEyJnLl.Keys);
	}

	public void PIdHGZlcDhZFWxuBqwdYeqgtpOuM()
	{
		zvTDQGflTtzrCKZQkcvYzgZRNcRDA.Clear();
		idImOmuzvdGLOotALUOanCfXIOuS(lZwSneskMjdcCDRCpckhVVEyJnLl.Keys);
	}

	public void gCQsiuHHoDBgyTofsxyDxbEzjwLF()
	{
		PqbpkCPKXpCXORlpKNNwfZegKUSt.Clear();
		idImOmuzvdGLOotALUOanCfXIOuS(lZwSneskMjdcCDRCpckhVVEyJnLl.Names);
	}

	public void VfXqdBFmbAriTEKxazHGnZJzQear()
	{
		zvTDQGflTtzrCKZQkcvYzgZRNcRDA.Clear();
		idImOmuzvdGLOotALUOanCfXIOuS(lZwSneskMjdcCDRCpckhVVEyJnLl.Names);
	}

	public virtual bool MdxxPyfHfndEXBmSVaqqImkPVasvA(CrEdIhdRuEefdCHiQoLwiMECdkdvB P_0, bool P_1)
	{
		if (!(P_0 is eYHlPtwpJoIPfXzbZKxlaBzhwzfV eYHlPtwpJoIPfXzbZKxlaBzhwzfV2))
		{
			return false;
		}
		if (!AztKGIvbswaZWeSHBhgTxTXCcKLB(P_0, P_1))
		{
			return false;
		}
		mQQEUnWrvIENJEQHDjPIUvhAyczkA mQQEUnWrvIENJEQHDjPIUvhAyczkA2 = dsHwORJIAktDRQJcegmaiPKJsgVrA();
		mQQEUnWrvIENJEQHDjPIUvhAyczkA mQQEUnWrvIENJEQHDjPIUvhAyczkA3 = eYHlPtwpJoIPfXzbZKxlaBzhwzfV2.dsHwORJIAktDRQJcegmaiPKJsgVrA();
		if (mQQEUnWrvIENJEQHDjPIUvhAyczkA2 == null != (mQQEUnWrvIENJEQHDjPIUvhAyczkA3 == null))
		{
			return false;
		}
		if (mQQEUnWrvIENJEQHDjPIUvhAyczkA2 != null && P_1 && (!string.Equals(mQQEUnWrvIENJEQHDjPIUvhAyczkA2.positiveKey, mQQEUnWrvIENJEQHDjPIUvhAyczkA3.positiveKey, StringComparison.Ordinal) || !string.Equals(mQQEUnWrvIENJEQHDjPIUvhAyczkA2.negativeKey, mQQEUnWrvIENJEQHDjPIUvhAyczkA3.negativeKey, StringComparison.Ordinal) || !string.Equals(mQQEUnWrvIENJEQHDjPIUvhAyczkA2.nonLocalizedPositiveDescriptiveName, mQQEUnWrvIENJEQHDjPIUvhAyczkA3.nonLocalizedPositiveDescriptiveName, StringComparison.Ordinal) || !string.Equals(mQQEUnWrvIENJEQHDjPIUvhAyczkA2.nonLocalizedNegativeDescriptiveName, mQQEUnWrvIENJEQHDjPIUvhAyczkA3.nonLocalizedNegativeDescriptiveName, StringComparison.Ordinal)))
		{
			return false;
		}
		return true;
	}

	protected virtual void TsaCSQDRxloaghHNfhvWLJvOZnIFB()
	{
		rGEIdssYVmaHobuMTZpfrtsIoPZC();
		PqbpkCPKXpCXORlpKNNwfZegKUSt.Clear();
		zvTDQGflTtzrCKZQkcvYzgZRNcRDA.Clear();
	}

	protected virtual void XLxxLmffmNkewsOzGFGvkraWPQMUA(lZwSneskMjdcCDRCpckhVVEyJnLl P_0)
	{
		base.idImOmuzvdGLOotALUOanCfXIOuS(P_0);
		mQQEUnWrvIENJEQHDjPIUvhAyczkA mQQEUnWrvIENJEQHDjPIUvhAyczkA2 = dsHwORJIAktDRQJcegmaiPKJsgVrA();
		if (mQQEUnWrvIENJEQHDjPIUvhAyczkA2 == null)
		{
			return;
		}
		if ((mQQEUnWrvIENJEQHDjPIUvhAyczkA2.autoGeneratedValueFlags & 2) == 0 && string.IsNullOrEmpty(mQQEUnWrvIENJEQHDjPIUvhAyczkA2.nonLocalizedPositiveDescriptiveName) && kRcfUaOGeoIGpcXfnKqeRSlYxRaTA(Pole.Positive))
		{
			mQQEUnWrvIENJEQHDjPIUvhAyczkA2.nonLocalizedPositiveDescriptiveName = mQQEUnWrvIENJEQHDjPIUvhAyczkA2.nonLocalizedDescriptiveName;
			if (nhIBYHeluYKeWeyuLacoDYyecGhiB(Pole.Positive))
			{
				mQQEUnWrvIENJEQHDjPIUvhAyczkA2.nonLocalizedPositiveDescriptiveName = LocalizationManager.AppendToNameAxisPole(mQQEUnWrvIENJEQHDjPIUvhAyczkA2.nonLocalizedPositiveDescriptiveName, Pole.Positive);
			}
			mQQEUnWrvIENJEQHDjPIUvhAyczkA2.autoGeneratedValueFlags |= 2;
			ZHfrtfTBXdLnGOfNRdLnBGkKHMRQ(2);
		}
		if ((mQQEUnWrvIENJEQHDjPIUvhAyczkA2.autoGeneratedValueFlags & 4) == 0 && string.IsNullOrEmpty(mQQEUnWrvIENJEQHDjPIUvhAyczkA2.nonLocalizedNegativeDescriptiveName) && kRcfUaOGeoIGpcXfnKqeRSlYxRaTA(Pole.Negative))
		{
			mQQEUnWrvIENJEQHDjPIUvhAyczkA2.nonLocalizedNegativeDescriptiveName = mQQEUnWrvIENJEQHDjPIUvhAyczkA2.nonLocalizedDescriptiveName;
			if (nhIBYHeluYKeWeyuLacoDYyecGhiB(Pole.Negative))
			{
				mQQEUnWrvIENJEQHDjPIUvhAyczkA2.nonLocalizedNegativeDescriptiveName = LocalizationManager.AppendToNameAxisPole(mQQEUnWrvIENJEQHDjPIUvhAyczkA2.nonLocalizedNegativeDescriptiveName, Pole.Negative);
			}
			mQQEUnWrvIENJEQHDjPIUvhAyczkA2.autoGeneratedValueFlags |= 4;
			ZHfrtfTBXdLnGOfNRdLnBGkKHMRQ(4);
		}
		if (string.IsNullOrEmpty(mQQEUnWrvIENJEQHDjPIUvhAyczkA2.key))
		{
			return;
		}
		if ((mQQEUnWrvIENJEQHDjPIUvhAyczkA2.autoGeneratedValueFlags & 8) == 0 && string.IsNullOrEmpty(mQQEUnWrvIENJEQHDjPIUvhAyczkA2.positiveKey) && kRcfUaOGeoIGpcXfnKqeRSlYxRaTA(Pole.Positive))
		{
			mQQEUnWrvIENJEQHDjPIUvhAyczkA2.positiveKey = mQQEUnWrvIENJEQHDjPIUvhAyczkA2.key;
			if (nhIBYHeluYKeWeyuLacoDYyecGhiB(Pole.Positive))
			{
				mQQEUnWrvIENJEQHDjPIUvhAyczkA2.positiveKey = LocalizationManager.AppendToKeyAxisPole(mQQEUnWrvIENJEQHDjPIUvhAyczkA2.positiveKey, Pole.Positive);
			}
			mQQEUnWrvIENJEQHDjPIUvhAyczkA2.autoGeneratedValueFlags |= 8;
			ZHfrtfTBXdLnGOfNRdLnBGkKHMRQ(8);
		}
		if ((mQQEUnWrvIENJEQHDjPIUvhAyczkA2.autoGeneratedValueFlags & 0x10) == 0 && string.IsNullOrEmpty(mQQEUnWrvIENJEQHDjPIUvhAyczkA2.negativeKey) && kRcfUaOGeoIGpcXfnKqeRSlYxRaTA(Pole.Negative))
		{
			mQQEUnWrvIENJEQHDjPIUvhAyczkA2.negativeKey = mQQEUnWrvIENJEQHDjPIUvhAyczkA2.key;
			if (nhIBYHeluYKeWeyuLacoDYyecGhiB(Pole.Negative))
			{
				mQQEUnWrvIENJEQHDjPIUvhAyczkA2.negativeKey = LocalizationManager.AppendToKeyAxisPole(mQQEUnWrvIENJEQHDjPIUvhAyczkA2.negativeKey, Pole.Negative);
			}
			mQQEUnWrvIENJEQHDjPIUvhAyczkA2.autoGeneratedValueFlags |= 16;
			ZHfrtfTBXdLnGOfNRdLnBGkKHMRQ(16);
		}
	}

	protected virtual void HwQPpsPUQulCkPbXWeHNcauuICBJ(FzqQtDWakuZFTntlWNdHXCvRdaki P_0)
	{
		base.HpPYiVrcZlpqpRSiAtDWiaBwavJF(P_0);
		mQQEUnWrvIENJEQHDjPIUvhAyczkA mQQEUnWrvIENJEQHDjPIUvhAyczkA2 = dsHwORJIAktDRQJcegmaiPKJsgVrA();
		if (mQQEUnWrvIENJEQHDjPIUvhAyczkA2 != null && ((uint)mQQEUnWrvIENJEQHDjPIUvhAyczkA2.autoGeneratedValueFlags & (uint)P_0) != 0)
		{
			if ((P_0 & FzqQtDWakuZFTntlWNdHXCvRdaki.PositiveKey) != FzqQtDWakuZFTntlWNdHXCvRdaki.None && (mQQEUnWrvIENJEQHDjPIUvhAyczkA2.autoGeneratedValueFlags & 8) != 0)
			{
				mQQEUnWrvIENJEQHDjPIUvhAyczkA2.positiveKey = null;
				ZHfrtfTBXdLnGOfNRdLnBGkKHMRQ(8);
				mQQEUnWrvIENJEQHDjPIUvhAyczkA2.autoGeneratedValueFlags &= -9;
			}
			if ((P_0 & FzqQtDWakuZFTntlWNdHXCvRdaki.NegativeKey) != FzqQtDWakuZFTntlWNdHXCvRdaki.None && (mQQEUnWrvIENJEQHDjPIUvhAyczkA2.autoGeneratedValueFlags & 0x10) != 0)
			{
				mQQEUnWrvIENJEQHDjPIUvhAyczkA2.negativeKey = null;
				ZHfrtfTBXdLnGOfNRdLnBGkKHMRQ(16);
				mQQEUnWrvIENJEQHDjPIUvhAyczkA2.autoGeneratedValueFlags &= -17;
			}
			if ((P_0 & FzqQtDWakuZFTntlWNdHXCvRdaki.PositiveDescriptiveName) != FzqQtDWakuZFTntlWNdHXCvRdaki.None && (mQQEUnWrvIENJEQHDjPIUvhAyczkA2.autoGeneratedValueFlags & 2) != 0)
			{
				mQQEUnWrvIENJEQHDjPIUvhAyczkA2.nonLocalizedPositiveDescriptiveName = null;
				ZHfrtfTBXdLnGOfNRdLnBGkKHMRQ(2);
				mQQEUnWrvIENJEQHDjPIUvhAyczkA2.autoGeneratedValueFlags &= -3;
			}
			if ((P_0 & FzqQtDWakuZFTntlWNdHXCvRdaki.NegativeDescriptiveName) != FzqQtDWakuZFTntlWNdHXCvRdaki.None && (mQQEUnWrvIENJEQHDjPIUvhAyczkA2.autoGeneratedValueFlags & 4) != 0)
			{
				mQQEUnWrvIENJEQHDjPIUvhAyczkA2.nonLocalizedNegativeDescriptiveName = null;
				ZHfrtfTBXdLnGOfNRdLnBGkKHMRQ(4);
				mQQEUnWrvIENJEQHDjPIUvhAyczkA2.autoGeneratedValueFlags &= -5;
			}
		}
	}

	protected virtual FzqQtDWakuZFTntlWNdHXCvRdaki PKWwspOMjSbQDkMfjAzyByZhFpetA(lZwSneskMjdcCDRCpckhVVEyJnLl P_0)
	{
		FzqQtDWakuZFTntlWNdHXCvRdaki fzqQtDWakuZFTntlWNdHXCvRdaki = base.TMcNPOZjXahkaxuEqKMUWpjQbXCu(P_0);
		if ((P_0 & lZwSneskMjdcCDRCpckhVVEyJnLl.Keys) != lZwSneskMjdcCDRCpckhVVEyJnLl.None)
		{
			fzqQtDWakuZFTntlWNdHXCvRdaki |= (FzqQtDWakuZFTntlWNdHXCvRdaki)24;
		}
		if ((P_0 & lZwSneskMjdcCDRCpckhVVEyJnLl.Names) != lZwSneskMjdcCDRCpckhVVEyJnLl.None)
		{
			fzqQtDWakuZFTntlWNdHXCvRdaki |= (FzqQtDWakuZFTntlWNdHXCvRdaki)6;
		}
		return fzqQtDWakuZFTntlWNdHXCvRdaki;
	}

	protected mQQEUnWrvIENJEQHDjPIUvhAyczkA dsHwORJIAktDRQJcegmaiPKJsgVrA()
	{
		return qUiJUHBRFEvMwwcmkRXSpLZcYrJm() as mQQEUnWrvIENJEQHDjPIUvhAyczkA;
	}

	protected virtual bool nhIBYHeluYKeWeyuLacoDYyecGhiB(Pole P_0)
	{
		return base.sIxvbdiJJXGTPKMdgswAQFCeVOyI switch
		{
			fyQKArxdnRgBFXnCTGFifmqgwogRA.Axis => true, 
			fyQKArxdnRgBFXnCTGFifmqgwogRA.Button => false, 
			_ => false, 
		};
	}

	protected virtual bool kRcfUaOGeoIGpcXfnKqeRSlYxRaTA(Pole P_0)
	{
		return base.sIxvbdiJJXGTPKMdgswAQFCeVOyI switch
		{
			fyQKArxdnRgBFXnCTGFifmqgwogRA.Axis => true, 
			fyQKArxdnRgBFXnCTGFifmqgwogRA.Button => P_0 switch
			{
				Pole.Positive => true, 
				Pole.Negative => false, 
				_ => false, 
			}, 
			_ => false, 
		};
	}

	protected virtual void kXGIEtlbEDSnYPzCYvCHHHyLxqDS()
	{
		base.fsJzDjYGZNEsXoOdrgfUlDksvlUG();
		_ = zPNcigbiryaPgXbjyaoZNShrqVUfb;
		_ = RLbUDlHGeFvGjHacKFOBoouLwnJJ;
	}

	protected virtual void yYkUuoYSWBrUVCGGVdnQHOSrRJIcA()
	{
		DaTALLHXzryylPLlNnhlPKgOrTSO();
		nUmRSnqJXLfZyjJvcbTdXNBpBiEX(1, new BKckUJBjHlyNjLMNcSvupioWhbq
		{
			qgVDeAEkFdUtVgYlhFXwAjAVYpXv = 6
		});
		nUmRSnqJXLfZyjJvcbTdXNBpBiEX(8, new BKckUJBjHlyNjLMNcSvupioWhbq(PqbpkCPKXpCXORlpKNNwfZegKUSt, 2));
		nUmRSnqJXLfZyjJvcbTdXNBpBiEX(16, new BKckUJBjHlyNjLMNcSvupioWhbq(zvTDQGflTtzrCKZQkcvYzgZRNcRDA, 4));
		nUmRSnqJXLfZyjJvcbTdXNBpBiEX(2, new BKckUJBjHlyNjLMNcSvupioWhbq
		{
			DjGcOGzVTgfPpfASudPfdptdepSkA = PqbpkCPKXpCXORlpKNNwfZegKUSt
		});
		nUmRSnqJXLfZyjJvcbTdXNBpBiEX(4, new BKckUJBjHlyNjLMNcSvupioWhbq
		{
			DjGcOGzVTgfPpfASudPfdptdepSkA = zvTDQGflTtzrCKZQkcvYzgZRNcRDA
		});
	}
}
