using System;
using Rewired.Internal.Glyphs;
using Rewired.Internal.Localization;

internal abstract class gXqchDIZGQWPEuTfRZqVwuVjGBSx : pbjvuCPUSoxkvbSHfHZTgPpvxwgh
{
	protected KeyedGlyph[] XodCRTaVhYTrfXPbnUuHURZDCRlE;

	public int HIiBZYctWoZgNBaviXhYfHbCmJFt => AomZkhATSIadYOOLVfcgOnNtMQBs.YJjoDvcTlhdCNHOpHXbTafYtikvO(base.tIdaRtrQxBpAaRqDMtdzgOasMtbS, base.DWmOvpXkRirncHVFxpOYBhZtwkTF);

	public abstract object YzMDwLdFGfaLFbOWPBausmCwzitO(int P_0);

	public abstract string UjxZMpLtwXsaPbdwNRBLmDRYFbcAA(int P_0);

	protected gXqchDIZGQWPEuTfRZqVwuVjGBSx(AomZkhATSIadYOOLVfcgOnNtMQBs.fyQKArxdnRgBFXnCTGFifmqgwogRA P_0, AomZkhATSIadYOOLVfcgOnNtMQBs.OUxgQpuZIuwKyJEylNPLslOwBwNAA P_1)
		: base(P_0, P_1)
	{
	}

	protected gXqchDIZGQWPEuTfRZqVwuVjGBSx(jhzHtawhGfHVCurgBdqnjuHNyiNIA P_0, AomZkhATSIadYOOLVfcgOnNtMQBs.fyQKArxdnRgBFXnCTGFifmqgwogRA P_1, AomZkhATSIadYOOLVfcgOnNtMQBs.OUxgQpuZIuwKyJEylNPLslOwBwNAA P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
	}

	protected virtual void jJxvBqKPXAzPlUyYCNGlHJactSiT()
	{
		int num = HIiBZYctWoZgNBaviXhYfHbCmJFt;
		XodCRTaVhYTrfXPbnUuHURZDCRlE = null;
		if (num > 0)
		{
			XodCRTaVhYTrfXPbnUuHURZDCRlE = new KeyedGlyph[num];
			for (int i = 0; i < num; i++)
			{
				XodCRTaVhYTrfXPbnUuHURZDCRlE[i] = new KeyedGlyph();
			}
		}
		dqPufkNtsdJBdffJArJOKYbSmMGf();
	}

	public virtual void sdKifRHMythbznnnKIJvFUyBlLDKc(jhzHtawhGfHVCurgBdqnjuHNyiNIA P_0)
	{
		JBtKTUACafaihxMYlnsjoyoqpDOe(P_0);
	}

	public virtual void hUhlnaTDsrCtpxQAcsIcPqvDsrfH(AIHwxHYiZBEVvZOJUhghGWlTpYhGA P_0)
	{
		base.JBtKTUACafaihxMYlnsjoyoqpDOe(P_0);
		if (!(P_0 is jhzHtawhGfHVCurgBdqnjuHNyiNIA))
		{
			throw new ArgumentException("value must implement " + typeof(jhzHtawhGfHVCurgBdqnjuHNyiNIA));
		}
	}

	public virtual void blewaRFKcmYtikFShBbGFuciVPZdA()
	{
		ZoCHeHnRIrAoxPHaAmEFzxtsOYOV();
		if (XodCRTaVhYTrfXPbnUuHURZDCRlE != null)
		{
			for (int i = 0; i < HIiBZYctWoZgNBaviXhYfHbCmJFt; i++)
			{
				XodCRTaVhYTrfXPbnUuHURZDCRlE[i].Clear();
			}
		}
	}

	public virtual bool SfHJVWvQKOOENWkwcebXEAvcktM(QcAIbyiZKqNrYORSslhiNfzBOxmDb P_0)
	{
		if (!(P_0 is gXqchDIZGQWPEuTfRZqVwuVjGBSx gXqchDIZGQWPEuTfRZqVwuVjGBSx2))
		{
			return false;
		}
		if (!TIAiVbCYyzTQdXhCECOHioTpwDUfA(P_0))
		{
			return false;
		}
		jhzHtawhGfHVCurgBdqnjuHNyiNIA jhzHtawhGfHVCurgBdqnjuHNyiNIA2 = sSQuMwXbhNWwZRVpUcUkYMWkhdSG();
		jhzHtawhGfHVCurgBdqnjuHNyiNIA jhzHtawhGfHVCurgBdqnjuHNyiNIA3 = gXqchDIZGQWPEuTfRZqVwuVjGBSx2.sSQuMwXbhNWwZRVpUcUkYMWkhdSG();
		if (jhzHtawhGfHVCurgBdqnjuHNyiNIA2 == null != (jhzHtawhGfHVCurgBdqnjuHNyiNIA3 == null))
		{
			return false;
		}
		if (jhzHtawhGfHVCurgBdqnjuHNyiNIA2 != null)
		{
			int num = HIiBZYctWoZgNBaviXhYfHbCmJFt;
			for (int i = 0; i < num; i++)
			{
				if (!string.Equals(jhzHtawhGfHVCurgBdqnjuHNyiNIA2.GetSpecialElementKey(i), jhzHtawhGfHVCurgBdqnjuHNyiNIA3.GetSpecialElementKey(i), StringComparison.Ordinal))
				{
					return false;
				}
			}
		}
		return true;
	}

	protected virtual void woJDCCkhquLMsDOLgxUadERijuFPE()
	{
		zjUDmNYjmBmnckMdxBEGVIuiBzug();
		if (XodCRTaVhYTrfXPbnUuHURZDCRlE != null)
		{
			for (int i = 0; i < XodCRTaVhYTrfXPbnUuHURZDCRlE.Length; i++)
			{
				XodCRTaVhYTrfXPbnUuHURZDCRlE[i].Clear();
			}
		}
	}

	protected virtual void ixInqOMvkZGOtWoDtLlQWosAntiP(AomZkhATSIadYOOLVfcgOnNtMQBs.lZwSneskMjdcCDRCpckhVVEyJnLl P_0)
	{
		base.uKBBMrarohsnlrYzAMyPhEyiFeje(P_0);
		jhzHtawhGfHVCurgBdqnjuHNyiNIA jhzHtawhGfHVCurgBdqnjuHNyiNIA2 = sSQuMwXbhNWwZRVpUcUkYMWkhdSG();
		if (jhzHtawhGfHVCurgBdqnjuHNyiNIA2 == null || base.tIdaRtrQxBpAaRqDMtdzgOasMtbS != AomZkhATSIadYOOLVfcgOnNtMQBs.fyQKArxdnRgBFXnCTGFifmqgwogRA.CompoundElement || !AomZkhATSIadYOOLVfcgOnNtMQBs.kvsrEyzaoorJFgijytjCTPHeGAViA(base.DWmOvpXkRirncHVFxpOYBhZtwkTF, out var oNzOlLehqVXtXsHwkBQOBMVHFvXX))
		{
			return;
		}
		for (int i = 0; i < oNzOlLehqVXtXsHwkBQOBMVHFvXX.cuUGbCcfPKjlHPEsWJJjgyCNRxpzA; i++)
		{
			int num = 8388608 << i;
			if ((jhzHtawhGfHVCurgBdqnjuHNyiNIA2.autoGeneratedValueFlags & num) == 0 && !string.IsNullOrEmpty(jhzHtawhGfHVCurgBdqnjuHNyiNIA2.key) && string.IsNullOrEmpty(jhzHtawhGfHVCurgBdqnjuHNyiNIA2.GetSpecialElementKey(i)))
			{
				string text = jhzHtawhGfHVCurgBdqnjuHNyiNIA2.key;
				if (oNzOlLehqVXtXsHwkBQOBMVHFvXX.bnCCmDVASxNjXfAechLydAaZCcmeA(i).aRBhJlmnGWnqDuvJhLAszIYobqRJA.HasValue)
				{
					text = LocalizationManager.AppendToKeyAxisDirection(text, oNzOlLehqVXtXsHwkBQOBMVHFvXX.bnCCmDVASxNjXfAechLydAaZCcmeA(i).aRBhJlmnGWnqDuvJhLAszIYobqRJA.Value);
				}
				jhzHtawhGfHVCurgBdqnjuHNyiNIA2.SetSpecialElementKey(i, text);
				jhzHtawhGfHVCurgBdqnjuHNyiNIA2.autoGeneratedValueFlags |= num;
				PfffRuGSBVHZeTueHdEAfaiDfBjW(num);
			}
		}
	}

	protected virtual void PHnZoNbIiPaHoXUSqDXgkfLzYTDO(AomZkhATSIadYOOLVfcgOnNtMQBs.FzqQtDWakuZFTntlWNdHXCvRdaki P_0)
	{
		base.mpZGqZhYVhjEivhDnHYgBewfPbgvA(P_0);
		jhzHtawhGfHVCurgBdqnjuHNyiNIA jhzHtawhGfHVCurgBdqnjuHNyiNIA2 = sSQuMwXbhNWwZRVpUcUkYMWkhdSG();
		if (jhzHtawhGfHVCurgBdqnjuHNyiNIA2 == null || ((uint)jhzHtawhGfHVCurgBdqnjuHNyiNIA2.autoGeneratedValueFlags & (uint)P_0) == 0 || base.tIdaRtrQxBpAaRqDMtdzgOasMtbS != AomZkhATSIadYOOLVfcgOnNtMQBs.fyQKArxdnRgBFXnCTGFifmqgwogRA.CompoundElement || !AomZkhATSIadYOOLVfcgOnNtMQBs.kvsrEyzaoorJFgijytjCTPHeGAViA(base.DWmOvpXkRirncHVFxpOYBhZtwkTF, out var oNzOlLehqVXtXsHwkBQOBMVHFvXX))
		{
			return;
		}
		for (int i = 0; i < oNzOlLehqVXtXsHwkBQOBMVHFvXX.cuUGbCcfPKjlHPEsWJJjgyCNRxpzA; i++)
		{
			int num = 8388608 << i;
			if ((jhzHtawhGfHVCurgBdqnjuHNyiNIA2.autoGeneratedValueFlags & num) != 0)
			{
				jhzHtawhGfHVCurgBdqnjuHNyiNIA2.SetSpecialElementKey(i, null);
				jhzHtawhGfHVCurgBdqnjuHNyiNIA2.autoGeneratedValueFlags &= ~num;
				PfffRuGSBVHZeTueHdEAfaiDfBjW(num);
			}
		}
	}

	protected virtual AomZkhATSIadYOOLVfcgOnNtMQBs.FzqQtDWakuZFTntlWNdHXCvRdaki aBZnsmscBiPIAgEdAPmtdbouTQgB(AomZkhATSIadYOOLVfcgOnNtMQBs.lZwSneskMjdcCDRCpckhVVEyJnLl P_0)
	{
		AomZkhATSIadYOOLVfcgOnNtMQBs.FzqQtDWakuZFTntlWNdHXCvRdaki fzqQtDWakuZFTntlWNdHXCvRdaki = base.DtmfITCNSilmrzrCzbHAdubYCPAyA(P_0);
		int num = HIiBZYctWoZgNBaviXhYfHbCmJFt;
		if ((P_0 & AomZkhATSIadYOOLVfcgOnNtMQBs.lZwSneskMjdcCDRCpckhVVEyJnLl.Keys) != AomZkhATSIadYOOLVfcgOnNtMQBs.lZwSneskMjdcCDRCpckhVVEyJnLl.None)
		{
			for (int i = 0; i < num; i++)
			{
				fzqQtDWakuZFTntlWNdHXCvRdaki = (AomZkhATSIadYOOLVfcgOnNtMQBs.FzqQtDWakuZFTntlWNdHXCvRdaki)((int)fzqQtDWakuZFTntlWNdHXCvRdaki | (8388608 << i));
			}
		}
		return fzqQtDWakuZFTntlWNdHXCvRdaki;
	}

	protected jhzHtawhGfHVCurgBdqnjuHNyiNIA sSQuMwXbhNWwZRVpUcUkYMWkhdSG()
	{
		return rwuWfypFyCRXrrqMgjBCxLhqsyKs() as jhzHtawhGfHVCurgBdqnjuHNyiNIA;
	}

	protected virtual void hHwpAZDmkTcdQnwPisOxfWuiAFEf()
	{
		base.gwPRnOZcHdIDjrpMDbeRVuCDFsCcA();
		int num = HIiBZYctWoZgNBaviXhYfHbCmJFt;
		for (int i = 0; i < num; i++)
		{
			YzMDwLdFGfaLFbOWPBausmCwzitO(i);
		}
	}

	protected virtual void mPuIBsQRmAOIuAyzuOnEzgPrVsWg()
	{
		UzXmnwmdugOvcxMPIVxVAEXxSuCG();
	}
}
