using System;
using Rewired.Internal.Localization;

internal class OoMOZEqfXndBIZKQcgmHDZDrhUwEA : gDrCmzJNXwFvGTMAYKGQspUqeYD
{
	protected readonly AomZkhATSIadYOOLVfcgOnNtMQBs cjQPccnIYmSeKouGbcODBVBCOzvT;

	private readonly string JrsvlSVekgWnsqofWgIElwIBbkcw;

	private readonly string IESEnoclSffblaIcZezOPpCscHnW;

	private string UfpfOkQXQEoHepleJZRmOICETMbs;

	private readonly string ZnHMlntRGanYWWqtfMdTJaYhEVQZ;

	private int IQrbKTwWhUcCfkfGJrQdLvjsheSbb;

	public AomZkhATSIadYOOLVfcgOnNtMQBs JLFYlpbldhaAwtjOCdSYZmwoESgjA => cjQPccnIYmSeKouGbcODBVBCOzvT;

	string gDrCmzJNXwFvGTMAYKGQspUqeYD.keyCategory => JrsvlSVekgWnsqofWgIElwIBbkcw;

	string gDrCmzJNXwFvGTMAYKGQspUqeYD.scriptingName => IESEnoclSffblaIcZezOPpCscHnW;

	string gDrCmzJNXwFvGTMAYKGQspUqeYD.nonLocalizedDescriptiveName
	{
		get
		{
			return UfpfOkQXQEoHepleJZRmOICETMbs;
		}
		set
		{
			UfpfOkQXQEoHepleJZRmOICETMbs = value;
		}
	}

	string gDrCmzJNXwFvGTMAYKGQspUqeYD.key => ZnHMlntRGanYWWqtfMdTJaYhEVQZ;

	int gDrCmzJNXwFvGTMAYKGQspUqeYD.autoGeneratedValueFlags
	{
		get
		{
			return IQrbKTwWhUcCfkfGJrQdLvjsheSbb;
		}
		set
		{
			IQrbKTwWhUcCfkfGJrQdLvjsheSbb = value;
		}
	}

	public string keyCategory => JrsvlSVekgWnsqofWgIElwIBbkcw;

	public string scriptingName => IESEnoclSffblaIcZezOPpCscHnW;

	public string aVVdhXOnPqdAnZNJpkXLKIdxbTax
	{
		get
		{
			if (!LocalizationManager.isEnabled)
			{
				return UfpfOkQXQEoHepleJZRmOICETMbs;
			}
			return cjQPccnIYmSeKouGbcODBVBCOzvT.LoGZqdROKyuYHJXdnhuxPciDQjeL;
		}
	}

	public string nonLocalizedDescriptiveName => UfpfOkQXQEoHepleJZRmOICETMbs;

	public string key => ZnHMlntRGanYWWqtfMdTJaYhEVQZ;

	public OoMOZEqfXndBIZKQcgmHDZDrhUwEA(AomZkhATSIadYOOLVfcgOnNtMQBs P_0, string P_1, string P_2, string P_3, string P_4)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException();
		}
		cjQPccnIYmSeKouGbcODBVBCOzvT = P_0;
		JrsvlSVekgWnsqofWgIElwIBbkcw = P_1;
		IESEnoclSffblaIcZezOPpCscHnW = P_2;
		UfpfOkQXQEoHepleJZRmOICETMbs = P_3;
		ZnHMlntRGanYWWqtfMdTJaYhEVQZ = P_4;
		P_0.GDNPdTRkvkcYBsFVTOaYnLSpXXKh(this);
	}

	public virtual bool ONNbteXxuydDDSwvcgYKyVMQOdPh(OoMOZEqfXndBIZKQcgmHDZDrhUwEA P_0, bool P_1)
	{
		if (P_0 == null)
		{
			return false;
		}
		if ((object)GetType() != P_0.GetType())
		{
			return false;
		}
		if (!cjQPccnIYmSeKouGbcODBVBCOzvT.QlMvYOrrkGobkvjoAMgNaIOEePwJA(P_0.cjQPccnIYmSeKouGbcODBVBCOzvT, P_1))
		{
			return false;
		}
		return true;
	}
}
