using System;
using Rewired;
using Rewired.Internal.Glyphs;
using Rewired.Internal.Localization;

internal abstract class sixVYViftOYZHgQrzKrknyxUhrs : pbjvuCPUSoxkvbSHfHZTgPpvxwgh
{
	protected readonly KeyedGlyph nllbCfpNrdLdIlagysQgoEfWbYq;

	protected readonly KeyedGlyph uwycZIsrzZFKQJFYyyIeqDqNEpMcA;

	public abstract object rDFxUatMbooeegVqsbQAmfdclvkb { get; }

	public abstract object virtdIFyIFsRliRxpxDCRdeEbxUd { get; }

	public abstract string NomOvFfGNzjocpHXgQVkYuGuWtOf { get; }

	public abstract string KNuOvihbENmAquPLvjhhiXUexGHEA { get; }

	protected sixVYViftOYZHgQrzKrknyxUhrs(AomZkhATSIadYOOLVfcgOnNtMQBs.fyQKArxdnRgBFXnCTGFifmqgwogRA P_0, AomZkhATSIadYOOLVfcgOnNtMQBs.OUxgQpuZIuwKyJEylNPLslOwBwNAA P_1)
		: base(P_0, P_1)
	{
		nllbCfpNrdLdIlagysQgoEfWbYq = new KeyedGlyph();
		uwycZIsrzZFKQJFYyyIeqDqNEpMcA = new KeyedGlyph();
	}

	protected sixVYViftOYZHgQrzKrknyxUhrs(sLizqcvxoCawnuvvDbUZJbhvIfejA P_0, AomZkhATSIadYOOLVfcgOnNtMQBs.fyQKArxdnRgBFXnCTGFifmqgwogRA P_1, AomZkhATSIadYOOLVfcgOnNtMQBs.OUxgQpuZIuwKyJEylNPLslOwBwNAA P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
		nllbCfpNrdLdIlagysQgoEfWbYq = new KeyedGlyph();
		uwycZIsrzZFKQJFYyyIeqDqNEpMcA = new KeyedGlyph();
	}

	protected virtual void tLOpmFraxXaPIlsIUHMbXHAGqtYS()
	{
		dqPufkNtsdJBdffJArJOKYbSmMGf();
	}

	public virtual void hcagmSYWGwRpLGrexQWFnefstrKk(sLizqcvxoCawnuvvDbUZJbhvIfejA P_0)
	{
		JBtKTUACafaihxMYlnsjoyoqpDOe(P_0);
	}

	public virtual void zNbtpBWMqEbdpHMmpuSadJcYlxMz(AIHwxHYiZBEVvZOJUhghGWlTpYhGA P_0)
	{
		base.JBtKTUACafaihxMYlnsjoyoqpDOe(P_0);
		if (!(P_0 is sLizqcvxoCawnuvvDbUZJbhvIfejA))
		{
			throw new ArgumentException("value must implement " + typeof(sLizqcvxoCawnuvvDbUZJbhvIfejA));
		}
	}

	public virtual void lGBFDyFpaUUOtUfNndhrEiXJzAbab()
	{
		ZoCHeHnRIrAoxPHaAmEFzxtsOYOV();
		nllbCfpNrdLdIlagysQgoEfWbYq.Clear();
		uwycZIsrzZFKQJFYyyIeqDqNEpMcA.Clear();
	}

	public void xgKGYnpHDimXDyRwDBBPZxvZwauk()
	{
		nllbCfpNrdLdIlagysQgoEfWbYq.Clear();
		uKBBMrarohsnlrYzAMyPhEyiFeje(AomZkhATSIadYOOLVfcgOnNtMQBs.lZwSneskMjdcCDRCpckhVVEyJnLl.Keys);
	}

	public void ofZEMbjCrOsRbPZZUBJtDLWKVXFLA()
	{
		uwycZIsrzZFKQJFYyyIeqDqNEpMcA.Clear();
		uKBBMrarohsnlrYzAMyPhEyiFeje(AomZkhATSIadYOOLVfcgOnNtMQBs.lZwSneskMjdcCDRCpckhVVEyJnLl.Keys);
	}

	public virtual bool VHbGsEENNIKIDnwXrwpWBwVueaSEA(QcAIbyiZKqNrYORSslhiNfzBOxmDb P_0)
	{
		if (!(P_0 is sixVYViftOYZHgQrzKrknyxUhrs sixVYViftOYZHgQrzKrknyxUhrs2))
		{
			return false;
		}
		if (!TIAiVbCYyzTQdXhCECOHioTpwDUfA(P_0))
		{
			return false;
		}
		sLizqcvxoCawnuvvDbUZJbhvIfejA sLizqcvxoCawnuvvDbUZJbhvIfejA2 = PPnPjnLDSRoWuiwsBeUowAuFJBUb();
		sLizqcvxoCawnuvvDbUZJbhvIfejA sLizqcvxoCawnuvvDbUZJbhvIfejA3 = sixVYViftOYZHgQrzKrknyxUhrs2.PPnPjnLDSRoWuiwsBeUowAuFJBUb();
		if (sLizqcvxoCawnuvvDbUZJbhvIfejA2 == null != (sLizqcvxoCawnuvvDbUZJbhvIfejA3 == null))
		{
			return false;
		}
		if (sLizqcvxoCawnuvvDbUZJbhvIfejA2 != null && (!string.Equals(sLizqcvxoCawnuvvDbUZJbhvIfejA2.positiveKey, sLizqcvxoCawnuvvDbUZJbhvIfejA3.positiveKey, StringComparison.Ordinal) || !string.Equals(sLizqcvxoCawnuvvDbUZJbhvIfejA2.negativeKey, sLizqcvxoCawnuvvDbUZJbhvIfejA3.negativeKey, StringComparison.Ordinal)))
		{
			return false;
		}
		return true;
	}

	protected virtual void OrLfLMjUgelsOSMRjFUZVEQuJXBs()
	{
		zjUDmNYjmBmnckMdxBEGVIuiBzug();
		nllbCfpNrdLdIlagysQgoEfWbYq.Clear();
		uwycZIsrzZFKQJFYyyIeqDqNEpMcA.Clear();
	}

	protected virtual void iUUrChdfsqpiWSGyCCjuhgUyOPRwA(AomZkhATSIadYOOLVfcgOnNtMQBs.lZwSneskMjdcCDRCpckhVVEyJnLl P_0)
	{
		base.uKBBMrarohsnlrYzAMyPhEyiFeje(P_0);
		sLizqcvxoCawnuvvDbUZJbhvIfejA sLizqcvxoCawnuvvDbUZJbhvIfejA2 = PPnPjnLDSRoWuiwsBeUowAuFJBUb();
		if (sLizqcvxoCawnuvvDbUZJbhvIfejA2 == null || string.IsNullOrEmpty(sLizqcvxoCawnuvvDbUZJbhvIfejA2.key))
		{
			return;
		}
		if ((sLizqcvxoCawnuvvDbUZJbhvIfejA2.autoGeneratedValueFlags & 8) == 0 && string.IsNullOrEmpty(sLizqcvxoCawnuvvDbUZJbhvIfejA2.positiveKey) && mQeHlINZpSpGpcdvhLKCijVaxvlQ(Pole.Positive))
		{
			sLizqcvxoCawnuvvDbUZJbhvIfejA2.positiveKey = sLizqcvxoCawnuvvDbUZJbhvIfejA2.key;
			if (QgFsUtfHbvRzISASGrSYNyvOFnfe(Pole.Positive))
			{
				sLizqcvxoCawnuvvDbUZJbhvIfejA2.positiveKey = LocalizationManager.AppendToKeyAxisPole(sLizqcvxoCawnuvvDbUZJbhvIfejA2.positiveKey, Pole.Positive);
			}
			sLizqcvxoCawnuvvDbUZJbhvIfejA2.autoGeneratedValueFlags |= 8;
			PfffRuGSBVHZeTueHdEAfaiDfBjW(8);
		}
		if ((sLizqcvxoCawnuvvDbUZJbhvIfejA2.autoGeneratedValueFlags & 0x10) == 0 && string.IsNullOrEmpty(sLizqcvxoCawnuvvDbUZJbhvIfejA2.negativeKey) && mQeHlINZpSpGpcdvhLKCijVaxvlQ(Pole.Negative))
		{
			sLizqcvxoCawnuvvDbUZJbhvIfejA2.negativeKey = sLizqcvxoCawnuvvDbUZJbhvIfejA2.key;
			if (QgFsUtfHbvRzISASGrSYNyvOFnfe(Pole.Negative))
			{
				sLizqcvxoCawnuvvDbUZJbhvIfejA2.negativeKey = LocalizationManager.AppendToKeyAxisPole(sLizqcvxoCawnuvvDbUZJbhvIfejA2.negativeKey, Pole.Negative);
			}
			sLizqcvxoCawnuvvDbUZJbhvIfejA2.autoGeneratedValueFlags |= 16;
			PfffRuGSBVHZeTueHdEAfaiDfBjW(16);
		}
	}

	protected virtual void OzGbdzeGUUaitMYNguiSftZwdDwTA(AomZkhATSIadYOOLVfcgOnNtMQBs.FzqQtDWakuZFTntlWNdHXCvRdaki P_0)
	{
		base.mpZGqZhYVhjEivhDnHYgBewfPbgvA(P_0);
		sLizqcvxoCawnuvvDbUZJbhvIfejA sLizqcvxoCawnuvvDbUZJbhvIfejA2 = PPnPjnLDSRoWuiwsBeUowAuFJBUb();
		if (sLizqcvxoCawnuvvDbUZJbhvIfejA2 != null && ((uint)sLizqcvxoCawnuvvDbUZJbhvIfejA2.autoGeneratedValueFlags & (uint)P_0) != 0)
		{
			if ((P_0 & AomZkhATSIadYOOLVfcgOnNtMQBs.FzqQtDWakuZFTntlWNdHXCvRdaki.PositiveKey) != AomZkhATSIadYOOLVfcgOnNtMQBs.FzqQtDWakuZFTntlWNdHXCvRdaki.None && (sLizqcvxoCawnuvvDbUZJbhvIfejA2.autoGeneratedValueFlags & 8) != 0)
			{
				sLizqcvxoCawnuvvDbUZJbhvIfejA2.positiveKey = null;
				PfffRuGSBVHZeTueHdEAfaiDfBjW(8);
				sLizqcvxoCawnuvvDbUZJbhvIfejA2.autoGeneratedValueFlags &= -9;
			}
			if ((P_0 & AomZkhATSIadYOOLVfcgOnNtMQBs.FzqQtDWakuZFTntlWNdHXCvRdaki.NegativeKey) != AomZkhATSIadYOOLVfcgOnNtMQBs.FzqQtDWakuZFTntlWNdHXCvRdaki.None && (sLizqcvxoCawnuvvDbUZJbhvIfejA2.autoGeneratedValueFlags & 0x10) != 0)
			{
				sLizqcvxoCawnuvvDbUZJbhvIfejA2.negativeKey = null;
				PfffRuGSBVHZeTueHdEAfaiDfBjW(16);
				sLizqcvxoCawnuvvDbUZJbhvIfejA2.autoGeneratedValueFlags &= -17;
			}
		}
	}

	protected virtual AomZkhATSIadYOOLVfcgOnNtMQBs.FzqQtDWakuZFTntlWNdHXCvRdaki lJxCbuEbPCdrwQMXPDQusCxFsiRV(AomZkhATSIadYOOLVfcgOnNtMQBs.lZwSneskMjdcCDRCpckhVVEyJnLl P_0)
	{
		AomZkhATSIadYOOLVfcgOnNtMQBs.FzqQtDWakuZFTntlWNdHXCvRdaki fzqQtDWakuZFTntlWNdHXCvRdaki = base.DtmfITCNSilmrzrCzbHAdubYCPAyA(P_0);
		if ((P_0 & AomZkhATSIadYOOLVfcgOnNtMQBs.lZwSneskMjdcCDRCpckhVVEyJnLl.Keys) != AomZkhATSIadYOOLVfcgOnNtMQBs.lZwSneskMjdcCDRCpckhVVEyJnLl.None)
		{
			fzqQtDWakuZFTntlWNdHXCvRdaki |= (AomZkhATSIadYOOLVfcgOnNtMQBs.FzqQtDWakuZFTntlWNdHXCvRdaki)24;
		}
		return fzqQtDWakuZFTntlWNdHXCvRdaki;
	}

	protected sLizqcvxoCawnuvvDbUZJbhvIfejA PPnPjnLDSRoWuiwsBeUowAuFJBUb()
	{
		return rwuWfypFyCRXrrqMgjBCxLhqsyKs() as sLizqcvxoCawnuvvDbUZJbhvIfejA;
	}

	protected virtual bool QgFsUtfHbvRzISASGrSYNyvOFnfe(Pole P_0)
	{
		return base.tIdaRtrQxBpAaRqDMtdzgOasMtbS switch
		{
			AomZkhATSIadYOOLVfcgOnNtMQBs.fyQKArxdnRgBFXnCTGFifmqgwogRA.Axis => true, 
			AomZkhATSIadYOOLVfcgOnNtMQBs.fyQKArxdnRgBFXnCTGFifmqgwogRA.Button => false, 
			_ => false, 
		};
	}

	protected virtual bool mQeHlINZpSpGpcdvhLKCijVaxvlQ(Pole P_0)
	{
		return base.tIdaRtrQxBpAaRqDMtdzgOasMtbS switch
		{
			AomZkhATSIadYOOLVfcgOnNtMQBs.fyQKArxdnRgBFXnCTGFifmqgwogRA.Axis => true, 
			AomZkhATSIadYOOLVfcgOnNtMQBs.fyQKArxdnRgBFXnCTGFifmqgwogRA.Button => P_0 switch
			{
				Pole.Positive => true, 
				Pole.Negative => false, 
				_ => false, 
			}, 
			_ => false, 
		};
	}

	protected virtual void UhlKjqlJWVwHwtOatZVoZoWmcAOA()
	{
		base.gwPRnOZcHdIDjrpMDbeRVuCDFsCcA();
		_ = rDFxUatMbooeegVqsbQAmfdclvkb;
		_ = virtdIFyIFsRliRxpxDCRdeEbxUd;
	}

	protected virtual void dAamsWyFudScGONneEMxefYWfWvK()
	{
		UzXmnwmdugOvcxMPIVxVAEXxSuCG();
		ifDFbrYaRPQixSjSvfqZeDdmXSyFA(8, new KGqiNNbccNiMxnrDiZaeNlmjIUxHA
		{
			koFjeYvFWOCoiuKRXGKIvVrMbrPb = nllbCfpNrdLdIlagysQgoEfWbYq
		});
		ifDFbrYaRPQixSjSvfqZeDdmXSyFA(16, new KGqiNNbccNiMxnrDiZaeNlmjIUxHA
		{
			koFjeYvFWOCoiuKRXGKIvVrMbrPb = uwycZIsrzZFKQJFYyyIeqDqNEpMcA
		});
	}
}
