using System;
using Rewired.Internal.Localization;

internal abstract class vRxehaImOeJEYZjAHzcTdGbMbGst : AomZkhATSIadYOOLVfcgOnNtMQBs
{
	protected LocalizedString[] uZMktLKxVFgShqfHbKijMdtBCikg;

	public int PigQuqwlngXbAqDDYmfGLgmLqCnh => AomZkhATSIadYOOLVfcgOnNtMQBs.YJjoDvcTlhdCNHOpHXbTafYtikvO(base.sIxvbdiJJXGTPKMdgswAQFCeVOyI, base.oAneKvBTUlXClxNArblEZzfmJYEU);

	public abstract string VxSCVyObxksuNRtHTByuEmCYzwLj(int P_0);

	protected vRxehaImOeJEYZjAHzcTdGbMbGst(fyQKArxdnRgBFXnCTGFifmqgwogRA P_0, OUxgQpuZIuwKyJEylNPLslOwBwNAA P_1)
		: base(P_0, P_1)
	{
	}

	protected vRxehaImOeJEYZjAHzcTdGbMbGst(wOcwbdLCJaOhasRXtoPQFUPfsCvq P_0, fyQKArxdnRgBFXnCTGFifmqgwogRA P_1, OUxgQpuZIuwKyJEylNPLslOwBwNAA P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
	}

	protected virtual void gRCMyEbcSabjeyImHyTgrWmyigxC()
	{
		int num = PigQuqwlngXbAqDDYmfGLgmLqCnh;
		uZMktLKxVFgShqfHbKijMdtBCikg = null;
		if (num > 0)
		{
			uZMktLKxVFgShqfHbKijMdtBCikg = new LocalizedString[num];
			for (int i = 0; i < num; i++)
			{
				uZMktLKxVFgShqfHbKijMdtBCikg[i] = new LocalizedString();
			}
		}
		LkQRPNtLZxlSRESaPGkQjrNILfSL();
	}

	public virtual void aBZzdoEtrDHqKVUaUxnzmVWatlkJ(wOcwbdLCJaOhasRXtoPQFUPfsCvq P_0)
	{
		GDNPdTRkvkcYBsFVTOaYnLSpXXKh(P_0);
	}

	public virtual void nVBcheBKmikNdQlCsflchqFVxTMHA(gDrCmzJNXwFvGTMAYKGQspUqeYD P_0)
	{
		base.GDNPdTRkvkcYBsFVTOaYnLSpXXKh(P_0);
		if (!(P_0 is wOcwbdLCJaOhasRXtoPQFUPfsCvq))
		{
			throw new ArgumentException("value must implement " + typeof(wOcwbdLCJaOhasRXtoPQFUPfsCvq));
		}
	}

	public virtual void FHetBwviMKHNcTMCiQnwaHkkBRGl()
	{
		TDKmJIWOjsfmrjGxkDYGHhJupxzKA();
	}

	public virtual void wQydXnFCAYcGvbqkesKUOMZYjluMc()
	{
		lhdOvYLoqhTkAKWLCfmALaqDPClT();
		if (uZMktLKxVFgShqfHbKijMdtBCikg != null)
		{
			for (int i = 0; i < PigQuqwlngXbAqDDYmfGLgmLqCnh; i++)
			{
				uZMktLKxVFgShqfHbKijMdtBCikg[i].Clear();
			}
		}
	}

	public virtual bool cBDzOknBMPEjCbibXDhLHmNFzPEnb(CrEdIhdRuEefdCHiQoLwiMECdkdvB P_0, bool P_1)
	{
		if (!(P_0 is vRxehaImOeJEYZjAHzcTdGbMbGst vRxehaImOeJEYZjAHzcTdGbMbGst2))
		{
			return false;
		}
		if (!AztKGIvbswaZWeSHBhgTxTXCcKLB(P_0, P_1))
		{
			return false;
		}
		wOcwbdLCJaOhasRXtoPQFUPfsCvq wOcwbdLCJaOhasRXtoPQFUPfsCvq2 = SziVqzkKQDCUaxwYTXWeECXAhhkz();
		wOcwbdLCJaOhasRXtoPQFUPfsCvq wOcwbdLCJaOhasRXtoPQFUPfsCvq3 = vRxehaImOeJEYZjAHzcTdGbMbGst2.SziVqzkKQDCUaxwYTXWeECXAhhkz();
		if (wOcwbdLCJaOhasRXtoPQFUPfsCvq2 == null != (wOcwbdLCJaOhasRXtoPQFUPfsCvq3 == null))
		{
			return false;
		}
		if (wOcwbdLCJaOhasRXtoPQFUPfsCvq2 != null && P_1)
		{
			int num = PigQuqwlngXbAqDDYmfGLgmLqCnh;
			for (int i = 0; i < num; i++)
			{
				if (!string.Equals(wOcwbdLCJaOhasRXtoPQFUPfsCvq2.GetSpecialElementKey(i), wOcwbdLCJaOhasRXtoPQFUPfsCvq3.GetSpecialElementKey(i), StringComparison.Ordinal))
				{
					return false;
				}
				if (!string.Equals(wOcwbdLCJaOhasRXtoPQFUPfsCvq2.GetSpecialElementNonLocalizedDescriptiveName(i), wOcwbdLCJaOhasRXtoPQFUPfsCvq3.GetSpecialElementNonLocalizedDescriptiveName(i), StringComparison.Ordinal))
				{
					return false;
				}
			}
		}
		return true;
	}

	protected virtual void SbPRClURPPfEssUlNkOyXbrONSTx()
	{
		rGEIdssYVmaHobuMTZpfrtsIoPZC();
		if (uZMktLKxVFgShqfHbKijMdtBCikg != null)
		{
			for (int i = 0; i < uZMktLKxVFgShqfHbKijMdtBCikg.Length; i++)
			{
				uZMktLKxVFgShqfHbKijMdtBCikg[i].Clear();
			}
		}
	}

	protected virtual void XZfpbQMQljWigyENGhxUiyrVatyU(lZwSneskMjdcCDRCpckhVVEyJnLl P_0)
	{
		base.idImOmuzvdGLOotALUOanCfXIOuS(P_0);
		wOcwbdLCJaOhasRXtoPQFUPfsCvq wOcwbdLCJaOhasRXtoPQFUPfsCvq2 = SziVqzkKQDCUaxwYTXWeECXAhhkz();
		if (wOcwbdLCJaOhasRXtoPQFUPfsCvq2 == null || string.IsNullOrEmpty(wOcwbdLCJaOhasRXtoPQFUPfsCvq2.key) || base.sIxvbdiJJXGTPKMdgswAQFCeVOyI != fyQKArxdnRgBFXnCTGFifmqgwogRA.CompoundElement || !AomZkhATSIadYOOLVfcgOnNtMQBs.kvsrEyzaoorJFgijytjCTPHeGAViA(base.oAneKvBTUlXClxNArblEZzfmJYEU, out var oNzOlLehqVXtXsHwkBQOBMVHFvXX))
		{
			return;
		}
		for (int i = 0; i < oNzOlLehqVXtXsHwkBQOBMVHFvXX.cuUGbCcfPKjlHPEsWJJjgyCNRxpzA; i++)
		{
			int num = 8388608 << i;
			if ((wOcwbdLCJaOhasRXtoPQFUPfsCvq2.autoGeneratedValueFlags & num) == 0 && !string.IsNullOrEmpty(wOcwbdLCJaOhasRXtoPQFUPfsCvq2.key) && string.IsNullOrEmpty(wOcwbdLCJaOhasRXtoPQFUPfsCvq2.GetSpecialElementKey(i)))
			{
				string text = wOcwbdLCJaOhasRXtoPQFUPfsCvq2.key;
				if (oNzOlLehqVXtXsHwkBQOBMVHFvXX.bnCCmDVASxNjXfAechLydAaZCcmeA(i).aRBhJlmnGWnqDuvJhLAszIYobqRJA.HasValue)
				{
					text = LocalizationManager.AppendToKeyAxisDirection(text, oNzOlLehqVXtXsHwkBQOBMVHFvXX.bnCCmDVASxNjXfAechLydAaZCcmeA(i).aRBhJlmnGWnqDuvJhLAszIYobqRJA.Value);
				}
				wOcwbdLCJaOhasRXtoPQFUPfsCvq2.SetSpecialElementKey(i, text);
				wOcwbdLCJaOhasRXtoPQFUPfsCvq2.autoGeneratedValueFlags |= num;
				ZHfrtfTBXdLnGOfNRdLnBGkKHMRQ(num);
			}
			int num2 = 16384 << i;
			if ((wOcwbdLCJaOhasRXtoPQFUPfsCvq2.autoGeneratedValueFlags & num2) == 0 && !string.IsNullOrEmpty(wOcwbdLCJaOhasRXtoPQFUPfsCvq2.nonLocalizedDescriptiveName) && string.IsNullOrEmpty(wOcwbdLCJaOhasRXtoPQFUPfsCvq2.GetSpecialElementNonLocalizedDescriptiveName(i)))
			{
				string text2 = wOcwbdLCJaOhasRXtoPQFUPfsCvq2.nonLocalizedDescriptiveName;
				if (oNzOlLehqVXtXsHwkBQOBMVHFvXX.bnCCmDVASxNjXfAechLydAaZCcmeA(i).aRBhJlmnGWnqDuvJhLAszIYobqRJA.HasValue)
				{
					text2 = LocalizationManager.AppendToNameAxisDirection(text2, oNzOlLehqVXtXsHwkBQOBMVHFvXX.bnCCmDVASxNjXfAechLydAaZCcmeA(i).aRBhJlmnGWnqDuvJhLAszIYobqRJA.Value);
				}
				wOcwbdLCJaOhasRXtoPQFUPfsCvq2.SetSpecialElementNonLocalizedDescriptiveName(i, text2);
				wOcwbdLCJaOhasRXtoPQFUPfsCvq2.autoGeneratedValueFlags |= num2;
				ZHfrtfTBXdLnGOfNRdLnBGkKHMRQ(num2);
			}
		}
	}

	protected virtual void zDeEYFgbaHyNdOOTvJhmkICLAJcxA(FzqQtDWakuZFTntlWNdHXCvRdaki P_0)
	{
		base.HpPYiVrcZlpqpRSiAtDWiaBwavJF(P_0);
		wOcwbdLCJaOhasRXtoPQFUPfsCvq wOcwbdLCJaOhasRXtoPQFUPfsCvq2 = SziVqzkKQDCUaxwYTXWeECXAhhkz();
		if (wOcwbdLCJaOhasRXtoPQFUPfsCvq2 == null || ((uint)wOcwbdLCJaOhasRXtoPQFUPfsCvq2.autoGeneratedValueFlags & (uint)P_0) == 0 || base.sIxvbdiJJXGTPKMdgswAQFCeVOyI != fyQKArxdnRgBFXnCTGFifmqgwogRA.CompoundElement || !AomZkhATSIadYOOLVfcgOnNtMQBs.kvsrEyzaoorJFgijytjCTPHeGAViA(base.oAneKvBTUlXClxNArblEZzfmJYEU, out var oNzOlLehqVXtXsHwkBQOBMVHFvXX))
		{
			return;
		}
		for (int i = 0; i < oNzOlLehqVXtXsHwkBQOBMVHFvXX.cuUGbCcfPKjlHPEsWJJjgyCNRxpzA; i++)
		{
			int num = 8388608 << i;
			if ((wOcwbdLCJaOhasRXtoPQFUPfsCvq2.autoGeneratedValueFlags & num) != 0)
			{
				wOcwbdLCJaOhasRXtoPQFUPfsCvq2.SetSpecialElementKey(i, null);
				wOcwbdLCJaOhasRXtoPQFUPfsCvq2.autoGeneratedValueFlags &= ~num;
				ZHfrtfTBXdLnGOfNRdLnBGkKHMRQ(num);
			}
			int num2 = 16384 << i;
			if ((wOcwbdLCJaOhasRXtoPQFUPfsCvq2.autoGeneratedValueFlags & num2) != 0)
			{
				wOcwbdLCJaOhasRXtoPQFUPfsCvq2.SetSpecialElementNonLocalizedDescriptiveName(i, null);
				wOcwbdLCJaOhasRXtoPQFUPfsCvq2.autoGeneratedValueFlags &= ~num2;
				ZHfrtfTBXdLnGOfNRdLnBGkKHMRQ(num2);
			}
		}
	}

	protected virtual FzqQtDWakuZFTntlWNdHXCvRdaki JYmkoBPYsCOrbFCfUcCVjNNJocup(lZwSneskMjdcCDRCpckhVVEyJnLl P_0)
	{
		FzqQtDWakuZFTntlWNdHXCvRdaki fzqQtDWakuZFTntlWNdHXCvRdaki = base.TMcNPOZjXahkaxuEqKMUWpjQbXCu(P_0);
		int num = PigQuqwlngXbAqDDYmfGLgmLqCnh;
		if ((P_0 & lZwSneskMjdcCDRCpckhVVEyJnLl.Keys) != lZwSneskMjdcCDRCpckhVVEyJnLl.None)
		{
			for (int i = 0; i < num; i++)
			{
				fzqQtDWakuZFTntlWNdHXCvRdaki = (FzqQtDWakuZFTntlWNdHXCvRdaki)((int)fzqQtDWakuZFTntlWNdHXCvRdaki | (8388608 << i));
			}
		}
		if ((P_0 & lZwSneskMjdcCDRCpckhVVEyJnLl.Names) != lZwSneskMjdcCDRCpckhVVEyJnLl.None)
		{
			for (int j = 0; j < num; j++)
			{
				fzqQtDWakuZFTntlWNdHXCvRdaki = (FzqQtDWakuZFTntlWNdHXCvRdaki)((int)fzqQtDWakuZFTntlWNdHXCvRdaki | (16384 << j));
			}
		}
		return fzqQtDWakuZFTntlWNdHXCvRdaki;
	}

	protected wOcwbdLCJaOhasRXtoPQFUPfsCvq SziVqzkKQDCUaxwYTXWeECXAhhkz()
	{
		return qUiJUHBRFEvMwwcmkRXSpLZcYrJm() as wOcwbdLCJaOhasRXtoPQFUPfsCvq;
	}

	protected virtual void kUyfBohdhnBNHXSCFDuOMLwekcRab()
	{
		base.fsJzDjYGZNEsXoOdrgfUlDksvlUG();
		int num = PigQuqwlngXbAqDDYmfGLgmLqCnh;
		for (int i = 0; i < num; i++)
		{
			VxSCVyObxksuNRtHTByuEmCYzwLj(i);
		}
	}

	protected virtual void OqBIItBUVYpKRkkdxipCmqTbDPtI()
	{
		DaTALLHXzryylPLlNnhlPKgOrTSO();
		if (base.sIxvbdiJJXGTPKMdgswAQFCeVOyI != fyQKArxdnRgBFXnCTGFifmqgwogRA.CompoundElement)
		{
			return;
		}
		OUxgQpuZIuwKyJEylNPLslOwBwNAA oUxgQpuZIuwKyJEylNPLslOwBwNAA = base.oAneKvBTUlXClxNArblEZzfmJYEU;
		if ((oUxgQpuZIuwKyJEylNPLslOwBwNAA == OUxgQpuZIuwKyJEylNPLslOwBwNAA.Axis2D || (uint)(oUxgQpuZIuwKyJEylNPLslOwBwNAA - 3) <= 2u) && uZMktLKxVFgShqfHbKijMdtBCikg != null)
		{
			int num = PigQuqwlngXbAqDDYmfGLgmLqCnh;
			for (int i = 0; i < num; i++)
			{
				nUmRSnqJXLfZyjJvcbTdXNBpBiEX(1, new BKckUJBjHlyNjLMNcSvupioWhbq(uZMktLKxVFgShqfHbKijMdtBCikg[i], 16384 << i));
			}
		}
	}
}
