internal class RHrJzbmIXsdYvASDPWOTfZbswxFS : dmwPlHfCHErBELjQlGwCmsUXbNbq
{
	protected readonly NrPxKUKQSPaerZsCohGosVlmvWeK rDvKCTlMYhSdffQVWboZpLdNRYOT;

	private readonly string CILfJxcZczTgFldyhLeGrXgKkJNiA;

	private readonly string RUnayDueQaHkAfZnmNZWtXgpqkKH;

	private string TNERoPMwQDoIXgftaznekaoLClOeA;

	private readonly string YpikLApnGzMXlLpiInTRtgeeWwnn;

	private int RYSYmscslNDDKaQFsjirALPdFFvbb;

	public NrPxKUKQSPaerZsCohGosVlmvWeK WoaDJEnWziwZXmADtEwWjSCxwvBx => null;

	string dmwPlHfCHErBELjQlGwCmsUXbNbq.keyCategory => null;

	string dmwPlHfCHErBELjQlGwCmsUXbNbq.scriptingName => null;

	string dmwPlHfCHErBELjQlGwCmsUXbNbq.nonLocalizedDescriptiveName
	{
		get
		{
			return null;
		}
		set
		{
		}
	}

	string dmwPlHfCHErBELjQlGwCmsUXbNbq.key => null;

	int dmwPlHfCHErBELjQlGwCmsUXbNbq.autoGeneratedValueFlags
	{
		get
		{
			return 0;
		}
		set
		{
		}
	}

	public string keyCategory => null;

	public string scriptingName => null;

	public string poeTFkSLRzNdIILYUELLuCHkypDi => null;

	public string nonLocalizedDescriptiveName => null;

	public string key => null;

	public RHrJzbmIXsdYvASDPWOTfZbswxFS(NrPxKUKQSPaerZsCohGosVlmvWeK P_0, string P_1, string P_2, string P_3, string P_4)
	{
	}

	public virtual bool BmuDRZilnDsgEXpHCWUCCjGRxmob(RHrJzbmIXsdYvASDPWOTfZbswxFS P_0, bool P_1)
	{
		return false;
	}
}
