<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Timberborn.Reproduction</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Timberborn.InventorySystem">
      <HintPath>..\..\Assemblies\Timberborn.InventorySystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TimeSystem">
      <HintPath>..\..\Assemblies\Timberborn.TimeSystem.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections.Immutable">
      <HintPath>..\..\Assemblies\System.Collections.Immutable.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Goods">
      <HintPath>..\..\Assemblies\Timberborn.Goods.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.WorldPersistence">
      <HintPath>..\..\Assemblies\Timberborn.WorldPersistence.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Common">
      <HintPath>..\..\Assemblies\Timberborn.Common.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BlueprintSystem">
      <HintPath>..\..\Assemblies\Timberborn.BlueprintSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BehaviorSystem">
      <HintPath>..\..\Assemblies\Timberborn.BehaviorSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Hauling">
      <HintPath>..\..\Assemblies\Timberborn.Hauling.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Beavers">
      <HintPath>..\..\Assemblies\Timberborn.Beavers.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SingletonSystem">
      <HintPath>..\..\Assemblies\Timberborn.SingletonSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BaseComponentSystem">
      <HintPath>..\..\Assemblies\Timberborn.BaseComponentSystem.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EnterableSystem">
      <HintPath>..\..\Assemblies\Timberborn.EnterableSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TemplateInstantiation">
      <HintPath>..\..\Assemblies\Timberborn.TemplateInstantiation.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Persistence">
      <HintPath>..\..\Assemblies\Timberborn.Persistence.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BlockingSystem">
      <HintPath>..\..\Assemblies\Timberborn.BlockingSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Buildings">
      <HintPath>..\..\Assemblies\Timberborn.Buildings.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.GameDistricts">
      <HintPath>..\..\Assemblies\Timberborn.GameDistricts.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Carrying">
      <HintPath>..\..\Assemblies\Timberborn.Carrying.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.DwellingSystem">
      <HintPath>..\..\Assemblies\Timberborn.DwellingSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BlockSystem">
      <HintPath>..\..\Assemblies\Timberborn.BlockSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EntitySystem">
      <HintPath>..\..\Assemblies\Timberborn.EntitySystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.WorkSystem">
      <HintPath>..\..\Assemblies\Timberborn.WorkSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TickSystem">
      <HintPath>..\..\Assemblies\Timberborn.TickSystem.dll</HintPath>
    </Reference>
    <Reference Include="Bindito.Core">
      <HintPath>..\..\Assemblies\Bindito.Core.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Navigation">
      <HintPath>..\..\Assemblies\Timberborn.Navigation.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.CharactersGame">
      <HintPath>..\..\Assemblies\Timberborn.CharactersGame.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.NeedSystem">
      <HintPath>..\..\Assemblies\Timberborn.NeedSystem.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>