<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PugMod.Platform</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="PugMod.Integration">
      <HintPath>..\..\Assemblies\PugMod.Integration.dll</HintPath>
    </Reference>
    <Reference Include="modio.UnityPlugin">
      <HintPath>..\..\Assemblies\modio.UnityPlugin.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>..\..\Assemblies\UnityEngine.JSONSerializeModule.dll</HintPath>
    </Reference>
    <Reference Include="PugMod.SDK">
      <HintPath>..\..\Assemblies\PugMod.SDK.dll</HintPath>
    </Reference>
    <Reference Include="PugMod.Loader">
      <HintPath>..\..\Assemblies\PugMod.Loader.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>