using System;
using Rewired;
using Rewired.Internal.Glyphs;
using Rewired.Internal.Localization;

internal abstract class bEGMonvAERhJZhrLApNDusRgdSuD : ygZwNwIMhUCPvDceCIcxgnzserfbA
{
	protected readonly KeyedGlyph mlwzUvSzypjuEeJqxJhxzfijdIxS;

	protected readonly KeyedGlyph wTFwmDhOdAtbNvAabwzHiBGeBWAaA;

	public abstract object YyUsIUduGWeOfCtjIywoJfllsurQ { get; }

	public abstract object YSPUguRwsXdgRZEXPfEfiDKpzBmf { get; }

	public abstract string QRtdMqfdnInSEUzeWexXMKtDKsnyA { get; }

	public abstract string pRGxScpVOokrwgzCeoGGDnJeZOJP { get; }

	protected bEGMonvAERhJZhrLApNDusRgdSuD(JSWalVgNfayAAqqgkCDSfWJdaAMTB.VwAEfXIfCgCiohhuMMznDzgWRhLp P_0, JSWalVgNfayAAqqgkCDSfWJdaAMTB.bETiEQbYCrQRqCLRvbSAcJMPkrdD P_1)
		: base(P_0, P_1)
	{
		mlwzUvSzypjuEeJqxJhxzfijdIxS = new KeyedGlyph();
		wTFwmDhOdAtbNvAabwzHiBGeBWAaA = new KeyedGlyph();
	}

	protected bEGMonvAERhJZhrLApNDusRgdSuD(rCWArSkiHiMJlBWAwpbfXxbyxlrS P_0, JSWalVgNfayAAqqgkCDSfWJdaAMTB.VwAEfXIfCgCiohhuMMznDzgWRhLp P_1, JSWalVgNfayAAqqgkCDSfWJdaAMTB.bETiEQbYCrQRqCLRvbSAcJMPkrdD P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
		mlwzUvSzypjuEeJqxJhxzfijdIxS = new KeyedGlyph();
		wTFwmDhOdAtbNvAabwzHiBGeBWAaA = new KeyedGlyph();
	}

	protected override void izqgVCmGioijeoXrjYwAEVccIJMK()
	{
		base.izqgVCmGioijeoXrjYwAEVccIJMK();
	}

	public virtual void yCbnuYjPdoDSWlofAupfOuHlfNOG(rCWArSkiHiMJlBWAwpbfXxbyxlrS P_0)
	{
		yCbnuYjPdoDSWlofAupfOuHlfNOG((LFxfRtFXyxgAjxbmpHDNQNxOPKov)P_0);
	}

	public override void yCbnuYjPdoDSWlofAupfOuHlfNOG(LFxfRtFXyxgAjxbmpHDNQNxOPKov P_0)
	{
		base.yCbnuYjPdoDSWlofAupfOuHlfNOG(P_0);
		if (!(P_0 is rCWArSkiHiMJlBWAwpbfXxbyxlrS))
		{
			throw new ArgumentException("value must implement " + typeof(rCWArSkiHiMJlBWAwpbfXxbyxlrS));
		}
	}

	public override void OXcBXtPnTqYHpiucqKbwxkVzPkjf()
	{
		base.OXcBXtPnTqYHpiucqKbwxkVzPkjf();
		mlwzUvSzypjuEeJqxJhxzfijdIxS.Clear();
		wTFwmDhOdAtbNvAabwzHiBGeBWAaA.Clear();
	}

	public void iaqfIKjbRMPDFoCBbwPBerMeneZuA()
	{
		mlwzUvSzypjuEeJqxJhxzfijdIxS.Clear();
		PWkFKbOvHOZIUAfzpEAIGeluRTIK(JSWalVgNfayAAqqgkCDSfWJdaAMTB.VEYElUHTAVQERqFafltfcwjOaUMyA.Keys);
	}

	public void lpXMARXdoqDjiJdhmRDgUetHrdBA()
	{
		wTFwmDhOdAtbNvAabwzHiBGeBWAaA.Clear();
		PWkFKbOvHOZIUAfzpEAIGeluRTIK(JSWalVgNfayAAqqgkCDSfWJdaAMTB.VEYElUHTAVQERqFafltfcwjOaUMyA.Keys);
	}

	public override bool TUibHCXgdJpNwgxVPYRazOMZLYAI(VNmGeGFSdUUKSjRvPzQEfrbImtru P_0)
	{
		if (!(P_0 is bEGMonvAERhJZhrLApNDusRgdSuD bEGMonvAERhJZhrLApNDusRgdSuD2))
		{
			return false;
		}
		if (!base.TUibHCXgdJpNwgxVPYRazOMZLYAI(P_0))
		{
			return false;
		}
		rCWArSkiHiMJlBWAwpbfXxbyxlrS rCWArSkiHiMJlBWAwpbfXxbyxlrS2 = jfPgAiHCXDOsCqPqzSwgbROIKKdw();
		rCWArSkiHiMJlBWAwpbfXxbyxlrS rCWArSkiHiMJlBWAwpbfXxbyxlrS3 = bEGMonvAERhJZhrLApNDusRgdSuD2.jfPgAiHCXDOsCqPqzSwgbROIKKdw();
		if (rCWArSkiHiMJlBWAwpbfXxbyxlrS2 == null != (rCWArSkiHiMJlBWAwpbfXxbyxlrS3 == null))
		{
			return false;
		}
		if (rCWArSkiHiMJlBWAwpbfXxbyxlrS2 != null && (!string.Equals(rCWArSkiHiMJlBWAwpbfXxbyxlrS2.positiveKey, rCWArSkiHiMJlBWAwpbfXxbyxlrS3.positiveKey, StringComparison.Ordinal) || !string.Equals(rCWArSkiHiMJlBWAwpbfXxbyxlrS2.negativeKey, rCWArSkiHiMJlBWAwpbfXxbyxlrS3.negativeKey, StringComparison.Ordinal)))
		{
			return false;
		}
		return true;
	}

	protected override void wJjPIIRJfHhEbGedUconecGfiwzgB()
	{
		base.wJjPIIRJfHhEbGedUconecGfiwzgB();
		mlwzUvSzypjuEeJqxJhxzfijdIxS.Clear();
		wTFwmDhOdAtbNvAabwzHiBGeBWAaA.Clear();
	}

	protected override void PWkFKbOvHOZIUAfzpEAIGeluRTIK(JSWalVgNfayAAqqgkCDSfWJdaAMTB.VEYElUHTAVQERqFafltfcwjOaUMyA P_0)
	{
		base.PWkFKbOvHOZIUAfzpEAIGeluRTIK(P_0);
		rCWArSkiHiMJlBWAwpbfXxbyxlrS rCWArSkiHiMJlBWAwpbfXxbyxlrS2 = jfPgAiHCXDOsCqPqzSwgbROIKKdw();
		if (rCWArSkiHiMJlBWAwpbfXxbyxlrS2 == null || string.IsNullOrEmpty(rCWArSkiHiMJlBWAwpbfXxbyxlrS2.key))
		{
			return;
		}
		if ((rCWArSkiHiMJlBWAwpbfXxbyxlrS2.autoGeneratedValueFlags & 8) == 0 && string.IsNullOrEmpty(rCWArSkiHiMJlBWAwpbfXxbyxlrS2.positiveKey) && faXHDBAAOZDwuwJHQrByrdTWsRQC(Pole.Positive))
		{
			rCWArSkiHiMJlBWAwpbfXxbyxlrS2.positiveKey = rCWArSkiHiMJlBWAwpbfXxbyxlrS2.key;
			if (uJUjODPczvYqPUUgCxDsAdZvCbmq(Pole.Positive))
			{
				rCWArSkiHiMJlBWAwpbfXxbyxlrS2.positiveKey = LocalizationManager.AppendToKeyAxisPole(rCWArSkiHiMJlBWAwpbfXxbyxlrS2.positiveKey, Pole.Positive);
			}
			rCWArSkiHiMJlBWAwpbfXxbyxlrS2.autoGeneratedValueFlags |= 8;
			UADvwlynuwapiHLmAmTBEEeQFLafA(8);
		}
		if ((rCWArSkiHiMJlBWAwpbfXxbyxlrS2.autoGeneratedValueFlags & 0x10) == 0 && string.IsNullOrEmpty(rCWArSkiHiMJlBWAwpbfXxbyxlrS2.negativeKey) && faXHDBAAOZDwuwJHQrByrdTWsRQC(Pole.Negative))
		{
			rCWArSkiHiMJlBWAwpbfXxbyxlrS2.negativeKey = rCWArSkiHiMJlBWAwpbfXxbyxlrS2.key;
			if (uJUjODPczvYqPUUgCxDsAdZvCbmq(Pole.Negative))
			{
				rCWArSkiHiMJlBWAwpbfXxbyxlrS2.negativeKey = LocalizationManager.AppendToKeyAxisPole(rCWArSkiHiMJlBWAwpbfXxbyxlrS2.negativeKey, Pole.Negative);
			}
			rCWArSkiHiMJlBWAwpbfXxbyxlrS2.autoGeneratedValueFlags |= 16;
			UADvwlynuwapiHLmAmTBEEeQFLafA(16);
		}
	}

	protected override void LiXAHjDsSjcjuheRSvInddHJDOVCA(JSWalVgNfayAAqqgkCDSfWJdaAMTB.MbnhNztvlYEMfnRNZAzRFTGcWsDiA P_0)
	{
		base.LiXAHjDsSjcjuheRSvInddHJDOVCA(P_0);
		rCWArSkiHiMJlBWAwpbfXxbyxlrS rCWArSkiHiMJlBWAwpbfXxbyxlrS2 = jfPgAiHCXDOsCqPqzSwgbROIKKdw();
		if (rCWArSkiHiMJlBWAwpbfXxbyxlrS2 != null && ((uint)rCWArSkiHiMJlBWAwpbfXxbyxlrS2.autoGeneratedValueFlags & (uint)P_0) != 0)
		{
			if ((P_0 & JSWalVgNfayAAqqgkCDSfWJdaAMTB.MbnhNztvlYEMfnRNZAzRFTGcWsDiA.PositiveKey) != JSWalVgNfayAAqqgkCDSfWJdaAMTB.MbnhNztvlYEMfnRNZAzRFTGcWsDiA.None && (rCWArSkiHiMJlBWAwpbfXxbyxlrS2.autoGeneratedValueFlags & 8) != 0)
			{
				rCWArSkiHiMJlBWAwpbfXxbyxlrS2.positiveKey = null;
				UADvwlynuwapiHLmAmTBEEeQFLafA(8);
				rCWArSkiHiMJlBWAwpbfXxbyxlrS2.autoGeneratedValueFlags &= -9;
			}
			if ((P_0 & JSWalVgNfayAAqqgkCDSfWJdaAMTB.MbnhNztvlYEMfnRNZAzRFTGcWsDiA.NegativeKey) != JSWalVgNfayAAqqgkCDSfWJdaAMTB.MbnhNztvlYEMfnRNZAzRFTGcWsDiA.None && (rCWArSkiHiMJlBWAwpbfXxbyxlrS2.autoGeneratedValueFlags & 0x10) != 0)
			{
				rCWArSkiHiMJlBWAwpbfXxbyxlrS2.negativeKey = null;
				UADvwlynuwapiHLmAmTBEEeQFLafA(16);
				rCWArSkiHiMJlBWAwpbfXxbyxlrS2.autoGeneratedValueFlags &= -17;
			}
		}
	}

	protected override JSWalVgNfayAAqqgkCDSfWJdaAMTB.MbnhNztvlYEMfnRNZAzRFTGcWsDiA cfJjiFeTHaaDjDguihuHBEeWpOdD(JSWalVgNfayAAqqgkCDSfWJdaAMTB.VEYElUHTAVQERqFafltfcwjOaUMyA P_0)
	{
		JSWalVgNfayAAqqgkCDSfWJdaAMTB.MbnhNztvlYEMfnRNZAzRFTGcWsDiA mbnhNztvlYEMfnRNZAzRFTGcWsDiA = base.cfJjiFeTHaaDjDguihuHBEeWpOdD(P_0);
		if ((P_0 & JSWalVgNfayAAqqgkCDSfWJdaAMTB.VEYElUHTAVQERqFafltfcwjOaUMyA.Keys) != JSWalVgNfayAAqqgkCDSfWJdaAMTB.VEYElUHTAVQERqFafltfcwjOaUMyA.None)
		{
			mbnhNztvlYEMfnRNZAzRFTGcWsDiA |= (JSWalVgNfayAAqqgkCDSfWJdaAMTB.MbnhNztvlYEMfnRNZAzRFTGcWsDiA)24;
		}
		return mbnhNztvlYEMfnRNZAzRFTGcWsDiA;
	}

	protected new rCWArSkiHiMJlBWAwpbfXxbyxlrS jfPgAiHCXDOsCqPqzSwgbROIKKdw()
	{
		return base.jfPgAiHCXDOsCqPqzSwgbROIKKdw() as rCWArSkiHiMJlBWAwpbfXxbyxlrS;
	}

	protected virtual bool uJUjODPczvYqPUUgCxDsAdZvCbmq(Pole P_0)
	{
		switch (base.ugEcvEUjcYzrLriOHSDCiapaTNEm)
		{
		case JSWalVgNfayAAqqgkCDSfWJdaAMTB.VwAEfXIfCgCiohhuMMznDzgWRhLp.Axis:
			return true;
		case JSWalVgNfayAAqqgkCDSfWJdaAMTB.VwAEfXIfCgCiohhuMMznDzgWRhLp.Button:
			return false;
		default:
			return false;
		}
	}

	protected virtual bool faXHDBAAOZDwuwJHQrByrdTWsRQC(Pole P_0)
	{
		switch (base.ugEcvEUjcYzrLriOHSDCiapaTNEm)
		{
		case JSWalVgNfayAAqqgkCDSfWJdaAMTB.VwAEfXIfCgCiohhuMMznDzgWRhLp.Axis:
			return true;
		case JSWalVgNfayAAqqgkCDSfWJdaAMTB.VwAEfXIfCgCiohhuMMznDzgWRhLp.Button:
			switch (P_0)
			{
			case Pole.Positive:
				return true;
			case Pole.Negative:
				return false;
			default:
				return false;
			}
		default:
			return false;
		}
	}

	protected override void kakEANoxNEASOrgsQDjgagRjuxdPA()
	{
		base.kakEANoxNEASOrgsQDjgagRjuxdPA();
		_ = YyUsIUduGWeOfCtjIywoJfllsurQ;
		_ = YSPUguRwsXdgRZEXPfEfiDKpzBmf;
	}

	protected override void IOIteHoWYMIdXUPYMcUTgwJmPXpoA()
	{
		base.IOIteHoWYMIdXUPYMcUTgwJmPXpoA();
		hdKvZSMBobFalOMlTkDjSeXHEDLKA(8, new ZDOHKxiITjftpRcmToJGFSyiYFok
		{
			QOQCmrIxdYGkZJJkjlLjSsjiCHJDA = mlwzUvSzypjuEeJqxJhxzfijdIxS
		});
		hdKvZSMBobFalOMlTkDjSeXHEDLKA(16, new ZDOHKxiITjftpRcmToJGFSyiYFok
		{
			QOQCmrIxdYGkZJJkjlLjSsjiCHJDA = wTFwmDhOdAtbNvAabwzHiBGeBWAaA
		});
	}
}
