using System;
using Rewired;
using Rewired.Internal.Localization;

internal abstract class hNpoKVhMsIsqhjWAuOEXelnsIjau : JSWalVgNfayAAqqgkCDSfWJdaAMTB
{
	protected readonly LocalizedString TFbQDiujouWZgNbceuSOyCcDHFWr;

	protected readonly LocalizedString rrLQtkwowSZdziBzBcAkXqMUQAHA;

	public abstract string nkieIDGTvoQOzfhnwqrRbpIBgcrw { get; }

	public abstract string CWdJorNsJxtHBeABWaFvcIChQSiaA { get; }

	protected hNpoKVhMsIsqhjWAuOEXelnsIjau(VwAEfXIfCgCiohhuMMznDzgWRhLp P_0, bETiEQbYCrQRqCLRvbSAcJMPkrdD P_1)
		: base(P_0, P_1)
	{
		TFbQDiujouWZgNbceuSOyCcDHFWr = new LocalizedString();
		rrLQtkwowSZdziBzBcAkXqMUQAHA = new LocalizedString();
	}

	protected hNpoKVhMsIsqhjWAuOEXelnsIjau(dEyHRFFHMmNkBjyccsmusjbnHemDB P_0, VwAEfXIfCgCiohhuMMznDzgWRhLp P_1, bETiEQbYCrQRqCLRvbSAcJMPkrdD P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
		TFbQDiujouWZgNbceuSOyCcDHFWr = new LocalizedString();
		rrLQtkwowSZdziBzBcAkXqMUQAHA = new LocalizedString();
	}

	protected override void izqgVCmGioijeoXrjYwAEVccIJMK()
	{
		base.izqgVCmGioijeoXrjYwAEVccIJMK();
	}

	public virtual void yCbnuYjPdoDSWlofAupfOuHlfNOG(dEyHRFFHMmNkBjyccsmusjbnHemDB P_0)
	{
		yCbnuYjPdoDSWlofAupfOuHlfNOG((jtAeQMwqfCHdCmeHvhaRCqwDmBxb)P_0);
	}

	public override void yCbnuYjPdoDSWlofAupfOuHlfNOG(jtAeQMwqfCHdCmeHvhaRCqwDmBxb P_0)
	{
		base.yCbnuYjPdoDSWlofAupfOuHlfNOG(P_0);
		if (!(P_0 is dEyHRFFHMmNkBjyccsmusjbnHemDB))
		{
			throw new ArgumentException("value must implement " + typeof(dEyHRFFHMmNkBjyccsmusjbnHemDB));
		}
	}

	public override void ijtdeCdNfQFeopbwLHgQcRDjMsVz()
	{
		base.ijtdeCdNfQFeopbwLHgQcRDjMsVz();
		TFbQDiujouWZgNbceuSOyCcDHFWr.Clear();
		rrLQtkwowSZdziBzBcAkXqMUQAHA.Clear();
	}

	public override void OXcBXtPnTqYHpiucqKbwxkVzPkjf()
	{
		base.OXcBXtPnTqYHpiucqKbwxkVzPkjf();
		TFbQDiujouWZgNbceuSOyCcDHFWr.Clear();
		rrLQtkwowSZdziBzBcAkXqMUQAHA.Clear();
	}

	public void iaqfIKjbRMPDFoCBbwPBerMeneZuA()
	{
		TFbQDiujouWZgNbceuSOyCcDHFWr.Clear();
		PWkFKbOvHOZIUAfzpEAIGeluRTIK(VEYElUHTAVQERqFafltfcwjOaUMyA.Keys);
	}

	public void lpXMARXdoqDjiJdhmRDgUetHrdBA()
	{
		rrLQtkwowSZdziBzBcAkXqMUQAHA.Clear();
		PWkFKbOvHOZIUAfzpEAIGeluRTIK(VEYElUHTAVQERqFafltfcwjOaUMyA.Keys);
	}

	public void pjBoYQDQmYltEbIDwnlpAnwItxcv()
	{
		TFbQDiujouWZgNbceuSOyCcDHFWr.Clear();
		PWkFKbOvHOZIUAfzpEAIGeluRTIK(VEYElUHTAVQERqFafltfcwjOaUMyA.Names);
	}

	public void uOrKQcLYTlGJqVnyiQqbMnhcLgPQ()
	{
		rrLQtkwowSZdziBzBcAkXqMUQAHA.Clear();
		PWkFKbOvHOZIUAfzpEAIGeluRTIK(VEYElUHTAVQERqFafltfcwjOaUMyA.Names);
	}

	public override bool TUibHCXgdJpNwgxVPYRazOMZLYAI(JdcCLFiaJuoUfXzTzdwUYtOkZosQ P_0, bool P_1)
	{
		if (!(P_0 is hNpoKVhMsIsqhjWAuOEXelnsIjau hNpoKVhMsIsqhjWAuOEXelnsIjau2))
		{
			return false;
		}
		if (!base.TUibHCXgdJpNwgxVPYRazOMZLYAI(P_0, P_1))
		{
			return false;
		}
		dEyHRFFHMmNkBjyccsmusjbnHemDB dEyHRFFHMmNkBjyccsmusjbnHemDB2 = jfPgAiHCXDOsCqPqzSwgbROIKKdw();
		dEyHRFFHMmNkBjyccsmusjbnHemDB dEyHRFFHMmNkBjyccsmusjbnHemDB3 = hNpoKVhMsIsqhjWAuOEXelnsIjau2.jfPgAiHCXDOsCqPqzSwgbROIKKdw();
		if (dEyHRFFHMmNkBjyccsmusjbnHemDB2 == null != (dEyHRFFHMmNkBjyccsmusjbnHemDB3 == null))
		{
			return false;
		}
		if (dEyHRFFHMmNkBjyccsmusjbnHemDB2 != null && P_1 && (!string.Equals(dEyHRFFHMmNkBjyccsmusjbnHemDB2.positiveKey, dEyHRFFHMmNkBjyccsmusjbnHemDB3.positiveKey, StringComparison.Ordinal) || !string.Equals(dEyHRFFHMmNkBjyccsmusjbnHemDB2.negativeKey, dEyHRFFHMmNkBjyccsmusjbnHemDB3.negativeKey, StringComparison.Ordinal) || !string.Equals(dEyHRFFHMmNkBjyccsmusjbnHemDB2.nonLocalizedPositiveDescriptiveName, dEyHRFFHMmNkBjyccsmusjbnHemDB3.nonLocalizedPositiveDescriptiveName, StringComparison.Ordinal) || !string.Equals(dEyHRFFHMmNkBjyccsmusjbnHemDB2.nonLocalizedNegativeDescriptiveName, dEyHRFFHMmNkBjyccsmusjbnHemDB3.nonLocalizedNegativeDescriptiveName, StringComparison.Ordinal)))
		{
			return false;
		}
		return true;
	}

	protected override void wJjPIIRJfHhEbGedUconecGfiwzgB()
	{
		base.wJjPIIRJfHhEbGedUconecGfiwzgB();
		TFbQDiujouWZgNbceuSOyCcDHFWr.Clear();
		rrLQtkwowSZdziBzBcAkXqMUQAHA.Clear();
	}

	protected override void PWkFKbOvHOZIUAfzpEAIGeluRTIK(VEYElUHTAVQERqFafltfcwjOaUMyA P_0)
	{
		base.PWkFKbOvHOZIUAfzpEAIGeluRTIK(P_0);
		dEyHRFFHMmNkBjyccsmusjbnHemDB dEyHRFFHMmNkBjyccsmusjbnHemDB2 = jfPgAiHCXDOsCqPqzSwgbROIKKdw();
		if (dEyHRFFHMmNkBjyccsmusjbnHemDB2 == null)
		{
			return;
		}
		if ((dEyHRFFHMmNkBjyccsmusjbnHemDB2.autoGeneratedValueFlags & 2) == 0 && string.IsNullOrEmpty(dEyHRFFHMmNkBjyccsmusjbnHemDB2.nonLocalizedPositiveDescriptiveName) && faXHDBAAOZDwuwJHQrByrdTWsRQC(Pole.Positive))
		{
			dEyHRFFHMmNkBjyccsmusjbnHemDB2.nonLocalizedPositiveDescriptiveName = dEyHRFFHMmNkBjyccsmusjbnHemDB2.nonLocalizedDescriptiveName;
			if (uJUjODPczvYqPUUgCxDsAdZvCbmq(Pole.Positive))
			{
				dEyHRFFHMmNkBjyccsmusjbnHemDB2.nonLocalizedPositiveDescriptiveName = LocalizationManager.AppendToNameAxisPole(dEyHRFFHMmNkBjyccsmusjbnHemDB2.nonLocalizedPositiveDescriptiveName, Pole.Positive);
			}
			dEyHRFFHMmNkBjyccsmusjbnHemDB2.autoGeneratedValueFlags |= 2;
			UADvwlynuwapiHLmAmTBEEeQFLafA(2);
		}
		if ((dEyHRFFHMmNkBjyccsmusjbnHemDB2.autoGeneratedValueFlags & 4) == 0 && string.IsNullOrEmpty(dEyHRFFHMmNkBjyccsmusjbnHemDB2.nonLocalizedNegativeDescriptiveName) && faXHDBAAOZDwuwJHQrByrdTWsRQC(Pole.Negative))
		{
			dEyHRFFHMmNkBjyccsmusjbnHemDB2.nonLocalizedNegativeDescriptiveName = dEyHRFFHMmNkBjyccsmusjbnHemDB2.nonLocalizedDescriptiveName;
			if (uJUjODPczvYqPUUgCxDsAdZvCbmq(Pole.Negative))
			{
				dEyHRFFHMmNkBjyccsmusjbnHemDB2.nonLocalizedNegativeDescriptiveName = LocalizationManager.AppendToNameAxisPole(dEyHRFFHMmNkBjyccsmusjbnHemDB2.nonLocalizedNegativeDescriptiveName, Pole.Negative);
			}
			dEyHRFFHMmNkBjyccsmusjbnHemDB2.autoGeneratedValueFlags |= 4;
			UADvwlynuwapiHLmAmTBEEeQFLafA(4);
		}
		if (string.IsNullOrEmpty(dEyHRFFHMmNkBjyccsmusjbnHemDB2.key))
		{
			return;
		}
		if ((dEyHRFFHMmNkBjyccsmusjbnHemDB2.autoGeneratedValueFlags & 8) == 0 && string.IsNullOrEmpty(dEyHRFFHMmNkBjyccsmusjbnHemDB2.positiveKey) && faXHDBAAOZDwuwJHQrByrdTWsRQC(Pole.Positive))
		{
			dEyHRFFHMmNkBjyccsmusjbnHemDB2.positiveKey = dEyHRFFHMmNkBjyccsmusjbnHemDB2.key;
			if (uJUjODPczvYqPUUgCxDsAdZvCbmq(Pole.Positive))
			{
				dEyHRFFHMmNkBjyccsmusjbnHemDB2.positiveKey = LocalizationManager.AppendToKeyAxisPole(dEyHRFFHMmNkBjyccsmusjbnHemDB2.positiveKey, Pole.Positive);
			}
			dEyHRFFHMmNkBjyccsmusjbnHemDB2.autoGeneratedValueFlags |= 8;
			UADvwlynuwapiHLmAmTBEEeQFLafA(8);
		}
		if ((dEyHRFFHMmNkBjyccsmusjbnHemDB2.autoGeneratedValueFlags & 0x10) == 0 && string.IsNullOrEmpty(dEyHRFFHMmNkBjyccsmusjbnHemDB2.negativeKey) && faXHDBAAOZDwuwJHQrByrdTWsRQC(Pole.Negative))
		{
			dEyHRFFHMmNkBjyccsmusjbnHemDB2.negativeKey = dEyHRFFHMmNkBjyccsmusjbnHemDB2.key;
			if (uJUjODPczvYqPUUgCxDsAdZvCbmq(Pole.Negative))
			{
				dEyHRFFHMmNkBjyccsmusjbnHemDB2.negativeKey = LocalizationManager.AppendToKeyAxisPole(dEyHRFFHMmNkBjyccsmusjbnHemDB2.negativeKey, Pole.Negative);
			}
			dEyHRFFHMmNkBjyccsmusjbnHemDB2.autoGeneratedValueFlags |= 16;
			UADvwlynuwapiHLmAmTBEEeQFLafA(16);
		}
	}

	protected override void LiXAHjDsSjcjuheRSvInddHJDOVCA(MbnhNztvlYEMfnRNZAzRFTGcWsDiA P_0)
	{
		base.LiXAHjDsSjcjuheRSvInddHJDOVCA(P_0);
		dEyHRFFHMmNkBjyccsmusjbnHemDB dEyHRFFHMmNkBjyccsmusjbnHemDB2 = jfPgAiHCXDOsCqPqzSwgbROIKKdw();
		if (dEyHRFFHMmNkBjyccsmusjbnHemDB2 != null && ((uint)dEyHRFFHMmNkBjyccsmusjbnHemDB2.autoGeneratedValueFlags & (uint)P_0) != 0)
		{
			if ((P_0 & MbnhNztvlYEMfnRNZAzRFTGcWsDiA.PositiveKey) != MbnhNztvlYEMfnRNZAzRFTGcWsDiA.None && (dEyHRFFHMmNkBjyccsmusjbnHemDB2.autoGeneratedValueFlags & 8) != 0)
			{
				dEyHRFFHMmNkBjyccsmusjbnHemDB2.positiveKey = null;
				UADvwlynuwapiHLmAmTBEEeQFLafA(8);
				dEyHRFFHMmNkBjyccsmusjbnHemDB2.autoGeneratedValueFlags &= -9;
			}
			if ((P_0 & MbnhNztvlYEMfnRNZAzRFTGcWsDiA.NegativeKey) != MbnhNztvlYEMfnRNZAzRFTGcWsDiA.None && (dEyHRFFHMmNkBjyccsmusjbnHemDB2.autoGeneratedValueFlags & 0x10) != 0)
			{
				dEyHRFFHMmNkBjyccsmusjbnHemDB2.negativeKey = null;
				UADvwlynuwapiHLmAmTBEEeQFLafA(16);
				dEyHRFFHMmNkBjyccsmusjbnHemDB2.autoGeneratedValueFlags &= -17;
			}
			if ((P_0 & MbnhNztvlYEMfnRNZAzRFTGcWsDiA.PositiveDescriptiveName) != MbnhNztvlYEMfnRNZAzRFTGcWsDiA.None && (dEyHRFFHMmNkBjyccsmusjbnHemDB2.autoGeneratedValueFlags & 2) != 0)
			{
				dEyHRFFHMmNkBjyccsmusjbnHemDB2.nonLocalizedPositiveDescriptiveName = null;
				UADvwlynuwapiHLmAmTBEEeQFLafA(2);
				dEyHRFFHMmNkBjyccsmusjbnHemDB2.autoGeneratedValueFlags &= -3;
			}
			if ((P_0 & MbnhNztvlYEMfnRNZAzRFTGcWsDiA.NegativeDescriptiveName) != MbnhNztvlYEMfnRNZAzRFTGcWsDiA.None && (dEyHRFFHMmNkBjyccsmusjbnHemDB2.autoGeneratedValueFlags & 4) != 0)
			{
				dEyHRFFHMmNkBjyccsmusjbnHemDB2.nonLocalizedNegativeDescriptiveName = null;
				UADvwlynuwapiHLmAmTBEEeQFLafA(4);
				dEyHRFFHMmNkBjyccsmusjbnHemDB2.autoGeneratedValueFlags &= -5;
			}
		}
	}

	protected override MbnhNztvlYEMfnRNZAzRFTGcWsDiA cfJjiFeTHaaDjDguihuHBEeWpOdD(VEYElUHTAVQERqFafltfcwjOaUMyA P_0)
	{
		MbnhNztvlYEMfnRNZAzRFTGcWsDiA mbnhNztvlYEMfnRNZAzRFTGcWsDiA = base.cfJjiFeTHaaDjDguihuHBEeWpOdD(P_0);
		if ((P_0 & VEYElUHTAVQERqFafltfcwjOaUMyA.Keys) != VEYElUHTAVQERqFafltfcwjOaUMyA.None)
		{
			mbnhNztvlYEMfnRNZAzRFTGcWsDiA |= (MbnhNztvlYEMfnRNZAzRFTGcWsDiA)24;
		}
		if ((P_0 & VEYElUHTAVQERqFafltfcwjOaUMyA.Names) != VEYElUHTAVQERqFafltfcwjOaUMyA.None)
		{
			mbnhNztvlYEMfnRNZAzRFTGcWsDiA |= (MbnhNztvlYEMfnRNZAzRFTGcWsDiA)6;
		}
		return mbnhNztvlYEMfnRNZAzRFTGcWsDiA;
	}

	protected new dEyHRFFHMmNkBjyccsmusjbnHemDB jfPgAiHCXDOsCqPqzSwgbROIKKdw()
	{
		return base.jfPgAiHCXDOsCqPqzSwgbROIKKdw() as dEyHRFFHMmNkBjyccsmusjbnHemDB;
	}

	protected virtual bool uJUjODPczvYqPUUgCxDsAdZvCbmq(Pole P_0)
	{
		switch (base.ugEcvEUjcYzrLriOHSDCiapaTNEm)
		{
		case VwAEfXIfCgCiohhuMMznDzgWRhLp.Axis:
			return true;
		case VwAEfXIfCgCiohhuMMznDzgWRhLp.Button:
			return false;
		default:
			return false;
		}
	}

	protected virtual bool faXHDBAAOZDwuwJHQrByrdTWsRQC(Pole P_0)
	{
		switch (base.ugEcvEUjcYzrLriOHSDCiapaTNEm)
		{
		case VwAEfXIfCgCiohhuMMznDzgWRhLp.Axis:
			return true;
		case VwAEfXIfCgCiohhuMMznDzgWRhLp.Button:
			switch (P_0)
			{
			case Pole.Positive:
				return true;
			case Pole.Negative:
				return false;
			default:
				return false;
			}
		default:
			return false;
		}
	}

	protected override void KMlMwaGRrxQYwdSiVNXyPVZXKreA()
	{
		base.KMlMwaGRrxQYwdSiVNXyPVZXKreA();
		_ = nkieIDGTvoQOzfhnwqrRbpIBgcrw;
		_ = CWdJorNsJxtHBeABWaFvcIChQSiaA;
	}

	protected override void IOIteHoWYMIdXUPYMcUTgwJmPXpoA()
	{
		base.IOIteHoWYMIdXUPYMcUTgwJmPXpoA();
		hdKvZSMBobFalOMlTkDjSeXHEDLKA(1, new WkflcJKKhlDFbBrbgxTHkqcdvDwd
		{
			bEObyXQRTpcIEjHdzVovOMlzkufCA = 6
		});
		hdKvZSMBobFalOMlTkDjSeXHEDLKA(8, new WkflcJKKhlDFbBrbgxTHkqcdvDwd(TFbQDiujouWZgNbceuSOyCcDHFWr, 2));
		hdKvZSMBobFalOMlTkDjSeXHEDLKA(16, new WkflcJKKhlDFbBrbgxTHkqcdvDwd(rrLQtkwowSZdziBzBcAkXqMUQAHA, 4));
		hdKvZSMBobFalOMlTkDjSeXHEDLKA(2, new WkflcJKKhlDFbBrbgxTHkqcdvDwd
		{
			LTGLdhEbjhgPoerZJGmVXTZoYKUIA = TFbQDiujouWZgNbceuSOyCcDHFWr
		});
		hdKvZSMBobFalOMlTkDjSeXHEDLKA(4, new WkflcJKKhlDFbBrbgxTHkqcdvDwd
		{
			LTGLdhEbjhgPoerZJGmVXTZoYKUIA = rrLQtkwowSZdziBzBcAkXqMUQAHA
		});
	}
}
