using System;
using Rewired.Internal.Localization;

internal abstract class iiFvxWRSrSmoIrhnwAizbWrXGZxH : JSWalVgNfayAAqqgkCDSfWJdaAMTB
{
	protected LocalizedString[] PROjQYrpgSIdZjYqEnOaDHUXyBjG;

	public int dhMPxgNIozGOSCWblPFvccnEWDJI => JSWalVgNfayAAqqgkCDSfWJdaAMTB.hMtVUAEviNnyqkiTSEVFSjpeZUfm(base.ugEcvEUjcYzrLriOHSDCiapaTNEm, base.iDKoVNKBUFFkBevicPLoKjjnDSZL);

	public abstract string jzbdtVDIZOFSEAfWzRXPFuJyPfqpA(int P_0);

	protected iiFvxWRSrSmoIrhnwAizbWrXGZxH(VwAEfXIfCgCiohhuMMznDzgWRhLp P_0, bETiEQbYCrQRqCLRvbSAcJMPkrdD P_1)
		: base(P_0, P_1)
	{
	}

	protected iiFvxWRSrSmoIrhnwAizbWrXGZxH(jYOuwHQLkAMAsMhmCbimJoXgoSaP P_0, VwAEfXIfCgCiohhuMMznDzgWRhLp P_1, bETiEQbYCrQRqCLRvbSAcJMPkrdD P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
	}

	protected override void izqgVCmGioijeoXrjYwAEVccIJMK()
	{
		int num = dhMPxgNIozGOSCWblPFvccnEWDJI;
		PROjQYrpgSIdZjYqEnOaDHUXyBjG = null;
		if (num > 0)
		{
			PROjQYrpgSIdZjYqEnOaDHUXyBjG = new LocalizedString[num];
			for (int i = 0; i < num; i++)
			{
				PROjQYrpgSIdZjYqEnOaDHUXyBjG[i] = new LocalizedString();
			}
		}
		base.izqgVCmGioijeoXrjYwAEVccIJMK();
	}

	public virtual void yCbnuYjPdoDSWlofAupfOuHlfNOG(jYOuwHQLkAMAsMhmCbimJoXgoSaP P_0)
	{
		yCbnuYjPdoDSWlofAupfOuHlfNOG((jtAeQMwqfCHdCmeHvhaRCqwDmBxb)P_0);
	}

	public override void yCbnuYjPdoDSWlofAupfOuHlfNOG(jtAeQMwqfCHdCmeHvhaRCqwDmBxb P_0)
	{
		base.yCbnuYjPdoDSWlofAupfOuHlfNOG(P_0);
		if (!(P_0 is jYOuwHQLkAMAsMhmCbimJoXgoSaP))
		{
			throw new ArgumentException("value must implement " + typeof(jYOuwHQLkAMAsMhmCbimJoXgoSaP));
		}
	}

	public override void ijtdeCdNfQFeopbwLHgQcRDjMsVz()
	{
		base.ijtdeCdNfQFeopbwLHgQcRDjMsVz();
	}

	public override void OXcBXtPnTqYHpiucqKbwxkVzPkjf()
	{
		base.OXcBXtPnTqYHpiucqKbwxkVzPkjf();
		if (PROjQYrpgSIdZjYqEnOaDHUXyBjG != null)
		{
			for (int i = 0; i < dhMPxgNIozGOSCWblPFvccnEWDJI; i++)
			{
				PROjQYrpgSIdZjYqEnOaDHUXyBjG[i].Clear();
			}
		}
	}

	public override bool TUibHCXgdJpNwgxVPYRazOMZLYAI(JdcCLFiaJuoUfXzTzdwUYtOkZosQ P_0, bool P_1)
	{
		if (!(P_0 is iiFvxWRSrSmoIrhnwAizbWrXGZxH iiFvxWRSrSmoIrhnwAizbWrXGZxH2))
		{
			return false;
		}
		if (!base.TUibHCXgdJpNwgxVPYRazOMZLYAI(P_0, P_1))
		{
			return false;
		}
		jYOuwHQLkAMAsMhmCbimJoXgoSaP jYOuwHQLkAMAsMhmCbimJoXgoSaP2 = jfPgAiHCXDOsCqPqzSwgbROIKKdw();
		jYOuwHQLkAMAsMhmCbimJoXgoSaP jYOuwHQLkAMAsMhmCbimJoXgoSaP3 = iiFvxWRSrSmoIrhnwAizbWrXGZxH2.jfPgAiHCXDOsCqPqzSwgbROIKKdw();
		if (jYOuwHQLkAMAsMhmCbimJoXgoSaP2 == null != (jYOuwHQLkAMAsMhmCbimJoXgoSaP3 == null))
		{
			return false;
		}
		if (jYOuwHQLkAMAsMhmCbimJoXgoSaP2 != null && P_1)
		{
			int num = dhMPxgNIozGOSCWblPFvccnEWDJI;
			for (int i = 0; i < num; i++)
			{
				if (!string.Equals(jYOuwHQLkAMAsMhmCbimJoXgoSaP2.GetSpecialElementKey(i), jYOuwHQLkAMAsMhmCbimJoXgoSaP3.GetSpecialElementKey(i), StringComparison.Ordinal))
				{
					return false;
				}
				if (!string.Equals(jYOuwHQLkAMAsMhmCbimJoXgoSaP2.GetSpecialElementNonLocalizedDescriptiveName(i), jYOuwHQLkAMAsMhmCbimJoXgoSaP3.GetSpecialElementNonLocalizedDescriptiveName(i), StringComparison.Ordinal))
				{
					return false;
				}
			}
		}
		return true;
	}

	protected override void wJjPIIRJfHhEbGedUconecGfiwzgB()
	{
		base.wJjPIIRJfHhEbGedUconecGfiwzgB();
		if (PROjQYrpgSIdZjYqEnOaDHUXyBjG != null)
		{
			for (int i = 0; i < PROjQYrpgSIdZjYqEnOaDHUXyBjG.Length; i++)
			{
				PROjQYrpgSIdZjYqEnOaDHUXyBjG[i].Clear();
			}
		}
	}

	protected override void PWkFKbOvHOZIUAfzpEAIGeluRTIK(VEYElUHTAVQERqFafltfcwjOaUMyA P_0)
	{
		base.PWkFKbOvHOZIUAfzpEAIGeluRTIK(P_0);
		jYOuwHQLkAMAsMhmCbimJoXgoSaP jYOuwHQLkAMAsMhmCbimJoXgoSaP2 = jfPgAiHCXDOsCqPqzSwgbROIKKdw();
		if (jYOuwHQLkAMAsMhmCbimJoXgoSaP2 == null || string.IsNullOrEmpty(jYOuwHQLkAMAsMhmCbimJoXgoSaP2.key) || base.ugEcvEUjcYzrLriOHSDCiapaTNEm != VwAEfXIfCgCiohhuMMznDzgWRhLp.CompoundElement || !JSWalVgNfayAAqqgkCDSfWJdaAMTB.HiplrqmAxSeQEXpdvOXYKTZEASQi(base.iDKoVNKBUFFkBevicPLoKjjnDSZL, out var exlqDuEbMnCkpHMuXAQdzpkhfUUr))
		{
			return;
		}
		for (int i = 0; i < exlqDuEbMnCkpHMuXAQdzpkhfUUr.psjRAApvubFvKrvItiJJlxpacaQl; i++)
		{
			int num = 8388608 << i;
			if ((jYOuwHQLkAMAsMhmCbimJoXgoSaP2.autoGeneratedValueFlags & num) == 0 && !string.IsNullOrEmpty(jYOuwHQLkAMAsMhmCbimJoXgoSaP2.key) && string.IsNullOrEmpty(jYOuwHQLkAMAsMhmCbimJoXgoSaP2.GetSpecialElementKey(i)))
			{
				string text = jYOuwHQLkAMAsMhmCbimJoXgoSaP2.key;
				if (exlqDuEbMnCkpHMuXAQdzpkhfUUr.TIxnSRhPSalQFvQOFZaLLiQtwMIC(i).CFZgLeSNFyCLpaVLVUHQRDinORMQA.HasValue)
				{
					text = LocalizationManager.AppendToKeyAxisDirection(text, exlqDuEbMnCkpHMuXAQdzpkhfUUr.TIxnSRhPSalQFvQOFZaLLiQtwMIC(i).CFZgLeSNFyCLpaVLVUHQRDinORMQA.Value);
				}
				jYOuwHQLkAMAsMhmCbimJoXgoSaP2.SetSpecialElementKey(i, text);
				jYOuwHQLkAMAsMhmCbimJoXgoSaP2.autoGeneratedValueFlags |= num;
				UADvwlynuwapiHLmAmTBEEeQFLafA(num);
			}
			int num2 = 16384 << i;
			if ((jYOuwHQLkAMAsMhmCbimJoXgoSaP2.autoGeneratedValueFlags & num2) == 0 && !string.IsNullOrEmpty(jYOuwHQLkAMAsMhmCbimJoXgoSaP2.nonLocalizedDescriptiveName) && string.IsNullOrEmpty(jYOuwHQLkAMAsMhmCbimJoXgoSaP2.GetSpecialElementNonLocalizedDescriptiveName(i)))
			{
				string text2 = jYOuwHQLkAMAsMhmCbimJoXgoSaP2.nonLocalizedDescriptiveName;
				if (exlqDuEbMnCkpHMuXAQdzpkhfUUr.TIxnSRhPSalQFvQOFZaLLiQtwMIC(i).CFZgLeSNFyCLpaVLVUHQRDinORMQA.HasValue)
				{
					text2 = LocalizationManager.AppendToNameAxisDirection(text2, exlqDuEbMnCkpHMuXAQdzpkhfUUr.TIxnSRhPSalQFvQOFZaLLiQtwMIC(i).CFZgLeSNFyCLpaVLVUHQRDinORMQA.Value);
				}
				jYOuwHQLkAMAsMhmCbimJoXgoSaP2.SetSpecialElementNonLocalizedDescriptiveName(i, text2);
				jYOuwHQLkAMAsMhmCbimJoXgoSaP2.autoGeneratedValueFlags |= num2;
				UADvwlynuwapiHLmAmTBEEeQFLafA(num2);
			}
		}
	}

	protected override void LiXAHjDsSjcjuheRSvInddHJDOVCA(MbnhNztvlYEMfnRNZAzRFTGcWsDiA P_0)
	{
		base.LiXAHjDsSjcjuheRSvInddHJDOVCA(P_0);
		jYOuwHQLkAMAsMhmCbimJoXgoSaP jYOuwHQLkAMAsMhmCbimJoXgoSaP2 = jfPgAiHCXDOsCqPqzSwgbROIKKdw();
		if (jYOuwHQLkAMAsMhmCbimJoXgoSaP2 == null || ((uint)jYOuwHQLkAMAsMhmCbimJoXgoSaP2.autoGeneratedValueFlags & (uint)P_0) == 0 || base.ugEcvEUjcYzrLriOHSDCiapaTNEm != VwAEfXIfCgCiohhuMMznDzgWRhLp.CompoundElement || !JSWalVgNfayAAqqgkCDSfWJdaAMTB.HiplrqmAxSeQEXpdvOXYKTZEASQi(base.iDKoVNKBUFFkBevicPLoKjjnDSZL, out var exlqDuEbMnCkpHMuXAQdzpkhfUUr))
		{
			return;
		}
		for (int i = 0; i < exlqDuEbMnCkpHMuXAQdzpkhfUUr.psjRAApvubFvKrvItiJJlxpacaQl; i++)
		{
			int num = 8388608 << i;
			if ((jYOuwHQLkAMAsMhmCbimJoXgoSaP2.autoGeneratedValueFlags & num) != 0)
			{
				jYOuwHQLkAMAsMhmCbimJoXgoSaP2.SetSpecialElementKey(i, null);
				jYOuwHQLkAMAsMhmCbimJoXgoSaP2.autoGeneratedValueFlags &= ~num;
				UADvwlynuwapiHLmAmTBEEeQFLafA(num);
			}
			int num2 = 16384 << i;
			if ((jYOuwHQLkAMAsMhmCbimJoXgoSaP2.autoGeneratedValueFlags & num2) != 0)
			{
				jYOuwHQLkAMAsMhmCbimJoXgoSaP2.SetSpecialElementNonLocalizedDescriptiveName(i, null);
				jYOuwHQLkAMAsMhmCbimJoXgoSaP2.autoGeneratedValueFlags &= ~num2;
				UADvwlynuwapiHLmAmTBEEeQFLafA(num2);
			}
		}
	}

	protected override MbnhNztvlYEMfnRNZAzRFTGcWsDiA cfJjiFeTHaaDjDguihuHBEeWpOdD(VEYElUHTAVQERqFafltfcwjOaUMyA P_0)
	{
		MbnhNztvlYEMfnRNZAzRFTGcWsDiA mbnhNztvlYEMfnRNZAzRFTGcWsDiA = base.cfJjiFeTHaaDjDguihuHBEeWpOdD(P_0);
		int num = dhMPxgNIozGOSCWblPFvccnEWDJI;
		if ((P_0 & VEYElUHTAVQERqFafltfcwjOaUMyA.Keys) != VEYElUHTAVQERqFafltfcwjOaUMyA.None)
		{
			for (int i = 0; i < num; i++)
			{
				mbnhNztvlYEMfnRNZAzRFTGcWsDiA = (MbnhNztvlYEMfnRNZAzRFTGcWsDiA)((int)mbnhNztvlYEMfnRNZAzRFTGcWsDiA | (8388608 << i));
			}
		}
		if ((P_0 & VEYElUHTAVQERqFafltfcwjOaUMyA.Names) != VEYElUHTAVQERqFafltfcwjOaUMyA.None)
		{
			for (int j = 0; j < num; j++)
			{
				mbnhNztvlYEMfnRNZAzRFTGcWsDiA = (MbnhNztvlYEMfnRNZAzRFTGcWsDiA)((int)mbnhNztvlYEMfnRNZAzRFTGcWsDiA | (16384 << j));
			}
		}
		return mbnhNztvlYEMfnRNZAzRFTGcWsDiA;
	}

	protected new jYOuwHQLkAMAsMhmCbimJoXgoSaP jfPgAiHCXDOsCqPqzSwgbROIKKdw()
	{
		return base.jfPgAiHCXDOsCqPqzSwgbROIKKdw() as jYOuwHQLkAMAsMhmCbimJoXgoSaP;
	}

	protected override void KMlMwaGRrxQYwdSiVNXyPVZXKreA()
	{
		base.KMlMwaGRrxQYwdSiVNXyPVZXKreA();
		int num = dhMPxgNIozGOSCWblPFvccnEWDJI;
		for (int i = 0; i < num; i++)
		{
			jzbdtVDIZOFSEAfWzRXPFuJyPfqpA(i);
		}
	}

	protected override void IOIteHoWYMIdXUPYMcUTgwJmPXpoA()
	{
		base.IOIteHoWYMIdXUPYMcUTgwJmPXpoA();
		if (base.ugEcvEUjcYzrLriOHSDCiapaTNEm != VwAEfXIfCgCiohhuMMznDzgWRhLp.CompoundElement)
		{
			return;
		}
		bETiEQbYCrQRqCLRvbSAcJMPkrdD bETiEQbYCrQRqCLRvbSAcJMPkrdD = base.iDKoVNKBUFFkBevicPLoKjjnDSZL;
		if ((bETiEQbYCrQRqCLRvbSAcJMPkrdD == bETiEQbYCrQRqCLRvbSAcJMPkrdD.Axis2D || (uint)(bETiEQbYCrQRqCLRvbSAcJMPkrdD - 3) <= 2u) && PROjQYrpgSIdZjYqEnOaDHUXyBjG != null)
		{
			int num = dhMPxgNIozGOSCWblPFvccnEWDJI;
			for (int i = 0; i < num; i++)
			{
				hdKvZSMBobFalOMlTkDjSeXHEDLKA(1, new WkflcJKKhlDFbBrbgxTHkqcdvDwd(PROjQYrpgSIdZjYqEnOaDHUXyBjG[i], 16384 << i));
			}
		}
	}
}
