using Rewired;

[CustomClassObfuscation(renamePubIntMembers = false, renamePrivateMembers = false)]
internal interface LFxfRtFXyxgAjxbmpHDNQNxOPKov
{
	string keyCategory { get; }

	string key { get; }

	int autoGeneratedValueFlags { get; set; }
}
