using System;
using Rewired.Internal.Glyphs;
using Rewired.Internal.Localization;

internal abstract class pkYfefdEzaIkCbIAguLfpcVlgVJnc : ygZwNwIMhUCPvDceCIcxgnzserfbA
{
	protected KeyedGlyph[] fIgcsUCmnMbFlJRuCscVepQOCsmGb;

	public int dhMPxgNIozGOSCWblPFvccnEWDJI => JSWalVgNfayAAqqgkCDSfWJdaAMTB.hMtVUAEviNnyqkiTSEVFSjpeZUfm(base.ugEcvEUjcYzrLriOHSDCiapaTNEm, base.iDKoVNKBUFFkBevicPLoKjjnDSZL);

	public abstract object RbwazNyPnwaYWhMAtptGmUWlMPlHb(int P_0);

	public abstract string OKEtlQZtvOkFHmftvxtaSTbWLGsy(int P_0);

	protected pkYfefdEzaIkCbIAguLfpcVlgVJnc(JSWalVgNfayAAqqgkCDSfWJdaAMTB.VwAEfXIfCgCiohhuMMznDzgWRhLp P_0, JSWalVgNfayAAqqgkCDSfWJdaAMTB.bETiEQbYCrQRqCLRvbSAcJMPkrdD P_1)
		: base(P_0, P_1)
	{
	}

	protected pkYfefdEzaIkCbIAguLfpcVlgVJnc(yBPKsUhYrRiyCEpVcVcLwcBSjoGT P_0, JSWalVgNfayAAqqgkCDSfWJdaAMTB.VwAEfXIfCgCiohhuMMznDzgWRhLp P_1, JSWalVgNfayAAqqgkCDSfWJdaAMTB.bETiEQbYCrQRqCLRvbSAcJMPkrdD P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
	}

	protected override void izqgVCmGioijeoXrjYwAEVccIJMK()
	{
		int num = dhMPxgNIozGOSCWblPFvccnEWDJI;
		fIgcsUCmnMbFlJRuCscVepQOCsmGb = null;
		if (num > 0)
		{
			fIgcsUCmnMbFlJRuCscVepQOCsmGb = new KeyedGlyph[num];
			for (int i = 0; i < num; i++)
			{
				fIgcsUCmnMbFlJRuCscVepQOCsmGb[i] = new KeyedGlyph();
			}
		}
		base.izqgVCmGioijeoXrjYwAEVccIJMK();
	}

	public virtual void yCbnuYjPdoDSWlofAupfOuHlfNOG(yBPKsUhYrRiyCEpVcVcLwcBSjoGT P_0)
	{
		yCbnuYjPdoDSWlofAupfOuHlfNOG((LFxfRtFXyxgAjxbmpHDNQNxOPKov)P_0);
	}

	public override void yCbnuYjPdoDSWlofAupfOuHlfNOG(LFxfRtFXyxgAjxbmpHDNQNxOPKov P_0)
	{
		base.yCbnuYjPdoDSWlofAupfOuHlfNOG(P_0);
		if (!(P_0 is yBPKsUhYrRiyCEpVcVcLwcBSjoGT))
		{
			throw new ArgumentException("value must implement " + typeof(yBPKsUhYrRiyCEpVcVcLwcBSjoGT));
		}
	}

	public override void OXcBXtPnTqYHpiucqKbwxkVzPkjf()
	{
		base.OXcBXtPnTqYHpiucqKbwxkVzPkjf();
		if (fIgcsUCmnMbFlJRuCscVepQOCsmGb != null)
		{
			for (int i = 0; i < dhMPxgNIozGOSCWblPFvccnEWDJI; i++)
			{
				fIgcsUCmnMbFlJRuCscVepQOCsmGb[i].Clear();
			}
		}
	}

	public override bool TUibHCXgdJpNwgxVPYRazOMZLYAI(VNmGeGFSdUUKSjRvPzQEfrbImtru P_0)
	{
		if (!(P_0 is pkYfefdEzaIkCbIAguLfpcVlgVJnc pkYfefdEzaIkCbIAguLfpcVlgVJnc2))
		{
			return false;
		}
		if (!base.TUibHCXgdJpNwgxVPYRazOMZLYAI(P_0))
		{
			return false;
		}
		yBPKsUhYrRiyCEpVcVcLwcBSjoGT yBPKsUhYrRiyCEpVcVcLwcBSjoGT2 = jfPgAiHCXDOsCqPqzSwgbROIKKdw();
		yBPKsUhYrRiyCEpVcVcLwcBSjoGT yBPKsUhYrRiyCEpVcVcLwcBSjoGT3 = pkYfefdEzaIkCbIAguLfpcVlgVJnc2.jfPgAiHCXDOsCqPqzSwgbROIKKdw();
		if (yBPKsUhYrRiyCEpVcVcLwcBSjoGT2 == null != (yBPKsUhYrRiyCEpVcVcLwcBSjoGT3 == null))
		{
			return false;
		}
		if (yBPKsUhYrRiyCEpVcVcLwcBSjoGT2 != null)
		{
			int num = dhMPxgNIozGOSCWblPFvccnEWDJI;
			for (int i = 0; i < num; i++)
			{
				if (!string.Equals(yBPKsUhYrRiyCEpVcVcLwcBSjoGT2.GetSpecialElementKey(i), yBPKsUhYrRiyCEpVcVcLwcBSjoGT3.GetSpecialElementKey(i), StringComparison.Ordinal))
				{
					return false;
				}
			}
		}
		return true;
	}

	protected override void wJjPIIRJfHhEbGedUconecGfiwzgB()
	{
		base.wJjPIIRJfHhEbGedUconecGfiwzgB();
		if (fIgcsUCmnMbFlJRuCscVepQOCsmGb != null)
		{
			for (int i = 0; i < fIgcsUCmnMbFlJRuCscVepQOCsmGb.Length; i++)
			{
				fIgcsUCmnMbFlJRuCscVepQOCsmGb[i].Clear();
			}
		}
	}

	protected override void PWkFKbOvHOZIUAfzpEAIGeluRTIK(JSWalVgNfayAAqqgkCDSfWJdaAMTB.VEYElUHTAVQERqFafltfcwjOaUMyA P_0)
	{
		base.PWkFKbOvHOZIUAfzpEAIGeluRTIK(P_0);
		yBPKsUhYrRiyCEpVcVcLwcBSjoGT yBPKsUhYrRiyCEpVcVcLwcBSjoGT2 = jfPgAiHCXDOsCqPqzSwgbROIKKdw();
		if (yBPKsUhYrRiyCEpVcVcLwcBSjoGT2 == null || base.ugEcvEUjcYzrLriOHSDCiapaTNEm != JSWalVgNfayAAqqgkCDSfWJdaAMTB.VwAEfXIfCgCiohhuMMznDzgWRhLp.CompoundElement || !JSWalVgNfayAAqqgkCDSfWJdaAMTB.HiplrqmAxSeQEXpdvOXYKTZEASQi(base.iDKoVNKBUFFkBevicPLoKjjnDSZL, out var exlqDuEbMnCkpHMuXAQdzpkhfUUr))
		{
			return;
		}
		for (int i = 0; i < exlqDuEbMnCkpHMuXAQdzpkhfUUr.psjRAApvubFvKrvItiJJlxpacaQl; i++)
		{
			int num = 8388608 << i;
			if ((yBPKsUhYrRiyCEpVcVcLwcBSjoGT2.autoGeneratedValueFlags & num) == 0 && !string.IsNullOrEmpty(yBPKsUhYrRiyCEpVcVcLwcBSjoGT2.key) && string.IsNullOrEmpty(yBPKsUhYrRiyCEpVcVcLwcBSjoGT2.GetSpecialElementKey(i)))
			{
				string text = yBPKsUhYrRiyCEpVcVcLwcBSjoGT2.key;
				if (exlqDuEbMnCkpHMuXAQdzpkhfUUr.TIxnSRhPSalQFvQOFZaLLiQtwMIC(i).CFZgLeSNFyCLpaVLVUHQRDinORMQA.HasValue)
				{
					text = LocalizationManager.AppendToKeyAxisDirection(text, exlqDuEbMnCkpHMuXAQdzpkhfUUr.TIxnSRhPSalQFvQOFZaLLiQtwMIC(i).CFZgLeSNFyCLpaVLVUHQRDinORMQA.Value);
				}
				yBPKsUhYrRiyCEpVcVcLwcBSjoGT2.SetSpecialElementKey(i, text);
				yBPKsUhYrRiyCEpVcVcLwcBSjoGT2.autoGeneratedValueFlags |= num;
				UADvwlynuwapiHLmAmTBEEeQFLafA(num);
			}
		}
	}

	protected override void LiXAHjDsSjcjuheRSvInddHJDOVCA(JSWalVgNfayAAqqgkCDSfWJdaAMTB.MbnhNztvlYEMfnRNZAzRFTGcWsDiA P_0)
	{
		base.LiXAHjDsSjcjuheRSvInddHJDOVCA(P_0);
		yBPKsUhYrRiyCEpVcVcLwcBSjoGT yBPKsUhYrRiyCEpVcVcLwcBSjoGT2 = jfPgAiHCXDOsCqPqzSwgbROIKKdw();
		if (yBPKsUhYrRiyCEpVcVcLwcBSjoGT2 == null || ((uint)yBPKsUhYrRiyCEpVcVcLwcBSjoGT2.autoGeneratedValueFlags & (uint)P_0) == 0 || base.ugEcvEUjcYzrLriOHSDCiapaTNEm != JSWalVgNfayAAqqgkCDSfWJdaAMTB.VwAEfXIfCgCiohhuMMznDzgWRhLp.CompoundElement || !JSWalVgNfayAAqqgkCDSfWJdaAMTB.HiplrqmAxSeQEXpdvOXYKTZEASQi(base.iDKoVNKBUFFkBevicPLoKjjnDSZL, out var exlqDuEbMnCkpHMuXAQdzpkhfUUr))
		{
			return;
		}
		for (int i = 0; i < exlqDuEbMnCkpHMuXAQdzpkhfUUr.psjRAApvubFvKrvItiJJlxpacaQl; i++)
		{
			int num = 8388608 << i;
			if ((yBPKsUhYrRiyCEpVcVcLwcBSjoGT2.autoGeneratedValueFlags & num) != 0)
			{
				yBPKsUhYrRiyCEpVcVcLwcBSjoGT2.SetSpecialElementKey(i, null);
				yBPKsUhYrRiyCEpVcVcLwcBSjoGT2.autoGeneratedValueFlags &= ~num;
				UADvwlynuwapiHLmAmTBEEeQFLafA(num);
			}
		}
	}

	protected override JSWalVgNfayAAqqgkCDSfWJdaAMTB.MbnhNztvlYEMfnRNZAzRFTGcWsDiA cfJjiFeTHaaDjDguihuHBEeWpOdD(JSWalVgNfayAAqqgkCDSfWJdaAMTB.VEYElUHTAVQERqFafltfcwjOaUMyA P_0)
	{
		JSWalVgNfayAAqqgkCDSfWJdaAMTB.MbnhNztvlYEMfnRNZAzRFTGcWsDiA mbnhNztvlYEMfnRNZAzRFTGcWsDiA = base.cfJjiFeTHaaDjDguihuHBEeWpOdD(P_0);
		int num = dhMPxgNIozGOSCWblPFvccnEWDJI;
		if ((P_0 & JSWalVgNfayAAqqgkCDSfWJdaAMTB.VEYElUHTAVQERqFafltfcwjOaUMyA.Keys) != JSWalVgNfayAAqqgkCDSfWJdaAMTB.VEYElUHTAVQERqFafltfcwjOaUMyA.None)
		{
			for (int i = 0; i < num; i++)
			{
				mbnhNztvlYEMfnRNZAzRFTGcWsDiA = (JSWalVgNfayAAqqgkCDSfWJdaAMTB.MbnhNztvlYEMfnRNZAzRFTGcWsDiA)((int)mbnhNztvlYEMfnRNZAzRFTGcWsDiA | (8388608 << i));
			}
		}
		return mbnhNztvlYEMfnRNZAzRFTGcWsDiA;
	}

	protected new yBPKsUhYrRiyCEpVcVcLwcBSjoGT jfPgAiHCXDOsCqPqzSwgbROIKKdw()
	{
		return base.jfPgAiHCXDOsCqPqzSwgbROIKKdw() as yBPKsUhYrRiyCEpVcVcLwcBSjoGT;
	}

	protected override void kakEANoxNEASOrgsQDjgagRjuxdPA()
	{
		base.kakEANoxNEASOrgsQDjgagRjuxdPA();
		int num = dhMPxgNIozGOSCWblPFvccnEWDJI;
		for (int i = 0; i < num; i++)
		{
			RbwazNyPnwaYWhMAtptGmUWlMPlHb(i);
		}
	}

	protected override void IOIteHoWYMIdXUPYMcUTgwJmPXpoA()
	{
		base.IOIteHoWYMIdXUPYMcUTgwJmPXpoA();
	}
}
