using System;

internal class swEgtSymhLZsvYfSiwxRQqQbrUZt : LFxfRtFXyxgAjxbmpHDNQNxOPKov
{
	protected readonly ygZwNwIMhUCPvDceCIcxgnzserfbA tysgDrQrbyTPVOntjJDqNfDrdNii;

	private readonly string gDcvfmMCiiUBoTMoJAByBPmpHaZIA;

	private readonly string iznbkRlQcoGkZtBlmfunFSNsZtUK;

	private int rDnRVTAZXyaVlJOBjDydLOTjrRpD;

	public ygZwNwIMhUCPvDceCIcxgnzserfbA qZphrAywinRGQldaZbzVDTvRRYwCA => tysgDrQrbyTPVOntjJDqNfDrdNii;

	string LFxfRtFXyxgAjxbmpHDNQNxOPKov.keyCategory => gDcvfmMCiiUBoTMoJAByBPmpHaZIA;

	string LFxfRtFXyxgAjxbmpHDNQNxOPKov.key => iznbkRlQcoGkZtBlmfunFSNsZtUK;

	int LFxfRtFXyxgAjxbmpHDNQNxOPKov.autoGeneratedValueFlags
	{
		get
		{
			return rDnRVTAZXyaVlJOBjDydLOTjrRpD;
		}
		set
		{
			rDnRVTAZXyaVlJOBjDydLOTjrRpD = value;
		}
	}

	public string keyCategory => gDcvfmMCiiUBoTMoJAByBPmpHaZIA;

	public string key => iznbkRlQcoGkZtBlmfunFSNsZtUK;

	public swEgtSymhLZsvYfSiwxRQqQbrUZt(ygZwNwIMhUCPvDceCIcxgnzserfbA P_0, string P_1, string P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException();
		}
		tysgDrQrbyTPVOntjJDqNfDrdNii = P_0;
		gDcvfmMCiiUBoTMoJAByBPmpHaZIA = P_1;
		iznbkRlQcoGkZtBlmfunFSNsZtUK = P_2;
		P_0.yCbnuYjPdoDSWlofAupfOuHlfNOG(this);
	}

	public virtual bool TUibHCXgdJpNwgxVPYRazOMZLYAI(swEgtSymhLZsvYfSiwxRQqQbrUZt P_0)
	{
		if (P_0 == null)
		{
			return false;
		}
		if ((object)GetType() != P_0.GetType())
		{
			return false;
		}
		if (!tysgDrQrbyTPVOntjJDqNfDrdNii.TUibHCXgdJpNwgxVPYRazOMZLYAI(P_0.tysgDrQrbyTPVOntjJDqNfDrdNii))
		{
			return false;
		}
		return true;
	}
}
