using System;
using Rewired.Internal.Localization;

internal class XXqMAmtzgVleMjCfPcHhdJZaHOvVA : jtAeQMwqfCHdCmeHvhaRCqwDmBxb
{
	protected readonly JSWalVgNfayAAqqgkCDSfWJdaAMTB SLPfoLEFsScnNhJxiHwVjPkEzuFMe;

	private readonly string gDcvfmMCiiUBoTMoJAByBPmpHaZIA;

	private readonly string QRfEvQGkxAAmTtQRZAtNCppjfWeEb;

	private string zLUoBtdnVFFcDcbREckOKwQUGmGEA;

	private readonly string iznbkRlQcoGkZtBlmfunFSNsZtUK;

	private int rDnRVTAZXyaVlJOBjDydLOTjrRpD;

	public JSWalVgNfayAAqqgkCDSfWJdaAMTB RFjHapmZhUbePVVdFDdJBEtHxRzt => SLPfoLEFsScnNhJxiHwVjPkEzuFMe;

	string jtAeQMwqfCHdCmeHvhaRCqwDmBxb.keyCategory => gDcvfmMCiiUBoTMoJAByBPmpHaZIA;

	string jtAeQMwqfCHdCmeHvhaRCqwDmBxb.scriptingName => QRfEvQGkxAAmTtQRZAtNCppjfWeEb;

	string jtAeQMwqfCHdCmeHvhaRCqwDmBxb.nonLocalizedDescriptiveName
	{
		get
		{
			return zLUoBtdnVFFcDcbREckOKwQUGmGEA;
		}
		set
		{
			zLUoBtdnVFFcDcbREckOKwQUGmGEA = value;
		}
	}

	string jtAeQMwqfCHdCmeHvhaRCqwDmBxb.key => iznbkRlQcoGkZtBlmfunFSNsZtUK;

	int jtAeQMwqfCHdCmeHvhaRCqwDmBxb.autoGeneratedValueFlags
	{
		get
		{
			return rDnRVTAZXyaVlJOBjDydLOTjrRpD;
		}
		set
		{
			rDnRVTAZXyaVlJOBjDydLOTjrRpD = value;
		}
	}

	public string keyCategory => gDcvfmMCiiUBoTMoJAByBPmpHaZIA;

	public string scriptingName => QRfEvQGkxAAmTtQRZAtNCppjfWeEb;

	public string jXwgbYbEpdqHGeBdCbXEcskUaWaFA
	{
		get
		{
			if (!LocalizationManager.isEnabled)
			{
				return zLUoBtdnVFFcDcbREckOKwQUGmGEA;
			}
			return SLPfoLEFsScnNhJxiHwVjPkEzuFMe.jXwgbYbEpdqHGeBdCbXEcskUaWaFA;
		}
	}

	public string nonLocalizedDescriptiveName => zLUoBtdnVFFcDcbREckOKwQUGmGEA;

	public string key => iznbkRlQcoGkZtBlmfunFSNsZtUK;

	public XXqMAmtzgVleMjCfPcHhdJZaHOvVA(JSWalVgNfayAAqqgkCDSfWJdaAMTB P_0, string P_1, string P_2, string P_3, string P_4)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException();
		}
		SLPfoLEFsScnNhJxiHwVjPkEzuFMe = P_0;
		gDcvfmMCiiUBoTMoJAByBPmpHaZIA = P_1;
		QRfEvQGkxAAmTtQRZAtNCppjfWeEb = P_2;
		zLUoBtdnVFFcDcbREckOKwQUGmGEA = P_3;
		iznbkRlQcoGkZtBlmfunFSNsZtUK = P_4;
		P_0.yCbnuYjPdoDSWlofAupfOuHlfNOG(this);
	}

	public virtual bool TUibHCXgdJpNwgxVPYRazOMZLYAI(XXqMAmtzgVleMjCfPcHhdJZaHOvVA P_0, bool P_1)
	{
		if (P_0 == null)
		{
			return false;
		}
		if ((object)GetType() != P_0.GetType())
		{
			return false;
		}
		if (!SLPfoLEFsScnNhJxiHwVjPkEzuFMe.TUibHCXgdJpNwgxVPYRazOMZLYAI(P_0.SLPfoLEFsScnNhJxiHwVjPkEzuFMe, P_1))
		{
			return false;
		}
		return true;
	}
}
