<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>KitchenMode</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>8.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Unity.Entities">
      <HintPath>..\..\Assemblies\Unity.Entities.dll</HintPath>
    </Reference>
    <Reference Include="Kitchen.Common">
      <HintPath>..\..\Assemblies\Kitchen.Common.dll</HintPath>
    </Reference>
    <Reference Include="Kitchen.GameData">
      <HintPath>..\..\Assemblies\Kitchen.GameData.dll</HintPath>
    </Reference>
    <Reference Include="Kitchen.Layouts">
      <HintPath>..\..\Assemblies\Kitchen.Layouts.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Kitchen.Persistence">
      <HintPath>..\..\Assemblies\Kitchen.Persistence.dll</HintPath>
    </Reference>
    <Reference Include="Controllers">
      <HintPath>..\..\Assemblies\Controllers.dll</HintPath>
    </Reference>
    <Reference Include="ShapesRuntime">
      <HintPath>..\..\Assemblies\ShapesRuntime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>..\..\Assemblies\Unity.Collections.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>..\..\Assemblies\Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\Assemblies\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\..\Assemblies\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VFXModule">
      <HintPath>..\..\Assemblies\UnityEngine.VFXModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\..\Assemblies\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>..\..\Assemblies\UnityEngine.AIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\Assemblies\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="MessagePack.Annotations">
      <HintPath>..\..\Assemblies\MessagePack.Annotations.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst">
      <HintPath>..\..\Assemblies\Unity.Burst.dll</HintPath>
    </Reference>
    <Reference Include="websocket-sharp">
      <HintPath>..\..\Assemblies\websocket-sharp.dll</HintPath>
    </Reference>
    <Reference Include="PlatformSettings">
      <HintPath>..\..\Assemblies\PlatformSettings.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\Assemblies\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Utilities">
      <HintPath>..\..\Assemblies\Sirenix.Utilities.dll</HintPath>
    </Reference>
    <Reference Include="Kitchen.Networking">
      <HintPath>..\..\Assemblies\Kitchen.Networking.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Jobs">
      <HintPath>..\..\Assemblies\Unity.Jobs.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>