using System;
using System.Collections.Generic;
using UnityEngine;

namespace EasyRoads3Dv3
{
	[Serializable]
	public class ERSOSection
	{
		public Vector3 startPosition;

		public Vector3 endPosition;

		public Vector3 p2;

		public Vector3 p3;

		public Vector3 ms1;

		public Vector3 ms2;

		public Vector3 ms3;

		public Vector3 ms4;

		public Vector3 me1;

		public Vector3 me2;

		public Vector3 me3;

		public Vector3 me4;

		public Vector3 startSplinePointOrig;

		public float startDistance;

		public int startSplinePointObject;

		public int startSplinePoint;

		public int endSplinePoint;

		public float startFraction;

		public float endFraction;

		public float hsStart;

		public float hsEnd;

		public int startSplinePointGeo;

		public float startDistanceGeo;

		public int endSplinePointGeo;

		public float endDistanceGeo;

		public float maxHeightDifference;

		public float startTunnelDistance;

		public float endTunnelDistance;

		public SideObject so;

		public bool forceSo;

		public ERRoadSide roadSide;

		public double soid;

		public bool acceptBarriers;

		public bool active;

		public double linkedSoId1;

		public double linkedSoId2;

		public float snapIndentWidthStart;

		public float snapIndentWidthEnd;

		public float geoStartOffset;

		public float geoEndOffset;

		public float innerStartOffset;

		public float innerEndOffset;

		public bool autoGenerated;

		public ERSOSection(Vector3 _startPos, Vector3 _endPos, int _startIndex, int _endIndex, float _startFraction, float _endFraction, float _hsStart, float _hsEnd)
		{
			startPosition = _startPos;
			endPosition = _endPos;
			p2 = Vector3.zero;
			p3 = Vector3.zero;
			ms1 = Vector3.zero;
			ms2 = Vector3.zero;
			ms3 = Vector3.zero;
			ms4 = Vector3.zero;
			me1 = Vector3.zero;
			me2 = Vector3.zero;
			me3 = Vector3.zero;
			me4 = Vector3.zero;
			startSplinePoint = (startSplinePointObject = _startIndex);
			endSplinePoint = _endIndex;
			startFraction = _startFraction;
			endFraction = _endFraction;
			hsStart = _hsStart;
			hsEnd = _hsEnd;
			so = null;
			soid = 0.0;
			active = true;
			roadSide = ERRoadSide.Left;
			startSplinePointOrig = Vector3.zero;
			startDistance = 0f;
			acceptBarriers = false;
			startSplinePointGeo = 0;
			startDistanceGeo = 0f;
			endSplinePointGeo = 0;
			maxHeightDifference = 0f;
			endDistanceGeo = 0f;
			linkedSoId1 = 0.0;
			linkedSoId2 = 0.0;
			forceSo = false;
			snapIndentWidthStart = 0.5f;
			snapIndentWidthEnd = 0.5f;
			geoStartOffset = 0f;
			geoEndOffset = 0f;
			innerStartOffset = 0f;
			innerEndOffset = 0f;
			autoGenerated = true;
		}

		public static ERSOSection GetERSOSection(ERModularRoad road, int listIndex, ref int index, int leftright, ref string soType, ref List<ERSOSection> sections)
		{
			List<ERSOSection> list;
			switch (listIndex)
			{
			case 1:
				soType = "Tunnel";
				sections = road.soSectionList1;
				list = road.soSectionList1;
				break;
			case 2:
				soType = "Bridge";
				sections = road.soSectionList2;
				list = road.soSectionList2;
				break;
			case 3:
				soType = "Barrier";
				sections = road.soSectionList3;
				list = road.soSectionList3;
				break;
			case 4:
				soType = "Barrier";
				sections = road.soSectionList4;
				list = road.soSectionList4;
				break;
			case 5:
				soType = "Prop";
				sections = road.soSectionList5;
				list = road.soSectionList5;
				break;
			case 6:
				soType = "Retaining Wall";
				sections = road.soSectionList6;
				list = road.soSectionList6;
				break;
			case 7:
				soType = "Retaining Wall";
				sections = road.soSectionList7;
				list = road.soSectionList7;
				break;
			default:
				soType = "Vegetation";
				sections = road.soSectionList8;
				list = road.soSectionList8;
				break;
			}
			if (list.Count > index)
			{
				return list[index];
			}
			return new ERSOSection(Vector3.zero, Vector3.zero, 0, 0, 0f, 0f, 0f, 0f);
		}

		public static ERSOSection OQQCDOOODQ(ERSOSection target, ERSOSection source)
		{
			if (target.endSplinePoint >= source.startSplinePoint)
			{
				target.endSplinePoint = source.startSplinePoint - 1;
				target.endFraction = 1f - source.startFraction;
			}
			return target;
		}

		public void OODDCOCDOD()
		{
			if (so != null)
			{
				soid = so.id;
				innerStartOffset = so.innerStartOffset;
				innerEndOffset = so.innerEndOffset;
				snapIndentWidthStart = (snapIndentWidthEnd = so.snapIndentWidth);
			}
		}

		public void GetERSectionSO(List<SideObject> sideobjects)
		{
			for (int i = 0; i < sideobjects.Count; i++)
			{
				if (sideobjects[i] != null && soid == sideobjects[i].id)
				{
					so = sideobjects[i];
					break;
				}
			}
		}
	}
}
