internal sealed class XvfBmdEgRnvPsKlrVzgfyacaJCJKA
{
	public static readonly HgnaIMWLxDFBogoGAwoPjgchNwNZA AKqFJNcCMqkRvTsdKqExdqSUHKvrA = ZmPCOajDQDMMfeJWlOgbdnUIsNUuA.rZJfWTWBbYKNCgYznEeSrijQUGGg(RnFErNcXnuQmSJTGLSCHmcqwWZbx.DeviceNotConnected);
}
