using UnityEngine;
using UnityEngine.InputSystem;

namespace AllIn1SpriteShader
{
	public static class InputKeyConverter
	{
		public static Key GetKeyFromKeycode(KeyCode keyCode)
		{
			Key key = Key.Space;
			return keyCode switch
			{
				KeyCode.A => Key.A, 
				KeyCode.B => Key.B, 
				KeyCode.C => Key.C, 
				KeyCode.D => Key.D, 
				KeyCode.E => Key.E, 
				KeyCode.F => Key.F, 
				KeyCode.G => Key.G, 
				KeyCode.H => Key.H, 
				KeyCode.I => Key.I, 
				KeyCode.J => Key.J, 
				KeyCode.K => Key.K, 
				KeyCode.L => Key.L, 
				KeyCode.M => Key.M, 
				KeyCode.N => Key.N, 
				KeyCode.O => Key.O, 
				KeyCode.P => Key.P, 
				KeyCode.Q => Key.Q, 
				KeyCode.R => Key.R, 
				KeyCode.S => Key.S, 
				KeyCode.T => Key.T, 
				KeyCode.U => Key.U, 
				KeyCode.V => Key.V, 
				KeyCode.W => Key.W, 
				KeyCode.X => Key.X, 
				KeyCode.Y => Key.Y, 
				KeyCode.Z => Key.Z, 
				KeyCode.Alpha0 => Key.Digit0, 
				KeyCode.Alpha1 => Key.Digit1, 
				KeyCode.Alpha2 => Key.Digit2, 
				KeyCode.Alpha3 => Key.Digit3, 
				KeyCode.Alpha4 => Key.Digit4, 
				KeyCode.Alpha5 => Key.Digit5, 
				KeyCode.Alpha6 => Key.Digit6, 
				KeyCode.Alpha7 => Key.Digit7, 
				KeyCode.Alpha8 => Key.Digit8, 
				KeyCode.Alpha9 => Key.Digit9, 
				KeyCode.Space => Key.Space, 
				KeyCode.Return => Key.Enter, 
				KeyCode.Escape => Key.Escape, 
				KeyCode.Backspace => Key.Backspace, 
				KeyCode.Tab => Key.Tab, 
				KeyCode.LeftShift => Key.LeftShift, 
				KeyCode.RightShift => Key.RightShift, 
				KeyCode.LeftControl => Key.LeftCtrl, 
				KeyCode.RightControl => Key.RightCtrl, 
				KeyCode.LeftAlt => Key.LeftAlt, 
				KeyCode.RightAlt => Key.RightAlt, 
				KeyCode.LeftMeta => Key.LeftMeta, 
				KeyCode.RightMeta => Key.RightMeta, 
				KeyCode.LeftWindows => Key.LeftMeta, 
				KeyCode.RightWindows => Key.RightMeta, 
				KeyCode.UpArrow => Key.UpArrow, 
				KeyCode.DownArrow => Key.DownArrow, 
				KeyCode.LeftArrow => Key.LeftArrow, 
				KeyCode.RightArrow => Key.RightArrow, 
				KeyCode.F1 => Key.F1, 
				KeyCode.F2 => Key.F2, 
				KeyCode.F3 => Key.F3, 
				KeyCode.F4 => Key.F4, 
				KeyCode.F5 => Key.F5, 
				KeyCode.F6 => Key.F6, 
				KeyCode.F7 => Key.F7, 
				KeyCode.F8 => Key.F8, 
				KeyCode.F9 => Key.F9, 
				KeyCode.F10 => Key.F10, 
				KeyCode.F11 => Key.F11, 
				KeyCode.F12 => Key.F12, 
				KeyCode.Insert => Key.Insert, 
				KeyCode.Delete => Key.Delete, 
				KeyCode.Home => Key.Home, 
				KeyCode.End => Key.End, 
				KeyCode.PageUp => Key.PageUp, 
				KeyCode.PageDown => Key.PageDown, 
				KeyCode.Keypad0 => Key.Numpad0, 
				KeyCode.Keypad1 => Key.Numpad1, 
				KeyCode.Keypad2 => Key.Numpad2, 
				KeyCode.Keypad3 => Key.Numpad3, 
				KeyCode.Keypad4 => Key.Numpad4, 
				KeyCode.Keypad5 => Key.Numpad5, 
				KeyCode.Keypad6 => Key.Numpad6, 
				KeyCode.Keypad7 => Key.Numpad7, 
				KeyCode.Keypad8 => Key.Numpad8, 
				KeyCode.Keypad9 => Key.Numpad9, 
				KeyCode.KeypadDivide => Key.NumpadDivide, 
				KeyCode.KeypadMultiply => Key.NumpadMultiply, 
				KeyCode.KeypadMinus => Key.NumpadMinus, 
				KeyCode.KeypadPlus => Key.NumpadPlus, 
				KeyCode.KeypadEnter => Key.NumpadEnter, 
				KeyCode.KeypadPeriod => Key.NumpadPeriod, 
				KeyCode.CapsLock => Key.CapsLock, 
				KeyCode.ScrollLock => Key.ScrollLock, 
				KeyCode.Pause => Key.Pause, 
				KeyCode.Quote => Key.Quote, 
				KeyCode.Comma => Key.Comma, 
				KeyCode.Minus => Key.Minus, 
				KeyCode.Period => Key.Period, 
				KeyCode.Slash => Key.Slash, 
				KeyCode.Semicolon => Key.Semicolon, 
				KeyCode.Equals => Key.Equals, 
				KeyCode.LeftBracket => Key.LeftBracket, 
				KeyCode.RightBracket => Key.RightBracket, 
				KeyCode.Backslash => Key.Backslash, 
				KeyCode.BackQuote => Key.Backquote, 
				_ => Key.Space, 
			};
		}
	}
}
