<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>AwesomeTechnologies.VegetationStudioPro.Runtime</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>7.3</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>..\..\Assemblies\UnityEngine.TerrainModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>..\..\Assemblies\Unity.Collections.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Postprocessing.Runtime">
      <HintPath>..\..\Assemblies\Unity.Postprocessing.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>..\..\Assemblies\Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.WindModule">
      <HintPath>..\..\Assemblies\UnityEngine.WindModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\Assemblies\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainPhysicsModule">
      <HintPath>..\..\Assemblies\UnityEngine.TerrainPhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst">
      <HintPath>..\..\Assemblies\Unity.Burst.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Jobs">
      <HintPath>..\..\Assemblies\Unity.Jobs.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>..\..\Assemblies\UnityEngine.AIModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\Assemblies\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule">
      <HintPath>..\..\Assemblies\UnityEngine.ScreenCaptureModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>