namespace Rewired
{
	[CustomObfuscation]
	internal enum InputPlatform
	{
		ZDPGOyOxRyXhnQTZSdtVDGTYxBB = 0,
		KJVDiztbBAwNhYcjGwnrWKTUrhs = 1,
		ooHKyaIxEPQWkTbMtnRDuNsiVDg = 2,
		yauYbxEsoJvMeznhaXrWCIMwfO = 3,
		jhxnDTiekitbCodTvBjImJLdBOh = 4,
		paCCgZCSgXFClmghvZDdjHYVFDe = 5,
		XVXaEhCzeYETTOguJCtUOyeuYrN = 6,
		aOvdosGEOEuXTVfOYLDtMHRGfHUd = 7,
		xmmAArCEtjLBfHAgQvgLGUNACCBk = 8,
		mYxkZYnNKgsQibnRKLRovdBEPVy = 9,
		cZQuPPypaGcsUqGWlBtTFLhvxwf = 10,
		DAtTLhhqwkArVmPVsLJcMbStFsD = 11,
		tATPiQdEmTcoxkglHrAXpeNIFqy = 12,
		JNAqeiptLqeBrJacQeDbHRPXsRnA = 13,
		cOczEKRSPubmRZlWIGNLjVbKuRGU = 14,
		DjBsXHAiWLaNoPBuNwidHlkOtuA = 15,
		KPLgtLDjUzbWWVUZPapTkcopMEGN = 16,
		BEsUNMrayMNKJtKuRDghaFXtOvBM = 17,
		jfGTKNJqAKBbngtHDrcbKKJRVXvj = 18,
		iYiwTSnIOKdJWLkqcBwYxNmEFmA = 19,
		NCBOeMZWSpUUMIimmghSgXNMoEA = 20,
		hCBxRIRvaYXOEsXCYwmWiFUAiKr = 21,
		ZcAZJubKXFQxeFfnJjQXkVuqhHal = 22,
		sMsrkAsILeGRHxCKlirHISgLmJIy = 23,
		jQlhYAigiDRWZpuLCSvKmyhkAPM = 24,
		fZXuunWCYupzgSisgTrggIfjoiY = 25,
		hxdIpPkfeaEBfnegdybBBHShluD = 26,
		uUcfAPcMPbHONlJvSbbDFNTWAbl = 27,
		jEZgGsvUOQPsKWePHyqIWDyOgXc = 28,
		hWngTbEqiKtCIoqiBgZTlrnMUHO = 29,
		yRLuKxJLdmikzATCpHQcGcRGQWvU = 30,
		LdYimWIedhBaJENKdCJzDGFlUmhP = 31,
		pguBJnVtmDUprmtuvypDKsVUQbe = 32,
		btBlLglZELkOrMoXqmFKRpujpMS = 33,
		QkinWSxMaRsZwWpDcCZfSLjNyKr = 34,
		QDEXJJzRtksYzHMOOjNdCBndUcp = 35,
		yhZbkKSLPeChMLLCxBJbawOrLrW = 36,
		ASRJVSvRTeNBjudtByibPkfyUPq = 37,
		NkCrbbzYWNRUPnjDDqsKwbGTAUT = 38,
		kpRKkTQudwHLRGjTDPVuUhldnp = 39,
		maxTjlEOFhbEqWpxicJCRFckcMn = 40,
		VwhidOOzUpNGsXWUmaxmGCWnakyk = 41,
		FdZsIibGTWzwByflGDRIZVseciX = 42
	}
}
