/**
 * gitignore-gen.js
 * ─────────────────────────────────────────────────────────────
 * Every run does a clean slate:
 *   1. Deletes the existing .gitignore (if any)
 *   2. Deletes ALL *.stub files found anywhere in the tree
 *   3. Scans every file recursively for files > threshold MB
 *   4. Writes a fresh .gitignore with those files listed
 *   5a. [default]  Creates a <filename>.stub next to each file
 *   5b. [root mode] Creates one filesIgnored.stub at the root
 *
 * Stub content is deterministic — no timestamps, no volatile
 * values — so re-runs only dirty stubs when files actually change.
 *
 * Usage:
 *   node gitignore-gen.js              ← threshold=100MB, individual stubs
 *   node gitignore-gen.js 95           ← threshold=95MB,  individual stubs
 *   node gitignore-gen.js root         ← threshold=100MB, single root stub
 *   node gitignore-gen.js 95 root      ← threshold=95MB,  single root stub
 *   node gitignore-gen.js root 95      ← same as above
 *
 * No external dependencies — Node.js built-ins only.
 * ─────────────────────────────────────────────────────────────
 */

const fs   = require('fs');
const path = require('path');

// ── Arg parsing — order-independent ──────────────────────────
// Accepts any mix of a numeric threshold and the literal "root"
// flag in argv[2] and argv[3], in either order.
const args      = process.argv.slice(2);
const ROOT_MODE = args.includes('root');
const numArg    = args.find(a => a !== 'root');

const THRESHOLD_MB = numArg ? parseFloat(numArg) : 100;

if (isNaN(THRESHOLD_MB) || THRESHOLD_MB <= 0) {
  const SCRIPT_NAME_ERR = path.basename(__filename);
  console.error(`\n❌  Invalid threshold: "${numArg}". Pass a positive number in MB.\n`);
  console.error(`    Examples:\n`);
  console.error(`      node ${SCRIPT_NAME_ERR} 95`);
  console.error(`      node ${SCRIPT_NAME_ERR} root`);
  console.error(`      node ${SCRIPT_NAME_ERR} 95 root\n`);
  process.exit(1);
}

// ── Config ────────────────────────────────────────────────────
const ROOT              = process.cwd();
const SCRIPT_NAME       = path.basename(__filename);
const GITIGNORE         = path.join(ROOT, '.gitignore');
const ROOT_STUB_NAME    = 'filesIgnored.stub';
const ROOT_STUB_PATH    = path.join(ROOT, ROOT_STUB_NAME);
const SKIP_DIRS         = new Set(['.git', 'node_modules', '.svn', '.hg']);
const THRESHOLD_BYTES   = THRESHOLD_MB * 1024 * 1024;

// ── Helpers ───────────────────────────────────────────────────
const toGitPath = (p) => path.relative(ROOT, p).replace(/\\/g, '/');

// 1 decimal place — used in both stub modes
const sizeMB = (b) => `${(b / (1024 ** 2)).toFixed(1)} MB`;

// Exact size for .gitignore comments only
function humanSize(bytes) {
  if (bytes >= 1073741824) return `${(bytes / 1073741824).toFixed(3)} GB`;
  if (bytes >= 1048576)    return `${(bytes / 1048576).toFixed(2)} MB`;
  return `${(bytes / 1024).toFixed(1)} KB`;
}

// ── Walk — collect oversized files AND all stub files ─────────
function walkDir(dir, oversized = [], stubs = []) {
  let entries;
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); }
  catch { return { oversized, stubs }; }

  for (const entry of entries) {
    if (entry.name === SCRIPT_NAME  && dir === ROOT) continue; // skip self
    if (entry.name === '.gitignore' && dir === ROOT) continue; // handle separately

    const full = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      walkDir(full, oversized, stubs);
    } else if (entry.isFile()) {
      // collect every *.stub for wiping — includes filesIgnored.stub
      if (entry.name.endsWith('.stub')) {
        stubs.push(full);
        continue;
      }

      try {
        const { size } = fs.statSync(full);
        if (size > THRESHOLD_BYTES) {
          oversized.push({ full, size, name: entry.name });
        }
      } catch { /* permission denied — skip */ }
    }
  }

  return { oversized, stubs };
}

// ── Build individual stub (JSON, next to original file) ───────
function buildStub(file) {
  return `{\n\t"ogFileName": "${file.name}",\n\t"ogFileSize": "${sizeMB(file.size)}"\n}`;
}

// ── Build root stub (one file, all entries) ───────────────────
// Format per line:  relative/path/to/file.ext: X.X MB
function buildRootStub(oversized) {
  const lines = oversized.map(f => `${toGitPath(f.full)}: ${sizeMB(f.size)}`);
  return lines.join('\n') + '\n';
}

// ── Build .gitignore ──────────────────────────────────────────
function buildGitignore(oversized) {
  const lines = [
    `# ── Generated by gitignore-gen.js ──────────────────────────`,
    `# ── Threshold : > ${THRESHOLD_MB} MB`,
    `# ── Files     : ${oversized.length} excluded`,
    `# ─────────────────────────────────────────────────────────────`,
    ``,
    `# Script itself`,
    `${SCRIPT_NAME}`,
    ``,
    `# Oversized files (> ${THRESHOLD_MB} MB)`,
  ];

  for (const f of oversized) {
    lines.push(`${f.gitPath}   # ${humanSize(f.size)}`);
  }

  lines.push('');
  return lines.join('\n');
}

// ── Wipe .gitignore ───────────────────────────────────────────
function wipeGitignore() {
  if (fs.existsSync(GITIGNORE)) { fs.unlinkSync(GITIGNORE); return true; }
  return false;
}

// ── Delete all stubs ──────────────────────────────────────────
function wipeStubs(stubs) {
  let deleted = 0, failed = 0;
  for (const p of stubs) {
    try { fs.unlinkSync(p); deleted++; }
    catch { failed++; }
  }
  return { deleted, failed };
}

// ── Main ──────────────────────────────────────────────────────
function main() {
  const divider = '─'.repeat(65);
  const modeTag = ROOT_MODE ? 'root stub' : 'individual stubs';

  console.log(`\n🚀  gitignore-gen.js — threshold: > ${THRESHOLD_MB} MB  [${modeTag}]`);
  console.log(`    Root: ${ROOT}\n`);
  console.log(divider);

  // ── PHASE 1: Scan ─────────────────────────────────────────────
  console.log(`\n🔍  Scanning tree...\n`);
  const { oversized, stubs } = walkDir(ROOT);
  oversized.sort((a, b) => b.size - a.size);

  console.log(`    Files > ${THRESHOLD_MB} MB : ${oversized.length}`);
  console.log(`    Stub files found   : ${stubs.length}`);

  // ── PHASE 2: Wipe .gitignore ──────────────────────────────────
  console.log(`\n${divider}`);
  console.log(`\n🗑️   Wiping old .gitignore...`);
  console.log(wipeGitignore() ? `    ✅ Deleted` : `    ℹ️  None existed`);

  // ── PHASE 3: Wipe all stubs ───────────────────────────────────
  console.log(`\n🗑️   Deleting all *.stub files...`);
  if (stubs.length === 0) {
    console.log(`    ℹ️  None found`);
  } else {
    const { deleted, failed } = wipeStubs(stubs);
    for (const s of stubs) console.log(`    ✖ ${path.relative(ROOT, s).replace(/\\/g, '/')}`);
    console.log(`\n    Deleted: ${deleted}  |  Failed: ${failed}`);
  }

  if (oversized.length === 0) {
    fs.writeFileSync(GITIGNORE, buildGitignore([]), 'utf8');
    console.log(`\n${divider}`);
    console.log(`\n✅  No files exceed ${THRESHOLD_MB} MB.`);
    console.log(`    Fresh .gitignore written (script-only exclusion).\n`);
    return;
  }

  // ── PHASE 4: Write fresh .gitignore ──────────────────────────
  console.log(`\n${divider}`);
  console.log(`\n📝  Writing fresh .gitignore...`);
  for (const f of oversized) f.gitPath = toGitPath(f.full);
  fs.writeFileSync(GITIGNORE, buildGitignore(oversized), 'utf8');
  console.log(`    ✅ Written — ${oversized.length} entr${oversized.length === 1 ? 'y' : 'ies'}`);

  // ── PHASE 5a: Root mode — single filesIgnored.stub ───────────
  if (ROOT_MODE) {
    console.log(`\n${divider}`);
    console.log(`\n🗒️   Writing root stub...\n`);

    try {
      fs.writeFileSync(ROOT_STUB_PATH, buildRootStub(oversized), 'utf8');
      console.log(`    📄 ${ROOT_STUB_NAME}  (${oversized.length} entr${oversized.length === 1 ? 'y' : 'ies'})`);
      for (const f of oversized) {
        console.log(`       ${toGitPath(f.full)}: ${sizeMB(f.size)}`);
      }
    } catch (err) {
      console.warn(`    ⚠️  Failed to write ${ROOT_STUB_NAME} — ${err.message}`);
    }

    console.log(`\n${divider}`);
    console.log(`\n📊  Summary:`);
    console.log(`    Mode                   : root stub`);
    console.log(`    Threshold              : > ${THRESHOLD_MB} MB`);
    console.log(`    Old stubs deleted      : ${stubs.length}`);
    console.log(`    Files ignored          : ${oversized.length}`);
    console.log(`    Root stub              : ${ROOT_STUB_NAME}`);

    console.log(`\n💡  Next steps:`);
    console.log(`    git add .gitignore`);
    console.log(`    git add ${ROOT_STUB_NAME}`);
    console.log(`    git commit -m "Ignore files over ${THRESHOLD_MB}MB, refresh root stub"`);
    console.log(`    git push\n`);
    return;
  }

  // ── PHASE 5b: Default mode — individual stubs ────────────────
  console.log(`\n${divider}`);
  console.log(`\n🗒️   Creating stub files...\n`);

  let stubsOk = 0, stubsFail = 0;

  for (const file of oversized) {
    const stubPath = file.full + '.stub';
    const relStub  = path.relative(ROOT, stubPath).replace(/\\/g, '/');
    try {
      fs.writeFileSync(stubPath, buildStub(file), 'utf8');
      console.log(`    📄 ${relStub}`);
      stubsOk++;
    } catch (err) {
      console.warn(`    ⚠️  Failed: ${relStub} — ${err.message}`);
      stubsFail++;
    }
  }

  console.log(`\n${divider}`);
  console.log(`\n📊  Summary:`);
  console.log(`    Mode                   : individual stubs`);
  console.log(`    Threshold              : > ${THRESHOLD_MB} MB`);
  console.log(`    Old stubs deleted      : ${stubs.length}`);
  console.log(`    Files ignored          : ${oversized.length}`);
  console.log(`    New stubs created      : ${stubsOk}`);
  if (stubsFail) console.log(`    Stub creation failures : ${stubsFail}`);

  console.log(`\n💡  Next steps:`);
  console.log(`    git add .gitignore`);
  console.log(`    git add "**/*.stub"`);
  console.log(`    git commit -m "Ignore files over ${THRESHOLD_MB}MB, refresh stubs"`);
  console.log(`    git push\n`);
}

main();