<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Timberborn.TailDecalSystem</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Timberborn.SingletonSystem">
      <HintPath>..\..\Assemblies\Timberborn.SingletonSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EnterableSystem">
      <HintPath>..\..\Assemblies\Timberborn.EnterableSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BlueprintSystem">
      <HintPath>..\..\Assemblies\Timberborn.BlueprintSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.DecalSystem">
      <HintPath>..\..\Assemblies\Timberborn.DecalSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.WorldPersistence">
      <HintPath>..\..\Assemblies\Timberborn.WorldPersistence.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Characters">
      <HintPath>..\..\Assemblies\Timberborn.Characters.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.NeedSystem">
      <HintPath>..\..\Assemblies\Timberborn.NeedSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TemplateInstantiation">
      <HintPath>..\..\Assemblies\Timberborn.TemplateInstantiation.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Persistence">
      <HintPath>..\..\Assemblies\Timberborn.Persistence.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BaseComponentSystem">
      <HintPath>..\..\Assemblies\Timberborn.BaseComponentSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EntitySystem">
      <HintPath>..\..\Assemblies\Timberborn.EntitySystem.dll</HintPath>
    </Reference>
    <Reference Include="Bindito.Core">
      <HintPath>..\..\Assemblies\Bindito.Core.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Beavers">
      <HintPath>..\..\Assemblies\Timberborn.Beavers.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>