<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Timberborn.GatheringUI</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Timberborn.CoreUI">
      <HintPath>..\..\Assemblies\Timberborn.CoreUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TooltipSystem">
      <HintPath>..\..\Assemblies\Timberborn.TooltipSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.YieldingUI">
      <HintPath>..\..\Assemblies\Timberborn.YieldingUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Localization">
      <HintPath>..\..\Assemblies\Timberborn.Localization.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.GoodsUI">
      <HintPath>..\..\Assemblies\Timberborn.GoodsUI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BaseComponentSystem">
      <HintPath>..\..\Assemblies\Timberborn.BaseComponentSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.DropdownSystem">
      <HintPath>..\..\Assemblies\Timberborn.DropdownSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Gathering">
      <HintPath>..\..\Assemblies\Timberborn.Gathering.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BatchControl">
      <HintPath>..\..\Assemblies\Timberborn.BatchControl.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections.Immutable">
      <HintPath>..\..\Assemblies\System.Collections.Immutable.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TemplateInstantiation">
      <HintPath>..\..\Assemblies\Timberborn.TemplateInstantiation.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EntityPanelSystem">
      <HintPath>..\..\Assemblies\Timberborn.EntityPanelSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Growing">
      <HintPath>..\..\Assemblies\Timberborn.Growing.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.NaturalResourcesLifecycle">
      <HintPath>..\..\Assemblies\Timberborn.NaturalResourcesLifecycle.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EntitySystem">
      <HintPath>..\..\Assemblies\Timberborn.EntitySystem.dll</HintPath>
    </Reference>
    <Reference Include="Bindito.Core">
      <HintPath>..\..\Assemblies\Bindito.Core.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.UIFormatters">
      <HintPath>..\..\Assemblies\Timberborn.UIFormatters.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Yielding">
      <HintPath>..\..\Assemblies\Timberborn.Yielding.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Goods">
      <HintPath>..\..\Assemblies\Timberborn.Goods.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Common">
      <HintPath>..\..\Assemblies\Timberborn.Common.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.YielderFinding">
      <HintPath>..\..\Assemblies\Timberborn.YielderFinding.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SimpleOutputBuildingsUI">
      <HintPath>..\..\Assemblies\Timberborn.SimpleOutputBuildingsUI.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>