<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Ionic.Zip</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net20</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Ionic.Zip.Resources.ZippedResources.zip" />
    <EmbeddedResource Include="Ionic.Zip.Resources.ZippedResources.zip" LogicalName="Ionic.Zip.Resources.ZippedResources.zip" />
  </ItemGroup>
  <ItemGroup />
</Project>