<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PlayFabPartySDK</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="PlayFab">
      <HintPath>..\..\Assemblies\PlayFab.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Microsoft.GDK">
      <HintPath>..\..\Assemblies\Unity.Microsoft.GDK.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>