<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>DV.SignPlacer</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>7.3</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\Assemblies\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="BezierCurves">
      <HintPath>..\..\Assemblies\BezierCurves.dll</HintPath>
    </Reference>
    <Reference Include="DV.RailTrack">
      <HintPath>..\..\Assemblies\DV.RailTrack.dll</HintPath>
    </Reference>
    <Reference Include="DV.Common">
      <HintPath>..\..\Assemblies\DV.Common.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="DV.SignPlacer.Utils">
      <HintPath>..\..\Assemblies\DV.SignPlacer.Utils.dll</HintPath>
    </Reference>
    <Reference Include="LINQtoGameObject">
      <HintPath>..\..\Assemblies\LINQtoGameObject.dll</HintPath>
    </Reference>
    <Reference Include="DV.OriginShiftInfo">
      <HintPath>..\..\Assemblies\DV.OriginShiftInfo.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>