namespace NJsonSchema.Validation
{
	public enum ValidationErrorKind
	{
		Unknown = 0,
		StringExpected = 1,
		NumberExpected = 2,
		IntegerExpected = 3,
		BooleanExpected = 4,
		ObjectExpected = 5,
		PropertyRequired = 6,
		ArrayExpected = 7,
		NullExpected = 8,
		PatternMismatch = 9,
		StringTooShort = 10,
		StringTooLong = 11,
		NumberTooSmall = 12,
		NumberTooBig = 13,
		IntegerTooBig = 14,
		TooManyItems = 15,
		TooFewItems = 16,
		ItemsNotUnique = 17,
		DateTimeExpected = 18,
		DateExpected = 19,
		TimeExpected = 20,
		TimeSpanExpected = 21,
		UriExpected = 22,
		IpV4Expected = 23,
		IpV6Expected = 24,
		GuidExpected = 25,
		NotAnyOf = 26,
		NotAllOf = 27,
		NotOneOf = 28,
		ExcludedSchemaValidates = 29,
		NumberNotMultipleOf = 30,
		IntegerNotMultipleOf = 31,
		NotInEnumeration = 32,
		EmailExpected = 33,
		HostnameExpected = 34,
		TooManyItemsInTuple = 35,
		ArrayItemNotValid = 36,
		AdditionalItemNotValid = 37,
		AdditionalPropertiesNotValid = 38,
		NoAdditionalPropertiesAllowed = 39,
		TooManyProperties = 40,
		TooFewProperties = 41,
		Base64Expected = 42,
		NoTypeValidates = 43,
		UuidExpected = 44
	}
}
