namespace Rewired
{
	[CustomObfuscation(rename = false)]
	internal enum InputPlatform
	{
		mWddvsAGGdWECRlxCOhehpBItyh = 0,
		nxzcJmevYVMAWQJHQoCKKweYMfMv = 1,
		TxthorEPmOLBHYyZxIReALnmNeM = 2,
		ZrSavanyxdsgnhdTbscQkWtEAzy = 3,
		EyNWaUwBjrKkvnlxbfIvCGetaIFY = 4,
		YRqjNMGyPIGPClpJpmPGREvRRcG = 5,
		sEjjrezmdTWEmzaCLMCrIvBsKtv = 6,
		PFLTzcYFaBOghAebEsCXymESHdk = 7,
		MUAhruUHigYSGBDKEDFejoaAIKbu = 8,
		LpFemRBnLvpZJDqbCUqPHDmhIPES = 9,
		ZsaDxCopXVftxhaUhaeehEFdpYT = 10,
		ihHkUizAxnFTofebgOcNeIKdjDdD = 11,
		ArpgvXxCfOlVSvkIJEIwRKgOTcG = 12,
		weyUTntvYvSMCYMOQToKrFyLWLT = 13,
		JdIptPBVWljvyIXqApempcOWYPa = 14,
		owpHBIMXRSAHRIGaFHvWdFAQwYa = 15,
		rypEUYaHNuXFnaKpDREuGUThbUgF = 16,
		ePYPwNnorHLXgaZGXMLQtvarFfn = 17,
		YzmOpGLKJXakWuQxDJNYoikTWXV = 18,
		VVULNUzeBDKyeIXYqiPFHOiKRFQ = 19,
		spryPJJRZoNXpNHWwjQrYqqOcQaE = 20,
		OIhUrHBapNKofzWuGXdbWpfEYqL = 21,
		uvinkbnCOUhiBIQPTivyCtHAuXUk = 22,
		BfEQfLyOjlOdysiRbIaosBjRLpg = 23,
		UNTAzLDwrIRHwWirSuYtaEQeELys = 24,
		AUxRFgGXRnMmNDDYccYLHOChnqyL = 25,
		IOPdHWmrObUEwmObrCgWvfxfehz = 26,
		RZICaWagIuKgaolDMOOypgwWFMH = 27,
		QAbfXJnvPJiIZJfOVOFDonsOFob = 28,
		AkZZquMxhXIVvnmCRwxaVZYYTek = 29,
		HglRpaPpklgbSOuqnDvBSmwGtUX = 30,
		svmFLfAwcmvduLqYnidKumuhopX = 31,
		SzWkkyLAdSLqShzUrBqqoRHKOhW = 32,
		AftxmphNLUuHCDzhgsurtHDpiKs = 33,
		tDSEXVttzObSTRvKkzvQqSrZkMJ = 34,
		nWmlkIpvopTHEIQiYbcEoLWzsmD = 35,
		ZttKGDSUEbTObEfblEyIYTXbRoc = 36,
		hzbbqXbtQbxKAebJVOPUbWKsXBI = 37,
		oDiIcinIBGOOyqKvDBdnWsbZGMv = 38,
		PWHiXxDBzketsYwZBiVoACMtEdP = 39,
		ZlXwEiQKEmyTNTNLkgHhdkHiqKF = 40,
		wHPBYVcSPaWTXCAyolOVCijkbqIm = 41,
		mvnXduzIcJqcHpJHCcDjxXAwuzv = 42
	}
}
