<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MotionSmoothing.Converters</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="MotionSmoothing.Authoring">
      <HintPath>..\..\Assemblies\MotionSmoothing.Authoring.dll</HintPath>
    </Reference>
    <Reference Include="PugConversion">
      <HintPath>..\..\Assemblies\PugConversion.dll</HintPath>
    </Reference>
    <Reference Include="MotionSmoothing.Components">
      <HintPath>..\..\Assemblies\MotionSmoothing.Components.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>