using System;
using Rewired.Internal.Localization;
using UnityEngine;

namespace Rewired
{
	[Serializable]
	public abstract class InputCategory : sZLAxvZSvDRmVjMjTVRhHfujppQp
	{
		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _name;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _descriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _key;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _tag;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected int _id;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected bool _userAssignable;

		[NonSerialized]
		private pdfeDVjdjwArmqtCcVAoNpExpqyM olAnABzSnDmqUWFVBktkrXWrvcnm;

		[NonSerialized]
		private int eztBtnnISvBuRVThZfYdtFhlXHUg;

		internal abstract string keyCategory { get; }

		public string name
		{
			get
			{
				return _name;
			}
			internal set
			{
				_name = text;
			}
		}

		public string descriptiveName
		{
			get
			{
				if (!ReInput.isReady || !LocalizationManager.isEnabled || olAnABzSnDmqUWFVBktkrXWrvcnm == null)
				{
					return _descriptiveName;
				}
				return olAnABzSnDmqUWFVBktkrXWrvcnm.HKQoqutKkgeGtFcRmtcKMQqgsDoY;
			}
			internal set
			{
				nonLocalizedDescriptiveName = text;
			}
		}

		public string tag
		{
			get
			{
				return _tag;
			}
			internal set
			{
				_tag = text;
			}
		}

		public int id
		{
			get
			{
				return _id;
			}
			internal set
			{
				_id = num;
			}
		}

		public bool userAssignable
		{
			get
			{
				return _userAssignable;
			}
			internal set
			{
				_userAssignable = flag;
			}
		}

		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return _key;
			}
			set
			{
				_key = value;
				if (ReInput.isReady && olAnABzSnDmqUWFVBktkrXWrvcnm != null)
				{
					olAnABzSnDmqUWFVBktkrXWrvcnm.yrhZMBOdOtpQsbmxygSzAaWtnMDfb();
				}
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
				if (ReInput.isReady && olAnABzSnDmqUWFVBktkrXWrvcnm != null)
				{
					olAnABzSnDmqUWFVBktkrXWrvcnm.XIvHPuMcrskwDDbqHcWqpyJRLTkr();
				}
			}
		}

		string sZLAxvZSvDRmVjMjTVRhHfujppQp.keyCategory => keyCategory;

		string sZLAxvZSvDRmVjMjTVRhHfujppQp.scriptingName => _name;

		string sZLAxvZSvDRmVjMjTVRhHfujppQp.nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
			}
		}

		string sZLAxvZSvDRmVjMjTVRhHfujppQp.key => _key;

		int sZLAxvZSvDRmVjMjTVRhHfujppQp.autoGeneratedValueFlags
		{
			get
			{
				return eztBtnnISvBuRVThZfYdtFhlXHUg;
			}
			set
			{
				eztBtnnISvBuRVThZfYdtFhlXHUg = value;
			}
		}

		public InputCategory()
		{
		}

		public InputCategory(InputCategory P_0)
		{
			_name = P_0._name;
			_descriptiveName = P_0._descriptiveName;
			_key = P_0._key;
			_tag = P_0._tag;
			_id = P_0._id;
			_userAssignable = P_0._userAssignable;
			eztBtnnISvBuRVThZfYdtFhlXHUg = P_0.eztBtnnISvBuRVThZfYdtFhlXHUg;
		}

		internal virtual void NAyVYtzaEfONhahjqQAdVIOhqgzK()
		{
			olAnABzSnDmqUWFVBktkrXWrvcnm = pdfeDVjdjwArmqtCcVAoNpExpqyM.FFjXRWNznybaCatfhwLUCHTjGTKc(this);
		}

		internal virtual void rPyGMUcMLMKquPkOtbvPcDKZHMI()
		{
		}
	}
}
