using System;
using Rewired.Internal.Localization;
using UnityEngine;

namespace Rewired
{
	[Serializable]
	public sealed class InputLayout : sZLAxvZSvDRmVjMjTVRhHfujppQp
	{
		private const string keyCategory = "controller_map/layout";

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _name;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _descriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _key;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private int _id;

		[NonSerialized]
		private pdfeDVjdjwArmqtCcVAoNpExpqyM aJSkHDmGBLNqpZeCcbYAEssVvKJF;

		[NonSerialized]
		private int ZLHHdSmpiHJeSShQpFPSdoFlqdXgA;

		public string name
		{
			get
			{
				return _name;
			}
			internal set
			{
				_name = text;
			}
		}

		public string descriptiveName
		{
			get
			{
				if (!ReInput.isReady || !LocalizationManager.isEnabled || aJSkHDmGBLNqpZeCcbYAEssVvKJF == null)
				{
					return _descriptiveName;
				}
				return aJSkHDmGBLNqpZeCcbYAEssVvKJF.HKQoqutKkgeGtFcRmtcKMQqgsDoY;
			}
			internal set
			{
				nonLocalizedDescriptiveName = text;
			}
		}

		public int id
		{
			get
			{
				return _id;
			}
			internal set
			{
				_id = num;
			}
		}

		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return _key;
			}
			set
			{
				_key = value;
				if (ReInput.isReady && aJSkHDmGBLNqpZeCcbYAEssVvKJF != null)
				{
					aJSkHDmGBLNqpZeCcbYAEssVvKJF.yrhZMBOdOtpQsbmxygSzAaWtnMDfb();
				}
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
				if (ReInput.isReady && aJSkHDmGBLNqpZeCcbYAEssVvKJF != null)
				{
					aJSkHDmGBLNqpZeCcbYAEssVvKJF.XIvHPuMcrskwDDbqHcWqpyJRLTkr();
				}
			}
		}

		string sZLAxvZSvDRmVjMjTVRhHfujppQp.keyCategory => "controller_map/layout";

		string sZLAxvZSvDRmVjMjTVRhHfujppQp.scriptingName => _name;

		string sZLAxvZSvDRmVjMjTVRhHfujppQp.nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
			}
		}

		string sZLAxvZSvDRmVjMjTVRhHfujppQp.key => _key;

		int sZLAxvZSvDRmVjMjTVRhHfujppQp.autoGeneratedValueFlags
		{
			get
			{
				return ZLHHdSmpiHJeSShQpFPSdoFlqdXgA;
			}
			set
			{
				ZLHHdSmpiHJeSShQpFPSdoFlqdXgA = value;
			}
		}

		public InputLayout()
		{
		}

		public InputLayout(InputLayout P_0)
			: this()
		{
			_name = P_0._name;
			_descriptiveName = P_0._descriptiveName;
			_key = P_0._key;
			_id = P_0._id;
			ZLHHdSmpiHJeSShQpFPSdoFlqdXgA = P_0.ZLHHdSmpiHJeSShQpFPSdoFlqdXgA;
		}

		public InputLayout Clone()
		{
			return new InputLayout(this);
		}

		internal void fIUUIApNfUaIAIZwlwUHqmEmCPkaA()
		{
			aJSkHDmGBLNqpZeCcbYAEssVvKJF = pdfeDVjdjwArmqtCcVAoNpExpqyM.FFjXRWNznybaCatfhwLUCHTjGTKc(this);
		}

		internal void oETCpZaiTgNLphnwhNGLpIfBsJdoD()
		{
		}
	}
}
