<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Timberborn.WorkshopsEffects</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Timberborn.Workshops">
      <HintPath>..\..\Assemblies\Timberborn.Workshops.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.InventorySystem">
      <HintPath>..\..\Assemblies\Timberborn.InventorySystem.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections.Immutable">
      <HintPath>..\..\Assemblies\System.Collections.Immutable.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Common">
      <HintPath>..\..\Assemblies\Timberborn.Common.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BlueprintSystem">
      <HintPath>..\..\Assemblies\Timberborn.BlueprintSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TimeSystem">
      <HintPath>..\..\Assemblies\Timberborn.TimeSystem.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SingletonSystem">
      <HintPath>..\..\Assemblies\Timberborn.SingletonSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EnterableSystem">
      <HintPath>..\..\Assemblies\Timberborn.EnterableSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TemplateInstantiation">
      <HintPath>..\..\Assemblies\Timberborn.TemplateInstantiation.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.CharacterModelSystem">
      <HintPath>..\..\Assemblies\Timberborn.CharacterModelSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TimbermeshAnimations">
      <HintPath>..\..\Assemblies\Timberborn.TimbermeshAnimations.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Particles">
      <HintPath>..\..\Assemblies\Timberborn.Particles.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Buildings">
      <HintPath>..\..\Assemblies\Timberborn.Buildings.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BehaviorSystem">
      <HintPath>..\..\Assemblies\Timberborn.BehaviorSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BaseComponentSystem">
      <HintPath>..\..\Assemblies\Timberborn.BaseComponentSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BlockSystem">
      <HintPath>..\..\Assemblies\Timberborn.BlockSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EntitySystem">
      <HintPath>..\..\Assemblies\Timberborn.EntitySystem.dll</HintPath>
    </Reference>
    <Reference Include="Bindito.Core">
      <HintPath>..\..\Assemblies\Bindito.Core.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TickSystem">
      <HintPath>..\..\Assemblies\Timberborn.TickSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.WorkSystem">
      <HintPath>..\..\Assemblies\Timberborn.WorkSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SlotSystem">
      <HintPath>..\..\Assemblies\Timberborn.SlotSystem.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>