using System;
using System.Collections;
using System.Collections.Generic;
using DV.StreamerExtensions;
using DV.Utils;
using UnityEngine;
using UnityEngine.SceneManagement;

[HelpURL("http://indago.homenko.pl/world-streamer/")]
public class Streamer : MonoBehaviour
{
	private const int MAX_PARALLEL_LOADING_FALLBACK = 1;

	public static bool unloadUnusedAssetsEnabled = false;

	public StreamerConcurrentManager concurrentManager;

	[Tooltip("This checkbox deactivates streamer and unload or doesn't load it's data.")]
	public bool streamerActive = true;

	public static string STREAMERTAG = "SceneStreamer";

	[Header("Scene Collection")]
	[Tooltip("Drag and drop here your scene collection prefab. You could find it in catalogue with scenes which were generated by scene splitter.")]
	public SceneCollection sceneCollection;

	public SceneSplit[] splits;

	[Header("Ranges")]
	[Tooltip("Distance in grid elements that you want hold loaded.")]
	public Vector3 loadingRange = new Vector3(3f, 3f, 3f);

	[Tooltip("Enables ring streaming.")]
	public bool useLoadingRangeMin;

	[Tooltip("Area that you want to cutout from loading range.")]
	public Vector3 loadingRangeMin = new Vector3(2f, 2f, 2f);

	[Tooltip("Distance in grid elements after which you want to unload assets.")]
	public Vector3 deloadingRange = new Vector3(3f, 3f, 3f);

	[Header("Settings")]
	[Tooltip("Frequancy in seconds in which you want to check if grid element is close /far enough to load/unload.")]
	public float positionCheckTime = 0.1f;

	[Tooltip("Time in seconds after which grid element will be unloaded.")]
	public float destroyTileDelay = 2f;

	[Tooltip("Number of empty frames between loading actions.")]
	public int sceneLoadWaitFrames = 2;

	[Space(10f)]
	[Tooltip("If you want to fix small holes from LODs system at unity terrain borders, drag and drop object here from scene hierarchy that contains our \"Terrain Neighbours\" script.")]
	public TerrainNeighbours terrainNeighbours;

	[Space(10f)]
	[Tooltip("Enable looping system, each layer is streamed independently, so if you want to synchronize them, they should have the same XYZ size. More info at manual.")]
	public bool looping;

	[Space(10f)]
	[Header("Player Settings")]
	[HideInInspector]
	public bool showLoadingScreen = true;

	[HideInInspector]
	public UILoadingStreamer loadingStreamer;

	[HideInInspector]
	public bool initialized;

	[HideInInspector]
	public int tilesToLoad = int.MaxValue;

	[HideInInspector]
	public int tilesLoaded;

	[HideInInspector]
	public Vector3 currentMove = Vector3.zero;

	[HideInInspector]
	public int xPos;

	[HideInInspector]
	public int yPos;

	[HideInInspector]
	public int zPos;

	public Dictionary<int[], SceneSplit> scenesArray;

	[HideInInspector]
	public List<SceneSplit> loadedScenes = new List<SceneSplit>();

	private HashSet<Vector3Int> loadedScenesCoords = new HashSet<Vector3Int>();

	private int currentlySceneLoading;

	private List<SceneSplit> scenesToLoad = new List<SceneSplit>();

	private int sceneLoadFrameNext;

	private bool sceneLoadFramesNextWaited;

	private int xLimity;

	private int xLimitx;

	private int xRange;

	private int yLimity;

	private int yLimitx;

	private int yRange;

	private int zLimity;

	private int zLimitx;

	private int zRange;

	private static bool canUnload = true;

	private static float waitTillNextUnload = 20f;

	private static bool unloadNext = false;

	private HashSet<AsyncOperation> pendingOperations = new HashSet<AsyncOperation>();

	public float LoadingProgress
	{
		get
		{
			if (tilesToLoad <= 0)
			{
				return 1f;
			}
			return (float)tilesLoaded / (float)tilesToLoad;
		}
	}

	public bool IsBusy => pendingOperations.Count > 0;

	public event Action Loaded;

	public event Action LoadingNewScenes;

	public event Action LoadedScenesChanged;

	private void Awake()
	{
		xPos = int.MinValue;
		yPos = int.MinValue;
		zPos = int.MinValue;
	}

	private void Start()
	{
		if ((bool)SingletonBehaviour<WorldMover>.Instance)
		{
			SingletonBehaviour<WorldMover>.Instance.WorldMoved += OnWorldMoved;
		}
		if (!concurrentManager)
		{
			Debug.LogError("Missing StreamerConcurrentManager on Streamer");
		}
		if (sceneCollection != null)
		{
			PrepareScenesArray();
			xLimity = sceneCollection.xLimitsy;
			xLimitx = sceneCollection.xLimitsx;
			xRange = xLimity + Mathf.Abs(xLimitx) + 1;
			yLimity = sceneCollection.yLimitsy;
			yLimitx = sceneCollection.yLimitsx;
			yRange = yLimity + Mathf.Abs(yLimitx) + 1;
			zLimity = sceneCollection.zLimitsy;
			zLimitx = sceneCollection.zLimitsx;
			zRange = zLimity + Mathf.Abs(zLimitx) + 1;
			StartCoroutine(PositionChecker());
			canUnload = true;
		}
		else
		{
			Debug.LogError("No scene collection in streamer");
		}
	}

	private void OnWorldMoved(WorldMover mover, Vector3 moveVector)
	{
		currentMove = WorldMover.currentMove;
		foreach (SceneSplit loadedScene in loadedScenes)
		{
			if (loadedScene.loaded && loadedScene.sceneGo != null)
			{
				loadedScene.sceneGo.transform.position -= moveVector;
			}
		}
	}

	private int mod(int x, int m)
	{
		return (x % m + m) % m;
	}

	public void AddSceneGO(string sceneName, GameObject sceneGO)
	{
		int posX = 0;
		int posY = 0;
		int posZ = 0;
		SceneNameToPos(sceneCollection, sceneName, out posX, out posY, out posZ);
		int[] key = new int[3] { posX, posY, posZ };
		if (scenesArray.ContainsKey(key))
		{
			scenesArray[key].sceneGo = sceneGO;
			sceneGO.transform.position += currentMove + new Vector3(scenesArray[key].posXLimitMove, scenesArray[key].posYLimitMove, scenesArray[key].posZLimitMove);
		}
		tilesLoaded++;
		currentlySceneLoading--;
		if ((bool)concurrentManager)
		{
			concurrentManager.currentlySceneLoadingAll--;
		}
		if ((bool)terrainNeighbours)
		{
			terrainNeighbours.CreateNeighbours();
		}
		loadedScenesCoords.Add(new Vector3Int(posX, posY, posZ));
		this.LoadedScenesChanged?.Invoke();
		if (LoadingProgress == 1f && this.Loaded != null)
		{
			this.Loaded();
		}
	}

	private void Update()
	{
		pendingOperations.RemoveWhere((AsyncOperation op) => op.isDone);
		LoadLevelAsyncManage();
	}

	private void LoadLevelAsyncManage()
	{
		if (scenesToLoad.Count <= 0 || currentlySceneLoading > 0)
		{
			return;
		}
		if (LoadingProgress < 1f || (sceneLoadFramesNextWaited && sceneLoadFrameNext <= 0))
		{
			sceneLoadFramesNextWaited = false;
			sceneLoadFrameNext = sceneLoadWaitFrames;
			int num = ((concurrentManager != null) ? concurrentManager.currentlySceneLoadingAll : currentlySceneLoading);
			int num2 = ((!(concurrentManager != null)) ? 1 : concurrentManager.maxParallelSceneLoading);
			while (num < num2 && scenesToLoad.Count > 0)
			{
				SceneSplit sceneSplit = scenesToLoad[0];
				scenesToLoad.Remove(sceneSplit);
				currentlySceneLoading++;
				if ((bool)concurrentManager)
				{
					concurrentManager.currentlySceneLoadingAll++;
				}
				Application.backgroundLoadingPriority = ThreadPriority.Low;
				pendingOperations.Add(SceneManager.LoadSceneAsync(sceneSplit.sceneName, LoadSceneMode.Additive));
			}
		}
		else
		{
			sceneLoadFramesNextWaited = true;
			sceneLoadFrameNext--;
		}
	}

	private IEnumerator PositionChecker()
	{
		while (true)
		{
			if (streamerActive && SingletonBehaviour<WorldMover>.Instance.playerTracker != null)
			{
				CheckPositionTiles();
			}
			else if (loadedScenes.Count > 0)
			{
				UnloadAllScenes();
				xPos = int.MinValue;
				yPos = int.MinValue;
				zPos = int.MinValue;
			}
			yield return WaitFor.SecondsRealtime(positionCheckTime);
		}
	}

	public void CheckPositionTiles()
	{
		AWorldMoverPlayerTracker playerTracker = SingletonBehaviour<WorldMover>.Instance.playerTracker;
		if (playerTracker.IsSynced())
		{
			Vector3 position = playerTracker.GetTrackerTransform().position;
			position -= currentMove;
			int num = ((sceneCollection.xSize != 0) ? Mathf.FloorToInt(position.x / (float)sceneCollection.xSize) : 0);
			int num2 = ((sceneCollection.ySize != 0) ? Mathf.FloorToInt(position.y / (float)sceneCollection.ySize) : 0);
			int num3 = ((sceneCollection.zSize != 0) ? Mathf.FloorToInt(position.z / (float)sceneCollection.zSize) : 0);
			if (num != xPos || num2 != yPos || num3 != zPos)
			{
				xPos = num;
				yPos = num2;
				zPos = num3;
				SceneLoading();
				StartCoroutine(InvokeDelayed(SceneUnloading, destroyTileDelay));
			}
		}
	}

	private static IEnumerator InvokeDelayed(Action action, float delay)
	{
		yield return WaitFor.SecondsRealtime(delay);
		action();
	}

	private void SceneLoading()
	{
		if (showLoadingScreen && loadingStreamer != null)
		{
			showLoadingScreen = false;
			if (tilesLoaded >= tilesToLoad)
			{
				tilesToLoad = int.MaxValue;
				tilesLoaded = 0;
			}
		}
		int num = 0;
		if (!useLoadingRangeMin)
		{
			int num2 = xPos;
			int num3 = yPos;
			int num4 = zPos;
			int[] array = new int[3] { num2, num3, num4 };
			float posXLimitMove = 0f;
			int num5 = 0;
			float posYLimitMove = 0f;
			int num6 = 0;
			float posZLimitMove = 0f;
			int num7 = 0;
			if (looping)
			{
				if (sceneCollection.xSplitIs)
				{
					int num8 = mod(num2 + Mathf.Abs(xLimitx), xRange) + xLimitx;
					num5 = (int)Math.Ceiling((float)(num2 - xLimity) / (float)xRange) * xRange;
					posXLimitMove = num5 * sceneCollection.xSize;
					array[0] = num8;
				}
				if (sceneCollection.ySplitIs)
				{
					int num9 = mod(num3 + Mathf.Abs(yLimitx), yRange) + yLimitx;
					num6 = (int)Math.Ceiling((float)(num3 - yLimity) / (float)yRange) * yRange;
					posYLimitMove = num6 * sceneCollection.ySize;
					array[1] = num9;
				}
				if (sceneCollection.zSplitIs)
				{
					int num10 = mod(num4 + Mathf.Abs(zLimitx), zRange) + zLimitx;
					num7 = (int)Math.Ceiling((float)(num4 - zLimity) / (float)zRange) * zRange;
					posZLimitMove = num7 * sceneCollection.zSize;
					array[2] = num10;
				}
			}
			if (scenesArray.ContainsKey(array))
			{
				SceneSplit sceneSplit = scenesArray[array];
				if (!sceneSplit.loaded)
				{
					sceneSplit.loaded = true;
					sceneSplit.posXLimitMove = posXLimitMove;
					sceneSplit.xDeloadLimit = num5;
					sceneSplit.posYLimitMove = posYLimitMove;
					sceneSplit.yDeloadLimit = num6;
					sceneSplit.posZLimitMove = posZLimitMove;
					sceneSplit.zDeloadLimit = num7;
					scenesToLoad.Add(sceneSplit);
					loadedScenes.Add(sceneSplit);
					num++;
				}
			}
		}
		for (int i = -(int)loadingRange.x + xPos; i <= (int)loadingRange.x + xPos; i++)
		{
			for (int j = -(int)loadingRange.y + yPos; j <= (int)loadingRange.y + yPos; j++)
			{
				for (int k = -(int)loadingRange.z + zPos; k <= (int)loadingRange.z + zPos; k++)
				{
					if (useLoadingRangeMin && (float)(i - xPos) >= 0f - loadingRangeMin.x && (float)(i - xPos) <= loadingRangeMin.x && (float)(j - yPos) >= 0f - loadingRangeMin.y && (float)(j - yPos) <= loadingRangeMin.y && (float)(k - zPos) >= 0f - loadingRangeMin.z && (float)(k - zPos) <= loadingRangeMin.z)
					{
						continue;
					}
					int[] array2 = new int[3] { i, j, k };
					float posXLimitMove2 = 0f;
					int num11 = 0;
					float posYLimitMove2 = 0f;
					int num12 = 0;
					float posZLimitMove2 = 0f;
					int num13 = 0;
					if (looping)
					{
						if (sceneCollection.xSplitIs)
						{
							int num14 = mod(i + Mathf.Abs(xLimitx), xRange) + xLimitx;
							num11 = (int)Math.Ceiling((float)(i - xLimity) / (float)xRange) * xRange;
							posXLimitMove2 = num11 * sceneCollection.xSize;
							array2[0] = num14;
						}
						if (sceneCollection.ySplitIs)
						{
							int num15 = mod(j + Mathf.Abs(yLimitx), yRange) + yLimitx;
							num12 = (int)Math.Ceiling((float)(j - yLimity) / (float)yRange) * yRange;
							posYLimitMove2 = num12 * sceneCollection.ySize;
							array2[1] = num15;
						}
						if (sceneCollection.zSplitIs)
						{
							int num16 = mod(k + Mathf.Abs(zLimitx), zRange) + zLimitx;
							num13 = (int)Math.Ceiling((float)(k - zLimity) / (float)zRange) * zRange;
							posZLimitMove2 = num13 * sceneCollection.zSize;
							array2[2] = num16;
						}
					}
					if (scenesArray.ContainsKey(array2))
					{
						SceneSplit sceneSplit2 = scenesArray[array2];
						if (!sceneSplit2.loaded)
						{
							sceneSplit2.loaded = true;
							sceneSplit2.posXLimitMove = posXLimitMove2;
							sceneSplit2.xDeloadLimit = num11;
							sceneSplit2.posYLimitMove = posYLimitMove2;
							sceneSplit2.yDeloadLimit = num12;
							sceneSplit2.posZLimitMove = posZLimitMove2;
							sceneSplit2.zDeloadLimit = num13;
							scenesToLoad.Add(sceneSplit2);
							loadedScenes.Add(sceneSplit2);
							num++;
						}
					}
				}
			}
		}
		tilesToLoad = num;
		initialized = true;
		this.LoadingNewScenes?.Invoke();
	}

	private void SceneUnloading()
	{
		List<SceneSplit> list = new List<SceneSplit>();
		foreach (SceneSplit loadedScene in loadedScenes)
		{
			if ((Mathf.Abs(loadedScene.posX + loadedScene.xDeloadLimit - xPos) > (int)deloadingRange.x || Mathf.Abs(loadedScene.posY + loadedScene.yDeloadLimit - yPos) > (int)deloadingRange.y || Mathf.Abs(loadedScene.posZ + loadedScene.zDeloadLimit - zPos) > (int)deloadingRange.x) && loadedScene.sceneGo != null)
			{
				list.Add(loadedScene);
			}
			if (useLoadingRangeMin && (float)Mathf.Abs(loadedScene.posX + loadedScene.xDeloadLimit - xPos) <= loadingRangeMin.x && (float)Mathf.Abs(loadedScene.posY + loadedScene.yDeloadLimit - yPos) <= loadingRangeMin.y && (float)Mathf.Abs(loadedScene.posZ + loadedScene.zDeloadLimit - zPos) <= loadingRangeMin.z && loadedScene.sceneGo != null)
			{
				list.Add(loadedScene);
			}
		}
		foreach (SceneSplit item in list)
		{
			loadedScenes.Remove(item);
			loadedScenesCoords.Remove(new Vector3Int(item.posX, item.posY, item.posZ));
			this.LoadedScenesChanged?.Invoke();
			if (item.sceneGo != null)
			{
				Terrain componentInChildren = item.sceneGo.GetComponentInChildren<Terrain>();
				if ((bool)componentInChildren)
				{
					GameObject obj = componentInChildren.gameObject;
					UnityEngine.Object.Destroy(componentInChildren);
					componentInChildren = null;
					UnityEngine.Object.Destroy(obj);
					obj = null;
				}
			}
			try
			{
				pendingOperations.Add(SceneManager.UnloadSceneAsync(item.sceneGo.scene.name));
			}
			catch (Exception ex)
			{
				Debug.Log(item.sceneName);
				Debug.Log(item.sceneGo.name);
				Debug.Log(item.sceneGo.scene.name);
				Debug.LogError(ex.Message);
			}
			item.sceneGo = null;
			item.loaded = false;
		}
		list.Clear();
		if ((bool)terrainNeighbours)
		{
			terrainNeighbours.CreateNeighbours();
		}
		UnloadAssets(this);
	}

	public void UnloadAllScenes()
	{
		foreach (KeyValuePair<int[], SceneSplit> item in scenesArray)
		{
			if (item.Value.sceneGo != null)
			{
				Terrain componentInChildren = item.Value.sceneGo.GetComponentInChildren<Terrain>();
				if ((bool)componentInChildren)
				{
					GameObject obj = componentInChildren.gameObject;
					UnityEngine.Object.Destroy(componentInChildren);
					componentInChildren = null;
					UnityEngine.Object.Destroy(obj);
					obj = null;
				}
				try
				{
					pendingOperations.Add(SceneManager.UnloadSceneAsync(item.Value.sceneGo.scene.name));
				}
				catch (Exception ex)
				{
					Debug.Log(item.Value.sceneName);
					Debug.Log(item.Value.sceneGo.name);
					Debug.Log(item.Value.sceneGo.scene.name);
					Debug.LogError(ex.Message);
				}
			}
			item.Value.loaded = false;
			item.Value.sceneGo = null;
		}
		loadedScenes.Clear();
		loadedScenesCoords.Clear();
		this.LoadedScenesChanged?.Invoke();
		if ((bool)terrainNeighbours)
		{
			terrainNeighbours.CreateNeighbours();
		}
		UnloadAssets(this);
	}

	public static void UnloadAssets(Streamer streamer)
	{
		if (canUnload)
		{
			canUnload = false;
			streamer.StartCoroutine(streamer.UnloadAssetsWait());
		}
		else
		{
			unloadNext = true;
		}
	}

	public IEnumerator UnloadAssetsWait()
	{
		do
		{
			unloadNext = false;
			if (unloadUnusedAssetsEnabled)
			{
				Debug.LogWarning("Streamer calling Resources.UnloadUnusedAssets()");
				Resources.UnloadUnusedAssets();
			}
			yield return WaitFor.SecondsRealtime(waitTillNextUnload);
		}
		while (unloadNext);
		canUnload = true;
	}

	private void PrepareScenesArray()
	{
		scenesArray = new Dictionary<int[], SceneSplit>(new IntArrayComparer());
		string[] names = sceneCollection.names;
		foreach (string text in names)
		{
			int posX = 0;
			int posY = 0;
			int posZ = 0;
			SceneNameToPos(sceneCollection, text, out posX, out posY, out posZ);
			SceneSplit sceneSplit = new SceneSplit();
			sceneSplit.posX = posX;
			sceneSplit.posY = posY;
			sceneSplit.posZ = posZ;
			sceneSplit.sceneName = text.Replace(".unity", "");
			scenesArray.Add(new int[3] { posX, posY, posZ }, sceneSplit);
		}
	}

	public static void SceneNameToPos(SceneCollection sceneCollection, string sceneName, out int posX, out int posY, out int posZ)
	{
		posX = 0;
		posY = 0;
		posZ = 0;
		string[] array = sceneName.Replace(sceneCollection.prefixScene, "").Replace(".unity", "").Split(new char[1] { '_' }, StringSplitOptions.RemoveEmptyEntries);
		foreach (string text in array)
		{
			if (text[0] == 'x')
			{
				posX = int.Parse(text.Replace("x", ""));
			}
			if (text[0] == 'y')
			{
				posY = int.Parse(text.Replace("y", ""));
			}
			if (text[0] == 'z')
			{
				posZ = int.Parse(text.Replace("z", ""));
			}
		}
	}

	public bool IsSceneLoaded(Vector3 worldPosition)
	{
		worldPosition -= currentMove;
		int x = ((sceneCollection.xSize != 0) ? Mathf.FloorToInt(worldPosition.x / (float)sceneCollection.xSize) : 0);
		int y = ((sceneCollection.ySize != 0) ? Mathf.FloorToInt(worldPosition.y / (float)sceneCollection.ySize) : 0);
		int z = ((sceneCollection.zSize != 0) ? Mathf.FloorToInt(worldPosition.z / (float)sceneCollection.zSize) : 0);
		return loadedScenesCoords.Contains(new Vector3Int(x, y, z));
	}

	private void OnDrawGizmosSelected()
	{
		if (!sceneCollection)
		{
			return;
		}
		Gizmos.color = sceneCollection.color;
		Vector3 vector = new Vector3((sceneCollection.xSize == 0) ? 2 : sceneCollection.xSize, (sceneCollection.ySize == 0) ? 2 : sceneCollection.ySize, (sceneCollection.zSize == 0) ? 2 : sceneCollection.zSize);
		for (int i = -(int)loadingRange.x + xPos; i <= (int)loadingRange.x + xPos; i++)
		{
			for (int j = -(int)loadingRange.y + yPos; j <= (int)loadingRange.y + yPos; j++)
			{
				for (int k = -(int)loadingRange.z + zPos; k <= (int)loadingRange.z + zPos; k++)
				{
					if (!useLoadingRangeMin || !((float)(i - xPos) >= 0f - loadingRangeMin.x) || !((float)(i - xPos) <= loadingRangeMin.x) || !((float)(j - yPos) >= 0f - loadingRangeMin.y) || !((float)(j - yPos) <= loadingRangeMin.y) || !((float)(k - zPos) >= 0f - loadingRangeMin.z) || !((float)(k - zPos) <= loadingRangeMin.z))
					{
						Gizmos.DrawWireCube(new Vector3((float)i * vector.x, (float)j * vector.y, (float)k * vector.z) + vector * 0.5f + currentMove, vector);
					}
				}
			}
		}
		Gizmos.color = Color.green;
		Gizmos.DrawWireCube(new Vector3((float)xPos * vector.x, (float)yPos * vector.y, (float)zPos * vector.z) + vector * 0.5f + currentMove, vector);
	}
}
