using System;
using Rewired;
using Rewired.Internal.Localization;

internal abstract class FVnuoKOpyokKSDbIoOCrfICafeofA : jjEiJGkdrKfqxJAsceTeoFkgoNMlA
{
	protected readonly LocalizedString ohXtJbzukpqYhFzWvsmuseRnBDXq;

	protected readonly LocalizedString OCzLbpNCojscfRvjNfUOhKqMgfKx;

	public abstract string UDfFJNMhCyBCNIpQLiHPdXQolEJqA { get; }

	public abstract string uHNCrEpNbRlmMRKTnwRRnCRKxuSl { get; }

	protected FVnuoKOpyokKSDbIoOCrfICafeofA(AqybaYFDSFEDwBRnsokwpBTdIblQ P_0, veVjxECKraSLRuRJUJeBWprfCtQDb P_1)
		: base(P_0, P_1)
	{
		ohXtJbzukpqYhFzWvsmuseRnBDXq = new LocalizedString();
		OCzLbpNCojscfRvjNfUOhKqMgfKx = new LocalizedString();
	}

	protected FVnuoKOpyokKSDbIoOCrfICafeofA(LiukxMkkUUmGsEJaoRyGyuSBQfoS P_0, AqybaYFDSFEDwBRnsokwpBTdIblQ P_1, veVjxECKraSLRuRJUJeBWprfCtQDb P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
		ohXtJbzukpqYhFzWvsmuseRnBDXq = new LocalizedString();
		OCzLbpNCojscfRvjNfUOhKqMgfKx = new LocalizedString();
	}

	protected virtual void dZYWtgxBEVCgdsvJyRZKYkoIEbVN()
	{
		ocwkkmZurlqfuKPEalGIqdmTGdXI();
	}

	public virtual void ewPsHlWWYTNcyUKQvfYlqnQsGFIs(LiukxMkkUUmGsEJaoRyGyuSBQfoS P_0)
	{
		robwaoxSKinucgPcyrfEovhcOMTl(P_0);
	}

	public virtual void uTjzKuQbXnFnUkMHyqTLWtMLloT(LnhaMJXLiFbdSGpizhhMTtFDjtXy P_0)
	{
		base.robwaoxSKinucgPcyrfEovhcOMTl(P_0);
		if (!(P_0 is LiukxMkkUUmGsEJaoRyGyuSBQfoS))
		{
			throw new ArgumentException("value must implement " + typeof(LiukxMkkUUmGsEJaoRyGyuSBQfoS));
		}
	}

	public virtual void pkQOYNewTiTecNKgWCjFKIdJVQgAA()
	{
		uogVoxebOaalYvSMFHpEhkktkqiEA();
		ohXtJbzukpqYhFzWvsmuseRnBDXq.Clear();
		OCzLbpNCojscfRvjNfUOhKqMgfKx.Clear();
	}

	public virtual void EWQFLjzfSdmFqspyzLNsTwkxqbHW()
	{
		URVTChhdPhlphEvyvsHKScBWvFun();
		ohXtJbzukpqYhFzWvsmuseRnBDXq.Clear();
		OCzLbpNCojscfRvjNfUOhKqMgfKx.Clear();
	}

	public void VuVdZdXGdeIJzaBSwYHRlsLFNplKA()
	{
		ohXtJbzukpqYhFzWvsmuseRnBDXq.Clear();
		ZkeNHOSKcvJlBczdcxBaeQXQJqfE(QtSxnZYSjrgthBpvYZqvQdRfKXUE.Keys);
	}

	public void qlVAzkNPkdiObBjuNJQIapVdyFbBB()
	{
		OCzLbpNCojscfRvjNfUOhKqMgfKx.Clear();
		ZkeNHOSKcvJlBczdcxBaeQXQJqfE(QtSxnZYSjrgthBpvYZqvQdRfKXUE.Keys);
	}

	public void BrqPcLzhJFhYTJVIHnKPgptmKoCR()
	{
		ohXtJbzukpqYhFzWvsmuseRnBDXq.Clear();
		ZkeNHOSKcvJlBczdcxBaeQXQJqfE(QtSxnZYSjrgthBpvYZqvQdRfKXUE.Names);
	}

	public void oTvzCizjOSehqAUOHakMGgqsXjxJA()
	{
		OCzLbpNCojscfRvjNfUOhKqMgfKx.Clear();
		ZkeNHOSKcvJlBczdcxBaeQXQJqfE(QtSxnZYSjrgthBpvYZqvQdRfKXUE.Names);
	}

	public virtual bool fqPRoHVJYdrViBpxmANelSJECdpeA(xhsfjMHWBKokSPBLxdeojZhcJxoeA P_0, bool P_1)
	{
		if (!(P_0 is FVnuoKOpyokKSDbIoOCrfICafeofA fVnuoKOpyokKSDbIoOCrfICafeofA))
		{
			return false;
		}
		if (!buRpSpFySsnOwisfqOOesjuLfQTJ(P_0, P_1))
		{
			return false;
		}
		LiukxMkkUUmGsEJaoRyGyuSBQfoS liukxMkkUUmGsEJaoRyGyuSBQfoS = CbftpsrIhwCScSmLFIFoGulCutQo();
		LiukxMkkUUmGsEJaoRyGyuSBQfoS liukxMkkUUmGsEJaoRyGyuSBQfoS2 = fVnuoKOpyokKSDbIoOCrfICafeofA.CbftpsrIhwCScSmLFIFoGulCutQo();
		if (liukxMkkUUmGsEJaoRyGyuSBQfoS == null != (liukxMkkUUmGsEJaoRyGyuSBQfoS2 == null))
		{
			return false;
		}
		if (liukxMkkUUmGsEJaoRyGyuSBQfoS != null && P_1 && (!string.Equals(liukxMkkUUmGsEJaoRyGyuSBQfoS.positiveKey, liukxMkkUUmGsEJaoRyGyuSBQfoS2.positiveKey, StringComparison.Ordinal) || !string.Equals(liukxMkkUUmGsEJaoRyGyuSBQfoS.negativeKey, liukxMkkUUmGsEJaoRyGyuSBQfoS2.negativeKey, StringComparison.Ordinal) || !string.Equals(liukxMkkUUmGsEJaoRyGyuSBQfoS.nonLocalizedPositiveDescriptiveName, liukxMkkUUmGsEJaoRyGyuSBQfoS2.nonLocalizedPositiveDescriptiveName, StringComparison.Ordinal) || !string.Equals(liukxMkkUUmGsEJaoRyGyuSBQfoS.nonLocalizedNegativeDescriptiveName, liukxMkkUUmGsEJaoRyGyuSBQfoS2.nonLocalizedNegativeDescriptiveName, StringComparison.Ordinal)))
		{
			return false;
		}
		return true;
	}

	protected virtual void wgWFdhzWCfahPBKkMKAAElKUMwHq()
	{
		UMcCdLWmjevbDnqFgUwpyXSLsnWp();
		ohXtJbzukpqYhFzWvsmuseRnBDXq.Clear();
		OCzLbpNCojscfRvjNfUOhKqMgfKx.Clear();
	}

	protected virtual void wGXYLdFZsRnHLkQcvzrogHhPZeRD(QtSxnZYSjrgthBpvYZqvQdRfKXUE P_0)
	{
		base.ZkeNHOSKcvJlBczdcxBaeQXQJqfE(P_0);
		LiukxMkkUUmGsEJaoRyGyuSBQfoS liukxMkkUUmGsEJaoRyGyuSBQfoS = CbftpsrIhwCScSmLFIFoGulCutQo();
		if (liukxMkkUUmGsEJaoRyGyuSBQfoS == null)
		{
			return;
		}
		if ((liukxMkkUUmGsEJaoRyGyuSBQfoS.autoGeneratedValueFlags & 2) == 0 && string.IsNullOrEmpty(liukxMkkUUmGsEJaoRyGyuSBQfoS.nonLocalizedPositiveDescriptiveName) && HHOCnTbkRggJAtLOIhHuQDMTdOrZA(Pole.Positive))
		{
			liukxMkkUUmGsEJaoRyGyuSBQfoS.nonLocalizedPositiveDescriptiveName = liukxMkkUUmGsEJaoRyGyuSBQfoS.nonLocalizedDescriptiveName;
			if (MmigdsDIDCIpncMJgWZsJaBnwTgq(Pole.Positive))
			{
				liukxMkkUUmGsEJaoRyGyuSBQfoS.nonLocalizedPositiveDescriptiveName = LocalizationManager.AppendToNameAxisPole(liukxMkkUUmGsEJaoRyGyuSBQfoS.nonLocalizedPositiveDescriptiveName, Pole.Positive);
			}
			liukxMkkUUmGsEJaoRyGyuSBQfoS.autoGeneratedValueFlags |= 2;
			yEJKXEtRylKddSbgoiIxUFVZUTMX(2);
		}
		if ((liukxMkkUUmGsEJaoRyGyuSBQfoS.autoGeneratedValueFlags & 4) == 0 && string.IsNullOrEmpty(liukxMkkUUmGsEJaoRyGyuSBQfoS.nonLocalizedNegativeDescriptiveName) && HHOCnTbkRggJAtLOIhHuQDMTdOrZA(Pole.Negative))
		{
			liukxMkkUUmGsEJaoRyGyuSBQfoS.nonLocalizedNegativeDescriptiveName = liukxMkkUUmGsEJaoRyGyuSBQfoS.nonLocalizedDescriptiveName;
			if (MmigdsDIDCIpncMJgWZsJaBnwTgq(Pole.Negative))
			{
				liukxMkkUUmGsEJaoRyGyuSBQfoS.nonLocalizedNegativeDescriptiveName = LocalizationManager.AppendToNameAxisPole(liukxMkkUUmGsEJaoRyGyuSBQfoS.nonLocalizedNegativeDescriptiveName, Pole.Negative);
			}
			liukxMkkUUmGsEJaoRyGyuSBQfoS.autoGeneratedValueFlags |= 4;
			yEJKXEtRylKddSbgoiIxUFVZUTMX(4);
		}
		if (string.IsNullOrEmpty(liukxMkkUUmGsEJaoRyGyuSBQfoS.key))
		{
			return;
		}
		if ((liukxMkkUUmGsEJaoRyGyuSBQfoS.autoGeneratedValueFlags & 8) == 0 && string.IsNullOrEmpty(liukxMkkUUmGsEJaoRyGyuSBQfoS.positiveKey) && HHOCnTbkRggJAtLOIhHuQDMTdOrZA(Pole.Positive))
		{
			liukxMkkUUmGsEJaoRyGyuSBQfoS.positiveKey = liukxMkkUUmGsEJaoRyGyuSBQfoS.key;
			if (MmigdsDIDCIpncMJgWZsJaBnwTgq(Pole.Positive))
			{
				liukxMkkUUmGsEJaoRyGyuSBQfoS.positiveKey = LocalizationManager.AppendToKeyAxisPole(liukxMkkUUmGsEJaoRyGyuSBQfoS.positiveKey, Pole.Positive);
			}
			liukxMkkUUmGsEJaoRyGyuSBQfoS.autoGeneratedValueFlags |= 8;
			yEJKXEtRylKddSbgoiIxUFVZUTMX(8);
		}
		if ((liukxMkkUUmGsEJaoRyGyuSBQfoS.autoGeneratedValueFlags & 0x10) == 0 && string.IsNullOrEmpty(liukxMkkUUmGsEJaoRyGyuSBQfoS.negativeKey) && HHOCnTbkRggJAtLOIhHuQDMTdOrZA(Pole.Negative))
		{
			liukxMkkUUmGsEJaoRyGyuSBQfoS.negativeKey = liukxMkkUUmGsEJaoRyGyuSBQfoS.key;
			if (MmigdsDIDCIpncMJgWZsJaBnwTgq(Pole.Negative))
			{
				liukxMkkUUmGsEJaoRyGyuSBQfoS.negativeKey = LocalizationManager.AppendToKeyAxisPole(liukxMkkUUmGsEJaoRyGyuSBQfoS.negativeKey, Pole.Negative);
			}
			liukxMkkUUmGsEJaoRyGyuSBQfoS.autoGeneratedValueFlags |= 16;
			yEJKXEtRylKddSbgoiIxUFVZUTMX(16);
		}
	}

	protected virtual void yWseKFrmvmkIRRZalVnPhxFpTfAL(oTYnvuyaZmGssrtKlgjPUrEEwolk P_0)
	{
		base.yDzbfaLEJphcSkTjzHYGsryjYvCjA(P_0);
		LiukxMkkUUmGsEJaoRyGyuSBQfoS liukxMkkUUmGsEJaoRyGyuSBQfoS = CbftpsrIhwCScSmLFIFoGulCutQo();
		if (liukxMkkUUmGsEJaoRyGyuSBQfoS != null && ((uint)liukxMkkUUmGsEJaoRyGyuSBQfoS.autoGeneratedValueFlags & (uint)P_0) != 0)
		{
			if ((P_0 & oTYnvuyaZmGssrtKlgjPUrEEwolk.PositiveKey) != oTYnvuyaZmGssrtKlgjPUrEEwolk.None && (liukxMkkUUmGsEJaoRyGyuSBQfoS.autoGeneratedValueFlags & 8) != 0)
			{
				liukxMkkUUmGsEJaoRyGyuSBQfoS.positiveKey = null;
				yEJKXEtRylKddSbgoiIxUFVZUTMX(8);
				liukxMkkUUmGsEJaoRyGyuSBQfoS.autoGeneratedValueFlags &= -9;
			}
			if ((P_0 & oTYnvuyaZmGssrtKlgjPUrEEwolk.NegativeKey) != oTYnvuyaZmGssrtKlgjPUrEEwolk.None && (liukxMkkUUmGsEJaoRyGyuSBQfoS.autoGeneratedValueFlags & 0x10) != 0)
			{
				liukxMkkUUmGsEJaoRyGyuSBQfoS.negativeKey = null;
				yEJKXEtRylKddSbgoiIxUFVZUTMX(16);
				liukxMkkUUmGsEJaoRyGyuSBQfoS.autoGeneratedValueFlags &= -17;
			}
			if ((P_0 & oTYnvuyaZmGssrtKlgjPUrEEwolk.PositiveDescriptiveName) != oTYnvuyaZmGssrtKlgjPUrEEwolk.None && (liukxMkkUUmGsEJaoRyGyuSBQfoS.autoGeneratedValueFlags & 2) != 0)
			{
				liukxMkkUUmGsEJaoRyGyuSBQfoS.nonLocalizedPositiveDescriptiveName = null;
				yEJKXEtRylKddSbgoiIxUFVZUTMX(2);
				liukxMkkUUmGsEJaoRyGyuSBQfoS.autoGeneratedValueFlags &= -3;
			}
			if ((P_0 & oTYnvuyaZmGssrtKlgjPUrEEwolk.NegativeDescriptiveName) != oTYnvuyaZmGssrtKlgjPUrEEwolk.None && (liukxMkkUUmGsEJaoRyGyuSBQfoS.autoGeneratedValueFlags & 4) != 0)
			{
				liukxMkkUUmGsEJaoRyGyuSBQfoS.nonLocalizedNegativeDescriptiveName = null;
				yEJKXEtRylKddSbgoiIxUFVZUTMX(4);
				liukxMkkUUmGsEJaoRyGyuSBQfoS.autoGeneratedValueFlags &= -5;
			}
		}
	}

	protected virtual oTYnvuyaZmGssrtKlgjPUrEEwolk kMamLGgMCCTBucPEWAGajnmooadR(QtSxnZYSjrgthBpvYZqvQdRfKXUE P_0)
	{
		oTYnvuyaZmGssrtKlgjPUrEEwolk oTYnvuyaZmGssrtKlgjPUrEEwolk = base.yaKwzIfaeqvJqzbBTjbIPAiLOtPd(P_0);
		if ((P_0 & QtSxnZYSjrgthBpvYZqvQdRfKXUE.Keys) != QtSxnZYSjrgthBpvYZqvQdRfKXUE.None)
		{
			oTYnvuyaZmGssrtKlgjPUrEEwolk |= (oTYnvuyaZmGssrtKlgjPUrEEwolk)24;
		}
		if ((P_0 & QtSxnZYSjrgthBpvYZqvQdRfKXUE.Names) != QtSxnZYSjrgthBpvYZqvQdRfKXUE.None)
		{
			oTYnvuyaZmGssrtKlgjPUrEEwolk |= (oTYnvuyaZmGssrtKlgjPUrEEwolk)6;
		}
		return oTYnvuyaZmGssrtKlgjPUrEEwolk;
	}

	protected LiukxMkkUUmGsEJaoRyGyuSBQfoS CbftpsrIhwCScSmLFIFoGulCutQo()
	{
		return RZKDbaDlqKvZBfkLJCkUzoaxqLAwA() as LiukxMkkUUmGsEJaoRyGyuSBQfoS;
	}

	protected virtual bool MmigdsDIDCIpncMJgWZsJaBnwTgq(Pole P_0)
	{
		return base.LJXAbEKxmDHBiYmUZFbAJTxfIUxj switch
		{
			AqybaYFDSFEDwBRnsokwpBTdIblQ.Axis => true, 
			AqybaYFDSFEDwBRnsokwpBTdIblQ.Button => false, 
			_ => false, 
		};
	}

	protected virtual bool HHOCnTbkRggJAtLOIhHuQDMTdOrZA(Pole P_0)
	{
		return base.LJXAbEKxmDHBiYmUZFbAJTxfIUxj switch
		{
			AqybaYFDSFEDwBRnsokwpBTdIblQ.Axis => true, 
			AqybaYFDSFEDwBRnsokwpBTdIblQ.Button => P_0 switch
			{
				Pole.Positive => true, 
				Pole.Negative => false, 
				_ => false, 
			}, 
			_ => false, 
		};
	}

	protected virtual void NaeGjYJHzNVefpNzrNrTGYRaQhMyb()
	{
		base.WWbQWIkCrHILkmvtSGPWgKBbHyFQ();
		_ = UDfFJNMhCyBCNIpQLiHPdXQolEJqA;
		_ = uHNCrEpNbRlmMRKTnwRRnCRKxuSl;
	}

	protected virtual void FUOlVNcydPdFmSLbiIEIDXvoPIJw()
	{
		aZzOkurvWhsbADLEqQAdGQZVlQRx();
		WfYxlWKheRqSPhxWVoclUcggslZQ(1, new eHmaJdrNOVirmgtpoujzQtBnLiexA
		{
			FodEZfUyahnacEwWYFigPPfEgiKo = 6
		});
		WfYxlWKheRqSPhxWVoclUcggslZQ(8, new eHmaJdrNOVirmgtpoujzQtBnLiexA(ohXtJbzukpqYhFzWvsmuseRnBDXq, 2));
		WfYxlWKheRqSPhxWVoclUcggslZQ(16, new eHmaJdrNOVirmgtpoujzQtBnLiexA(OCzLbpNCojscfRvjNfUOhKqMgfKx, 4));
		WfYxlWKheRqSPhxWVoclUcggslZQ(2, new eHmaJdrNOVirmgtpoujzQtBnLiexA
		{
			sigTNzHcEgiAMnBdNaAdaLOmuMJG = ohXtJbzukpqYhFzWvsmuseRnBDXq
		});
		WfYxlWKheRqSPhxWVoclUcggslZQ(4, new eHmaJdrNOVirmgtpoujzQtBnLiexA
		{
			sigTNzHcEgiAMnBdNaAdaLOmuMJG = OCzLbpNCojscfRvjNfUOhKqMgfKx
		});
	}
}
