using System;
using Rewired.Internal.Localization;

internal class pfetedQbitdObLxnJcXDFUggaTfnA : LnhaMJXLiFbdSGpizhhMTtFDjtXy
{
	protected readonly jjEiJGkdrKfqxJAsceTeoFkgoNMlA VJgSDVHgvwYvhqOdEZfHWeoLjeaEA;

	private readonly string gGEnIrdQBgymBylItIrYdgtIBjlmA;

	private readonly string zNazrHIrOdmWUkDCoOIEOpynQqTc;

	private string bpJdhVkvfKeEXdvBkAuqFPzVhTwY;

	private readonly string cLrVSCZurgjBnKqWWNIRUxryOWTr;

	private int zBHhlyCZSIOVQbPvgebnocKrrjPy;

	public jjEiJGkdrKfqxJAsceTeoFkgoNMlA aOhQIONsIpURLhjvhVnGKJRxbNfBA => VJgSDVHgvwYvhqOdEZfHWeoLjeaEA;

	string LnhaMJXLiFbdSGpizhhMTtFDjtXy.keyCategory => gGEnIrdQBgymBylItIrYdgtIBjlmA;

	string LnhaMJXLiFbdSGpizhhMTtFDjtXy.scriptingName => zNazrHIrOdmWUkDCoOIEOpynQqTc;

	string LnhaMJXLiFbdSGpizhhMTtFDjtXy.nonLocalizedDescriptiveName
	{
		get
		{
			return bpJdhVkvfKeEXdvBkAuqFPzVhTwY;
		}
		set
		{
			bpJdhVkvfKeEXdvBkAuqFPzVhTwY = value;
		}
	}

	string LnhaMJXLiFbdSGpizhhMTtFDjtXy.key => cLrVSCZurgjBnKqWWNIRUxryOWTr;

	int LnhaMJXLiFbdSGpizhhMTtFDjtXy.autoGeneratedValueFlags
	{
		get
		{
			return zBHhlyCZSIOVQbPvgebnocKrrjPy;
		}
		set
		{
			zBHhlyCZSIOVQbPvgebnocKrrjPy = value;
		}
	}

	public string keyCategory => gGEnIrdQBgymBylItIrYdgtIBjlmA;

	public string scriptingName => zNazrHIrOdmWUkDCoOIEOpynQqTc;

	public string PtvEiRywqMLUHZiGMBDrPChiQetC
	{
		get
		{
			if (!LocalizationManager.isEnabled)
			{
				return bpJdhVkvfKeEXdvBkAuqFPzVhTwY;
			}
			return VJgSDVHgvwYvhqOdEZfHWeoLjeaEA.qJkqRAxrrocPcPhIKAOpCMJUoZxfA;
		}
	}

	public string nonLocalizedDescriptiveName => bpJdhVkvfKeEXdvBkAuqFPzVhTwY;

	public string key => cLrVSCZurgjBnKqWWNIRUxryOWTr;

	public pfetedQbitdObLxnJcXDFUggaTfnA(jjEiJGkdrKfqxJAsceTeoFkgoNMlA P_0, string P_1, string P_2, string P_3, string P_4)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException();
		}
		VJgSDVHgvwYvhqOdEZfHWeoLjeaEA = P_0;
		gGEnIrdQBgymBylItIrYdgtIBjlmA = P_1;
		zNazrHIrOdmWUkDCoOIEOpynQqTc = P_2;
		bpJdhVkvfKeEXdvBkAuqFPzVhTwY = P_3;
		cLrVSCZurgjBnKqWWNIRUxryOWTr = P_4;
		P_0.robwaoxSKinucgPcyrfEovhcOMTl(this);
	}

	public virtual bool xAvEtPzMAmejwMLFXLySdnqPFWII(pfetedQbitdObLxnJcXDFUggaTfnA P_0, bool P_1)
	{
		if (P_0 == null)
		{
			return false;
		}
		if ((object)GetType() != P_0.GetType())
		{
			return false;
		}
		if (!VJgSDVHgvwYvhqOdEZfHWeoLjeaEA.fnknzfXTJAiyPjhBrqRTlqnPySbr(P_0.VJgSDVHgvwYvhqOdEZfHWeoLjeaEA, P_1))
		{
			return false;
		}
		return true;
	}
}
