using System;
using Rewired.Internal.Glyphs;
using Rewired.Internal.Localization;

internal abstract class ZcUMKmfyrUiAlcfAkYLRtdycPITr : CnLKLdvrkwwcGfIoKweJxFIiKujS
{
	protected KeyedGlyph[] iCRrnsUomQUWCPfyEpaBTRsSPPsI;

	public int eqIgsbSjportkHBSJpAEgrERuASX => jjEiJGkdrKfqxJAsceTeoFkgoNMlA.zIFHYKIYFbwXaLMpuqkDbbnkpdiD(base.EBtqAXtODeZFPNkhxWrjaFttagr, base.uxCljSdtaqwHXXSmSSwCKwRsbEEf);

	public abstract object zucaHsRbQvAxizbSaHWafpJbdPgD(int P_0);

	public abstract string voVHhOzLXBavqlBPsHiFgdoRxwhRA(int P_0);

	protected ZcUMKmfyrUiAlcfAkYLRtdycPITr(jjEiJGkdrKfqxJAsceTeoFkgoNMlA.AqybaYFDSFEDwBRnsokwpBTdIblQ P_0, jjEiJGkdrKfqxJAsceTeoFkgoNMlA.veVjxECKraSLRuRJUJeBWprfCtQDb P_1)
		: base(P_0, P_1)
	{
	}

	protected ZcUMKmfyrUiAlcfAkYLRtdycPITr(WXuKXKglhBEpgRBwkNznjqCddGcA P_0, jjEiJGkdrKfqxJAsceTeoFkgoNMlA.AqybaYFDSFEDwBRnsokwpBTdIblQ P_1, jjEiJGkdrKfqxJAsceTeoFkgoNMlA.veVjxECKraSLRuRJUJeBWprfCtQDb P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
	}

	protected virtual void YIVmiRsPaGvKICZtvfWfYjHtABhq()
	{
		int num = eqIgsbSjportkHBSJpAEgrERuASX;
		iCRrnsUomQUWCPfyEpaBTRsSPPsI = null;
		if (num > 0)
		{
			iCRrnsUomQUWCPfyEpaBTRsSPPsI = new KeyedGlyph[num];
			for (int i = 0; i < num; i++)
			{
				iCRrnsUomQUWCPfyEpaBTRsSPPsI[i] = new KeyedGlyph();
			}
		}
		GyvVuNpmOrQDAjpmjMcKZjKXHjHx();
	}

	public virtual void PrgHAeaORxIiOrWQpoefZWDaVSEw(WXuKXKglhBEpgRBwkNznjqCddGcA P_0)
	{
		wrVdvyaMppSpOxPfMIMhdQJhfgZHA(P_0);
	}

	public virtual void EyDGpFxORlZPAbhxDRRyOeSCnJuF(vfRBokPaPPEWJRenHDjJaOGZJkR P_0)
	{
		base.wrVdvyaMppSpOxPfMIMhdQJhfgZHA(P_0);
		if (!(P_0 is WXuKXKglhBEpgRBwkNznjqCddGcA))
		{
			throw new ArgumentException("value must implement " + typeof(WXuKXKglhBEpgRBwkNznjqCddGcA));
		}
	}

	public virtual void OMMLJspiNoUcRsKxAAWSbVPzIyMg()
	{
		gJuABohBdpRbYcPPGjzZMkOBbNcFe();
		if (iCRrnsUomQUWCPfyEpaBTRsSPPsI != null)
		{
			for (int i = 0; i < eqIgsbSjportkHBSJpAEgrERuASX; i++)
			{
				iCRrnsUomQUWCPfyEpaBTRsSPPsI[i].Clear();
			}
		}
	}

	public virtual bool roXakqckxWnFpPfHZVPpSJfeChkGA(tSkGCPxidsRshBOpBnQicfGGOeto P_0)
	{
		if (!(P_0 is ZcUMKmfyrUiAlcfAkYLRtdycPITr zcUMKmfyrUiAlcfAkYLRtdycPITr))
		{
			return false;
		}
		if (!mlqZuQkYZfHtGHypfzSZjaiiOeHG(P_0))
		{
			return false;
		}
		WXuKXKglhBEpgRBwkNznjqCddGcA wXuKXKglhBEpgRBwkNznjqCddGcA = JcVXBtzIHVFcGFQjhXopNbdOqVgb();
		WXuKXKglhBEpgRBwkNznjqCddGcA wXuKXKglhBEpgRBwkNznjqCddGcA2 = zcUMKmfyrUiAlcfAkYLRtdycPITr.JcVXBtzIHVFcGFQjhXopNbdOqVgb();
		if (wXuKXKglhBEpgRBwkNznjqCddGcA == null != (wXuKXKglhBEpgRBwkNznjqCddGcA2 == null))
		{
			return false;
		}
		if (wXuKXKglhBEpgRBwkNznjqCddGcA != null)
		{
			int num = eqIgsbSjportkHBSJpAEgrERuASX;
			for (int i = 0; i < num; i++)
			{
				if (!string.Equals(wXuKXKglhBEpgRBwkNznjqCddGcA.GetSpecialElementKey(i), wXuKXKglhBEpgRBwkNznjqCddGcA2.GetSpecialElementKey(i), StringComparison.Ordinal))
				{
					return false;
				}
			}
		}
		return true;
	}

	protected virtual void REjefnBoHkOVDSCeMopkBnweXtAq()
	{
		CHyiRkqsEJpAPoRxIgWYILFdOSfm();
		if (iCRrnsUomQUWCPfyEpaBTRsSPPsI != null)
		{
			for (int i = 0; i < iCRrnsUomQUWCPfyEpaBTRsSPPsI.Length; i++)
			{
				iCRrnsUomQUWCPfyEpaBTRsSPPsI[i].Clear();
			}
		}
	}

	protected virtual void DBovPluhLFcFCfUyAKQCrNBVMkbHb(jjEiJGkdrKfqxJAsceTeoFkgoNMlA.QtSxnZYSjrgthBpvYZqvQdRfKXUE P_0)
	{
		base.RCnuQGEZevjVGhQRlnERuzInQmqe(P_0);
		WXuKXKglhBEpgRBwkNznjqCddGcA wXuKXKglhBEpgRBwkNznjqCddGcA = JcVXBtzIHVFcGFQjhXopNbdOqVgb();
		if (wXuKXKglhBEpgRBwkNznjqCddGcA == null || base.EBtqAXtODeZFPNkhxWrjaFttagr != jjEiJGkdrKfqxJAsceTeoFkgoNMlA.AqybaYFDSFEDwBRnsokwpBTdIblQ.CompoundElement || !jjEiJGkdrKfqxJAsceTeoFkgoNMlA.BYUvlRLHXoZMeceCTjMMIYmbtBMmA(base.uxCljSdtaqwHXXSmSSwCKwRsbEEf, out var pEZtEoWUXFickyhTPzxGMRoQswOL))
		{
			return;
		}
		for (int i = 0; i < pEZtEoWUXFickyhTPzxGMRoQswOL.PewIUhZMyGUcqMDJtzetvXdUpuqS; i++)
		{
			int num = 8388608 << i;
			if ((wXuKXKglhBEpgRBwkNznjqCddGcA.autoGeneratedValueFlags & num) == 0 && !string.IsNullOrEmpty(wXuKXKglhBEpgRBwkNznjqCddGcA.key) && string.IsNullOrEmpty(wXuKXKglhBEpgRBwkNznjqCddGcA.GetSpecialElementKey(i)))
			{
				string text = wXuKXKglhBEpgRBwkNznjqCddGcA.key;
				if (pEZtEoWUXFickyhTPzxGMRoQswOL.IaedbspyldSLenBPDisowZTAxgvk(i).XdrIyCHSvCOtelgsOknkTmjdPjQPA.HasValue)
				{
					text = LocalizationManager.AppendToKeyAxisDirection(text, pEZtEoWUXFickyhTPzxGMRoQswOL.IaedbspyldSLenBPDisowZTAxgvk(i).XdrIyCHSvCOtelgsOknkTmjdPjQPA.Value);
				}
				wXuKXKglhBEpgRBwkNznjqCddGcA.SetSpecialElementKey(i, text);
				wXuKXKglhBEpgRBwkNznjqCddGcA.autoGeneratedValueFlags |= num;
				khJGmLkqmPYzNLVRuANYwNIWGmgd(num);
			}
		}
	}

	protected virtual void mfBgqqHBbXCXrLxHPquPzumgCWPb(jjEiJGkdrKfqxJAsceTeoFkgoNMlA.oTYnvuyaZmGssrtKlgjPUrEEwolk P_0)
	{
		base.XHzbXuCXybtTHzrgGGfkFjJcNcteA(P_0);
		WXuKXKglhBEpgRBwkNznjqCddGcA wXuKXKglhBEpgRBwkNznjqCddGcA = JcVXBtzIHVFcGFQjhXopNbdOqVgb();
		if (wXuKXKglhBEpgRBwkNznjqCddGcA == null || ((uint)wXuKXKglhBEpgRBwkNznjqCddGcA.autoGeneratedValueFlags & (uint)P_0) == 0 || base.EBtqAXtODeZFPNkhxWrjaFttagr != jjEiJGkdrKfqxJAsceTeoFkgoNMlA.AqybaYFDSFEDwBRnsokwpBTdIblQ.CompoundElement || !jjEiJGkdrKfqxJAsceTeoFkgoNMlA.BYUvlRLHXoZMeceCTjMMIYmbtBMmA(base.uxCljSdtaqwHXXSmSSwCKwRsbEEf, out var pEZtEoWUXFickyhTPzxGMRoQswOL))
		{
			return;
		}
		for (int i = 0; i < pEZtEoWUXFickyhTPzxGMRoQswOL.PewIUhZMyGUcqMDJtzetvXdUpuqS; i++)
		{
			int num = 8388608 << i;
			if ((wXuKXKglhBEpgRBwkNznjqCddGcA.autoGeneratedValueFlags & num) != 0)
			{
				wXuKXKglhBEpgRBwkNznjqCddGcA.SetSpecialElementKey(i, null);
				wXuKXKglhBEpgRBwkNznjqCddGcA.autoGeneratedValueFlags &= ~num;
				khJGmLkqmPYzNLVRuANYwNIWGmgd(num);
			}
		}
	}

	protected virtual jjEiJGkdrKfqxJAsceTeoFkgoNMlA.oTYnvuyaZmGssrtKlgjPUrEEwolk FrjAPBOFTPgSbulntqmismSxICJu(jjEiJGkdrKfqxJAsceTeoFkgoNMlA.QtSxnZYSjrgthBpvYZqvQdRfKXUE P_0)
	{
		jjEiJGkdrKfqxJAsceTeoFkgoNMlA.oTYnvuyaZmGssrtKlgjPUrEEwolk oTYnvuyaZmGssrtKlgjPUrEEwolk = base.iAYJjunKxgfxQgfzQTqMbfKBuIJqA(P_0);
		int num = eqIgsbSjportkHBSJpAEgrERuASX;
		if ((P_0 & jjEiJGkdrKfqxJAsceTeoFkgoNMlA.QtSxnZYSjrgthBpvYZqvQdRfKXUE.Keys) != jjEiJGkdrKfqxJAsceTeoFkgoNMlA.QtSxnZYSjrgthBpvYZqvQdRfKXUE.None)
		{
			for (int i = 0; i < num; i++)
			{
				oTYnvuyaZmGssrtKlgjPUrEEwolk = (jjEiJGkdrKfqxJAsceTeoFkgoNMlA.oTYnvuyaZmGssrtKlgjPUrEEwolk)((int)oTYnvuyaZmGssrtKlgjPUrEEwolk | (8388608 << i));
			}
		}
		return oTYnvuyaZmGssrtKlgjPUrEEwolk;
	}

	protected WXuKXKglhBEpgRBwkNznjqCddGcA JcVXBtzIHVFcGFQjhXopNbdOqVgb()
	{
		return SCQsEZHFBGaOGHdrLNaADiCIdlJUB() as WXuKXKglhBEpgRBwkNznjqCddGcA;
	}

	protected virtual void GGWQbybPsVbXvxgyHBLnwnhfFZVd()
	{
		base.DvBuhkbmxtOGnvpgTZDWNzIWvVT();
		int num = eqIgsbSjportkHBSJpAEgrERuASX;
		for (int i = 0; i < num; i++)
		{
			zucaHsRbQvAxizbSaHWafpJbdPgD(i);
		}
	}

	protected virtual void FCYdcZoeFENrDQEuDziCqeysElJJ()
	{
		bttZnJQoTaBSPdAchiSDHbcuJNXL();
	}
}
