<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Timberborn.AttractionsUI</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EnterableSystem">
      <HintPath>..\..\Assemblies\Timberborn.EnterableSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.CoreUI">
      <HintPath>..\..\Assemblies\Timberborn.CoreUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TooltipSystem">
      <HintPath>..\..\Assemblies\Timberborn.TooltipSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BatchControl">
      <HintPath>..\..\Assemblies\Timberborn.BatchControl.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BaseComponentSystem">
      <HintPath>..\..\Assemblies\Timberborn.BaseComponentSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Effects">
      <HintPath>..\..\Assemblies\Timberborn.Effects.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Localization">
      <HintPath>..\..\Assemblies\Timberborn.Localization.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EntityPanelSystem">
      <HintPath>..\..\Assemblies\Timberborn.EntityPanelSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SelectionSystem">
      <HintPath>..\..\Assemblies\Timberborn.SelectionSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.CharactersUI">
      <HintPath>..\..\Assemblies\Timberborn.CharactersUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SingletonSystem">
      <HintPath>..\..\Assemblies\Timberborn.SingletonSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BlockSystem">
      <HintPath>..\..\Assemblies\Timberborn.BlockSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TimeSystem">
      <HintPath>..\..\Assemblies\Timberborn.TimeSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Attractions">
      <HintPath>..\..\Assemblies\Timberborn.Attractions.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TemplateInstantiation">
      <HintPath>..\..\Assemblies\Timberborn.TemplateInstantiation.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections.Immutable">
      <HintPath>..\..\Assemblies\System.Collections.Immutable.dll</HintPath>
    </Reference>
    <Reference Include="Bindito.Core">
      <HintPath>..\..\Assemblies\Bindito.Core.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.NeedSpecs">
      <HintPath>..\..\Assemblies\Timberborn.NeedSpecs.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Common">
      <HintPath>..\..\Assemblies\Timberborn.Common.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>