public enum BuildingType
{
	None = 0,
	CropPatch = 1,
	BiofuelConverter = 2,
	WaterWell = 3,
	WaterBot = 4,
	Bench = 5,
	CarryBot = 6,
	HarvestBot = 7,
	Storage = 8,
	Beehives = 9,
	Flowers = 10,
	Decor = 11,
	WasteBot = 12,
	FertilizerBot = 13,
	FeederBot = 14,
	Feeder = 15,
	BerryBot = 16,
	ButterflyHouse = 17,
	WasteStorage = 18,
	ChickenNest = 19,
	PetHouse = 20,
	Belt = 21
}
