<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Kitchen.Layouts</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>8.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Unity.Mathematics">
      <HintPath>..\..\Assemblies\Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="XNode">
      <HintPath>..\..\Assemblies\XNode.dll</HintPath>
    </Reference>
    <Reference Include="MessagePack.Annotations">
      <HintPath>..\..\Assemblies\MessagePack.Annotations.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>..\..\Assemblies\Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="Kitchen.MessagePack">
      <HintPath>..\..\Assemblies\Kitchen.MessagePack.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Utilities">
      <HintPath>..\..\Assemblies\Sirenix.Utilities.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>