using System;
using System.Collections.Generic;
using PajamaLlama.Extensions;
using PajamaLlama.Flotsam.Procedural;
using PajamaLlama.Flotsam.World;
using PajamaLlama.Generic;
using UnityEngine;

[Serializable]
public class RegionPointOfInterestSettings
{
	[Serializable]
	private enum DistributionList
	{
		PointsOfInterest = 0,
		PointOfInterestCount = 1
	}

	[Serializable]
	private struct PointOfInterest
	{
		public int Count;

		public PointOfInterestProperties PointOfInterestProperties;
	}

	[SerializeField]
	private WorldRegionType _region;

	[SerializeField]
	private PollutionLevels _pollutionLevel;

	[Header("Flotsam Spawning")]
	[Tooltip("The amount of m2 per POI patch")]
	[SerializeField]
	private float _density;

	[Tooltip("The amount of variance allowed in the density as a percentage of the given density (e.g. 1 is 100%)")]
	[SerializeField]
	[MinMaxRangeFloat(0.5f, 2f)]
	private RangedFloat _densityVariance;

	[SerializeField]
	[MinMaxRangeFloat(0f, 1f)]
	private RangedFloat _landmarkRatio;

	[Tooltip("The chance a landmark with a given amount of flotsam pois spawns a flotsam poi. The index is the amount of pois")]
	[SerializeField]
	private AnimationCurve _landmarkPOIChances;

	[SerializeField]
	[MinMaxRangeFloat(75f, 500f)]
	private RangedFloat _landmarkSpawnRange;

	[Tooltip("The chance a cell with a given amount of landmarks and POIs spawns a flotsam poi. The index is the sum of landmarks and POIs in the cell")]
	[SerializeField]
	private AnimationCurve _restFlotsamChances;

	[Header("Cells")]
	[Tooltip("Should the cells generated by the RegionPasses be used?")]
	[SerializeField]
	private bool _useRegionPassesCells;

	[SerializeField]
	[ConditionalHide("_useRegionPassesCells", true, true)]
	private RegionPassCells.Settings _cellSettings;

	[Header("POI Distribution")]
	[SerializeField]
	private DistributionList _distributionList;

	[SerializeField]
	private PointOfInterestProperties[] _pointsOfInterest;

	[SerializeField]
	private PointOfInterest[] _pointOfInterestCount;

	private List<PointOfInterestProperties> _poisToDistribute;

	public WorldRegionType Region => _region;

	public PollutionLevels PullutionLevel => _pollutionLevel;

	public RangedFloat LandmarkRatio => _landmarkRatio;

	public RangedFloat LandmarkSpawnRange => _landmarkSpawnRange;

	public AnimationCurve LandmarkChancesCurve => _landmarkPOIChances;

	public AnimationCurve RestFlotsamChancesCurve => _restFlotsamChances;

	public bool UseRegionPassesCells => _useRegionPassesCells;

	public RegionPassCells.Settings CellSettings => _cellSettings;

	public void Initialize()
	{
		if (_poisToDistribute == null)
		{
			_poisToDistribute = new List<PointOfInterestProperties>();
		}
		else
		{
			_poisToDistribute.Clear();
		}
		PopulatePoisToDistribute();
	}

	public bool TryEvaluateLeafChance(int leafCount, out float leafChance)
	{
		if (_landmarkPOIChances.TryEvaluate(leafCount, out leafChance))
		{
			return 0f < leafChance;
		}
		return false;
	}

	public bool TryEvaluateCellSpawnChance(int nodeCount, out float cellSpawnChance)
	{
		if (_restFlotsamChances.TryEvaluate(nodeCount, out cellSpawnChance))
		{
			return 0f < cellSpawnChance;
		}
		return false;
	}

	private void PopulatePoisToDistribute()
	{
		switch (_distributionList)
		{
		case DistributionList.PointsOfInterest:
			_poisToDistribute.AddRange(_pointsOfInterest);
			break;
		case DistributionList.PointOfInterestCount:
		{
			PointOfInterest[] pointOfInterestCount = _pointOfInterestCount;
			for (int i = 0; i < pointOfInterestCount.Length; i++)
			{
				PointOfInterest pointOfInterest = pointOfInterestCount[i];
				for (int j = 0; j < pointOfInterest.Count; j++)
				{
					_poisToDistribute.Add(pointOfInterest.PointOfInterestProperties);
				}
			}
			break;
		}
		default:
			Debug.LogException(new NotImplementedException());
			break;
		}
	}

	public float ReturnRandomizedDensity()
	{
		return _density * _densityVariance.ReturnRandom();
	}

	public PointOfInterestProperties ReturnPointOfInterestProperties()
	{
		if (_poisToDistribute.Count == 0)
		{
			PopulatePoisToDistribute();
		}
		int index = UnityEngine.Random.Range(0, _poisToDistribute.Count);
		PointOfInterestProperties result = _poisToDistribute[index];
		_poisToDistribute.RemoveAt(index);
		return result;
	}
}
