public enum XboxOneUserActionResultId
{
	SIGN_IN_SUCCES = 0,
	SIGN_IN_CANCEL = 1,
	SIGN_IN_ERROR = 2,
	SIGN_OUT_REVERT = 3,
	SIGN_OUT_CHANGE = 4,
	SIGN_OUT_CONFIRM = 5,
	CHANGE_REVERT = 6,
	CHANGE_CHANGE = 7,
	CHANGE_CONFIRM = 8,
	CONFIRM_CONFIRM = 9,
	CONFIRM_CHANGE = 10
}
