namespace Assets.Scripts.Bindings.Manifold
{
	public enum Error
	{
		NO_ERROR = 0,
		NON_FINITE_VERTEX = 1,
		NOT_MANIFOLD = 2,
		VERTEX_INDEX_OUT_OF_BOUNDS = 3,
		PROPERTIES_WRONG_LENGTH = 4,
		MISSING_POSITION_PROPERTIES = 5,
		MERGE_VECTORS_DIFFERENT_LENGTHS = 6,
		MERGE_INDEX_OUT_OF_BOUNDS = 7,
		TRANSFORM_WRONG_LENGTH = 8,
		RUN_INDEX_WRONG_LENGTH = 9,
		FACE_ID_WRONG_LENGTH = 10,
		INVALID_CONSTRUCTION = 11,
		RESULT_TOO_LARGE = 12
	}
}
