<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TwitchLib.Api</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>8.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="TwitchLib.Api.Core.Interfaces">
      <HintPath>..\..\Assemblies\TwitchLib.Api.Core.Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="TwitchLib.Api.V5">
      <HintPath>..\..\Assemblies\TwitchLib.Api.V5.dll</HintPath>
    </Reference>
    <Reference Include="TwitchLib.Api.Helix">
      <HintPath>..\..\Assemblies\TwitchLib.Api.Helix.dll</HintPath>
    </Reference>
    <Reference Include="TwitchLib.Api.Core">
      <HintPath>..\..\Assemblies\TwitchLib.Api.Core.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>..\..\Assemblies\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="TwitchLib.Api.Core.Enums">
      <HintPath>..\..\Assemblies\TwitchLib.Api.Core.Enums.dll</HintPath>
    </Reference>
    <Reference Include="TwitchLib.Api.Helix.Models">
      <HintPath>..\..\Assemblies\TwitchLib.Api.Helix.Models.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\Assemblies\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>