<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Coherence.RSL.Brisk</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Coherence.Transport">
      <HintPath>..\..\Assemblies\Coherence.Transport.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Common">
      <HintPath>..\..\Assemblies\Coherence.Common.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.RSL.Transport">
      <HintPath>..\..\Assemblies\Coherence.RSL.Transport.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Log">
      <HintPath>..\..\Assemblies\Coherence.Log.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Brisk">
      <HintPath>..\..\Assemblies\Coherence.Brisk.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Brook">
      <HintPath>..\..\Assemblies\Coherence.Brook.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.SimulationFrame">
      <HintPath>..\..\Assemblies\Coherence.SimulationFrame.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.RSL.Tickers">
      <HintPath>..\..\Assemblies\Coherence.RSL.Tickers.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Tend">
      <HintPath>..\..\Assemblies\Coherence.Tend.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>