namespace VampireSurvivors.Data;

public enum PropType
{
	CANDLE = 0,
	CANDELABRA = 1,
	BRAZIER = 2,
	BRAZIER2 = 3,
	LAMPOST = 4,
	CART = 5,
	WINDOW = 6,
	LANTERN = 7,
	FOSCARI_SEAL_1 = 8,
	FOSCARI_SEAL_2 = 9,
	FOSCARI_SEAL_3 = 10,
	LANTERN_INVERSE = 11,
	WEATHERNODE = 12,
	TRAINLEVER = 13,
	LABORATORYLEVER2 = 14,
	LABORATORYLEVER3 = 15,
	LABORATORYLEVER4 = 16,
	LAB_DOOR_A = 17,
	LAB_DOOR_B = 18,
	LAMPOST_SINGLE = 19,
	EX_TOHILSTATUE = 20,
	FB_CAPSULE = 101,
	FB_EXPLOCAR = 102,
	FB_EXPLOBARREL = 103,
	TP_DOOR = 104
}
