namespace VampireSurvivors.Data;

public enum StageSetType
{
	STAGE_DATA_ADV_M001,
	STAGE_DATA_ADV_0001,
	STAGESET_POE,
	STAGESET_IMELDA,
	STAGESET_CHALCEDONY,
	STAGESET_FIRSTBLOOD,
	STAGESET_SHEMOON,
	STAGESET_FOSCARI,
	STAGESET_OTC_001
}
