using System;
using System.Collections.Generic;
using Dorfromantik;

[Serializable]
public class QuestTileData_001 : QuestTileData
{
	public string questTileId;

	public bool questActive;

	public int questQueueIndex;

	public int targetValue = -1;

	public int questLevel;

	public string questId;

	public string unlockedSessionQuestId;

	public static Dictionary<string, QuestId> questIdByStringId = new Dictionary<string, QuestId>
	{
		{
			"lockQuest",
			QuestId.ClosingQuest
		},
		{
			"village_moreThan",
			QuestId.village_moreThan
		},
		{
			"village_exactly",
			QuestId.village_exactly
		},
		{
			"forest_moreThan",
			QuestId.forest_moreThan
		},
		{
			"field_moreThan",
			QuestId.Agriculture_moreThan
		},
		{
			"field_exactly",
			QuestId.Agriculture_exactly
		},
		{
			"train_moreThan",
			QuestId.train_moreThan
		},
		{
			"train_exactly",
			QuestId.train_exactly
		},
		{
			"water_moreThan",
			QuestId.water_moreThan
		},
		{
			"water_exactly",
			QuestId.water_exactly
		}
	};

	public static Dictionary<QuestId, string> questStringIdById = new Dictionary<QuestId, string>
	{
		{
			QuestId.ClosingQuest,
			"lockQuest"
		},
		{
			QuestId.village_moreThan,
			"village_moreThan"
		},
		{
			QuestId.village_exactly,
			"village_exactly"
		},
		{
			QuestId.forest_moreThan,
			"forest_moreThan"
		},
		{
			QuestId.Agriculture_moreThan,
			"field_moreThan"
		},
		{
			QuestId.Agriculture_exactly,
			"field_exactly"
		},
		{
			QuestId.train_moreThan,
			"train_moreThan"
		},
		{
			QuestId.train_exactly,
			"train_exactly"
		},
		{
			QuestId.water_moreThan,
			"water_moreThan"
		},
		{
			QuestId.water_exactly,
			"water_exactly"
		}
	};

	public static Dictionary<string, QuestTileId> questTileIdByName = new Dictionary<string, QuestTileId>
	{
		{
			"fields_base_2A_2AV_1AV",
			QuestTileId.Agriculture_2AA_2AV_1AV
		},
		{
			"fields_base_2A",
			QuestTileId.Agriculture_2AA_4AF
		},
		{
			"fields_bigtree_2A-4AF",
			QuestTileId.Agriculture_2AA_4AF_BigTree
		},
		{
			"fields_granary_2A-4AF",
			QuestTileId.Agriculture_2AA_4AF_Granary
		},
		{
			"fields_windmill_2A-4AF",
			QuestTileId.Agriculture_2AA_4AF_Windmill
		},
		{
			"fields_base_3A_1AV",
			QuestTileId.Agriculture_3AA_1AV
		},
		{
			"fields_granary_3A_1AV",
			QuestTileId.Agriculture_3AA_1AV_Granary
		},
		{
			"fields_windmill_3A_1AV",
			QuestTileId.Agriculture_3AA_1AV_Windmill
		},
		{
			"fields_base_4A-2AF",
			QuestTileId.Agriculture_4AA_2AF
		},
		{
			"fields_granary_4A-2AF",
			QuestTileId.Agriculture_4AA_2AF_Granary
		},
		{
			"fields_base_4B-1AF-1AF",
			QuestTileId.Agriculture_4BA_1AF_1AF
		},
		{
			"fields_bigtree_4B-1AF-1AF",
			QuestTileId.Agriculture_4BA_1AF_1AF_BigTree
		},
		{
			"fields_base_6A",
			QuestTileId.Agriculture_6AA
		},
		{
			"fields_bigtree_6A",
			QuestTileId.Agriculture_6AA_BigTree
		},
		{
			"fields_windmill_6A",
			QuestTileId.Agriculture_6AA_Windmill
		},
		{
			"forest_base_1A",
			QuestTileId.Forest_1AF
		},
		{
			"forest_deer_1A",
			QuestTileId.Forest_1AF_Deer
		},
		{
			"forest_base_1A_2AW",
			QuestTileId.Forest_1AF_2AW
		},
		{
			"forest_deer_1A_2AW",
			QuestTileId.Forest_1AF_2AW_Deer
		},
		{
			"forest_base_3A",
			QuestTileId.Forest_3AF
		},
		{
			"forest_deer_3A",
			QuestTileId.Forest_3AF_Deer
		},
		{
			"forest_base_4A",
			QuestTileId.Forest_4AF
		},
		{
			"forest_base_6A",
			QuestTileId.Forest_6AF
		},
		{
			"forest_deer_6A",
			QuestTileId.Forest_6AF_Deer
		},
		{
			"train_base_2B-3A-1A",
			QuestTileId.Train_2BT_3AA_1AA
		},
		{
			"train_base_2B_3AF_1AF",
			QuestTileId.Train_2BT_3AF_1AF
		},
		{
			"train_base_2B-3AV-1AV",
			QuestTileId.Train_2BT_3AV_1AV
		},
		{
			"train_base_2C",
			QuestTileId.Train_2CT
		},
		{
			"train_locomotive_2C",
			QuestTileId.Train_2CT_Locomotive
		},
		{
			"train_base_2C-1AF-1AV",
			QuestTileId.Train_2CT_1AF_1AV
		},
		{
			"train_locomotive_2C-1AF-1AV",
			QuestTileId.Train_2CT_1AF_1AV_Locomotive
		},
		{
			"train_base_4C_1AF_1AF",
			QuestTileId.Train_4CT_1AF_1AF
		},
		{
			"village_base_2A",
			QuestTileId.Village_2AV
		},
		{
			"village_base_3A",
			QuestTileId.Village_3AV
		},
		{
			"village_fountain_3A",
			QuestTileId.Village_3AV_Fountain
		},
		{
			"village_base_3A-3AF",
			QuestTileId.Village_3AV_3AF
		},
		{
			"village_fountain_3A-3AF",
			QuestTileId.Village_3AV_3AF_Fountain
		},
		{
			"village_tower_3A-3AF",
			QuestTileId.Village_3AV_3AF_Tower
		},
		{
			"village_base_4B-1AF-1AF",
			QuestTileId.Village_4BV_1AF_1AF
		},
		{
			"village_fountain_4B-1AF-1AF",
			QuestTileId.Village_4BV_1AF_1AF_Fountain
		},
		{
			"village_tower_4B-1AF-1AF",
			QuestTileId.Village_4BV_1AF_1AF_Tower
		},
		{
			"village_base_6A",
			QuestTileId.Village_6AV
		},
		{
			"village_fountain_6A",
			QuestTileId.Village_6AV_Fountain
		},
		{
			"village_tower_6A",
			QuestTileId.Village_6AV_Tower
		},
		{
			"water_base_2B-1AF-3AF",
			QuestTileId.Water_2BW_3AF_1AF
		},
		{
			"water_boat_2B-1AF-3AF",
			QuestTileId.Water_2BW_3AF_1AF_Boat
		},
		{
			"water_base_2C-1A-2AF",
			QuestTileId.Water_2CW_2AF_1AA
		},
		{
			"water_watermill_2C-1A-2AF",
			QuestTileId.Water_2CW_2AF_1AA_Watermill
		},
		{
			"water_base_2C-1AV-2A",
			QuestTileId.Water_2CW_2AA_1AV
		},
		{
			"water_watermill_2C-1AV-2A",
			QuestTileId.Water_2CW_2AA_1AV_Watermill
		},
		{
			"water_base_2C-1AV-2AV",
			QuestTileId.Water_2CW_2AV_1AV
		},
		{
			"water_2C",
			QuestTileId.Water_2CW
		},
		{
			"water_watermill_2C-1AV-2AV",
			QuestTileId.Water_2CW_2AV_2AV_Watermill
		},
		{
			"water_boat_2C",
			QuestTileId.Water_2CW_Boat
		},
		{
			"water_base_6A",
			QuestTileId.Water_6AW
		},
		{
			"water_boat_6A",
			QuestTileId.Water_6AW_Boat
		},
		{
			"water_trainstation_6A",
			QuestTileId.WaterTrainStation_6AW_6AT
		}
	};

	public static Dictionary<QuestTileId, string> questTileNameById = new Dictionary<QuestTileId, string>
	{
		{
			QuestTileId.Agriculture_2AA_2AV_1AV,
			"fields_base_2A_2AV_1AV"
		},
		{
			QuestTileId.Agriculture_2AA_4AF,
			"fields_base_2A"
		},
		{
			QuestTileId.Agriculture_2AA_4AF_BigTree,
			"fields_bigtree_2A-4AF"
		},
		{
			QuestTileId.Agriculture_2AA_4AF_Granary,
			"fields_granary_2A-4AF"
		},
		{
			QuestTileId.Agriculture_2AA_4AF_Windmill,
			"fields_windmill_2A-4AF"
		},
		{
			QuestTileId.Agriculture_3AA_1AV,
			"fields_base_3A_1AV"
		},
		{
			QuestTileId.Agriculture_3AA_1AV_Granary,
			"fields_granary_3A_1AV"
		},
		{
			QuestTileId.Agriculture_3AA_1AV_Windmill,
			"fields_windmill_3A_1AV"
		},
		{
			QuestTileId.Agriculture_4AA_2AF,
			"fields_base_4A-2AF"
		},
		{
			QuestTileId.Agriculture_4AA_2AF_Granary,
			"fields_granary_4A-2AF"
		},
		{
			QuestTileId.Agriculture_4BA_1AF_1AF,
			"fields_base_4B-1AF-1AF"
		},
		{
			QuestTileId.Agriculture_4BA_1AF_1AF_BigTree,
			"fields_bigtree_4B-1AF-1AF"
		},
		{
			QuestTileId.Agriculture_6AA,
			"fields_base_6A"
		},
		{
			QuestTileId.Agriculture_6AA_BigTree,
			"fields_bigtree_6A"
		},
		{
			QuestTileId.Agriculture_6AA_Windmill,
			"fields_windmill_6A"
		},
		{
			QuestTileId.Forest_1AF,
			"forest_base_1A"
		},
		{
			QuestTileId.Forest_1AF_Deer,
			"forest_deer_1A"
		},
		{
			QuestTileId.Forest_1AF_2AW,
			"forest_base_1A_2AW"
		},
		{
			QuestTileId.Forest_1AF_2AW_Deer,
			"forest_deer_1A_2AW"
		},
		{
			QuestTileId.Forest_3AF,
			"forest_base_3A"
		},
		{
			QuestTileId.Forest_3AF_Deer,
			"forest_deer_3A"
		},
		{
			QuestTileId.Forest_4AF,
			"forest_base_4A"
		},
		{
			QuestTileId.Forest_6AF,
			"forest_base_6A"
		},
		{
			QuestTileId.Forest_6AF_Deer,
			"forest_deer_6A"
		},
		{
			QuestTileId.Train_2BT_3AA_1AA,
			"train_base_2B-3A-1A"
		},
		{
			QuestTileId.Train_2BT_3AF_1AF,
			"train_base_2B_3AF_1AF"
		},
		{
			QuestTileId.Train_2BT_3AV_1AV,
			"train_base_2B-3AV-1AV"
		},
		{
			QuestTileId.Train_2CT,
			"train_base_2C"
		},
		{
			QuestTileId.Train_2CT_Locomotive,
			"train_locomotive_2C"
		},
		{
			QuestTileId.Train_2CT_1AF_1AV,
			"train_base_2C-1AF-1AV"
		},
		{
			QuestTileId.Train_2CT_1AF_1AV_Locomotive,
			"train_locomotive_2C-1AF-1AV"
		},
		{
			QuestTileId.Train_4CT_1AF_1AF,
			"train_base_4C_1AF_1AF"
		},
		{
			QuestTileId.Village_2AV,
			"village_base_2A"
		},
		{
			QuestTileId.Village_3AV,
			"village_base_3A"
		},
		{
			QuestTileId.Village_3AV_Fountain,
			"village_fountain_3A"
		},
		{
			QuestTileId.Village_3AV_3AF,
			"village_base_3A-3AF"
		},
		{
			QuestTileId.Village_3AV_3AF_Fountain,
			"village_fountain_3A-3AF"
		},
		{
			QuestTileId.Village_3AV_3AF_Tower,
			"village_tower_3A-3AF"
		},
		{
			QuestTileId.Village_4BV_1AF_1AF,
			"village_base_4B-1AF-1AF"
		},
		{
			QuestTileId.Village_4BV_1AF_1AF_Fountain,
			"village_fountain_4B-1AF-1AF"
		},
		{
			QuestTileId.Village_4BV_1AF_1AF_Tower,
			"village_tower_4B-1AF-1AF"
		},
		{
			QuestTileId.Village_6AV,
			"village_base_6A"
		},
		{
			QuestTileId.Village_6AV_Fountain,
			"village_fountain_6A"
		},
		{
			QuestTileId.Village_6AV_Tower,
			"village_tower_6A"
		},
		{
			QuestTileId.Water_2BW_3AF_1AF,
			"water_base_2B-1AF-3AF"
		},
		{
			QuestTileId.Water_2BW_3AF_1AF_Boat,
			"water_boat_2B-1AF-3AF"
		},
		{
			QuestTileId.Water_2CW_2AF_1AA,
			"water_base_2C-1A-2AF"
		},
		{
			QuestTileId.Water_2CW_2AF_1AA_Watermill,
			"water_watermill_2C-1A-2AF"
		},
		{
			QuestTileId.Water_2CW_2AA_1AV,
			"water_base_2C-1AV-2A"
		},
		{
			QuestTileId.Water_2CW_2AA_1AV_Watermill,
			"water_watermill_2C-1AV-2A"
		},
		{
			QuestTileId.Water_2CW_2AV_1AV,
			"water_base_2C-1AV-2AV"
		},
		{
			QuestTileId.Water_2CW,
			"water_2C"
		},
		{
			QuestTileId.Water_2CW_2AV_2AV_Watermill,
			"water_watermill_2C-1AV-2AV"
		},
		{
			QuestTileId.Water_2CW_Boat,
			"water_boat_2C"
		},
		{
			QuestTileId.Water_6AW,
			"water_base_6A"
		},
		{
			QuestTileId.Water_6AW_Boat,
			"water_boat_6A"
		},
		{
			QuestTileId.WaterTrainStation_6AW_6AT,
			"water_trainstation_6A"
		}
	};

	public QuestTileData_001()
	{
		version = 1;
	}

	public QuestTileData_001(QuestTile questTile)
	{
		version = 1;
		questTileId = questTile.questTileId;
		if (questTile.QuestWatcher.Watching)
		{
			questActive = true;
			targetValue = questTile.QuestWatcher.GetConditionWatcher(0).TargetValue;
			questQueueIndex = questTile.QuestWatcher.CurrentQuestIndex;
			questId = questTile.QuestWatcher.CurrentQuest.stringId;
			unlockedSessionQuestId = (questTile.QuestWatcher.UnlockingSessionQuest ? questTile.QuestWatcher.UnlockingSessionQuest.stringId : "");
		}
		questLevel = questTile.level;
	}
}
