<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>RandomWalkState.Authoring</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="RandomWalkState.Components">
      <HintPath>..\..\Assemblies\RandomWalkState.Components.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="NaughtyAttributes.Core">
      <HintPath>..\..\Assemblies\NaughtyAttributes.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>