<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Unity.Postprocessing.Runtime">
      <HintPath>..\..\Assemblies\Unity.Postprocessing.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\Assemblies\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>..\..\Assemblies\Unity.Collections.dll</HintPath>
    </Reference>
    <Reference Include="FoxyVoxel.OcclusionCulling">
      <HintPath>..\..\Assemblies\FoxyVoxel.OcclusionCulling.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\..\Assemblies\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\Assemblies\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>..\..\Assemblies\UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainPhysicsModule">
      <HintPath>..\..\Assemblies\UnityEngine.TerrainPhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>..\..\Assemblies\UnityEngine.TerrainModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\..\Assemblies\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\..\Assemblies\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\..\Assemblies\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>..\..\Assemblies\UnityEngine.AIModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\Assemblies\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>..\..\Assemblies\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\..\Assemblies\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="FoxyVoxel.Logging.Core">
      <HintPath>..\..\Assemblies\FoxyVoxel.Logging.Core.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>..\..\Assemblies\Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\Assemblies\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml" />
    <Reference Include="UnityEngine.UnityAnalyticsModule">
      <HintPath>..\..\Assemblies\UnityEngine.UnityAnalyticsModule.dll</HintPath>
    </Reference>
    <Reference Include="TwitchIntegration">
      <HintPath>..\..\Assemblies\TwitchIntegration.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ResourceManager">
      <HintPath>..\..\Assemblies\Unity.ResourceManager.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Addressables">
      <HintPath>..\..\Assemblies\Unity.Addressables.dll</HintPath>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>..\..\Assemblies\com.rlabrecque.steamworks.net.dll</HintPath>
    </Reference>
    <Reference Include="MeshFusionPro.Runtime">
      <HintPath>..\..\Assemblies\MeshFusionPro.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="FMODUnity">
      <HintPath>..\..\Assemblies\FMODUnity.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>..\..\Assemblies\UnityEngine.VideoModule.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging">
      <HintPath>..\..\Assemblies\Microsoft.Extensions.Logging.dll</HintPath>
    </Reference>
    <Reference Include="NodeCanvas">
      <HintPath>..\..\Assemblies\NodeCanvas.dll</HintPath>
    </Reference>
    <Reference Include="ParadoxNotion">
      <HintPath>..\..\Assemblies\ParadoxNotion.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.WindModule">
      <HintPath>..\..\Assemblies\UnityEngine.WindModule.dll</HintPath>
    </Reference>
    <Reference Include="Aura2_Core">
      <HintPath>..\..\Assemblies\Aura2_Core.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>..\..\Assemblies\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Ionic.Zip.Unity">
      <HintPath>..\..\Assemblies\Ionic.Zip.Unity.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst">
      <HintPath>..\..\Assemblies\Unity.Burst.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\Assemblies\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="Google.Apis.Auth">
      <HintPath>..\..\Assemblies\Google.Apis.Auth.dll</HintPath>
    </Reference>
    <Reference Include="Google.Apis.Sheets.v4">
      <HintPath>..\..\Assemblies\Google.Apis.Sheets.v4.dll</HintPath>
    </Reference>
    <Reference Include="Google.Apis">
      <HintPath>..\..\Assemblies\Google.Apis.dll</HintPath>
    </Reference>
    <Reference Include="Google.Apis.Core">
      <HintPath>..\..\Assemblies\Google.Apis.Core.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VRModule">
      <HintPath>..\..\Assemblies\UnityEngine.VRModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TilemapModule">
      <HintPath>..\..\Assemblies\UnityEngine.TilemapModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>..\..\Assemblies\UnityEngine.JSONSerializeModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule">
      <HintPath>..\..\Assemblies\UnityEngine.ScreenCaptureModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CrashReportingModule">
      <HintPath>..\..\Assemblies\UnityEngine.CrashReportingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>..\..\Assemblies\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ProBuilder">
      <HintPath>..\..\Assemblies\Unity.ProBuilder.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>