internal sealed class THAzHfMdYlXjSeVopEUdnzWlOnlm
{
	public static readonly LUISlIAquBcnQKnVgEALfdAorcbM YwBagHGBNkFdNCPyyMonjJgDWOTX = ZUmrdcHMBLmhFpaHPQWxuwoVDIoL.tEyeEVAYAEhwwMjPDUqKeHGHYUos(JTsSZLVcsmEugnkHjyXNxgEfZHDK.DeviceNotConnected);
}
