<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Timberborn.MechanicalSystemUI</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Localization">
      <HintPath>..\..\Assemblies\Timberborn.Localization.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.CoreUI">
      <HintPath>..\..\Assemblies\Timberborn.CoreUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.MechanicalSystem">
      <HintPath>..\..\Assemblies\Timberborn.MechanicalSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BatchControl">
      <HintPath>..\..\Assemblies\Timberborn.BatchControl.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BaseComponentSystem">
      <HintPath>..\..\Assemblies\Timberborn.BaseComponentSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Debugging">
      <HintPath>..\..\Assemblies\Timberborn.Debugging.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SingletonSystem">
      <HintPath>..\..\Assemblies\Timberborn.SingletonSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TimeSystem">
      <HintPath>..\..\Assemblies\Timberborn.TimeSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Common">
      <HintPath>..\..\Assemblies\Timberborn.Common.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BlueprintSystem">
      <HintPath>..\..\Assemblies\Timberborn.BlueprintSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.UIFormatters">
      <HintPath>..\..\Assemblies\Timberborn.UIFormatters.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EntityPanelSystem">
      <HintPath>..\..\Assemblies\Timberborn.EntityPanelSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Rendering">
      <HintPath>..\..\Assemblies\Timberborn.Rendering.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BlockSystem">
      <HintPath>..\..\Assemblies\Timberborn.BlockSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.DebuggingUI">
      <HintPath>..\..\Assemblies\Timberborn.DebuggingUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SelectionSystem">
      <HintPath>..\..\Assemblies\Timberborn.SelectionSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TemplateInstantiation">
      <HintPath>..\..\Assemblies\Timberborn.TemplateInstantiation.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TimbermeshAnimations">
      <HintPath>..\..\Assemblies\Timberborn.TimbermeshAnimations.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Illumination">
      <HintPath>..\..\Assemblies\Timberborn.Illumination.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BlockObjectModelSystem">
      <HintPath>..\..\Assemblies\Timberborn.BlockObjectModelSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.StatusSystem">
      <HintPath>..\..\Assemblies\Timberborn.StatusSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TickSystem">
      <HintPath>..\..\Assemblies\Timberborn.TickSystem.dll</HintPath>
    </Reference>
    <Reference Include="Bindito.Core">
      <HintPath>..\..\Assemblies\Bindito.Core.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Coordinates">
      <HintPath>..\..\Assemblies\Timberborn.Coordinates.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections.Immutable">
      <HintPath>..\..\Assemblies\System.Collections.Immutable.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>