namespace BestHTTP.Connections.HTTP2
{
	public enum HTTP2Settings : ushort
	{
		HEADER_TABLE_SIZE = 1,
		ENABLE_PUSH = 2,
		MAX_CONCURRENT_STREAMS = 3,
		INITIAL_WINDOW_SIZE = 4,
		MAX_FRAME_SIZE = 5,
		MAX_HEADER_LIST_SIZE = 6,
		RESERVED = 7,
		ENABLE_CONNECT_PROTOCOL = 8
	}
}
