public enum eControlScheme
{
	DEFAULT = 0,
	COINPAGE = 1,
	MAP_SCENE = 2,
	MAIN_GAME = 3,
	TOWER_BUILD_MODE = 4,
	TETRIS_BUILD_MODE = 5,
	BUFF_MODE = 6,
	TOWER_CONTROL = 7,
	SCRAP_MASTER_MACHINE = 8,
	BUILD_TOWER_RING = 9,
	SELECT_BLOCK_CARD = 10,
	PAUSED = 11,
	BASIC_UI = 12,
	UI_JOURNAL = 13,
	UI_VICTORY = 14,
	UI_VICTORY_VIEW_MAP = 15,
	VIEW_RELIC_DETAIL = 16
}
