public enum eEndlessModeType
{
	NONE = 0,
	BASIC_ENDLESS = 1,
	HALLOWEEN_EVENT = 2,
	DAILY_CHALLENGE = 3,
	WEEKLY_CHALLENGE = 4,
	ENIGMA_SANCTUM_DAILY = 5,
	ENIGMA_SANCTUM_WEEKLY = 6,
	ENIGMA_SANCTUM_CASUAL = 7,
	RANDOM_ENDLESS_CHALLENGE = 8,
	XMAS_EVENT = 9
}
