using System;

[Flags]
public enum eExtraTooltipType
{
	NONE = 0,
	POISON_ELEMENT = 1,
	ARCANE_ELEMENT = 2,
	FIRE_ELEMENT = 4,
	ICE_ELEMENT = 8,
	ELECTRIC_ELEMENT = 0x10,
	BURN = 0x20,
	CHILL = 0x40,
	SCRAP_TOWER = 0x80,
	FRAGILE = 0x100,
	VULNERABLE = 0x200
}
