public enum eHardModeShardType
{
	NONE = 0,
	SHARD_HP = 1,
	SHARD_CANNON = 2,
	SHARD_MONSTER = 3,
	SHARD_PLAYER = 4,
	SHARD_BOSS = 5,
	SHARD_GOLD = 6,
	SHARD_CORRUPT = 7,
	SHARD_ENVIRONMENT = 8,
	SHARD_VOID = 9
}
