public enum ePlayerStats
{
	TOTAL_WIN = 0,
	TOTAL_LOSE = 1,
	HIGHEST_WIN_STREAK = 2,
	LEVEL_CLEARED = 3,
	NORMAL_MONSTER_KILLED = 4,
	ELITE_MONSTER_KILLED = 5,
	BOSS_KILLED = 6,
	TOTAL_GOLD = 7,
	TOTAL_EMBER_STONE = 8,
	TOTAL_EXP = 9,
	TOTAL_DAMAGE_TAKEN = 10,
	TOTAL_DAMAGE_DEALT = 11,
	NORMAL_DAMAGE = 12,
	FIRE_DAMAGE = 13,
	FROST_DAMAGE = 14,
	ELECTRIC_DAMAGE = 15,
	POISON_DAMAGE = 16,
	ARCANE_DAMAGE = 17,
	END = 18
}
