using System;

[Serializable]
public enum ePowerGridType
{
	NONE = 0,
	INCREASE_ATK = 1,
	INCREASE_SPEED = 2,
	INCREASE_RANGE = 3,
	FIRE_ELEMENT_BUFF = 4,
	FROST_ELEMENT_BUFF = 5,
	ELECTRIC_ELEMENT_BUFF = 6,
	POISON_ELEMENT_BUFF = 7,
	ARCANE_ELEMENT_BUFF = 8,
	INCREASE_COIN = 9,
	INCREASE_ATK_LESSER = 10,
	INCREASE_SPEED_LESSER = 11,
	INCREASE_RANGE_LESSER = 12,
	EXPLOSION = 13,
	PROTECTION = 14,
	CORRUPTED = 101,
	CORRUPTED_FREEZE = 102,
	CORRUPTED_LAVA = 103
}
