public enum eScrapMasterSkillType
{
	NONE = 0,
	WEAPON_CANNON = 1,
	WEAPON_MISSILE = 2,
	WEAPON_MACHINE_GUN = 3,
	PLATFORM_1x1 = 4,
	PLATFORM_2x2 = 5,
	PLATFORM_3x3 = 6,
	TOWER_ENHANCE_DAMAGE = 7,
	TOWER_ENHANCE_ATTACK_RANGE = 8
}
