<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Coherence.Toolkit</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Numerics" />
    <Reference Include="Coherence.Common">
      <HintPath>..\..\Assemblies\Coherence.Common.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Log">
      <HintPath>..\..\Assemblies\Coherence.Log.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Stats">
      <HintPath>..\..\Assemblies\Coherence.Stats.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Runtime">
      <HintPath>..\..\Assemblies\Coherence.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Core">
      <HintPath>..\..\Assemblies\Coherence.Core.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Entities">
      <HintPath>..\..\Assemblies\Coherence.Entities.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.ProtocolDef">
      <HintPath>..\..\Assemblies\Coherence.ProtocolDef.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Transport">
      <HintPath>..\..\Assemblies\Coherence.Transport.dll</HintPath>
    </Reference>
    <Reference Include="Coherence">
      <HintPath>..\..\Assemblies\Coherence.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.SimulationFrame">
      <HintPath>..\..\Assemblies\Coherence.SimulationFrame.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>..\..\Assemblies\System.Core.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.ReplicationServer">
      <HintPath>..\..\Assemblies\Coherence.ReplicationServer.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Plugins">
      <HintPath>..\..\Assemblies\Coherence.Plugins.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\..\Assemblies\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Interpolation">
      <HintPath>..\..\Assemblies\Coherence.Interpolation.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ResourceManager">
      <HintPath>..\..\Assemblies\Unity.ResourceManager.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\Assemblies\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>..\..\Assemblies\UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Addressables">
      <HintPath>..\..\Assemblies\Unity.Addressables.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Brook">
      <HintPath>..\..\Assemblies\Coherence.Brook.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Core.Native">
      <HintPath>..\..\Assemblies\Coherence.Core.Native.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Profiling.Core">
      <HintPath>..\..\Assemblies\Unity.Profiling.Core.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\Assemblies\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>