using System;
using UnityEngine;

namespace Rewired
{
	[Serializable]
	public sealed class InputAction : ukqsQQLaXKdUclUNTHuyNrLvJoRf, ygnuJPyjhZTGYdIDYqMweKSjbBks
	{
		private const string keyCategory = "action";

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private int _id;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _name;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private InputActionType _type;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _descriptiveName;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		private string _positiveDescriptiveName;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		private string _negativeDescriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _key;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		private string _positiveKey;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		private string _negativeKey;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		private int _behaviorId;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		private bool _userAssignable;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private int _categoryId;

		[NonSerialized]
		private eGYBMsiivmbEJYDIzVkfnAgaCCHBA EfOfDwyPNVSNrJCFfAZWBxxqkpUo;

		[NonSerialized]
		private int DMdztsoguPwethluNnufkgZhZFwc;

		public int id
		{
			get
			{
				return 0;
			}
			internal set
			{
			}
		}

		public string name
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public InputActionType type
		{
			get
			{
				return default(InputActionType);
			}
			internal set
			{
			}
		}

		public string descriptiveName
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public string positiveDescriptiveName
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public string negativeDescriptiveName
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public int behaviorId
		{
			get
			{
				return 0;
			}
			internal set
			{
			}
		}

		public int categoryId
		{
			get
			{
				return 0;
			}
			internal set
			{
			}
		}

		public bool userAssignable
		{
			get
			{
				return false;
			}
			internal set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string positiveKey
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string negativeKey
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedPositiveDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedNegativeDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string ygnuJPyjhZTGYdIDYqMweKSjbBks.keyCategory => null;

		string ygnuJPyjhZTGYdIDYqMweKSjbBks.scriptingName => null;

		string ygnuJPyjhZTGYdIDYqMweKSjbBks.nonLocalizedDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string ukqsQQLaXKdUclUNTHuyNrLvJoRf.nonLocalizedPositiveDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string ukqsQQLaXKdUclUNTHuyNrLvJoRf.nonLocalizedNegativeDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string ygnuJPyjhZTGYdIDYqMweKSjbBks.key => null;

		string ukqsQQLaXKdUclUNTHuyNrLvJoRf.positiveKey
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string ukqsQQLaXKdUclUNTHuyNrLvJoRf.negativeKey
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		int ygnuJPyjhZTGYdIDYqMweKSjbBks.autoGeneratedValueFlags
		{
			get
			{
				return 0;
			}
			set
			{
			}
		}

		public InputAction()
		{
		}

		public InputAction(InputAction P_0)
		{
		}

		public InputAction Clone()
		{
			return null;
		}

		public string GetDisplayName(AxisRange axisRange)
		{
			return null;
		}

		internal void NxpvLzHWRbrhPoltQQqrmjOlpOGR()
		{
		}

		internal void ejDPvYtiCXChGlQTJYoBmtfkkgJq()
		{
		}

		private static IIMSRAFgrMZddteJJypOkilIlNdG.tbmleEseZBqpaiaKBMVIUgEXqHQu jrtDqYyxtUqIZlxymVQzFSyGIwHi(InputActionType P_0)
		{
			return default(IIMSRAFgrMZddteJJypOkilIlNdG.tbmleEseZBqpaiaKBMVIUgEXqHQu);
		}
	}
}
