using System;
using UnityEngine;

namespace Rewired
{
	[Serializable]
	public sealed class InputLayout : ygnuJPyjhZTGYdIDYqMweKSjbBks
	{
		private const string keyCategory = "controller_map/layout";

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _name;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		private string _descriptiveName;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		private string _key;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		private int _id;

		[NonSerialized]
		private tiNBYbYMraZDnyWczeThmkcdcMCM shkgOxPKPFYhcNEsxLgBnrIFYLtT;

		[NonSerialized]
		private int NOfLSoTfqJMxFKRqyGwZVcrpFhzi;

		public string name
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public string descriptiveName
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public int id
		{
			get
			{
				return 0;
			}
			internal set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string ygnuJPyjhZTGYdIDYqMweKSjbBks.keyCategory => null;

		string ygnuJPyjhZTGYdIDYqMweKSjbBks.scriptingName => null;

		string ygnuJPyjhZTGYdIDYqMweKSjbBks.nonLocalizedDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string ygnuJPyjhZTGYdIDYqMweKSjbBks.key => null;

		int ygnuJPyjhZTGYdIDYqMweKSjbBks.autoGeneratedValueFlags
		{
			get
			{
				return 0;
			}
			set
			{
			}
		}

		public InputLayout()
		{
		}

		public InputLayout(InputLayout P_0)
		{
		}

		public InputLayout Clone()
		{
			return null;
		}

		internal void tlsboqObtKoiPZLWgfNWNukkrnKO()
		{
		}

		internal void ezdTyjTUXohPkdLYYXFKvKXkbeUL()
		{
		}
	}
}
