using System;
using UnityEngine;

namespace Rewired
{
	[Serializable]
	public abstract class InputCategory : ygnuJPyjhZTGYdIDYqMweKSjbBks
	{
		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _name;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		protected string _descriptiveName;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		protected string _key;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _tag;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		protected int _id;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected bool _userAssignable;

		[NonSerialized]
		private tiNBYbYMraZDnyWczeThmkcdcMCM kkaFJtcEfXDKVzErQnfzOUgfQVDkA;

		[NonSerialized]
		private int ywFKtFWNUjBjWCJrYaoyfEtIhlkaB;

		internal abstract string keyCategory { get; }

		public string name
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public string descriptiveName
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public string tag
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public int id
		{
			get
			{
				return 0;
			}
			internal set
			{
			}
		}

		public bool userAssignable
		{
			get
			{
				return false;
			}
			internal set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string ygnuJPyjhZTGYdIDYqMweKSjbBks.keyCategory => null;

		string ygnuJPyjhZTGYdIDYqMweKSjbBks.scriptingName => null;

		string ygnuJPyjhZTGYdIDYqMweKSjbBks.nonLocalizedDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string ygnuJPyjhZTGYdIDYqMweKSjbBks.key => null;

		int ygnuJPyjhZTGYdIDYqMweKSjbBks.autoGeneratedValueFlags
		{
			get
			{
				return 0;
			}
			set
			{
			}
		}

		public InputCategory()
		{
		}

		public InputCategory(InputCategory P_0)
		{
		}

		internal virtual void ZZMjnVEmerGakmqPbAVaqWetfITIA()
		{
		}

		internal virtual void fctRAgpiaDZgjgsrNjkskqtYXbiy()
		{
		}
	}
}
