using System;

internal struct YWumhJCpCQTVjskCTcIoILKEFuRI
{
	public IntPtr ZWtEIVCLNCpVNyDISCnCWMsygkK;

	public qWiBGvGbARgYWgfshAjjsHfXsIjQ MsMEjJRvHUZAMBtbRMThVTmGckQ;

	public jpRetmpvlSMoNYSCQhXVFnpsFpf FYYDbcObdDNtyZjneiznVgVHJQP;

	public uint aIVKuFBvBDiabBRhnpPiQbmOPbS;

	public uint MUjLXcXSkaSGwgaKBHQZCsppZvco;

	public int dpkaDSHhWDZEfdjUruZmMIdAJgKg;

	public int xEUKPyQaTfqoROGHJowSWeletXA;

	public int VeUXJbtopZnzuPExHBOZDuueBov;

	internal YWumhJCpCQTVjskCTcIoILKEFuRI(ref xkJqMOEQeGTfwKaRfpLTGoGtuOK rawInput)
	{
		ZWtEIVCLNCpVNyDISCnCWMsygkK = rawInput.uXaSVNCSQvDOAiNhBrdVzRoycNS.ZWtEIVCLNCpVNyDISCnCWMsygkK;
		MsMEjJRvHUZAMBtbRMThVTmGckQ = (qWiBGvGbARgYWgfshAjjsHfXsIjQ)rawInput.qUOmbTETUXuKZoTqSzcKuTsxCRK.WibnlhrIoppUjEuxjomaVCUrgKFC.rgNOkrpmhiGBrLTBaaLZBGFVYBc;
		FYYDbcObdDNtyZjneiznVgVHJQP = (jpRetmpvlSMoNYSCQhXVFnpsFpf)rawInput.qUOmbTETUXuKZoTqSzcKuTsxCRK.WibnlhrIoppUjEuxjomaVCUrgKFC.AJzcWEjsBVIccgMdUUpYrczeewv.FYYDbcObdDNtyZjneiznVgVHJQP;
		dpkaDSHhWDZEfdjUruZmMIdAJgKg = rawInput.qUOmbTETUXuKZoTqSzcKuTsxCRK.WibnlhrIoppUjEuxjomaVCUrgKFC.AJzcWEjsBVIccgMdUUpYrczeewv.jbJpGshbNaJDDTyKCBXvtfoEQCA;
		MUjLXcXSkaSGwgaKBHQZCsppZvco = rawInput.qUOmbTETUXuKZoTqSzcKuTsxCRK.WibnlhrIoppUjEuxjomaVCUrgKFC.sSPQMlHrHfhsGlgrSAiddTdAHiSC;
		xEUKPyQaTfqoROGHJowSWeletXA = rawInput.qUOmbTETUXuKZoTqSzcKuTsxCRK.WibnlhrIoppUjEuxjomaVCUrgKFC.WCiySinqDBIsPrDhzkiIZMFBWtz;
		VeUXJbtopZnzuPExHBOZDuueBov = rawInput.qUOmbTETUXuKZoTqSzcKuTsxCRK.WibnlhrIoppUjEuxjomaVCUrgKFC.vkeceKhuYfvXeMYxfClAWIPgirQ;
		aIVKuFBvBDiabBRhnpPiQbmOPbS = rawInput.qUOmbTETUXuKZoTqSzcKuTsxCRK.WibnlhrIoppUjEuxjomaVCUrgKFC.aIVKuFBvBDiabBRhnpPiQbmOPbS;
	}
}
