using System;
using UnityEngine;

namespace Rewired
{
	[Serializable]
	public sealed class InputLayout : dmwPlHfCHErBELjQlGwCmsUXbNbq
	{
		private const string keyCategory = "controller_map/layout";

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _name;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _descriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _key;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private int _id;

		[NonSerialized]
		private kHQCdvDFmtugtOEvKzWXyTgZIwTh dCfCAhWhvGMQybtnOQWlfTMzmPeT;

		[NonSerialized]
		private int ONoSDiGTYItdPscdLHufaBdZnDmTA;

		public string name
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public string descriptiveName
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public int id
		{
			get
			{
				return 0;
			}
			internal set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string dmwPlHfCHErBELjQlGwCmsUXbNbq.keyCategory => null;

		string dmwPlHfCHErBELjQlGwCmsUXbNbq.scriptingName => null;

		string dmwPlHfCHErBELjQlGwCmsUXbNbq.nonLocalizedDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string dmwPlHfCHErBELjQlGwCmsUXbNbq.key => null;

		int dmwPlHfCHErBELjQlGwCmsUXbNbq.autoGeneratedValueFlags
		{
			get
			{
				return 0;
			}
			set
			{
			}
		}

		public InputLayout()
		{
		}

		public InputLayout(InputLayout P_0)
		{
		}

		public InputLayout Clone()
		{
			return null;
		}

		internal void qhzEymTPFTQTJjnLFMvaHsmUrpFM()
		{
		}

		internal void zWwMTpCbhfsQaROLtudwnsRMUfHW()
		{
		}
	}
}
