using System;
using Rewired.Internal.Localization;
using UnityEngine;

namespace Rewired
{
	[Serializable]
	public abstract class InputCategory : jtAeQMwqfCHdCmeHvhaRCqwDmBxb
	{
		[CustomObfuscation(rename = false)]
		[SerializeField]
		protected string _name;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		protected string _descriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _key;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _tag;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		protected int _id;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		protected bool _userAssignable;

		[NonSerialized]
		private ySFzLcEuqAOMOxTEGgUhEEdHrazE oGPaEasMppAsagimCGQlgSqfnxSs;

		[NonSerialized]
		private int rDnRVTAZXyaVlJOBjDydLOTjrRpD;

		internal abstract string keyCategory { get; }

		public string name
		{
			get
			{
				return _name;
			}
			internal set
			{
				_name = text;
			}
		}

		public string descriptiveName
		{
			get
			{
				if (!ReInput.isReady || !LocalizationManager.isEnabled || oGPaEasMppAsagimCGQlgSqfnxSs == null)
				{
					return _descriptiveName;
				}
				return oGPaEasMppAsagimCGQlgSqfnxSs.jXwgbYbEpdqHGeBdCbXEcskUaWaFA;
			}
			internal set
			{
				nonLocalizedDescriptiveName = text;
			}
		}

		public string tag
		{
			get
			{
				return _tag;
			}
			internal set
			{
				_tag = text;
			}
		}

		public int id
		{
			get
			{
				return _id;
			}
			internal set
			{
				_id = num;
			}
		}

		public bool userAssignable
		{
			get
			{
				return _userAssignable;
			}
			internal set
			{
				_userAssignable = flag;
			}
		}

		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return _key;
			}
			set
			{
				_key = value;
				if (ReInput.isReady && oGPaEasMppAsagimCGQlgSqfnxSs != null)
				{
					oGPaEasMppAsagimCGQlgSqfnxSs.OXcBXtPnTqYHpiucqKbwxkVzPkjf();
				}
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
				if (ReInput.isReady && oGPaEasMppAsagimCGQlgSqfnxSs != null)
				{
					oGPaEasMppAsagimCGQlgSqfnxSs.dsySnzlaDCdVTBdBHhqcOjWsSalGA();
				}
			}
		}

		string jtAeQMwqfCHdCmeHvhaRCqwDmBxb.keyCategory => keyCategory;

		string jtAeQMwqfCHdCmeHvhaRCqwDmBxb.scriptingName => _name;

		string jtAeQMwqfCHdCmeHvhaRCqwDmBxb.nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
			}
		}

		string jtAeQMwqfCHdCmeHvhaRCqwDmBxb.key => _key;

		int jtAeQMwqfCHdCmeHvhaRCqwDmBxb.autoGeneratedValueFlags
		{
			get
			{
				return rDnRVTAZXyaVlJOBjDydLOTjrRpD;
			}
			set
			{
				rDnRVTAZXyaVlJOBjDydLOTjrRpD = value;
			}
		}

		public InputCategory()
		{
		}

		public InputCategory(InputCategory P_0)
		{
			_name = P_0._name;
			_descriptiveName = P_0._descriptiveName;
			_key = P_0._key;
			_tag = P_0._tag;
			_id = P_0._id;
			_userAssignable = P_0._userAssignable;
			rDnRVTAZXyaVlJOBjDydLOTjrRpD = P_0.rDnRVTAZXyaVlJOBjDydLOTjrRpD;
		}

		internal virtual void zweOkwOYzJmmdPKMUZyDxJxHpxON()
		{
			oGPaEasMppAsagimCGQlgSqfnxSs = ySFzLcEuqAOMOxTEGgUhEEdHrazE.VxSNvmooWfTkIVcICGUZnqoUJPDW(this);
		}

		internal virtual void vjLugohvsLblZuxYcbzfaOVaQPnA()
		{
		}
	}
}
