using System;
using Rewired.Internal.Localization;
using UnityEngine;

namespace Rewired
{
	[Serializable]
	public sealed class InputLayout : jtAeQMwqfCHdCmeHvhaRCqwDmBxb
	{
		private const string keyCategory = "controller_map/layout";

		[CustomObfuscation(rename = false)]
		[SerializeField]
		private string _name;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _descriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _key;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		private int _id;

		[NonSerialized]
		private ySFzLcEuqAOMOxTEGgUhEEdHrazE oGPaEasMppAsagimCGQlgSqfnxSs;

		[NonSerialized]
		private int rDnRVTAZXyaVlJOBjDydLOTjrRpD;

		public string name
		{
			get
			{
				return _name;
			}
			internal set
			{
				_name = text;
			}
		}

		public string descriptiveName
		{
			get
			{
				if (!ReInput.isReady || !LocalizationManager.isEnabled || oGPaEasMppAsagimCGQlgSqfnxSs == null)
				{
					return _descriptiveName;
				}
				return oGPaEasMppAsagimCGQlgSqfnxSs.jXwgbYbEpdqHGeBdCbXEcskUaWaFA;
			}
			internal set
			{
				nonLocalizedDescriptiveName = text;
			}
		}

		public int id
		{
			get
			{
				return _id;
			}
			internal set
			{
				_id = num;
			}
		}

		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return _key;
			}
			set
			{
				_key = value;
				if (ReInput.isReady && oGPaEasMppAsagimCGQlgSqfnxSs != null)
				{
					oGPaEasMppAsagimCGQlgSqfnxSs.OXcBXtPnTqYHpiucqKbwxkVzPkjf();
				}
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
				if (ReInput.isReady && oGPaEasMppAsagimCGQlgSqfnxSs != null)
				{
					oGPaEasMppAsagimCGQlgSqfnxSs.dsySnzlaDCdVTBdBHhqcOjWsSalGA();
				}
			}
		}

		string jtAeQMwqfCHdCmeHvhaRCqwDmBxb.keyCategory => "controller_map/layout";

		string jtAeQMwqfCHdCmeHvhaRCqwDmBxb.scriptingName => _name;

		string jtAeQMwqfCHdCmeHvhaRCqwDmBxb.nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
			}
		}

		string jtAeQMwqfCHdCmeHvhaRCqwDmBxb.key => _key;

		int jtAeQMwqfCHdCmeHvhaRCqwDmBxb.autoGeneratedValueFlags
		{
			get
			{
				return rDnRVTAZXyaVlJOBjDydLOTjrRpD;
			}
			set
			{
				rDnRVTAZXyaVlJOBjDydLOTjrRpD = value;
			}
		}

		public InputLayout()
		{
		}

		public InputLayout(InputLayout P_0)
			: this()
		{
			_name = P_0._name;
			_descriptiveName = P_0._descriptiveName;
			_key = P_0._key;
			_id = P_0._id;
			rDnRVTAZXyaVlJOBjDydLOTjrRpD = P_0.rDnRVTAZXyaVlJOBjDydLOTjrRpD;
		}

		public InputLayout Clone()
		{
			return new InputLayout(this);
		}

		internal void zweOkwOYzJmmdPKMUZyDxJxHpxON()
		{
			oGPaEasMppAsagimCGQlgSqfnxSs = ySFzLcEuqAOMOxTEGgUhEEdHrazE.VxSNvmooWfTkIVcICGUZnqoUJPDW(this);
		}

		internal void vjLugohvsLblZuxYcbzfaOVaQPnA()
		{
		}
	}
}
