using System;
using System.Collections.Generic;
using NBT.Tags;
using UnityEngine;
using mattmc3.dotmore.Collections.Generic;

public class RplCore
{
	private enum CONST_SIGNALTYPES
	{
		SIGNAL_NONE = 0,
		SIGNAL_SINE = 1,
		SIGNAL_SQUARE = 2,
		SIGNAL_TRIANGLE = 3,
		SIGNAL_SAWTOOTH = 4,
		SIGNAL_RANDOM = 5,
		SIGNAL_CONSTANT = 6
	}

	public enum STATEMENT
	{
		PUSH = 0,
		READ = 1,
		WRITE = 2,
		DELETE = 3,
		REFREAD = 4,
		REFWRITE = 5,
		REFEXISTS = 6,
		REFDELETE = 7,
		EXISTS = 8,
		CLEARLOCALS = 9,
		READGLOBAL = 10,
		WRITEGLOBAL = 11,
		DELETEGLOBAL = 12,
		REFREADGLOBAL = 13,
		REFWRITEGLOBAL = 14,
		REFEXISTSGLOBAL = 15,
		REFDELETEGLOBAL = 16,
		EXISTSGLOBAL = 17,
		CLEARGLOBALS = 18,
		OPENTRAN = 19,
		CLOSETRAN = 20,
		OPENBRACKET = 21,
		CLOSEBRACKET = 22,
		OPENBRACE = 23,
		CLOSEBRACE = 24,
		NOTPERSIST = 25,
		IF = 26,
		ELSE = 27,
		ENDIF = 28,
		DO = 29,
		LOOP = 30,
		I = 31,
		J = 32,
		K = 33,
		WHILE = 34,
		REPEAT = 35,
		ENDWHILE = 36,
		BREAK = 37,
		SWITCH = 38,
		ENDSWITCH = 39,
		CASE = 40,
		ENDCASE = 41,
		ONCE = 42,
		ENDONCE = 43,
		RANDINT = 44,
		RANDFLOAT = 45,
		DUP = 46,
		DUP2 = 47,
		SWAP = 48,
		POP = 49,
		CLEARSTACK = 50,
		STACKSIZE = 51,
		ASINT = 52,
		ASFLOAT = 53,
		ASSTRING = 54,
		GT = 55,
		GTE = 56,
		LT = 57,
		LTE = 58,
		EQ = 59,
		NEQ = 60,
		EQ0 = 61,
		NEQ0 = 62,
		GT0 = 63,
		GTE0 = 64,
		LT0 = 65,
		LTE0 = 66,
		ADD = 67,
		SUB = 68,
		MUL = 69,
		DIV = 70,
		MOD = 71,
		MOD2 = 72,
		ABS = 73,
		ROUND = 74,
		NEG = 75,
		SIGN = 76,
		SIGN0 = 77,
		CLAMP = 78,
		CLAMP01 = 79,
		DOT = 80,
		CROSS = 81,
		NUMREPEAT = 82,
		PINGPONG = 83,
		SIN = 84,
		COS = 85,
		TAN = 86,
		ASIN = 87,
		ACOS = 88,
		ATAN = 89,
		ATAN2 = 90,
		PI = 91,
		TAU = 92,
		TWOPI = 93,
		HALFPI = 94,
		QUARTERPI = 95,
		THREEQUARTERPI = 96,
		THREEHALVESPI = 97,
		E = 98,
		RAD2DEG = 99,
		DEG2RAD = 100,
		SIGNALGENERATOR = 101,
		MININT = 102,
		MAXINT = 103,
		VECTOR0 = 104,
		BALLISTICARCLATERAL = 105,
		BALLISTICARCPOS = 106,
		POW = 107,
		SQRT = 108,
		LOG = 109,
		LN = 110,
		LOG10 = 111,
		MIN = 112,
		MAX = 113,
		FLOOR = 114,
		CEIL = 115,
		APPROXIMATELY = 116,
		AVG2 = 117,
		AND = 118,
		OR = 119,
		XOR = 120,
		NOT = 121,
		TRUE = 122,
		FALSE = 123,
		DQ = 124,
		CR = 125,
		LF = 126,
		TAB = 127,
		GETTYPE = 128,
		ISNULL = 129,
		NULL = 130,
		V2 = 131,
		V3 = 132,
		V4 = 133,
		EV2 = 134,
		EV3 = 135,
		EV4 = 136,
		TOCELL = 137,
		FROMCELL = 138,
		CREATELIST = 139,
		LIST = 140,
		LISTN = 141,
		CREATELISTSTARTINGSIZE = 142,
		GETLISTELEMENT = 143,
		SETLISTELEMENT = 144,
		SETLISTELEMENTRPN = 145,
		APPENDTOLIST = 146,
		PREPENDTOLIST = 147,
		APPENDSTACKTOLIST = 148,
		PREPENDSTACKTOLIST = 149,
		INSERTLISTELEMENT = 150,
		REMOVELISTELEMENT = 151,
		GETLISTCOUNT = 152,
		LISTCONTAINS = 153,
		GETLISTINDEX = 154,
		GETLISTINDICES = 155,
		REVERSELIST = 156,
		CLEARLIST = 157,
		PUSHLIST = 158,
		POPLIST = 159,
		APPENDLISTTOLIST = 160,
		PREPENDLISTTOLIST = 161,
		LISTTOSTACK = 162,
		CREATETABLE = 163,
		CLEARTABLE = 164,
		GETTABLEELEMENT = 165,
		SETTABLEELEMENT = 166,
		SETTABLEELEMENTRPN = 167,
		REMOVETABLEELEMENT = 168,
		GETTABLECOUNT = 169,
		TABLE = 170,
		TABLEN = 171,
		GETTABLEKEYS = 172,
		GETTABLEVALUES = 173,
		TABLECONTAINSKEY = 174,
		COPY = 175,
		DEEPCOPY = 176,
		DISTANCECELL = 177,
		DISTANCE = 178,
		MAGNITUDE = 179,
		SQRMAGNITUDE = 180,
		SHORTESTANGLE = 181,
		VECTORANGLECELL = 182,
		VECTORANGLE = 183,
		ROTATETOWARDS = 184,
		ROTATETOWARDSCELL = 185,
		NORMALIZE = 186,
		DISTANCEPOINTLINE = 187,
		MOVETOWARDS = 188,
		CONCAT = 189,
		CONCAT3 = 190,
		CONCAT4 = 191,
		SUBSTRING = 192,
		STARTSWITH = 193,
		ENDSWITH = 194,
		SPLIT = 195,
		STRINGTOLIST = 196,
		STRINGLENGTH = 197,
		TOUPPER = 198,
		TOLOWER = 199,
		STRINGREPLACE = 200,
		REMOVEWHITESPACE = 201,
		DEBUG = 202,
		DEBUGALLSP = 203,
		TRACE = 204,
		TRACE2 = 205,
		TRACE3 = 206,
		TRACE4 = 207,
		TRACE5 = 208,
		TRACEALL = 209,
		TRACEALLSP = 210,
		TRACESTACK = 211,
		CLEARTRACELOG = 212,
		GETTIMESTRING = 213,
		ELAPSEDTIME = 214,
		PRINT = 215,
		PRINT2 = 216,
		PRINT3 = 217,
		PRINT4 = 218,
		PRINT5 = 219,
		PRINTALL = 220,
		PRINTALLSP = 221,
		PRINTSTACK = 222,
		GETPRINTPREFIXENABLED = 223,
		SETPRINTPREFIXENABLED = 224,
		CLEARPRINTLOG = 225,
		CALL = 226,
		REFCALL = 227,
		FUNC = 228,
		RETURN = 229,
		EOS = 230,
		NULLCOMMAND = 231,
		GETGLOBALTABLE = 232,
		SETGLOBALTABLE = 233,
		GETGLOBALLIST = 234,
		SETGLOBALLIST = 235,
		SETTIMER0 = 236,
		SETTIMER1 = 237,
		SETTIMER2 = 238,
		SETTIMER3 = 239,
		GETTIMER0 = 240,
		GETTIMER1 = 241,
		GETTIMER2 = 242,
		GETTIMER3 = 243,
		SETTIMEROBEYPAUSE0 = 244,
		SETTIMEROBEYPAUSE1 = 245,
		SETTIMEROBEYPAUSE2 = 246,
		SETTIMEROBEYPAUSE3 = 247,
		ISEDITMODE = 248,
		INVOCATIONCOUNT = 249,
		GETUNITDESTROYED = 250,
		GETUNITENABLED = 251,
		SETUNITENABLED = 252,
		GETUNITARMED = 253,
		SETUNITARMED = 254,
		GETUNITSUPPLIED = 255,
		SETUNITSUPPLIED = 256,
		GETUNITHEALTH = 257,
		SETUNITHEALTH = 258,
		GETUNITMAXHEALTH = 259,
		SETUNITMAXHEALTH = 260,
		GETUNITHEALRATE = 261,
		SETUNITHEALRATE = 262,
		GETUNITAMMO = 263,
		SETUNITAMMO = 264,
		GETUNITMAXAMMO = 265,
		SETUNITMAXAMMO = 266,
		GETUNITAMMOWARE = 267,
		SETUNITAMMOWARE = 268,
		GETUNITBUILDWARE = 269,
		SETUNITBUILDWARE = 270,
		GETUNITCANDESTROY = 271,
		SETUNITCANDESTROY = 272,
		GETUNITCREEPERDAMAGES = 273,
		SETUNITCREEPERDAMAGES = 274,
		GETUNITANTICREEPERDAMAGES = 275,
		SETUNITANTICREEPERDAMAGES = 276,
		GETUNITFOOTPRINTRESISTSCREEPERHEIGHT = 277,
		SETUNITFOOTPRINTRESISTSCREEPERHEIGHT = 278,
		GETUNITCONNECTABLE = 279,
		SETUNITCONNECTABLE = 280,
		GETUNITRANGE = 281,
		GETUNITRANGEWITHMODS = 282,
		SETUNITMODRANGES = 283,
		SETUNITRANGE = 284,
		GETUNITFIREOFFSET = 285,
		SETUNITFIREOFFSET = 286,
		GETUNITTARGETOFFSET = 287,
		SETUNITTARGETOFFSET = 288,
		GETUNITREQUESTPACKETS = 289,
		SETUNITREQUESTPACKETS = 290,
		GETUNITPACKETREQUESTRATE = 291,
		SETUNITPACKETREQUESTRATE = 292,
		GETUNITERNSTATE = 293,
		GETUNITERNSIMULATED = 294,
		SETUNITERNSIMULATED = 295,
		GETUNITSUPPRESSCOUNT = 296,
		SETUNITSUPPRESSCOUNT = 297,
		GETUNITOFFICIALNAME = 298,
		GETUNITTYPE = 299,
		ADDASWAREHOLDER = 300,
		REMOVEASWAREHOLDER = 301,
		GETUNITDESTROYUNEVENLAND = 302,
		SETUNITDESTROYUNEVENLAND = 303,
		GETUNITOCCUPIESLAND = 304,
		SETUNITOCCUPIESLAND = 305,
		GETUNITDAMAGEDBYCREEPER = 306,
		SETUNITDAMAGEDBYCREEPER = 307,
		GETUNITDAMAGEDBYAC = 308,
		SETUNITDAMAGEDBYAC = 309,
		GETUNITLOSENABLED = 310,
		SETUNITLOSENABLED = 311,
		GETUNITCANSTUN = 312,
		SETUNITCANSTUN = 313,
		GETUNITMOVECELL = 314,
		SETUNITMOVECELL = 315,
		GETCELLOCCUPIEDCOUNT = 316,
		SETCELLOCCUPIEDCOUNT = 317,
		GETUNITCANMOVE = 318,
		SETUNITCANMOVE = 319,
		GETUNITSPECIALTARGET = 320,
		SETUNITSPECIALTARGET = 321,
		GETUNITTRUEGUID = 322,
		GETUNITGROWSMESH = 323,
		SETUNITGROWSMESH = 324,
		GETUNITIGNOREDARK = 325,
		SETUNITIGNOREDARK = 326,
		GETUNITWANTSERN = 327,
		SETUNITWANTSERN = 328,
		REGISTERFORMSG = 329,
		DEREGISTERFORMSG = 330,
		SENDMSG = 331,
		SENDMVERSEMSG = 332,
		SETMVERSESENDCREEPERCHANGES = 333,
		SETMVERSECREATESUNITGHOST = 334,
		GETMVERSEPLAYERNUM = 335,
		GETMVERSEPLAYERS = 336,
		SETMSGBUTTON = 337,
		STOPCONSOLE = 338,
		GETGAMETICKCOUNT = 339,
		GETGAMEFRAMECOUNT = 340,
		GETLASTEXECUTIONCOUNT = 341,
		ISMISSIONCOMPLETE = 342,
		SHOWADAMESSAGE = 343,
		SHOWADAMESSAGEATCELL = 344,
		SHOWADAMESSAGEATUNIT = 345,
		ISADAMESSAGESHOWING = 346,
		ISADAMESSAGEREAD = 347,
		GETADALOGOPEN = 348,
		SETADALOGOPEN = 349,
		GETFINALDIALOGOPEN = 350,
		GETTERRAFORMMENUOPEN = 351,
		GETMISSIONSCANCOMPLETE = 352,
		GETTERRAFORMMARKER = 353,
		SETTERRAFORMMARKER = 354,
		GETTERRAFORMDIGSITE = 355,
		SETTERRAFORMACTIVECELL = 356,
		SHOWGAMEMESSAGE = 357,
		CLOSEGAMEMESSAGE = 358,
		ISGAMEMESSAGESHOWING = 359,
		SETGAMEMESSAGETEXT = 360,
		SHOWUIINDICATOR = 361,
		USELEGALUNITCELLS = 362,
		SETLEGALUNITCELLS = 363,
		SETALLLEGALUNITCELLS = 364,
		CANCEL = 365,
		GETSOYLENTMODE = 366,
		SETSOYLENTMODE = 367,
		SETSOYLENTDELAY = 368,
		SETSOYLENTCOUNT = 369,
		ISBUILDUNITSELECTED = 370,
		GETBUILDUNIT = 371,
		GETPAUSE = 372,
		SETPAUSE = 373,
		GETSELECTEDUNITS = 374,
		GETEDITMODE = 375,
		GETCANMOVEUNITS = 376,
		SETCANMOVEUNITS = 377,
		GETUNITCANBUILD = 378,
		SETUNITCANBUILD = 379,
		GETUNITCOUNT = 380,
		GETUNITBUILDLIMIT = 381,
		SETUNITBUILDLIMIT = 382,
		SETCMODEDITMENUNAME = 383,
		SETCMODPLAYERMENUNAME = 384,
		GETUNITSELECTED = 385,
		SETUNITSELECTED = 386,
		GETUNITSELECTABLE = 387,
		SETUNITSELECTABLE = 388,
		SETUNITSSELECTABLE = 389,
		SETCREEPERGRAPHAVAILABLE = 390,
		SETDEPARTBUTTONAVAILABLE = 391,
		SETUNITOUTLINEENABLED = 392,
		SETUNITOUTLINEWIDTH = 393,
		SETUNITOUTLINECOLOR = 394,
		SETUNITOUTLINEMODE = 395,
		GETOPENBUILDTAB = 396,
		GETORBITALCOUNT = 397,
		SETORBITALCOUNT = 398,
		GETECOCOUNTS = 399,
		SELF = 400,
		GETGAMEUPDATECOUNT = 401,
		CREATEUNIT = 402,
		CREATEUNITONTERRAIN = 403,
		GETUNITSETTINGS = 404,
		SETUNITSETTINGS = 405,
		DESTROYUNIT = 406,
		CREATEEFFECT = 407,
		CREATEMIST = 408,
		GETUNITINCREEPER = 409,
		CREATEMISSILE = 410,
		CREATESNIPERSHOT = 411,
		CREATEORB = 412,
		CREATEEGG = 413,
		SETEGGORBDATA = 414,
		SETWALLCHARGED = 415,
		GETOBJACTIVE = 416,
		SETOBJACTIVE = 417,
		GETOBJPOSITION = 418,
		GETOBJROTATION = 419,
		GETOBJSCALE = 420,
		GETOBJCOLOR = 421,
		SETOBJPOSITION = 422,
		SETOBJROTATION = 423,
		SETOBJSCALE = 424,
		SETOBJCOLOR = 425,
		GETOBJFORWARD = 426,
		SETOBJFORWARD = 427,
		ROTATEOBJ = 428,
		ROTATEOBJTOWARDS = 429,
		ROTATEOBJTOWARDSCELL = 430,
		GETOBJFACINGANGLE = 431,
		GETOBJFACINGANGLECELL = 432,
		SETOBJLIGHTCONEVISIBLE = 433,
		CREATETRAIL = 434,
		DESTROYTRAIL = 435,
		SETOBJTEXT = 436,
		SETOBJTEXTCOLOR = 437,
		SETOBJTEXTFONTSIZE = 438,
		SETOBJTEXTBILLOARD = 439,
		SETOBJTEXTBILLBOARD = 440,
		GETUNITCONSTRUCTINGDATA = 441,
		CONSTRUCTUNIT = 442,
		GETUNITCONSTRUCTING = 443,
		GETUNITSPECIFIEDTARGET = 444,
		SETUNITSPECIFIEDTARGET = 445,
		CLEARUNITSPECIFIEDTARGET = 446,
		SETUNITSPECIFIEDTARGETSHOWPATH = 447,
		SETUNITSPECIFIEDTARGETPATHHEIGHT = 448,
		SETUNITSPECIFIEDTARGETPATHSOURCEOFFSET = 449,
		SETUNITSPECIFIEDTARGETOCCUPIESMAP = 450,
		SETUNITDEBUGTEXT = 451,
		GETUNITCONNECTEDTORIFTLAB = 452,
		GETUNITSUPPRESSEDMOVEMENT = 453,
		SETUNITSUPPRESSEDMOVEMENT = 454,
		SETUNITMINIMAPIMAGE = 455,
		SETUNITMINIMAPIMAGECOLOR = 456,
		SETUNITMINIMAPTEXT = 457,
		SETUNITMINIMAPTIMETOEVENT = 458,
		GETERNPORTALEFFICIENCY = 459,
		GETRIFTLAB = 460,
		GETFACTORY = 461,
		GETERNPORTAL = 462,
		GETMINERMODE = 463,
		GETFACTORYWARES = 464,
		SETFACTORYWARES = 465,
		GETUNITUPDATECOUNT = 466,
		GETUNITPOSITION = 467,
		SETUNITPOSITION = 468,
		GETUNITCELL = 469,
		SETUNITCELL = 470,
		GETUNITROTATION = 471,
		SETUNITROTATION = 472,
		GETUNITORIENTATION = 473,
		SETUNITORIENTATION = 474,
		GETUNITFORWARD = 475,
		SETUNITFORWARD = 476,
		ROTATEUNIT = 477,
		ROTATEUNITTOWARDS = 478,
		ROTATEUNITTOWARDSCELL = 479,
		GETUNITSINRANGE = 480,
		GETUNITS = 481,
		GETUNITSBYTYPE = 482,
		GETSCRIPTVAR = 483,
		SETSCRIPTVAR = 484,
		GETSCRIPT1VAR = 485,
		SETSCRIPT1VAR = 486,
		REGISTERSCRIPT = 487,
		DEREGISTERSCRIPT = 488,
		GETREGISTEREDSCRIPTVAR = 489,
		SETREGISTEREDSCRIPTVAR = 490,
		DAMAGEUNIT = 491,
		MOVETOWARDSANDAVOID = 492,
		MOVETOWARDSCELLANDAVOID = 493,
		GETUNITUISTATE = 494,
		SETUNITUISTATE = 495,
		GETUNITUITEXT = 496,
		SETUNITUITEXT = 497,
		GETUNITUIOPTIONS = 498,
		SETUNITUIOPTIONS = 499,
		GETUNITSHIELDRANGE = 500,
		SETUNITSHIELDRANGE = 501,
		DEPLOYUNITSHIELD = 502,
		SETUNITSHIELDVISIBLE = 503,
		GETDECALVISIBLE = 504,
		SETDECALVISIBLE = 505,
		GETDECALCOLOR = 506,
		SETDECALCOLOR = 507,
		GETDECALSIZE = 508,
		SETDECALSIZE = 509,
		GETDECALPOSITION = 510,
		SETDECALPOSITION = 511,
		SHOWRASTER = 512,
		SETRASTERSIZE = 513,
		CLEARRASTER = 514,
		SETRASTER = 515,
		SETRASTERC = 516,
		RASTERCOLOR = 517,
		BLITRASTER = 518,
		BLITFADERASTER = 519,
		SETUNITPOPUPENABLED = 520,
		SETUNITPOPUPTEXT0 = 521,
		SETUNITPOPUPTEXT1 = 522,
		STUNUNIT = 523,
		STUNUNITSINRANGE = 524,
		GETUNITSTUNCOUNT = 525,
		SETUNITSTUNCOUNT = 526,
		CLEARUNITSTUN = 527,
		GETENERGYGENERATION = 528,
		GETENERGYUSE = 529,
		GETENERGYSTORE = 530,
		GETENERGYECO = 531,
		GETENERGYBONUS = 532,
		CREATEBEAM = 533,
		DESTROYBEAM = 534,
		SETBEAMVISIBLE = 535,
		SETBEAMCOLOR = 536,
		SETBEAMBRIGHTNESS = 537,
		SETBEAMWIDTH = 538,
		SETBEAMSTART = 539,
		SETBEAMEND = 540,
		ATTACHBEAM = 541,
		UNATTACHBEAM = 542,
		SETBEAMFORCELOCALEND = 543,
		ISBEAM = 544,
		DESTROYALLBEAMS = 545,
		DESTROYALLATTACHEDBEAMS = 546,
		PLAYSOUND = 547,
		PLAYSOUNDATPOSITION = 548,
		PLAYSOUNDLOOP = 549,
		STOPSOUNDLOOP = 550,
		GETMAPSIZE = 551,
		FC = 552,
		UFC = 553,
		ISV3INMAP = 554,
		ISV2INMAP = 555,
		GETRANDMAPCELL = 556,
		GETTERRAIN = 557,
		GETTERRAINVECTOR = 558,
		SETTERRAIN = 559,
		SETTERRAININRANGE = 560,
		SETTERRAINLINE = 561,
		GETEXACTTERRAIN = 562,
		GETEXACTTERRAINANDNORMAL = 563,
		GETEXACTTERRAINWITHSHIELD = 564,
		GETTERRAINSPECIAL = 565,
		SETTERRAINSPECIAL = 566,
		GETTERRAINOVERRIDE = 567,
		SETTERRAINOVERRIDE = 568,
		BOUNCETERRAINCOLLISION = 569,
		BOUNCEEDGECOLLISION = 570,
		GETTERRAINLOS = 571,
		FLOODFILLTERRAIN = 572,
		GETVOIDHEIGHT = 573,
		SETVOIDHEIGHT = 574,
		SETFIELDRECT = 575,
		GETFIELDCELL = 576,
		SETFIELDCELL = 577,
		GETCREEPERCUTOFF = 578,
		SETCREEPERCUTOFF = 579,
		ISCREEPERCUTOFF = 580,
		GETCREEPERWITHDAMAGEMAP = 581,
		GETCREEPER = 582,
		SETCREEPER = 583,
		ADDCREEPER = 584,
		ADDCREEPERWITHCAP = 585,
		GETCREEPERINRANGE = 586,
		SETCREEPERINRANGE = 587,
		ADDCREEPERINRANGE = 588,
		ADDCREEPERWITHCAPINRANGE = 589,
		CONVERTCREEPERTOAC = 590,
		CONVERTACTOCREEPER = 591,
		DAMAGECREEPER = 592,
		DAMAGEMESH = 593,
		GETMESHHEALTH = 594,
		SETMESHHEALTH = 595,
		GETMAXCREEPERCELL = 596,
		GETMAXACCELL = 597,
		GETMINCREEPERCELL = 598,
		GETMINACCELL = 599,
		GETDARKCELL = 600,
		SETDARKCELL = 601,
		GETEXACTCREEPERHEIGHT = 602,
		GETTOTALCREEPER = 603,
		GETTOTALAC = 604,
		GETCREEPERCOVERAGE = 605,
		GETMAXCREEPERCELLWITHDAMAGE = 606,
		GETMINCREEPERCELLWITHDAMAGE = 607,
		GETCRIMSON = 608,
		SETCRIMSON = 609,
		FINDUNITENEMY = 610,
		GETNEARESTSPORE = 611,
		GETNEARESTAIRSAC = 612,
		GETNEARESTSNIPERTARGET = 613,
		GETNEARESTSPECIALTARGET = 614,
		GETSPECIALTARGETS = 615,
		REFRESHUNITLOSCACHE = 616,
		APPLYTODAMAGEMAP = 617,
		REMOVEUNITDAMAGEMAP = 618,
		CLIPCREEPERLINE = 619,
		GENERATEENERGY = 620,
		SUPPRESSTOTEMACTIVATION = 621,
		GETTOTEMACTIVATED = 622,
		SETTOTEMACTIVATED = 623,
		BOUNCEFADEBLACK = 624,
		GETFLOW = 625,
		SETFLOW = 626,
		GETMISSIONOBJECTIVESTATE = 627,
		ACQUIREMISSIONOBJECTIVE = 628,
		SETCUSTOMOBJECTIVETEXT = 629,
		GETMISSIONOBJECTIVEREQUIRED = 630,
		SETMISSIONOBJECTIVEREQUIRED = 631,
		GETMISSIONOBJECTIVEENABLED = 632,
		SETMISSIONOBJECTIVEENABLED = 633,
		ENDMISSION = 634,
		GETPOINTERTERRAINCOORDS = 635,
		GETMOUSEBUTTONDOWN = 636,
		GETMOUSEBUTTONUP = 637,
		GETMOUSEBUTTON = 638,
		GETMOUSEPOSITION = 639,
		GETMOUSEDELTA = 640,
		GETKEYDOWN = 641,
		GETKEY = 642,
		GETMAPPEDKEYDOWN = 643,
		GETMAPPEDKEY = 644,
		GETMAPPEDKEYSTRINGS = 645,
		GETMOUSESCROLLDELTA = 646,
		GETCAMERAPOSITION = 647,
		SETCAMERAPOSITION = 648,
		GETCAMERAROTATION = 649,
		SETCAMERAROTATION = 650,
		RESETCAMERA = 651,
		GETCAMERAMODE = 652,
		SETCAMERATOPDOWN = 653,
		GETCAMERATOPDOWN = 654,
		SETRPLCAM = 655,
		SETRPLCAMPOSITION = 656,
		GETRPLCAMPOSITION = 657,
		SETRPLCAMROTATION = 658,
		GETRPLCAMROTATION = 659,
		RPLCAMTWEEN = 660,
		RPLCAMTWEENLOOKAT = 661,
		RPLCAMCOPYPOSANDROT = 662,
		SETRPLCAMCURSORLOCK = 663,
		GETRPLCAMFORWARD = 664,
		SETRPLCAMFORWARD = 665,
		GETRPLCAMRIGHT = 666,
		SETRPLCAMRIGHT = 667,
		GETRPLCAMUP = 668,
		SETRPLCAMUP = 669,
		GETUNDERCREEPEREFFECTENABLED = 670,
		SETUNDERCREEPEREFFECTENABLED = 671,
		SETMAPPANENABLED = 672,
		SETMAPZOOMENABLED = 673,
		SETMAPROTATEENABLED = 674,
		EDITADDUNDO = 675,
		EDITRESTOREUNDO = 676,
		EDITREDO = 677,
		SHOWTERRAINRANGEINDICATOR = 678,
		DESTROYTERRAINRANGEINDICATOR = 679,
		APPLYTHEME = 680,
		GETTHEMETEXTURE = 681,
		GETTHEMETEXTURESCALE = 682,
		GETTHEMETEXTUREDETILE = 683,
		GETTHEMETEXTURELIGHT = 684,
		GETTHEMETEXTURELIGHTBOOST = 685,
		GETTHEMENORMAL = 686,
		GETTHEMENORMALAMT = 687,
		GETTHEMENORMALSCALE = 688,
		GETTHEMECLIFFTEXTURE = 689,
		GETTHEMECLIFFSCALE = 690,
		GETTHEMECLIFFLIGHT = 691,
		GETTHEMECLIFFLIGHTBOOST = 692,
		GETTHEMECLIFFNORMAL = 693,
		GETTHEMECLIFFNORMALAMT = 694,
		GETTHEMECLIFFNORMALSCALE = 695,
		SETTHEMETEXTURE = 696,
		SETTHEMETEXTURESCALE = 697,
		SETTHEMETEXTUREDETILE = 698,
		SETTHEMETEXTURELIGHT = 699,
		SETTHEMETEXTURELIGHTBOOST = 700,
		SETTHEMENORMAL = 701,
		SETTHEMENORMALAMT = 702,
		SETTHEMENORMALSCALE = 703,
		SETTHEMECLIFFTEXTURE = 704,
		SETTHEMECLIFFSCALE = 705,
		SETTHEMECLIFFLIGHT = 706,
		SETTHEMECLIFFLIGHTBOOST = 707,
		SETTHEMECLIFFNORMAL = 708,
		SETTHEMECLIFFNORMALAMT = 709,
		SETTHEMECLIFFNORMALSCALE = 710,
		CREATETHEMEOVERLAY = 711,
		DESTROYTHEMEOVERLAY = 712,
		SETTHEMEOVERLAYENABLED = 713,
		SETTHEMEOVERLAYSCALE = 714,
		SETTHEMEOVERLAYOFFSET = 715,
		SETTHEMEOVERLAYCOLOR = 716,
		SETTHEMEOVERLAYAPPLYTOCLIFFS = 717,
		SETTHEMEOVERLAYPOINTFILTER = 718,
		SETTHEMEOVERLAYPIXELS = 719,
		SETTHEMEOVERLAYRECTPIXELS = 720,
		CLEARTHEMEOVERLAY = 721,
		GETMCSENTRIES = 722,
		DELETEMCSENTRY = 723,
		RESERVED1 = 724,
		RESERVED2 = 725,
		RESERVED3 = 726,
		RESERVED4 = 727,
		RESERVED5 = 728
	}

	public struct Command
	{
		public STATEMENT statement;

		public Data data;

		public int metaData;

		public int lineNumber;

		public Command(STATEMENT statement, int lineNumber)
		{
			this.statement = default(STATEMENT);
			data = null;
			metaData = 0;
			this.lineNumber = 0;
		}

		public Command(STATEMENT statement, int arg, int lineNumber)
		{
			this.statement = default(STATEMENT);
			data = null;
			metaData = 0;
			this.lineNumber = 0;
		}

		public Command(STATEMENT statement, float arg, int lineNumber)
		{
			this.statement = default(STATEMENT);
			data = null;
			metaData = 0;
			this.lineNumber = 0;
		}

		public Command(STATEMENT statement, string arg, int lineNumber)
		{
			this.statement = default(STATEMENT);
			data = null;
			metaData = 0;
			this.lineNumber = 0;
		}

		public Command(STATEMENT statement, string arg, int metaData, int lineNumber)
		{
			this.statement = default(STATEMENT);
			data = null;
			this.metaData = 0;
			this.lineNumber = 0;
		}
	}

	public class Data
	{
		public enum TYPE
		{
			NULL = 0,
			INT = 1,
			FLOAT = 2,
			STRING = 3,
			LIST = 4,
			TABLE = 5,
			VECTOR = 6
		}

		private TYPE type;

		public int int_val;

		public float float_val;

		public string string_val;

		public List<Data> list_val;

		public OrderedDictionary2<string, Data> table_val;

		public Vector4 vector_val;

		private int listStackDepth;

		public Data Copy()
		{
			return null;
		}

		public Data()
		{
		}

		public Data(Data val)
		{
		}

		public Data(bool val)
		{
		}

		public Data(int val)
		{
		}

		public Data(float val)
		{
		}

		public Data(string val)
		{
		}

		public Data(List<Data> val)
		{
		}

		public Data(OrderedDictionary2<string, Data> val)
		{
		}

		public Data(Vector4 val)
		{
		}

		public bool Equals(Data d)
		{
			return false;
		}

		public new TYPE GetType()
		{
			return default(TYPE);
		}

		public int GetInt()
		{
			return 0;
		}

		public float GetFloat()
		{
			return 0f;
		}

		public string GetString()
		{
			return null;
		}

		public List<Data> GetList()
		{
			return null;
		}

		public OrderedDictionary2<string, Data> GetTable()
		{
			return null;
		}

		public Vector4 GetVector()
		{
			return default(Vector4);
		}

		public Tag Serialize()
		{
			return null;
		}

		public void Deserialize(Tag t)
		{
		}
	}

	public delegate void DebugTextCallback(RplCore core, string val);

	public delegate void DebugTextClearCallback(RplCore core);

	public bool operateWhilePaused;

	private const int MAX_COMMANDS = 10000000;

	[NonSerialized]
	public string scriptName;

	public List<Command> commands;

	public Dictionary<string, int> funcTable;

	public OrderedDictionary2<string, Data> inputVars;

	public HashSet<string> hiddenInputVars;

	public Stack<Data> stack;

	public Stack<Data> loopStack;

	public Stack<Data> whileStack;

	public Stack<int> callStack;

	public Stack<int> callStackLoopDepth;

	public Stack<int> callStackWhileDepth;

	public Dictionary<string, Data> heap;

	public OrderedDictionary2<string, Data> setInputVars;

	public OrderedDictionary2<string, Data> setCModInputVars;

	public HashSet<string> notPersist;

	private int infoMessageResult;

	private GameObject infoPanel;

	protected bool allowMVerseSend;

	protected bool allowMVerseIgnore;

	protected int _currentCommandIndex;

	private int delay;

	private int currentDelayCount;

	protected int updateCount;

	private int[] onceArray;

	protected int[] timers;

	protected bool[] timerObeyPause;

	protected int invocationCount;

	public CModUnitManager baseUnit;

	private bool preProcessed;

	private bool onceProcessed;

	private bool gameLoadedProcessed;

	private double signalGeneratorRandSeed;

	private int version;

	private Dictionary<string, string> registeredChannels;

	private string registeredCoreName;

	public CPack cpack;

	private static int _instanceID;

	public int instanceID;

	public DebugTextCallback debugTextCallback;

	public DebugTextClearCallback debugTextClearCallback;

	private bool printPrefixEnabled;

	public string runnerScript;

	private bool bypassDelay;

	private int bypassDelaycci;

	private bool skipTimers;

	protected int currentCommandIndex
	{
		get
		{
			return 0;
		}
		set
		{
		}
	}

	public static RplCore GetCoreFromPool(CModUnitManager baseUnit, string scriptName, bool dontCompile = false)
	{
		return null;
	}

	public static void ReturnCoreToPool(RplCore core)
	{
	}

	public static void EmptyCorePool()
	{
	}

	public void RegisterCore(string name)
	{
	}

	public void DeregisterCore()
	{
	}

	public void RegisterForMSG(string channel, string functionName)
	{
	}

	public void DeregisterForMSG(string channel)
	{
	}

	public void DeregisterAllMSGS()
	{
	}

	public void ResetCore()
	{
	}

	public RplCore(CModUnitManager baseUnit, string scriptName)
	{
	}

	~RplCore()
	{
	}

	public void PreGameUpdate()
	{
	}

	public void GameLoadedGameUpdate()
	{
	}

	public void InvokeEvent(string eventName, Data eventData, string varName = "_DATA")
	{
	}

	public void GameUpdate(bool final, bool paused = false)
	{
	}

	public void SetVar(string varName, Data d)
	{
	}

	public Data GetVar(string varName)
	{
		return null;
	}

	public void ClearInputVars()
	{
	}

	public void DTCallback(RplCore core, string val)
	{
	}

	private void DebugText(RplCore core, string val)
	{
	}

	private void DebugTextClear(RplCore core)
	{
	}

	private void PrintMessage(RplCore core, string message)
	{
	}

	public bool Compile()
	{
		return false;
	}

	protected Data GetDataFromStack()
	{
		return null;
	}

	protected bool GetBoolFromStack()
	{
		return false;
	}

	protected int GetIntFromStack()
	{
		return 0;
	}

	protected float GetFloatFromStack()
	{
		return 0f;
	}

	protected string GetStringFromStack()
	{
		return null;
	}

	protected List<Data> GetListFromStack(bool warnOnNonNativeType = false)
	{
		return null;
	}

	protected OrderedDictionary2<string, Data> GetTableFromStack(bool warnOnNonNativeType = false)
	{
		return null;
	}

	protected Vector4 GetVectorFromStack()
	{
		return default(Vector4);
	}

	private void Compare(STATEMENT s)
	{
	}

	private float mod2(float x, float m)
	{
		return 0f;
	}

	private int mod2(int x, int m)
	{
		return 0;
	}

	private void Math(STATEMENT s)
	{
	}

	public virtual void HandleUnitCommands(Command command)
	{
	}

	public virtual void CommandsFinished(int cc)
	{
	}

	private void ProcessCommands(bool start, bool onceP, bool final, bool gameLoaded, string eventName, bool paused = false)
	{
	}

	private static Vector3 ProjectPointLine(Vector3 point, Vector3 lineStart, Vector3 lineEnd)
	{
		return default(Vector3);
	}

	private static float DistancePointLine(Vector3 point, Vector3 lineStart, Vector3 lineEnd)
	{
		return 0f;
	}

	public static List<Data> DeepCopyList(List<Data> l)
	{
		return null;
	}

	public static OrderedDictionary2<string, Data> DeepCopyTable(OrderedDictionary2<string, Data> t)
	{
		return null;
	}

	public virtual TagCompound WriteData()
	{
		return null;
	}

	public virtual void ReadData(Tag tag)
	{
	}
}
