<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>DV.MeshX</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>7.3</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="DV.PointSet">
      <HintPath>..\..\Assemblies\DV.PointSet.dll</HintPath>
    </Reference>
    <Reference Include="BezierCurves">
      <HintPath>..\..\Assemblies\BezierCurves.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="net.smkd.vector3d">
      <HintPath>..\..\Assemblies\net.smkd.vector3d.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>