<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Timberborn.Effects</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Timberborn.NeedSpecs">
      <HintPath>..\..\Assemblies\Timberborn.NeedSpecs.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.GameFactionSystem">
      <HintPath>..\..\Assemblies\Timberborn.GameFactionSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Persistence">
      <HintPath>..\..\Assemblies\Timberborn.Persistence.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Goods">
      <HintPath>..\..\Assemblies\Timberborn.Goods.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.GoodsUI">
      <HintPath>..\..\Assemblies\Timberborn.GoodsUI.dll</HintPath>
    </Reference>
    <Reference Include="Bindito.Core">
      <HintPath>..\..\Assemblies\Bindito.Core.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Common">
      <HintPath>..\..\Assemblies\Timberborn.Common.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.CoreUI">
      <HintPath>..\..\Assemblies\Timberborn.CoreUI.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections.Immutable">
      <HintPath>..\..\Assemblies\System.Collections.Immutable.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>