using System;
using UnityEngine;

namespace Rewired
{
	[Serializable]
	public sealed class InputAction : mQQEUnWrvIENJEQHDjPIUvhAyczkA, gDrCmzJNXwFvGTMAYKGQspUqeYD
	{
		private const string keyCategory = "action";

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private int _id;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _name;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private InputActionType _type;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _descriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _positiveDescriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _negativeDescriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _key;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _positiveKey;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _negativeKey;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private int _behaviorId;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private bool _userAssignable;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private int _categoryId;

		[NonSerialized]
		private ahuRaZdFDycoogbYpYeTHJAPrflRA WhueNXjLlTisKBeBbcRqutLDHGcXA;

		[NonSerialized]
		private int XqDaHJhpYFIYQfOjERnLPOERMwxOB;

		public int id
		{
			get
			{
				return 0;
			}
			internal set
			{
			}
		}

		public string name
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public InputActionType type
		{
			get
			{
				return default(InputActionType);
			}
			internal set
			{
			}
		}

		public string descriptiveName
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public string positiveDescriptiveName
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public string negativeDescriptiveName
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public int behaviorId
		{
			get
			{
				return 0;
			}
			internal set
			{
			}
		}

		public int categoryId
		{
			get
			{
				return 0;
			}
			internal set
			{
			}
		}

		public bool userAssignable
		{
			get
			{
				return false;
			}
			internal set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string positiveKey
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string negativeKey
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedPositiveDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedNegativeDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.keyCategory => null;

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.scriptingName => null;

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.nonLocalizedDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string mQQEUnWrvIENJEQHDjPIUvhAyczkA.nonLocalizedPositiveDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string mQQEUnWrvIENJEQHDjPIUvhAyczkA.nonLocalizedNegativeDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.key => null;

		string mQQEUnWrvIENJEQHDjPIUvhAyczkA.positiveKey
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string mQQEUnWrvIENJEQHDjPIUvhAyczkA.negativeKey
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		int gDrCmzJNXwFvGTMAYKGQspUqeYD.autoGeneratedValueFlags
		{
			get
			{
				return 0;
			}
			set
			{
			}
		}

		public InputAction()
		{
		}

		public InputAction(InputAction P_0)
		{
		}

		public InputAction Clone()
		{
			return null;
		}

		public string GetDisplayName(AxisRange axisRange)
		{
			return null;
		}

		internal void NTPvCyCpmjJwhTblSmBPIyeUdwSb()
		{
		}

		internal void uFhDwxaAuBcVrMQZXRaxMdBHvHns()
		{
		}

		private static AomZkhATSIadYOOLVfcgOnNtMQBs.fyQKArxdnRgBFXnCTGFifmqgwogRA xuZLfpnoFIJOqCEawmVDtpIfWrzS(InputActionType P_0)
		{
			return default(AomZkhATSIadYOOLVfcgOnNtMQBs.fyQKArxdnRgBFXnCTGFifmqgwogRA);
		}
	}
}
