using System;
using UnityEngine;

namespace Rewired
{
	[Serializable]
	public abstract class InputCategory : gDrCmzJNXwFvGTMAYKGQspUqeYD
	{
		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _name;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _descriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _key;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _tag;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected int _id;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected bool _userAssignable;

		[NonSerialized]
		private zepspERRxafWKJaGpLXDAMQMfvgE wGSlsYVeFVmPunxzGpMPwjSEkrnK;

		[NonSerialized]
		private int iWbVxeDSejZThqMbSsXAoRQUAFAF;

		internal abstract string keyCategory { get; }

		public string name
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public string descriptiveName
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public string tag
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public int id
		{
			get
			{
				return 0;
			}
			internal set
			{
			}
		}

		public bool userAssignable
		{
			get
			{
				return false;
			}
			internal set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.keyCategory => null;

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.scriptingName => null;

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.nonLocalizedDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.key => null;

		int gDrCmzJNXwFvGTMAYKGQspUqeYD.autoGeneratedValueFlags
		{
			get
			{
				return 0;
			}
			set
			{
			}
		}

		public InputCategory()
		{
		}

		public InputCategory(InputCategory P_0)
		{
		}

		internal virtual void ZzoVDiFcIzGOVDvNlITWKiMIFbjy()
		{
		}

		internal virtual void jBXBmBeKAZaSYPFvJNoUCmXvWKCW()
		{
		}
	}
}
