using System;
using UnityEngine;

namespace Rewired
{
	[Serializable]
	public sealed class InputLayout : gDrCmzJNXwFvGTMAYKGQspUqeYD
	{
		private const string keyCategory = "controller_map/layout";

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _name;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _descriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _key;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private int _id;

		[NonSerialized]
		private zepspERRxafWKJaGpLXDAMQMfvgE yhMgNWGQzHRSTqdadsWzDRmesKJh;

		[NonSerialized]
		private int DSFfbJfKSDewwrlguBUtvhXAOcHTA;

		public string name
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public string descriptiveName
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public int id
		{
			get
			{
				return 0;
			}
			internal set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.keyCategory => null;

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.scriptingName => null;

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.nonLocalizedDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.key => null;

		int gDrCmzJNXwFvGTMAYKGQspUqeYD.autoGeneratedValueFlags
		{
			get
			{
				return 0;
			}
			set
			{
			}
		}

		public InputLayout()
		{
		}

		public InputLayout(InputLayout P_0)
		{
		}

		public InputLayout Clone()
		{
			return null;
		}

		internal void fmOrYBZOFQQUysQAinBulUGFSOqm()
		{
		}

		internal void yYZktKGFhcsPHASOMrTcJPlVvEeW()
		{
		}
	}
}
