using System;
using Rewired.Internal.Localization;
using UnityEngine;

namespace Rewired
{
	[Serializable]
	public abstract class InputCategory : gDrCmzJNXwFvGTMAYKGQspUqeYD
	{
		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _name;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _descriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _key;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _tag;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected int _id;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected bool _userAssignable;

		[NonSerialized]
		private zepspERRxafWKJaGpLXDAMQMfvgE wGSlsYVeFVmPunxzGpMPwjSEkrnK;

		[NonSerialized]
		private int iWbVxeDSejZThqMbSsXAoRQUAFAF;

		internal abstract string keyCategory { get; }

		public string name
		{
			get
			{
				return _name;
			}
			internal set
			{
				_name = text;
			}
		}

		public string descriptiveName
		{
			get
			{
				if (!ReInput.isReady || !LocalizationManager.isEnabled || wGSlsYVeFVmPunxzGpMPwjSEkrnK == null)
				{
					return _descriptiveName;
				}
				return wGSlsYVeFVmPunxzGpMPwjSEkrnK.LoGZqdROKyuYHJXdnhuxPciDQjeL;
			}
			internal set
			{
				nonLocalizedDescriptiveName = text;
			}
		}

		public string tag
		{
			get
			{
				return _tag;
			}
			internal set
			{
				_tag = text;
			}
		}

		public int id
		{
			get
			{
				return _id;
			}
			internal set
			{
				_id = num;
			}
		}

		public bool userAssignable
		{
			get
			{
				return _userAssignable;
			}
			internal set
			{
				_userAssignable = flag;
			}
		}

		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return _key;
			}
			set
			{
				_key = value;
				if (ReInput.isReady && wGSlsYVeFVmPunxzGpMPwjSEkrnK != null)
				{
					wGSlsYVeFVmPunxzGpMPwjSEkrnK.wmroSGiryndOGMmBfWDEbJMKrRBv();
				}
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
				if (ReInput.isReady && wGSlsYVeFVmPunxzGpMPwjSEkrnK != null)
				{
					wGSlsYVeFVmPunxzGpMPwjSEkrnK.TebLFfuNscsSdmSSCRmDmNccAdoF();
				}
			}
		}

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.keyCategory => keyCategory;

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.scriptingName => _name;

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
			}
		}

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.key => _key;

		int gDrCmzJNXwFvGTMAYKGQspUqeYD.autoGeneratedValueFlags
		{
			get
			{
				return iWbVxeDSejZThqMbSsXAoRQUAFAF;
			}
			set
			{
				iWbVxeDSejZThqMbSsXAoRQUAFAF = value;
			}
		}

		public InputCategory()
		{
		}

		public InputCategory(InputCategory P_0)
		{
			_name = P_0._name;
			_descriptiveName = P_0._descriptiveName;
			_key = P_0._key;
			_tag = P_0._tag;
			_id = P_0._id;
			_userAssignable = P_0._userAssignable;
			iWbVxeDSejZThqMbSsXAoRQUAFAF = P_0.iWbVxeDSejZThqMbSsXAoRQUAFAF;
		}

		internal virtual void ZzoVDiFcIzGOVDvNlITWKiMIFbjy()
		{
			wGSlsYVeFVmPunxzGpMPwjSEkrnK = zepspERRxafWKJaGpLXDAMQMfvgE.HKzbZMduZchtOBhLaihmPtNUHVVO(this);
		}

		internal virtual void jBXBmBeKAZaSYPFvJNoUCmXvWKCW()
		{
		}
	}
}
