using System;
using Rewired.Internal.Localization;
using UnityEngine;

namespace Rewired
{
	[Serializable]
	public sealed class InputLayout : gDrCmzJNXwFvGTMAYKGQspUqeYD
	{
		private const string keyCategory = "controller_map/layout";

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _name;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _descriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _key;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private int _id;

		[NonSerialized]
		private zepspERRxafWKJaGpLXDAMQMfvgE yhMgNWGQzHRSTqdadsWzDRmesKJh;

		[NonSerialized]
		private int DSFfbJfKSDewwrlguBUtvhXAOcHTA;

		public string name
		{
			get
			{
				return _name;
			}
			internal set
			{
				_name = text;
			}
		}

		public string descriptiveName
		{
			get
			{
				if (!ReInput.isReady || !LocalizationManager.isEnabled || yhMgNWGQzHRSTqdadsWzDRmesKJh == null)
				{
					return _descriptiveName;
				}
				return yhMgNWGQzHRSTqdadsWzDRmesKJh.LoGZqdROKyuYHJXdnhuxPciDQjeL;
			}
			internal set
			{
				nonLocalizedDescriptiveName = text;
			}
		}

		public int id
		{
			get
			{
				return _id;
			}
			internal set
			{
				_id = num;
			}
		}

		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return _key;
			}
			set
			{
				_key = value;
				if (ReInput.isReady && yhMgNWGQzHRSTqdadsWzDRmesKJh != null)
				{
					yhMgNWGQzHRSTqdadsWzDRmesKJh.wmroSGiryndOGMmBfWDEbJMKrRBv();
				}
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
				if (ReInput.isReady && yhMgNWGQzHRSTqdadsWzDRmesKJh != null)
				{
					yhMgNWGQzHRSTqdadsWzDRmesKJh.TebLFfuNscsSdmSSCRmDmNccAdoF();
				}
			}
		}

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.keyCategory => "controller_map/layout";

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.scriptingName => _name;

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
			}
		}

		string gDrCmzJNXwFvGTMAYKGQspUqeYD.key => _key;

		int gDrCmzJNXwFvGTMAYKGQspUqeYD.autoGeneratedValueFlags
		{
			get
			{
				return DSFfbJfKSDewwrlguBUtvhXAOcHTA;
			}
			set
			{
				DSFfbJfKSDewwrlguBUtvhXAOcHTA = value;
			}
		}

		public InputLayout()
		{
		}

		public InputLayout(InputLayout P_0)
			: this()
		{
			_name = P_0._name;
			_descriptiveName = P_0._descriptiveName;
			_key = P_0._key;
			_id = P_0._id;
			DSFfbJfKSDewwrlguBUtvhXAOcHTA = P_0.DSFfbJfKSDewwrlguBUtvhXAOcHTA;
		}

		public InputLayout Clone()
		{
			return new InputLayout(this);
		}

		internal void fmOrYBZOFQQUysQAinBulUGFSOqm()
		{
			yhMgNWGQzHRSTqdadsWzDRmesKJh = zepspERRxafWKJaGpLXDAMQMfvgE.HKzbZMduZchtOBhLaihmPtNUHVVO(this);
		}

		internal void yYZktKGFhcsPHASOMrTcJPlVvEeW()
		{
		}
	}
}
