using System;

internal struct qVyRZQOIuXMUHHaroaQRawSSdxck
{
	public IntPtr bXrquYGelDoJfXttpIRbzqVoxIxF;

	public KtqulkIzwYPngSZQClaIqIhJNmUF ycQclCBQdFUJmmhOkkAYsQqOjfhV;

	public BcHlPvznLRsddttrnvLmclviOoWv hnQfzbIBLUMzWoEJLkKCqByFCUqE;

	public uint EWCwHvVVeSxnIgwgWdYivxnMSBUD;

	public uint syxPbhBJItzVAVLveDKeKXtdjmVVA;

	public int HnkFhPjbyWDFJnGjEoJTgtnAhrplA;

	public int XHAcjfYHxobupnkeqiFjdRtqsftl;

	public int hOOUxyzjPSHmCugYimIocEeoCnOZ;

	internal qVyRZQOIuXMUHHaroaQRawSSdxck(ref TiTouRGUQDLgWdlwKFrcffKhCPnU P_0)
	{
		bXrquYGelDoJfXttpIRbzqVoxIxF = P_0.MWayvISaaknDyJMUyglsHWggtIpz.bXrquYGelDoJfXttpIRbzqVoxIxF;
		ycQclCBQdFUJmmhOkkAYsQqOjfhV = (KtqulkIzwYPngSZQClaIqIhJNmUF)P_0.SSaCegYtbDtuwHgjNxDNXRzkPiIc.yQtrXavcKmERVHlOUkyDkwOxlViHA.PRRpOkhGRpmYTaxqZbRqgXTDKOHx;
		hnQfzbIBLUMzWoEJLkKCqByFCUqE = (BcHlPvznLRsddttrnvLmclviOoWv)P_0.SSaCegYtbDtuwHgjNxDNXRzkPiIc.yQtrXavcKmERVHlOUkyDkwOxlViHA.olzQUJrJdGPYOJnQbElfCthatyCg.hnQfzbIBLUMzWoEJLkKCqByFCUqE;
		HnkFhPjbyWDFJnGjEoJTgtnAhrplA = P_0.SSaCegYtbDtuwHgjNxDNXRzkPiIc.yQtrXavcKmERVHlOUkyDkwOxlViHA.olzQUJrJdGPYOJnQbElfCthatyCg.LLTDztlKbrGovoobhBQQMheOLJjI;
		syxPbhBJItzVAVLveDKeKXtdjmVVA = P_0.SSaCegYtbDtuwHgjNxDNXRzkPiIc.yQtrXavcKmERVHlOUkyDkwOxlViHA.MfPlmcRztuavgCrSpMuKmPrIfhpZ;
		XHAcjfYHxobupnkeqiFjdRtqsftl = P_0.SSaCegYtbDtuwHgjNxDNXRzkPiIc.yQtrXavcKmERVHlOUkyDkwOxlViHA.mqaWPdnLhSJyfSiIKuYdyrZLmEGG;
		hOOUxyzjPSHmCugYimIocEeoCnOZ = P_0.SSaCegYtbDtuwHgjNxDNXRzkPiIc.yQtrXavcKmERVHlOUkyDkwOxlViHA.ZqwgQLChkkQWIjWIOBCbbzFoJcjnA;
		EWCwHvVVeSxnIgwgWdYivxnMSBUD = P_0.SSaCegYtbDtuwHgjNxDNXRzkPiIc.yQtrXavcKmERVHlOUkyDkwOxlViHA.EWCwHvVVeSxnIgwgWdYivxnMSBUD;
	}
}
