using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEngine;

public class SFXLookUpIdGenerator
{
	private const string lineEnding = "\n";

	public const string enumCSharpOutputPath = "Assets/Scripts/Base/BasicTypes/SfxTableID.cs";

	private static string[] reservedNames = new string[77]
	{
		"abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
		"class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else", "enum",
		"event", "explicit", "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto",
		"if", "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
		"new", "null", "object", "operator", "out", "override", "params", "private", "protected", "public",
		"readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string",
		"struct", "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
		"unsafe", "ushort", "using", "virtual", "void", "volatile", "while"
	};

	public static void UpdateIDs()
	{
		List<SfxTableElement> list = Resources.LoadAll<SfxTableElement>("SFXTableElements").ToList();
		StringBuilder stringBuilder = new StringBuilder();
		char c = ((list.Count == 0) ? ';' : ',');
		stringBuilder.Append(string.Format("\t\tnone = 0{0}{1}", c, "\n"));
		HashSet<string> hashSet = new HashSet<string>();
		for (int i = 0; i < list.Count; i++)
		{
			SfxTableElement sfxTableElement = list[i];
			string shortName = sfxTableElement.name;
			StringBuilder stringBuilder2 = new StringBuilder();
			if (hashSet.Contains(shortName))
			{
				Debug.LogError("Found duplicate SFX elements with name " + shortName + ". The name must be unique.");
				return;
			}
			hashSet.Add(shortName);
			if (reservedNames.Any((string q) => q == shortName))
			{
				shortName = "__reservedCSharpName__" + shortName;
			}
			for (int num = 0; num < shortName.Length; num++)
			{
				char c2 = shortName[num];
				bool flag = (c2 >= 'A' && c2 <= 'Z') || (c2 >= 'a' && c2 <= 'z') || c2 == '_';
				bool flag2 = c2 >= '0' && c2 <= '9';
				if (num == 0 && flag2)
				{
					stringBuilder2.Append('_');
				}
				stringBuilder2.Append((flag || flag2) ? c2 : '_');
			}
			c = ((i == list.Count - 1) ? ';' : ',');
			stringBuilder.Append(string.Format("\t\t{0} = StringToHash(\"{1}\"){2}{3}", stringBuilder2, stringBuilder2, c, "\n"));
		}
		StringBuilder stringBuilder3 = new StringBuilder();
		stringBuilder3.Append(string.Format("// Generated by {0}\n// from the names/IDs of the SFX look up table entries.\n// Do not edit this file manually.\n// *DO* commit any changes to this file.\nusing static UnityEngine.Animator;\n\npublic static class SfxTableID\n{{\n\tpublic static void Init()\n\t{{\n\t\t// Intentionally empty\n\t}}\n\tpublic static readonly int\n{1}}}\n", "SFXLookUpIdGenerator", stringBuilder));
		string text = stringBuilder3.ToString();
		try
		{
			if (File.ReadAllText("Assets/Scripts/Base/BasicTypes/SfxTableID.cs", Encoding.UTF8) == text)
			{
				return;
			}
		}
		catch
		{
		}
		File.WriteAllText("Assets/Scripts/Base/BasicTypes/SfxTableID.cs", text, Encoding.UTF8);
		Debug.Log("Regenerated Assets/Scripts/Base/BasicTypes/SfxTableID.cs");
	}
}
