<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ProBuilderMeshOps-Unity5</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net35</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>4</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="ProBuilderCore-Unity5">
      <HintPath>..\..\Assemblies\ProBuilderCore-Unity5.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\Assemblies\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="Poly2Tri">
      <HintPath>..\..\Assemblies\Poly2Tri.dll</HintPath>
    </Reference>
    <Reference Include="KdTreeLib">
      <HintPath>..\..\Assemblies\KdTreeLib.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>