internal class WLidSnxDbdFpzgCOypsfxMzGTdKU : ygnuJPyjhZTGYdIDYqMweKSjbBks
{
	protected readonly IIMSRAFgrMZddteJJypOkilIlNdG egmQxVmWqyStlRlCfSizlbhpFMXy;

	private readonly string LlKZtzKEsoJXnHnCSSBcPuPuLOEC;

	private readonly string EfqguRxuarwXMLLgVIvmbSgNDeDy;

	private string KcTyWJNCgUdLJSToXBOSepsxzhBj;

	private readonly string FKlZhKehwuwoxhXbtjDphIeSJeeN;

	private int WKLyMchXyOqLCMAGFOvHXJhFFhod;

	public IIMSRAFgrMZddteJJypOkilIlNdG RfzJSosVZhyZYSORKUqRxCsLfSrB => null;

	string ygnuJPyjhZTGYdIDYqMweKSjbBks.keyCategory => null;

	string ygnuJPyjhZTGYdIDYqMweKSjbBks.scriptingName => null;

	string ygnuJPyjhZTGYdIDYqMweKSjbBks.nonLocalizedDescriptiveName
	{
		get
		{
			return null;
		}
		set
		{
		}
	}

	string ygnuJPyjhZTGYdIDYqMweKSjbBks.key => null;

	int ygnuJPyjhZTGYdIDYqMweKSjbBks.autoGeneratedValueFlags
	{
		get
		{
			return 0;
		}
		set
		{
		}
	}

	public string keyCategory => null;

	public string scriptingName => null;

	public string gVbrDwVHzqzmAqrLtqsncMDUDqCHA => null;

	public string nonLocalizedDescriptiveName => null;

	public string key => null;

	public WLidSnxDbdFpzgCOypsfxMzGTdKU(IIMSRAFgrMZddteJJypOkilIlNdG P_0, string P_1, string P_2, string P_3, string P_4)
	{
	}

	public virtual bool ATnfFHIUPgDFiAbmizmqfKvxVhlbA(WLidSnxDbdFpzgCOypsfxMzGTdKU P_0, bool P_1)
	{
		return false;
	}
}
