namespace DV.Tutorial.QT
{
	public enum QTVerb
	{
		None = 0,
		Look = 1,
		Hold = 2,
		Enable = 3,
		Disable = 4,
		Press = 5,
		SetToForward = 6,
		SetToNeutral = 7,
		SetToReverse = 8,
		Apply = 9,
		FullyApply = 10,
		GentlyApply = 11,
		FullyDisengage = 12,
		Release = 13,
		Push = 14,
		Pull = 15,
		SetToGear1 = 16,
		SetToGear2 = 17,
		Monitor = 18,
		Grab = 19,
		Attach = 20,
		Tighten = 21,
		Open = 22,
		Close = 23,
		Loosen = 24,
		SetCloserToNeutral = 25,
		Ignite = 26,
		Take = 27,
		PutInto = 28,
		EngageCW = 29,
		EngageCCW = 30,
		Refill = 31,
		Accel_Disengage = 32,
		Accel_GentlyEngage = 33,
		Accel_FullyEngage = 34,
		Brake_Disengage = 35,
		Brake_GentlyEngage = 36,
		Brake_FullyEngage = 37
	}
}
