internal sealed class dlJgunMgqCuHEoWFEafqiveGuzx
{
	public static readonly jYVOPQCYHiqgKMeoByaWkMeLSnl uBSigLCuKoBIYXzqmuxuXvfZDRcD = hZjmKiPJrqGxFfdueRqiChAukhay.MEFwrWujTTnLXdqfGVLRDngNyLQ(zybLfJTVUXRSwhwoWMFCuLeYpHV.cmLgKoZPnGaBuvJUzaFUWKHwYRk);
}
