internal enum iigQhpBaDQmotAfvxGytLzcqriC
{
	bAGIIPqiarDJwJDeDisbQKZcySm = 0,
	knkbBcHeMwSiOvSwwLqNtvncVlqH = 1,
	ZLBElTuVGdhJcHKKzlyYByHdwzKg = 2,
	oMdGtofgeUYvpGJdZCKyeFafDgRg = 3,
	xUkaMNSfsZoHPlxlKPpoKmwiOOj = 4,
	pJrwDCEQGkqrKUihETuTfeDVGWq = 5,
	MzVFVdHQwfEwbjnrKLSpXeUliAEF = 6,
	xUmEjqJTVpyLbdvJlpOmBitQlmik = 7,
	VFhYauUPnZBdwgDoKlHdHOvdZXgd = 8,
	IDBsmaspdgSMjVnZhxuTXyWNoWp = 9,
	bAOZULgfhxdBpByVXqkjmEtQwDQ = 10,
	JUfiTMYQJkEBZaXCEBqlaNwGeZy = 11,
	thNXbCCALrOOmJkQTUYXhNeByBy = 12,
	ijEDLhpGDhIOLouBDRRflpyeIJe = 13,
	GUjuPzyvAxELMOquihQtFeToYfa = 14,
	LnATsXQmDSoImIihTswemBqUjWQ = 15,
	XPJMEYmnLPCeNXWKJfQGwfIQBcz = 16,
	CjWLJXcsJnNkBoCEJPPcqKZhHlc = 64,
	nAefkZDzzlrDhMiJyOaDeKfxTfTs = 65,
	UjqNFxdcpYslrxmXeaxbeJofNjyR = 66,
	nducCmcGPXSARkZUHkfauHvBcBDg = 67,
	yCCoxEPpicVtIpuxhORiDKKkDBg = 68
}
