using System;

internal struct cBjdMczDgoEYQlFSGytXSwLhLdF
{
	public IntPtr IwQsZkJYbdNBBYrWJIGRHvvDEft;

	public kGzKERAiEUkXQAhDKgJaitseOtM FqUmioVXxpRWWfcTGmmFOZDQjum;

	public int KzGJFBmETipIxSOdhRqYgimkeILE;

	public keYfQZftRQMIGBjcEezmFOHqjHQy ZHNLnkESFQDwGrHPMgYqDdSPKUA;

	public uvxRgDFmdliTSgWsBezRbUrebGkw ZsAtmYWchUBhLFXbZXHtQxIfUWra;

	public int jujHHTUNJgtQybaJojjODJwnvWSH;

	internal cBjdMczDgoEYQlFSGytXSwLhLdF(ref oJqDOpLSpzXpieFwwDGOPDuUBLb rawInput)
	{
		IwQsZkJYbdNBBYrWJIGRHvvDEft = rawInput.byDGMqNQwQgcEKGrKIjIwBvRyWv.IwQsZkJYbdNBBYrWJIGRHvvDEft;
		FqUmioVXxpRWWfcTGmmFOZDQjum = (kGzKERAiEUkXQAhDKgJaitseOtM)rawInput.nvzezGVBdfISGGHTlahzHbKLnPuh.cXiIaGSjeBKnSzIJGvtEtwBDTsm.JXAzHMxMlcDFMCDyjfKJEGMXiTs;
		KzGJFBmETipIxSOdhRqYgimkeILE = rawInput.nvzezGVBdfISGGHTlahzHbKLnPuh.cXiIaGSjeBKnSzIJGvtEtwBDTsm.KzGJFBmETipIxSOdhRqYgimkeILE;
		ZHNLnkESFQDwGrHPMgYqDdSPKUA = rawInput.nvzezGVBdfISGGHTlahzHbKLnPuh.cXiIaGSjeBKnSzIJGvtEtwBDTsm.wbmxfUinNZtnthzDdPSUImGyMjT;
		ZsAtmYWchUBhLFXbZXHtQxIfUWra = rawInput.nvzezGVBdfISGGHTlahzHbKLnPuh.cXiIaGSjeBKnSzIJGvtEtwBDTsm.lXwAlioodeuHIrjCjXHYWlVRKsK;
		jujHHTUNJgtQybaJojjODJwnvWSH = rawInput.nvzezGVBdfISGGHTlahzHbKLnPuh.cXiIaGSjeBKnSzIJGvtEtwBDTsm.jujHHTUNJgtQybaJojjODJwnvWSH;
	}
}
