namespace PartyCSharpSDK
{
	public enum PARTY_OPTION : uint
	{
		PARTY_OPTION_LOCAL_UDP_SOCKET_BIND_ADDRESS = 0u,
		PARTY_OPTION_LOCAL_DEVICE_DIRECT_PEER_CONNECTIVITY_OPTIONS_MASK = 1u,
		PARTY_OPTION_TEXT_CHAT_FILTER_LEVEL = 2u
	}
}
