<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Kitchen.ResearchMode</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>8.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Entities">
      <HintPath>..\..\Assemblies\Unity.Entities.dll</HintPath>
    </Reference>
    <Reference Include="Kitchen.GameData">
      <HintPath>..\..\Assemblies\Kitchen.GameData.dll</HintPath>
    </Reference>
    <Reference Include="Kitchen.Common">
      <HintPath>..\..\Assemblies\Kitchen.Common.dll</HintPath>
    </Reference>
    <Reference Include="KitchenMode">
      <HintPath>..\..\Assemblies\KitchenMode.dll</HintPath>
    </Reference>
    <Reference Include="Kitchen.Layouts">
      <HintPath>..\..\Assemblies\Kitchen.Layouts.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>..\..\Assemblies\Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Jobs">
      <HintPath>..\..\Assemblies\Unity.Jobs.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>