namespace PartyCSharpSDK
{
	public enum PARTY_TEXT_CHAT_FILTER_LEVEL : uint
	{
		PARTY_TEXT_CHAT_FILTER_LEVEL_FAMILY_FRIENDLY = 0u,
		PARTY_TEXT_CHAT_FILTER_LEVEL_MEDIUM = 1u,
		PARTY_TEXT_CHAT_FILTER_LEVEL_MATURE = 2u
	}
}
