namespace PartyCSharpSDK
{
	public enum PARTY_OPTION : uint
	{
		PARTY_OPTION_LOCAL_UDP_SOCKET_BIND_ADDRESS = 0u,
		PARTY_OPTION_LOCAL_DEVICE_DIRECT_PEER_CONNECTIVITY_OPTIONS_MASK = 1u,
		PARTY_OPTION_TEXT_CHAT_FILTER_LEVEL = 2u,
		PARTY_OPTION_LOCAL_DEVICE_MAX_DIRECT_PEER_CONNECTIONS = 3u,
		PARTY_OPTION_REGION_UPDATE_CONFIGURATION = 4u,
		PARTY_OPTION_REGION_QUALITY_MEASUREMENT_CONFIGURATION = 5u
	}
}
