<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Pug.ECS.Conversion</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Pug.ECS.Authoring">
      <HintPath>..\..\Assemblies\Pug.ECS.Authoring.dll</HintPath>
    </Reference>
    <Reference Include="Pug.Base">
      <HintPath>..\..\Assemblies\Pug.Base.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Pug.ECS.Components">
      <HintPath>..\..\Assemblies\Pug.ECS.Components.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Entities">
      <HintPath>..\..\Assemblies\Unity.Entities.dll</HintPath>
    </Reference>
    <Reference Include="PugConversion">
      <HintPath>..\..\Assemblies\PugConversion.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Physics.Custom">
      <HintPath>..\..\Assemblies\Unity.Physics.Custom.dll</HintPath>
    </Reference>
    <Reference Include="Pug.Other">
      <HintPath>..\..\Assemblies\Pug.Other.dll</HintPath>
    </Reference>
    <Reference Include="Interaction.Components">
      <HintPath>..\..\Assemblies\Interaction.Components.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>..\..\Assemblies\Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="PugProperties">
      <HintPath>..\..\Assemblies\PugProperties.dll</HintPath>
    </Reference>
    <Reference Include="Pug.UnityExtensions">
      <HintPath>..\..\Assemblies\Pug.UnityExtensions.dll</HintPath>
    </Reference>
    <Reference Include="Pug.ECS.Extensions">
      <HintPath>..\..\Assemblies\Pug.ECS.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Entities.Hybrid">
      <HintPath>..\..\Assemblies\Unity.Entities.Hybrid.dll</HintPath>
    </Reference>
    <Reference Include="Pug.ECS.ConditionExtensions">
      <HintPath>..\..\Assemblies\Pug.ECS.ConditionExtensions.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>..\..\Assemblies\Unity.Collections.dll</HintPath>
    </Reference>
    <Reference Include="PugMod.SDK.Runtime">
      <HintPath>..\..\Assemblies\PugMod.SDK.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="ScriptableData">
      <HintPath>..\..\Assemblies\ScriptableData.dll</HintPath>
    </Reference>
    <Reference Include="Affixes.Authoring">
      <HintPath>..\..\Assemblies\Affixes.Authoring.dll</HintPath>
    </Reference>
    <Reference Include="Pug.Automation.Authoring">
      <HintPath>..\..\Assemblies\Pug.Automation.Authoring.dll</HintPath>
    </Reference>
    <Reference Include="Unity.NetCode.Authoring.Hybrid">
      <HintPath>..\..\Assemblies\Unity.NetCode.Authoring.Hybrid.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\..\Assemblies\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Physics">
      <HintPath>..\..\Assemblies\Unity.Physics.dll</HintPath>
    </Reference>
    <Reference Include="Unity.NetCode">
      <HintPath>..\..\Assemblies\Unity.NetCode.dll</HintPath>
    </Reference>
    <Reference Include="CommandMinion.Components">
      <HintPath>..\..\Assemblies\CommandMinion.Components.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Physics.Hybrid">
      <HintPath>..\..\Assemblies\Unity.Physics.Hybrid.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>