namespace Coherence
{
	internal enum DocumentationKeys
	{
		None = 0,
		DeveloperPortalOverview = 1,
		ProjectSetup = 2,
		UploadSchema = 3,
		PrefabSetup = 4,
		SceneSetup = 5,
		Baking = 6,
		Simulators = 7,
		LocalServers = 8,
		AddBridge = 9,
		AddLiveQuery = 10,
		Schemas = 11,
		RoomsAndWorlds = 12,
		CoherenceBridge = 13,
		OnLiveQuerySynced = 14,
		CloudService = 15,
		SimFrame = 16,
		ClientMessages = 17,
		ClientConnectionPrefabs = 18,
		LiveQuery = 19,
		Authority = 20,
		InputQueues = 21,
		CoherenceSync = 22,
		TagQuery = 23,
		SceneTransitioning = 24,
		UnlockToken = 25,
		ReleaseNotes = 26,
		Parenting = 27,
		GettingStarted = 28,
		AutoSimulatorConnection = 29,
		Overview = 30,
		MaxQueryCount = 31,
		CloudApi = 32,
		ReplicationServerApi = 33,
		GlobalQuery = 34
	}
}
