public enum GameCheatType
{
	kLevelUp = 0,
	kGainFuser = 1,
	kToggleUnkillableEnemies = 2,
	kToggleGodMode = 3,
	kToggleOneHitKills = 4,
	kToggleAutoplay = 5,
	kSkipToNextMiniboss = 6,
	kSkipToEnd = 7,
	kMaxOutItems = 8,
	kAddGold = 9,
	kAddBall = 10,
	kAddPassive = 11,
	kAddCombo = 12,
	kCompleteLevel = 13,
	kTestAllCombos = 14,
	kStopEnemySpawning = 15,
	kDisableAllPickups = 16,
	kSetUpReleaseDateTrailer = 17,
	kClearCheatFlag = 18,
	kSkipToEndless = 19,
	kSpamBalls = 20,
	kBallCrash = 21,
	kTestCharCombos = 22,
	kNum = 23
}
