using System;

internal struct iJawmjhAjftQEFiAxCWpAEMQJSfu
{
	public IntPtr LhRFhEzQhelswJJRIavmSCSCiPwe;

	public WkyBRDjfvsDqvYSqXuzqGIrXfcXBA TuXhpLcEOXfHfAIxuKKYafJjEFuDA;

	public TPJwEKUYvbKuilSfeHMSGfDiTeNg bktiwzypKMkdkAqyIXosTDAUhpie;

	public uint yUnTsInILZqYnFTgZtreSODvEOxg;

	public uint FWCsKfSRhVrkkYcnUuAGaHVEtVTI;

	public int THDYfSstaOrzWaQEGDLrZanpFKcQ;

	public int pcADeQaSnINnQgcIfdDDWJLsfWnpc;

	public int CflclKOwnHTPfdPnscweYtrfFTSt;

	internal iJawmjhAjftQEFiAxCWpAEMQJSfu(ref LwLPWqtLAhTwTnToPNxMTOsfkimd P_0)
	{
		LhRFhEzQhelswJJRIavmSCSCiPwe = P_0.mdpNRBIgPyqMtyHIUYmqygMACyJf.YDzHaxbfvrGbwrjQmLwABbzfzzkg;
		TuXhpLcEOXfHfAIxuKKYafJjEFuDA = (WkyBRDjfvsDqvYSqXuzqGIrXfcXBA)P_0.fcVoAeiUSDHLyNBrLCLIvUjkEsmEA.VTUSbPHxfugOZGKMIuTsmbkTxlKR.nCqbxxKlHtjwuZiLHHBzkNDHmTgHA;
		bktiwzypKMkdkAqyIXosTDAUhpie = (TPJwEKUYvbKuilSfeHMSGfDiTeNg)P_0.fcVoAeiUSDHLyNBrLCLIvUjkEsmEA.VTUSbPHxfugOZGKMIuTsmbkTxlKR.tOxaRchAdgVPxEbYpNAnWiDUqccE.dKNdjCJhQSYJmJjdpeJHFnKwaKol;
		THDYfSstaOrzWaQEGDLrZanpFKcQ = P_0.fcVoAeiUSDHLyNBrLCLIvUjkEsmEA.VTUSbPHxfugOZGKMIuTsmbkTxlKR.tOxaRchAdgVPxEbYpNAnWiDUqccE.tcwEqSUBasXRwMWVmKhoOraqPkPX;
		FWCsKfSRhVrkkYcnUuAGaHVEtVTI = P_0.fcVoAeiUSDHLyNBrLCLIvUjkEsmEA.VTUSbPHxfugOZGKMIuTsmbkTxlKR.MzdcKIeucynDDCvuKjjziZQplmdhb;
		pcADeQaSnINnQgcIfdDDWJLsfWnpc = P_0.fcVoAeiUSDHLyNBrLCLIvUjkEsmEA.VTUSbPHxfugOZGKMIuTsmbkTxlKR.chpmPzUeQCrKDowzkeApiraAWPzq;
		CflclKOwnHTPfdPnscweYtrfFTSt = P_0.fcVoAeiUSDHLyNBrLCLIvUjkEsmEA.VTUSbPHxfugOZGKMIuTsmbkTxlKR.nJGhqwuPVPnLZDTUVFIdzQcsDljo;
		yUnTsInILZqYnFTgZtreSODvEOxg = P_0.fcVoAeiUSDHLyNBrLCLIvUjkEsmEA.VTUSbPHxfugOZGKMIuTsmbkTxlKR.zkHTkYdeHWFJNuROnhrpivIvFgXAA;
	}
}
