using System;
using System.Xml.Linq;
using UnityEngine;

namespace ModApi.Craft.Parts
{
	public class PartCollision
	{
		private Assembly _assembly;

		public Assembly Assembly => _assembly;

		public bool AutoGenerated { get; private set; }

		public string ColliderNameA { get; private set; }

		public string ColliderNameB { get; private set; }

		public PartData PartA { get; private set; }

		public PartData PartB { get; private set; }

		public PartCollision(PartData partA, PartData partB)
			: this(partA, null, partB, null, autoGenerated: true)
		{
		}

		public PartCollision(PartData partA, string colliderNameA, PartData partB, string colliderNameB, bool autoGenerated)
		{
			if (partA == partB)
			{
				throw new Exception("PartCollision: PartA and PartB cannot be the same part.");
			}
			PartA = partA;
			PartB = partB;
			ColliderNameA = colliderNameA;
			ColliderNameB = colliderNameB;
			AutoGenerated = autoGenerated;
		}

		public static PartCollision Create(XElement xml, Assembly assembly)
		{
			int num = (int)xml.Attribute("partA");
			int num2 = (int)xml.Attribute("partB");
			PartData partById = assembly.GetPartById(num);
			PartData partById2 = assembly.GetPartById(num2);
			if (partById == null || partById2 == null)
			{
				Debug.LogError($"Unable to create a part collision between part '{num}' and part '{num2}' " + "because " + ((partById == null && partById2 == null) ? "both" : "one") + " of the parts could not be found.");
				return null;
			}
			string colliderNameA = (string)xml.Attribute("colliderNameA");
			string colliderNameB = (string)xml.Attribute("colliderNameB");
			bool autoGenerated = ((bool?)xml.Attribute("autoGenerated")) ?? true;
			return new PartCollision(partById, colliderNameA, partById2, colliderNameB, autoGenerated);
		}

		public XElement GenerateXml()
		{
			return new XElement("Collision", new XAttribute("partA", PartA.Id), new XAttribute("partB", PartB.Id), string.IsNullOrWhiteSpace(ColliderNameA) ? null : new XAttribute("colliderNameA", ColliderNameA), string.IsNullOrWhiteSpace(ColliderNameB) ? null : new XAttribute("colliderNameB", ColliderNameB), AutoGenerated ? null : new XAttribute("autoGenerated", AutoGenerated));
		}

		public PartData GetOtherPart(PartData part)
		{
			if (!(part == PartA))
			{
				if (!(part == PartB))
				{
					return null;
				}
				return PartA;
			}
			return PartB;
		}

		public void SetAssembly(Assembly assembly)
		{
			_assembly = assembly;
		}
	}
}
