<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Timberborn.GameDistrictsUI</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Timberborn.BaseComponentSystem">
      <HintPath>..\..\Assemblies\Timberborn.BaseComponentSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SingletonSystem">
      <HintPath>..\..\Assemblies\Timberborn.SingletonSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EntityNaming">
      <HintPath>..\..\Assemblies\Timberborn.EntityNaming.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Common">
      <HintPath>..\..\Assemblies\Timberborn.Common.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BlueprintSystem">
      <HintPath>..\..\Assemblies\Timberborn.BlueprintSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SelectionSystem">
      <HintPath>..\..\Assemblies\Timberborn.SelectionSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BuildingsNavigation">
      <HintPath>..\..\Assemblies\Timberborn.BuildingsNavigation.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EntityPanelSystem">
      <HintPath>..\..\Assemblies\Timberborn.EntityPanelSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.GameDistricts">
      <HintPath>..\..\Assemblies\Timberborn.GameDistricts.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.CoreUI">
      <HintPath>..\..\Assemblies\Timberborn.CoreUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BatchControl">
      <HintPath>..\..\Assemblies\Timberborn.BatchControl.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.GameDistrictsMigration">
      <HintPath>..\..\Assemblies\Timberborn.GameDistrictsMigration.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Bots">
      <HintPath>..\..\Assemblies\Timberborn.Bots.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TooltipSystem">
      <HintPath>..\..\Assemblies\Timberborn.TooltipSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.WorkerTypesUI">
      <HintPath>..\..\Assemblies\Timberborn.WorkerTypesUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SliderToggleSystem">
      <HintPath>..\..\Assemblies\Timberborn.SliderToggleSystem.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.GameDistrictsMigrationBatchControl">
      <HintPath>..\..\Assemblies\Timberborn.GameDistrictsMigrationBatchControl.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.RootProviders">
      <HintPath>..\..\Assemblies\Timberborn.RootProviders.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.CameraSystem">
      <HintPath>..\..\Assemblies\Timberborn.CameraSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BlockSystem">
      <HintPath>..\..\Assemblies\Timberborn.BlockSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.UILayoutSystem">
      <HintPath>..\..\Assemblies\Timberborn.UILayoutSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Localization">
      <HintPath>..\..\Assemblies\Timberborn.Localization.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.InputSystemUI">
      <HintPath>..\..\Assemblies\Timberborn.InputSystemUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Navigation">
      <HintPath>..\..\Assemblies\Timberborn.Navigation.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TemplateInstantiation">
      <HintPath>..\..\Assemblies\Timberborn.TemplateInstantiation.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Characters">
      <HintPath>..\..\Assemblies\Timberborn.Characters.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EntitySystem">
      <HintPath>..\..\Assemblies\Timberborn.EntitySystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.WorkSystem">
      <HintPath>..\..\Assemblies\Timberborn.WorkSystem.dll</HintPath>
    </Reference>
    <Reference Include="Bindito.Core">
      <HintPath>..\..\Assemblies\Bindito.Core.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Beavers">
      <HintPath>..\..\Assemblies\Timberborn.Beavers.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Coordinates">
      <HintPath>..\..\Assemblies\Timberborn.Coordinates.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>