using System.Collections.Generic;
using ModApi.Craft;
using ModApi.Craft.Parts;
using UnityEngine;

namespace Assets.Scripts.Craft.Parts
{
	public static class PartCollisionIgnoreUtility
	{
		private enum ColliderAttachPointType
		{
			Unknown = 0,
			Ignore = 1,
			DoNotIgnore = 2
		}

		private class ColliderInfo
		{
			public ColliderAttachPointType AttachPointType;

			public Collider Collider;

			public Vector3 Position;

			public Quaternion Rotation;

			public Transform Transform;

			public ColliderInfo(Collider collider)
			{
				Collider = collider;
			}
		}

		public const PartCollisionHandlingMethod DefaultPartCollisionHandling = PartCollisionHandlingMethod.AutoDisablePerCollider;

		public const float MinimumCollisionDistance = 0f;

		private static List<Collider> _collidersA = new List<Collider>();

		private static List<Collider> _collidersB = new List<Collider>();

		public static void ApplyPartCollisions(IPartScript part)
		{
			List<PartCollision> partCollisions = part.CraftScript.Data.Assembly.GetPartCollisions(part.Data);
			for (int i = 0; i < partCollisions.Count; i++)
			{
				ApplyPartCollision(partCollisions[i]);
			}
			_collidersA.Clear();
			_collidersB.Clear();
		}

		public static void ApplyPartCollisions(CraftScript craft)
		{
			IReadOnlyList<PartCollision> partCollisions = craft.Data.Assembly.PartCollisions;
			for (int i = 0; i < partCollisions.Count; i++)
			{
				ApplyPartCollision(partCollisions[i]);
			}
			_collidersA.Clear();
			_collidersB.Clear();
		}

		public static void UpdatePartCollisions(CraftScript craft)
		{
			Assembly assembly = craft.Data.Assembly;
			_ = assembly.Parts;
			assembly.RemovePartCollisions(autoGeneratedOnly: true);
			Dictionary<int, ColliderInfo[]> colliderInfoLookup = new Dictionary<int, ColliderInfo[]>();
			IReadOnlyList<BodyData> bodies = assembly.Bodies;
			int count = bodies.Count;
			for (int i = 0; i < count; i++)
			{
				List<PartData> parts = bodies[i].Parts;
				int count2 = parts.Count;
				for (int j = i + 1; j < count; j++)
				{
					List<PartData> parts2 = bodies[j].Parts;
					int count3 = parts2.Count;
					for (int k = 0; k < count2; k++)
					{
						for (int l = 0; l < count3; l++)
						{
							UpdatePartCollisions(assembly, parts[k], parts2[l], colliderInfoLookup);
						}
					}
				}
			}
			_collidersA.Clear();
			_collidersB.Clear();
		}

		private static void ApplyPartCollision(PartCollision collision)
		{
			if (collision.PartA.PartScript == null || collision.PartB.PartScript == null)
			{
				return;
			}
			_collidersA.Clear();
			_collidersB.Clear();
			collision.PartA.PartScript.GameObject.GetComponentsInChildren(includeInactive: false, _collidersA);
			collision.PartB.PartScript.GameObject.GetComponentsInChildren(includeInactive: false, _collidersB);
			string text = collision.ColliderNameA ?? string.Empty;
			if (text != string.Empty)
			{
				for (int num = _collidersA.Count - 1; num >= 0; num--)
				{
					if (_collidersA[num].name != text)
					{
						_collidersA.RemoveAt(num);
					}
				}
			}
			string text2 = collision.ColliderNameB ?? string.Empty;
			if (text2 != string.Empty)
			{
				for (int num2 = _collidersB.Count - 1; num2 >= 0; num2--)
				{
					if (_collidersB[num2].name != text2)
					{
						_collidersB.RemoveAt(num2);
					}
				}
			}
			if (_collidersA.Count != 0)
			{
				_ = _collidersB.Count;
			}
			for (int i = 0; i < _collidersA.Count; i++)
			{
				for (int j = 0; j < _collidersB.Count; j++)
				{
					Physics.IgnoreCollision(_collidersA[i], _collidersB[j], ignore: true);
				}
			}
		}

		private static PartCollisionHandlingMethod GetCollisionHandlingMethod(PartData partA, PartData partB)
		{
			PartCollisionHandlingMethod partCollisionHandlingMethod = partA.Config.PartCollisionHandling;
			PartCollisionHandlingMethod partCollisionHandlingMethod2 = partB.Config.PartCollisionHandling;
			if (partCollisionHandlingMethod == PartCollisionHandlingMethod.Default)
			{
				partCollisionHandlingMethod = partA.PartType.PartCollisionHandling;
				if (partCollisionHandlingMethod == PartCollisionHandlingMethod.Default)
				{
					partCollisionHandlingMethod = PartCollisionHandlingMethod.AutoDisablePerCollider;
				}
			}
			if (partCollisionHandlingMethod2 == PartCollisionHandlingMethod.Default)
			{
				partCollisionHandlingMethod2 = partB.PartType.PartCollisionHandling;
				if (partCollisionHandlingMethod2 == PartCollisionHandlingMethod.Default)
				{
					partCollisionHandlingMethod2 = PartCollisionHandlingMethod.AutoDisablePerCollider;
				}
			}
			if (partCollisionHandlingMethod == PartCollisionHandlingMethod.Always || partCollisionHandlingMethod2 == PartCollisionHandlingMethod.Always)
			{
				return PartCollisionHandlingMethod.Always;
			}
			if (partCollisionHandlingMethod == PartCollisionHandlingMethod.Never || partCollisionHandlingMethod2 == PartCollisionHandlingMethod.Never)
			{
				return PartCollisionHandlingMethod.Never;
			}
			if (partCollisionHandlingMethod == PartCollisionHandlingMethod.AutoDisablePerPart || partCollisionHandlingMethod2 == PartCollisionHandlingMethod.AutoDisablePerPart)
			{
				return PartCollisionHandlingMethod.AutoDisablePerPart;
			}
			return PartCollisionHandlingMethod.AutoDisablePerCollider;
		}

		private static void UpdatePartCollisions(Assembly assembly, PartData partA, PartData partB, Dictionary<int, ColliderInfo[]> colliderInfoLookup)
		{
			PartCollisionHandlingMethod collisionHandlingMethod = GetCollisionHandlingMethod(partA, partB);
			if (collisionHandlingMethod == PartCollisionHandlingMethod.Always || collisionHandlingMethod == PartCollisionHandlingMethod.Never)
			{
				return;
			}
			if (!colliderInfoLookup.TryGetValue(partA.Id, out var value))
			{
				_collidersA.Clear();
				partA.PartScript.GameObject.GetComponentsInChildren(includeInactive: false, _collidersA);
				_collidersA.RemoveAll((Collider x) => x.TryGetComponent<EnabledScript>(out var component3) && component3.EnabledOnlyInDesigner);
				int count = _collidersA.Count;
				value = new ColliderInfo[count];
				for (int num = 0; num < count; num++)
				{
					value[num] = new ColliderInfo(_collidersA[num]);
				}
				colliderInfoLookup.Add(partA.Id, value);
			}
			if (!colliderInfoLookup.TryGetValue(partB.Id, out var value2))
			{
				_collidersB.Clear();
				partB.PartScript.GameObject.GetComponentsInChildren(includeInactive: false, _collidersB);
				_collidersB.RemoveAll((Collider x) => x.TryGetComponent<EnabledScript>(out var component3) && component3.EnabledOnlyInDesigner);
				int count2 = _collidersB.Count;
				value2 = new ColliderInfo[count2];
				for (int num2 = 0; num2 < count2; num2++)
				{
					value2[num2] = new ColliderInfo(_collidersB[num2]);
				}
				colliderInfoLookup.Add(partB.Id, value2);
			}
			foreach (ColliderInfo colliderInfo in value)
			{
				Collider collider = colliderInfo.Collider;
				if (colliderInfo.AttachPointType == ColliderAttachPointType.Unknown)
				{
					AttachPointScript component = collider.GetComponent<AttachPointScript>();
					colliderInfo.AttachPointType = ((component != null && !component.AttachPoint.IsSurfaceAttachPoint) ? ColliderAttachPointType.Ignore : ColliderAttachPointType.DoNotIgnore);
				}
				if (colliderInfo.AttachPointType == ColliderAttachPointType.Ignore)
				{
					continue;
				}
				if ((object)colliderInfo.Transform == null)
				{
					Transform transform = (colliderInfo.Transform = collider.transform);
					colliderInfo.Position = transform.position;
					colliderInfo.Rotation = transform.rotation;
				}
				foreach (ColliderInfo colliderInfo2 in value2)
				{
					Collider collider2 = colliderInfo2.Collider;
					if (colliderInfo2.AttachPointType == ColliderAttachPointType.Unknown)
					{
						AttachPointScript component2 = collider2.GetComponent<AttachPointScript>();
						colliderInfo2.AttachPointType = ((component2 != null && !component2.AttachPoint.IsSurfaceAttachPoint) ? ColliderAttachPointType.Ignore : ColliderAttachPointType.DoNotIgnore);
					}
					if (colliderInfo2.AttachPointType == ColliderAttachPointType.Ignore)
					{
						continue;
					}
					if ((object)colliderInfo2.Transform == null)
					{
						Transform transform2 = (colliderInfo2.Transform = collider2.transform);
						colliderInfo2.Position = transform2.position;
						colliderInfo2.Rotation = transform2.rotation;
					}
					bool flag = !collider.enabled;
					if (flag)
					{
						collider.enabled = true;
					}
					bool flag2 = !collider2.enabled;
					if (flag2)
					{
						collider2.enabled = true;
					}
					Vector3 direction;
					float distance;
					bool num5 = Physics.ComputePenetration(collider, colliderInfo.Position, colliderInfo.Rotation, collider2, colliderInfo2.Position, colliderInfo2.Rotation, out direction, out distance);
					if (flag)
					{
						collider.enabled = false;
					}
					if (flag2)
					{
						collider2.enabled = false;
					}
					if (num5 && distance > 0f)
					{
						switch (collisionHandlingMethod)
						{
						case PartCollisionHandlingMethod.AutoDisablePerCollider:
							assembly.AddPartCollision(new PartCollision(partA, collider.name, partB, collider2.name, autoGenerated: true));
							break;
						case PartCollisionHandlingMethod.AutoDisablePerPart:
							assembly.AddPartCollision(new PartCollision(partA, partB));
							return;
						default:
							Debug.LogError($"Unexpected collision handling method: {collisionHandlingMethod}");
							break;
						}
					}
				}
			}
		}
	}
}
