namespace ShellFileDialogs
{
	internal enum SICHINTF
	{
		SICHINT_DISPLAY = 0,
		SICHINT_CANONICAL = 268435456,
		SICHINT_TEST_FILESYSPATH_IF_NOT_EQUAL = 536870912,
		SICHINT_ALLFIELDS = int.MinValue
	}
}
