using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("VoxelBusters.CoreLibrary.NativePlugins")]
[assembly: InternalsVisibleTo("VoxelBusters.CoreLibrary.Editor")]
[assembly: InternalsVisibleTo("VoxelBusters.CoreLibrary.Editor.NativePlugins")]
[assembly: InternalsVisibleTo("VoxelBusters.EssentialKit")]
[assembly: InternalsVisibleTo("VoxelBusters.EssentialKit.Editor")]
[assembly: InternalsVisibleTo("VoxelBusters.ScreenRecorderKit")]
[assembly: InternalsVisibleTo("VoxelBusters.ScreenRecorderKit.Editor")]
[assembly: InternalsVisibleTo("VoxelBusters.ReportingKit")]
[assembly: InternalsVisibleTo("VoxelBusters.ReportingKit.Editor")]
[assembly: InternalsVisibleTo("VoxelBusters.EasyMLKit")]
[assembly: InternalsVisibleTo("VoxelBusters.EasyMLKit.Editor")]
[assembly: InternalsVisibleTo("VoxelBusters.SocialKit")]
[assembly: InternalsVisibleTo("VoxelBusters.SocialKit.Editor")]
[assembly: InternalsVisibleTo("VoxelBusters.AdsKit")]
[assembly: InternalsVisibleTo("VoxelBusters.AdsKit.Editor")]
[assembly: InternalsVisibleTo("VoxelBusters.PermissionsKit")]
[assembly: InternalsVisibleTo("VoxelBusters.PermissionsKit.Editor")]
[assembly: AssemblyVersion("0.0.0.0")]
