namespace Inventory
{
	public enum InventoryAction
	{
		ClaimInventory = 0,
		ConsumeObjectType = 1,
		ConsumeEntityAt = 2,
		CreateObject = 3,
		AddAmount = 4,
		SetAmount = 5,
		DropAllItemsAt = 6,
		DropItem = 7,
		MoveAmount = 8,
		MoveOrDropItem = 9,
		MoveOrDropAllItems = 10,
		MoveOrDropAmount = 11,
		DropAllItems = 12,
		Swap = 13,
		Destroy = 14,
		DestroyItems = 15,
		Sell = 16,
		QuickStack = 17,
		Sort = 18,
		MoveInventory = 19,
		PickUpObject = 20,
		SetVariation = 21,
		SetName = 22,
		SetPetTalentPoints = 23,
		ResetPetTalentTree = 24,
		SetPetSkin = 25,
		SetAuthor = 26,
		Buy = 27,
		ResetSkillTalentTree = 28,
		SalvageAll = 29,
		SellAll = 30,
		MoveOrDropItems = 31,
		MoveAllOrDropThenTryMove = 32,
		TryReplaceBrokenObject = 33,
		ToggleLock = 34,
		QuickStackToNearbyChests = 35,
		MoveOrDropItemIgnoreGuestMode = 36,
		AddFilter = 37,
		SetAllItemsInInventoryToLevel = 38
	}
}
