namespace HeathenEngineering.SteamworksIntegration
{
	public enum SteamEventTriggerType
	{
		AchievementStored = 0,
		ActiveBeaconsUpdated = 1,
		AppResumeFromSuspend = 2,
		AvailableBeaconLocationsUpdated = 3,
		ChatMessageReceived = 4,
		DlcInstalled = 5,
		FriendRichPresenceUpdate = 6,
		GameConnectedChatJoin = 7,
		GameConnectedChatLeave = 8,
		GameConnectedFriendChatMsg = 9,
		GamepadTextInputDismissed = 10,
		GamepadTextShown = 11,
		InitializationError = 12,
		InitializationSuccess = 13,
		InputDataChanged = 14,
		InventoryDefinitionUpdate = 15,
		InventoryResultReady = 16,
		KeyboardClosed = 17,
		KeyboardShown = 18,
		LobbyAskedToLeave = 19,
		LobbyAuthenticationRequest = 20,
		LobbyChatMsg = 21,
		LobbyChatUpdate = 22,
		LobbyDataUpdate = 23,
		LobbyEnterFailed = 24,
		LobbyEnterSuccess = 25,
		LobbyGameCreated = 26,
		LobbyInvite = 27,
		LobbyJoinRequested = 28,
		LobbyLeave = 29,
		MicroTransactionAuthorizationResponse = 30,
		NewUrlLaunchParameters = 31,
		OverlayActivated = 32,
		PersonaStateChange = 33,
		RemotePlaySessionConnected = 34,
		RemotePlaySessionDisconnected = 35,
		RemoteStorageFileChanged = 36,
		ReservationNotificationCallback = 37,
		RichPresenceJoinRequested = 38,
		ScreenshotReady = 39,
		ScreenshotRequested = 40,
		ServerChangeRequested = 41,
		ServersConnectFailure = 42,
		ServersConnected = 43,
		ServersDisconnected = 44,
		ServerFavoritesListChanged = 45,
		StatsReceived = 46,
		StatsStored = 47,
		StatsUnloaded = 48
	}
}
