public enum BehaviorLocationInfo
{
	PREFER_ISOLATED_LOCATION = 0,
	PREFER_BUSY_LOCATION = 1,
	PREFER_EMPTY_LOCATION = 2,
	PREFER_NON_DEN_ISOLATED_LOCATION = 3,
	PREFER_NEST_ISOLATED_LOCATION = 4,
	PREFER_BEDROOM_ISOLATED_LOCATION = 5
}
