public enum Requirement
{
	ALL_LEGS_GROUNDED = 0,
	NO_LEGS_GROUNDED = 1,
	ACTOR_ROTATION_VALID = 2,
	ACTOR_ROTATION_INVALID = 3,
	NEED_REQUIREMENT = 4,
	ANY_LEG_GROUNDED = 5,
	CAN_BARF = 6,
	NO_EDIBLE_OBJECTS_EXIST = 7,
	GAME_MODE_HOME = 8,
	CASUAL_POOP = 9,
	EMERGENCY_POOP = 10,
	HAS_COMPLETED_DEN = 11,
	HAS_WINGS = 12
}
