public enum StartConditionType
{
	REQUIREMENT_CONDITION = 0,
	NEED_CONDITION = 1,
	SOCIAL_PERSONALITY_REQUIREMENT = 2,
	ENERGY_PERSONALITY_REQUIREMENT = 3,
	FOOD_PERSONALITY_REQUIREMENT = 4,
	MISCHIEF_PERSONALITY_REQUIREMENT = 5,
	AGE_CONDITION = 6,
	CAN_BUILD_NEW_DEN_INTERIORS = 7,
	LOUDNESS_PERSONALITY_REQUIREMENT = 8
}
