public enum TutorialState
{
	WELCOME_CONVO = 0,
	NEW_DOG_CONVO = 1,
	DOG_STORAGE_CONVO = 2,
	DOG_STORAGE_OPEN_WAIT = 3,
	DOG_STORAGE_CLOSE_WAIT = 4,
	DOG_HATCH_CONVO = 5,
	DISPENSER_BUILD_PROMPT = 6,
	FEED_DOG_PROMPT = 7,
	MUTATION_CONVO = 8,
	MUTATION_PROMPT = 9,
	MUTATION_WAIT = 10,
	MUTATION_FINISHED_CONVO = 11,
	INCUBATOR_BUILD_PROMPT = 12,
	INCUBATOR_USE_PROMPT = 13,
	FINAL_UNLOCKS = 14
}
