namespace Logic.SteamAchievements
{
	public static class SteamAchievementConstants
	{
		public enum SteamStatNames
		{
			NONE = 0,
			TOTAL_CUBES_PRODUCED = 1,
			TOTAL_RESOURCES_SCRAPPED = 2
		}

		public enum SteamAchievementNames
		{
			NONE = 0,
			LOCAL_FIRST_DATASHARD = 1,
			LOCAL_FIRST_PAINT = 2,
			LOCAL_UNLOCK_ISLAND = 3,
			LOCAL_GREY_MONUMENT = 4,
			LOCAL_BLUE_MONUMENT = 5,
			LOCAL_YELLOW_MONUMENT = 6,
			LOCAL_GNN_GATE = 7,
			LOCAL_40K_BOTS = 8,
			LOCAL_25K_DROIDS = 9,
			LOCAL_25K_MECHS = 10,
			LOCAL_5K_HYPERDROIDS = 11,
			LOCAL_5K_ULTRAMECHS = 12,
			LOCAL_RANK_10 = 13,
			LOCAL_RANK_20 = 14,
			LOCAL_RANK_25 = 15,
			LOCAL_COMPLETED_TECH_TREE = 16,
			LOCAL_MEGA_CUBE = 17,
			LOCAL_BABY_CUBE = 18,
			LOCAL_40_FULL_BUILDINGS = 19,
			LOCAL_MONUMENTS_SAME_ISLAND = 20,
			LOCAL_10_ACTIVE_FREIGHTERS = 21,
			LOCAL_OVERCLOCK_BUILDING = 22,
			LOCAL_BOT_IN_PAINTER = 23,
			LOCAL_RANK_8_WITH_3_ISLANDS = 24,
			LOCAL_BOT_IN_SCRAPPER = 25,
			LOCAL_50_OPERATORS_SAME_ISLAND = 26,
			GLOBAL_1M_CUBES = 27,
			GLOBAL_10M_CUBES = 28,
			GLOBAL_100M_CUBES = 29,
			GLOBAL_SCRAP_RESOURCES = 30,
			LOCAL_ASSEMBLE_BASIC_CUBE = 31,
			LOCAL_10_ISLANDS_OR_LESS = 32,
			LOCAL_CONVEYOR_CIRCLE = 33,
			LOCAL_CHESSBOARD_MODULE = 34,
			LOCAL_25_FULL_BUILDINGS = 35,
			LOCAL_50_FULL_BUILDINGS = 36,
			LOCAL_FIRST_HEXACRYSTAL = 37,
			LOCAL_FIRST_OIL = 38,
			LOCAL_FIRST_COOLANT = 39,
			LOCAL_12_ACTIVE_FREIGHTERS = 40,
			LOCAL_14_ACTIVE_FREIGHTERS = 41,
			LOCAL_16_ACTIVE_FREIGHTERS = 42
		}
	}
}
