using System;
using Rewired.Internal.Glyphs;
using Rewired.Internal.Localization;

internal abstract class dQTdWToRhItjLrwNfUbmULUfayjJ : ghQbrEhajwCFoEejkJrqHEmjrMVBB
{
	protected KeyedGlyph[] MOWgQLNqiCxtwOXpFLqykYOTLjYn;

	public int AeLHnGLtvwULSQCRWVpvFAcSeokF => RyDiYtnCdYRqXXpxvIjJeSOrrroG.LdCDypFhAhzHGQMVrcvuiORltJYJA(base.myIuJxQUSFnyzENhkiZOUczykYAM, base.MiFkShoksmGDvbGtXsXtnvMjwRoKA);

	public abstract object LOdXDFSNhfdfWiycbFWLGaBiZNGX(int P_0);

	public abstract string DDYWjtyRPVEjOiNOrnwoMWUGCbLK(int P_0);

	protected dQTdWToRhItjLrwNfUbmULUfayjJ(RyDiYtnCdYRqXXpxvIjJeSOrrroG.wDdhIfgQYXRpSeEwrBrHOItkwVRlA P_0, RyDiYtnCdYRqXXpxvIjJeSOrrroG.NpYWoxDajscclIyARrpcWpXeFhgi P_1)
		: base(P_0, P_1)
	{
	}

	protected dQTdWToRhItjLrwNfUbmULUfayjJ(euWsBsFZlnKdNdwSzRGQMkIVzLgq P_0, RyDiYtnCdYRqXXpxvIjJeSOrrroG.wDdhIfgQYXRpSeEwrBrHOItkwVRlA P_1, RyDiYtnCdYRqXXpxvIjJeSOrrroG.NpYWoxDajscclIyARrpcWpXeFhgi P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
	}

	protected virtual void yRQDGwlZuEvHaTtaiaoGrmhaxxXi()
	{
		int num = AeLHnGLtvwULSQCRWVpvFAcSeokF;
		MOWgQLNqiCxtwOXpFLqykYOTLjYn = null;
		if (num > 0)
		{
			MOWgQLNqiCxtwOXpFLqykYOTLjYn = new KeyedGlyph[num];
			for (int i = 0; i < num; i++)
			{
				MOWgQLNqiCxtwOXpFLqykYOTLjYn[i] = new KeyedGlyph();
			}
		}
		gpyJaemOGpUvyuNpuWRtyiwOZlhl();
	}

	public virtual void dzddJRplHzZdqcSPcfNEchrfgHgH(euWsBsFZlnKdNdwSzRGQMkIVzLgq P_0)
	{
		OcYtYNxzhxSQwaOaRJuYQmbgOqtf(P_0);
	}

	public virtual void akYifwyeTbQyeonaGfMDjYqHfLEN(VXuSsTlJoBHbugAzwdYIdycaHtQaB P_0)
	{
		base.OcYtYNxzhxSQwaOaRJuYQmbgOqtf(P_0);
		if (!(P_0 is euWsBsFZlnKdNdwSzRGQMkIVzLgq))
		{
			throw new ArgumentException("value must implement " + typeof(euWsBsFZlnKdNdwSzRGQMkIVzLgq));
		}
	}

	public virtual void oVPuqFaHHgdBdrCyXaXvdQfmVsyjA()
	{
		UpnmvVIdufAiaEWGkoIcBeuavBfi();
		if (MOWgQLNqiCxtwOXpFLqykYOTLjYn != null)
		{
			for (int i = 0; i < AeLHnGLtvwULSQCRWVpvFAcSeokF; i++)
			{
				MOWgQLNqiCxtwOXpFLqykYOTLjYn[i].Clear();
			}
		}
	}

	public virtual bool ZfUNJNjQxAikBQhYKdSMJtTxKNGHA(ZaddemmCrcgBNYzwAdPPVXoDjYTk P_0)
	{
		if (!(P_0 is dQTdWToRhItjLrwNfUbmULUfayjJ dQTdWToRhItjLrwNfUbmULUfayjJ2))
		{
			return false;
		}
		if (!WPjLstpPtfwwkSgMymeoSjApsXlF(P_0))
		{
			return false;
		}
		euWsBsFZlnKdNdwSzRGQMkIVzLgq euWsBsFZlnKdNdwSzRGQMkIVzLgq2 = rjjxewwdEZNaOUsHucUPgxFyEQdU();
		euWsBsFZlnKdNdwSzRGQMkIVzLgq euWsBsFZlnKdNdwSzRGQMkIVzLgq3 = dQTdWToRhItjLrwNfUbmULUfayjJ2.rjjxewwdEZNaOUsHucUPgxFyEQdU();
		if (euWsBsFZlnKdNdwSzRGQMkIVzLgq2 == null != (euWsBsFZlnKdNdwSzRGQMkIVzLgq3 == null))
		{
			return false;
		}
		if (euWsBsFZlnKdNdwSzRGQMkIVzLgq2 != null)
		{
			int num = AeLHnGLtvwULSQCRWVpvFAcSeokF;
			for (int i = 0; i < num; i++)
			{
				if (!string.Equals(euWsBsFZlnKdNdwSzRGQMkIVzLgq2.GetSpecialElementKey(i), euWsBsFZlnKdNdwSzRGQMkIVzLgq3.GetSpecialElementKey(i), StringComparison.Ordinal))
				{
					return false;
				}
			}
		}
		return true;
	}

	protected virtual void rNkUfUCLPcilxLabRaVHsBKbfNkP()
	{
		wZzeJZlTSHjEjpxmJqnhbOrsakDIA();
		if (MOWgQLNqiCxtwOXpFLqykYOTLjYn != null)
		{
			for (int i = 0; i < MOWgQLNqiCxtwOXpFLqykYOTLjYn.Length; i++)
			{
				MOWgQLNqiCxtwOXpFLqykYOTLjYn[i].Clear();
			}
		}
	}

	protected virtual void ngpiQyrFPVqwRFjDJHdngjCOUiXe(RyDiYtnCdYRqXXpxvIjJeSOrrroG.aePIIoVXbbnFXSmuBBCQkjRgryklA P_0)
	{
		base.nQmZTlVgBhGOiKmDoxamEVFsUwSDA(P_0);
		euWsBsFZlnKdNdwSzRGQMkIVzLgq euWsBsFZlnKdNdwSzRGQMkIVzLgq2 = rjjxewwdEZNaOUsHucUPgxFyEQdU();
		if (euWsBsFZlnKdNdwSzRGQMkIVzLgq2 == null || base.myIuJxQUSFnyzENhkiZOUczykYAM != RyDiYtnCdYRqXXpxvIjJeSOrrroG.wDdhIfgQYXRpSeEwrBrHOItkwVRlA.CompoundElement || !RyDiYtnCdYRqXXpxvIjJeSOrrroG.xeTKhmONIypEUlLsOBJlnkOmtBsK(base.MiFkShoksmGDvbGtXsXtnvMjwRoKA, out var lAczHHLPNKZSpdQQYyjLdOHCMoNA))
		{
			return;
		}
		for (int i = 0; i < lAczHHLPNKZSpdQQYyjLdOHCMoNA.xtbdPMQWwGZVQBAuqlgMIDVLKKAK; i++)
		{
			int num = 8388608 << i;
			if ((euWsBsFZlnKdNdwSzRGQMkIVzLgq2.autoGeneratedValueFlags & num) == 0 && !string.IsNullOrEmpty(euWsBsFZlnKdNdwSzRGQMkIVzLgq2.key) && string.IsNullOrEmpty(euWsBsFZlnKdNdwSzRGQMkIVzLgq2.GetSpecialElementKey(i)))
			{
				string text = euWsBsFZlnKdNdwSzRGQMkIVzLgq2.key;
				if (lAczHHLPNKZSpdQQYyjLdOHCMoNA.cSngAPaBzrRrYucECUhFZadVCXFiA(i).xouJkbRahCYnGvJzReGTTdDcXqiH.HasValue)
				{
					text = LocalizationManager.AppendToKeyAxisDirection(text, lAczHHLPNKZSpdQQYyjLdOHCMoNA.cSngAPaBzrRrYucECUhFZadVCXFiA(i).xouJkbRahCYnGvJzReGTTdDcXqiH.Value);
				}
				euWsBsFZlnKdNdwSzRGQMkIVzLgq2.SetSpecialElementKey(i, text);
				euWsBsFZlnKdNdwSzRGQMkIVzLgq2.autoGeneratedValueFlags |= num;
				KwGbjejliVubzoOCfsXlDJhXdaGfA(num);
			}
		}
	}

	protected virtual void KAGwNRAMFPdnjMRmAfbLYOIvYqus(RyDiYtnCdYRqXXpxvIjJeSOrrroG.OKDfONxCXupdMmVNgSzknasBOGLo P_0)
	{
		base.lNssnJYyHduvXebhPghHAhQlOPxc(P_0);
		euWsBsFZlnKdNdwSzRGQMkIVzLgq euWsBsFZlnKdNdwSzRGQMkIVzLgq2 = rjjxewwdEZNaOUsHucUPgxFyEQdU();
		if (euWsBsFZlnKdNdwSzRGQMkIVzLgq2 == null || ((uint)euWsBsFZlnKdNdwSzRGQMkIVzLgq2.autoGeneratedValueFlags & (uint)P_0) == 0 || base.myIuJxQUSFnyzENhkiZOUczykYAM != RyDiYtnCdYRqXXpxvIjJeSOrrroG.wDdhIfgQYXRpSeEwrBrHOItkwVRlA.CompoundElement || !RyDiYtnCdYRqXXpxvIjJeSOrrroG.xeTKhmONIypEUlLsOBJlnkOmtBsK(base.MiFkShoksmGDvbGtXsXtnvMjwRoKA, out var lAczHHLPNKZSpdQQYyjLdOHCMoNA))
		{
			return;
		}
		for (int i = 0; i < lAczHHLPNKZSpdQQYyjLdOHCMoNA.xtbdPMQWwGZVQBAuqlgMIDVLKKAK; i++)
		{
			int num = 8388608 << i;
			if ((euWsBsFZlnKdNdwSzRGQMkIVzLgq2.autoGeneratedValueFlags & num) != 0)
			{
				euWsBsFZlnKdNdwSzRGQMkIVzLgq2.SetSpecialElementKey(i, null);
				euWsBsFZlnKdNdwSzRGQMkIVzLgq2.autoGeneratedValueFlags &= ~num;
				KwGbjejliVubzoOCfsXlDJhXdaGfA(num);
			}
		}
	}

	protected virtual RyDiYtnCdYRqXXpxvIjJeSOrrroG.OKDfONxCXupdMmVNgSzknasBOGLo zjoLlsXHDZfbTfCsiShXLpewcelV(RyDiYtnCdYRqXXpxvIjJeSOrrroG.aePIIoVXbbnFXSmuBBCQkjRgryklA P_0)
	{
		RyDiYtnCdYRqXXpxvIjJeSOrrroG.OKDfONxCXupdMmVNgSzknasBOGLo oKDfONxCXupdMmVNgSzknasBOGLo = base.YPXOGPmMxwUewyToThWfQkmMmynj(P_0);
		int num = AeLHnGLtvwULSQCRWVpvFAcSeokF;
		if ((P_0 & RyDiYtnCdYRqXXpxvIjJeSOrrroG.aePIIoVXbbnFXSmuBBCQkjRgryklA.Keys) != RyDiYtnCdYRqXXpxvIjJeSOrrroG.aePIIoVXbbnFXSmuBBCQkjRgryklA.None)
		{
			for (int i = 0; i < num; i++)
			{
				oKDfONxCXupdMmVNgSzknasBOGLo = (RyDiYtnCdYRqXXpxvIjJeSOrrroG.OKDfONxCXupdMmVNgSzknasBOGLo)((int)oKDfONxCXupdMmVNgSzknasBOGLo | (8388608 << i));
			}
		}
		return oKDfONxCXupdMmVNgSzknasBOGLo;
	}

	protected euWsBsFZlnKdNdwSzRGQMkIVzLgq rjjxewwdEZNaOUsHucUPgxFyEQdU()
	{
		return oQVcjeUcPIxziqYkQkfxTLecSBhr() as euWsBsFZlnKdNdwSzRGQMkIVzLgq;
	}

	protected virtual void sADEbNCaRFGELfyjBCOQJZXgxnrib()
	{
		base.bLmUVOwGixSluchaznCmnnJJhTdw();
		int num = AeLHnGLtvwULSQCRWVpvFAcSeokF;
		for (int i = 0; i < num; i++)
		{
			LOdXDFSNhfdfWiycbFWLGaBiZNGX(i);
		}
	}

	protected virtual void tqFESibbXGoknsDFQWuhrBGpXalbA()
	{
		XEoIoeXEPgdchAqbiNlkHaIlKntSA();
	}
}
