using System;
using Rewired;
using Rewired.Internal.Localization;

internal abstract class fgGNpXliahjwEjBzyBUMNwlwECs : RyDiYtnCdYRqXXpxvIjJeSOrrroG
{
	protected readonly LocalizedString KWooWsVshZrTKbZqYjDJZhsKxdn;

	protected readonly LocalizedString esuADSAZujFlJYysUZcpMgIRFpmI;

	public abstract string iLiuzsLDQkvHfcjDCcGykVsvicft { get; }

	public abstract string CzMNKjcKhXiLoSCUyZnmWlpFrLws { get; }

	protected fgGNpXliahjwEjBzyBUMNwlwECs(wDdhIfgQYXRpSeEwrBrHOItkwVRlA P_0, NpYWoxDajscclIyARrpcWpXeFhgi P_1)
		: base(P_0, P_1)
	{
		KWooWsVshZrTKbZqYjDJZhsKxdn = new LocalizedString();
		esuADSAZujFlJYysUZcpMgIRFpmI = new LocalizedString();
	}

	protected fgGNpXliahjwEjBzyBUMNwlwECs(bXtOivlsOYjkGZtzvdtdZjoKDUCF P_0, wDdhIfgQYXRpSeEwrBrHOItkwVRlA P_1, NpYWoxDajscclIyARrpcWpXeFhgi P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
		KWooWsVshZrTKbZqYjDJZhsKxdn = new LocalizedString();
		esuADSAZujFlJYysUZcpMgIRFpmI = new LocalizedString();
	}

	protected virtual void XRVpjFmgMFiZJtPMfGYlAdQZlBpz()
	{
		OrdbNTaQcjaBQxLMdluxgJOFKkbub();
	}

	public virtual void MlKcaGDDSBUBURaTgGZOaHsxlbudb(bXtOivlsOYjkGZtzvdtdZjoKDUCF P_0)
	{
		LGwfJRmzAybEYrAflsatLfLhagnEA(P_0);
	}

	public virtual void CWSuCpjNtZkeBBOVGoxwgAJVeLMiA(leeNpeIpkRWAaDYnewmtyKpQcRpw P_0)
	{
		base.LGwfJRmzAybEYrAflsatLfLhagnEA(P_0);
		if (!(P_0 is bXtOivlsOYjkGZtzvdtdZjoKDUCF))
		{
			throw new ArgumentException("value must implement " + typeof(bXtOivlsOYjkGZtzvdtdZjoKDUCF));
		}
	}

	public virtual void XzXzEmzdBueFSIopXSiezHHYaoEz()
	{
		YazFMUpYRqUkNsDWQojsBWEkIGnc();
		KWooWsVshZrTKbZqYjDJZhsKxdn.Clear();
		esuADSAZujFlJYysUZcpMgIRFpmI.Clear();
	}

	public virtual void aKNuaWqpQpkpIvnjwSmHyTWcDQxG()
	{
		uMjlOiAVfMPZZTxyUgttpxJlFOI();
		KWooWsVshZrTKbZqYjDJZhsKxdn.Clear();
		esuADSAZujFlJYysUZcpMgIRFpmI.Clear();
	}

	public void jaUyiIAerycXXSHTlQEaFjjULGXJ()
	{
		KWooWsVshZrTKbZqYjDJZhsKxdn.Clear();
		lEdwygNfSpgwTzispGoDRYgTIvVM(aePIIoVXbbnFXSmuBBCQkjRgryklA.Keys);
	}

	public void SPMIwJAoNfhUDmjgKNyrIjvxfTHe()
	{
		esuADSAZujFlJYysUZcpMgIRFpmI.Clear();
		lEdwygNfSpgwTzispGoDRYgTIvVM(aePIIoVXbbnFXSmuBBCQkjRgryklA.Keys);
	}

	public void lBnLmeaxZDkhxYoPMPJqXmFtBMet()
	{
		KWooWsVshZrTKbZqYjDJZhsKxdn.Clear();
		lEdwygNfSpgwTzispGoDRYgTIvVM(aePIIoVXbbnFXSmuBBCQkjRgryklA.Names);
	}

	public void QywrBRmSUSMMOTNxYjMpHKVxFPHD()
	{
		esuADSAZujFlJYysUZcpMgIRFpmI.Clear();
		lEdwygNfSpgwTzispGoDRYgTIvVM(aePIIoVXbbnFXSmuBBCQkjRgryklA.Names);
	}

	public virtual bool XYKBNcUPInamUIMarRGPAgrHYHVS(LppKwrUfVUBJkUZWgjBXcdVtfTUS P_0, bool P_1)
	{
		if (!(P_0 is fgGNpXliahjwEjBzyBUMNwlwECs fgGNpXliahjwEjBzyBUMNwlwECs2))
		{
			return false;
		}
		if (!TESrEAMoQgmAGpmixcVZFHEEcPry(P_0, P_1))
		{
			return false;
		}
		bXtOivlsOYjkGZtzvdtdZjoKDUCF bXtOivlsOYjkGZtzvdtdZjoKDUCF2 = kqidKTqAlohjQfVSIZYNslNFsNulA();
		bXtOivlsOYjkGZtzvdtdZjoKDUCF bXtOivlsOYjkGZtzvdtdZjoKDUCF3 = fgGNpXliahjwEjBzyBUMNwlwECs2.kqidKTqAlohjQfVSIZYNslNFsNulA();
		if (bXtOivlsOYjkGZtzvdtdZjoKDUCF2 == null != (bXtOivlsOYjkGZtzvdtdZjoKDUCF3 == null))
		{
			return false;
		}
		if (bXtOivlsOYjkGZtzvdtdZjoKDUCF2 != null && P_1 && (!string.Equals(bXtOivlsOYjkGZtzvdtdZjoKDUCF2.positiveKey, bXtOivlsOYjkGZtzvdtdZjoKDUCF3.positiveKey, StringComparison.Ordinal) || !string.Equals(bXtOivlsOYjkGZtzvdtdZjoKDUCF2.negativeKey, bXtOivlsOYjkGZtzvdtdZjoKDUCF3.negativeKey, StringComparison.Ordinal) || !string.Equals(bXtOivlsOYjkGZtzvdtdZjoKDUCF2.nonLocalizedPositiveDescriptiveName, bXtOivlsOYjkGZtzvdtdZjoKDUCF3.nonLocalizedPositiveDescriptiveName, StringComparison.Ordinal) || !string.Equals(bXtOivlsOYjkGZtzvdtdZjoKDUCF2.nonLocalizedNegativeDescriptiveName, bXtOivlsOYjkGZtzvdtdZjoKDUCF3.nonLocalizedNegativeDescriptiveName, StringComparison.Ordinal)))
		{
			return false;
		}
		return true;
	}

	protected virtual void CoTWZOseIxMwpGThHNfvbduHEYrP()
	{
		eXbqIgJPhccQlGcAzglSFZyAfNobb();
		KWooWsVshZrTKbZqYjDJZhsKxdn.Clear();
		esuADSAZujFlJYysUZcpMgIRFpmI.Clear();
	}

	protected virtual void IbCxrgUnFRiMjzJNeUuQXpjEfzhcA(aePIIoVXbbnFXSmuBBCQkjRgryklA P_0)
	{
		base.lEdwygNfSpgwTzispGoDRYgTIvVM(P_0);
		bXtOivlsOYjkGZtzvdtdZjoKDUCF bXtOivlsOYjkGZtzvdtdZjoKDUCF2 = kqidKTqAlohjQfVSIZYNslNFsNulA();
		if (bXtOivlsOYjkGZtzvdtdZjoKDUCF2 == null)
		{
			return;
		}
		if ((bXtOivlsOYjkGZtzvdtdZjoKDUCF2.autoGeneratedValueFlags & 2) == 0 && string.IsNullOrEmpty(bXtOivlsOYjkGZtzvdtdZjoKDUCF2.nonLocalizedPositiveDescriptiveName) && jmPYgidHLeyeiIFFVcQNcpwKNaBT(Pole.Positive))
		{
			bXtOivlsOYjkGZtzvdtdZjoKDUCF2.nonLocalizedPositiveDescriptiveName = bXtOivlsOYjkGZtzvdtdZjoKDUCF2.nonLocalizedDescriptiveName;
			if (ialEODEuVUCDVlqGlQCFoDvwbnQP(Pole.Positive))
			{
				bXtOivlsOYjkGZtzvdtdZjoKDUCF2.nonLocalizedPositiveDescriptiveName = LocalizationManager.AppendToNameAxisPole(bXtOivlsOYjkGZtzvdtdZjoKDUCF2.nonLocalizedPositiveDescriptiveName, Pole.Positive);
			}
			bXtOivlsOYjkGZtzvdtdZjoKDUCF2.autoGeneratedValueFlags |= 2;
			SxOitnieunZrHDRnvKLWhqjMgpgjA(2);
		}
		if ((bXtOivlsOYjkGZtzvdtdZjoKDUCF2.autoGeneratedValueFlags & 4) == 0 && string.IsNullOrEmpty(bXtOivlsOYjkGZtzvdtdZjoKDUCF2.nonLocalizedNegativeDescriptiveName) && jmPYgidHLeyeiIFFVcQNcpwKNaBT(Pole.Negative))
		{
			bXtOivlsOYjkGZtzvdtdZjoKDUCF2.nonLocalizedNegativeDescriptiveName = bXtOivlsOYjkGZtzvdtdZjoKDUCF2.nonLocalizedDescriptiveName;
			if (ialEODEuVUCDVlqGlQCFoDvwbnQP(Pole.Negative))
			{
				bXtOivlsOYjkGZtzvdtdZjoKDUCF2.nonLocalizedNegativeDescriptiveName = LocalizationManager.AppendToNameAxisPole(bXtOivlsOYjkGZtzvdtdZjoKDUCF2.nonLocalizedNegativeDescriptiveName, Pole.Negative);
			}
			bXtOivlsOYjkGZtzvdtdZjoKDUCF2.autoGeneratedValueFlags |= 4;
			SxOitnieunZrHDRnvKLWhqjMgpgjA(4);
		}
		if (string.IsNullOrEmpty(bXtOivlsOYjkGZtzvdtdZjoKDUCF2.key))
		{
			return;
		}
		if ((bXtOivlsOYjkGZtzvdtdZjoKDUCF2.autoGeneratedValueFlags & 8) == 0 && string.IsNullOrEmpty(bXtOivlsOYjkGZtzvdtdZjoKDUCF2.positiveKey) && jmPYgidHLeyeiIFFVcQNcpwKNaBT(Pole.Positive))
		{
			bXtOivlsOYjkGZtzvdtdZjoKDUCF2.positiveKey = bXtOivlsOYjkGZtzvdtdZjoKDUCF2.key;
			if (ialEODEuVUCDVlqGlQCFoDvwbnQP(Pole.Positive))
			{
				bXtOivlsOYjkGZtzvdtdZjoKDUCF2.positiveKey = LocalizationManager.AppendToKeyAxisPole(bXtOivlsOYjkGZtzvdtdZjoKDUCF2.positiveKey, Pole.Positive);
			}
			bXtOivlsOYjkGZtzvdtdZjoKDUCF2.autoGeneratedValueFlags |= 8;
			SxOitnieunZrHDRnvKLWhqjMgpgjA(8);
		}
		if ((bXtOivlsOYjkGZtzvdtdZjoKDUCF2.autoGeneratedValueFlags & 0x10) == 0 && string.IsNullOrEmpty(bXtOivlsOYjkGZtzvdtdZjoKDUCF2.negativeKey) && jmPYgidHLeyeiIFFVcQNcpwKNaBT(Pole.Negative))
		{
			bXtOivlsOYjkGZtzvdtdZjoKDUCF2.negativeKey = bXtOivlsOYjkGZtzvdtdZjoKDUCF2.key;
			if (ialEODEuVUCDVlqGlQCFoDvwbnQP(Pole.Negative))
			{
				bXtOivlsOYjkGZtzvdtdZjoKDUCF2.negativeKey = LocalizationManager.AppendToKeyAxisPole(bXtOivlsOYjkGZtzvdtdZjoKDUCF2.negativeKey, Pole.Negative);
			}
			bXtOivlsOYjkGZtzvdtdZjoKDUCF2.autoGeneratedValueFlags |= 16;
			SxOitnieunZrHDRnvKLWhqjMgpgjA(16);
		}
	}

	protected virtual void QHvkZewEbgPVjWCrmmUuEIvoCvaP(OKDfONxCXupdMmVNgSzknasBOGLo P_0)
	{
		base.YUwOCHUyJxCFkSJimUFzGTYalFwo(P_0);
		bXtOivlsOYjkGZtzvdtdZjoKDUCF bXtOivlsOYjkGZtzvdtdZjoKDUCF2 = kqidKTqAlohjQfVSIZYNslNFsNulA();
		if (bXtOivlsOYjkGZtzvdtdZjoKDUCF2 != null && ((uint)bXtOivlsOYjkGZtzvdtdZjoKDUCF2.autoGeneratedValueFlags & (uint)P_0) != 0)
		{
			if ((P_0 & OKDfONxCXupdMmVNgSzknasBOGLo.PositiveKey) != OKDfONxCXupdMmVNgSzknasBOGLo.None && (bXtOivlsOYjkGZtzvdtdZjoKDUCF2.autoGeneratedValueFlags & 8) != 0)
			{
				bXtOivlsOYjkGZtzvdtdZjoKDUCF2.positiveKey = null;
				SxOitnieunZrHDRnvKLWhqjMgpgjA(8);
				bXtOivlsOYjkGZtzvdtdZjoKDUCF2.autoGeneratedValueFlags &= -9;
			}
			if ((P_0 & OKDfONxCXupdMmVNgSzknasBOGLo.NegativeKey) != OKDfONxCXupdMmVNgSzknasBOGLo.None && (bXtOivlsOYjkGZtzvdtdZjoKDUCF2.autoGeneratedValueFlags & 0x10) != 0)
			{
				bXtOivlsOYjkGZtzvdtdZjoKDUCF2.negativeKey = null;
				SxOitnieunZrHDRnvKLWhqjMgpgjA(16);
				bXtOivlsOYjkGZtzvdtdZjoKDUCF2.autoGeneratedValueFlags &= -17;
			}
			if ((P_0 & OKDfONxCXupdMmVNgSzknasBOGLo.PositiveDescriptiveName) != OKDfONxCXupdMmVNgSzknasBOGLo.None && (bXtOivlsOYjkGZtzvdtdZjoKDUCF2.autoGeneratedValueFlags & 2) != 0)
			{
				bXtOivlsOYjkGZtzvdtdZjoKDUCF2.nonLocalizedPositiveDescriptiveName = null;
				SxOitnieunZrHDRnvKLWhqjMgpgjA(2);
				bXtOivlsOYjkGZtzvdtdZjoKDUCF2.autoGeneratedValueFlags &= -3;
			}
			if ((P_0 & OKDfONxCXupdMmVNgSzknasBOGLo.NegativeDescriptiveName) != OKDfONxCXupdMmVNgSzknasBOGLo.None && (bXtOivlsOYjkGZtzvdtdZjoKDUCF2.autoGeneratedValueFlags & 4) != 0)
			{
				bXtOivlsOYjkGZtzvdtdZjoKDUCF2.nonLocalizedNegativeDescriptiveName = null;
				SxOitnieunZrHDRnvKLWhqjMgpgjA(4);
				bXtOivlsOYjkGZtzvdtdZjoKDUCF2.autoGeneratedValueFlags &= -5;
			}
		}
	}

	protected virtual OKDfONxCXupdMmVNgSzknasBOGLo CVdqQlvjEWmUGlbLNdFTCLCxWUHQ(aePIIoVXbbnFXSmuBBCQkjRgryklA P_0)
	{
		OKDfONxCXupdMmVNgSzknasBOGLo oKDfONxCXupdMmVNgSzknasBOGLo = base.UoJwXOylmiqEhqxsCJajaPgEbybQ(P_0);
		if ((P_0 & aePIIoVXbbnFXSmuBBCQkjRgryklA.Keys) != aePIIoVXbbnFXSmuBBCQkjRgryklA.None)
		{
			oKDfONxCXupdMmVNgSzknasBOGLo |= (OKDfONxCXupdMmVNgSzknasBOGLo)24;
		}
		if ((P_0 & aePIIoVXbbnFXSmuBBCQkjRgryklA.Names) != aePIIoVXbbnFXSmuBBCQkjRgryklA.None)
		{
			oKDfONxCXupdMmVNgSzknasBOGLo |= (OKDfONxCXupdMmVNgSzknasBOGLo)6;
		}
		return oKDfONxCXupdMmVNgSzknasBOGLo;
	}

	protected bXtOivlsOYjkGZtzvdtdZjoKDUCF kqidKTqAlohjQfVSIZYNslNFsNulA()
	{
		return teLIlNgcmKaxxnoSUdIdFnYabJsF() as bXtOivlsOYjkGZtzvdtdZjoKDUCF;
	}

	protected virtual bool ialEODEuVUCDVlqGlQCFoDvwbnQP(Pole P_0)
	{
		return base.dUUDrzPkiDVoUVOJOYUjkoDyEkRM switch
		{
			wDdhIfgQYXRpSeEwrBrHOItkwVRlA.Axis => true, 
			wDdhIfgQYXRpSeEwrBrHOItkwVRlA.Button => false, 
			_ => false, 
		};
	}

	protected virtual bool jmPYgidHLeyeiIFFVcQNcpwKNaBT(Pole P_0)
	{
		return base.dUUDrzPkiDVoUVOJOYUjkoDyEkRM switch
		{
			wDdhIfgQYXRpSeEwrBrHOItkwVRlA.Axis => true, 
			wDdhIfgQYXRpSeEwrBrHOItkwVRlA.Button => P_0 switch
			{
				Pole.Positive => true, 
				Pole.Negative => false, 
				_ => false, 
			}, 
			_ => false, 
		};
	}

	protected virtual void bgzMKxYrXHTBFEbugaqebydBPTif()
	{
		base.oHuRhhpJfZCiQxskDQUbJrlwERnK();
		_ = iLiuzsLDQkvHfcjDCcGykVsvicft;
		_ = CzMNKjcKhXiLoSCUyZnmWlpFrLws;
	}

	protected virtual void bIRcoqdetXIcOHcqlcBxhsRfRihKA()
	{
		GhaBPZesKjYUwADBlcVAdYlUEshX();
		wqTWbHLiuJlbKmBHEbeWhODjBobC(1, new YZnlcOeKAPoAAuserPoAYphkWGQw
		{
			bcwuDMDWijTVGHxFXvoBqeHTaKiM = 6
		});
		wqTWbHLiuJlbKmBHEbeWhODjBobC(8, new YZnlcOeKAPoAAuserPoAYphkWGQw(KWooWsVshZrTKbZqYjDJZhsKxdn, 2));
		wqTWbHLiuJlbKmBHEbeWhODjBobC(16, new YZnlcOeKAPoAAuserPoAYphkWGQw(esuADSAZujFlJYysUZcpMgIRFpmI, 4));
		wqTWbHLiuJlbKmBHEbeWhODjBobC(2, new YZnlcOeKAPoAAuserPoAYphkWGQw
		{
			AXfBaIhEmyMRigckhEzKRLsOfWfHc = KWooWsVshZrTKbZqYjDJZhsKxdn
		});
		wqTWbHLiuJlbKmBHEbeWhODjBobC(4, new YZnlcOeKAPoAAuserPoAYphkWGQw
		{
			AXfBaIhEmyMRigckhEzKRLsOfWfHc = esuADSAZujFlJYysUZcpMgIRFpmI
		});
	}
}
