using System;
using Rewired.Internal.Localization;

internal abstract class kwMfeaHpvwjvXHYcpqNoPRmCUbBVA : RyDiYtnCdYRqXXpxvIjJeSOrrroG
{
	protected LocalizedString[] xfzEuHpxQViGctJFToaKkioJxrVT;

	public int AVTlIeHPCqGlkkbfwnAnuffVVDKVA => RyDiYtnCdYRqXXpxvIjJeSOrrroG.LdCDypFhAhzHGQMVrcvuiORltJYJA(base.dUUDrzPkiDVoUVOJOYUjkoDyEkRM, base.dHGEbniTxxezwgeoRPphhEiirMrL);

	public abstract string GKfACuKlEeaAGEWnfvjBJwNbGKcuC(int P_0);

	protected kwMfeaHpvwjvXHYcpqNoPRmCUbBVA(wDdhIfgQYXRpSeEwrBrHOItkwVRlA P_0, NpYWoxDajscclIyARrpcWpXeFhgi P_1)
		: base(P_0, P_1)
	{
	}

	protected kwMfeaHpvwjvXHYcpqNoPRmCUbBVA(jmJlodmyeuTJffDdVhrvxnUdztWH P_0, wDdhIfgQYXRpSeEwrBrHOItkwVRlA P_1, NpYWoxDajscclIyARrpcWpXeFhgi P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
	}

	protected virtual void jtfjOOWANiwVbtekpSKNVvPuMLMv()
	{
		int num = AVTlIeHPCqGlkkbfwnAnuffVVDKVA;
		xfzEuHpxQViGctJFToaKkioJxrVT = null;
		if (num > 0)
		{
			xfzEuHpxQViGctJFToaKkioJxrVT = new LocalizedString[num];
			for (int i = 0; i < num; i++)
			{
				xfzEuHpxQViGctJFToaKkioJxrVT[i] = new LocalizedString();
			}
		}
		OrdbNTaQcjaBQxLMdluxgJOFKkbub();
	}

	public virtual void tdikrgroWTixNMySygHCAVVcQKFx(jmJlodmyeuTJffDdVhrvxnUdztWH P_0)
	{
		LGwfJRmzAybEYrAflsatLfLhagnEA(P_0);
	}

	public virtual void glmXvisqFuilkRZcMuBTMvMLMafR(leeNpeIpkRWAaDYnewmtyKpQcRpw P_0)
	{
		base.LGwfJRmzAybEYrAflsatLfLhagnEA(P_0);
		if (!(P_0 is jmJlodmyeuTJffDdVhrvxnUdztWH))
		{
			throw new ArgumentException("value must implement " + typeof(jmJlodmyeuTJffDdVhrvxnUdztWH));
		}
	}

	public virtual void MFJJrsCCfSKffYLqKBZBGhfuxstw()
	{
		YazFMUpYRqUkNsDWQojsBWEkIGnc();
	}

	public virtual void fpVPEbvPhMuewjAOOcwjmxEnUAFO()
	{
		uMjlOiAVfMPZZTxyUgttpxJlFOI();
		if (xfzEuHpxQViGctJFToaKkioJxrVT != null)
		{
			for (int i = 0; i < AVTlIeHPCqGlkkbfwnAnuffVVDKVA; i++)
			{
				xfzEuHpxQViGctJFToaKkioJxrVT[i].Clear();
			}
		}
	}

	public virtual bool jmqdKsAGtLQFTbWZxeRiYkAbHojiA(LppKwrUfVUBJkUZWgjBXcdVtfTUS P_0, bool P_1)
	{
		if (!(P_0 is kwMfeaHpvwjvXHYcpqNoPRmCUbBVA kwMfeaHpvwjvXHYcpqNoPRmCUbBVA2))
		{
			return false;
		}
		if (!TESrEAMoQgmAGpmixcVZFHEEcPry(P_0, P_1))
		{
			return false;
		}
		jmJlodmyeuTJffDdVhrvxnUdztWH jmJlodmyeuTJffDdVhrvxnUdztWH2 = ZJJbuxDSpNtypucoppaXqOYOGGJHA();
		jmJlodmyeuTJffDdVhrvxnUdztWH jmJlodmyeuTJffDdVhrvxnUdztWH3 = kwMfeaHpvwjvXHYcpqNoPRmCUbBVA2.ZJJbuxDSpNtypucoppaXqOYOGGJHA();
		if (jmJlodmyeuTJffDdVhrvxnUdztWH2 == null != (jmJlodmyeuTJffDdVhrvxnUdztWH3 == null))
		{
			return false;
		}
		if (jmJlodmyeuTJffDdVhrvxnUdztWH2 != null && P_1)
		{
			int num = AVTlIeHPCqGlkkbfwnAnuffVVDKVA;
			for (int i = 0; i < num; i++)
			{
				if (!string.Equals(jmJlodmyeuTJffDdVhrvxnUdztWH2.GetSpecialElementKey(i), jmJlodmyeuTJffDdVhrvxnUdztWH3.GetSpecialElementKey(i), StringComparison.Ordinal))
				{
					return false;
				}
				if (!string.Equals(jmJlodmyeuTJffDdVhrvxnUdztWH2.GetSpecialElementNonLocalizedDescriptiveName(i), jmJlodmyeuTJffDdVhrvxnUdztWH3.GetSpecialElementNonLocalizedDescriptiveName(i), StringComparison.Ordinal))
				{
					return false;
				}
			}
		}
		return true;
	}

	protected virtual void ZXwCepjmfRavvnNzziLXzgjSrLmE()
	{
		eXbqIgJPhccQlGcAzglSFZyAfNobb();
		if (xfzEuHpxQViGctJFToaKkioJxrVT != null)
		{
			for (int i = 0; i < xfzEuHpxQViGctJFToaKkioJxrVT.Length; i++)
			{
				xfzEuHpxQViGctJFToaKkioJxrVT[i].Clear();
			}
		}
	}

	protected virtual void InQBbIdtErFohJznkBDjdQuIBGHxB(aePIIoVXbbnFXSmuBBCQkjRgryklA P_0)
	{
		base.lEdwygNfSpgwTzispGoDRYgTIvVM(P_0);
		jmJlodmyeuTJffDdVhrvxnUdztWH jmJlodmyeuTJffDdVhrvxnUdztWH2 = ZJJbuxDSpNtypucoppaXqOYOGGJHA();
		if (jmJlodmyeuTJffDdVhrvxnUdztWH2 == null || string.IsNullOrEmpty(jmJlodmyeuTJffDdVhrvxnUdztWH2.key) || base.dUUDrzPkiDVoUVOJOYUjkoDyEkRM != wDdhIfgQYXRpSeEwrBrHOItkwVRlA.CompoundElement || !RyDiYtnCdYRqXXpxvIjJeSOrrroG.xeTKhmONIypEUlLsOBJlnkOmtBsK(base.dHGEbniTxxezwgeoRPphhEiirMrL, out var lAczHHLPNKZSpdQQYyjLdOHCMoNA))
		{
			return;
		}
		for (int i = 0; i < lAczHHLPNKZSpdQQYyjLdOHCMoNA.xtbdPMQWwGZVQBAuqlgMIDVLKKAK; i++)
		{
			int num = 8388608 << i;
			if ((jmJlodmyeuTJffDdVhrvxnUdztWH2.autoGeneratedValueFlags & num) == 0 && !string.IsNullOrEmpty(jmJlodmyeuTJffDdVhrvxnUdztWH2.key) && string.IsNullOrEmpty(jmJlodmyeuTJffDdVhrvxnUdztWH2.GetSpecialElementKey(i)))
			{
				string text = jmJlodmyeuTJffDdVhrvxnUdztWH2.key;
				if (lAczHHLPNKZSpdQQYyjLdOHCMoNA.cSngAPaBzrRrYucECUhFZadVCXFiA(i).xouJkbRahCYnGvJzReGTTdDcXqiH.HasValue)
				{
					text = LocalizationManager.AppendToKeyAxisDirection(text, lAczHHLPNKZSpdQQYyjLdOHCMoNA.cSngAPaBzrRrYucECUhFZadVCXFiA(i).xouJkbRahCYnGvJzReGTTdDcXqiH.Value);
				}
				jmJlodmyeuTJffDdVhrvxnUdztWH2.SetSpecialElementKey(i, text);
				jmJlodmyeuTJffDdVhrvxnUdztWH2.autoGeneratedValueFlags |= num;
				SxOitnieunZrHDRnvKLWhqjMgpgjA(num);
			}
			int num2 = 16384 << i;
			if ((jmJlodmyeuTJffDdVhrvxnUdztWH2.autoGeneratedValueFlags & num2) == 0 && !string.IsNullOrEmpty(jmJlodmyeuTJffDdVhrvxnUdztWH2.nonLocalizedDescriptiveName) && string.IsNullOrEmpty(jmJlodmyeuTJffDdVhrvxnUdztWH2.GetSpecialElementNonLocalizedDescriptiveName(i)))
			{
				string text2 = jmJlodmyeuTJffDdVhrvxnUdztWH2.nonLocalizedDescriptiveName;
				if (lAczHHLPNKZSpdQQYyjLdOHCMoNA.cSngAPaBzrRrYucECUhFZadVCXFiA(i).xouJkbRahCYnGvJzReGTTdDcXqiH.HasValue)
				{
					text2 = LocalizationManager.AppendToNameAxisDirection(text2, lAczHHLPNKZSpdQQYyjLdOHCMoNA.cSngAPaBzrRrYucECUhFZadVCXFiA(i).xouJkbRahCYnGvJzReGTTdDcXqiH.Value);
				}
				jmJlodmyeuTJffDdVhrvxnUdztWH2.SetSpecialElementNonLocalizedDescriptiveName(i, text2);
				jmJlodmyeuTJffDdVhrvxnUdztWH2.autoGeneratedValueFlags |= num2;
				SxOitnieunZrHDRnvKLWhqjMgpgjA(num2);
			}
		}
	}

	protected virtual void aJVAdTSPDRdJkDirTVQRiePXwDFI(OKDfONxCXupdMmVNgSzknasBOGLo P_0)
	{
		base.YUwOCHUyJxCFkSJimUFzGTYalFwo(P_0);
		jmJlodmyeuTJffDdVhrvxnUdztWH jmJlodmyeuTJffDdVhrvxnUdztWH2 = ZJJbuxDSpNtypucoppaXqOYOGGJHA();
		if (jmJlodmyeuTJffDdVhrvxnUdztWH2 == null || ((uint)jmJlodmyeuTJffDdVhrvxnUdztWH2.autoGeneratedValueFlags & (uint)P_0) == 0 || base.dUUDrzPkiDVoUVOJOYUjkoDyEkRM != wDdhIfgQYXRpSeEwrBrHOItkwVRlA.CompoundElement || !RyDiYtnCdYRqXXpxvIjJeSOrrroG.xeTKhmONIypEUlLsOBJlnkOmtBsK(base.dHGEbniTxxezwgeoRPphhEiirMrL, out var lAczHHLPNKZSpdQQYyjLdOHCMoNA))
		{
			return;
		}
		for (int i = 0; i < lAczHHLPNKZSpdQQYyjLdOHCMoNA.xtbdPMQWwGZVQBAuqlgMIDVLKKAK; i++)
		{
			int num = 8388608 << i;
			if ((jmJlodmyeuTJffDdVhrvxnUdztWH2.autoGeneratedValueFlags & num) != 0)
			{
				jmJlodmyeuTJffDdVhrvxnUdztWH2.SetSpecialElementKey(i, null);
				jmJlodmyeuTJffDdVhrvxnUdztWH2.autoGeneratedValueFlags &= ~num;
				SxOitnieunZrHDRnvKLWhqjMgpgjA(num);
			}
			int num2 = 16384 << i;
			if ((jmJlodmyeuTJffDdVhrvxnUdztWH2.autoGeneratedValueFlags & num2) != 0)
			{
				jmJlodmyeuTJffDdVhrvxnUdztWH2.SetSpecialElementNonLocalizedDescriptiveName(i, null);
				jmJlodmyeuTJffDdVhrvxnUdztWH2.autoGeneratedValueFlags &= ~num2;
				SxOitnieunZrHDRnvKLWhqjMgpgjA(num2);
			}
		}
	}

	protected virtual OKDfONxCXupdMmVNgSzknasBOGLo CoJTaBoAZCRmeAtPkbycPbOFoXNt(aePIIoVXbbnFXSmuBBCQkjRgryklA P_0)
	{
		OKDfONxCXupdMmVNgSzknasBOGLo oKDfONxCXupdMmVNgSzknasBOGLo = base.UoJwXOylmiqEhqxsCJajaPgEbybQ(P_0);
		int num = AVTlIeHPCqGlkkbfwnAnuffVVDKVA;
		if ((P_0 & aePIIoVXbbnFXSmuBBCQkjRgryklA.Keys) != aePIIoVXbbnFXSmuBBCQkjRgryklA.None)
		{
			for (int i = 0; i < num; i++)
			{
				oKDfONxCXupdMmVNgSzknasBOGLo = (OKDfONxCXupdMmVNgSzknasBOGLo)((int)oKDfONxCXupdMmVNgSzknasBOGLo | (8388608 << i));
			}
		}
		if ((P_0 & aePIIoVXbbnFXSmuBBCQkjRgryklA.Names) != aePIIoVXbbnFXSmuBBCQkjRgryklA.None)
		{
			for (int j = 0; j < num; j++)
			{
				oKDfONxCXupdMmVNgSzknasBOGLo = (OKDfONxCXupdMmVNgSzknasBOGLo)((int)oKDfONxCXupdMmVNgSzknasBOGLo | (16384 << j));
			}
		}
		return oKDfONxCXupdMmVNgSzknasBOGLo;
	}

	protected jmJlodmyeuTJffDdVhrvxnUdztWH ZJJbuxDSpNtypucoppaXqOYOGGJHA()
	{
		return teLIlNgcmKaxxnoSUdIdFnYabJsF() as jmJlodmyeuTJffDdVhrvxnUdztWH;
	}

	protected virtual void tSTJheYKUbxCELIadHUddVjieNiy()
	{
		base.oHuRhhpJfZCiQxskDQUbJrlwERnK();
		int num = AVTlIeHPCqGlkkbfwnAnuffVVDKVA;
		for (int i = 0; i < num; i++)
		{
			GKfACuKlEeaAGEWnfvjBJwNbGKcuC(i);
		}
	}

	protected virtual void HsqfAbkwwQZDKvhVLaOpGOMbqaEgA()
	{
		GhaBPZesKjYUwADBlcVAdYlUEshX();
		if (base.dUUDrzPkiDVoUVOJOYUjkoDyEkRM != wDdhIfgQYXRpSeEwrBrHOItkwVRlA.CompoundElement)
		{
			return;
		}
		NpYWoxDajscclIyARrpcWpXeFhgi npYWoxDajscclIyARrpcWpXeFhgi = base.dHGEbniTxxezwgeoRPphhEiirMrL;
		if ((npYWoxDajscclIyARrpcWpXeFhgi == NpYWoxDajscclIyARrpcWpXeFhgi.Axis2D || (uint)(npYWoxDajscclIyARrpcWpXeFhgi - 3) <= 2u) && xfzEuHpxQViGctJFToaKkioJxrVT != null)
		{
			int num = AVTlIeHPCqGlkkbfwnAnuffVVDKVA;
			for (int i = 0; i < num; i++)
			{
				wqTWbHLiuJlbKmBHEbeWhODjBobC(1, new YZnlcOeKAPoAAuserPoAYphkWGQw(xfzEuHpxQViGctJFToaKkioJxrVT[i], 16384 << i));
			}
		}
	}
}
