using System;

internal class mxBaKqGjjllpsxoNhubQolBgrqvI : VXuSsTlJoBHbugAzwdYIdycaHtQaB
{
	protected readonly ghQbrEhajwCFoEejkJrqHEmjrMVBB xyaPQmUAvthgYVVPLSJJOahyihYHA;

	private readonly string ipCklbMtHxOjPbPiZjVOVEYZelcT;

	private readonly string eaabORIhYXIEPwhFGULXfRgACZOEA;

	private int sZWFMKpPyWfhTEQoKOolAYtZeLXfb;

	public ghQbrEhajwCFoEejkJrqHEmjrMVBB ZfYHibIgoTqXDPnzzcdSuRBaKqTOA => xyaPQmUAvthgYVVPLSJJOahyihYHA;

	string VXuSsTlJoBHbugAzwdYIdycaHtQaB.keyCategory => ipCklbMtHxOjPbPiZjVOVEYZelcT;

	string VXuSsTlJoBHbugAzwdYIdycaHtQaB.key => eaabORIhYXIEPwhFGULXfRgACZOEA;

	int VXuSsTlJoBHbugAzwdYIdycaHtQaB.autoGeneratedValueFlags
	{
		get
		{
			return sZWFMKpPyWfhTEQoKOolAYtZeLXfb;
		}
		set
		{
			sZWFMKpPyWfhTEQoKOolAYtZeLXfb = value;
		}
	}

	public string keyCategory => ipCklbMtHxOjPbPiZjVOVEYZelcT;

	public string key => eaabORIhYXIEPwhFGULXfRgACZOEA;

	public mxBaKqGjjllpsxoNhubQolBgrqvI(ghQbrEhajwCFoEejkJrqHEmjrMVBB P_0, string P_1, string P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException();
		}
		xyaPQmUAvthgYVVPLSJJOahyihYHA = P_0;
		ipCklbMtHxOjPbPiZjVOVEYZelcT = P_1;
		eaabORIhYXIEPwhFGULXfRgACZOEA = P_2;
		P_0.OcYtYNxzhxSQwaOaRJuYQmbgOqtf(this);
	}

	public virtual bool INnoOGdheCHKEdZHmMaXRUGhwhgY(mxBaKqGjjllpsxoNhubQolBgrqvI P_0)
	{
		if (P_0 == null)
		{
			return false;
		}
		if ((object)GetType() != P_0.GetType())
		{
			return false;
		}
		if (!xyaPQmUAvthgYVVPLSJJOahyihYHA.oYRjHeCgOqlvQrMwuJiBJiMXaGfn(P_0.xyaPQmUAvthgYVVPLSJJOahyihYHA))
		{
			return false;
		}
		return true;
	}
}
