using System;
using Rewired;
using Rewired.Internal.Glyphs;
using Rewired.Internal.Localization;

internal abstract class zeTnBCXhYntsWWDqRLoWIKxtUEQy : ghQbrEhajwCFoEejkJrqHEmjrMVBB
{
	protected readonly KeyedGlyph kcEobWCVajajkZZAAnOfCoDtwYdR;

	protected readonly KeyedGlyph dKHzDETnSLkiLAdmMZeZMDpRESlKA;

	public abstract object wmuNdKUkrnkWpjuvYITjKzyigQIt { get; }

	public abstract object sWYnzYgdXPvOelpjXPXbjLkADKfr { get; }

	public abstract string QrHHSNOiylXNliXvWTuJqpBeNbxv { get; }

	public abstract string HHBrebMxBkmjqfbRGBIUbVgJzyuA { get; }

	protected zeTnBCXhYntsWWDqRLoWIKxtUEQy(RyDiYtnCdYRqXXpxvIjJeSOrrroG.wDdhIfgQYXRpSeEwrBrHOItkwVRlA P_0, RyDiYtnCdYRqXXpxvIjJeSOrrroG.NpYWoxDajscclIyARrpcWpXeFhgi P_1)
		: base(P_0, P_1)
	{
		kcEobWCVajajkZZAAnOfCoDtwYdR = new KeyedGlyph();
		dKHzDETnSLkiLAdmMZeZMDpRESlKA = new KeyedGlyph();
	}

	protected zeTnBCXhYntsWWDqRLoWIKxtUEQy(hWHawgOADYRYslwTpcXmtDidkGPQ P_0, RyDiYtnCdYRqXXpxvIjJeSOrrroG.wDdhIfgQYXRpSeEwrBrHOItkwVRlA P_1, RyDiYtnCdYRqXXpxvIjJeSOrrroG.NpYWoxDajscclIyARrpcWpXeFhgi P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
		kcEobWCVajajkZZAAnOfCoDtwYdR = new KeyedGlyph();
		dKHzDETnSLkiLAdmMZeZMDpRESlKA = new KeyedGlyph();
	}

	protected virtual void eblxzZOGWXdhNoGawSiGvfZWnYjM()
	{
		gpyJaemOGpUvyuNpuWRtyiwOZlhl();
	}

	public virtual void cdLiOKnrNmRdYROoZoweLccsAxle(hWHawgOADYRYslwTpcXmtDidkGPQ P_0)
	{
		OcYtYNxzhxSQwaOaRJuYQmbgOqtf(P_0);
	}

	public virtual void eYWpgHdXBSDFcFsGNqpBthlGASnt(VXuSsTlJoBHbugAzwdYIdycaHtQaB P_0)
	{
		base.OcYtYNxzhxSQwaOaRJuYQmbgOqtf(P_0);
		if (!(P_0 is hWHawgOADYRYslwTpcXmtDidkGPQ))
		{
			throw new ArgumentException("value must implement " + typeof(hWHawgOADYRYslwTpcXmtDidkGPQ));
		}
	}

	public virtual void sAmBfuYZJKimqktvVDTYEnYztHEj()
	{
		UpnmvVIdufAiaEWGkoIcBeuavBfi();
		kcEobWCVajajkZZAAnOfCoDtwYdR.Clear();
		dKHzDETnSLkiLAdmMZeZMDpRESlKA.Clear();
	}

	public void chjCKdQtmaHCUatQbrrcghoZsTHHA()
	{
		kcEobWCVajajkZZAAnOfCoDtwYdR.Clear();
		nQmZTlVgBhGOiKmDoxamEVFsUwSDA(RyDiYtnCdYRqXXpxvIjJeSOrrroG.aePIIoVXbbnFXSmuBBCQkjRgryklA.Keys);
	}

	public void vBmKlzlcKUBbcKyxacxQbHFSOyot()
	{
		dKHzDETnSLkiLAdmMZeZMDpRESlKA.Clear();
		nQmZTlVgBhGOiKmDoxamEVFsUwSDA(RyDiYtnCdYRqXXpxvIjJeSOrrroG.aePIIoVXbbnFXSmuBBCQkjRgryklA.Keys);
	}

	public virtual bool IUEabOwhwSmTGhYrBRDxvqCaTgfk(ZaddemmCrcgBNYzwAdPPVXoDjYTk P_0)
	{
		if (!(P_0 is zeTnBCXhYntsWWDqRLoWIKxtUEQy zeTnBCXhYntsWWDqRLoWIKxtUEQy2))
		{
			return false;
		}
		if (!WPjLstpPtfwwkSgMymeoSjApsXlF(P_0))
		{
			return false;
		}
		hWHawgOADYRYslwTpcXmtDidkGPQ hWHawgOADYRYslwTpcXmtDidkGPQ2 = UqSRZlsncLOMTfWEtAUpKpHBSmyQ();
		hWHawgOADYRYslwTpcXmtDidkGPQ hWHawgOADYRYslwTpcXmtDidkGPQ3 = zeTnBCXhYntsWWDqRLoWIKxtUEQy2.UqSRZlsncLOMTfWEtAUpKpHBSmyQ();
		if (hWHawgOADYRYslwTpcXmtDidkGPQ2 == null != (hWHawgOADYRYslwTpcXmtDidkGPQ3 == null))
		{
			return false;
		}
		if (hWHawgOADYRYslwTpcXmtDidkGPQ2 != null && (!string.Equals(hWHawgOADYRYslwTpcXmtDidkGPQ2.positiveKey, hWHawgOADYRYslwTpcXmtDidkGPQ3.positiveKey, StringComparison.Ordinal) || !string.Equals(hWHawgOADYRYslwTpcXmtDidkGPQ2.negativeKey, hWHawgOADYRYslwTpcXmtDidkGPQ3.negativeKey, StringComparison.Ordinal)))
		{
			return false;
		}
		return true;
	}

	protected virtual void NLmViCMHHgUzBJHzHlsojIVaomkL()
	{
		wZzeJZlTSHjEjpxmJqnhbOrsakDIA();
		kcEobWCVajajkZZAAnOfCoDtwYdR.Clear();
		dKHzDETnSLkiLAdmMZeZMDpRESlKA.Clear();
	}

	protected virtual void tqrIffGPXkCXQRAWgTJbWRbcsjwC(RyDiYtnCdYRqXXpxvIjJeSOrrroG.aePIIoVXbbnFXSmuBBCQkjRgryklA P_0)
	{
		base.nQmZTlVgBhGOiKmDoxamEVFsUwSDA(P_0);
		hWHawgOADYRYslwTpcXmtDidkGPQ hWHawgOADYRYslwTpcXmtDidkGPQ2 = UqSRZlsncLOMTfWEtAUpKpHBSmyQ();
		if (hWHawgOADYRYslwTpcXmtDidkGPQ2 == null || string.IsNullOrEmpty(hWHawgOADYRYslwTpcXmtDidkGPQ2.key))
		{
			return;
		}
		if ((hWHawgOADYRYslwTpcXmtDidkGPQ2.autoGeneratedValueFlags & 8) == 0 && string.IsNullOrEmpty(hWHawgOADYRYslwTpcXmtDidkGPQ2.positiveKey) && vOHlUAuCVGwcqrbTPmtxYIoiYIOF(Pole.Positive))
		{
			hWHawgOADYRYslwTpcXmtDidkGPQ2.positiveKey = hWHawgOADYRYslwTpcXmtDidkGPQ2.key;
			if (BymfyhYmidJlRRMoulVltTzCBgQp(Pole.Positive))
			{
				hWHawgOADYRYslwTpcXmtDidkGPQ2.positiveKey = LocalizationManager.AppendToKeyAxisPole(hWHawgOADYRYslwTpcXmtDidkGPQ2.positiveKey, Pole.Positive);
			}
			hWHawgOADYRYslwTpcXmtDidkGPQ2.autoGeneratedValueFlags |= 8;
			KwGbjejliVubzoOCfsXlDJhXdaGfA(8);
		}
		if ((hWHawgOADYRYslwTpcXmtDidkGPQ2.autoGeneratedValueFlags & 0x10) == 0 && string.IsNullOrEmpty(hWHawgOADYRYslwTpcXmtDidkGPQ2.negativeKey) && vOHlUAuCVGwcqrbTPmtxYIoiYIOF(Pole.Negative))
		{
			hWHawgOADYRYslwTpcXmtDidkGPQ2.negativeKey = hWHawgOADYRYslwTpcXmtDidkGPQ2.key;
			if (BymfyhYmidJlRRMoulVltTzCBgQp(Pole.Negative))
			{
				hWHawgOADYRYslwTpcXmtDidkGPQ2.negativeKey = LocalizationManager.AppendToKeyAxisPole(hWHawgOADYRYslwTpcXmtDidkGPQ2.negativeKey, Pole.Negative);
			}
			hWHawgOADYRYslwTpcXmtDidkGPQ2.autoGeneratedValueFlags |= 16;
			KwGbjejliVubzoOCfsXlDJhXdaGfA(16);
		}
	}

	protected virtual void BIhxDlzWtKGpaZahEGPpZCEeIcTM(RyDiYtnCdYRqXXpxvIjJeSOrrroG.OKDfONxCXupdMmVNgSzknasBOGLo P_0)
	{
		base.lNssnJYyHduvXebhPghHAhQlOPxc(P_0);
		hWHawgOADYRYslwTpcXmtDidkGPQ hWHawgOADYRYslwTpcXmtDidkGPQ2 = UqSRZlsncLOMTfWEtAUpKpHBSmyQ();
		if (hWHawgOADYRYslwTpcXmtDidkGPQ2 != null && ((uint)hWHawgOADYRYslwTpcXmtDidkGPQ2.autoGeneratedValueFlags & (uint)P_0) != 0)
		{
			if ((P_0 & RyDiYtnCdYRqXXpxvIjJeSOrrroG.OKDfONxCXupdMmVNgSzknasBOGLo.PositiveKey) != RyDiYtnCdYRqXXpxvIjJeSOrrroG.OKDfONxCXupdMmVNgSzknasBOGLo.None && (hWHawgOADYRYslwTpcXmtDidkGPQ2.autoGeneratedValueFlags & 8) != 0)
			{
				hWHawgOADYRYslwTpcXmtDidkGPQ2.positiveKey = null;
				KwGbjejliVubzoOCfsXlDJhXdaGfA(8);
				hWHawgOADYRYslwTpcXmtDidkGPQ2.autoGeneratedValueFlags &= -9;
			}
			if ((P_0 & RyDiYtnCdYRqXXpxvIjJeSOrrroG.OKDfONxCXupdMmVNgSzknasBOGLo.NegativeKey) != RyDiYtnCdYRqXXpxvIjJeSOrrroG.OKDfONxCXupdMmVNgSzknasBOGLo.None && (hWHawgOADYRYslwTpcXmtDidkGPQ2.autoGeneratedValueFlags & 0x10) != 0)
			{
				hWHawgOADYRYslwTpcXmtDidkGPQ2.negativeKey = null;
				KwGbjejliVubzoOCfsXlDJhXdaGfA(16);
				hWHawgOADYRYslwTpcXmtDidkGPQ2.autoGeneratedValueFlags &= -17;
			}
		}
	}

	protected virtual RyDiYtnCdYRqXXpxvIjJeSOrrroG.OKDfONxCXupdMmVNgSzknasBOGLo uzQeQyFxsSiHpfBxxyaHOYoLBDyXA(RyDiYtnCdYRqXXpxvIjJeSOrrroG.aePIIoVXbbnFXSmuBBCQkjRgryklA P_0)
	{
		RyDiYtnCdYRqXXpxvIjJeSOrrroG.OKDfONxCXupdMmVNgSzknasBOGLo oKDfONxCXupdMmVNgSzknasBOGLo = base.YPXOGPmMxwUewyToThWfQkmMmynj(P_0);
		if ((P_0 & RyDiYtnCdYRqXXpxvIjJeSOrrroG.aePIIoVXbbnFXSmuBBCQkjRgryklA.Keys) != RyDiYtnCdYRqXXpxvIjJeSOrrroG.aePIIoVXbbnFXSmuBBCQkjRgryklA.None)
		{
			oKDfONxCXupdMmVNgSzknasBOGLo |= (RyDiYtnCdYRqXXpxvIjJeSOrrroG.OKDfONxCXupdMmVNgSzknasBOGLo)24;
		}
		return oKDfONxCXupdMmVNgSzknasBOGLo;
	}

	protected hWHawgOADYRYslwTpcXmtDidkGPQ UqSRZlsncLOMTfWEtAUpKpHBSmyQ()
	{
		return oQVcjeUcPIxziqYkQkfxTLecSBhr() as hWHawgOADYRYslwTpcXmtDidkGPQ;
	}

	protected virtual bool BymfyhYmidJlRRMoulVltTzCBgQp(Pole P_0)
	{
		return base.myIuJxQUSFnyzENhkiZOUczykYAM switch
		{
			RyDiYtnCdYRqXXpxvIjJeSOrrroG.wDdhIfgQYXRpSeEwrBrHOItkwVRlA.Axis => true, 
			RyDiYtnCdYRqXXpxvIjJeSOrrroG.wDdhIfgQYXRpSeEwrBrHOItkwVRlA.Button => false, 
			_ => false, 
		};
	}

	protected virtual bool vOHlUAuCVGwcqrbTPmtxYIoiYIOF(Pole P_0)
	{
		return base.myIuJxQUSFnyzENhkiZOUczykYAM switch
		{
			RyDiYtnCdYRqXXpxvIjJeSOrrroG.wDdhIfgQYXRpSeEwrBrHOItkwVRlA.Axis => true, 
			RyDiYtnCdYRqXXpxvIjJeSOrrroG.wDdhIfgQYXRpSeEwrBrHOItkwVRlA.Button => P_0 switch
			{
				Pole.Positive => true, 
				Pole.Negative => false, 
				_ => false, 
			}, 
			_ => false, 
		};
	}

	protected virtual void TVILGbOwsSLMAoYgUAzupxxICHty()
	{
		base.bLmUVOwGixSluchaznCmnnJJhTdw();
		_ = wmuNdKUkrnkWpjuvYITjKzyigQIt;
		_ = sWYnzYgdXPvOelpjXPXbjLkADKfr;
	}

	protected virtual void qdHnkQVSZvMuBRNJMheUdATMxSWiA()
	{
		XEoIoeXEPgdchAqbiNlkHaIlKntSA();
		hZivPvpkINCzgJiHXGTipewcxIBD(8, new ZrZHrHYDCTemgupLAGeHjdvzlMKK
		{
			fRqNjGIOcGWgldQadvwzBIACgCWw = kcEobWCVajajkZZAAnOfCoDtwYdR
		});
		hZivPvpkINCzgJiHXGTipewcxIBD(16, new ZrZHrHYDCTemgupLAGeHjdvzlMKK
		{
			fRqNjGIOcGWgldQadvwzBIACgCWw = dKHzDETnSLkiLAdmMZeZMDpRESlKA
		});
	}
}
