using System;
using Rewired.Internal.Localization;

internal class ZtWDGFywnarTKNuYsScniCpUdPO : leeNpeIpkRWAaDYnewmtyKpQcRpw
{
	protected readonly RyDiYtnCdYRqXXpxvIjJeSOrrroG rxZioCYbcoKXNfaHzyyPxWOWCQEA;

	private readonly string GPJrkCoBFqhHxrAFwTmtRTLPAHPn;

	private readonly string DihcAsCHjzbFeHtEcjFzinTawkeGe;

	private string TZCAwsflrSdWbaAUdprNaHNWtDQe;

	private readonly string CyIjnfKnBsgVPBNSTHkspJdlmnQb;

	private int RKIQsDVlCWciswAavIyQTouyTSxk;

	public RyDiYtnCdYRqXXpxvIjJeSOrrroG OwidrtApKhdsnydceogfdMzkEpHdA => rxZioCYbcoKXNfaHzyyPxWOWCQEA;

	string leeNpeIpkRWAaDYnewmtyKpQcRpw.keyCategory => GPJrkCoBFqhHxrAFwTmtRTLPAHPn;

	string leeNpeIpkRWAaDYnewmtyKpQcRpw.scriptingName => DihcAsCHjzbFeHtEcjFzinTawkeGe;

	string leeNpeIpkRWAaDYnewmtyKpQcRpw.nonLocalizedDescriptiveName
	{
		get
		{
			return TZCAwsflrSdWbaAUdprNaHNWtDQe;
		}
		set
		{
			TZCAwsflrSdWbaAUdprNaHNWtDQe = value;
		}
	}

	string leeNpeIpkRWAaDYnewmtyKpQcRpw.key => CyIjnfKnBsgVPBNSTHkspJdlmnQb;

	int leeNpeIpkRWAaDYnewmtyKpQcRpw.autoGeneratedValueFlags
	{
		get
		{
			return RKIQsDVlCWciswAavIyQTouyTSxk;
		}
		set
		{
			RKIQsDVlCWciswAavIyQTouyTSxk = value;
		}
	}

	public string keyCategory => GPJrkCoBFqhHxrAFwTmtRTLPAHPn;

	public string scriptingName => DihcAsCHjzbFeHtEcjFzinTawkeGe;

	public string lhqYvBnTykeMuKCzFAtyigejBsLQ
	{
		get
		{
			if (!LocalizationManager.isEnabled)
			{
				return TZCAwsflrSdWbaAUdprNaHNWtDQe;
			}
			return rxZioCYbcoKXNfaHzyyPxWOWCQEA.YYpaixksduwqUQfFFmPUzWfHjhDu;
		}
	}

	public string nonLocalizedDescriptiveName => TZCAwsflrSdWbaAUdprNaHNWtDQe;

	public string key => CyIjnfKnBsgVPBNSTHkspJdlmnQb;

	public ZtWDGFywnarTKNuYsScniCpUdPO(RyDiYtnCdYRqXXpxvIjJeSOrrroG P_0, string P_1, string P_2, string P_3, string P_4)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException();
		}
		rxZioCYbcoKXNfaHzyyPxWOWCQEA = P_0;
		GPJrkCoBFqhHxrAFwTmtRTLPAHPn = P_1;
		DihcAsCHjzbFeHtEcjFzinTawkeGe = P_2;
		TZCAwsflrSdWbaAUdprNaHNWtDQe = P_3;
		CyIjnfKnBsgVPBNSTHkspJdlmnQb = P_4;
		P_0.LGwfJRmzAybEYrAflsatLfLhagnEA(this);
	}

	public virtual bool FsaHjueLSoGTYHNWMdIbeIIhKnaQB(ZtWDGFywnarTKNuYsScniCpUdPO P_0, bool P_1)
	{
		if (P_0 == null)
		{
			return false;
		}
		if ((object)GetType() != P_0.GetType())
		{
			return false;
		}
		if (!rxZioCYbcoKXNfaHzyyPxWOWCQEA.TUhOKAWZDSFHneJYgWLgWaTMqqZh(P_0.rxZioCYbcoKXNfaHzyyPxWOWCQEA, P_1))
		{
			return false;
		}
		return true;
	}
}
