using System;

internal struct UVUcwbjoCUbEuhneeFIgITKaUkT
{
	public IntPtr JAPGXbnGLEVcKvOepfYKLDmQrgU;

	public iWSlJLlKYTxRRikCAehlAljheYn YfsgTpmJDKgINSOXgeMjKwsiasQ;

	public xXrqVEWVxQxYUTugvDwBKTtQlOt HqgdQAHbpBBYdNYFNZuzGUTvDVRa;

	public uint wdgcVUgqrTFznrCdCabJGVdgwTnr;

	public uint StZBYGkviapTxbBkcxUZtsvTSde;

	public int vKIKLkGYWXZYuucUWNriFjigkIQ;

	public int xIuDTKizXrGdQWHryFwOfDhIWfYh;

	public int BnoOLWClHLapgAPysAHqWqcOkax;

	internal UVUcwbjoCUbEuhneeFIgITKaUkT(ref fIfDvwvvsOcXtZCxSBYBVEQFUcW rawInput)
	{
		JAPGXbnGLEVcKvOepfYKLDmQrgU = rawInput.wtYGxjhSdvLEZrXjirTZkeCIDfO.JAPGXbnGLEVcKvOepfYKLDmQrgU;
		YfsgTpmJDKgINSOXgeMjKwsiasQ = (iWSlJLlKYTxRRikCAehlAljheYn)rawInput.qCmvlLxcVUaxPDpvXtvsPlXAJOVt.UQBduDQfcpFVodDJGKokyQOHOEHN.pShanBKDpoPUyQsbLLJHCsXlpFm;
		HqgdQAHbpBBYdNYFNZuzGUTvDVRa = (xXrqVEWVxQxYUTugvDwBKTtQlOt)rawInput.qCmvlLxcVUaxPDpvXtvsPlXAJOVt.UQBduDQfcpFVodDJGKokyQOHOEHN.SjJetoKpXBSVtfvDtIIUqozUgkf.HqgdQAHbpBBYdNYFNZuzGUTvDVRa;
		vKIKLkGYWXZYuucUWNriFjigkIQ = rawInput.qCmvlLxcVUaxPDpvXtvsPlXAJOVt.UQBduDQfcpFVodDJGKokyQOHOEHN.SjJetoKpXBSVtfvDtIIUqozUgkf.nqvDiAAfJwMWUAUklPPluEcyHOE;
		StZBYGkviapTxbBkcxUZtsvTSde = rawInput.qCmvlLxcVUaxPDpvXtvsPlXAJOVt.UQBduDQfcpFVodDJGKokyQOHOEHN.ahnDkFoXTnnDFiWVdqffIltikZU;
		xIuDTKizXrGdQWHryFwOfDhIWfYh = rawInput.qCmvlLxcVUaxPDpvXtvsPlXAJOVt.UQBduDQfcpFVodDJGKokyQOHOEHN.MvOivICmXRTTKqDFGIkWULNnDnfD;
		BnoOLWClHLapgAPysAHqWqcOkax = rawInput.qCmvlLxcVUaxPDpvXtvsPlXAJOVt.UQBduDQfcpFVodDJGKokyQOHOEHN.xJCnueEjGjGnfHaZKEmUDXLIpdM;
		wdgcVUgqrTFznrCdCabJGVdgwTnr = rawInput.qCmvlLxcVUaxPDpvXtvsPlXAJOVt.UQBduDQfcpFVodDJGKokyQOHOEHN.wdgcVUgqrTFznrCdCabJGVdgwTnr;
	}
}
