using System;
using Rewired.Internal.Localization;

internal abstract class bonesbqwpqPFiqmPEuEwcpLrXygD : MJyJuisFiOmfspJhIRvXPkFSAPFT
{
	protected LocalizedString[] qyCoxKkSFLoaZNWNoJbQHtvcPCik;

	public int HNmdAzQUBawVJDZrZRnhIjeuYffP => MJyJuisFiOmfspJhIRvXPkFSAPFT.WFlgMaYJJpzOhusNWIdstVGKtOzl(base.wmxpDuCFjDeAdhOVfyzrBCCDpMkT, base.kwfjWgpYavMRDMfyekVhYczFHBCY);

	public abstract string XtKWPvibVeeipuzfMWsFFvSriMHH(int P_0);

	protected bonesbqwpqPFiqmPEuEwcpLrXygD(jZSMnsLXoBDMhquJQKqHviQNprmC P_0, GtxbKiHSwksUKuQYeAEqHnCDMtFmA P_1)
		: base(P_0, P_1)
	{
	}

	protected bonesbqwpqPFiqmPEuEwcpLrXygD(orgqfgrCrmobGJnxqbGdAMXEeZnY P_0, jZSMnsLXoBDMhquJQKqHviQNprmC P_1, GtxbKiHSwksUKuQYeAEqHnCDMtFmA P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
	}

	protected virtual void woGWAXHkWejSSXPcGjeLefIZAjnN()
	{
		int num = HNmdAzQUBawVJDZrZRnhIjeuYffP;
		qyCoxKkSFLoaZNWNoJbQHtvcPCik = null;
		if (num > 0)
		{
			qyCoxKkSFLoaZNWNoJbQHtvcPCik = new LocalizedString[num];
			for (int i = 0; i < num; i++)
			{
				qyCoxKkSFLoaZNWNoJbQHtvcPCik[i] = new LocalizedString();
			}
		}
		VnWBKSRlXtnXrnYpEZchoRflOLED();
	}

	public virtual void meXdLtctPFBagaYYHeeYlfEFhieP(orgqfgrCrmobGJnxqbGdAMXEeZnY P_0)
	{
		GcNXeKljLqBwpXBtANTbgsUENESW(P_0);
	}

	public virtual void xJjtvZhEcrPDRnalDeFWzDyyWST(sZLAxvZSvDRmVjMjTVRhHfujppQp P_0)
	{
		base.GcNXeKljLqBwpXBtANTbgsUENESW(P_0);
		if (!(P_0 is orgqfgrCrmobGJnxqbGdAMXEeZnY))
		{
			throw new ArgumentException("value must implement " + typeof(orgqfgrCrmobGJnxqbGdAMXEeZnY));
		}
	}

	public virtual void ZeoRJpHhmSrTWgMcdCcLdfgDIMKNA()
	{
		JCAXBBaNFkTsJKtXzRPvwKXTRcrq();
	}

	public virtual void mRgIJwwPkKdSBPVYbYPnJoHMRcoV()
	{
		lEtBlPkzIphsonzxFzbxmYcymXxrA();
		if (qyCoxKkSFLoaZNWNoJbQHtvcPCik != null)
		{
			for (int i = 0; i < HNmdAzQUBawVJDZrZRnhIjeuYffP; i++)
			{
				qyCoxKkSFLoaZNWNoJbQHtvcPCik[i].Clear();
			}
		}
	}

	public virtual bool qWPlShHBkJHvmbBDQEekTzLCcOMBb(ORSKUsFUQMFbVqzYDhEFDxAETxpN P_0, bool P_1)
	{
		if (!(P_0 is bonesbqwpqPFiqmPEuEwcpLrXygD bonesbqwpqPFiqmPEuEwcpLrXygD2))
		{
			return false;
		}
		if (!IDvCTHHzFaiwfZeoUqzJwjFbvlWj(P_0, P_1))
		{
			return false;
		}
		orgqfgrCrmobGJnxqbGdAMXEeZnY orgqfgrCrmobGJnxqbGdAMXEeZnY2 = MuqMqyULaTsKYQCcYNTXVFJtWgoN();
		orgqfgrCrmobGJnxqbGdAMXEeZnY orgqfgrCrmobGJnxqbGdAMXEeZnY3 = bonesbqwpqPFiqmPEuEwcpLrXygD2.MuqMqyULaTsKYQCcYNTXVFJtWgoN();
		if (orgqfgrCrmobGJnxqbGdAMXEeZnY2 == null != (orgqfgrCrmobGJnxqbGdAMXEeZnY3 == null))
		{
			return false;
		}
		if (orgqfgrCrmobGJnxqbGdAMXEeZnY2 != null && P_1)
		{
			int num = HNmdAzQUBawVJDZrZRnhIjeuYffP;
			for (int i = 0; i < num; i++)
			{
				if (!string.Equals(orgqfgrCrmobGJnxqbGdAMXEeZnY2.GetSpecialElementKey(i), orgqfgrCrmobGJnxqbGdAMXEeZnY3.GetSpecialElementKey(i), StringComparison.Ordinal))
				{
					return false;
				}
				if (!string.Equals(orgqfgrCrmobGJnxqbGdAMXEeZnY2.GetSpecialElementNonLocalizedDescriptiveName(i), orgqfgrCrmobGJnxqbGdAMXEeZnY3.GetSpecialElementNonLocalizedDescriptiveName(i), StringComparison.Ordinal))
				{
					return false;
				}
			}
		}
		return true;
	}

	protected virtual void QfFtCkkQlPTCYVdHIWDNOmnjbVNy()
	{
		vlOKPjAaaycgGQlEQhKKEoxzutTJA();
		if (qyCoxKkSFLoaZNWNoJbQHtvcPCik != null)
		{
			for (int i = 0; i < qyCoxKkSFLoaZNWNoJbQHtvcPCik.Length; i++)
			{
				qyCoxKkSFLoaZNWNoJbQHtvcPCik[i].Clear();
			}
		}
	}

	protected virtual void ZVzrHXieDvQgITblFgajvcjumqau(rCaSuhSWufhFquqeuhJWSlKJKnNk P_0)
	{
		base.sxIwjwSDkhWegJoWETHTsxpgJcOb(P_0);
		orgqfgrCrmobGJnxqbGdAMXEeZnY orgqfgrCrmobGJnxqbGdAMXEeZnY2 = MuqMqyULaTsKYQCcYNTXVFJtWgoN();
		if (orgqfgrCrmobGJnxqbGdAMXEeZnY2 == null || string.IsNullOrEmpty(orgqfgrCrmobGJnxqbGdAMXEeZnY2.key) || base.wmxpDuCFjDeAdhOVfyzrBCCDpMkT != jZSMnsLXoBDMhquJQKqHviQNprmC.CompoundElement || !MJyJuisFiOmfspJhIRvXPkFSAPFT.yzssAvNAWgRZfJKNdgmvMuNHsBFU(base.kwfjWgpYavMRDMfyekVhYczFHBCY, out var eSrXtKMIUZjpxRfWzNHzGoDkUsXw))
		{
			return;
		}
		for (int i = 0; i < eSrXtKMIUZjpxRfWzNHzGoDkUsXw.gOGhhRRzbMztvfVGNQkYpoWayxzi; i++)
		{
			int num = 8388608 << i;
			if ((orgqfgrCrmobGJnxqbGdAMXEeZnY2.autoGeneratedValueFlags & num) == 0 && !string.IsNullOrEmpty(orgqfgrCrmobGJnxqbGdAMXEeZnY2.key) && string.IsNullOrEmpty(orgqfgrCrmobGJnxqbGdAMXEeZnY2.GetSpecialElementKey(i)))
			{
				string text = orgqfgrCrmobGJnxqbGdAMXEeZnY2.key;
				if (eSrXtKMIUZjpxRfWzNHzGoDkUsXw.nKOMQWpKurFAtKeCjgKJcJeqAbqFA(i).oPBcZcQLcCCmxHLvqEJHDmGGNjVsB.HasValue)
				{
					text = LocalizationManager.AppendToKeyAxisDirection(text, eSrXtKMIUZjpxRfWzNHzGoDkUsXw.nKOMQWpKurFAtKeCjgKJcJeqAbqFA(i).oPBcZcQLcCCmxHLvqEJHDmGGNjVsB.Value);
				}
				orgqfgrCrmobGJnxqbGdAMXEeZnY2.SetSpecialElementKey(i, text);
				orgqfgrCrmobGJnxqbGdAMXEeZnY2.autoGeneratedValueFlags |= num;
				XFdvjghozpLZsrvkWgkIQqPrTeDD(num);
			}
			int num2 = 16384 << i;
			if ((orgqfgrCrmobGJnxqbGdAMXEeZnY2.autoGeneratedValueFlags & num2) == 0 && !string.IsNullOrEmpty(orgqfgrCrmobGJnxqbGdAMXEeZnY2.nonLocalizedDescriptiveName) && string.IsNullOrEmpty(orgqfgrCrmobGJnxqbGdAMXEeZnY2.GetSpecialElementNonLocalizedDescriptiveName(i)))
			{
				string text2 = orgqfgrCrmobGJnxqbGdAMXEeZnY2.nonLocalizedDescriptiveName;
				if (eSrXtKMIUZjpxRfWzNHzGoDkUsXw.nKOMQWpKurFAtKeCjgKJcJeqAbqFA(i).oPBcZcQLcCCmxHLvqEJHDmGGNjVsB.HasValue)
				{
					text2 = LocalizationManager.AppendToNameAxisDirection(text2, eSrXtKMIUZjpxRfWzNHzGoDkUsXw.nKOMQWpKurFAtKeCjgKJcJeqAbqFA(i).oPBcZcQLcCCmxHLvqEJHDmGGNjVsB.Value);
				}
				orgqfgrCrmobGJnxqbGdAMXEeZnY2.SetSpecialElementNonLocalizedDescriptiveName(i, text2);
				orgqfgrCrmobGJnxqbGdAMXEeZnY2.autoGeneratedValueFlags |= num2;
				XFdvjghozpLZsrvkWgkIQqPrTeDD(num2);
			}
		}
	}

	protected virtual void fywjGKRTSJoRNfqbwBmLFxSypKsW(JWyGUUsjYeTFhAbDNEOqGDnqBiaw P_0)
	{
		base.VnJKWKTgMlanDqXyFDmtdQZNvhXV(P_0);
		orgqfgrCrmobGJnxqbGdAMXEeZnY orgqfgrCrmobGJnxqbGdAMXEeZnY2 = MuqMqyULaTsKYQCcYNTXVFJtWgoN();
		if (orgqfgrCrmobGJnxqbGdAMXEeZnY2 == null || ((uint)orgqfgrCrmobGJnxqbGdAMXEeZnY2.autoGeneratedValueFlags & (uint)P_0) == 0 || base.wmxpDuCFjDeAdhOVfyzrBCCDpMkT != jZSMnsLXoBDMhquJQKqHviQNprmC.CompoundElement || !MJyJuisFiOmfspJhIRvXPkFSAPFT.yzssAvNAWgRZfJKNdgmvMuNHsBFU(base.kwfjWgpYavMRDMfyekVhYczFHBCY, out var eSrXtKMIUZjpxRfWzNHzGoDkUsXw))
		{
			return;
		}
		for (int i = 0; i < eSrXtKMIUZjpxRfWzNHzGoDkUsXw.gOGhhRRzbMztvfVGNQkYpoWayxzi; i++)
		{
			int num = 8388608 << i;
			if ((orgqfgrCrmobGJnxqbGdAMXEeZnY2.autoGeneratedValueFlags & num) != 0)
			{
				orgqfgrCrmobGJnxqbGdAMXEeZnY2.SetSpecialElementKey(i, null);
				orgqfgrCrmobGJnxqbGdAMXEeZnY2.autoGeneratedValueFlags &= ~num;
				XFdvjghozpLZsrvkWgkIQqPrTeDD(num);
			}
			int num2 = 16384 << i;
			if ((orgqfgrCrmobGJnxqbGdAMXEeZnY2.autoGeneratedValueFlags & num2) != 0)
			{
				orgqfgrCrmobGJnxqbGdAMXEeZnY2.SetSpecialElementNonLocalizedDescriptiveName(i, null);
				orgqfgrCrmobGJnxqbGdAMXEeZnY2.autoGeneratedValueFlags &= ~num2;
				XFdvjghozpLZsrvkWgkIQqPrTeDD(num2);
			}
		}
	}

	protected virtual JWyGUUsjYeTFhAbDNEOqGDnqBiaw BucocKhSSYCGVqLNNLvikJLyxNiE(rCaSuhSWufhFquqeuhJWSlKJKnNk P_0)
	{
		JWyGUUsjYeTFhAbDNEOqGDnqBiaw jWyGUUsjYeTFhAbDNEOqGDnqBiaw = base.JNsVFFfxWgmUyGiKpTpjZfmbKYeB(P_0);
		int num = HNmdAzQUBawVJDZrZRnhIjeuYffP;
		if ((P_0 & rCaSuhSWufhFquqeuhJWSlKJKnNk.Keys) != rCaSuhSWufhFquqeuhJWSlKJKnNk.None)
		{
			for (int i = 0; i < num; i++)
			{
				jWyGUUsjYeTFhAbDNEOqGDnqBiaw = (JWyGUUsjYeTFhAbDNEOqGDnqBiaw)((int)jWyGUUsjYeTFhAbDNEOqGDnqBiaw | (8388608 << i));
			}
		}
		if ((P_0 & rCaSuhSWufhFquqeuhJWSlKJKnNk.Names) != rCaSuhSWufhFquqeuhJWSlKJKnNk.None)
		{
			for (int j = 0; j < num; j++)
			{
				jWyGUUsjYeTFhAbDNEOqGDnqBiaw = (JWyGUUsjYeTFhAbDNEOqGDnqBiaw)((int)jWyGUUsjYeTFhAbDNEOqGDnqBiaw | (16384 << j));
			}
		}
		return jWyGUUsjYeTFhAbDNEOqGDnqBiaw;
	}

	protected orgqfgrCrmobGJnxqbGdAMXEeZnY MuqMqyULaTsKYQCcYNTXVFJtWgoN()
	{
		return ezuBKWkznYBOSXRGpqYrdiJDWPLoA() as orgqfgrCrmobGJnxqbGdAMXEeZnY;
	}

	protected virtual void gosHFbZnXneNzCbyCMttZIuDAfVBb()
	{
		base.xwVhfgkgqJaUdXIocRzzcWsTaSSK();
		int num = HNmdAzQUBawVJDZrZRnhIjeuYffP;
		for (int i = 0; i < num; i++)
		{
			XtKWPvibVeeipuzfMWsFFvSriMHH(i);
		}
	}

	protected virtual void KMJEQsffEShchLLuqvFdfhDIWzzH()
	{
		NbDPXWlaZpogZcLLEYqCGRinHQWq();
		if (base.wmxpDuCFjDeAdhOVfyzrBCCDpMkT != jZSMnsLXoBDMhquJQKqHviQNprmC.CompoundElement)
		{
			return;
		}
		GtxbKiHSwksUKuQYeAEqHnCDMtFmA gtxbKiHSwksUKuQYeAEqHnCDMtFmA = base.kwfjWgpYavMRDMfyekVhYczFHBCY;
		if ((gtxbKiHSwksUKuQYeAEqHnCDMtFmA == GtxbKiHSwksUKuQYeAEqHnCDMtFmA.Axis2D || (uint)(gtxbKiHSwksUKuQYeAEqHnCDMtFmA - 3) <= 2u) && qyCoxKkSFLoaZNWNoJbQHtvcPCik != null)
		{
			int num = HNmdAzQUBawVJDZrZRnhIjeuYffP;
			for (int i = 0; i < num; i++)
			{
				jriVMgSVfNhJUCcVjmEMYoZYjhGW(1, new ZfSdyTfpTJoTlWfkGbXUdYyHUehp(qyCoxKkSFLoaZNWNoJbQHtvcPCik[i], 16384 << i));
			}
		}
	}
}
