using System;
using Rewired.Internal.Localization;

internal class EsWxHDSqntpFyaXqdUbmApTIfXceA : sZLAxvZSvDRmVjMjTVRhHfujppQp
{
	protected readonly MJyJuisFiOmfspJhIRvXPkFSAPFT eoKyclTJiyicwNHgiNHaGrZdAylHA;

	private readonly string NUwrzRvROoivAXBBFtJheUSkAjyu;

	private readonly string QaMAxnOySjfGJVKRGmyjUAUBKixD;

	private string KedfQxGecOzXUESCExWLiLOdqJvFA;

	private readonly string DlHXtmXqmeZGmtgTmzssQjEUhWKAA;

	private int QszgWEGcHQSATUWmSuDGiOvNIjSO;

	public MJyJuisFiOmfspJhIRvXPkFSAPFT TMHlvqHxBpCGUAQoFpDnAxiNvTqy => eoKyclTJiyicwNHgiNHaGrZdAylHA;

	string sZLAxvZSvDRmVjMjTVRhHfujppQp.keyCategory => NUwrzRvROoivAXBBFtJheUSkAjyu;

	string sZLAxvZSvDRmVjMjTVRhHfujppQp.scriptingName => QaMAxnOySjfGJVKRGmyjUAUBKixD;

	string sZLAxvZSvDRmVjMjTVRhHfujppQp.nonLocalizedDescriptiveName
	{
		get
		{
			return KedfQxGecOzXUESCExWLiLOdqJvFA;
		}
		set
		{
			KedfQxGecOzXUESCExWLiLOdqJvFA = value;
		}
	}

	string sZLAxvZSvDRmVjMjTVRhHfujppQp.key => DlHXtmXqmeZGmtgTmzssQjEUhWKAA;

	int sZLAxvZSvDRmVjMjTVRhHfujppQp.autoGeneratedValueFlags
	{
		get
		{
			return QszgWEGcHQSATUWmSuDGiOvNIjSO;
		}
		set
		{
			QszgWEGcHQSATUWmSuDGiOvNIjSO = value;
		}
	}

	public string keyCategory => NUwrzRvROoivAXBBFtJheUSkAjyu;

	public string scriptingName => QaMAxnOySjfGJVKRGmyjUAUBKixD;

	public string yVatUAudEsSPycjNahorNfJAMqVb
	{
		get
		{
			if (!LocalizationManager.isEnabled)
			{
				return KedfQxGecOzXUESCExWLiLOdqJvFA;
			}
			return eoKyclTJiyicwNHgiNHaGrZdAylHA.HKQoqutKkgeGtFcRmtcKMQqgsDoY;
		}
	}

	public string nonLocalizedDescriptiveName => KedfQxGecOzXUESCExWLiLOdqJvFA;

	public string key => DlHXtmXqmeZGmtgTmzssQjEUhWKAA;

	public EsWxHDSqntpFyaXqdUbmApTIfXceA(MJyJuisFiOmfspJhIRvXPkFSAPFT P_0, string P_1, string P_2, string P_3, string P_4)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException();
		}
		eoKyclTJiyicwNHgiNHaGrZdAylHA = P_0;
		NUwrzRvROoivAXBBFtJheUSkAjyu = P_1;
		QaMAxnOySjfGJVKRGmyjUAUBKixD = P_2;
		KedfQxGecOzXUESCExWLiLOdqJvFA = P_3;
		DlHXtmXqmeZGmtgTmzssQjEUhWKAA = P_4;
		P_0.GcNXeKljLqBwpXBtANTbgsUENESW(this);
	}

	public virtual bool EKBjmhhLPylzdjWOjllvxzJdReJi(EsWxHDSqntpFyaXqdUbmApTIfXceA P_0, bool P_1)
	{
		if (P_0 == null)
		{
			return false;
		}
		if ((object)GetType() != P_0.GetType())
		{
			return false;
		}
		if (!eoKyclTJiyicwNHgiNHaGrZdAylHA.INYrIPNPQGAfMACMHLnoinKxNIiHb(P_0.eoKyclTJiyicwNHgiNHaGrZdAylHA, P_1))
		{
			return false;
		}
		return true;
	}
}
