using System;

internal class xhoBmdXXajZTTXGDQAZKPpMHcNEkA : IkNokIafnDXAZobQNzBQDEduXYfJ
{
	protected readonly xWpnnJnIauvtZWmfyACergtAcaup ahVqPjFfwfsOxtMBoWqFtjyNgFbbA;

	private readonly string vMplaaXqOlVriJgyyUaUsZukBaRG;

	private readonly string hDoIAmDJNXquXaLnioJdYdlrxvX;

	private int lilEwHeNjIRvyirsdLcnzCoabuoK;

	public xWpnnJnIauvtZWmfyACergtAcaup IDpaRyhrrThLwHfwEGPUwSrVSHge => ahVqPjFfwfsOxtMBoWqFtjyNgFbbA;

	string IkNokIafnDXAZobQNzBQDEduXYfJ.keyCategory => vMplaaXqOlVriJgyyUaUsZukBaRG;

	string IkNokIafnDXAZobQNzBQDEduXYfJ.key => hDoIAmDJNXquXaLnioJdYdlrxvX;

	int IkNokIafnDXAZobQNzBQDEduXYfJ.autoGeneratedValueFlags
	{
		get
		{
			return lilEwHeNjIRvyirsdLcnzCoabuoK;
		}
		set
		{
			lilEwHeNjIRvyirsdLcnzCoabuoK = value;
		}
	}

	public string keyCategory => vMplaaXqOlVriJgyyUaUsZukBaRG;

	public string key => hDoIAmDJNXquXaLnioJdYdlrxvX;

	public xhoBmdXXajZTTXGDQAZKPpMHcNEkA(xWpnnJnIauvtZWmfyACergtAcaup P_0, string P_1, string P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException();
		}
		ahVqPjFfwfsOxtMBoWqFtjyNgFbbA = P_0;
		vMplaaXqOlVriJgyyUaUsZukBaRG = P_1;
		hDoIAmDJNXquXaLnioJdYdlrxvX = P_2;
		P_0.NgvSmCyfgtkxZQxmcuFMzgwRamCM(this);
	}

	public virtual bool XPCaKRwAhYCczFhRHhRDXxBUJJBGA(xhoBmdXXajZTTXGDQAZKPpMHcNEkA P_0)
	{
		if (P_0 == null)
		{
			return false;
		}
		if ((object)GetType() != P_0.GetType())
		{
			return false;
		}
		if (!ahVqPjFfwfsOxtMBoWqFtjyNgFbbA.vJkPAvTOHaVyfZbkDySJwPQgsDUF(P_0.ahVqPjFfwfsOxtMBoWqFtjyNgFbbA))
		{
			return false;
		}
		return true;
	}
}
