<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Timberborn.UncuttableYielding</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Timberborn.WalkingSystem">
      <HintPath>..\..\Assemblies\Timberborn.WalkingSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BaseComponentSystem">
      <HintPath>..\..\Assemblies\Timberborn.BaseComponentSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.ReservableSystem">
      <HintPath>..\..\Assemblies\Timberborn.ReservableSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TemplateInstantiation">
      <HintPath>..\..\Assemblies\Timberborn.TemplateInstantiation.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Demolishing">
      <HintPath>..\..\Assemblies\Timberborn.Demolishing.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EntitySystem">
      <HintPath>..\..\Assemblies\Timberborn.EntitySystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Yielding">
      <HintPath>..\..\Assemblies\Timberborn.Yielding.dll</HintPath>
    </Reference>
    <Reference Include="Bindito.Core">
      <HintPath>..\..\Assemblies\Bindito.Core.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.NaturalResourcesModelSystem">
      <HintPath>..\..\Assemblies\Timberborn.NaturalResourcesModelSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.CharacterModelSystem">
      <HintPath>..\..\Assemblies\Timberborn.CharacterModelSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.NaturalResources">
      <HintPath>..\..\Assemblies\Timberborn.NaturalResources.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>