using System;
using Rewired.Internal.Localization;
using UnityEngine;

namespace Rewired
{
	[Serializable]
	public sealed class InputLayout : leeNpeIpkRWAaDYnewmtyKpQcRpw
	{
		private const string keyCategory = "controller_map/layout";

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _name;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _descriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _key;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private int _id;

		[NonSerialized]
		private oEEgoKqIygbHTIQCNsneyiTKzIXQA lUhByGfjSDcxEfnGZsEQJnxcsRemA;

		[NonSerialized]
		private int KQktlXlnnBCKtaoAUaJCRyKCZzgH;

		public string name
		{
			get
			{
				return _name;
			}
			internal set
			{
				_name = text;
			}
		}

		public string descriptiveName
		{
			get
			{
				if (!ReInput.isReady || !LocalizationManager.isEnabled || lUhByGfjSDcxEfnGZsEQJnxcsRemA == null)
				{
					return _descriptiveName;
				}
				return lUhByGfjSDcxEfnGZsEQJnxcsRemA.YYpaixksduwqUQfFFmPUzWfHjhDu;
			}
			internal set
			{
				nonLocalizedDescriptiveName = text;
			}
		}

		public int id
		{
			get
			{
				return _id;
			}
			internal set
			{
				_id = num;
			}
		}

		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return _key;
			}
			set
			{
				_key = value;
				if (ReInput.isReady && lUhByGfjSDcxEfnGZsEQJnxcsRemA != null)
				{
					lUhByGfjSDcxEfnGZsEQJnxcsRemA.rGfGCTURtYyLPalJfxlbNDAOsgNA();
				}
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
				if (ReInput.isReady && lUhByGfjSDcxEfnGZsEQJnxcsRemA != null)
				{
					lUhByGfjSDcxEfnGZsEQJnxcsRemA.GvKqFlBIauBSccpqkijaDCUIwlHHB();
				}
			}
		}

		string leeNpeIpkRWAaDYnewmtyKpQcRpw.keyCategory => "controller_map/layout";

		string leeNpeIpkRWAaDYnewmtyKpQcRpw.scriptingName => _name;

		string leeNpeIpkRWAaDYnewmtyKpQcRpw.nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
			}
		}

		string leeNpeIpkRWAaDYnewmtyKpQcRpw.key => _key;

		int leeNpeIpkRWAaDYnewmtyKpQcRpw.autoGeneratedValueFlags
		{
			get
			{
				return KQktlXlnnBCKtaoAUaJCRyKCZzgH;
			}
			set
			{
				KQktlXlnnBCKtaoAUaJCRyKCZzgH = value;
			}
		}

		public InputLayout()
		{
		}

		public InputLayout(InputLayout P_0)
			: this()
		{
			_name = P_0._name;
			_descriptiveName = P_0._descriptiveName;
			_key = P_0._key;
			_id = P_0._id;
			KQktlXlnnBCKtaoAUaJCRyKCZzgH = P_0.KQktlXlnnBCKtaoAUaJCRyKCZzgH;
		}

		public InputLayout Clone()
		{
			return new InputLayout(this);
		}

		internal void eurMFZskNUorrhkDAbZqDHMBfTPb()
		{
			lUhByGfjSDcxEfnGZsEQJnxcsRemA = oEEgoKqIygbHTIQCNsneyiTKzIXQA.CXYVDSKouccTTATbQGDZttKGiskv(this);
		}

		internal void vZgfdOxBEqlNUFzqwbhRvPqBvkJL()
		{
		}
	}
}
