<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>VampireSurvivors.Runtime</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\Assemblies\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.2D.Runtime">
      <HintPath>..\..\Assemblies\Unity.RenderPipelines.Universal.2D.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\Assemblies\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Common">
      <HintPath>..\..\Assemblies\Coherence.Common.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Toolkit">
      <HintPath>..\..\Assemblies\Coherence.Toolkit.dll</HintPath>
    </Reference>
    <Reference Include="PlayFabParty">
      <HintPath>..\..\Assemblies\PlayFabParty.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Transport">
      <HintPath>..\..\Assemblies\Coherence.Transport.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Log">
      <HintPath>..\..\Assemblies\Coherence.Log.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Stats">
      <HintPath>..\..\Assemblies\Coherence.Stats.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Brook">
      <HintPath>..\..\Assemblies\Coherence.Brook.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\..\Assemblies\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="Rewired_Core">
      <HintPath>..\..\Assemblies\Rewired_Core.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\Assemblies\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\..\Assemblies\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>..\..\Assemblies\Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="PhaserPort">
      <HintPath>..\..\Assemblies\PhaserPort.dll</HintPath>
    </Reference>
    <Reference Include="DOTween">
      <HintPath>..\..\Assemblies\DOTween.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Runtime">
      <HintPath>..\..\Assemblies\Coherence.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Zenject">
      <HintPath>..\..\Assemblies\Zenject.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.ReplicationServer">
      <HintPath>..\..\Assemblies\Coherence.ReplicationServer.dll</HintPath>
    </Reference>
    <Reference Include="PlayFab">
      <HintPath>..\..\Assemblies\PlayFab.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Steamworks.Win64">
      <HintPath>..\..\Assemblies\Facepunch.Steamworks.Win64.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>..\..\Assemblies\System.Core.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TilemapModule">
      <HintPath>..\..\Assemblies\UnityEngine.TilemapModule.dll</HintPath>
    </Reference>
    <Reference Include="Dreamteck.Splines">
      <HintPath>..\..\Assemblies\Dreamteck.Splines.dll</HintPath>
    </Reference>
    <Reference Include="Rewired_UnityUI_CSharp">
      <HintPath>..\..\Assemblies\Rewired_UnityUI_CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\Assemblies\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="UniTask">
      <HintPath>..\..\Assemblies\UniTask.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>..\..\Assemblies\UnityEngine.VideoModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\..\Assemblies\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="QFSW.MOP2">
      <HintPath>..\..\Assemblies\QFSW.MOP2.dll</HintPath>
    </Reference>
    <Reference Include="SuperTiled2Unity">
      <HintPath>..\..\Assemblies\SuperTiled2Unity.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\..\Assemblies\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Addressables">
      <HintPath>..\..\Assemblies\Unity.Addressables.dll</HintPath>
    </Reference>
    <Reference Include="ProCamera2D">
      <HintPath>..\..\Assemblies\ProCamera2D.dll</HintPath>
    </Reference>
    <Reference Include="MAScripts">
      <HintPath>..\..\Assemblies\MAScripts.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>..\..\Assemblies\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ResourceManager">
      <HintPath>..\..\Assemblies\Unity.ResourceManager.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.OdinInspector.Attributes">
      <HintPath>..\..\Assemblies\Sirenix.OdinInspector.Attributes.dll</HintPath>
    </Reference>
    <Reference Include="lexonegit.unity-twitch-chat">
      <HintPath>..\..\Assemblies\lexonegit.unity-twitch-chat.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\Assemblies\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.LevelPlay">
      <HintPath>..\..\Assemblies\Unity.LevelPlay.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Runtime">
      <HintPath>..\..\Assemblies\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Rewired_CSharp">
      <HintPath>..\..\Assemblies\Rewired_CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\..\Assemblies\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.SpriteMaskModule">
      <HintPath>..\..\Assemblies\UnityEngine.SpriteMaskModule.dll</HintPath>
    </Reference>
    <Reference Include="l2localization">
      <HintPath>..\..\Assemblies\l2localization.dll</HintPath>
    </Reference>
    <Reference Include="Coffee.UIParticle">
      <HintPath>..\..\Assemblies\Coffee.UIParticle.dll</HintPath>
    </Reference>
    <Reference Include="Doozy">
      <HintPath>..\..\Assemblies\Doozy.dll</HintPath>
    </Reference>
    <Reference Include="UIEffect">
      <HintPath>..\..\Assemblies\UIEffect.dll</HintPath>
    </Reference>
    <Reference Include="System.Numerics" />
    <Reference Include="Zenject-usage">
      <HintPath>..\..\Assemblies\Zenject-usage.dll</HintPath>
    </Reference>
    <Reference Include="PauseSystem">
      <HintPath>..\..\Assemblies\PauseSystem.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst">
      <HintPath>..\..\Assemblies\Unity.Burst.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>..\..\Assemblies\Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="Poncle.Schema.Attributes">
      <HintPath>..\..\Assemblies\Poncle.Schema.Attributes.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>..\..\Assemblies\Unity.Collections.dll</HintPath>
    </Reference>
    <Reference Include="UnsafeAccess">
      <HintPath>..\..\Assemblies\UnsafeAccess.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>