using System;
using Rewired.Internal.Glyphs;
using Rewired.Internal.Localization;

internal abstract class crsEzMrGeGLRuTfFYobwxrRWjYOV : xWpnnJnIauvtZWmfyACergtAcaup
{
	protected KeyedGlyph[] ZtvYrKMPlCNpDiSxgLsgPFLiNNjF;

	public int RCojFLAycwbyxuwZlLqnwszxMuRK => MJyJuisFiOmfspJhIRvXPkFSAPFT.WFlgMaYJJpzOhusNWIdstVGKtOzl(base.fKdZAaHFMHQcMidfZwsSpPaBghlH, base.TzmGaqpWpytaYoWdsgszGPGEfyTe);

	public abstract object USpHQpJevJTvoQoGllRQnGXljnCA(int P_0);

	public abstract string GflJQkxSEFvgtMzAOHUirFNnIciZ(int P_0);

	protected crsEzMrGeGLRuTfFYobwxrRWjYOV(MJyJuisFiOmfspJhIRvXPkFSAPFT.jZSMnsLXoBDMhquJQKqHviQNprmC P_0, MJyJuisFiOmfspJhIRvXPkFSAPFT.GtxbKiHSwksUKuQYeAEqHnCDMtFmA P_1)
		: base(P_0, P_1)
	{
	}

	protected crsEzMrGeGLRuTfFYobwxrRWjYOV(ljpLhlKaijVdgLAKEnJGvqHultLG P_0, MJyJuisFiOmfspJhIRvXPkFSAPFT.jZSMnsLXoBDMhquJQKqHviQNprmC P_1, MJyJuisFiOmfspJhIRvXPkFSAPFT.GtxbKiHSwksUKuQYeAEqHnCDMtFmA P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
	}

	protected virtual void tMzRHxiDzKwRZfxaVQRYOSwFEVes()
	{
		int num = RCojFLAycwbyxuwZlLqnwszxMuRK;
		ZtvYrKMPlCNpDiSxgLsgPFLiNNjF = null;
		if (num > 0)
		{
			ZtvYrKMPlCNpDiSxgLsgPFLiNNjF = new KeyedGlyph[num];
			for (int i = 0; i < num; i++)
			{
				ZtvYrKMPlCNpDiSxgLsgPFLiNNjF[i] = new KeyedGlyph();
			}
		}
		pMDkYhpVRrVbVWDhBkHpXIvtpTCL();
	}

	public virtual void adOibUinMzydZKeXJMGYThsGBWBBA(ljpLhlKaijVdgLAKEnJGvqHultLG P_0)
	{
		NgvSmCyfgtkxZQxmcuFMzgwRamCM(P_0);
	}

	public virtual void jYnpddxqQzYeDCEwzBjXEPzcfnvv(IkNokIafnDXAZobQNzBQDEduXYfJ P_0)
	{
		base.NgvSmCyfgtkxZQxmcuFMzgwRamCM(P_0);
		if (!(P_0 is ljpLhlKaijVdgLAKEnJGvqHultLG))
		{
			throw new ArgumentException("value must implement " + typeof(ljpLhlKaijVdgLAKEnJGvqHultLG));
		}
	}

	public virtual void fOaqgOryMgMnANswgpuvlicXkSJP()
	{
		RUIfcOfJipXoTKmSBTPqJudFaXATA();
		if (ZtvYrKMPlCNpDiSxgLsgPFLiNNjF != null)
		{
			for (int i = 0; i < RCojFLAycwbyxuwZlLqnwszxMuRK; i++)
			{
				ZtvYrKMPlCNpDiSxgLsgPFLiNNjF[i].Clear();
			}
		}
	}

	public virtual bool IDzdNUmumMHWoiSEnTnUEyYEknrN(CcGgbpntamtnacmabegPksrcgakT P_0)
	{
		if (!(P_0 is crsEzMrGeGLRuTfFYobwxrRWjYOV crsEzMrGeGLRuTfFYobwxrRWjYOV2))
		{
			return false;
		}
		if (!PoQfHuGkWfdIDeuihNPuAbBlEUYMb(P_0))
		{
			return false;
		}
		ljpLhlKaijVdgLAKEnJGvqHultLG ljpLhlKaijVdgLAKEnJGvqHultLG2 = eUYsnidTgREbygNjDfHkXAtHgYXB();
		ljpLhlKaijVdgLAKEnJGvqHultLG ljpLhlKaijVdgLAKEnJGvqHultLG3 = crsEzMrGeGLRuTfFYobwxrRWjYOV2.eUYsnidTgREbygNjDfHkXAtHgYXB();
		if (ljpLhlKaijVdgLAKEnJGvqHultLG2 == null != (ljpLhlKaijVdgLAKEnJGvqHultLG3 == null))
		{
			return false;
		}
		if (ljpLhlKaijVdgLAKEnJGvqHultLG2 != null)
		{
			int num = RCojFLAycwbyxuwZlLqnwszxMuRK;
			for (int i = 0; i < num; i++)
			{
				if (!string.Equals(ljpLhlKaijVdgLAKEnJGvqHultLG2.GetSpecialElementKey(i), ljpLhlKaijVdgLAKEnJGvqHultLG3.GetSpecialElementKey(i), StringComparison.Ordinal))
				{
					return false;
				}
			}
		}
		return true;
	}

	protected virtual void eqBICTRBSkCKSjjxevLHHJXWAjVHb()
	{
		piSBZMsrTDaJENouqIrvCmoZCzaF();
		if (ZtvYrKMPlCNpDiSxgLsgPFLiNNjF != null)
		{
			for (int i = 0; i < ZtvYrKMPlCNpDiSxgLsgPFLiNNjF.Length; i++)
			{
				ZtvYrKMPlCNpDiSxgLsgPFLiNNjF[i].Clear();
			}
		}
	}

	protected virtual void mAQyoVkjMNeQRrGdaXepPlujxqir(MJyJuisFiOmfspJhIRvXPkFSAPFT.rCaSuhSWufhFquqeuhJWSlKJKnNk P_0)
	{
		base.sMNNSwAEQxubPCfZLNJgsdCBkCzO(P_0);
		ljpLhlKaijVdgLAKEnJGvqHultLG ljpLhlKaijVdgLAKEnJGvqHultLG2 = eUYsnidTgREbygNjDfHkXAtHgYXB();
		if (ljpLhlKaijVdgLAKEnJGvqHultLG2 == null || base.fKdZAaHFMHQcMidfZwsSpPaBghlH != MJyJuisFiOmfspJhIRvXPkFSAPFT.jZSMnsLXoBDMhquJQKqHviQNprmC.CompoundElement || !MJyJuisFiOmfspJhIRvXPkFSAPFT.yzssAvNAWgRZfJKNdgmvMuNHsBFU(base.TzmGaqpWpytaYoWdsgszGPGEfyTe, out var eSrXtKMIUZjpxRfWzNHzGoDkUsXw))
		{
			return;
		}
		for (int i = 0; i < eSrXtKMIUZjpxRfWzNHzGoDkUsXw.gOGhhRRzbMztvfVGNQkYpoWayxzi; i++)
		{
			int num = 8388608 << i;
			if ((ljpLhlKaijVdgLAKEnJGvqHultLG2.autoGeneratedValueFlags & num) == 0 && !string.IsNullOrEmpty(ljpLhlKaijVdgLAKEnJGvqHultLG2.key) && string.IsNullOrEmpty(ljpLhlKaijVdgLAKEnJGvqHultLG2.GetSpecialElementKey(i)))
			{
				string text = ljpLhlKaijVdgLAKEnJGvqHultLG2.key;
				if (eSrXtKMIUZjpxRfWzNHzGoDkUsXw.nKOMQWpKurFAtKeCjgKJcJeqAbqFA(i).oPBcZcQLcCCmxHLvqEJHDmGGNjVsB.HasValue)
				{
					text = LocalizationManager.AppendToKeyAxisDirection(text, eSrXtKMIUZjpxRfWzNHzGoDkUsXw.nKOMQWpKurFAtKeCjgKJcJeqAbqFA(i).oPBcZcQLcCCmxHLvqEJHDmGGNjVsB.Value);
				}
				ljpLhlKaijVdgLAKEnJGvqHultLG2.SetSpecialElementKey(i, text);
				ljpLhlKaijVdgLAKEnJGvqHultLG2.autoGeneratedValueFlags |= num;
				ZijjNbcjtNDoOooGWeXrwQkaSDnl(num);
			}
		}
	}

	protected virtual void LddXBOZGJFLCKsIsjAmRzKHMUOJF(MJyJuisFiOmfspJhIRvXPkFSAPFT.JWyGUUsjYeTFhAbDNEOqGDnqBiaw P_0)
	{
		base.uVDhkShHjzvWWRUtucRZzvqOrakJA(P_0);
		ljpLhlKaijVdgLAKEnJGvqHultLG ljpLhlKaijVdgLAKEnJGvqHultLG2 = eUYsnidTgREbygNjDfHkXAtHgYXB();
		if (ljpLhlKaijVdgLAKEnJGvqHultLG2 == null || ((uint)ljpLhlKaijVdgLAKEnJGvqHultLG2.autoGeneratedValueFlags & (uint)P_0) == 0 || base.fKdZAaHFMHQcMidfZwsSpPaBghlH != MJyJuisFiOmfspJhIRvXPkFSAPFT.jZSMnsLXoBDMhquJQKqHviQNprmC.CompoundElement || !MJyJuisFiOmfspJhIRvXPkFSAPFT.yzssAvNAWgRZfJKNdgmvMuNHsBFU(base.TzmGaqpWpytaYoWdsgszGPGEfyTe, out var eSrXtKMIUZjpxRfWzNHzGoDkUsXw))
		{
			return;
		}
		for (int i = 0; i < eSrXtKMIUZjpxRfWzNHzGoDkUsXw.gOGhhRRzbMztvfVGNQkYpoWayxzi; i++)
		{
			int num = 8388608 << i;
			if ((ljpLhlKaijVdgLAKEnJGvqHultLG2.autoGeneratedValueFlags & num) != 0)
			{
				ljpLhlKaijVdgLAKEnJGvqHultLG2.SetSpecialElementKey(i, null);
				ljpLhlKaijVdgLAKEnJGvqHultLG2.autoGeneratedValueFlags &= ~num;
				ZijjNbcjtNDoOooGWeXrwQkaSDnl(num);
			}
		}
	}

	protected virtual MJyJuisFiOmfspJhIRvXPkFSAPFT.JWyGUUsjYeTFhAbDNEOqGDnqBiaw svBCtpYCGFMNgRqyHiODeYdPfCAO(MJyJuisFiOmfspJhIRvXPkFSAPFT.rCaSuhSWufhFquqeuhJWSlKJKnNk P_0)
	{
		MJyJuisFiOmfspJhIRvXPkFSAPFT.JWyGUUsjYeTFhAbDNEOqGDnqBiaw jWyGUUsjYeTFhAbDNEOqGDnqBiaw = base.XNeiYAxQauwwNEjiyCIdxKnteSIO(P_0);
		int num = RCojFLAycwbyxuwZlLqnwszxMuRK;
		if ((P_0 & MJyJuisFiOmfspJhIRvXPkFSAPFT.rCaSuhSWufhFquqeuhJWSlKJKnNk.Keys) != MJyJuisFiOmfspJhIRvXPkFSAPFT.rCaSuhSWufhFquqeuhJWSlKJKnNk.None)
		{
			for (int i = 0; i < num; i++)
			{
				jWyGUUsjYeTFhAbDNEOqGDnqBiaw = (MJyJuisFiOmfspJhIRvXPkFSAPFT.JWyGUUsjYeTFhAbDNEOqGDnqBiaw)((int)jWyGUUsjYeTFhAbDNEOqGDnqBiaw | (8388608 << i));
			}
		}
		return jWyGUUsjYeTFhAbDNEOqGDnqBiaw;
	}

	protected ljpLhlKaijVdgLAKEnJGvqHultLG eUYsnidTgREbygNjDfHkXAtHgYXB()
	{
		return fReLfzPhSCfLTAzobjWfyqjTDxEt() as ljpLhlKaijVdgLAKEnJGvqHultLG;
	}

	protected virtual void tdqlKWhMWJcDeOzQjliGyjMLNaEL()
	{
		base.oRVHAZrlknBMDEcGKbVwMQQatoQe();
		int num = RCojFLAycwbyxuwZlLqnwszxMuRK;
		for (int i = 0; i < num; i++)
		{
			USpHQpJevJTvoQoGllRQnGXljnCA(i);
		}
	}

	protected virtual void asqEXtmIRYGkAnHOzTWjmRKKOwAd()
	{
		MDBuurQPSiKEOWHlVBUsThHIaTKbA();
	}
}
