using System;
using Rewired;
using Rewired.Internal.Localization;

internal abstract class ewFYRuWBzwsRVoyZGJsYxjxEMafx : MJyJuisFiOmfspJhIRvXPkFSAPFT
{
	protected readonly LocalizedString BvlXuXvUpfCJuelLFACNaekBqNQdb;

	protected readonly LocalizedString hqXDKRZmztXnmajyjtwrdWJeCdBt;

	public abstract string vqTJyxMIVweNIWENvOzgHIrQkYCw { get; }

	public abstract string FktASepfaNwtFksADsQexzwgRpBn { get; }

	protected ewFYRuWBzwsRVoyZGJsYxjxEMafx(jZSMnsLXoBDMhquJQKqHviQNprmC P_0, GtxbKiHSwksUKuQYeAEqHnCDMtFmA P_1)
		: base(P_0, P_1)
	{
		BvlXuXvUpfCJuelLFACNaekBqNQdb = new LocalizedString();
		hqXDKRZmztXnmajyjtwrdWJeCdBt = new LocalizedString();
	}

	protected ewFYRuWBzwsRVoyZGJsYxjxEMafx(qlShIqeuHSIRhnLpCXWfkIdpMdpx P_0, jZSMnsLXoBDMhquJQKqHviQNprmC P_1, GtxbKiHSwksUKuQYeAEqHnCDMtFmA P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
		BvlXuXvUpfCJuelLFACNaekBqNQdb = new LocalizedString();
		hqXDKRZmztXnmajyjtwrdWJeCdBt = new LocalizedString();
	}

	protected virtual void UMuzSOrATJDpmTvCYIjdAjXoKfOU()
	{
		VnWBKSRlXtnXrnYpEZchoRflOLED();
	}

	public virtual void XtlMiFGmXFrnntnRLSiCqmhAPDVX(qlShIqeuHSIRhnLpCXWfkIdpMdpx P_0)
	{
		GcNXeKljLqBwpXBtANTbgsUENESW(P_0);
	}

	public virtual void JLjSaVagYLYewhTVlAgaTUgwngfE(sZLAxvZSvDRmVjMjTVRhHfujppQp P_0)
	{
		base.GcNXeKljLqBwpXBtANTbgsUENESW(P_0);
		if (!(P_0 is qlShIqeuHSIRhnLpCXWfkIdpMdpx))
		{
			throw new ArgumentException("value must implement " + typeof(qlShIqeuHSIRhnLpCXWfkIdpMdpx));
		}
	}

	public virtual void OKsRzxovMurkliDfwNnuCfSfcMpr()
	{
		JCAXBBaNFkTsJKtXzRPvwKXTRcrq();
		BvlXuXvUpfCJuelLFACNaekBqNQdb.Clear();
		hqXDKRZmztXnmajyjtwrdWJeCdBt.Clear();
	}

	public virtual void xWekyFhtDjWStXkrZAnLjVJFgbSeb()
	{
		lEtBlPkzIphsonzxFzbxmYcymXxrA();
		BvlXuXvUpfCJuelLFACNaekBqNQdb.Clear();
		hqXDKRZmztXnmajyjtwrdWJeCdBt.Clear();
	}

	public void gfdeyNgRmeIQeqwHEklubgsnrpiBA()
	{
		BvlXuXvUpfCJuelLFACNaekBqNQdb.Clear();
		sxIwjwSDkhWegJoWETHTsxpgJcOb(rCaSuhSWufhFquqeuhJWSlKJKnNk.Keys);
	}

	public void LojfYKiBhvXZsiErjRqzlvwEANumA()
	{
		hqXDKRZmztXnmajyjtwrdWJeCdBt.Clear();
		sxIwjwSDkhWegJoWETHTsxpgJcOb(rCaSuhSWufhFquqeuhJWSlKJKnNk.Keys);
	}

	public void mFMkdpduWHHeUgsHviuqmEEMyKNJ()
	{
		BvlXuXvUpfCJuelLFACNaekBqNQdb.Clear();
		sxIwjwSDkhWegJoWETHTsxpgJcOb(rCaSuhSWufhFquqeuhJWSlKJKnNk.Names);
	}

	public void BIVTdIpnFUBwhhnXrMOryHDWffqBA()
	{
		hqXDKRZmztXnmajyjtwrdWJeCdBt.Clear();
		sxIwjwSDkhWegJoWETHTsxpgJcOb(rCaSuhSWufhFquqeuhJWSlKJKnNk.Names);
	}

	public virtual bool MFpmRbNwDbFAbcYwUNdDzgsuwdgX(ORSKUsFUQMFbVqzYDhEFDxAETxpN P_0, bool P_1)
	{
		if (!(P_0 is ewFYRuWBzwsRVoyZGJsYxjxEMafx ewFYRuWBzwsRVoyZGJsYxjxEMafx2))
		{
			return false;
		}
		if (!IDvCTHHzFaiwfZeoUqzJwjFbvlWj(P_0, P_1))
		{
			return false;
		}
		qlShIqeuHSIRhnLpCXWfkIdpMdpx qlShIqeuHSIRhnLpCXWfkIdpMdpx2 = zoHlOIjhqmdBxhlWfBbFhGYIwfBOb();
		qlShIqeuHSIRhnLpCXWfkIdpMdpx qlShIqeuHSIRhnLpCXWfkIdpMdpx3 = ewFYRuWBzwsRVoyZGJsYxjxEMafx2.zoHlOIjhqmdBxhlWfBbFhGYIwfBOb();
		if (qlShIqeuHSIRhnLpCXWfkIdpMdpx2 == null != (qlShIqeuHSIRhnLpCXWfkIdpMdpx3 == null))
		{
			return false;
		}
		if (qlShIqeuHSIRhnLpCXWfkIdpMdpx2 != null && P_1 && (!string.Equals(qlShIqeuHSIRhnLpCXWfkIdpMdpx2.positiveKey, qlShIqeuHSIRhnLpCXWfkIdpMdpx3.positiveKey, StringComparison.Ordinal) || !string.Equals(qlShIqeuHSIRhnLpCXWfkIdpMdpx2.negativeKey, qlShIqeuHSIRhnLpCXWfkIdpMdpx3.negativeKey, StringComparison.Ordinal) || !string.Equals(qlShIqeuHSIRhnLpCXWfkIdpMdpx2.nonLocalizedPositiveDescriptiveName, qlShIqeuHSIRhnLpCXWfkIdpMdpx3.nonLocalizedPositiveDescriptiveName, StringComparison.Ordinal) || !string.Equals(qlShIqeuHSIRhnLpCXWfkIdpMdpx2.nonLocalizedNegativeDescriptiveName, qlShIqeuHSIRhnLpCXWfkIdpMdpx3.nonLocalizedNegativeDescriptiveName, StringComparison.Ordinal)))
		{
			return false;
		}
		return true;
	}

	protected virtual void PSokMTdGZbfwOFqvmLkfyCxipsSGA()
	{
		vlOKPjAaaycgGQlEQhKKEoxzutTJA();
		BvlXuXvUpfCJuelLFACNaekBqNQdb.Clear();
		hqXDKRZmztXnmajyjtwrdWJeCdBt.Clear();
	}

	protected virtual void XgndbXPEzVoEnNVuJFIryshdPORb(rCaSuhSWufhFquqeuhJWSlKJKnNk P_0)
	{
		base.sxIwjwSDkhWegJoWETHTsxpgJcOb(P_0);
		qlShIqeuHSIRhnLpCXWfkIdpMdpx qlShIqeuHSIRhnLpCXWfkIdpMdpx2 = zoHlOIjhqmdBxhlWfBbFhGYIwfBOb();
		if (qlShIqeuHSIRhnLpCXWfkIdpMdpx2 == null)
		{
			return;
		}
		if (!string.IsNullOrEmpty(qlShIqeuHSIRhnLpCXWfkIdpMdpx2.key))
		{
			if ((qlShIqeuHSIRhnLpCXWfkIdpMdpx2.autoGeneratedValueFlags & 8) == 0 && string.IsNullOrEmpty(qlShIqeuHSIRhnLpCXWfkIdpMdpx2.positiveKey) && qWkcKzDmUwsWBagLentZGZhtKSuuA(Pole.Positive))
			{
				qlShIqeuHSIRhnLpCXWfkIdpMdpx2.positiveKey = qlShIqeuHSIRhnLpCXWfkIdpMdpx2.key;
				if (nBOjCIRGYCWaaPRIUgpZVomTbPbx(Pole.Positive))
				{
					qlShIqeuHSIRhnLpCXWfkIdpMdpx2.positiveKey = LocalizationManager.AppendToKeyAxisPole(qlShIqeuHSIRhnLpCXWfkIdpMdpx2.positiveKey, Pole.Positive);
				}
				qlShIqeuHSIRhnLpCXWfkIdpMdpx2.autoGeneratedValueFlags |= 8;
				XFdvjghozpLZsrvkWgkIQqPrTeDD(8);
			}
			if ((qlShIqeuHSIRhnLpCXWfkIdpMdpx2.autoGeneratedValueFlags & 0x10) == 0 && string.IsNullOrEmpty(qlShIqeuHSIRhnLpCXWfkIdpMdpx2.negativeKey) && qWkcKzDmUwsWBagLentZGZhtKSuuA(Pole.Negative))
			{
				qlShIqeuHSIRhnLpCXWfkIdpMdpx2.negativeKey = qlShIqeuHSIRhnLpCXWfkIdpMdpx2.key;
				if (nBOjCIRGYCWaaPRIUgpZVomTbPbx(Pole.Negative))
				{
					qlShIqeuHSIRhnLpCXWfkIdpMdpx2.negativeKey = LocalizationManager.AppendToKeyAxisPole(qlShIqeuHSIRhnLpCXWfkIdpMdpx2.negativeKey, Pole.Negative);
				}
				qlShIqeuHSIRhnLpCXWfkIdpMdpx2.autoGeneratedValueFlags |= 16;
				XFdvjghozpLZsrvkWgkIQqPrTeDD(16);
			}
		}
		if ((qlShIqeuHSIRhnLpCXWfkIdpMdpx2.autoGeneratedValueFlags & 2) == 0 && string.IsNullOrEmpty(qlShIqeuHSIRhnLpCXWfkIdpMdpx2.nonLocalizedPositiveDescriptiveName) && qWkcKzDmUwsWBagLentZGZhtKSuuA(Pole.Positive))
		{
			qlShIqeuHSIRhnLpCXWfkIdpMdpx2.nonLocalizedPositiveDescriptiveName = qlShIqeuHSIRhnLpCXWfkIdpMdpx2.nonLocalizedDescriptiveName;
			if (nBOjCIRGYCWaaPRIUgpZVomTbPbx(Pole.Positive))
			{
				qlShIqeuHSIRhnLpCXWfkIdpMdpx2.nonLocalizedPositiveDescriptiveName = LocalizationManager.AppendToNameAxisPole(qlShIqeuHSIRhnLpCXWfkIdpMdpx2.nonLocalizedPositiveDescriptiveName, Pole.Positive);
			}
			qlShIqeuHSIRhnLpCXWfkIdpMdpx2.autoGeneratedValueFlags |= 2;
			XFdvjghozpLZsrvkWgkIQqPrTeDD(2);
		}
		if ((qlShIqeuHSIRhnLpCXWfkIdpMdpx2.autoGeneratedValueFlags & 4) == 0 && string.IsNullOrEmpty(qlShIqeuHSIRhnLpCXWfkIdpMdpx2.nonLocalizedNegativeDescriptiveName) && qWkcKzDmUwsWBagLentZGZhtKSuuA(Pole.Negative))
		{
			qlShIqeuHSIRhnLpCXWfkIdpMdpx2.nonLocalizedNegativeDescriptiveName = qlShIqeuHSIRhnLpCXWfkIdpMdpx2.nonLocalizedDescriptiveName;
			if (nBOjCIRGYCWaaPRIUgpZVomTbPbx(Pole.Negative))
			{
				qlShIqeuHSIRhnLpCXWfkIdpMdpx2.nonLocalizedNegativeDescriptiveName = LocalizationManager.AppendToNameAxisPole(qlShIqeuHSIRhnLpCXWfkIdpMdpx2.nonLocalizedNegativeDescriptiveName, Pole.Negative);
			}
			qlShIqeuHSIRhnLpCXWfkIdpMdpx2.autoGeneratedValueFlags |= 4;
			XFdvjghozpLZsrvkWgkIQqPrTeDD(4);
		}
	}

	protected virtual void JzQRTpncrkrCMaHzVbnmxkoFHCDI(JWyGUUsjYeTFhAbDNEOqGDnqBiaw P_0)
	{
		base.VnJKWKTgMlanDqXyFDmtdQZNvhXV(P_0);
		qlShIqeuHSIRhnLpCXWfkIdpMdpx qlShIqeuHSIRhnLpCXWfkIdpMdpx2 = zoHlOIjhqmdBxhlWfBbFhGYIwfBOb();
		if (qlShIqeuHSIRhnLpCXWfkIdpMdpx2 != null && ((uint)qlShIqeuHSIRhnLpCXWfkIdpMdpx2.autoGeneratedValueFlags & (uint)P_0) != 0)
		{
			if ((P_0 & JWyGUUsjYeTFhAbDNEOqGDnqBiaw.PositiveKey) != JWyGUUsjYeTFhAbDNEOqGDnqBiaw.None && (qlShIqeuHSIRhnLpCXWfkIdpMdpx2.autoGeneratedValueFlags & 8) != 0)
			{
				qlShIqeuHSIRhnLpCXWfkIdpMdpx2.positiveKey = null;
				XFdvjghozpLZsrvkWgkIQqPrTeDD(8);
				qlShIqeuHSIRhnLpCXWfkIdpMdpx2.autoGeneratedValueFlags &= -9;
			}
			if ((P_0 & JWyGUUsjYeTFhAbDNEOqGDnqBiaw.NegativeKey) != JWyGUUsjYeTFhAbDNEOqGDnqBiaw.None && (qlShIqeuHSIRhnLpCXWfkIdpMdpx2.autoGeneratedValueFlags & 0x10) != 0)
			{
				qlShIqeuHSIRhnLpCXWfkIdpMdpx2.negativeKey = null;
				XFdvjghozpLZsrvkWgkIQqPrTeDD(16);
				qlShIqeuHSIRhnLpCXWfkIdpMdpx2.autoGeneratedValueFlags &= -17;
			}
			if ((P_0 & JWyGUUsjYeTFhAbDNEOqGDnqBiaw.PositiveDescriptiveName) != JWyGUUsjYeTFhAbDNEOqGDnqBiaw.None && (qlShIqeuHSIRhnLpCXWfkIdpMdpx2.autoGeneratedValueFlags & 2) != 0)
			{
				qlShIqeuHSIRhnLpCXWfkIdpMdpx2.nonLocalizedPositiveDescriptiveName = null;
				XFdvjghozpLZsrvkWgkIQqPrTeDD(2);
				qlShIqeuHSIRhnLpCXWfkIdpMdpx2.autoGeneratedValueFlags &= -3;
			}
			if ((P_0 & JWyGUUsjYeTFhAbDNEOqGDnqBiaw.NegativeDescriptiveName) != JWyGUUsjYeTFhAbDNEOqGDnqBiaw.None && (qlShIqeuHSIRhnLpCXWfkIdpMdpx2.autoGeneratedValueFlags & 4) != 0)
			{
				qlShIqeuHSIRhnLpCXWfkIdpMdpx2.nonLocalizedNegativeDescriptiveName = null;
				XFdvjghozpLZsrvkWgkIQqPrTeDD(4);
				qlShIqeuHSIRhnLpCXWfkIdpMdpx2.autoGeneratedValueFlags &= -5;
			}
		}
	}

	protected virtual JWyGUUsjYeTFhAbDNEOqGDnqBiaw DoSqmqczHAeOxPMFgNwJxOXEiqcw(rCaSuhSWufhFquqeuhJWSlKJKnNk P_0)
	{
		JWyGUUsjYeTFhAbDNEOqGDnqBiaw jWyGUUsjYeTFhAbDNEOqGDnqBiaw = base.JNsVFFfxWgmUyGiKpTpjZfmbKYeB(P_0);
		if ((P_0 & rCaSuhSWufhFquqeuhJWSlKJKnNk.Keys) != rCaSuhSWufhFquqeuhJWSlKJKnNk.None)
		{
			jWyGUUsjYeTFhAbDNEOqGDnqBiaw |= (JWyGUUsjYeTFhAbDNEOqGDnqBiaw)24;
		}
		if ((P_0 & rCaSuhSWufhFquqeuhJWSlKJKnNk.Names) != rCaSuhSWufhFquqeuhJWSlKJKnNk.None)
		{
			jWyGUUsjYeTFhAbDNEOqGDnqBiaw |= (JWyGUUsjYeTFhAbDNEOqGDnqBiaw)6;
		}
		return jWyGUUsjYeTFhAbDNEOqGDnqBiaw;
	}

	protected qlShIqeuHSIRhnLpCXWfkIdpMdpx zoHlOIjhqmdBxhlWfBbFhGYIwfBOb()
	{
		return ezuBKWkznYBOSXRGpqYrdiJDWPLoA() as qlShIqeuHSIRhnLpCXWfkIdpMdpx;
	}

	protected virtual bool nBOjCIRGYCWaaPRIUgpZVomTbPbx(Pole P_0)
	{
		return base.wmxpDuCFjDeAdhOVfyzrBCCDpMkT switch
		{
			jZSMnsLXoBDMhquJQKqHviQNprmC.Axis => true, 
			jZSMnsLXoBDMhquJQKqHviQNprmC.Button => false, 
			_ => false, 
		};
	}

	protected virtual bool qWkcKzDmUwsWBagLentZGZhtKSuuA(Pole P_0)
	{
		return base.wmxpDuCFjDeAdhOVfyzrBCCDpMkT switch
		{
			jZSMnsLXoBDMhquJQKqHviQNprmC.Axis => true, 
			jZSMnsLXoBDMhquJQKqHviQNprmC.Button => P_0 switch
			{
				Pole.Positive => true, 
				Pole.Negative => false, 
				_ => false, 
			}, 
			_ => false, 
		};
	}

	protected virtual void eDYdYoaXcZOrahiwDqJasYuszpJR()
	{
		base.xwVhfgkgqJaUdXIocRzzcWsTaSSK();
		_ = vqTJyxMIVweNIWENvOzgHIrQkYCw;
		_ = FktASepfaNwtFksADsQexzwgRpBn;
	}

	protected virtual void wUoQilitoJQKfxSgOsglVkAOiGGdA()
	{
		NbDPXWlaZpogZcLLEYqCGRinHQWq();
		jriVMgSVfNhJUCcVjmEMYoZYjhGW(1, new ZfSdyTfpTJoTlWfkGbXUdYyHUehp
		{
			aATlyVMZfzbInxFRkgSBZcMommTT = 6
		});
		jriVMgSVfNhJUCcVjmEMYoZYjhGW(8, new ZfSdyTfpTJoTlWfkGbXUdYyHUehp(BvlXuXvUpfCJuelLFACNaekBqNQdb, 2));
		jriVMgSVfNhJUCcVjmEMYoZYjhGW(16, new ZfSdyTfpTJoTlWfkGbXUdYyHUehp(hqXDKRZmztXnmajyjtwrdWJeCdBt, 4));
		jriVMgSVfNhJUCcVjmEMYoZYjhGW(2, new ZfSdyTfpTJoTlWfkGbXUdYyHUehp
		{
			NmUmjFVjvsfeLKeuxcGWcsbAUoEx = BvlXuXvUpfCJuelLFACNaekBqNQdb
		});
		jriVMgSVfNhJUCcVjmEMYoZYjhGW(4, new ZfSdyTfpTJoTlWfkGbXUdYyHUehp
		{
			NmUmjFVjvsfeLKeuxcGWcsbAUoEx = hqXDKRZmztXnmajyjtwrdWJeCdBt
		});
	}
}
