using System;
using Rewired;
using Rewired.Internal.Glyphs;
using Rewired.Internal.Localization;

internal abstract class kaaeJTKKHtsGlcquaMLUrYwUlipt : xWpnnJnIauvtZWmfyACergtAcaup
{
	protected readonly KeyedGlyph bitcjDZNtppVXlNEnlxrxxUQTcYO;

	protected readonly KeyedGlyph wueFHBUBaZGqBuwvvXTopcEsaIXc;

	public abstract object jrBblZZCqzRkAPiflzkvfOhTIunO { get; }

	public abstract object zHbAvTjlSJogNXAtyecrFQjbMiIWA { get; }

	public abstract string ZLkWmYJqvhbNECBvzZwXJpCJJiGI { get; }

	public abstract string ASoxlpBpoLaEQFSlgwmOUEYNbFFFA { get; }

	protected kaaeJTKKHtsGlcquaMLUrYwUlipt(MJyJuisFiOmfspJhIRvXPkFSAPFT.jZSMnsLXoBDMhquJQKqHviQNprmC P_0, MJyJuisFiOmfspJhIRvXPkFSAPFT.GtxbKiHSwksUKuQYeAEqHnCDMtFmA P_1)
		: base(P_0, P_1)
	{
		bitcjDZNtppVXlNEnlxrxxUQTcYO = new KeyedGlyph();
		wueFHBUBaZGqBuwvvXTopcEsaIXc = new KeyedGlyph();
	}

	protected kaaeJTKKHtsGlcquaMLUrYwUlipt(ciioobTlGUakXNuXSZWsSBbYJisy P_0, MJyJuisFiOmfspJhIRvXPkFSAPFT.jZSMnsLXoBDMhquJQKqHviQNprmC P_1, MJyJuisFiOmfspJhIRvXPkFSAPFT.GtxbKiHSwksUKuQYeAEqHnCDMtFmA P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
		bitcjDZNtppVXlNEnlxrxxUQTcYO = new KeyedGlyph();
		wueFHBUBaZGqBuwvvXTopcEsaIXc = new KeyedGlyph();
	}

	protected virtual void tgUpMTNNZTHclAgMNRCSEWSdkWAB()
	{
		pMDkYhpVRrVbVWDhBkHpXIvtpTCL();
	}

	public virtual void vccIoFhkaotrzbzWciZetkfLIeGOA(ciioobTlGUakXNuXSZWsSBbYJisy P_0)
	{
		NgvSmCyfgtkxZQxmcuFMzgwRamCM(P_0);
	}

	public virtual void xJtRpAeOKKpbZliMuhBRbKkfyuQAA(IkNokIafnDXAZobQNzBQDEduXYfJ P_0)
	{
		base.NgvSmCyfgtkxZQxmcuFMzgwRamCM(P_0);
		if (!(P_0 is ciioobTlGUakXNuXSZWsSBbYJisy))
		{
			throw new ArgumentException("value must implement " + typeof(ciioobTlGUakXNuXSZWsSBbYJisy));
		}
	}

	public virtual void zHXfFjXUEGURDUhxoiiCtPBWEDtcA()
	{
		RUIfcOfJipXoTKmSBTPqJudFaXATA();
		bitcjDZNtppVXlNEnlxrxxUQTcYO.Clear();
		wueFHBUBaZGqBuwvvXTopcEsaIXc.Clear();
	}

	public void fcKMuiFHvwcIrJQUACFoKHtwJzoq()
	{
		bitcjDZNtppVXlNEnlxrxxUQTcYO.Clear();
		sMNNSwAEQxubPCfZLNJgsdCBkCzO(MJyJuisFiOmfspJhIRvXPkFSAPFT.rCaSuhSWufhFquqeuhJWSlKJKnNk.Keys);
	}

	public void igTfOkwJZUlNPsKbBfEYWqAlDANdA()
	{
		wueFHBUBaZGqBuwvvXTopcEsaIXc.Clear();
		sMNNSwAEQxubPCfZLNJgsdCBkCzO(MJyJuisFiOmfspJhIRvXPkFSAPFT.rCaSuhSWufhFquqeuhJWSlKJKnNk.Keys);
	}

	public virtual bool FjxemHlKlEaSdBNpaHabdWBCVrSxB(CcGgbpntamtnacmabegPksrcgakT P_0)
	{
		if (!(P_0 is kaaeJTKKHtsGlcquaMLUrYwUlipt kaaeJTKKHtsGlcquaMLUrYwUlipt2))
		{
			return false;
		}
		if (!PoQfHuGkWfdIDeuihNPuAbBlEUYMb(P_0))
		{
			return false;
		}
		ciioobTlGUakXNuXSZWsSBbYJisy ciioobTlGUakXNuXSZWsSBbYJisy2 = RNxVgsrwtFaUeFItAnzrhCcqMnZe();
		ciioobTlGUakXNuXSZWsSBbYJisy ciioobTlGUakXNuXSZWsSBbYJisy3 = kaaeJTKKHtsGlcquaMLUrYwUlipt2.RNxVgsrwtFaUeFItAnzrhCcqMnZe();
		if (ciioobTlGUakXNuXSZWsSBbYJisy2 == null != (ciioobTlGUakXNuXSZWsSBbYJisy3 == null))
		{
			return false;
		}
		if (ciioobTlGUakXNuXSZWsSBbYJisy2 != null && (!string.Equals(ciioobTlGUakXNuXSZWsSBbYJisy2.positiveKey, ciioobTlGUakXNuXSZWsSBbYJisy3.positiveKey, StringComparison.Ordinal) || !string.Equals(ciioobTlGUakXNuXSZWsSBbYJisy2.negativeKey, ciioobTlGUakXNuXSZWsSBbYJisy3.negativeKey, StringComparison.Ordinal)))
		{
			return false;
		}
		return true;
	}

	protected virtual void GWJCVZgDKgkmuczhgvMwsGMZEULsA()
	{
		piSBZMsrTDaJENouqIrvCmoZCzaF();
		bitcjDZNtppVXlNEnlxrxxUQTcYO.Clear();
		wueFHBUBaZGqBuwvvXTopcEsaIXc.Clear();
	}

	protected virtual void erQvGkPEKePwcpQCHtkPfhQTeSBIA(MJyJuisFiOmfspJhIRvXPkFSAPFT.rCaSuhSWufhFquqeuhJWSlKJKnNk P_0)
	{
		base.sMNNSwAEQxubPCfZLNJgsdCBkCzO(P_0);
		ciioobTlGUakXNuXSZWsSBbYJisy ciioobTlGUakXNuXSZWsSBbYJisy2 = RNxVgsrwtFaUeFItAnzrhCcqMnZe();
		if (ciioobTlGUakXNuXSZWsSBbYJisy2 == null || string.IsNullOrEmpty(ciioobTlGUakXNuXSZWsSBbYJisy2.key))
		{
			return;
		}
		if ((ciioobTlGUakXNuXSZWsSBbYJisy2.autoGeneratedValueFlags & 8) == 0 && string.IsNullOrEmpty(ciioobTlGUakXNuXSZWsSBbYJisy2.positiveKey) && wPoavVhbRYaWBmXNswJvibJVwsxoA(Pole.Positive))
		{
			ciioobTlGUakXNuXSZWsSBbYJisy2.positiveKey = ciioobTlGUakXNuXSZWsSBbYJisy2.key;
			if (UDVaysJTnxPhotOwNwRxEgkxYWfC(Pole.Positive))
			{
				ciioobTlGUakXNuXSZWsSBbYJisy2.positiveKey = LocalizationManager.AppendToKeyAxisPole(ciioobTlGUakXNuXSZWsSBbYJisy2.positiveKey, Pole.Positive);
			}
			ciioobTlGUakXNuXSZWsSBbYJisy2.autoGeneratedValueFlags |= 8;
			ZijjNbcjtNDoOooGWeXrwQkaSDnl(8);
		}
		if ((ciioobTlGUakXNuXSZWsSBbYJisy2.autoGeneratedValueFlags & 0x10) == 0 && string.IsNullOrEmpty(ciioobTlGUakXNuXSZWsSBbYJisy2.negativeKey) && wPoavVhbRYaWBmXNswJvibJVwsxoA(Pole.Negative))
		{
			ciioobTlGUakXNuXSZWsSBbYJisy2.negativeKey = ciioobTlGUakXNuXSZWsSBbYJisy2.key;
			if (UDVaysJTnxPhotOwNwRxEgkxYWfC(Pole.Negative))
			{
				ciioobTlGUakXNuXSZWsSBbYJisy2.negativeKey = LocalizationManager.AppendToKeyAxisPole(ciioobTlGUakXNuXSZWsSBbYJisy2.negativeKey, Pole.Negative);
			}
			ciioobTlGUakXNuXSZWsSBbYJisy2.autoGeneratedValueFlags |= 16;
			ZijjNbcjtNDoOooGWeXrwQkaSDnl(16);
		}
	}

	protected virtual void GUEIfqsMeWduHjXrxIflojTHfCggA(MJyJuisFiOmfspJhIRvXPkFSAPFT.JWyGUUsjYeTFhAbDNEOqGDnqBiaw P_0)
	{
		base.uVDhkShHjzvWWRUtucRZzvqOrakJA(P_0);
		ciioobTlGUakXNuXSZWsSBbYJisy ciioobTlGUakXNuXSZWsSBbYJisy2 = RNxVgsrwtFaUeFItAnzrhCcqMnZe();
		if (ciioobTlGUakXNuXSZWsSBbYJisy2 != null && ((uint)ciioobTlGUakXNuXSZWsSBbYJisy2.autoGeneratedValueFlags & (uint)P_0) != 0)
		{
			if ((P_0 & MJyJuisFiOmfspJhIRvXPkFSAPFT.JWyGUUsjYeTFhAbDNEOqGDnqBiaw.PositiveKey) != MJyJuisFiOmfspJhIRvXPkFSAPFT.JWyGUUsjYeTFhAbDNEOqGDnqBiaw.None && (ciioobTlGUakXNuXSZWsSBbYJisy2.autoGeneratedValueFlags & 8) != 0)
			{
				ciioobTlGUakXNuXSZWsSBbYJisy2.positiveKey = null;
				ZijjNbcjtNDoOooGWeXrwQkaSDnl(8);
				ciioobTlGUakXNuXSZWsSBbYJisy2.autoGeneratedValueFlags &= -9;
			}
			if ((P_0 & MJyJuisFiOmfspJhIRvXPkFSAPFT.JWyGUUsjYeTFhAbDNEOqGDnqBiaw.NegativeKey) != MJyJuisFiOmfspJhIRvXPkFSAPFT.JWyGUUsjYeTFhAbDNEOqGDnqBiaw.None && (ciioobTlGUakXNuXSZWsSBbYJisy2.autoGeneratedValueFlags & 0x10) != 0)
			{
				ciioobTlGUakXNuXSZWsSBbYJisy2.negativeKey = null;
				ZijjNbcjtNDoOooGWeXrwQkaSDnl(16);
				ciioobTlGUakXNuXSZWsSBbYJisy2.autoGeneratedValueFlags &= -17;
			}
		}
	}

	protected virtual MJyJuisFiOmfspJhIRvXPkFSAPFT.JWyGUUsjYeTFhAbDNEOqGDnqBiaw jEpOzxgpBChVWtbrSXnHzdmqduHD(MJyJuisFiOmfspJhIRvXPkFSAPFT.rCaSuhSWufhFquqeuhJWSlKJKnNk P_0)
	{
		MJyJuisFiOmfspJhIRvXPkFSAPFT.JWyGUUsjYeTFhAbDNEOqGDnqBiaw jWyGUUsjYeTFhAbDNEOqGDnqBiaw = base.XNeiYAxQauwwNEjiyCIdxKnteSIO(P_0);
		if ((P_0 & MJyJuisFiOmfspJhIRvXPkFSAPFT.rCaSuhSWufhFquqeuhJWSlKJKnNk.Keys) != MJyJuisFiOmfspJhIRvXPkFSAPFT.rCaSuhSWufhFquqeuhJWSlKJKnNk.None)
		{
			jWyGUUsjYeTFhAbDNEOqGDnqBiaw |= (MJyJuisFiOmfspJhIRvXPkFSAPFT.JWyGUUsjYeTFhAbDNEOqGDnqBiaw)24;
		}
		return jWyGUUsjYeTFhAbDNEOqGDnqBiaw;
	}

	protected ciioobTlGUakXNuXSZWsSBbYJisy RNxVgsrwtFaUeFItAnzrhCcqMnZe()
	{
		return fReLfzPhSCfLTAzobjWfyqjTDxEt() as ciioobTlGUakXNuXSZWsSBbYJisy;
	}

	protected virtual bool UDVaysJTnxPhotOwNwRxEgkxYWfC(Pole P_0)
	{
		return base.fKdZAaHFMHQcMidfZwsSpPaBghlH switch
		{
			MJyJuisFiOmfspJhIRvXPkFSAPFT.jZSMnsLXoBDMhquJQKqHviQNprmC.Axis => true, 
			MJyJuisFiOmfspJhIRvXPkFSAPFT.jZSMnsLXoBDMhquJQKqHviQNprmC.Button => false, 
			_ => false, 
		};
	}

	protected virtual bool wPoavVhbRYaWBmXNswJvibJVwsxoA(Pole P_0)
	{
		return base.fKdZAaHFMHQcMidfZwsSpPaBghlH switch
		{
			MJyJuisFiOmfspJhIRvXPkFSAPFT.jZSMnsLXoBDMhquJQKqHviQNprmC.Axis => true, 
			MJyJuisFiOmfspJhIRvXPkFSAPFT.jZSMnsLXoBDMhquJQKqHviQNprmC.Button => P_0 switch
			{
				Pole.Positive => true, 
				Pole.Negative => false, 
				_ => false, 
			}, 
			_ => false, 
		};
	}

	protected virtual void MNrcKwLLnMZejSlahlUeQSofCfOQ()
	{
		base.oRVHAZrlknBMDEcGKbVwMQQatoQe();
		_ = jrBblZZCqzRkAPiflzkvfOhTIunO;
		_ = zHbAvTjlSJogNXAtyecrFQjbMiIWA;
	}

	protected virtual void vEiiyTKFMvSCwvrLvJoWpVExyptG()
	{
		MDBuurQPSiKEOWHlVBUsThHIaTKbA();
		yDRfdccunXmqJdleFupgSUzbJDcMc(8, new SngFPGiFSNRQDdUtntlDROkQQRttA
		{
			ymPAbTHTpGfSWXdoAUFzwrRxqghR = bitcjDZNtppVXlNEnlxrxxUQTcYO
		});
		yDRfdccunXmqJdleFupgSUzbJDcMc(16, new SngFPGiFSNRQDdUtntlDROkQQRttA
		{
			ymPAbTHTpGfSWXdoAUFzwrRxqghR = wueFHBUBaZGqBuwvvXTopcEsaIXc
		});
	}
}
