<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PhotonNetworking</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>8.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Kitchen.Networking">
      <HintPath>..\..\Assemblies\Kitchen.Networking.dll</HintPath>
    </Reference>
    <Reference Include="PlatformSettings">
      <HintPath>..\..\Assemblies\PlatformSettings.dll</HintPath>
    </Reference>
    <Reference Include="PhotonRealtime">
      <HintPath>..\..\Assemblies\PhotonRealtime.dll</HintPath>
    </Reference>
    <Reference Include="Utility">
      <HintPath>..\..\Assemblies\Utility.dll</HintPath>
    </Reference>
    <Reference Include="Photon3Unity3D">
      <HintPath>..\..\Assemblies\Photon3Unity3D.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="Sirenix.Utilities">
      <HintPath>..\..\Assemblies\Sirenix.Utilities.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="websocket-sharp">
      <HintPath>..\..\Assemblies\websocket-sharp.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>