using System.Collections.Generic;
using DG.Tweening;
using NaughtyAttributes;
using Presentation.FactoryFloor.ParticleSystemPool;
using UnityEngine;
using UnityEngine.VFX;

namespace Presentation.FactoryFloor.FactoryObjectViews.Buildings
{
	public class BuildingCompletionEffect : MonoBehaviour
	{
		private enum ScalingAxis
		{
			X = 0,
			Y = 1,
			Z = 2
		}

		[SerializeField]
		private MeshRenderer _hologramBuilding;

		[SerializeField]
		private MeshRenderer _transitionBuilding;

		[SerializeField]
		private GameObject _finishedBuilding;

		[SerializeField]
		private ScalingAxis _scalingAxis = ScalingAxis.Z;

		[SerializeField]
		private List<MeshRenderer> _props;

		[SerializeField]
		private ParticleSystemPoolLocator _particleSystemPoolLocator;

		[SerializeField]
		private VisualEffect _customCompletionEffect;

		[Space]
		[InfoBox("Custom colliders currently only works for single-floor buildings (Monuments)", EInfoBoxType.Normal)]
		[SerializeField]
		private bool _overrideAutoGeneratedBuildingColliders;

		[SerializeField]
		[EnableIf("_overrideAutoGeneratedBuildingColliders")]
		private List<BoxCollider> _colliders;

		private MeshFilter _transitionMeshF;

		private static readonly int StartTime = Shader.PropertyToID("_startTime");

		private static readonly int BoundsYSize = Shader.PropertyToID("_boundsYSize");

		private static readonly int AnimationTime = Shader.PropertyToID("_animationTime");

		private static readonly int MainTexture = Shader.PropertyToID("_MainTexture");

		private static readonly int ValidPlacement = Shader.PropertyToID("_validPlacement");

		private bool _showingPolishedVersion;

		private Vector3 _boundsSize;

		public Vector3 BoundsSize
		{
			get
			{
				if (!(_boundsSize == Vector3.zero))
				{
					return _boundsSize;
				}
				return _hologramBuilding.bounds.size;
			}
		}

		public bool OverrideColliders => _overrideAutoGeneratedBuildingColliders;

		public List<BoxCollider> Colliders => _colliders;

		public void Init()
		{
			_transitionMeshF = _transitionBuilding.GetComponent<MeshFilter>();
			_showingPolishedVersion = false;
			_boundsSize = _hologramBuilding.bounds.size;
			SetValid(isValid: true);
		}

		public void ShowHologram()
		{
			_hologramBuilding.gameObject.SetActive(value: true);
			_transitionBuilding.gameObject.SetActive(value: false);
			_finishedBuilding.gameObject.SetActive(value: false);
			foreach (MeshRenderer prop in _props)
			{
				prop.gameObject.SetActive(value: false);
			}
		}

		public void ShowPolished()
		{
			if (_showingPolishedVersion)
			{
				return;
			}
			_showingPolishedVersion = true;
			Object.Destroy(_hologramBuilding.gameObject);
			Object.Destroy(_transitionBuilding.gameObject);
			_finishedBuilding.gameObject.SetActive(value: true);
			foreach (MeshRenderer prop in _props)
			{
				prop.gameObject.SetActive(value: true);
			}
		}

		public void StartTransition(float animTime)
		{
			_transitionBuilding.gameObject.SetActive(value: true);
			float y = _transitionMeshF.sharedMesh.bounds.size.y;
			Material[] materials = _hologramBuilding.materials;
			foreach (Material obj in materials)
			{
				obj.SetFloat(BoundsYSize, y);
				obj.SetFloat(AnimationTime, animTime);
				obj.SetFloat(StartTime, Time.time);
			}
			MeshRenderer component = _finishedBuilding.GetComponent<MeshRenderer>();
			Texture value = (component.sharedMaterial.HasTexture(MainTexture) ? component.sharedMaterial.GetTexture(MainTexture) : null);
			materials = _transitionBuilding.materials;
			foreach (Material obj2 in materials)
			{
				obj2.SetFloat(BoundsYSize, y);
				obj2.SetFloat(AnimationTime, animTime);
				obj2.SetFloat(StartTime, Time.time);
				obj2.SetTexture(MainTexture, value);
			}
		}

		public void StartPropsTransition(float animTime)
		{
			Vector3 vector = Vector3.up * (_boundsSize.y / 2f);
			if (_customCompletionEffect != null)
			{
				_customCompletionEffect.Play();
			}
			else
			{
				_particleSystemPoolLocator.Pool.PlayBuildingCompletionVFX(base.transform.position + vector, null);
			}
			ShowPolished();
			ScaleProps(animTime);
		}

		private void ScaleProps(float animTime)
		{
			switch (_scalingAxis)
			{
			case ScalingAxis.X:
			{
				foreach (MeshRenderer prop in _props)
				{
					Vector3 localScale3 = prop.transform.localScale;
					float x = localScale3.x;
					localScale3.x = 0.001f;
					prop.transform.localScale = localScale3;
					prop.transform.DOScaleX(x, animTime);
				}
				break;
			}
			case ScalingAxis.Y:
			{
				foreach (MeshRenderer prop2 in _props)
				{
					Vector3 localScale2 = prop2.transform.localScale;
					float y = localScale2.y;
					localScale2.y = 0.001f;
					prop2.transform.localScale = localScale2;
					prop2.transform.DOScaleY(y, animTime);
				}
				break;
			}
			case ScalingAxis.Z:
			{
				foreach (MeshRenderer prop3 in _props)
				{
					Vector3 localScale = prop3.transform.localScale;
					float z = localScale.z;
					localScale.z = 0.001f;
					prop3.transform.localScale = localScale;
					prop3.transform.DOScaleZ(z, animTime);
				}
				break;
			}
			}
		}

		public void SetValid(bool isValid)
		{
			Material[] materials = _hologramBuilding.materials;
			for (int i = 0; i < materials.Length; i++)
			{
				materials[i].SetFloat(ValidPlacement, isValid ? 1 : 0);
			}
		}
	}
}
