namespace FuryStudios.FurySDK
{
	public enum Language
	{
		Afrikaans = 0,
		Arabic = 1,
		Basque = 2,
		Belarusian = 3,
		Bulgarian = 4,
		Catalan = 5,
		Chinese = 6,
		Czech = 7,
		Danish = 8,
		Dutch = 9,
		English = 10,
		Estonian = 11,
		Faroese = 12,
		Finnish = 13,
		French = 14,
		German = 15,
		Greek = 16,
		Hebrew = 17,
		Icelandic = 18,
		Indonesian = 19,
		Italian = 20,
		Japanese = 21,
		Korean = 22,
		Latvian = 23,
		Lithuanian = 24,
		Norwegian = 25,
		Polish = 26,
		Portuguese = 27,
		BrazilianPortuguese = 28,
		Romanian = 29,
		Russian = 30,
		SerboCroatian = 31,
		Slovak = 32,
		Slovenian = 33,
		Spanish = 34,
		SpanishLA = 35,
		Swedish = 36,
		Thai = 37,
		Turkish = 38,
		Ukrainian = 39,
		Vietnamese = 40,
		ChineseSimplified = 41,
		ChineseTraditional = 42,
		Hungarian = 43,
		Unknown = 44
	}
}
