namespace Loxodon.Framework.Views
{
	public enum WindowState
	{
		NONE = 0,
		CREATE_BEGIN = 1,
		CREATE_END = 2,
		ENTER_ANIMATION_BEGIN = 3,
		VISIBLE = 4,
		ENTER_ANIMATION_END = 5,
		ACTIVATION_ANIMATION_BEGIN = 6,
		ACTIVATED = 7,
		ACTIVATION_ANIMATION_END = 8,
		PASSIVATION_ANIMATION_BEGIN = 9,
		PASSIVATED = 10,
		PASSIVATION_ANIMATION_END = 11,
		EXIT_ANIMATION_BEGIN = 12,
		INVISIBLE = 13,
		EXIT_ANIMATION_END = 14,
		DISMISS_BEGIN = 15,
		DISMISS_END = 16
	}
}
