namespace PlayerCommand
{
	public enum Command : byte
	{
		Unstuck = 0,
		SetPlayerHealth = 1,
		CreateAndDropItem = 2,
		CreateMapUI = 3,
		CreateEntityForStreamIntegration = 4,
		CreateMortarEntityForStreamIntegration = 5,
		DestroyAllEntitiesForStreamIntegration = 6,
		RemoveLoginImmunity = 7,
		AddOrRefreshCondition = 8,
		CollectSoul = 9,
		EnableSuperManForStreamIntegration = 10,
		UnlockSouls = 11,
		ResetSkillTalentTree = 12,
		SetSkillTalentCondition = 13,
		LowerTheGreatWall = 14,
		MapPing = 15,
		ResetMerchantHasNewItems = 16,
		PlayMusicSheet = 17,
		SetName = 18,
		ActivateTerminal = 19,
		SetDescription = 20,
		SetPlayerManaForStreamIntegration = 21,
		SetPlayerImmuneToDamage = 22,
		SetPlayerState = 23,
		AddSkillValue = 24,
		SetSkillValue = 25,
		SetSquashBugs = 26,
		SetAuthor = 27,
		UnlockCurrentState = 28,
		CreateItem = 29,
		SetGodMode = 30,
		SetWorldLabelVisibility = 31,
		SetCattleBreedable = 32,
		Message = 33,
		ServerSavedNotification = 34,
		CompleteQuest = 35,
		AchievementUnlocked = 36,
		MarkEnemyAsKilled = 37
	}
}
