<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SourceGeneration</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\..\Assemblies\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\..\Assemblies\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Localization">
      <HintPath>..\..\Assemblies\Unity.Localization.dll</HintPath>
    </Reference>
    <Reference Include="UniTask">
      <HintPath>..\..\Assemblies\UniTask.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ResourceManager">
      <HintPath>..\..\Assemblies\Unity.ResourceManager.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Addressables">
      <HintPath>..\..\Assemblies\Unity.Addressables.dll</HintPath>
    </Reference>
    <Reference Include="ZLinq">
      <HintPath>..\..\Assemblies\ZLinq.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.OdinInspector.Attributes">
      <HintPath>..\..\Assemblies\Sirenix.OdinInspector.Attributes.dll</HintPath>
    </Reference>
    <Reference Include="R3">
      <HintPath>..\..\Assemblies\R3.dll</HintPath>
    </Reference>
    <Reference Include="UniTask.Addressables">
      <HintPath>..\..\Assemblies\UniTask.Addressables.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>