<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Outlines.Converters</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="PugConversion">
      <HintPath>..\..\Assemblies\PugConversion.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Entities">
      <HintPath>..\..\Assemblies\Unity.Entities.dll</HintPath>
    </Reference>
    <Reference Include="Interaction.Components">
      <HintPath>..\..\Assemblies\Interaction.Components.dll</HintPath>
    </Reference>
    <Reference Include="Pug.ECS.Components">
      <HintPath>..\..\Assemblies\Pug.ECS.Components.dll</HintPath>
    </Reference>
    <Reference Include="Outlines.Components">
      <HintPath>..\..\Assemblies\Outlines.Components.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>