using System;
using M4.Session;
using UnityEngine;

namespace PajamaLlama.Flotsam.Narrative
{
	[Serializable]
	public class ScenarioTileProvider
	{
		[SerializeReference]
		[InstantiateSerializeReference]
		private IScenarioTriggerableCondition[] _conditions;

		[SerializeField]
		private WorldTileProviderBase _provider;

		[SerializeField]
		private bool _isFallback;

		[SerializeField]
		[ConditionalHide("_isFallback", true)]
		private bool _debugRunOnly;

		public bool TryGetWorldTile(out WorldTile worldTile, global::World world, ILandmarkPicker landmarkPicker)
		{
			worldTile = null;
			if (_debugRunOnly && !Session.Profile.ActiveRun.IsDebugRun)
			{
				return false;
			}
			IScenarioTriggerableCondition[] conditions = _conditions;
			for (int i = 0; i < conditions.Length; i++)
			{
				if (!conditions[i].IsMet())
				{
					return false;
				}
			}
			if (_isFallback)
			{
				if (Session.Profile.ActiveRun.IsDebugRun)
				{
					Debug.LogError("The next world tile was generated by a fallback ScenarioTileProvider");
				}
				else
				{
					Debug.LogException(new Exception("The next world tile was generated by a fallback ScenarioTileProvider"));
				}
			}
			return _provider.TryGetNextWorldTile(out worldTile, world, landmarkPicker);
		}
	}
}
