<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Coherence.RSL</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Coherence.ReplicationServer">
      <HintPath>..\..\Assemblies\Coherence.ReplicationServer.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.RSL.Extensions">
      <HintPath>..\..\Assemblies\Coherence.RSL.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Common">
      <HintPath>..\..\Assemblies\Coherence.Common.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Log">
      <HintPath>..\..\Assemblies\Coherence.Log.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Transport">
      <HintPath>..\..\Assemblies\Coherence.Transport.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.RSL.Transport">
      <HintPath>..\..\Assemblies\Coherence.RSL.Transport.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.RSL.Brisk">
      <HintPath>..\..\Assemblies\Coherence.RSL.Brisk.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.RSL.ReplicationManager">
      <HintPath>..\..\Assemblies\Coherence.RSL.ReplicationManager.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>