internal class ykBoQTtVMmAKQpPqgoapgNirorrw : RAkQYiWtBKQzQUREhAKdwhDIibCx
{
	protected readonly qYCbTvVNMjCiGkuYIMrPMULiLWHZA pwigtFabIkCLcxHaSSTscCEdzbIkb;

	private readonly string mGGJAfrigiShhfHXKfbWXjENlwyA;

	private readonly string emsyrcSvhArlnfiXZLXgtLYHVPEC;

	private int gMEaihEHUFWhrEXeRkjIUKEEFFBh;

	public qYCbTvVNMjCiGkuYIMrPMULiLWHZA HHKISKLfNKDwltmIgElfBmklLsVT => null;

	string RAkQYiWtBKQzQUREhAKdwhDIibCx.keyCategory => null;

	string RAkQYiWtBKQzQUREhAKdwhDIibCx.key => null;

	int RAkQYiWtBKQzQUREhAKdwhDIibCx.autoGeneratedValueFlags
	{
		get
		{
			return 0;
		}
		set
		{
		}
	}

	public string keyCategory => null;

	public string key => null;

	public ykBoQTtVMmAKQpPqgoapgNirorrw(qYCbTvVNMjCiGkuYIMrPMULiLWHZA P_0, string P_1, string P_2)
	{
	}

	public virtual bool AVxcjpQjLRdxwHPabajkEOlehSog(ykBoQTtVMmAKQpPqgoapgNirorrw P_0)
	{
		return false;
	}
}
