namespace TwitchLib.Api.Core.Enums
{
	public enum AuthScopes
	{
		Any = 0,
		Channel_Check_Subscription = 1,
		Channel_Commercial = 2,
		Channel_Editor = 3,
		Channel_Feed_Edit = 4,
		Channel_Feed_Read = 5,
		Channel_Read = 6,
		Channel_Stream = 7,
		Channel_Subscriptions = 8,
		Chat_Login = 9,
		Collections_Edit = 10,
		Communities_Edit = 11,
		Communities_Moderate = 12,
		User_Blocks_Edit = 13,
		User_Blocks_Read = 14,
		User_Follows_Edit = 15,
		User_Read = 16,
		User_Subscriptions = 17,
		Viewing_Activity_Read = 18,
		OpenId = 19,
		Helix_User_Edit_Broadcast = 20,
		Helix_Analytics_Read_Extensions = 21,
		Helix_Analytics_Read_Games = 22,
		Helix_Bits_Read = 23,
		Helix_Channel_Edit_Commercial = 24,
		Helix_Channel_Manage_Broadcast = 25,
		Helix_Channel_Manage_Extensions = 26,
		Helix_Channel_Manage_Redemptions = 27,
		Helix_Channel_Read_Hype_Train = 28,
		Helix_Channel_Read_Redemptions = 29,
		Helix_Channel_Read_Stream_Key = 30,
		Helix_Channel_Read_Subscriptions = 31,
		Helix_Clips_Edit = 32,
		Helix_Moderation_Read = 33,
		Helix_User_Edit = 34,
		Helix_User_Edit_Follows = 35,
		Helix_User_Read_Broadcast = 36,
		Helix_User_Read_Email = 37,
		Helix_Channel_Read_Editors = 38,
		Helix_Channel_Manage_Videos = 39,
		Helix_User_Read_BlockedUsers = 40,
		Helix_User_Manage_BlockedUsers = 41,
		Helix_User_Read_Subscriptions = 42,
		Helix_Channel_Manage_Polls = 43,
		Helix_Channel_Manage_Predictions = 44,
		Helix_Channel_Read_Polls = 45,
		Helix_Channel_Read_Predictions = 46,
		Helix_Channel_Moderator_Manage_Automod = 47,
		None = 48
	}
}
