<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Doozy</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="DOTween">
      <HintPath>..\..\VampSurv\DOTween.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\..\VampSurv\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\..\VampSurv\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>..\..\VampSurv\UnityEngine.JSONSerializeModule.dll</HintPath>
    </Reference>
    <Reference Include="DOTween.Modules">
      <HintPath>..\..\VampSurv\DOTween.Modules.dll</HintPath>
    </Reference>
    <ProjectReference Include="..\UnityEngine.CoreModule\UnityEngine.CoreModule.csproj" />
    <ProjectReference Include="..\UnityEngine.UI\UnityEngine.UI.csproj" />
    <ProjectReference Include="..\UnityEngine.UIModule\UnityEngine.UIModule.csproj" />
    <ProjectReference Include="..\UnityEngine.ParticleSystemModule\UnityEngine.ParticleSystemModule.csproj" />
    <ProjectReference Include="..\UnityEngine.InputLegacyModule\UnityEngine.InputLegacyModule.csproj" />
    <ProjectReference Include="..\UnityEngine.AudioModule\UnityEngine.AudioModule.csproj" />
    <ProjectReference Include="..\System.Core\System.Core.csproj" />
    <ProjectReference Include="..\DDebug\DDebug.csproj" />
  </ItemGroup>
</Project>