namespace VampireSurvivors.UI
{
	public enum UIState
	{
		DEBUG = 0,
		ADVANCED_SETTINGS = 1,
		NOT_LOGGED_IN_HOME = 2,
		UNVERIFIED_HOME = 3,
		LOGGED_IN_HOME = 4,
		LOGIN = 5,
		REGISTER = 6,
		MANAGE_DATA = 7,
		MANAGE_ACCOUNT = 8,
		MANAGE_SAVE_DATA = 9,
		MANAGE_LOAD_DATA = 10,
		ACCOUNT_RECOVERY = 11,
		PRIVACY_POLICY_GATE = 12,
		PRIVACY_POLICY_SCROLLER = 13,
		AGE_GATE = 14,
		HELP = 15,
		ERROR = 16
	}
}
