<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>R3</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="R3.LICENSE" />
    <EmbeddedResource Include="R3.LICENSE" LogicalName="R3.LICENSE" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.ComponentModel.Annotations">
      <HintPath>..\..\Assemblies\System.ComponentModel.Annotations.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Bcl.TimeProvider">
      <HintPath>..\..\Assemblies\Microsoft.Bcl.TimeProvider.dll</HintPath>
    </Reference>
    <Reference Include="System.Threading.Channels">
      <HintPath>..\..\Assemblies\System.Threading.Channels.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime.CompilerServices.Unsafe">
      <HintPath>..\..\Assemblies\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>