using System;
using System.Collections.Generic;
using System.Linq;
using ModApi.Craft.Parts;
using ModApi.Craft.Program.Craft;
using ModApi.Flight.GameView;
using ModApi.Ui.Inspector;
using UnityEngine;

namespace ModApi.Craft.Program
{
	public class CraftProperties
	{
		private static List<CraftProperty> _properties;

		static CraftProperties()
		{
			_properties = new List<CraftProperty>();
			AddProperty("Orbit", "Apoapsis", "Orbit.Apoapsis", ListItemInfoType.Number, "The altitude of the apoapsis above the planet's radius in meters.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetDoubleValue(c.Craft.Data.Orbit.ApoapsisAltitude, allowNegative: false);
			};
			AddProperty("Orbit", "Periapsis", "Orbit.Periapsis", ListItemInfoType.Number, "The altitude of the periapsis above the planet's radius in meters.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetDoubleValue(c.Craft.Data.Orbit.PeriapsisAltitude, allowNegative: false);
			};
			AddProperty("Orbit", "Time To Apoapsis", "Orbit.TimeToApoapsis", ListItemInfoType.Number, "The time remaining to the apoapsis in seconds.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetDoubleValue(c.Craft.Data.Orbit.ApoapsisTime, allowNegative: false);
			};
			AddProperty("Orbit", "Time To Periapsis", "Orbit.TimeToPeriapsis", ListItemInfoType.Number, "The time periapsis to the apoapsis in seconds.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetDoubleValue(c.Craft.Data.Orbit.PeriapsisTime, allowNegative: false);
			};
			AddProperty("Orbit", "Eccentricity", "Orbit.Eccentricity", ListItemInfoType.Number, "The eccentricity of the orbit.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetDoubleValue(c.Craft.Data.Orbit.Eccentricity, allowNegative: false);
			};
			AddProperty("Orbit", "Inclination", "Orbit.Inclination", ListItemInfoType.Radians, "The inclination of the orbit in radians.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetDoubleValue(c.Craft.Data.Orbit.Inclination);
			};
			AddProperty("Orbit", "Period", "Orbit.Period", ListItemInfoType.Number, "The period of the orbit in seconds.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetDoubleValue(c.Craft.Data.Orbit.Period, allowNegative: false);
			};
			AddProperty("Atmosphere", "Air Density", "Atmosphere.AirDensity", ListItemInfoType.Number, "The air density of the atmosphere at the craft's current position in kg/m3.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.AtmosphereSample.AirDensity;
			};
			AddProperty("Atmosphere", "Air Pressure", "Atmosphere.AirPressure", ListItemInfoType.Number, "The air pressure of the atmosphere at the craft's current position in Pa.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.AtmosphereSample.AirPressure;
			};
			AddProperty("Atmosphere", "Speed of Sound", "Atmosphere.SpeedOfSound", ListItemInfoType.Number, "The speed of sound at the craft's current position in m/s.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.AtmosphereSample.SpeedOfSound;
			};
			AddProperty("Atmosphere", "Temperature", "Atmosphere.Temperature", ListItemInfoType.Number, "The temperature at the craft's current position in K.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.AtmosphereSample.Temperature;
			};
			AddProperty("Altitude", "AGL", "Altitude.AGL", ListItemInfoType.Number, "The craft's current altitude above ground level in meters.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.AltitudeAboveGroundLevel;
			};
			AddProperty("Altitude", "ASL", "Altitude.ASL", ListItemInfoType.Number, "The craft's current altitude above sea level in meters.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.AltitudeAboveSeaLevel;
			};
			AddProperty("Altitude", "ASF", "Altitude.ASF", ListItemInfoType.Number, "The craft's current altitude above sea floor in meters. This is the same as AGL when not over water.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.AltitudeAboveTerrain;
			};
			AddProperty("Performance", "Engine Thrust", "Performance.CurrentEngineThrust", ListItemInfoType.Number, "The current thrust generated by all active engines in N.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.CurrentEngineThrustUnscaled;
			};
			AddProperty("Performance", "Mass", "Performance.Mass", ListItemInfoType.Number, "The current mass of the craft in kg.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.CurrentMassUnscaled;
			};
			AddProperty("Performance", "Dry Mass", "Performance.DryMass", ListItemInfoType.Number, "The current dry mass of the craft in kg.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = (c.Craft.Data.CurrentMass - c.Craft.Data.FuelMass) * 100f;
			};
			AddProperty("Performance", "Fuel Mass", "Performance.FuelMass", ListItemInfoType.Number, "The current fuel mass of the craft in kg.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.FuelMass * 100f;
			};
			AddProperty("Performance", "Max Engine Thrust", "Performance.MaxActiveEngineThrust", ListItemInfoType.Number, "The thrust that could be achieved if all active engines were at 100% throttle, in N.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.MaxActiveEngineThrustUnscaled;
			};
			AddProperty("Performance", "TWR", "Performance.TWR", ListItemInfoType.Number, "The thrust to weight ratio of the craft.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.Performance.ThrustToWeightRatio;
			};
			AddProperty("Performance", "Current Isp", "Performance.CurrentIsp", ListItemInfoType.Number, "The current specific impulse of the craft in seconds.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.Performance.CurrentIsp;
			};
			AddProperty("Performance", "Stage Delta-V", "Performance.StageDeltaV", ListItemInfoType.Number, "The delta-V remaining in the current stage.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.Performance.DeltaVStage;
			};
			AddProperty("Performance", "Stage Burn Time", "Performance.BurnTime", ListItemInfoType.Number, "The remaining burn time in the current stage in seconds.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.Performance.RemainingBurnTime;
			};
			AddProperty("Fuel", "Battery", "Fuel.Battery", ListItemInfoType.Number, "The percentage of battery remaining in the entire craft.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.RemainingBattery;
			};
			AddProperty("Fuel", "Stage", "Fuel.FuelInStage", ListItemInfoType.Number, "The percentage of fuel remaining for the currently active engines.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.RemainingFuelInStage;
			};
			AddProperty("Fuel", "Mono", "Fuel.Mono", ListItemInfoType.Number, "The percentage of mono fuel remaining in the entire craft.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.RemainingMonopropellant;
			};
			AddProperty("Fuel", "AllStages", "Fuel.AllStages", ListItemInfoType.Number, "The percentage of fuel remaining in the entire craft.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.Performance.FuelAllStagesPercentage;
			};
			AddProperty("Velocity", "Surface", "Vel.SurfaceVelocity", ListItemInfoType.Vector, "The current velocity of the craft in m/s relative to the surface of the planet.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = c.Craft.Data.SurfaceVelocity;
			};
			AddProperty("Velocity", "Orbit", "Vel.OrbitVelocity", ListItemInfoType.Vector, "The current velocity of the craft in m/s in PCI coordinates.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = c.Craft.Data.Velocity;
			};
			AddProperty("Velocity", "Target", "Target.Velocity", ListItemInfoType.Vector, "The current velocity of the target in m/s in PCI coordinates.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = Vec(c.Craft.Data.NavSphereTarget?.Velocity);
			};
			AddProperty("Velocity", "Gravity", "Vel.Gravity", ListItemInfoType.Vector, "The current gravity in m/s2 in PCI coordinates.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = c.Craft.Data.Gravity;
			};
			AddProperty("Velocity", "Drag", "Vel.Drag", ListItemInfoType.Vector, "The current drag in m/s2 in PCI coordinates.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = c.Craft.CraftScript.DragAcceleration;
			};
			AddProperty("Velocity", "Acceleration", "Vel.Acceleration", ListItemInfoType.Vector, "The current acceleration of the craft in m/s2.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = c.Craft.Data.Acceleration;
			};
			AddProperty("Velocity", "Angular", "Vel.AngularVelocity", ListItemInfoType.Vector, "The current angular velocity of the craft in rad/s (pitch rate, yaw rate, roll rate).").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = c.Craft.Data.AngularVelocity;
			};
			AddProperty("Velocity", "Lateral", "Vel.LateralSurfaceVelocity", ListItemInfoType.Number, "The current velocity tangent to the planet surface in m/s.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.LateralSurfaceVelocity;
			};
			AddProperty("Velocity", "Vertical", "Vel.VerticalSurfaceVelocity", ListItemInfoType.Number, "The current velocity toward the center of the planet in m/s.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.VerticalSurfaceVelocity;
			};
			AddProperty("Velocity", "Mach Number", "Vel.MachNumber", ListItemInfoType.Number, "The current mach number.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.MachNumber;
			};
			AddProperty("Input", "Roll", "Input.Roll", ListItemInfoType.Number, "The current roll input.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Inputs.Roll;
			};
			AddProperty("Input", "Pitch", "Input.Pitch", ListItemInfoType.Number, "The current pitch input.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Inputs.Pitch;
			};
			AddProperty("Input", "Yaw", "Input.Yaw", ListItemInfoType.Number, "The current yaw input.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Inputs.Yaw;
			};
			AddProperty("Input", "Throttle", "Input.Throttle", ListItemInfoType.Number, "The current throttle input.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Inputs.Throttle;
			};
			AddProperty("Input", "Brake", "Input.Brake", ListItemInfoType.Number, "The current brake input.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Inputs.Brake;
			};
			AddProperty("Input", "Slider 1", "Input.Slider1", ListItemInfoType.Number, "The current slider 1 input.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Inputs.Slider1;
			};
			AddProperty("Input", "Slider 2", "Input.Slider2", ListItemInfoType.Number, "The current slider 2 input.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Inputs.Slider2;
			};
			AddProperty("Input", "Slider 3", "Input.Slider3", ListItemInfoType.Number, "The current slider 3 input.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Inputs.Slider3;
			};
			AddProperty("Input", "Slider 4", "Input.Slider4", ListItemInfoType.Number, "The current slider 4 input.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Inputs.Slider4;
			};
			AddProperty("Input", "Translate Forward", "Input.TranslateForward", ListItemInfoType.Number, "The current translate forward input.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Inputs.TranslateForward;
			};
			AddProperty("Input", "Translate Right", "Input.TranslateRight", ListItemInfoType.Number, "The current translate right input.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Inputs.TranslateRight;
			};
			AddProperty("Input", "Translate Up", "Input.TranslateUp", ListItemInfoType.Number, "The current translate up input.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Inputs.TranslateUp;
			};
			AddProperty("Input", "Translation Mode", "Input.TranslationMode", ListItemInfoType.Number, "1 if Translation Mode is enabled, otherwise 0.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = (c.Craft.Inputs.TranslationMode ? 1 : 0);
			};
			AddProperty("Nav", "Position", "Nav.Position", ListItemInfoType.Vector, "The current position of the craft's CoM from the center of the current planet in meters (PCI coordinates).").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = c.Craft.Data.Position;
			};
			AddProperty("Nav", "Target Position", "Target.Position", ListItemInfoType.Vector, "The current position of the target from the center of its current planet in meters (PCI coordinates).").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = Vec(c.Craft.Data.NavSphereTarget?.Position);
			};
			AddProperty("Nav", "Heading", "Nav.CraftHeading", ListItemInfoType.Degrees, "The current heading of the craft in degrees.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.Heading;
			};
			AddProperty("Nav", "Pitch", "Nav.Pitch", ListItemInfoType.Degrees, "The current pitch of the craft in degrees.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.Pitch;
			};
			AddProperty("Nav", "Autopilot Heading", "Nav.AutopilotHeading", ListItemInfoType.Degrees, "The autopilot targeted heading in degrees.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.NavSphere.Heading;
			};
			AddProperty("Nav", "Autopilot Pitch", "Nav.AutopilotPitch", ListItemInfoType.Degrees, "The autopilot targeted pitch in degrees.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.NavSphere.Pitch;
			};
			AddProperty("Nav", "Bank Angle", "Nav.BankAngle", ListItemInfoType.Degrees, "The current bank angle of the craft in degrees.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.BankAngle;
			};
			AddProperty("Nav", "Angle of Attack", "Nav.AngleOfAttack", ListItemInfoType.Degrees, "The current angle of attack of the craft in degrees.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.AngleOfAttack;
			};
			AddProperty("Nav", "Side Slip", "Nav.SideSlip", ListItemInfoType.Degrees, "The current side slip of the craft in degrees.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.SideSlip;
			};
			AddProperty("Nav", "North", "Nav.North", ListItemInfoType.Vector, "The unit vector representing north from the craft's current position, in PCI coordinates.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = c.Craft.Data.North;
			};
			AddProperty("Nav", "East", "Nav.East", ListItemInfoType.Vector, "The unit vector representing east from the craft's current position, in PCI coordinates.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = c.Craft.Data.East;
			};
			AddProperty("Nav", "Craft Roll Axis", "Nav.CraftDirection", ListItemInfoType.Vector, "The unit vector representing the roll axis of the craft in PCI coordinates. This is the direction the craft is currently pointing.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = c.Craft.Data.CraftForward;
			};
			AddProperty("Nav", "Craft Pitch Axis", "Nav.CraftRight", ListItemInfoType.Vector, "The unit vector representing the pitch axis of the craft in PCI coordinates.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = c.Craft.Data.CraftRight;
			};
			AddProperty("Nav", "Craft Yaw Axis", "Nav.CraftUp", ListItemInfoType.Vector, "The unit vector representing the yaw axis of the craft in PCI coordinates.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = c.Craft.Data.CraftUp;
			};
			AddProperty("Name", "Craft", "Name.Craft", ListItemInfoType.Text, "The name of the craft.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.TextValue = c.Craft.CraftScript.CraftNode?.Name;
			};
			AddProperty("Name", "Planet", "Orbit.Planet", ListItemInfoType.Text, "The name of the planet the craft is currently orbiting.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.TextValue = c.Craft.Data.Orbit.Parent.Name;
			};
			AddProperty("Name", "Target Name", "Target.Name", ListItemInfoType.Text, "The name of the current target.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.TextValue = ((c.Craft.Data.NavSphereTarget == null) ? string.Empty : c.Craft.Data.NavSphereTarget.Name);
			};
			AddProperty("Name", "Target Planet", "Target.Planet", ListItemInfoType.Text, "The name of the target's current planet.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.TextValue = ((c.Craft.Data.NavSphereTarget == null) ? string.Empty : c.Craft.Data.NavSphereTarget.Parent.Name);
			};
			AddProperty("Misc", "Stage", "Misc.Stage", ListItemInfoType.Number, "The current stage of the craft's active command pod.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.CraftScript.ActiveCommandPod?.CurrentStage ?? 0;
			};
			AddProperty("Misc", "Num Stages", "Misc.NumStages", ListItemInfoType.Number, "The number of stages of craft's active command pod.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.CraftScript.ActiveCommandPod?.NumStages ?? 0;
			};
			AddProperty("Misc", "Grounded", "Misc.Grounded", ListItemInfoType.Bool, "One indicates the craft is currently touching the ground. Zero indicates it is not.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.BoolValue = c.Craft.Data.Grounded;
			};
			AddProperty("Misc", "Solar Radiation", "Misc.SolarRadiation", ListItemInfoType.Number, "The current amount of solar radiation the craft is receiving.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.Data.SolarRadiationIntensity;
			};
			AddProperty("Misc", "User Camera Position", "Misc.CameraPosition", ListItemInfoType.Vector, "The position of the player's camera in PCI coordinates.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = Game.Instance.FlightScene.ViewManager.GameView.GameCamera.PlanetPosition;
			};
			AddProperty("Misc", "User Camera Pointing", "Misc.CameraPointing", ListItemInfoType.Vector, "The pointing of the player's camera.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = c.Craft.CraftScript.ReferenceFrame.FrameToPlanetVector(Game.Instance.FlightScene.ViewManager.GameView.GameCamera.Transform.forward);
			};
			AddProperty("Misc", "User Camera Up Direction", "Misc.CameraUp", ListItemInfoType.Vector, "The upwards pointing of the player's camera.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = c.Craft.CraftScript.ReferenceFrame.FrameToPlanetVector(Game.Instance.FlightScene.ViewManager.GameView.GameCamera.Transform.up);
			};
			AddProperty("Misc", "Pitch PIDs", "Misc.PidPitch", ListItemInfoType.Vector, "The PID values for the pitch axis.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = c.Craft.PidGainsPitch;
			};
			AddProperty("Misc", "Roll PIDs", "Misc.PidRoll", ListItemInfoType.Vector, "The PID values for the roll axis.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = c.Craft.PidGainsRoll;
			};
			AddProperty("Time", "Frame Delta Time", "Time.FrameDeltaTime", ListItemInfoType.Number, "The amount of time (in seconds) that has passed since the last frame of execution.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.FrameDeltaTime;
			};
			AddProperty("Time", "Time Since Launch", "Time.TimeSinceLaunch", ListItemInfoType.Number, "The amount of time (in seconds) that has passed since this craft launched.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.TimeSinceLaunch;
			};
			AddProperty("Time", "Total Time", "Time.TotalTime", ListItemInfoType.Number, "The amount of time (in seconds) that has passed since the sandbox was created.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.TotalTime;
			};
			AddProperty("Time", "Warp Amount", "Time.WarpAmount", ListItemInfoType.Number, "The amount of time multiplication applied by the time warp.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = Game.Instance.FlightScene.TimeManager.CurrentMode.TimeMultiplier;
			};
			AddProperty("Time", "Real Time", "Time.RealTime", ListItemInfoType.Number, "The amount of time in real life that has passed since the game has started.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = (DateTime.Now - Game.Instance.StartTime).TotalSeconds;
			};
			AddProperty("CraftName", "ID", "Craft.NameToID", ListItemInfoType.Number, "The ID of the first craft found with the specified name or -1 if none are found. If no name is provided, then the ID of the player's craft is returned.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetCraftNodeByName(n, c, 0)?.NodeId ?? (-1);
			};
			AddProperty("Craft", "Altitude", "Craft.Altitude", ListItemInfoType.Number, "The craft's current altitude above sea level in meters.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetCraftNodeById(n, c, 0)?.Altitude ?? 0.0;
			};
			AddProperty("Craft", "Destroyed", "Craft.Destroyed", ListItemInfoType.Bool, "True if the craft is destroyed or does not exist.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.BoolValue = GetCraftNodeById(n, c, 0)?.IsDestroyed ?? true;
			};
			AddProperty("Craft", "Grounded", "Craft.Grounded", ListItemInfoType.Bool, "True if the craft is currently in contact with the planet.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.BoolValue = GetCraftNodeById(n, c, 0)?.InContactWithPlanet ?? false;
			};
			AddProperty("Craft", "Mass", "Craft.Mass", ListItemInfoType.Number, "The mass of the craft in kilograms.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				ICraftNode craftNodeById = GetCraftNodeById(n, c, 0);
				e.NumberValue = ((craftNodeById != null) ? (craftNodeById.CraftMass * 100f) : 0f);
			};
			AddProperty("Craft", "Name", "Craft.IDToName", ListItemInfoType.Text, "The name of the craft with the specified ID.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.TextValue = GetCraftNodeById(n, c, 0)?.Name ?? string.Empty;
			};
			AddProperty("Craft", "Part Count", "Craft.PartCount", ListItemInfoType.Number, "The number of parts in the craft.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetCraftNodeById(n, c, 0)?.CraftPartCount ?? 0;
			};
			AddProperty("Craft", "Planet", "Craft.Planet", ListItemInfoType.Text, "The name of the planet the craft is currently orbiting.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.TextValue = GetCraftNodeById(n, c, 0)?.Parent?.Name ?? string.Empty;
			};
			AddProperty("Craft", "Position", "Craft.Position", ListItemInfoType.Vector, "The current position of the craft from the center of its parent planet in meters (PCI coordinates).").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = GetCraftNodeById(n, c, 0)?.Position ?? ((Vector3d)Vector3.zero);
			};
			AddProperty("Craft", "Velocity", "Craft.Velocity", ListItemInfoType.Vector, "The current velocity of the craft in m/s in PCI coordinates.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = GetCraftNodeById(n, c, 0)?.Velocity ?? ((Vector3d)Vector3.zero);
			};
			AddProperty("Craft", "Is Player", "Craft.IsPlayer", ListItemInfoType.Bool, "True if it is the player craft.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.BoolValue = GetCraftNodeById(n, c, 0)?.IsPlayer ?? false;
			};
			AddProperty("Craft", "Bounding Box Min", "Craft.BoundMin", ListItemInfoType.Vector, "The distance of the min corner of the bounding box to the CoM. This is a performance expensive process, use it wisely.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				ICraftScript craftScript = GetCraftNodeById(n, c, 0)?.CraftScript;
				e.VectorValue = craftScript.CalculateBounds().min - craftScript.CenterOfMass.position;
			};
			AddProperty("Craft", "Bounding Box Max", "Craft.BoundMax", ListItemInfoType.Vector, "The distance of the max corner of the bounding box to the CoM. This is a performance expensive process, use it wisely.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				ICraftScript craftScript = GetCraftNodeById(n, c, 0)?.CraftScript;
				e.VectorValue = craftScript.CalculateBounds().max - craftScript.CenterOfMass.position;
			};
			AddProperty("Craft", "Orbit Apoapsis", "Craft.Apoapsis", ListItemInfoType.Vector, "A vector indicating the apoapsis position in meters.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = GetCraftNodeById(n, c, 0)?.Orbit.Apoapsis ?? Vector3d.zero;
			};
			AddProperty("Craft", "Orbit Periapsis", "Craft.Periapsis", ListItemInfoType.Vector, "A vector indicating the periapsis position in meters.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = GetCraftNodeById(n, c, 0)?.Orbit.Periapsis ?? Vector3d.zero;
			};
			AddProperty("Craft", "Orbit Period", "Craft.Period", ListItemInfoType.Number, "The period of the craft's orbit in seconds.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetCraftNodeById(n, c, 0)?.Orbit.Period ?? (-1.0);
			};
			AddProperty("Craft", "Orbit ApoapsisTime", "Craft.ApoapsisTime", ListItemInfoType.Number, "The time left for the craft to reach its apoapsis in seconds.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetCraftNodeById(n, c, 0)?.Orbit.GetTimeToApoapsis() ?? (-1.0);
			};
			AddProperty("Craft", "Orbit PeriapsisTime", "Craft.PeriapsisTime", ListItemInfoType.Number, "The time left for the craft to reach its periapsis in seconds.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetCraftNodeById(n, c, 0)?.Orbit.GetTimeToPeriapsis() ?? (-1.0);
			};
			AddProperty("Craft", "Orbit Inclination", "Craft.Inclination", ListItemInfoType.Radians, "The inclination of the craft's orbit.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetCraftNodeById(n, c, 0)?.Orbit.Inclination ?? (-1.0);
			};
			AddProperty("Craft", "Orbit Eccentricity", "Craft.Eccentricity", ListItemInfoType.Number, "The eccentricity of the craft's orbit.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetCraftNodeById(n, c, 0)?.Orbit.Eccentricity ?? (-1.0);
			};
			AddProperty("Craft", "Orbit Mean Anomaly", "Craft.MeanAnomaly", ListItemInfoType.Radians, "The mean anomaly of the craft's orbit.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetCraftNodeById(n, c, 0)?.Orbit.MeanAnomaly ?? (-1.0);
			};
			AddProperty("Craft", "Orbit Mean Motion", "Craft.MeanMotion", ListItemInfoType.Number, "The mean motion of the craft's orbit.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetCraftNodeById(n, c, 0)?.Orbit.MeanMotion ?? (-1.0);
			};
			AddProperty("Craft", "Orbit Periapsis Argument", "Craft.PeriapsisArgument", ListItemInfoType.Radians, "The argument of the periapsis of the craft's orbit.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetCraftNodeById(n, c, 0)?.Orbit.PeriapsisAngle ?? (-1.0);
			};
			AddProperty("Craft", "Orbit Right Ascension", "Craft.RightAscension", ListItemInfoType.Radians, "The right ascension node of the craft's orbit.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetCraftNodeById(n, c, 0)?.Orbit.RightAscensionOfAscendingNode ?? (-1.0);
			};
			AddProperty("Craft", "Orbit True Anomaly", "Craft.TrueAnomaly", ListItemInfoType.Radians, "The true anomaly of the craft's orbit.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetCraftNodeById(n, c, 0)?.Orbit.TrueAnomaly ?? (-1.0);
			};
			AddProperty("Craft", "Orbit Semi Major Axis", "Craft.SemiMajorAxis", ListItemInfoType.Number, "The length of the semi major axis of the craft's orbit in meters.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetCraftNodeById(n, c, 0)?.Orbit.SemiMajorAxis ?? (-1.0);
			};
			AddProperty("Craft", "Orbit Semi Minor Axis", "Craft.SemiMinorAxis", ListItemInfoType.Number, "The length of the semi minor axis of the craft's orbit in meters.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetCraftNodeById(n, c, 0)?.Orbit.SemiMinorAxis ?? (-1.0);
			};
			AddProperty("Part", "Name", "Part.IDToName", ListItemInfoType.Text, "The name of the part with the specified ID.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.TextValue = GetPartById(n, c, 0)?.Name ?? string.Empty;
			};
			AddProperty("Part", "Mass", "Part.Mass", ListItemInfoType.Number, "The mass of the part in kg.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				PartData partById = GetPartById(n, c, 0);
				e.NumberValue = (((object)partById != null) ? (partById.PartScript.Data.Mass * 100f) : 0f);
			};
			AddProperty("Part", "Dry Mass", "Part.DryMass", ListItemInfoType.Number, "Gets the dry mass of the part in kg.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				PartData partById = GetPartById(n, c, 0);
				e.NumberValue = (((object)partById != null) ? (partById.PartMass.Dry * 100f) : 0f);
			};
			AddProperty("Part", "Wet Mass", "Part.WetMass", ListItemInfoType.Number, "Gets the wet mass of the part in kg.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				PartData partById = GetPartById(n, c, 0);
				e.NumberValue = (((object)partById != null) ? (partById.PartMass.Wet * 100f) : 0f);
			};
			AddProperty("Part", "Activated", "Part.Activated", ListItemInfoType.Bool, "True if the part with the specified ID is activated.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.BoolValue = GetPartById(n, c, 0)?.Activated ?? false;
			};
			AddProperty("PartName", "ID", "Part.NameToID", ListItemInfoType.Number, "The ID of the first part found with the specified name or -1 if none are found.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetPartByName(n, c, 0)?.Id ?? (-1);
			};
			AddProperty("Part", "Part Type", "Part.PartType", ListItemInfoType.Text, "The type of the part with the specified ID.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.TextValue = GetPartById(n, c, 0)?.PartType.Name ?? string.Empty;
			};
			AddProperty("Part", "Position", "Part.Position", ListItemInfoType.Vector, "The current position of the part from the center of the current planet in meters (PCI coordinates).").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				IPartScript partScript = GetPartById(p, c, 0)?.PartScript;
				Vector3d vectorValue = Vector3d.zero;
				if (partScript != null)
				{
					vectorValue = c.Craft.CraftScript.ReferenceFrame.FrameToPlanetPosition(partScript.Transform.position);
				}
				e.VectorValue = vectorValue;
			};
			AddProperty("Part", "Temperature", "Part.Temperature", ListItemInfoType.Number, "The temperature of the part with the specified ID in Kelvin.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetPartById(n, c, 0)?.PartScript.Temperature ?? 0f;
			};
			AddProperty("Part", "Drag", "Part.Drag", ListItemInfoType.Number, "An estimation for how much drag this part is generating in Newtons.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetPartById(n, c, 0)?.PartScript.GetEstimatedDragForce() ?? 0f;
			};
			AddProperty("Part", "This Part ID", "Part.ThisID", ListItemInfoType.Number, "The ID of the part running this flight program.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.ExecutingPart?.Id ?? (-1);
			};
			AddProperty("Part", "Min Part ID", "Part.MinID", ListItemInfoType.Number, "Gets the smallest ID of all parts in the craft.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.CraftScript.Data.Assembly.Parts.Min((PartData x) => x.Id);
			};
			AddProperty("Part", "Max Part ID", "Part.MaxID", ListItemInfoType.Number, "Gets the largest ID of all parts in the craft.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.CraftScript.Data.Assembly.Parts.Max((PartData x) => x.Id);
			};
			AddProperty("Part", "Under Water", "Part.UnderWater", ListItemInfoType.Number, "The percentage of the part that is underwater from 0 to 1. Zero meaning not under water at all, and one meaning fully submerged.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = GetPartById(n, c, 0)?.PartScript.WaterPhysics.UnderWaterAmount ?? 0f;
			};
			AddProperty("Transform", "Local to PCI", "Part.LocalToPci", ListItemInfoType.Vector, "Rotates the vector from the part's local space to PCI coordinates. If no part is specified, then it converts from the craft's local space to PCI coordinates.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = c.Craft.ConvertLocalToPCI(GetPartById(n, c, 0)?.PartScript, n.GetExpression(1).Evaluate(c).VectorValue.ToVector3());
			};
			AddProperty("Transform", "PCI to Local", "Part.PciToLocal", ListItemInfoType.Vector, "Rotates the vector from the PCI coordinates to the part's local space. If no part is specified, then it converts from PCI coordinates to the craft's local space.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = c.Craft.ConvertPCIToLocal(GetPartById(n, c, 0)?.PartScript, n.GetExpression(1).Evaluate(c).VectorValue);
			};
			AddProperty("SetPart", "Activated", "Part.SetActivated", ListItemInfoType.Bool, "Sets the activation state of the part.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IPartScript partScript = GetPartById(n, c, 0)?.PartScript;
				bool boolValue = n.GetExpression(1).Evaluate(c).BoolValue;
				if (partScript != null && partScript.Data.Activated != boolValue)
				{
					if (boolValue)
					{
						partScript.Activate();
					}
					else
					{
						partScript.Deactivate();
					}
				}
			};
			AddProperty("SetPart", "Focused", "Part.SetFocused", ListItemInfoType.Bool, "If set to true, focuses the camera on the part; otherwise unfocuses from the part.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IPartScript obj = GetPartById(n, c, 0)?.PartScript;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				obj.FocusCameraOnPart(expressionResult.BoolValue);
			};
			AddProperty("SetPart", "Name", "Part.SetName", ListItemInfoType.Text, "Sets the name of the part with the specified ID.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				PartData partById = GetPartById(n, c, 0);
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (partById != null)
				{
					partById.Name = expressionResult.TextValue;
				}
			};
			AddProperty("SetPart", "Explode", "Part.SetExplode", ListItemInfoType.Number, "Explodes the part with the specified amount of power from 0 to 1. 0 just causes the part to fall without explosion. 1 is maximum explosion power.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IPartScript partScript = GetPartById(n, c, 0)?.PartScript;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				partScript?.BodyScript.ExplodePart(partScript, 10f * Mathf.Clamp01((float)expressionResult.NumberValue));
			};
			AddProperty("SetPart", "Fuel Transfer", "Part.FuelTransfer", ListItemInfoType.Number, "Sets the fuel transfer node to Drain if <0, None if 0 or Fill if >0.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IPartScript partScript = GetPartById(n, c, 0)?.PartScript;
				double numberValue = n.GetExpression(1).Evaluate(c).NumberValue;
				if (partScript != null)
				{
					FuelTransferMode fuelTransfer = ((numberValue != 0.0) ? ((!(numberValue > 0.0)) ? FuelTransferMode.Drain : FuelTransferMode.Fill) : FuelTransferMode.None);
					c.Craft.SetPartFuelTransfer(partScript, fuelTransfer);
				}
			};
			AddProperty("Terrain", "Color", "Terrain.Color", ListItemInfoType.Vector, "Gets the color of the terrain at the specified (latitude, longitude, 0) vector. The z component of the vector is not used.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.VectorValue = c.Craft.GetTerrainColor(n.GetExpression(0).Evaluate(c).VectorValue);
			};
			AddProperty("Terrain", "Height", "Terrain.Height", ListItemInfoType.Number, "Gets the height of the terrain above the radius in meters at the specified (latitude, longitude, 0) vector. The z component of the vector is not used.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				e.NumberValue = c.Craft.GetTerrainHeight(n.GetExpression(0).Evaluate(c).VectorValue);
			};
			AddProperty("Raycast", "Raycast", "Raycast", ListItemInfoType.Vector, "Projects a ray from the indicated position in the indicated direction and returns the position at which the ray touched something, or a zero vector if it didn't touch anything in a 100km radius.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode n)
			{
				int layerMask = -1543503872;
				Vector3 origin = c.Craft.CraftScript.ReferenceFrame.PlanetToFramePosition(n.GetExpression(0).Evaluate(c).VectorValue);
				Vector3 direction = c.Craft.CraftScript.ReferenceFrame.PlanetToFrameVector((Vector3)n.GetExpression(1).Evaluate(c).VectorValue);
				Physics.Raycast(origin, direction, out var hitInfo, 100000f, layerMask, QueryTriggerInteraction.Ignore);
				e.VectorValue = ((hitInfo.collider == null) ? ((Vector3d)Vector3.zero) : c.Craft.CraftScript.ReferenceFrame.FrameToPlanetPosition(hitInfo.point));
			};
			AddProperty("Mfd", "Anchored Position", "Mfd.AnchoredPosition", ListItemInfoType.Vector, "The position of the MFD widget relative to its anchor point within its parent.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.VectorValue = Vector2ToVector3d(GetMfdWidget(c, p)?.AnchoredPosition);
			};
			AddProperty("Mfd.Set", "Anchored Position", "Mfd.SetAnchoredPosition", ListItemInfoType.Vector, "Sets the position of the MFD widget relative to its anchor point within its parent.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, n);
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (mfdWidget != null)
				{
					mfdWidget.AnchoredPosition = expressionResult.VectorValue.ToVector3();
				}
			};
			AddProperty("Mfd", "Anchor Min", "Mfd.AnchorMin", ListItemInfoType.Vector, "The normalized position (0 to 1) in the parent widget that the lower left corner of this widget is anchored to.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.VectorValue = Vector2ToVector3d(GetMfdWidget(c, p)?.Transform.anchorMin);
			};
			AddProperty("Mfd.Set", "Anchor Min", "Mfd.SetAnchorMin", ListItemInfoType.Vector, "Sets the normalized position (0 to 1) in the parent widget that the lower left corner of this widget is anchored to.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, n);
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (mfdWidget != null)
				{
					mfdWidget.Transform.anchorMin = expressionResult.VectorValue.ToVector3();
				}
			};
			AddProperty("Mfd", "Anchor Max", "Mfd.AnchorMax", ListItemInfoType.Vector, "The normalized position (0 to 1) in the parent widget that the upper right corner of this widget is anchored to.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.VectorValue = Vector2ToVector3d(GetMfdWidget(c, p)?.Transform.anchorMax);
			};
			AddProperty("Mfd.Set", "Anchor Max", "Mfd.SetAnchorMax", ListItemInfoType.Vector, "Sets the normalized position (0 to 1) in the parent widget that the upper right corner of this widget is anchored to.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, n);
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (mfdWidget != null)
				{
					mfdWidget.Transform.anchorMax = expressionResult.VectorValue.ToVector3();
				}
			};
			AddProperty("Mfd", "Color", "Mfd.Color", ListItemInfoType.Vector, "The color of the MFD widget as a vector with (Red,Green,Blue) components, each ranging from 0 to 1.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.VectorValue = GetMfdWidget(c, p)?.Color ?? Vector3.zero;
			};
			AddProperty("Mfd.Set", "Color", "Mfd.SetColor", ListItemInfoType.Vector, "Sets the color of the MFD widget as a vector with (Red,Green,Blue) components, each ranging from 0 to 1.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, n);
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (mfdWidget != null)
				{
					mfdWidget.Color = expressionResult.VectorValue.ToVector3();
				}
			};
			AddProperty("Mfd", "Exists", "Mfd.Exists", ListItemInfoType.Bool, "Returns true if the widget with the specified name exists.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, p);
				e.BoolValue = mfdWidget != null;
			};
			AddProperty("Mfd", "Opacity", "Mfd.Opacity", ListItemInfoType.Number, "The opacity of the MFD widget from 0 (fully transparent) to 1 (fully opaque).").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.NumberValue = GetMfdWidget(c, p)?.Opacity ?? 0f;
			};
			AddProperty("Mfd.Set", "Opacity", "Mfd.SetOpacity", ListItemInfoType.Number, "Sets the opacity of the MFD widget from 0 (fully transparent) to 1 (fully opaque).").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, n);
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (mfdWidget != null)
				{
					mfdWidget.Opacity = (float)expressionResult.NumberValue;
				}
			};
			AddProperty("Mfd", "Parent", "Mfd.Parent", ListItemInfoType.Text, "Gets the name of the parent of the MFD widget, or an empty string if it does not have a parent.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.TextValue = GetMfdWidget(c, p)?.Parent?.Name;
			};
			AddProperty("Mfd.Set", "Parent", "Mfd.SetParent", ListItemInfoType.Text, "Sets the parent of the MFD widget.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, n);
				if (mfdWidget != null)
				{
					IMfdWidget mfdWidget2 = GetMfdWidget(c, n, 1);
					mfdWidget.SetParent(mfdWidget2, worldPositionStays: true);
				}
			};
			AddProperty("Mfd", "Pivot", "Mfd.Pivot", ListItemInfoType.Vector, "The point on this widget that it rotates around, in normalized position (0 to 1).").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.VectorValue = Vector2ToVector3d(GetMfdWidget(c, p)?.Pivot);
			};
			AddProperty("Mfd.Set", "Pivot", "Mfd.SetPivot", ListItemInfoType.Vector, "Sets the point on this widget that it rotates around, in normalized position (0 to 1).").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, n);
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (mfdWidget != null)
				{
					mfdWidget.Pivot = expressionResult.VectorValue.ToVector3();
				}
			};
			AddProperty("Mfd", "Position", "Mfd.Position", ListItemInfoType.Vector, "The position of the MFD widget relative to its parent.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.VectorValue = Vector2ToVector3d(GetMfdWidget(c, p)?.LocalPosition);
			};
			AddProperty("Mfd.Set", "Position", "Mfd.SetPosition", ListItemInfoType.Vector, "Sets the position of the MFD widget relative to its parent.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, n);
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (mfdWidget != null)
				{
					mfdWidget.LocalPosition = expressionResult.VectorValue.ToVector3();
				}
			};
			AddProperty("Mfd", "Rotation", "Mfd.Rotation", ListItemInfoType.Degrees, "The rotation of the MFD widget in degrees.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.NumberValue = GetMfdWidget(c, p)?.LocalRotation ?? 0f;
			};
			AddProperty("Mfd.Set", "Rotation", "Mfd.SetRotation", ListItemInfoType.Degrees, "Sets the rotation of the MFD widget in degrees.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, n);
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (mfdWidget != null)
				{
					mfdWidget.LocalRotation = (float)expressionResult.NumberValue;
				}
			};
			AddProperty("Mfd", "Scale", "Mfd.Scale", ListItemInfoType.Vector, "The scale of the MFD widget in the x and y component of the vector.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.VectorValue = Vector2ToVector3d(GetMfdWidget(c, p)?.Scale);
			};
			AddProperty("Mfd.Set", "Scale", "Mfd.SetScale", ListItemInfoType.Vector, "Sets the scale of the widget using the x and y components of the vector. Scale is different from size in that it also scales child widgets and is a percentage from 0 to 1.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, n);
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (mfdWidget != null)
				{
					Vector3 v = expressionResult.VectorValue.ToVector3();
					v.z = 1f;
					mfdWidget.Scale = LimitVector(v);
				}
			};
			AddProperty("Mfd", "Size", "Mfd.Size", ListItemInfoType.Vector, "The size of the MFD widget in the x and y component of the vector.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.VectorValue = Vector2ToVector3d(GetMfdWidget(c, p)?.Size);
			};
			AddProperty("Mfd.Set", "Size", "Mfd.SetSize", ListItemInfoType.Vector, "Sets the size of the MFD widget using the x and y components of the vector. Size is different from scale in that it doesn't necessarily resize child widgets and is in display units instead of a percentage.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, n);
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (mfdWidget != null)
				{
					mfdWidget.Size = LimitVector(expressionResult.VectorValue.ToVector3(), allowNegative: false);
				}
			};
			AddProperty("Mfd", "Visible", "Mfd.Visible", ListItemInfoType.Bool, "True if the MFD widget is visible, otherwise False.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.BoolValue = GetMfdWidget(c, p)?.Visible ?? false;
			};
			AddProperty("Mfd.Set", "Visible", "Mfd.SetVisible", ListItemInfoType.Bool, "Sets the visibility of the MFD widget.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, n);
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (mfdWidget != null)
				{
					mfdWidget.Visible = expressionResult.BoolValue;
				}
			};
			AddProperty("Mfd.Sprite", "Fill Method", "Mfd.Sprite.FillMethod", ListItemInfoType.Text, "The method used to fill the widget.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.TextValue = (GetMfdWidget(c, p) as ISpriteWidget)?.FillMethod ?? "None";
			};
			AddProperty("Mfd.SetSprite", "Fill Method", "Mfd.Sprite.SetFillMethod", ListItemInfoType.Text, "Sets the method used to fill the widget. Options are None, Horizontal, Vertical, Radial90, Radial180, and Radial360.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				ISpriteWidget spriteWidget = GetMfdWidget(c, n) as ISpriteWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (spriteWidget != null)
				{
					spriteWidget.FillMethod = expressionResult.TextValue;
				}
			};
			AddProperty("Mfd.Sprite", "Icon", "Mfd.Sprite.Icon", ListItemInfoType.Text, "The icon used by the sprite widget.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.TextValue = (GetMfdWidget(c, p) as ISpriteWidget)?.Icon;
			};
			AddProperty("Mfd.SetSprite", "Icon", "Mfd.Sprite.SetIcon", ListItemInfoType.Text, "Sets the icon used by the sprite widget.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				ISpriteWidget spriteWidget = GetMfdWidget(c, n) as ISpriteWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (spriteWidget != null)
				{
					spriteWidget.Icon = expressionResult.TextValue;
				}
			};
			AddProperty("Mfd.Sprite", "Fill Amount", "Mfd.Sprite.FillAmount", ListItemInfoType.Number, "The amount the sprite is filled, from 0 to 1.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.NumberValue = (GetMfdWidget(c, p) as ISpriteWidget)?.FillAmount ?? 0f;
			};
			AddProperty("Mfd.SetSprite", "Fill Amount", "Mfd.Sprite.SetFillAmount", ListItemInfoType.Number, "Sets the amount the sprite is filled, from 0 to 1.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				ISpriteWidget spriteWidget = GetMfdWidget(c, n) as ISpriteWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (spriteWidget != null)
				{
					spriteWidget.FillAmount = (float)expressionResult.NumberValue;
				}
			};
			AddProperty("Mfd.SetLinePoints", "LinePoints", "Mfd.Line.SetLinePoints", ListItemInfoType.Vector, "Sets the position of the end points of a line widget.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				if (GetMfdWidget(c, n) is ILineWidget lineWidget)
				{
					Vector3d vectorValue = n.GetExpression(1).Evaluate(c).VectorValue;
					Vector3d vectorValue2 = n.GetExpression(2).Evaluate(c).VectorValue;
					lineWidget.SetLineEndPoints(vectorValue.ToVector3(), vectorValue2.ToVector3());
				}
			};
			AddProperty("Mfd.SetLine", "Thickness", "Mfd.Line.SetThickness", ListItemInfoType.Vector, "Sets the thickness of the line.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				if (GetMfdWidget(c, n) is ILineWidget lineWidget)
				{
					lineWidget.Thickness = (float)n.GetExpression(1).Evaluate(c).NumberValue;
				}
			};
			AddProperty("Mfd.SetLine", "Length", "Mfd.Line.SetLength", ListItemInfoType.Vector, "Sets the length of the line.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				if (GetMfdWidget(c, n) is ILineWidget lineWidget)
				{
					lineWidget.Length = (float)n.GetExpression(1).Evaluate(c).NumberValue;
				}
			};
			AddProperty("Mfd.Event", "Drag", "Mfd.Event.Drag", ListItemInfoType.Text, "Gets the message name to broadcast when the user drags their cursor across the widget.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.TextValue = GetMfdWidget(c, p)?.GetEventHandler(GameViewPointerEventType.Drag);
			};
			AddProperty("Mfd.SetEvent", "Drag", "Mfd.Event.SetDrag", ListItemInfoType.Text, "Sets the message name to broadcast when the user drags their cursor across the widget. The data is the local position of the input on the widget.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, n);
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				ExpressionResult expressionResult2 = n.GetExpression(2).Evaluate(c);
				mfdWidget?.SetEventHandler(GameViewPointerEventType.Drag, expressionResult.TextValue, expressionResult2.TextValue);
			};
			AddProperty("Mfd.Event", "Pointer Down", "Mfd.Event.PointerDown", ListItemInfoType.Text, "Gets the message name to broadcast when the presses down on the widget.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.TextValue = GetMfdWidget(c, p)?.GetEventHandler(GameViewPointerEventType.PointerDown);
			};
			AddProperty("Mfd.SetEvent", "Pointer Down", "Mfd.Event.SetPointerDown", ListItemInfoType.Text, "Sets the message name to broadcast when the user presses down on the widget. The data is the local position of the input on the widget.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, n);
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				ExpressionResult expressionResult2 = n.GetExpression(2).Evaluate(c);
				mfdWidget?.SetEventHandler(GameViewPointerEventType.PointerDown, expressionResult.TextValue, expressionResult2.TextValue);
			};
			AddProperty("Mfd.Event", "Pointer Up", "Mfd.Event.PointerUp", ListItemInfoType.Text, "Gets the message name to broadcast when the releases their pointer on the widget.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.TextValue = GetMfdWidget(c, p)?.GetEventHandler(GameViewPointerEventType.PointerUp);
			};
			AddProperty("Mfd.SetEvent", "Pointer Up", "Mfd.Event.SetPointerUp", ListItemInfoType.Text, "Sets the message name to broadcast when the user releases their pointer on the widget. The data is the local position of the input on the widget.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, n);
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				ExpressionResult expressionResult2 = n.GetExpression(2).Evaluate(c);
				mfdWidget?.SetEventHandler(GameViewPointerEventType.PointerUp, expressionResult.TextValue, expressionResult2.TextValue);
			};
			AddProperty("Mfd.Event", "Click", "Mfd.Event.PointerClick", ListItemInfoType.Text, "Gets the message name to broadcast when the user clicks on the widget.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.TextValue = GetMfdWidget(c, p)?.GetEventHandler(GameViewPointerEventType.PointerClick);
			};
			AddProperty("Mfd.SetEvent", "Click", "Mfd.Event.SetPointerClick", ListItemInfoType.Text, "Sets the message name to broadcast when the user clicks on the widget. The data is the local position of the input on the widget.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, n);
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				ExpressionResult expressionResult2 = n.GetExpression(2).Evaluate(c);
				mfdWidget?.SetEventHandler(GameViewPointerEventType.PointerClick, expressionResult.TextValue, expressionResult2.TextValue);
			};
			AddProperty("Mfd.Label", "Text", "Mfd.Label.Text", ListItemInfoType.Text, "The text of the label widget.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.TextValue = (GetMfdWidget(c, p) as ILabelWidget)?.Text;
			};
			AddProperty("Mfd.SetLabel", "Text", "Mfd.Label.SetText", ListItemInfoType.Text, "Sets the text of the label widget.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				ILabelWidget labelWidget = GetMfdWidget(c, n) as ILabelWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (labelWidget != null)
				{
					labelWidget.Text = expressionResult.TextValue;
				}
			};
			AddProperty("Mfd.Label", "Font Size", "Mfd.Label.FontSize", ListItemInfoType.Number, "The size of the label widget's font.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.NumberValue = (GetMfdWidget(c, p) as ILabelWidget)?.FontSize ?? 0f;
			};
			AddProperty("Mfd.SetLabel", "Font Size", "Mfd.Label.SetFontSize", ListItemInfoType.Number, "Sets the size of the label widget's font.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				ILabelWidget labelWidget = GetMfdWidget(c, n) as ILabelWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (labelWidget != null)
				{
					labelWidget.FontSize = (float)expressionResult.NumberValue;
				}
			};
			AddProperty("Mfd.Label", "Auto Size", "Mfd.Label.AutoSize", ListItemInfoType.Bool, "Determines if the label currently has Auto Size enabled.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.BoolValue = (GetMfdWidget(c, p) as ILabelWidget)?.AutoSize ?? false;
			};
			AddProperty("Mfd.SetLabel", "Auto Size", "Mfd.Label.SetAutoSize", ListItemInfoType.Bool, "Enables or disables Auto Size, which automatically changes the size of the text to fill the full extents of the label widget.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				ILabelWidget labelWidget = GetMfdWidget(c, n) as ILabelWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (labelWidget != null)
				{
					labelWidget.AutoSize = expressionResult.BoolValue;
				}
			};
			AddProperty("Mfd.SetNavball", "Top Color", "Mfd.Navball.TopColor", ListItemInfoType.Vector, "Sets the top background color of the navball.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				INavballWidget navballWidget = GetMfdWidget(c, n) as INavballWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (navballWidget != null)
				{
					navballWidget.TopColor = expressionResult.VectorValue.ToVector3();
				}
			};
			AddProperty("Mfd.SetNavball", "Bottom Color", "Mfd.Navball.BottomColor", ListItemInfoType.Vector, "Sets the bottom background color of the navball.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				INavballWidget navballWidget = GetMfdWidget(c, n) as INavballWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (navballWidget != null)
				{
					navballWidget.BottomColor = expressionResult.VectorValue.ToVector3();
				}
			};
			AddProperty("Mfd.SetMap", "North Up", "Mfd.Map.NorthUp", ListItemInfoType.Bool, "Sets whether the map will north up, or track the craft's heading. Overriden by Manual Mode.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMapWidget mapWidget = GetMfdWidget(c, n) as IMapWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (mapWidget != null)
				{
					mapWidget.NorthUp = expressionResult.BoolValue;
				}
			};
			AddProperty("Mfd.SetMap", "Zoom", "Mfd.Map.Zoom", ListItemInfoType.Number, "Sets the zoom level of the map. This should be a value between 1 and 5.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMapWidget mapWidget = GetMfdWidget(c, n) as IMapWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (mapWidget != null)
				{
					mapWidget.Zoom = (float)expressionResult.NumberValue;
				}
			};
			AddProperty("Mfd.SetMap", "Manual Mode", "Mfd.Map.ManualMode", ListItemInfoType.Bool, "If this is set to true, the map won't track the craft, but will respond to the inputs changed with the other properties on this block.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMapWidget mapWidget = GetMfdWidget(c, n) as IMapWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (mapWidget != null)
				{
					mapWidget.ManualMode = expressionResult.BoolValue;
				}
			};
			AddProperty("Mfd.SetMap", "Planet", "Mfd.Map.PlanetName", ListItemInfoType.Text, "Sets the name of the planet to show a map of. Requires Manual Mode to be on.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMapWidget mapWidget = GetMfdWidget(c, n) as IMapWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (mapWidget != null)
				{
					mapWidget.PlanetName = expressionResult.TextValue;
				}
			};
			AddProperty("Mfd.SetMap", "Coordinates", "Mfd.Map.Coordinates", ListItemInfoType.Vector, "These are the lat/long coordinates in degrees of the point to centre the map on. Requires Manual Mode to be on.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMapWidget mapWidget = GetMfdWidget(c, n) as IMapWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (mapWidget != null)
				{
					mapWidget.Coordinates = (Vector2d)expressionResult.VectorValue;
				}
			};
			AddProperty("Mfd.SetMap", "Heading", "Mfd.Map.Heading", ListItemInfoType.Number, "The heading to display as up on the map. Requires Manual Mode to be on.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMapWidget mapWidget = GetMfdWidget(c, n) as IMapWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (mapWidget != null)
				{
					mapWidget.Heading = (float)expressionResult.NumberValue;
				}
			};
			AddProperty("Mfd.ConvertPosition", "Local to Display", "Mfd.LocaltoDisplay", ListItemInfoType.Vector, "Converts from the widget's local position to the display's global position.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, p);
				ExpressionResult expressionResult = p.GetExpression(1).Evaluate(c);
				if (mfdWidget != null)
				{
					e.VectorValue = mfdWidget.ConvertLocalToDisplay(expressionResult.VectorValue.ToVector3());
				}
			};
			AddProperty("Mfd.ConvertPosition", "Display to Local", "Mfd.DisplayToLocal", ListItemInfoType.Vector, "Converts from the display's global position to the widget's local position.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, p);
				ExpressionResult expressionResult = p.GetExpression(1).Evaluate(c);
				if (mfdWidget != null)
				{
					e.VectorValue = mfdWidget.ConvertDisplayToLocal(expressionResult.VectorValue.ToVector3());
				}
			};
			Array values = Enum.GetValues(typeof(ElementAlignment));
			foreach (object item in values)
			{
				ElementAlignment alignment = (ElementAlignment)item;
				AddProperty("Mfd.SetWidget.Anchor", alignment.ToString(), $"Mfd.Widget.SetAnchor.{alignment}", ListItemInfoType.None, $"Sets the anchor of the widget inside its parent to the {alignment}.").Setter = delegate(IThreadContext c, ProgramNode n)
				{
					GetMfdWidget(c, n)?.SetAnchor(alignment);
				};
			}
			foreach (object item2 in values)
			{
				ElementAlignment alignment2 = (ElementAlignment)item2;
				AddProperty("Mfd.SetLabel.Alignment", alignment2.ToString(), $"Mfd.Label.SetAlignment.{alignment2}", ListItemInfoType.None, $"Sets the alignment of the label to {alignment2}.").Setter = delegate(IThreadContext c, ProgramNode n)
				{
					if (GetMfdWidget(c, n) is ILabelWidget labelWidget)
					{
						labelWidget.TextAlignment = alignment2;
					}
				};
			}
			AddProperty("Mfd.Label", "Alignment", "Mfd.Label.Alignment", ListItemInfoType.Text, "Gets the alignment of the label.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.TextValue = (GetMfdWidget(c, p) as ILabelWidget)?.TextAlignment.ToString();
			};
			AddProperty("Mfd.Gauge", "Background Color", "Mfd.Gauge.BackgroundColor", ListItemInfoType.Vector, "The color of the MFD gauge background as a vector with (Red,Green,Blue) components, each ranging from 0 to 1.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.VectorValue = (GetMfdWidget(c, p) as IGaugeWidget)?.BackgroundColor ?? Vector3.zero;
			};
			AddProperty("Mfd.SetGauge", "Background Color", "Mfd.Gauge.SetBackgroundColor", ListItemInfoType.Vector, "Sets the color of the MFD gauge background as a vector with (Red,Green,Blue) components, each ranging from 0 to 1.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IGaugeWidget gaugeWidget = GetMfdWidget(c, n) as IGaugeWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (gaugeWidget != null)
				{
					gaugeWidget.BackgroundColor = expressionResult.VectorValue.ToVector3();
				}
			};
			AddProperty("Mfd.Gauge", "Color", "Mfd.Gauge.FillColor", ListItemInfoType.Vector, "The color of the MFD gauge fill as a vector with (Red,Green,Blue) components, each ranging from 0 to 1.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.VectorValue = (GetMfdWidget(c, p) as IGaugeWidget)?.FillColor ?? Vector3.zero;
			};
			AddProperty("Mfd.SetGauge", "Color", "Mfd.Gauge.SetFillColor", ListItemInfoType.Vector, "Sets the color of the MFD gauge fill as a vector with (Red,Green,Blue) components, each ranging from 0 to 1.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IGaugeWidget gaugeWidget = GetMfdWidget(c, n) as IGaugeWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (gaugeWidget != null)
				{
					gaugeWidget.FillColor = expressionResult.VectorValue.ToVector3();
				}
			};
			AddProperty("Mfd.Gauge", "Text", "Mfd.Gauge.Text", ListItemInfoType.Text, "The text of the gauge widget.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.TextValue = (GetMfdWidget(c, p) as IGaugeWidget)?.Text;
			};
			AddProperty("Mfd.SetGauge", "Text", "Mfd.Gauge.SetText", ListItemInfoType.Text, "Sets the text of the gauge widget).").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IGaugeWidget gaugeWidget = GetMfdWidget(c, n) as IGaugeWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (gaugeWidget != null)
				{
					gaugeWidget.Text = expressionResult.TextValue;
				}
			};
			AddProperty("Mfd.Gauge", "Text Color", "Mfd.Gauge.TextColor", ListItemInfoType.Vector, "The color of the MFD gauge needle as a vector with (Red,Green,Blue) components, each ranging from 0 to 1.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.VectorValue = (GetMfdWidget(c, p) as IGaugeWidget)?.TextColor ?? Vector3.zero;
			};
			AddProperty("Mfd.SetGauge", "Text Color", "Mfd.Gauge.SetTextColor", ListItemInfoType.Vector, "Sets the color of the MFD gauge needle as a vector with (Red,Green,Blue) components, each ranging from 0 to 1.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IGaugeWidget gaugeWidget = GetMfdWidget(c, n) as IGaugeWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (gaugeWidget != null)
				{
					gaugeWidget.TextColor = expressionResult.VectorValue.ToVector3();
				}
			};
			AddProperty("Mfd.Gauge", "Value", "Mfd.Gauge.Value", ListItemInfoType.Number, "The current value of the gauge, from 0 (min) to 1 (max).").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				e.NumberValue = (GetMfdWidget(c, p) as IGaugeWidget)?.Value ?? 0f;
			};
			AddProperty("Mfd.SetGauge", "Value", "Mfd.Gauge.SetValue", ListItemInfoType.Number, "Sets the current value of the gauge, from 0 (min) to 1 (max).").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IGaugeWidget gaugeWidget = GetMfdWidget(c, n) as IGaugeWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				if (gaugeWidget != null)
				{
					gaugeWidget.Value = (float)expressionResult.NumberValue;
				}
			};
			AddProperty("Mfd.SetTexture", "Initialize", "Mfd.Texture.Initialize", ListItemInfoType.Number, "Initializes the texture to the specified size.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				ITextureWidget textureWidget = GetMfdWidget(c, n) as ITextureWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				ExpressionResult expressionResult2 = n.GetExpression(2).Evaluate(c);
				textureWidget?.Initialize((int)expressionResult.NumberValue, (int)expressionResult2.NumberValue);
			};
			AddProperty("Mfd.SetTexture", "Set Pixel", "Mfd.Texture.SetPixel", ListItemInfoType.Number, "Sets the pixel at the coordinates to the specified color. Note: Coordinates start at 1, not 0.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				ITextureWidget textureWidget = GetMfdWidget(c, n) as ITextureWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				ExpressionResult expressionResult2 = n.GetExpression(2).Evaluate(c);
				ExpressionResult expressionResult3 = n.GetExpression(3).Evaluate(c);
				textureWidget?.SetPixel((int)expressionResult.NumberValue, (int)expressionResult2.NumberValue, expressionResult3.VectorValue.ToVector3());
			};
			AddProperty("Mfd.SetTexture", "Draw Line", "Mfd.Texture.DrawLine", ListItemInfoType.Number, "Draws a line in the specified color between the coordinates. Note: Coordinates start at 1, not 0.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				ITextureWidget textureWidget = GetMfdWidget(c, n) as ITextureWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				ExpressionResult expressionResult2 = n.GetExpression(2).Evaluate(c);
				ExpressionResult expressionResult3 = n.GetExpression(3).Evaluate(c);
				ExpressionResult expressionResult4 = n.GetExpression(4).Evaluate(c);
				ExpressionResult expressionResult5 = n.GetExpression(5).Evaluate(c);
				textureWidget?.DrawLine((int)expressionResult.NumberValue, (int)expressionResult2.NumberValue, (int)expressionResult3.NumberValue, (int)expressionResult4.NumberValue, expressionResult5.VectorValue.ToVector3());
			};
			AddProperty("Mfd.SetTexture", "Draw Box", "Mfd.Texture.DrawBox", ListItemInfoType.Number, "Draws a box in the specified color between the coordinates. Note: Coordinates start at 1, not 0.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				ITextureWidget textureWidget = GetMfdWidget(c, n) as ITextureWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				ExpressionResult expressionResult2 = n.GetExpression(2).Evaluate(c);
				ExpressionResult expressionResult3 = n.GetExpression(3).Evaluate(c);
				ExpressionResult expressionResult4 = n.GetExpression(4).Evaluate(c);
				ExpressionResult expressionResult5 = n.GetExpression(5).Evaluate(c);
				textureWidget?.DrawBox((int)expressionResult.NumberValue, (int)expressionResult2.NumberValue, (int)expressionResult3.NumberValue, (int)expressionResult4.NumberValue, expressionResult5.VectorValue.ToVector3());
			};
			AddProperty("Mfd.SetTexture", "Draw Triangle", "Mfd.Texture.DrawTri", ListItemInfoType.Number, "Draws a triangle in the specified color between the coordinates. Note: Coordinates start at 1, not 0.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				ITextureWidget textureWidget = GetMfdWidget(c, n) as ITextureWidget;
				ExpressionResult expressionResult = n.GetExpression(1).Evaluate(c);
				ExpressionResult expressionResult2 = n.GetExpression(2).Evaluate(c);
				ExpressionResult expressionResult3 = n.GetExpression(3).Evaluate(c);
				textureWidget?.DrawTri(expressionResult.VectorValue.ToVector3(), expressionResult2.VectorValue.ToVector3(), expressionResult3.VectorValue.ToVector3());
			};
			AddProperty("Mfd.GetTexture", "Get Pixel", "Mfd.Texture.GetPixel", ListItemInfoType.Vector, "Gets the pixel at the coordinates. Note: Coordinates start at 1, not 0.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				ITextureWidget textureWidget = GetMfdWidget(c, p) as ITextureWidget;
				ExpressionResult expressionResult = p.GetExpression(1).Evaluate(c);
				ExpressionResult expressionResult2 = p.GetExpression(2).Evaluate(c);
				if (textureWidget != null)
				{
					e.VectorValue = textureWidget.GetPixel((int)expressionResult.NumberValue, (int)expressionResult2.NumberValue);
				}
			};
			AddProperty("Mfd.Create", "Ellipse", "Mfd.Create.Ellipse", ListItemInfoType.Text, "Creates an ellipse sprite on the MFD with the specified name.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				c.Craft.CreateMfdWidget(MfdWidgetType.Sprite, n.GetExpression(0).Evaluate(c).TextValue, "Ui/Sprites/Circle");
			};
			AddProperty("Mfd.Create", "Label", "Mfd.Create.Label", ListItemInfoType.Text, "Creates a label on the MFD with the specified name.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				c.Craft.CreateMfdWidget(MfdWidgetType.Label, n.GetExpression(0).Evaluate(c).TextValue, null);
			};
			AddProperty("Mfd.Create", "Line", "Mfd.Create.Line", ListItemInfoType.Text, "Creates a line on the MFD with the specified name.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				c.Craft.CreateMfdWidget(MfdWidgetType.Line, n.GetExpression(0).Evaluate(c).TextValue, null);
			};
			AddProperty("Mfd.Create", "Radial Gauge", "Mfd.Create.RadialGauge", ListItemInfoType.Text, "Creates a radial gauge on the MFD with the specified name.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				c.Craft.CreateMfdWidget(MfdWidgetType.RadialGauge, n.GetExpression(0).Evaluate(c).TextValue, null);
			};
			AddProperty("Mfd.Create", "Rectangle", "Mfd.Create.Rectangle", ListItemInfoType.Text, "Creates a rectangle sprite on the MFD with the specified name.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				c.Craft.CreateMfdWidget(MfdWidgetType.Sprite, n.GetExpression(0).Evaluate(c).TextValue, "Ui/Sprites/Common/White");
			};
			AddProperty("Mfd.Create", "Texture", "Mfd.Create.Texture", ListItemInfoType.Text, "Creates a blank texture on the MFD with the specified name.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				c.Craft.CreateMfdWidget(MfdWidgetType.Texture, n.GetExpression(0).Evaluate(c).TextValue, null);
			};
			AddProperty("Mfd.Create", "Navball", "Mfd.Create.Navball", ListItemInfoType.Text, "Creates a navball on the MFD with the specified name.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				c.Craft.CreateMfdWidget(MfdWidgetType.Navball, n.GetExpression(0).Evaluate(c).TextValue, null);
			};
			AddProperty("Mfd.Create", "Map", "Mfd.Create.Map", ListItemInfoType.Text, "Creates a map on the MFD with the specified name.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				c.Craft.CreateMfdWidget(MfdWidgetType.Map, n.GetExpression(0).Evaluate(c).TextValue, null);
			};
			AddProperty("Mfd.Order", "Bring to Front", "Mfd.Order.SendToFront", ListItemInfoType.Text, "Brings the widget in front of the target widget.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, n);
				if (mfdWidget != null)
				{
					IMfdWidget mfdWidget2 = GetMfdWidget(c, n, 1);
					mfdWidget.SetWidgetOrder(mfdWidget2, front: true);
				}
			};
			AddProperty("Mfd.Order", "Send Behind", "Mfd.Order.SendToBack", ListItemInfoType.Text, "Sends the widget behind the target widget.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				IMfdWidget mfdWidget = GetMfdWidget(c, n);
				if (mfdWidget != null)
				{
					IMfdWidget mfdWidget2 = GetMfdWidget(c, n, 1);
					mfdWidget.SetWidgetOrder(mfdWidget2, front: false);
				}
			};
			AddProperty("Mfd.Destroy", "Destroy Widget", "Mfd.Destroy", ListItemInfoType.Text, "Destroys a widget on the MFD with the specified name. This will also destroy child widgets, if the widget has any.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				c.Craft.GetMfdWidget(n.GetExpression(0).Evaluate(c).TextValue)?.Destroy();
			};
			AddProperty("Mfd.Destroy.All", "Destroy All Widgets", "Mfd.Destroy.All", ListItemInfoType.Text, "Destroys all widgets on the MFD.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				foreach (IMfdWidget mfdChildWidget in c.Craft.GetMfdChildWidgets(null))
				{
					mfdChildWidget.Destroy();
				}
			};
			AddProperty("Sound.Beep", "Beep", "Sound.Beep", ListItemInfoType.None, "Plays a beep sound.").Setter = delegate(IThreadContext c, ProgramNode n)
			{
				c.Craft.PlayBeepSound((float)n.GetExpression(0).Evaluate(c).NumberValue, (float)n.GetExpression(1).Evaluate(c).NumberValue, (float)n.GetExpression(2).Evaluate(c).NumberValue);
			};
			AddProperty("Sound.Frequency", "Frequency", "Sound.Frequency", ListItemInfoType.None, "Gets the frequency of the sound.").Getter = delegate(IThreadContext c, ExpressionResult e, ProgramNode p)
			{
				string textValue = p.GetExpression(0).Evaluate(c).TextValue;
				int octave = (int)p.GetExpression(1).Evaluate(c).NumberValue;
				e.NumberValue = GetFrequencyOfNote(textValue, octave, c);
			};
		}

		public static CraftProperty AddProperty(string category, string name, string xmlName, ListItemInfoType itemType, string tooltip)
		{
			if (GetProperty(xmlName) != null)
			{
				throw new ArgumentException($"The craft property with XML name {xmlName} already exists");
			}
			CraftProperty craftProperty = new CraftProperty
			{
				Category = category,
				DisplayName = name,
				XmlName = xmlName,
				Tooltip = tooltip,
				ItemType = itemType
			};
			_properties.Add(craftProperty);
			return craftProperty;
		}

		public static List<CraftProperty> GetPropertiesInCategory(string category)
		{
			return _properties.Where((CraftProperty x) => x.Category == category).ToList();
		}

		public static CraftProperty GetProperty(string xmlName)
		{
			return _properties.Where((CraftProperty x) => x.XmlName == xmlName).FirstOrDefault();
		}

		private static ICraftNode GetCraftNodeById(ProgramNode node, IThreadContext context, int expressionIndex)
		{
			ExpressionResult expressionResult = node.GetExpression(expressionIndex).Evaluate(context);
			if (!string.IsNullOrWhiteSpace(expressionResult.TextValue))
			{
				int craftNodeId = (int)expressionResult.NumberValue;
				return context.Craft.GetCraftNode(craftNodeId);
			}
			return context.Craft.CraftScript.CraftNode;
		}

		private static ICraftNode GetCraftNodeByName(ProgramNode node, IThreadContext context, int expressionIndex)
		{
			string textValue = node.GetExpression(expressionIndex).Evaluate(context).TextValue;
			return context.Craft.GetCraftNodeByName(textValue);
		}

		private static double GetDoubleValue(double x, bool allowNegative = true)
		{
			if (double.IsNaN(x) || double.IsInfinity(x))
			{
				return 0.0;
			}
			if (!allowNegative && x < 0.0)
			{
				return 0.0;
			}
			return x;
		}

		private static double GetFrequencyOfNote(string note, int octave, IThreadContext c)
		{
			int num = Array.IndexOf(new string[12]
			{
				"C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A",
				"A#", "B"
			}, note) + 1;
			if (num >= 0)
			{
				return 440f * Mathf.Pow(2f, ((float)num - 10f) / 12f + ((float)octave - 4f));
			}
			c.Log.LogError("Unknown note: " + note);
			return 0.0;
		}

		private static IMfdWidget GetMfdWidget(IThreadContext context, ProgramNode node, int expressionIndex = 0)
		{
			string textValue = node.GetExpression(expressionIndex).Evaluate(context).TextValue;
			return context.Craft.GetMfdWidget(textValue);
		}

		private static PartData GetPartById(ProgramNode node, IThreadContext context, int expressionIndex)
		{
			ExpressionResult expressionResult = node.GetExpression(expressionIndex).Evaluate(context);
			if (!string.IsNullOrWhiteSpace(expressionResult.TextValue))
			{
				int partId = (int)expressionResult.NumberValue;
				return context.Craft.CraftScript.Data.Assembly.GetPartById(partId);
			}
			return context.Craft.ExecutingPart;
		}

		private static PartData GetPartByName(ProgramNode node, IThreadContext context, int expressionIndex)
		{
			string textValue = node.GetExpression(expressionIndex).Evaluate(context).TextValue;
			return context.Craft.CraftScript.Data.Assembly.GetPartByName(textValue);
		}

		private static Vector3 LimitVector(Vector3 v, bool allowNegative = true)
		{
			v.x = (float)GetDoubleValue(v.x, allowNegative);
			v.y = (float)GetDoubleValue(v.y, allowNegative);
			v.z = (float)GetDoubleValue(v.z, allowNegative);
			return v;
		}

		private static Vector3d Vec(Vector3d? v)
		{
			if (!v.HasValue)
			{
				return Vector3d.zero;
			}
			return v.Value;
		}

		private static Vector3d Vector2ToVector3d(Vector2? v)
		{
			if (v.HasValue)
			{
				return new Vector3d(v.Value.x, v.Value.y, 0f);
			}
			return Vector3d.zero;
		}
	}
}
