internal sealed class qGEOhRMUNbLYcxEtNODhqLYlDIQKA
{
	public static readonly uSAsLuAHxLQJwBfAMELHgmAkwgYO zAVGMbQCjgSHtVBbMhOpujcTCOuv = cNuJhSHeILHUroVUpRJlbGoRBRFy.UYkgcvdWFMQJKURMnLjUdbAHEYTtA(apcyszDglelGKiPGDxvByqEjHIei.DeviceNotConnected);
}
