using System;
using Rewired.Internal.Localization;
using UnityEngine;

namespace Rewired
{
	[Serializable]
	public sealed class InputLayout : LnhaMJXLiFbdSGpizhhMTtFDjtXy
	{
		private const string keyCategory = "controller_map/layout";

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _name;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _descriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _key;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private int _id;

		[NonSerialized]
		private CMZFLplsuqkvbBvNYmZBVurZoVpI PGaPOxmERLWloeHiEFUjMFrjhSWD;

		[NonSerialized]
		private int gCnKCciNvJznJxcRNrhbgTcFhtMm;

		public string name
		{
			get
			{
				return _name;
			}
			internal set
			{
				_name = text;
			}
		}

		public string descriptiveName
		{
			get
			{
				if (!ReInput.isReady || !LocalizationManager.isEnabled || PGaPOxmERLWloeHiEFUjMFrjhSWD == null)
				{
					return _descriptiveName;
				}
				return PGaPOxmERLWloeHiEFUjMFrjhSWD.qJkqRAxrrocPcPhIKAOpCMJUoZxfA;
			}
			internal set
			{
				nonLocalizedDescriptiveName = text;
			}
		}

		public int id
		{
			get
			{
				return _id;
			}
			internal set
			{
				_id = num;
			}
		}

		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return _key;
			}
			set
			{
				_key = value;
				if (ReInput.isReady && PGaPOxmERLWloeHiEFUjMFrjhSWD != null)
				{
					PGaPOxmERLWloeHiEFUjMFrjhSWD.VFHulbCONdrHnQmgMqwKyHtRlYIr();
				}
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
				if (ReInput.isReady && PGaPOxmERLWloeHiEFUjMFrjhSWD != null)
				{
					PGaPOxmERLWloeHiEFUjMFrjhSWD.wkNCiIKcomvvEiZxnJmXtmqxRPdW();
				}
			}
		}

		string LnhaMJXLiFbdSGpizhhMTtFDjtXy.keyCategory => "controller_map/layout";

		string LnhaMJXLiFbdSGpizhhMTtFDjtXy.scriptingName => _name;

		string LnhaMJXLiFbdSGpizhhMTtFDjtXy.nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
			}
		}

		string LnhaMJXLiFbdSGpizhhMTtFDjtXy.key => _key;

		int LnhaMJXLiFbdSGpizhhMTtFDjtXy.autoGeneratedValueFlags
		{
			get
			{
				return gCnKCciNvJznJxcRNrhbgTcFhtMm;
			}
			set
			{
				gCnKCciNvJznJxcRNrhbgTcFhtMm = value;
			}
		}

		public InputLayout()
		{
		}

		public InputLayout(InputLayout P_0)
			: this()
		{
			_name = P_0._name;
			_descriptiveName = P_0._descriptiveName;
			_key = P_0._key;
			_id = P_0._id;
			gCnKCciNvJznJxcRNrhbgTcFhtMm = P_0.gCnKCciNvJznJxcRNrhbgTcFhtMm;
		}

		public InputLayout Clone()
		{
			return new InputLayout(this);
		}

		internal void EjwXzgfRwWFXVgEjFOkecAxCWPrs()
		{
			PGaPOxmERLWloeHiEFUjMFrjhSWD = CMZFLplsuqkvbBvNYmZBVurZoVpI.mcPyJtFwDcyGtHKiRQGaIYyPGBGg(this);
		}

		internal void HupcOpKgIoLCqRUpzQkaEAYSkBnQA()
		{
		}
	}
}
