using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Xml.Linq;
using ModApi.Common.Animation;
using ModApi.Common.Extensions;
using ModApi.Packages.FastNoise;
using ModApi.Planet.Modifiers.Attributes;
using ModApi.Ui.Inspector;
using UnityEngine;

namespace ModApi.Planet.Modifiers.VertexData
{
	[PlanetModifierInfo("Craters 1", "A planet modifier used for generating craters. This supports multiple passes but each pass uses the same configuration (with different noise seed values).This modifier supports highly configurable noise for adjusting the shape of the craters.")]
	public class Craters : VertexDataNoise, ICustomObjectInspectorModel, IDataSlotConfiguration
	{
		private static List<FieldInfo> _dataSlotFields;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Shape", Order = 0, Tooltip = "The curve that craters will resembly. This is typically a curve mapped between (0,-1) and (1,0).The x-axis represents distance from the center of the crater and the y-axis represents the depth of the crater.The left side of the curve, starting at 0, represents the center of the craters.The right side of the curve, which should typically end at 1, represents the end of the rims of the craters. The bottom of the curve, starting at -1, represents the deepest part of the craters. The top of the curve, ending at 0, represents the regular surface of the planet.")]
		private AnimationCurve _craterCurve;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Frequency", Order = 50, Tooltip = "The frequency of the noise that generates the crater positions and sizes. The higher the frequency, the smaller and more numerous the craters become.")]
		private double _craterFrequency = 5.0;

		[SerializeField]
		[Range(-1f, 9f)]
		[DataSlot(DataSlotType.Input, "Crater Mask Input", true, true, Order = 0, Tooltip = "The data input value that, if used, can mask out the craters generated by this modifier. This is typically a value between zero and one where one represents full strength un-masked craters and zero results in this modifier changing nothing.")]
		private int _craterMaskDataIndex = -1;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Max Depth", Order = 10, Tooltip = "The maximum depth of the crater in meters. This occurs when the crater shape curve evaluates to -1 on the y-axis.")]
		private float _craterMaxDepth = 500f;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Noise Exponent", Order = 60, Tooltip = "The exponent applied to the crater positional noise. This is used to help prevent seams between craters.")]
		private double _craterNoisePowerValue = 8.0;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Shape Noise Strength", Order = 20, Tooltip = "The strength of the crater shape noise. The crater shape noise is what adds the noise to the shapes of the craters so that they are not perfectly circular. The crater shape noise is very configurable and this value provides an easy way to adjust the final strength of that noise.")]
		private double _craterNoiseStrength = 1.0;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Number of Passes", Order = 30, Tooltip = "The number of crater passes to perform. Crater passes are expensive so use sparingly, however, multiple crater passes are cheaper than using that same number of crater modifiers with a single pass to get a similar effect. Craters within a single pass cannot overlap but there can be overlap of craters between different passes.")]
		private int _craterPasses = 1;

		[SerializeField]
		[InspectorGroup("Crater Position Noise")]
		[InspectorProperty(null, false, Label = "Noise Seed", Order = 40, Tooltip = "The seed value used for the cellular noise that generates the crater positions and sizes.")]
		private int _craterSeed;

		private AnimationCurveSampler _curveSampler;

		private bool _hasMaxHeightColorVariance;

		private bool _hasMinHeightColorVariance;

		[SerializeField]
		[Range(-1f, 9f)]
		[DataSlot(DataSlotType.Output, "Height Noise Sum Output", true, true, Order = 10, Tooltip = "The data output that, if used, will be populated by the sum of the crater height noise from all passes. This is the value that, if mulitplied by the crater max depth and the final crater strength value, results in the final height adjustment applied by this modifier. This isn't always useful, but in certain situations it can be. For instance, if you have a single pass crater, this value can help you identify where craters arein such a way that it can be input into a biome modifier to generate biomes for inside and outside of craters.")]
		private int _heightNoiseOutputDataIndex = -1;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Max Height Color Variance", Order = 80, Tooltip = "The red, green, and blue color values (from 0 to 1) to add to the terrain color as the crater extends above the planet's surface. This is useful for adding a bit of color variation to the crater rims.")]
		private Vector3 _maxHeightColorVariance = new Vector3(0f, 0f, 0f);

		[SerializeField]
		[InspectorGroup("Crater Colors")]
		[InspectorProperty(null, false, Label = "Min Height Color Variance", Order = 70, Tooltip = "The red, green, and blue color values (from 0 to 1) to subtract from the terrain color as it reaches its minimum height for the craters. This is useful for adding a bit of color variation to the deep centers of the craters")]
		private Vector3 _minHeightColorVariance = new Vector3(0f, 0f, 0f);

		private IFastNoise[] _noise;

		private float _surfaceHeight;

		public bool CreateGroup => false;

		public override VertexDataPlanetModifierPassType[] SupportedPassTypes => new VertexDataPlanetModifierPassType[3]
		{
			VertexDataPlanetModifierPassType.Biome,
			VertexDataPlanetModifierPassType.Height,
			VertexDataPlanetModifierPassType.HeightFinal
		};

		public Craters()
		{
			base.VisibleInBasicViewMode = false;
		}

		public void CreateModel(GroupModel model, IObjectInspector objectInspector)
		{
			GroupModel groupModel = model.Add(new GroupModel("Craters"));
			GroupModel groupModel2 = groupModel;
			foreach (ObjectInspectorFieldInfo inspectorField in objectInspector.GetInspectorFields(typeof(Craters)))
			{
				if (objectInspector.PreprocessField(this, inspectorField.Field))
				{
					if (!string.IsNullOrWhiteSpace(inspectorField.GroupName))
					{
						groupModel2 = groupModel.Add(new GroupModel(inspectorField.GroupName));
					}
					objectInspector.BuildModelForField(inspectorField.Field, groupModel2, this, inspectorField.Label);
				}
			}
			GroupModel groupModel3 = groupModel.Add(new GroupModel("Crater Shape Noise"));
			foreach (FieldInfo inspectorField2 in GetInspectorFields())
			{
				if (objectInspector.PreprocessField(this, inspectorField2))
				{
					objectInspector.BuildModelForField(inspectorField2, groupModel3, this);
				}
			}
		}

		public void GetDataSlots(List<DataSlotField> dataSlots)
		{
			if (_dataSlotFields == null)
			{
				_dataSlotFields = new List<FieldInfo>();
				_dataSlotFields.Add(typeof(Craters).GetField("_craterMaskDataIndex", BindingFlags.Instance | BindingFlags.NonPublic));
				_dataSlotFields.Add(typeof(Craters).GetField("_heightNoiseOutputDataIndex", BindingFlags.Instance | BindingFlags.NonPublic));
				_dataSlotFields.Add(typeof(VertexDataNoise).GetField("_dataIndex", BindingFlags.Instance | BindingFlags.NonPublic));
			}
			dataSlots.AddRange(_dataSlotFields.Select((FieldInfo x) => new DataSlotField(this, x.GetCustomAttribute<DataSlotAttribute>(), x)));
			dataSlots[2].Attribute.Name = "Crater Noise Output";
		}

		public override void GetVertexData(PlanetVertexDataInput input, PlanetVertexData data)
		{
			float num = 1f;
			if (_craterMaskDataIndex != -1)
			{
				num = (float)data.Data[_craterMaskDataIndex];
				if (num <= 0f)
				{
					if (base.DataIndex != -1)
					{
						data.Data[base.DataIndex] = 0.0;
					}
					if (_heightNoiseOutputDataIndex != -1)
					{
						data.Data[_heightNoiseOutputDataIndex] = 0.0;
					}
					return;
				}
			}
			Vector3d position = input.Position;
			double noise = GetNoise(position.x, position.y, position.z, data.Data, data.CacheData);
			float num2 = 0f;
			float num3 = 0f;
			float num4 = 0f;
			for (int i = 0; i < _craterPasses; i++)
			{
				double noise2 = _noise[i].GetNoise(position.x, position.y, position.z);
				double num5 = System.Math.Pow(noise2, _craterNoisePowerValue) * _craterNoiseStrength;
				double num6 = noise2 + (noise + num5) * _craterNoiseStrength;
				float num7 = _curveSampler.Sample((float)num6);
				num7 -= _surfaceHeight;
				num2 += num7;
				if (num7 < num4)
				{
					num4 = num7;
					num3 = 0f;
				}
				else if (num7 > num3)
				{
					num3 = num7;
				}
			}
			data.Height += num2 * _craterMaxDepth * num;
			if (_hasMaxHeightColorVariance && (double)num3 > 0.001)
			{
				Vector3 vector = _maxHeightColorVariance * (num3 * num);
				data.Color.r += vector.x;
				data.Color.g += vector.y;
				data.Color.b += vector.z;
			}
			if (_hasMinHeightColorVariance && (double)num4 < -0.001)
			{
				Vector3 vector2 = _minHeightColorVariance * (num4 * num);
				data.Color.r += vector2.x;
				data.Color.g += vector2.y;
				data.Color.b += vector2.z;
			}
			if (base.DataIndex != -1)
			{
				data.Data[base.DataIndex] = noise;
			}
			if (_heightNoiseOutputDataIndex != -1)
			{
				data.Data[_heightNoiseOutputDataIndex] = num2;
			}
		}

		public override void GetVertexData(PlanetVertexDataInput input, PlanetBiomeVertexData data)
		{
			float num = 1f;
			if (_craterMaskDataIndex != -1)
			{
				num = (float)data.Data[_craterMaskDataIndex];
				if (num <= 0f)
				{
					return;
				}
			}
			Vector3d position = input.Position;
			double noise = GetNoise(position.x, position.y, position.z, data.Data, data.CommonData.CacheData);
			float num2 = 0f;
			float num3 = 0f;
			float num4 = 0f;
			for (int i = 0; i < _craterPasses; i++)
			{
				double noise2 = _noise[i].GetNoise(position.x, position.y, position.z);
				double num5 = System.Math.Pow(noise2, _craterNoisePowerValue) * _craterNoiseStrength;
				double num6 = noise2 + (noise + num5) * _craterNoiseStrength;
				float num7 = _curveSampler.Sample((float)num6);
				num7 -= _surfaceHeight;
				num2 += num7;
				if (num7 < num4)
				{
					num4 = num7;
					num3 = 0f;
				}
				else if (num7 > num3)
				{
					num3 = num7;
				}
			}
			data.Height += num2 * _craterMaxDepth * num;
			if (_hasMaxHeightColorVariance && (double)num3 > 0.001)
			{
				Vector3 vector = _maxHeightColorVariance * (num3 * num);
				data.Color.r += vector.x;
				data.Color.g += vector.y;
				data.Color.b += vector.z;
			}
			if (_hasMinHeightColorVariance && (double)num4 < -0.001)
			{
				Vector3 vector2 = _minHeightColorVariance * (num4 * num);
				data.Color.r += vector2.x;
				data.Color.g += vector2.y;
				data.Color.b += vector2.z;
			}
			if (base.DataIndex != -1)
			{
				data.Data[base.DataIndex] = noise;
			}
			if (_heightNoiseOutputDataIndex != -1)
			{
				data.Data[_heightNoiseOutputDataIndex] = num2;
			}
		}

		public override void Initialize(IPlanetData planetData)
		{
			base.Initialize(planetData);
			_noise = new IFastNoise[_craterPasses];
			for (int i = 0; i < _craterPasses; i++)
			{
				_noise[i] = FastNoise.CreateCellularNoise(_craterSeed + i, _craterFrequency, CellularDistanceFunction.EuclideanNoOverlap, CellularReturnType.Distance);
			}
			_curveSampler = new AnimationCurveSampler(_craterCurve);
			_surfaceHeight = _curveSampler.Sample(_curveSampler.SampleRangeMaxValue);
			_hasMaxHeightColorVariance = !Utilities.CompareVector3s(_maxHeightColorVariance, Vector3.zero);
			_hasMinHeightColorVariance = !Utilities.CompareVector3s(_minHeightColorVariance, Vector3.zero);
			if (_craterNoisePowerValue < 1.0)
			{
				_craterNoisePowerValue = 1.0;
			}
		}

		public override Vector2d LegacyGetMinMaxHeight(Vector2d minMaxHeight)
		{
			return minMaxHeight + new Vector2d(0f - _craterMaxDepth, (1f - _surfaceHeight) * _craterMaxDepth);
		}

		public override void OnCreatingInPlanetStudio(PlanetTerrainDataScript terrainData, VertexDataPlanetModifier parentModifier)
		{
			base.OnCreatingInPlanetStudio(terrainData, parentModifier);
			XElement element = new XElement("Defaults", new XAttribute("craterCurve", "0,-1,0,0,0,0,0,0|0.85,0.05,2.438755,2.438755,0,0,0,0|0.88,0.05,-0.9733779,-0.9733779,0,0,0,0|1,0,0,0,0,0,0,0"));
			_craterCurve = Utilities.GetAnimationCurveAttribute(element, "craterCurve");
			_craterFrequency = (int)(5.0 * (terrainData.PlanetData.Radius / 350000.0));
			base.NoiseType = NoiseType.PerlinFractal;
			base.FractalType = FractalType.FBM;
			base.Octaves = 4;
			base.Frequency = 60.0;
			base.DataIndex = -1;
		}

		public override bool Randomize(RandomizeContext context)
		{
			if (!base.LockSeed)
			{
				if (context.Flags.HasFlag(PlanetModifierRandomizationFlags.SeedValues))
				{
					_craterSeed = context.GetRandomInt((base.SeedSyncId != null) ? (base.SeedSyncId + "_CraterSeed") : null);
				}
				return base.Randomize(context);
			}
			return false;
		}

		public override void SaveXml(XElement xml)
		{
			base.SaveXml(xml);
			xml.SetAttributeValue("craterSeed", _craterSeed);
			xml.SetAttributeValue("craterFrequency", _craterFrequency);
			xml.SetAttributeValue("craterDepth", _craterMaxDepth);
			xml.SetAttributeValue("craterNoiseStrength", _craterNoiseStrength);
			xml.SetAttributeValue("craterNoisePowerValue", _craterNoisePowerValue);
			xml.SetAttributeValue("craterPasses", _craterPasses);
			xml.SetAttributeValue("craterMaskDataIndex", _craterMaskDataIndex);
			xml.SetAttributeValue("heightNoiseOutputDataIndex", _heightNoiseOutputDataIndex);
			xml.SetAttribute("maxHeightColorVariance", _maxHeightColorVariance);
			xml.SetAttribute("minHeightColorVariance", _minHeightColorVariance);
			Utilities.SetAnimationCurveAttribute(xml, "craterCurve", _craterCurve);
		}

		protected override void OnDestroy()
		{
			base.OnDestroy();
			IFastNoise[] noise = _noise;
			_noise = null;
			if (noise != null)
			{
				IFastNoise[] array = noise;
				for (int i = 0; i < array.Length; i++)
				{
					array[i]?.Dispose();
				}
			}
		}

		protected override void RestoreXml(XElement xml)
		{
			base.RestoreXml(xml);
			_craterSeed = (int)xml.Attribute("craterSeed");
			_craterFrequency = (double)xml.Attribute("craterFrequency");
			_craterMaxDepth = (float)xml.Attribute("craterDepth");
			_craterNoiseStrength = (double)xml.Attribute("craterNoiseStrength");
			_craterNoisePowerValue = (double)xml.Attribute("craterNoisePowerValue");
			_craterPasses = ((int?)xml.Attribute("craterPasses")) ?? 1;
			_craterMaskDataIndex = ((int?)xml.Attribute("craterMaskDataIndex")) ?? (-1);
			_heightNoiseOutputDataIndex = ((int?)xml.Attribute("heightNoiseOutputDataIndex")) ?? (-1);
			_maxHeightColorVariance = xml.GetVector3Attribute("maxHeightColorVariance");
			_minHeightColorVariance = xml.GetVector3Attribute("minHeightColorVariance");
			_craterCurve = Utilities.GetAnimationCurveAttribute(xml, "craterCurve");
			_craterMaxDepth *= base.PlanetScale;
		}
	}
}
