using System;
using System.Linq;
using System.Xml.Linq;
using ModApi.Planet.Modifiers.Attributes;
using ModApi.Ui.Inspector;
using UnityEngine;

namespace ModApi.Planet.Modifiers.VertexData
{
	[PlanetModifierInfo("Generate Height", "A planet modifier that is used to generate height values based of a data input and store those heights in a data output. This modifier does not directly update the terrain's height, rather it is typically followed by an 'Update Height' modifier to actually apply the height to the celestial body.")]
	public class GenerateHeight : VertexDataCommonPassPlanetModifier
	{
		[SerializeField]
		[Range(0f, 9f)]
		[DataSlot(DataSlotType.Input, "Input", false, true, Tooltip = "The input data value that is used to generate the heights.")]
		private int _dataIndexInput;

		[SerializeField]
		[Range(0f, 9f)]
		[DataSlot(DataSlotType.Output, "Output", false, true, Tooltip = "The data output that stores the generated height data.")]
		private int _dataIndexOutput;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Method", Order = 40, Tooltip = "The method used to interpret the data input and generate a height output. \n\nLerp Min To Max: The generated height is linearly interpolated from the minimum height to the maximum height based off the input value and its specified range. \n\nLerp To/From Zero: The generated height is linearly interpolated from the minimum height to zero if the input value is negative or linearly interpolated from zero to the maximum height if the input value is positive. This should not be used if the minimum and maximum heights to not span across zero.")]
		private GenerateHeightType _generateHeightType;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Max Input Value", Order = 30, Tooltip = "The maximum input value used to create the range by which the input value will be linearly interpolated.")]
		private double _inputMaxValue = 1.0;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Min Input Value", Order = 20, Tooltip = "The minimum input value used to create the range by which the input value will be linearly interpolated.")]
		private double _inputMinValue = -1.0;

		private double _inputRange;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Max Height", Order = 10, Tooltip = "The maximum height (in meters) generated by this modifier.")]
		private double _maxHeight = 1000.0;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Min Height", Order = 0, Tooltip = "The minimum height (in meters) generated by this modifier.")]
		private double _minHeight;

		public double MaxHeight
		{
			get
			{
				return _maxHeight;
			}
			set
			{
				_maxHeight = value;
			}
		}

		public double MinHeight
		{
			get
			{
				return _minHeight;
			}
			set
			{
				_minHeight = value;
			}
		}

		public override VertexDataPlanetModifierPassType[] SupportedPassTypes => new VertexDataPlanetModifierPassType[3]
		{
			VertexDataPlanetModifierPassType.Biome,
			VertexDataPlanetModifierPassType.Height,
			VertexDataPlanetModifierPassType.HeightFinal
		};

		public override VertexDataType VertexDataType => VertexDataType.Both;

		public GenerateHeight()
		{
			base.VisibleInBasicViewMode = true;
		}

		public override void GetVertexData(PlanetVertexDataInput input, PlanetVertexData data)
		{
			switch (_generateHeightType)
			{
			case GenerateHeightType.LerpMinToMax:
				data.Data[_dataIndexOutput] = Mathd.Lerp(_minHeight, _maxHeight, (data.Data[_dataIndexInput] - _inputMinValue) / _inputRange);
				break;
			case GenerateHeightType.LerpToFromZero:
			{
				double num = data.Data[_dataIndexInput];
				data.Data[_dataIndexOutput] = ((num < 0.0) ? Mathd.Lerp(_minHeight, 0.0, 1.0 - num / _inputMinValue) : Mathd.Lerp(0.0, _maxHeight, num / _inputMaxValue));
				break;
			}
			}
		}

		public override void GetVertexData(PlanetVertexDataInput input, PlanetBiomeVertexData data)
		{
			switch (_generateHeightType)
			{
			case GenerateHeightType.LerpMinToMax:
				data.Data[_dataIndexOutput] = Mathd.Lerp(_minHeight, _maxHeight, (data.Data[_dataIndexInput] - _inputMinValue) / _inputRange);
				break;
			case GenerateHeightType.LerpToFromZero:
			{
				double num = data.Data[_dataIndexInput];
				data.Data[_dataIndexOutput] = ((num < 0.0) ? Mathd.Lerp(_minHeight, 0.0, 1.0 - num / _inputMinValue) : Mathd.Lerp(0.0, _maxHeight, num / _inputMaxValue));
				break;
			}
			}
		}

		public override void Initialize(IPlanetData planetData)
		{
			base.Initialize(planetData);
			_inputRange = _inputMaxValue - _inputMinValue;
		}

		public override Vector2d LegacyGetMinMaxHeight(Vector2d minMaxHeight)
		{
			return new Vector2d(minMaxHeight.x + _minHeight, minMaxHeight.y + _maxHeight);
		}

		public override void OnCreatingInPlanetStudio(PlanetTerrainDataScript terrainData, VertexDataPlanetModifier parentModifier)
		{
			base.OnCreatingInPlanetStudio(terrainData, parentModifier);
			_dataIndexInput = (_dataIndexOutput = (parentModifier?.GetDataSlots().FirstOrDefault(delegate(DataSlotField x)
			{
				DataSlotAttribute attribute = x.Attribute;
				return attribute != null && attribute.DataSlotType == DataSlotType.Output && x.DataIndex >= 0;
			})?.DataIndex).GetValueOrDefault());
		}

		public override void SaveXml(XElement xml)
		{
			base.SaveXml(xml);
			xml.SetAttributeValue("generateHeightType", _generateHeightType);
			xml.SetAttributeValue("dataIndexInput", _dataIndexInput);
			xml.SetAttributeValue("dataIndexOutput", _dataIndexOutput);
			xml.SetAttributeValue("minHeight", _minHeight);
			xml.SetAttributeValue("maxHeight", _maxHeight);
			xml.SetAttributeValue("inputMinValue", _inputMinValue);
			xml.SetAttributeValue("inputMaxValue", _inputMaxValue);
		}

		protected override void RestoreXml(XElement xml)
		{
			base.RestoreXml(xml);
			XAttribute xAttribute = xml.Attribute("generateHeightType");
			if (xAttribute != null)
			{
				_generateHeightType = (GenerateHeightType)Enum.Parse(typeof(GenerateHeightType), (string)xAttribute, ignoreCase: true);
			}
			_dataIndexInput = (int)xml.Attribute("dataIndexInput");
			_dataIndexOutput = (int)xml.Attribute("dataIndexOutput");
			_minHeight = (double)xml.Attribute("minHeight");
			_maxHeight = (double)xml.Attribute("maxHeight");
			_inputMinValue = ((double?)xml.Attribute("inputMinValue")) ?? (-1.0);
			_inputMaxValue = ((double?)xml.Attribute("inputMaxValue")) ?? 1.0;
			float planetScale = base.PlanetScale;
			_minHeight *= planetScale;
			_maxHeight *= planetScale;
		}
	}
}
