using System;
using System.Xml.Linq;
using ModApi.Common.Extensions;
using ModApi.Packages.FastNoise;
using ModApi.Planet.Modifiers.Attributes;
using ModApi.Ui.Inspector;
using UnityEngine;

namespace ModApi.Planet.Modifiers.VertexData
{
	[PlanetModifierInfo("Longitude Lines", "A planet modifier that outputs a data value representing lines drawn from one pole of the celestial body to the other. A noise data input value can be applied to the lines and domain warping can be applied to the input postion.")]
	public class LongitudeLines : VertexDataCommonPassPlanetModifier
	{
		private double _angleBetweenLines;

		[SerializeField]
		[Range(-1f, 9f)]
		[DataSlot(DataSlotType.Input, "Input", true, true, Tooltip = "The optional noise input that can be applied to the lines. The input value is used as longitude variation in degrees. Thus, a value of 1 would shift the output position of a line by one degree. Typically, this input would come from a noise modifier with a strength value of 'x' degrees.")]
		private int _dataIndexInput = -1;

		[SerializeField]
		[Range(0f, 9f)]
		[DataSlot(DataSlotType.Output, "Output", false, true, Tooltip = "The output data representing the lines calculated by this modifier. This should be in the range of zero (no lines) to 1 (center of line).")]
		private int _dataIndexOutput;

		private double _halfLineWidth;

		private bool _hasRotation;

		[Space(10f)]
		[SerializeField]
		[InspectorProperty(null, false, Label = "Lines Count", Order = 10, Tooltip = "The number of lines to be generated by this modifier.")]
		private int _lineCount = 10;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Line Width", Order = 20, Tooltip = "The width of the lines, in degrees, generated by this modifier.")]
		private double _lineWidth = 10.0;

		private IFastNoise _noise;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Rotation", Order = 30, Tooltip = "The rotation in degrees about the X, Y, and Z axis to be applied to the input position.")]
		private Vector3 _rotation = Vector3.zero;

		private Quaterniond _rotationQuaternion;

		[SerializeField]
		[InspectorGroup("Twist Config")]
		[InspectorProperty(null, false, Label = "Twist Angle", Order = 35, Tooltip = "The amount of twist (in degrees) to apply to the lines in a single hemisphere.")]
		private double _twistAngle;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Twist Exponent", Order = 36, Tooltip = "The exponent to apply to the twist amount. Increasing this can reduce the twisting near the equator and increase the twisting near the poles.")]
		private double _twistExponent = 1.0;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Twist Method", Order = 37, Tooltip = "The method used to determine the strength of the twist at a given position.\n\nDistance On Axis - The twisting increases as distance on the axis increases.\n\nDistance On Axis Inverse - The twisting decreases as distance on the axis increases.\n\nDistance From Axis - The twisting increases as distance from the axis increases.\n\nDistance From Axis Inverse - The twisting decreases as distance from the axis increases.")]
		private DomainWarpingAxialTwistMethod _twistMethod;

		[Space(10f)]
		[SerializeField]
		[InspectorProperty(null, false, Label = "Amplitude", Order = 50, Tooltip = "The amplitude of the domain warping noise applied the input.")]
		private double _warpAmplitude = 0.1;

		[SerializeField]
		[InspectorGroup("Domain Warping")]
		[InspectorProperty(null, false, Label = "Frequency", Order = 40, Tooltip = "The frequency of the domain warping noise applied the input.")]
		private double _warpFrequency = 1.0;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Gain", Order = 80, Tooltip = "The gain applied to the amplitude at each octave of the domain warping noise applied the input.")]
		private double _warpGain = 0.5;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Lacunarity", Order = 70, Tooltip = "The lacunarity applied to the frequency at each octave of the domain warping noise applied the input.")]
		private double _warpLacunarity = 2.0;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Octaves", Order = 60, Tooltip = "The number of octaves used in the domain warping noise applied the input.")]
		private int _warpOctaves = 1;

		public override VertexDataType VertexDataType => VertexDataType.Both;

		public override void GetVertexData(PlanetVertexDataInput input, PlanetVertexData data)
		{
			Vector3d vector3d = (_hasRotation ? (_rotationQuaternion * input.Position) : input.Position);
			if (_twistAngle != 0.0)
			{
				double num = 0.0;
				num = _twistMethod switch
				{
					DomainWarpingAxialTwistMethod.DistanceOnAxis => vector3d.y, 
					DomainWarpingAxialTwistMethod.DistanceOnAxisInverse => (vector3d.y >= 0.0) ? (1.0 - vector3d.y) : (1.0 + vector3d.y), 
					DomainWarpingAxialTwistMethod.DistanceFromAxis => System.Math.Sqrt(vector3d.x * vector3d.x + vector3d.z * vector3d.z), 
					DomainWarpingAxialTwistMethod.DistanceFromAxisInverse => 1.0 - System.Math.Sqrt(vector3d.x * vector3d.x + vector3d.z * vector3d.z), 
					_ => throw new NotSupportedException("Twist method not supported."), 
				};
				if (_twistExponent != 1.0)
				{
					num = ((num >= 0.0) ? System.Math.Pow(num, _twistExponent) : (0.0 - System.Math.Pow(0.0 - num, _twistExponent)));
				}
				vector3d = Quaterniond.AngleAxis(_twistAngle * num, Vector3d.up) * vector3d;
			}
			double x = vector3d.x;
			double y = vector3d.y;
			double z = vector3d.z;
			_noise.GradientPerturbFractal(ref x, ref y, ref z);
			vector3d.Set(x, 0.0, z);
			vector3d.Normalize();
			double num2 = Vector3d.Angle(vector3d, Vector3d.right);
			if (vector3d.z < 0.0)
			{
				num2 = 180.0 + (180.0 - num2);
			}
			if (_dataIndexInput != -1)
			{
				num2 += data.Data[_dataIndexInput];
			}
			data.Data[_dataIndexOutput] = Mathd.Lerp(1.0, 0.0, System.Math.Abs(num2 % _angleBetweenLines - _halfLineWidth) / _halfLineWidth);
		}

		public override void GetVertexData(PlanetVertexDataInput input, PlanetBiomeVertexData data)
		{
			Vector3d vector3d = (_hasRotation ? (_rotationQuaternion * input.Position) : input.Position);
			if (_twistAngle != 0.0)
			{
				double num = 0.0;
				num = _twistMethod switch
				{
					DomainWarpingAxialTwistMethod.DistanceOnAxis => vector3d.y, 
					DomainWarpingAxialTwistMethod.DistanceOnAxisInverse => (vector3d.y >= 0.0) ? (1.0 - vector3d.y) : (1.0 + vector3d.y), 
					DomainWarpingAxialTwistMethod.DistanceFromAxis => System.Math.Sqrt(vector3d.x * vector3d.x + vector3d.z * vector3d.z), 
					DomainWarpingAxialTwistMethod.DistanceFromAxisInverse => 1.0 - System.Math.Sqrt(vector3d.x * vector3d.x + vector3d.z * vector3d.z), 
					_ => throw new NotSupportedException("Twist method not supported."), 
				};
				if (_twistExponent != 1.0)
				{
					num = ((num >= 0.0) ? System.Math.Pow(num, _twistExponent) : (0.0 - System.Math.Pow(0.0 - num, _twistExponent)));
				}
				vector3d = Quaterniond.AngleAxis(_twistAngle * num, Vector3d.up) * vector3d;
			}
			double x = vector3d.x;
			double y = vector3d.y;
			double z = vector3d.z;
			_noise.GradientPerturbFractal(ref x, ref y, ref z);
			vector3d.Set(x, 0.0, z);
			vector3d.Normalize();
			double num2 = Vector3d.Angle(vector3d, Vector3d.right);
			if (vector3d.z < 0.0)
			{
				num2 = 180.0 + (180.0 - num2);
			}
			if (_dataIndexInput != -1)
			{
				num2 += data.Data[_dataIndexInput];
			}
			data.Data[_dataIndexOutput] = Mathd.Lerp(1.0, 0.0, System.Math.Abs(num2 % _angleBetweenLines - _halfLineWidth) / _halfLineWidth);
		}

		public override void Initialize(IPlanetData planetData)
		{
			base.Initialize(planetData);
			_noise = FastNoise.CreateNoise(0);
			_noise.SetFrequency(_warpFrequency);
			_noise.SetFractalOctaves(_warpOctaves);
			_noise.SetFractalLacunarity(_warpLacunarity);
			_noise.SetFractalGain(_warpGain);
			_noise.SetInterpolation(Interpolation.Quintic);
			_noise.SetGradientPerturbAmp(_warpAmplitude);
			_angleBetweenLines = 360.0 / (double)_lineCount;
			_halfLineWidth = _lineWidth / 2.0;
			_hasRotation = !Utilities.CompareVector3s(_rotation, Vector3.zero);
			_rotationQuaternion = (_hasRotation ? Quaterniond.Euler(_rotation.x, _rotation.y, _rotation.z) : Quaterniond.identity);
		}

		public override void SaveXml(XElement xml)
		{
			base.SaveXml(xml);
			xml.SetAttributeValue("dataIndexInput", _dataIndexInput);
			xml.SetAttributeValue("dataIndexOutput", _dataIndexOutput);
			xml.SetAttributeValue("lineCount", _lineCount);
			xml.SetAttributeValue("lineWidth", _lineWidth);
			xml.SetAttribute("rotation", _rotation);
			xml.SetAttributeValue("warpAmplitude", _warpAmplitude);
			xml.SetAttributeValue("warpFrequency", _warpFrequency);
			xml.SetAttributeValue("warpGain", _warpGain);
			xml.SetAttributeValue("warpLacunarity", _warpLacunarity);
			xml.SetAttributeValue("warpOctaves", _warpOctaves);
			xml.SetAttributeValue("twistAngle", _twistAngle);
			xml.SetAttributeValue("twistExponent", _twistExponent);
			xml.SetAttributeValue("twistMethod", _twistMethod);
		}

		protected override void OnDestroy()
		{
			base.OnDestroy();
			IFastNoise noise = _noise;
			_noise = null;
			noise?.Dispose();
		}

		protected override void RestoreXml(XElement xml)
		{
			base.RestoreXml(xml);
			_dataIndexInput = (int)xml.Attribute("dataIndexInput");
			_dataIndexOutput = (int)xml.Attribute("dataIndexOutput");
			_lineCount = (int)xml.Attribute("lineCount");
			_lineWidth = (double)xml.Attribute("lineWidth");
			_rotation = xml.GetVector3AttributeOrNull("rotation") ?? Vector3.zero;
			_warpAmplitude = (double)xml.Attribute("warpAmplitude");
			_warpFrequency = (double)xml.Attribute("warpFrequency");
			_warpGain = (double)xml.Attribute("warpGain");
			_warpLacunarity = (double)xml.Attribute("warpLacunarity");
			_warpOctaves = (int)xml.Attribute("warpOctaves");
			_twistAngle = ((double?)xml.Attribute("twistAngle")).GetValueOrDefault();
			_twistExponent = ((double?)xml.Attribute("twistExponent")) ?? 1.0;
			_twistMethod = xml.GetEnumAttribute("twistMethod", DomainWarpingAxialTwistMethod.DistanceOnAxis);
		}
	}
}
