using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Xml.Linq;
using ModApi.CelestialData;
using ModApi.Common.Extensions;
using ModApi.Planet.Modifiers.Attributes;
using ModApi.Planet.Modifiers.Common;
using ModApi.Ui.Inspector;
using UnityEngine;

namespace ModApi.Planet.Modifiers.VertexData
{
	[PlanetModifierInfo("Texture Data (Cubemap Face)", "A planet modifier used to read data from a texture mapped to a cubemap face of the celestial body and store an output value based on that data. Rotation is limited to 90 degree increments. Textures should wrap to other faces but will not properly wrap around corners where three faces meet. Expect some distortion as the faces of the cubemap are mapped to the sphere representing the celestial body.")]
	public class TextureData : VertexDataCommonPassPlanetModifier
	{
		private enum CubeFace
		{
			Xpos = 0,
			Xneg = 1,
			Ypos = 2,
			Yneg = 3,
			Zpos = 4,
			Zneg = 5
		}

		private enum CubeFaceTextureRotation
		{
			RotateDefault = 0,
			Rotate90 = 1,
			Rotate180 = 2,
			Rotate270 = 3
		}

		[StructLayout(LayoutKind.Sequential, Size = 1)]
		private struct CubeFaceComparer : IEqualityComparer<CubeFace>
		{
			public bool Equals(CubeFace x, CubeFace y)
			{
				return x == y;
			}

			public int GetHashCode(CubeFace obj)
			{
				return (int)obj;
			}
		}

		private class CubeFaceTexture
		{
			public Vector4d Bounds;

			public CubeFace Face;

			public TextureDataSampleMode InterpolationMethod;

			public float MaxOutputValue = 1f;

			public CubeFaceTextureRotation Rotation;

			public ISingleChannelTextureDataSampler Sampler;

			public Vector2d Size;

			public float Sample(Vector2d cubePosition, float[][] tempArray)
			{
				if (cubePosition.x >= Bounds.x && cubePosition.x <= Bounds.z && cubePosition.y >= Bounds.y && cubePosition.y <= Bounds.w)
				{
					float num = (float)((cubePosition.x - Bounds.x) / Size.x);
					float num2 = (float)((cubePosition.y - Bounds.y) / Size.y);
					if (Rotation != CubeFaceTextureRotation.RotateDefault)
					{
						switch (Rotation)
						{
						case CubeFaceTextureRotation.Rotate90:
						{
							float num4 = num;
							num = 1f - num2;
							num2 = num4;
							break;
						}
						case CubeFaceTextureRotation.Rotate180:
							num = 1f - num;
							num2 = 1f - num2;
							break;
						case CubeFaceTextureRotation.Rotate270:
						{
							float num3 = num2;
							num2 = 1f - num;
							num = num3;
							break;
						}
						}
					}
					if (InterpolationMethod == TextureDataSampleMode.Bicubic)
					{
						return Sampler.SampleBicubic(num, num2, tempArray) * MaxOutputValue;
					}
					return Sampler.SampleBilinear(num, num2) * MaxOutputValue;
				}
				return 0f;
			}
		}

		[Serializable]
		private class TextureDataItem
		{
			[InspectorProperty(null, false, Label = "Cubemap Face", Order = 1, Tooltip = "The cube face of the texture's center position.")]
			public CubeFace Face;

			[InspectorProperty(null, false, Label = "Interpolation Method", Order = 6, Tooltip = "The interpolation method used when sampling the texture data. Bilinear should be much faster. Bicubic should be smoother, but may not always look better than bilinear as the look can be highly dependent on the texture content and resolution as well as the size of the texture on the celestial body. It is recommended to stick with bilinear for performance reasons unless bicubic offers a far better visual result.")]
			public TextureDataSampleMode InterpolationMethod;

			[InspectorProperty(null, false, Label = "Max Output Value", Order = 5, Tooltip = "The maximum value generated by this texture and added to the modifier output value for a pixel of max value. For example, if this value was 100 and pixels ranged from 0 to 255, then a pixel of value 0 would generate a value of 0, a pixel of value 102 would generate a value of 40, and a pixel of value 255 would generate a value of 100.")]
			public float MaxOutputValue = 1f;

			[TextureFileReference]
			[InspectorProperty(null, false, Label = "Texture", Order = 0, Tooltip = "The texture from which to read the data.")]
			public string Path;

			[InspectorProperty(null, false, Label = "Position", Order = 2, Tooltip = "The position of the center of the texture on the cube face. Coordinates are unit cube space, from -0.5 to 0.5.")]
			public Vector2d Position;

			[InspectorProperty(null, false, Label = "Rotation", Order = 3, Tooltip = "The rotation of the texture in degrees. NOTE: Only increments of 90 degrees will work.")]
			public float Rotation;

			[InspectorProperty(null, false, Label = "Size", Order = 4, Tooltip = "The size of the texture relative to the cube face. Coordinates are unit cube space with a size value of 1 filling the entire cubemap face.")]
			public Vector2d Size = new Vector2d(0.5, 0.5);

			[NonSerialized]
			public Texture2D Texture;

			[InspectorProperty(null, false, Label = "Texture Channel", Order = 7, Tooltip = "The texture channel from which values should be used for this texture.")]
			public TextureDataChannel TextureChannel;

			[InspectorProperty(null, false, Label = "Bits Per Pixel", Order = 8, Tooltip = "The number of bits per pixel used at runtime to represent the texture data. A value of 32 could be slightly more efficient on the CPU, but it can take way more memory at runtime, especially for large textures. It is recommended that this value be left at 8 bits per pixel.")]
			public TextureDataBitsPerPixel TextureChannelBitsPerPixel = TextureDataBitsPerPixel._8;

			public ISingleChannelTextureDataSampler Sampler { get; set; }

			public TextureDataItem()
			{
			}

			public TextureDataItem(XElement xml)
			{
				RestoreXml(xml);
			}

			public XElement CreateXml()
			{
				return new XElement("Texture", string.IsNullOrWhiteSpace(Path) ? null : new XAttribute("path", Path), new XAttribute("textureChannel", (int)TextureChannel), (TextureChannelBitsPerPixel == TextureDataBitsPerPixel._8) ? null : new XAttribute("textureChannelBitsPerPixel", (int)TextureChannelBitsPerPixel), new XAttribute("face", Face), new XAttribute("position", Position.XAttributeValue()), new XAttribute("rotation", Rotation), new XAttribute("size", Size.XAttributeValue()), new XAttribute("interpolationMethod", InterpolationMethod), new XAttribute("maxOutputValue", MaxOutputValue));
			}

			public void LoadTexture(PlanetTerrainDataScript terrainData)
			{
				if (Texture != null)
				{
					return;
				}
				try
				{
					Texture = null;
					if (!string.IsNullOrWhiteSpace(Path))
					{
						CelestialFile supportFile = terrainData.PlanetData.FileData.GetSupportFile(Path);
						Texture = supportFile.LoadTexture(mipmaps: false, linear: true, markNonReadable: false);
					}
				}
				catch (Exception exception)
				{
					Texture = null;
					Debug.LogException(exception);
				}
			}

			public void RestoreXml(XElement xml)
			{
				Path = (string)xml.Attribute("path");
				TextureChannel = (TextureDataChannel)((int?)xml.Attribute("textureChannel")).GetValueOrDefault();
				TextureChannelBitsPerPixel = (TextureDataBitsPerPixel)(((int?)xml.Attribute("textureChannelBitsPerPixel")) ?? 8);
				Face = xml.GetEnumAttribute("face", CubeFace.Xpos);
				Position = xml.GetVector2dAttribute("position");
				Rotation = ((float?)xml.Attribute("rotation")).GetValueOrDefault();
				Size = xml.GetVector2dAttribute("size");
				InterpolationMethod = xml.GetEnumAttribute("interpolationMethod", TextureDataSampleMode.Bilinear);
				MaxOutputValue = (float)xml.Attribute("maxOutputValue");
			}

			public void UnloadTexture()
			{
				if (Texture != null)
				{
					UnityEngine.Object.Destroy(Texture);
					Texture = null;
				}
			}
		}

		private Dictionary<CubeFace, List<CubeFaceTexture>> _cubeFaceTextures;

		[SerializeField]
		[Range(0f, 9f)]
		[DataSlot(DataSlotType.Output, "Output", false, true)]
		private int _dataIndexOutput;

		[SerializeField]
		private TextureDataItem[] _textures;

		private Dictionary<string, ISingleChannelTextureDataSampler> _textureSamplers;

		public override VertexDataType VertexDataType => VertexDataType.Both;

		public override void GetVertexData(PlanetVertexDataInput input, PlanetVertexData data)
		{
			double num = 0.0;
			GetCubeFaceAndPosition(input.Position, out var face, out var facePosition);
			if (_cubeFaceTextures.TryGetValue(face, out var value))
			{
				float[][] mapSampleArray = data.CacheData.MapSampleArray;
				for (int i = 0; i < value.Count; i++)
				{
					num += (double)value[i].Sample(facePosition, mapSampleArray);
				}
			}
			data.Data[_dataIndexOutput] = num;
		}

		public override void GetVertexData(PlanetVertexDataInput input, PlanetBiomeVertexData data)
		{
			double num = 0.0;
			GetCubeFaceAndPosition(input.Position, out var face, out var facePosition);
			if (_cubeFaceTextures.TryGetValue(face, out var value))
			{
				float[][] mapSampleArray = data.CommonData.CacheData.MapSampleArray;
				for (int i = 0; i < value.Count; i++)
				{
					num += (double)value[i].Sample(facePosition, mapSampleArray);
				}
			}
			data.Data[_dataIndexOutput] = num;
		}

		public override void Initialize(IPlanetData planetData)
		{
			base.Initialize(planetData);
			InitializeTextureSamplers();
			_cubeFaceTextures = new Dictionary<CubeFace, List<CubeFaceTexture>>(6, default(CubeFaceComparer));
			_cubeFaceTextures.Add(CubeFace.Xneg, new List<CubeFaceTexture>());
			_cubeFaceTextures.Add(CubeFace.Xpos, new List<CubeFaceTexture>());
			_cubeFaceTextures.Add(CubeFace.Yneg, new List<CubeFaceTexture>());
			_cubeFaceTextures.Add(CubeFace.Ypos, new List<CubeFaceTexture>());
			_cubeFaceTextures.Add(CubeFace.Zneg, new List<CubeFaceTexture>());
			_cubeFaceTextures.Add(CubeFace.Zpos, new List<CubeFaceTexture>());
			TextureDataItem[] textures = _textures;
			foreach (TextureDataItem textureDataItem in textures)
			{
				if (textureDataItem.Sampler != null)
				{
					CubeFaceTexture cubeFaceTexture = new CubeFaceTexture
					{
						Face = textureDataItem.Face,
						Size = textureDataItem.Size,
						InterpolationMethod = textureDataItem.InterpolationMethod,
						MaxOutputValue = textureDataItem.MaxOutputValue,
						Sampler = textureDataItem.Sampler
					};
					Vector2d vector2d = textureDataItem.Position - textureDataItem.Size * 0.5;
					Vector2d vector2d2 = vector2d + textureDataItem.Size;
					cubeFaceTexture.Bounds = new Vector4d(vector2d.x, vector2d.y, vector2d2.x, vector2d2.y);
					float num = Mathf.Abs(Mathf.Round(textureDataItem.Rotation / 90f));
					if (!Mathf.Approximately(textureDataItem.Rotation / 90f % 1f, 0f))
					{
						Debug.LogWarningFormat("TextureData currently only supports rotations in 90 degree increments. Rotation '{0}' degrees will be rounded to '{1}' degrees", textureDataItem.Rotation, num * 90f * Mathf.Sign(textureDataItem.Rotation));
					}
					CubeFaceTextureRotation rotation = CubeFaceTextureRotation.RotateDefault;
					bool flag = Mathf.Sign(textureDataItem.Rotation) >= 0f;
					for (int j = 0; (float)j < num; j++)
					{
						rotation = (flag ? RotationRight(rotation) : RotationLeft(rotation));
					}
					cubeFaceTexture.Rotation = rotation;
					_cubeFaceTextures[textureDataItem.Face].Add(cubeFaceTexture);
					WrapLeft(cubeFaceTexture);
					WrapRight(cubeFaceTexture);
					WrapUp(cubeFaceTexture);
					WrapDown(cubeFaceTexture);
				}
			}
		}

		public override void OnCreatingInPlanetStudio(PlanetTerrainDataScript terrainData, VertexDataPlanetModifier parentModifier)
		{
			base.OnCreatingInPlanetStudio(terrainData, parentModifier);
			_textures = new TextureDataItem[1]
			{
				new TextureDataItem()
			};
		}

		public override void SaveXml(XElement xml)
		{
			base.SaveXml(xml);
			xml.SetAttributeValue("dataIndexOutput", _dataIndexOutput);
			XElement xElement = new XElement("Textures");
			if (_textures != null)
			{
				TextureDataItem[] textures = _textures;
				foreach (TextureDataItem textureDataItem in textures)
				{
					xElement.Add(textureDataItem.CreateXml());
				}
			}
			xml.Add(xElement);
		}

		protected override void RestoreXml(XElement xml)
		{
			base.RestoreXml(xml);
			_dataIndexOutput = (int)xml.Attribute("dataIndexOutput");
			_textures = (from x in xml.Elements("Textures").Elements("Texture")
				select new TextureDataItem(x)).ToArray();
		}

		private ISingleChannelTextureDataSampler CreateSamplerFromTexture(TextureDataItem textureDataItem)
		{
			ISingleChannelTextureDataSampler result = null;
			bool num = textureDataItem.Texture != null;
			if (!num)
			{
				textureDataItem.LoadTexture(base.TerrainData);
			}
			if (textureDataItem.Texture != null)
			{
				ISingleChannelTextureDataSampler singleChannelTextureDataSampler2;
				if (textureDataItem.TextureChannelBitsPerPixel > TextureDataBitsPerPixel._8)
				{
					ISingleChannelTextureDataSampler singleChannelTextureDataSampler = new SingleChannelFloatTextureDataSampler(textureDataItem.Texture, (int)textureDataItem.TextureChannel);
					singleChannelTextureDataSampler2 = singleChannelTextureDataSampler;
				}
				else
				{
					ISingleChannelTextureDataSampler singleChannelTextureDataSampler = new SingleChannelByteTextureDataSampler(textureDataItem.Texture, (int)textureDataItem.TextureChannel);
					singleChannelTextureDataSampler2 = singleChannelTextureDataSampler;
				}
				result = singleChannelTextureDataSampler2;
			}
			if (!num)
			{
				textureDataItem.UnloadTexture();
			}
			return result;
		}

		private void GetCubeFaceAndPosition(Vector3d position, out CubeFace face, out Vector2d facePosition)
		{
			double num = ((position.x >= 0.0) ? position.x : (0.0 - position.x));
			double num2 = ((position.y >= 0.0) ? position.y : (0.0 - position.y));
			double num3 = ((position.z >= 0.0) ? position.z : (0.0 - position.z));
			if (num > num2)
			{
				if (num > num3)
				{
					if (position.x > 0.0)
					{
						face = CubeFace.Xpos;
						facePosition = new Vector2d(position.z / num, position.y / num) * 0.5;
					}
					else
					{
						face = CubeFace.Xneg;
						facePosition = new Vector2d((0.0 - position.z) / num, position.y / num) * 0.5;
					}
				}
				else if (position.z > 0.0)
				{
					face = CubeFace.Zpos;
					facePosition = new Vector2d((0.0 - position.x) / num3, position.y / num3) * 0.5;
				}
				else
				{
					face = CubeFace.Zneg;
					facePosition = new Vector2d(position.x / num3, position.y / num3) * 0.5;
				}
			}
			else if (num2 > num3)
			{
				if (position.y > 0.0)
				{
					face = CubeFace.Ypos;
					facePosition = new Vector2d(position.x / num2, position.z / num2) * 0.5;
				}
				else
				{
					face = CubeFace.Yneg;
					facePosition = new Vector2d(position.x / num2, (0.0 - position.z) / num2) * 0.5;
				}
			}
			else if (position.z > 0.0)
			{
				face = CubeFace.Zpos;
				facePosition = new Vector2d((0.0 - position.x) / num3, position.y / num3) * 0.5;
			}
			else
			{
				face = CubeFace.Zneg;
				facePosition = new Vector2d(position.x / num3, position.y / num3) * 0.5;
			}
		}

		private ISingleChannelTextureDataSampler InitializeTextureSampler(TextureDataItem textureDataItem)
		{
			if (string.IsNullOrEmpty(textureDataItem.Path))
			{
				return null;
			}
			CelestialFile supportFile = base.TerrainData.PlanetData.FileData.GetSupportFile(textureDataItem.Path);
			string fileName = $"TextureData_{supportFile.Id}_{textureDataItem.TextureChannel}{textureDataItem.TextureChannelBitsPerPixel}";
			string filePath = base.TerrainData.PlanetData.GeneratedData.GetFilePath(fileName, createDirectory: true);
			ISingleChannelTextureDataSampler singleChannelTextureDataSampler = null;
			if (!File.Exists(filePath))
			{
				singleChannelTextureDataSampler = CreateSamplerFromTexture(textureDataItem);
				using FileStream output = new FileStream(filePath, FileMode.Create);
				using BinaryWriter writer = new BinaryWriter(output);
				singleChannelTextureDataSampler.Save(writer);
			}
			else
			{
				using FileStream input = new FileStream(filePath, FileMode.Open);
				using BinaryReader reader = new BinaryReader(input);
				ISingleChannelTextureDataSampler singleChannelTextureDataSampler3;
				if (textureDataItem.TextureChannelBitsPerPixel > TextureDataBitsPerPixel._8)
				{
					ISingleChannelTextureDataSampler singleChannelTextureDataSampler2 = SingleChannelFloatTextureDataSampler.Load(reader);
					singleChannelTextureDataSampler3 = singleChannelTextureDataSampler2;
				}
				else
				{
					ISingleChannelTextureDataSampler singleChannelTextureDataSampler2 = SingleChannelByteTextureDataSampler.Load(reader);
					singleChannelTextureDataSampler3 = singleChannelTextureDataSampler2;
				}
				singleChannelTextureDataSampler = singleChannelTextureDataSampler3;
			}
			return singleChannelTextureDataSampler;
		}

		private void InitializeTextureSamplers()
		{
			_textureSamplers = new Dictionary<string, ISingleChannelTextureDataSampler>();
			TextureDataItem[] textures = _textures;
			foreach (TextureDataItem textureDataItem in textures)
			{
				ISingleChannelTextureDataSampler value = null;
				string key = textureDataItem.Path + "_" + textureDataItem.TextureChannel.ToString() + textureDataItem.TextureChannelBitsPerPixel;
				if (!_textureSamplers.TryGetValue(key, out value))
				{
					value = InitializeTextureSampler(textureDataItem);
					_textureSamplers.Add(key, value);
				}
				textureDataItem.Sampler = value;
			}
		}

		private CubeFaceTextureRotation RotationLeft(CubeFaceTextureRotation rotation)
		{
			return rotation switch
			{
				CubeFaceTextureRotation.RotateDefault => CubeFaceTextureRotation.Rotate270, 
				CubeFaceTextureRotation.Rotate90 => CubeFaceTextureRotation.RotateDefault, 
				CubeFaceTextureRotation.Rotate180 => CubeFaceTextureRotation.Rotate90, 
				CubeFaceTextureRotation.Rotate270 => CubeFaceTextureRotation.Rotate180, 
				_ => throw new InvalidOperationException(), 
			};
		}

		private CubeFaceTextureRotation RotationRight(CubeFaceTextureRotation rotation)
		{
			return rotation switch
			{
				CubeFaceTextureRotation.RotateDefault => CubeFaceTextureRotation.Rotate90, 
				CubeFaceTextureRotation.Rotate90 => CubeFaceTextureRotation.Rotate180, 
				CubeFaceTextureRotation.Rotate180 => CubeFaceTextureRotation.Rotate270, 
				CubeFaceTextureRotation.Rotate270 => CubeFaceTextureRotation.RotateDefault, 
				_ => throw new InvalidOperationException(), 
			};
		}

		private void WrapDown(CubeFaceTexture texture)
		{
			Vector4d bounds = texture.Bounds;
			if (bounds.y < -0.5)
			{
				CubeFaceTexture cubeFaceTexture = new CubeFaceTexture
				{
					Size = texture.Size,
					Rotation = texture.Rotation,
					InterpolationMethod = texture.InterpolationMethod,
					MaxOutputValue = texture.MaxOutputValue,
					Sampler = texture.Sampler
				};
				switch (texture.Face)
				{
				case CubeFace.Xneg:
					cubeFaceTexture.Face = CubeFace.Yneg;
					cubeFaceTexture.Size = new Vector2d(texture.Size.y, texture.Size.x);
					cubeFaceTexture.Bounds = new Vector4d(-1.0 - bounds.w, bounds.x, -1.0 - bounds.y, bounds.z);
					cubeFaceTexture.Rotation = RotationLeft(texture.Rotation);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapRight(cubeFaceTexture);
					break;
				case CubeFace.Xpos:
					cubeFaceTexture.Face = CubeFace.Yneg;
					cubeFaceTexture.Size = new Vector2d(texture.Size.y, texture.Size.x);
					cubeFaceTexture.Bounds = new Vector4d(bounds.y + 1.0, bounds.x, bounds.w + 1.0, bounds.z);
					cubeFaceTexture.Rotation = RotationRight(texture.Rotation);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapLeft(cubeFaceTexture);
					break;
				case CubeFace.Yneg:
					cubeFaceTexture.Face = CubeFace.Zpos;
					cubeFaceTexture.Bounds = new Vector4d(bounds.x, -1.0 - bounds.w, bounds.z, -1.0 - bounds.y);
					cubeFaceTexture.Rotation = RotationRight(RotationRight(texture.Rotation));
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapUp(cubeFaceTexture);
					break;
				case CubeFace.Ypos:
					cubeFaceTexture.Face = CubeFace.Zneg;
					cubeFaceTexture.Bounds = new Vector4d(bounds.x, bounds.y + 1.0, bounds.z, bounds.w + 1.0);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapDown(cubeFaceTexture);
					break;
				case CubeFace.Zneg:
					cubeFaceTexture.Face = CubeFace.Yneg;
					cubeFaceTexture.Bounds = new Vector4d(bounds.x, bounds.y + 1.0, bounds.z, bounds.w + 1.0);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapDown(cubeFaceTexture);
					break;
				case CubeFace.Zpos:
					cubeFaceTexture.Face = CubeFace.Yneg;
					cubeFaceTexture.Bounds = new Vector4d(bounds.x, -1.0 - bounds.w, bounds.z, -1.0 - bounds.y);
					cubeFaceTexture.Rotation = RotationRight(RotationRight(texture.Rotation));
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapUp(cubeFaceTexture);
					break;
				}
			}
		}

		private void WrapLeft(CubeFaceTexture texture)
		{
			Vector4d bounds = texture.Bounds;
			if (bounds.x < -0.5)
			{
				CubeFaceTexture cubeFaceTexture = new CubeFaceTexture
				{
					Size = texture.Size,
					Rotation = texture.Rotation,
					InterpolationMethod = texture.InterpolationMethod,
					MaxOutputValue = texture.MaxOutputValue,
					Sampler = texture.Sampler
				};
				switch (texture.Face)
				{
				case CubeFace.Xneg:
					cubeFaceTexture.Face = CubeFace.Zpos;
					cubeFaceTexture.Bounds = new Vector4d(bounds.x + 1.0, bounds.y, bounds.z + 1.0, bounds.w);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapLeft(cubeFaceTexture);
					break;
				case CubeFace.Xpos:
					cubeFaceTexture.Face = CubeFace.Zneg;
					cubeFaceTexture.Bounds = new Vector4d(bounds.x + 1.0, bounds.y, bounds.z + 1.0, bounds.w);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapLeft(cubeFaceTexture);
					break;
				case CubeFace.Yneg:
					cubeFaceTexture.Face = CubeFace.Xneg;
					cubeFaceTexture.Size = new Vector2d(texture.Size.y, texture.Size.x);
					cubeFaceTexture.Bounds = new Vector4d(bounds.y, -1.0 - bounds.z, bounds.w, -1.0 - bounds.x);
					cubeFaceTexture.Rotation = RotationRight(cubeFaceTexture.Rotation);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapUp(cubeFaceTexture);
					break;
				case CubeFace.Ypos:
					cubeFaceTexture.Face = CubeFace.Xneg;
					cubeFaceTexture.Size = new Vector2d(texture.Size.y, texture.Size.x);
					cubeFaceTexture.Bounds = new Vector4d(0.0 - bounds.w, 1.0 + bounds.x, 0.0 - bounds.y, 1.0 + bounds.z);
					cubeFaceTexture.Rotation = RotationLeft(cubeFaceTexture.Rotation);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapDown(cubeFaceTexture);
					break;
				case CubeFace.Zneg:
					cubeFaceTexture.Face = CubeFace.Xneg;
					cubeFaceTexture.Bounds = new Vector4d(bounds.x + 1.0, bounds.y, bounds.z + 1.0, bounds.w);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapLeft(cubeFaceTexture);
					break;
				case CubeFace.Zpos:
					cubeFaceTexture.Face = CubeFace.Xpos;
					cubeFaceTexture.Bounds = new Vector4d(bounds.x + 1.0, bounds.y, bounds.z + 1.0, bounds.w);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapLeft(cubeFaceTexture);
					break;
				}
			}
		}

		private void WrapRight(CubeFaceTexture texture)
		{
			Vector4d bounds = texture.Bounds;
			if (bounds.z > 0.5)
			{
				CubeFaceTexture cubeFaceTexture = new CubeFaceTexture
				{
					Size = texture.Size,
					Rotation = texture.Rotation,
					InterpolationMethod = texture.InterpolationMethod,
					MaxOutputValue = texture.MaxOutputValue,
					Sampler = texture.Sampler
				};
				switch (texture.Face)
				{
				case CubeFace.Xneg:
					cubeFaceTexture.Face = CubeFace.Zneg;
					cubeFaceTexture.Bounds = new Vector4d(bounds.x - 1.0, bounds.y, bounds.z - 1.0, bounds.w);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapRight(cubeFaceTexture);
					break;
				case CubeFace.Xpos:
					cubeFaceTexture.Face = CubeFace.Zpos;
					cubeFaceTexture.Bounds = new Vector4d(bounds.x - 1.0, bounds.y, bounds.z - 1.0, bounds.w);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapRight(cubeFaceTexture);
					break;
				case CubeFace.Yneg:
					cubeFaceTexture.Face = CubeFace.Xpos;
					cubeFaceTexture.Size = new Vector2d(texture.Size.y, texture.Size.x);
					cubeFaceTexture.Bounds = new Vector4d(0.0 - bounds.w, bounds.x - 1.0, 0.0 - bounds.y, bounds.z - 1.0);
					cubeFaceTexture.Rotation = RotationLeft(cubeFaceTexture.Rotation);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapUp(cubeFaceTexture);
					break;
				case CubeFace.Ypos:
					cubeFaceTexture.Face = CubeFace.Xpos;
					cubeFaceTexture.Size = new Vector2d(texture.Size.y, texture.Size.x);
					cubeFaceTexture.Bounds = new Vector4d(bounds.y, 1.0 - bounds.z, bounds.w, 1.0 - bounds.x);
					cubeFaceTexture.Rotation = RotationRight(cubeFaceTexture.Rotation);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapDown(cubeFaceTexture);
					break;
				case CubeFace.Zneg:
					cubeFaceTexture.Face = CubeFace.Xpos;
					cubeFaceTexture.Bounds = new Vector4d(bounds.x - 1.0, bounds.y, bounds.z - 1.0, bounds.w);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapRight(cubeFaceTexture);
					break;
				case CubeFace.Zpos:
					cubeFaceTexture.Face = CubeFace.Xneg;
					cubeFaceTexture.Bounds = new Vector4d(bounds.x - 1.0, bounds.y, bounds.z - 1.0, bounds.w);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapRight(cubeFaceTexture);
					break;
				}
			}
		}

		private void WrapUp(CubeFaceTexture texture)
		{
			Vector4d bounds = texture.Bounds;
			if (bounds.w > 0.5)
			{
				CubeFaceTexture cubeFaceTexture = new CubeFaceTexture
				{
					Size = texture.Size,
					Rotation = texture.Rotation,
					InterpolationMethod = texture.InterpolationMethod,
					MaxOutputValue = texture.MaxOutputValue,
					Sampler = texture.Sampler
				};
				switch (texture.Face)
				{
				case CubeFace.Xneg:
					cubeFaceTexture.Face = CubeFace.Ypos;
					cubeFaceTexture.Size = new Vector2d(texture.Size.y, texture.Size.x);
					cubeFaceTexture.Bounds = new Vector4d(bounds.y - 1.0, 0.0 - bounds.z, bounds.w - 1.0, 0.0 - bounds.x);
					cubeFaceTexture.Rotation = RotationRight(texture.Rotation);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapRight(cubeFaceTexture);
					break;
				case CubeFace.Xpos:
					cubeFaceTexture.Face = CubeFace.Ypos;
					cubeFaceTexture.Size = new Vector2d(texture.Size.y, texture.Size.x);
					cubeFaceTexture.Bounds = new Vector4d(1.0 - bounds.w, bounds.x, 1.0 - bounds.y, bounds.z);
					cubeFaceTexture.Rotation = RotationLeft(texture.Rotation);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapLeft(cubeFaceTexture);
					break;
				case CubeFace.Yneg:
					cubeFaceTexture.Face = CubeFace.Zneg;
					cubeFaceTexture.Bounds = new Vector4d(bounds.x, bounds.y - 1.0, bounds.z, bounds.w - 1.0);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapUp(cubeFaceTexture);
					break;
				case CubeFace.Ypos:
					cubeFaceTexture.Face = CubeFace.Zpos;
					cubeFaceTexture.Bounds = new Vector4d(bounds.x, 1.0 - bounds.w, bounds.z, 1.0 - bounds.y);
					cubeFaceTexture.Rotation = RotationRight(RotationRight(texture.Rotation));
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapDown(cubeFaceTexture);
					break;
				case CubeFace.Zneg:
					cubeFaceTexture.Face = CubeFace.Ypos;
					cubeFaceTexture.Bounds = new Vector4d(bounds.x, bounds.y - 1.0, bounds.z, bounds.w - 1.0);
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapUp(cubeFaceTexture);
					break;
				case CubeFace.Zpos:
					cubeFaceTexture.Face = CubeFace.Ypos;
					cubeFaceTexture.Bounds = new Vector4d(bounds.x, 1.0 - bounds.w, bounds.z, 1.0 - bounds.y);
					cubeFaceTexture.Rotation = RotationRight(RotationRight(texture.Rotation));
					_cubeFaceTextures[cubeFaceTexture.Face].Add(cubeFaceTexture);
					WrapDown(cubeFaceTexture);
					break;
				}
			}
		}
	}
}
