using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Xml.Linq;
using ModApi.CelestialData;
using ModApi.Common.Extensions;
using ModApi.Planet.Modifiers.Attributes;
using ModApi.Planet.Modifiers.Common;
using ModApi.Ui.Inspector;
using UnityEngine;

namespace ModApi.Planet.Modifiers.VertexData
{
	[PlanetModifierInfo("Texture Data (Projection)", "A planet modifier used to read data from a texture projected onto the surface of a celestial body and store an output value based on that data. This supports rotation of textures. Distortion should be minimal unless the texture is large enough to start curving around the sphere of the celestial body.")]
	public class TextureData2 : VertexDataCommonPassPlanetModifier
	{
		[Serializable]
		private class TextureDataItem
		{
			[InspectorProperty(null, false, Label = "Interpolation Method", Order = 6, Tooltip = "The interpolation method used when sampling the texture data. Bilinear should be much faster. Bicubic should be smoother, but may not always look better than bilinear as the look can be highly dependent on the texture content and resolution as well as the projected size of the texture. It is recommended to stick with bilinear for performance reasons unless bicubic offers a far better visual result.")]
			public TextureDataSampleMode InterpolationMethod;

			[InspectorProperty(null, false, Label = "Latitude", Order = 1, Tooltip = "The latitude at which this texture data should be centered and projected onto the celestial body.")]
			public float Latitude;

			[InspectorProperty(null, false, Label = "Longitude", Order = 2, Tooltip = "The longitude at which this texture data should be centered and projected onto the celestial body.")]
			public float Longitude;

			[InspectorProperty(null, false, Label = "Max Output Value", Order = 5, Tooltip = "The maximum value generated by this texture and added to the modifier output value for a pixel of max value. For example, if this value was 100 and pixels ranged from 0 to 255, then a pixel of value 0 would generate a value of 0, a pixel of value 102 would generate a value of 40, and a pixel of value 255 would generate a value of 100.")]
			public float MaxOutputValue = 1f;

			[TextureFileReference]
			[InspectorProperty(null, false, Label = "Texture", Order = 0, Tooltip = "The texture data to be projected onto the celestial body.")]
			public string Path;

			[InspectorProperty(null, false, Label = "Rotation", Order = 4, Tooltip = "The rotation of the projected texture in degrees.")]
			public float Rotation;

			[InspectorProperty(null, false, Label = "Size", Order = 3, Tooltip = "The size of the texture projected onto the planet. This value is relative to the size of a unit sphere. This size is not related to or affected by the radius of the celestial body.")]
			public Vector2d Size = new Vector2d(0.5, 0.5);

			[NonSerialized]
			public Texture2D Texture;

			[InspectorProperty(null, false, Label = "Texture Channel", Order = 7, Tooltip = "The texture channel from which values should be used for this texture.")]
			public TextureDataChannel TextureChannel;

			[InspectorProperty(null, false, Label = "Bits Per Pixel", Order = 8, Tooltip = "The number of bits per pixel used at runtime to represent the texture data. A value of 32 could be slightly more efficient on the CPU, but it can take way more memory at runtime, especially for large textures. It is recommended that this value be left at 8 bits per pixel.")]
			public TextureDataBitsPerPixel TextureChannelBitsPerPixel = TextureDataBitsPerPixel._8;

			public ISingleChannelTextureDataSampler Sampler { get; set; }

			public TextureDataItem()
			{
			}

			public TextureDataItem(XElement xml)
			{
				RestoreXml(xml);
			}

			public XElement CreateXml()
			{
				return new XElement("Texture", string.IsNullOrWhiteSpace(Path) ? null : new XAttribute("path", Path), new XAttribute("textureChannel", (int)TextureChannel), (TextureChannelBitsPerPixel == TextureDataBitsPerPixel._8) ? null : new XAttribute("textureChannelBitsPerPixel", (int)TextureChannelBitsPerPixel), new XAttribute("latitude", Latitude), new XAttribute("longitude", Longitude), new XAttribute("rotation", Rotation), new XAttribute("size", Size.XAttributeValue()), new XAttribute("interpolationMethod", InterpolationMethod), new XAttribute("maxOutputValue", MaxOutputValue));
			}

			public void LoadTexture(PlanetTerrainDataScript terrainData)
			{
				if (Texture != null)
				{
					return;
				}
				try
				{
					Texture = null;
					if (!string.IsNullOrWhiteSpace(Path))
					{
						CelestialFile supportFile = terrainData.PlanetData.FileData.GetSupportFile(Path);
						Texture = supportFile.LoadTexture(mipmaps: false, linear: true, markNonReadable: false);
					}
				}
				catch (Exception exception)
				{
					Texture = null;
					Debug.LogException(exception);
				}
			}

			public void RestoreXml(XElement xml)
			{
				Path = (string)xml.Attribute("path");
				TextureChannel = (TextureDataChannel)((int?)xml.Attribute("textureChannel")).GetValueOrDefault();
				TextureChannelBitsPerPixel = (TextureDataBitsPerPixel)(((int?)xml.Attribute("textureChannelBitsPerPixel")) ?? 8);
				Latitude = (float)xml.Attribute("latitude");
				Longitude = (float)xml.Attribute("longitude");
				Rotation = ((float?)xml.Attribute("rotation")).GetValueOrDefault();
				Size = xml.GetVector2dAttribute("size");
				InterpolationMethod = xml.GetEnumAttribute("interpolationMethod", TextureDataSampleMode.Bilinear);
				MaxOutputValue = (float)xml.Attribute("maxOutputValue");
				Size.x = Mathd.Clamp(Size.x, double.Epsilon, 2.0);
				Size.y = Mathd.Clamp(Size.y, double.Epsilon, 2.0);
			}

			public void UnloadTexture()
			{
				if (Texture != null)
				{
					UnityEngine.Object.Destroy(Texture);
					Texture = null;
				}
			}
		}

		private class TextureStamp
		{
			public Vector3d BiTangent;

			public double Height;

			public TextureDataSampleMode InterpolationMethod;

			public float MaxOutputValue;

			public double MinimumDotProduct;

			public Vector3d Position;

			public ISingleChannelTextureDataSampler Sampler;

			public Vector3d Tangent;

			public double Width;

			public TextureStamp(TextureDataItem textureData)
			{
				Sampler = textureData.Sampler;
				InterpolationMethod = textureData.InterpolationMethod;
				MaxOutputValue = textureData.MaxOutputValue;
				double d = (double)textureData.Latitude * 0.01745329;
				double num = (double)textureData.Longitude * 0.01745329;
				Position = new Vector3d(Mathd.Cos(d) * Mathd.Sin(0.0 - num), Mathd.Sin(d), Mathd.Cos(d) * Mathd.Cos(0.0 - num)).normalized;
				Vector3d vector3d = Quaterniond.AngleAxis(0f - textureData.Longitude, Vector3.up) * Vector3d.right;
				vector3d = (Quaterniond.AngleAxis(textureData.Rotation, Position) * vector3d).normalized;
				BiTangent = Vector3d.Cross(Position, vector3d).normalized;
				Tangent = Vector3d.Cross(BiTangent, Position).normalized;
				Width = Mathd.Sqrt(textureData.Size.x) * 0.5;
				Height = Mathd.Sqrt(textureData.Size.y) * 0.5;
				double num2 = Width * Width + Height * Height;
				double num3 = 1.0 - (Mathd.Approximately(num2, 1.0) ? 0.0 : Mathd.Sqrt(1.0 - num2));
				Vector3d rhs = Position + Tangent * Width + BiTangent * Height - Position * num3;
				MinimumDotProduct = Vector3d.Dot(Position, rhs);
			}
		}

		[SerializeField]
		[Range(0f, 9f)]
		[DataSlot(DataSlotType.Output, "Output", false, true)]
		private int _dataIndexOutput;

		[SerializeField]
		private TextureDataItem[] _textures;

		private Dictionary<string, ISingleChannelTextureDataSampler> _textureSamplers;

		private TextureStamp[] _textureStamps;

		public override VertexDataType VertexDataType => VertexDataType.Both;

		public override void GetVertexData(PlanetVertexDataInput input, PlanetVertexData data)
		{
			double num = 0.0;
			int num2 = _textureStamps.Length;
			for (int i = 0; i < num2; i++)
			{
				TextureStamp textureStamp = _textureStamps[i];
				double num3 = Vector3d.Dot(textureStamp.Position, input.Position);
				if (!(num3 < textureStamp.MinimumDotProduct))
				{
					Vector3d lhs = input.Position + textureStamp.Position * (1.0 - num3);
					double num4 = Vector3d.Dot(lhs, textureStamp.Tangent) / textureStamp.Width;
					double num5 = Vector3d.Dot(lhs, textureStamp.BiTangent) / textureStamp.Height;
					if (num4 >= -1.0 && num4 <= 1.0 && num5 >= -1.0 && num5 <= 1.0)
					{
						float u = (float)(num4 * 0.5 + 0.5);
						float v = (float)(num5 * 0.5 + 0.5);
						float num6 = 0f;
						num6 = ((textureStamp.InterpolationMethod != TextureDataSampleMode.Bicubic) ? textureStamp.Sampler.SampleBilinear(u, v) : textureStamp.Sampler.SampleBicubic(u, v, data.CacheData.MapSampleArray));
						num += (double)(num6 * textureStamp.MaxOutputValue);
					}
				}
			}
			data.Data[_dataIndexOutput] = num;
		}

		public override void GetVertexData(PlanetVertexDataInput input, PlanetBiomeVertexData data)
		{
			double num = 0.0;
			int num2 = _textureStamps.Length;
			for (int i = 0; i < num2; i++)
			{
				TextureStamp textureStamp = _textureStamps[i];
				double num3 = Vector3d.Dot(textureStamp.Position, input.Position);
				if (!(num3 < textureStamp.MinimumDotProduct))
				{
					Vector3d lhs = input.Position + textureStamp.Position * (1.0 - num3);
					double num4 = Vector3d.Dot(lhs, textureStamp.Tangent) / textureStamp.Width;
					double num5 = Vector3d.Dot(lhs, textureStamp.BiTangent) / textureStamp.Height;
					if (num4 >= -1.0 && num4 <= 1.0 && num5 >= -1.0 && num5 <= 1.0)
					{
						float u = (float)(num4 * 0.5 + 0.5);
						float v = (float)(num5 * 0.5 + 0.5);
						float num6 = 0f;
						num6 = ((textureStamp.InterpolationMethod != TextureDataSampleMode.Bicubic) ? textureStamp.Sampler.SampleBilinear(u, v) : textureStamp.Sampler.SampleBicubic(u, v, data.CommonData.CacheData.MapSampleArray));
						num += (double)(num6 * textureStamp.MaxOutputValue);
					}
				}
			}
			data.Data[_dataIndexOutput] = num;
		}

		public override void Initialize(IPlanetData planetData)
		{
			base.Initialize(planetData);
			InitializeTextureSamplers();
			_textureStamps = _textures.Select((TextureDataItem x) => new TextureStamp(x)).ToArray();
		}

		public override void OnCreatingInPlanetStudio(PlanetTerrainDataScript terrainData, VertexDataPlanetModifier parentModifier)
		{
			base.OnCreatingInPlanetStudio(terrainData, parentModifier);
			_textures = new TextureDataItem[1]
			{
				new TextureDataItem()
			};
		}

		public override void SaveXml(XElement xml)
		{
			base.SaveXml(xml);
			xml.SetAttributeValue("dataIndexOutput", _dataIndexOutput);
			XElement xElement = new XElement("Textures");
			if (_textures != null)
			{
				TextureDataItem[] textures = _textures;
				foreach (TextureDataItem textureDataItem in textures)
				{
					xElement.Add(textureDataItem.CreateXml());
				}
			}
			xml.Add(xElement);
		}

		protected override void RestoreXml(XElement xml)
		{
			base.RestoreXml(xml);
			_dataIndexOutput = (int)xml.Attribute("dataIndexOutput");
			_textures = (from x in xml.Elements("Textures").Elements("Texture")
				select new TextureDataItem(x)).ToArray();
		}

		private ISingleChannelTextureDataSampler CreateSamplerFromTexture(TextureDataItem textureDataItem)
		{
			ISingleChannelTextureDataSampler result = null;
			bool num = textureDataItem.Texture != null;
			if (!num)
			{
				textureDataItem.LoadTexture(base.TerrainData);
			}
			if (textureDataItem.Texture != null)
			{
				ISingleChannelTextureDataSampler singleChannelTextureDataSampler2;
				if (textureDataItem.TextureChannelBitsPerPixel > TextureDataBitsPerPixel._8)
				{
					ISingleChannelTextureDataSampler singleChannelTextureDataSampler = new SingleChannelFloatTextureDataSampler(textureDataItem.Texture, (int)textureDataItem.TextureChannel);
					singleChannelTextureDataSampler2 = singleChannelTextureDataSampler;
				}
				else
				{
					ISingleChannelTextureDataSampler singleChannelTextureDataSampler = new SingleChannelByteTextureDataSampler(textureDataItem.Texture, (int)textureDataItem.TextureChannel);
					singleChannelTextureDataSampler2 = singleChannelTextureDataSampler;
				}
				result = singleChannelTextureDataSampler2;
			}
			if (!num)
			{
				textureDataItem.UnloadTexture();
			}
			return result;
		}

		private ISingleChannelTextureDataSampler InitializeTextureSampler(TextureDataItem textureDataItem)
		{
			if (string.IsNullOrEmpty(textureDataItem.Path))
			{
				return null;
			}
			CelestialFile supportFile = base.TerrainData.PlanetData.FileData.GetSupportFile(textureDataItem.Path);
			string fileName = $"TextureData_{supportFile.Id}_{textureDataItem.TextureChannel}{textureDataItem.TextureChannelBitsPerPixel}";
			string filePath = base.TerrainData.PlanetData.GeneratedData.GetFilePath(fileName, createDirectory: true);
			ISingleChannelTextureDataSampler singleChannelTextureDataSampler = null;
			if (!File.Exists(filePath))
			{
				singleChannelTextureDataSampler = CreateSamplerFromTexture(textureDataItem);
				using FileStream output = new FileStream(filePath, FileMode.Create);
				using BinaryWriter writer = new BinaryWriter(output);
				singleChannelTextureDataSampler.Save(writer);
			}
			else
			{
				using FileStream input = new FileStream(filePath, FileMode.Open);
				using BinaryReader reader = new BinaryReader(input);
				ISingleChannelTextureDataSampler singleChannelTextureDataSampler3;
				if (textureDataItem.TextureChannelBitsPerPixel > TextureDataBitsPerPixel._8)
				{
					ISingleChannelTextureDataSampler singleChannelTextureDataSampler2 = SingleChannelFloatTextureDataSampler.Load(reader);
					singleChannelTextureDataSampler3 = singleChannelTextureDataSampler2;
				}
				else
				{
					ISingleChannelTextureDataSampler singleChannelTextureDataSampler2 = SingleChannelByteTextureDataSampler.Load(reader);
					singleChannelTextureDataSampler3 = singleChannelTextureDataSampler2;
				}
				singleChannelTextureDataSampler = singleChannelTextureDataSampler3;
			}
			return singleChannelTextureDataSampler;
		}

		private void InitializeTextureSamplers()
		{
			_textureSamplers = new Dictionary<string, ISingleChannelTextureDataSampler>();
			TextureDataItem[] textures = _textures;
			foreach (TextureDataItem textureDataItem in textures)
			{
				ISingleChannelTextureDataSampler value = null;
				string key = textureDataItem.Path + "_" + textureDataItem.TextureChannel.ToString() + textureDataItem.TextureChannelBitsPerPixel;
				if (!_textureSamplers.TryGetValue(key, out value))
				{
					value = InitializeTextureSampler(textureDataItem);
					_textureSamplers.Add(key, value);
				}
				textureDataItem.Sampler = value;
			}
		}
	}
}
