using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Xml.Linq;
using ModApi.Planet.Modifiers.Attributes;
using ModApi.Ui.Inspector;
using UnityEngine;

namespace ModApi.Planet.Modifiers.VertexData
{
	[PlanetModifierInfo("Update Height", "A planet modifier that updates the height of the terrain based off the height, in meters, specified in a data input. The input height data is usually generated by a 'Generate Height' modifier, though this is not required.")]
	public class UpdateFinalHeight : VertexDataCommonPassPlanetModifier, ICustomInspectorFields
	{
		[SerializeField]
		[Range(0f, 9f)]
		[DataSlot(DataSlotType.Input, "Input", false, true, Tooltip = "The data input used to update the height of the terrain. This should be the height, in meters, to be added to the current terrain height.")]
		private int _dataIndex;

		[SerializeField]
		[InspectorProperty(null, false, Label = "Ignore Biome Strength", Order = 10, Tooltip = "If enabled and running for a specific biome, the strength of the biome will be ignored when applying the height. If disabled, the height is scaled based off the strength of the biome for which this modifier is running.")]
		private bool _ignoreBiomeStrengthScale;

		public override VertexDataPlanetModifierPassType[] SupportedPassTypes => new VertexDataPlanetModifierPassType[3]
		{
			VertexDataPlanetModifierPassType.Biome,
			VertexDataPlanetModifierPassType.Height,
			VertexDataPlanetModifierPassType.HeightFinal
		};

		public override VertexDataType VertexDataType => VertexDataType.Both;

		public List<FieldInfo> GetInspectorFields()
		{
			if (!(base.Biome != null))
			{
				return new List<FieldInfo>(0);
			}
			return new List<FieldInfo> { typeof(UpdateFinalHeight).GetField("_ignoreBiomeStrengthScale", BindingFlags.Instance | BindingFlags.NonPublic) };
		}

		public override void GetVertexData(PlanetVertexDataInput input, PlanetVertexData data)
		{
			data.Height += data.Data[_dataIndex];
		}

		public override void GetVertexData(PlanetVertexDataInput input, PlanetBiomeVertexData data)
		{
			if (_ignoreBiomeStrengthScale)
			{
				data.CommonData.Height += data.Data[_dataIndex];
			}
			else
			{
				data.Height += data.Data[_dataIndex];
			}
		}

		public override void OnCreatingInPlanetStudio(PlanetTerrainDataScript terrainData, VertexDataPlanetModifier parentModifier)
		{
			base.OnCreatingInPlanetStudio(terrainData, parentModifier);
			_dataIndex = (parentModifier?.GetDataSlots().FirstOrDefault(delegate(DataSlotField x)
			{
				DataSlotAttribute attribute = x.Attribute;
				return attribute != null && attribute.DataSlotType == DataSlotType.Output && x.DataIndex >= 0;
			})?.DataIndex).GetValueOrDefault();
		}

		public override void SaveXml(XElement xml)
		{
			base.SaveXml(xml);
			xml.SetAttributeValue("dataIndex", _dataIndex);
			if (_ignoreBiomeStrengthScale)
			{
				xml.SetAttributeValue("ignoreBiomeStrengthScale", _ignoreBiomeStrengthScale);
			}
		}

		protected override void RestoreXml(XElement xml)
		{
			base.RestoreXml(xml);
			_dataIndex = (int)xml.Attribute("dataIndex");
			_ignoreBiomeStrengthScale = (bool?)xml.Attribute("ignoreBiomeStrengthScale") == true;
		}
	}
}
