namespace Tabletop.GameWorld
{
	public enum ETabletopXPRewardEvent
	{
		ASSEMBLE_MINIATURE = 0,
		ORGANIZE_EVENT = 1,
		PLAYING_CLIENS = 2,
		PAINTING_CLIENTS = 3,
		UNPACKING = 4,
		SCULPTING = 5,
		PAINTING = 6,
		WARGAME_WIN = 7,
		WARGAME_LOSS = 8,
		EVENT_PLAYING_CLIENT = 9,
		EVENT_PAINTING_CLIENT = 10,
		PAINTING_EVENT_WIN = 11,
		SELL_MINIATURE = 12,
		SELL_PAINTED_MINIATURE = 13
	}
}
