namespace Tabletop.GameWorld
{
	public enum EWargameEffectQuantity
	{
		NUMERIC = 0,
		PLAYER_ASSAULT = 1,
		PLAYER_DAMAGE = 2,
		PLAYER_PV = 3,
		PLAYER_BET = 4,
		PLAYER_TOKENS = 5,
		OPPONENT_ASSAULT = 6,
		OPPONENT_DAMAGE = 7,
		OPPONENT_PV = 8,
		OPPONENT_BET = 9,
		OPPONENT_TOKENS = 10,
		PRECEDENT_ACTIVATION = 11,
		ALL_PRECEDENT_ACTIVATION = 12,
		DELTA_ASSAULT = 13,
		DELTA_DAMAGE = 14,
		DELTA_PV = 15,
		CURRENT_ACTIVATION = 16
	}
}
