namespace Tabletop.GameWorld
{
	public enum EWargameEffectTrigger
	{
		IMMEDIATE = 0,
		POST_EFFECT = 1,
		NEXT_EFFECT_RECEIVED = 2,
		WHOLE_ROUND_EFFECT_RECEIVED = 3,
		NEXT_EFFECT_APPLIED = 4,
		WHOLE_ROUND_EFFECT_APPLIED = 5,
		WIN_ROUND = 6,
		LOSE_ROUND = 7,
		OVERRIDE_TOKEN_BEHAVIOUR = 8,
		PV_TO_0 = 9,
		NEXT_ROUND = 10,
		EVERY_ROUND = 11,
		WHOLE_ROUND_ALLY_ACTIVATION = 12,
		NEXT_DICE_COMBINATION = 13
	}
}
