<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>RoslynCSharp.Examples</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="RoslynCSharp">
      <HintPath>..\..\Assemblies\RoslynCSharp.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\Assemblies\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="RoslynCSharp.Compiler">
      <HintPath>..\..\Assemblies\RoslynCSharp.Compiler.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>..\..\Assemblies\UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="Trivial.CodeSecurity">
      <HintPath>..\..\Assemblies\Trivial.CodeSecurity.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>