using System;
using UniJSON;

namespace UniGLTF
{
	[Serializable]
	public class glTFAssets : JsonSerializableBase
	{
		public string generator;

		[JsonSchema(Required = true, Pattern = "^[0-9]+\\.[0-9]+$")]
		public string version;

		public string copyright;

		[JsonSchema(Pattern = "^[0-9]+\\.[0-9]+$")]
		public string minVersion;

		public object extensions;

		public object extras;

		protected override void SerializeMembers(GLTFJsonFormatter f)
		{
			f.Key("generator");
			f.Value(generator);
			f.Key("version");
			f.Value(version);
		}

		public override string ToString()
		{
			return $"GLTF-{version} generated by {generator}";
		}
	}
}
