<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Timberborn.SettingsSystemUI</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Timberborn.AccessibilitySettingsSystem">
      <HintPath>..\..\Assemblies\Timberborn.AccessibilitySettingsSystem.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Analytics">
      <HintPath>..\..\Assemblies\Timberborn.Analytics.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Localization">
      <HintPath>..\..\Assemblies\Timberborn.Localization.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.GraphicsQualitySystem">
      <HintPath>..\..\Assemblies\Timberborn.GraphicsQualitySystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.CameraSettingsSystem">
      <HintPath>..\..\Assemblies\Timberborn.CameraSettingsSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Debugging">
      <HintPath>..\..\Assemblies\Timberborn.Debugging.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.FactionSystem">
      <HintPath>..\..\Assemblies\Timberborn.FactionSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.MainMenuSceneLoading">
      <HintPath>..\..\Assemblies\Timberborn.MainMenuSceneLoading.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.PlayerDataSystem">
      <HintPath>..\..\Assemblies\Timberborn.PlayerDataSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.GameSaveRepositorySystem">
      <HintPath>..\..\Assemblies\Timberborn.GameSaveRepositorySystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SingletonSystem">
      <HintPath>..\..\Assemblies\Timberborn.SingletonSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.ScreenSystem">
      <HintPath>..\..\Assemblies\Timberborn.ScreenSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SettingsSystem">
      <HintPath>..\..\Assemblies\Timberborn.SettingsSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.DropdownSystem">
      <HintPath>..\..\Assemblies\Timberborn.DropdownSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.InputSystem">
      <HintPath>..\..\Assemblies\Timberborn.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.LanguageUI">
      <HintPath>..\..\Assemblies\Timberborn.LanguageUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.CoreUI">
      <HintPath>..\..\Assemblies\Timberborn.CoreUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.KeyBindingSystemUI">
      <HintPath>..\..\Assemblies\Timberborn.KeyBindingSystemUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.IntroSettingsSystem">
      <HintPath>..\..\Assemblies\Timberborn.IntroSettingsSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SoundSettingsSystem">
      <HintPath>..\..\Assemblies\Timberborn.SoundSettingsSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TutorialSettingsSystem">
      <HintPath>..\..\Assemblies\Timberborn.TutorialSettingsSystem.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections.Immutable">
      <HintPath>..\..\Assemblies\System.Collections.Immutable.dll</HintPath>
    </Reference>
    <Reference Include="Bindito.Core">
      <HintPath>..\..\Assemblies\Bindito.Core.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.ErrorReporting">
      <HintPath>..\..\Assemblies\Timberborn.ErrorReporting.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.PlatformUtilities">
      <HintPath>..\..\Assemblies\Timberborn.PlatformUtilities.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>