using PugWorldGen;
using Unity.Burst;
using Unity.Entities;
using UnityEngine;
using WorldGen;

[BurstCompile]
internal class __UnmanagedPostProcessorOutput__5055791706352413401
{
	[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]
	public static void EarlyInit()
	{
		SystemBaseRegistry.AddUnmanagedSystemType(typeof(LegacyRespawnPartialSubMapsInitSystem), BurstRuntime.GetHashCode64<LegacyRespawnPartialSubMapsInitSystem>(), LegacyRespawnPartialSubMapsInitSystem.__codegen__OnCreate, LegacyRespawnPartialSubMapsInitSystem.__codegen__OnUpdate, LegacyRespawnPartialSubMapsInitSystem.__codegen__OnDestroy, null, null, LegacyRespawnPartialSubMapsInitSystem.__codegen__OnCreateForCompiler, "LegacyRespawnPartialSubMapsInitSystem", 6);
		SystemBaseRegistry.AddUnmanagedSystemType(typeof(RespawnPartialSubMapsInitSystem), BurstRuntime.GetHashCode64<RespawnPartialSubMapsInitSystem>(), RespawnPartialSubMapsInitSystem.__codegen__OnCreate, RespawnPartialSubMapsInitSystem.__codegen__OnUpdate, RespawnPartialSubMapsInitSystem.__codegen__OnDestroy, null, null, RespawnPartialSubMapsInitSystem.__codegen__OnCreateForCompiler, "RespawnPartialSubMapsInitSystem", 6);
		SystemBaseRegistry.AddUnmanagedSystemType(typeof(SpawnEnvironmentObjectsInNewAreaSystem), BurstRuntime.GetHashCode64<SpawnEnvironmentObjectsInNewAreaSystem>(), SpawnEnvironmentObjectsInNewAreaSystem.__codegen__OnCreate, SpawnEnvironmentObjectsInNewAreaSystem.__codegen__OnUpdate, null, SpawnEnvironmentObjectsInNewAreaSystem.__codegen__OnStartRunning, SpawnEnvironmentObjectsInNewAreaSystem.__codegen__OnStopRunning, SpawnEnvironmentObjectsInNewAreaSystem.__codegen__OnCreateForCompiler, "SpawnEnvironmentObjectsInNewAreaSystem", 26);
		SystemBaseRegistry.AddUnmanagedSystemType(typeof(SpawnProceduralTerrainSystem), BurstRuntime.GetHashCode64<SpawnProceduralTerrainSystem>(), SpawnProceduralTerrainSystem.__codegen__OnCreate, SpawnProceduralTerrainSystem.__codegen__OnUpdate, SpawnProceduralTerrainSystem.__codegen__OnDestroy, SpawnProceduralTerrainSystem.__codegen__OnStartRunning, SpawnProceduralTerrainSystem.__codegen__OnStopRunning, SpawnProceduralTerrainSystem.__codegen__OnCreateForCompiler, "SpawnProceduralTerrainSystem", 6);
		SystemBaseRegistry.AddUnmanagedSystemType(typeof(SpawnRootsInNewAreasRunSystem), BurstRuntime.GetHashCode64<SpawnRootsInNewAreasRunSystem>(), SpawnRootsInNewAreasRunSystem.__codegen__OnCreate, SpawnRootsInNewAreasRunSystem.__codegen__OnUpdate, SpawnRootsInNewAreasRunSystem.__codegen__OnDestroy, null, null, SpawnRootsInNewAreasRunSystem.__codegen__OnCreateForCompiler, "WorldGen.SpawnRootsInNewAreasRunSystem", 2);
		SystemBaseRegistry.AddUnmanagedSystemType(typeof(SpawnTerritoriesInNewAreasSystem), BurstRuntime.GetHashCode64<SpawnTerritoriesInNewAreasSystem>(), SpawnTerritoriesInNewAreasSystem.__codegen__OnCreate, SpawnTerritoriesInNewAreasSystem.__codegen__OnUpdate, null, SpawnTerritoriesInNewAreasSystem.__codegen__OnStartRunning, SpawnTerritoriesInNewAreasSystem.__codegen__OnStopRunning, SpawnTerritoriesInNewAreasSystem.__codegen__OnCreateForCompiler, "WorldGen.SpawnTerritoriesInNewAreasSystem", 19);
		SystemBaseRegistry.AddUnmanagedSystemType(typeof(SpawnDungeonAndSceneSystem), BurstRuntime.GetHashCode64<SpawnDungeonAndSceneSystem>(), SpawnDungeonAndSceneSystem.__codegen__OnCreate, SpawnDungeonAndSceneSystem.__codegen__OnUpdate, SpawnDungeonAndSceneSystem.__codegen__OnDestroy, SpawnDungeonAndSceneSystem.__codegen__OnStartRunning, SpawnDungeonAndSceneSystem.__codegen__OnStopRunning, SpawnDungeonAndSceneSystem.__codegen__OnCreateForCompiler, "PugWorldGen.SpawnDungeonAndSceneSystem", 23);
	}
}
