<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\Assemblies\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\..\Assemblies\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VehiclesModule">
      <HintPath>..\..\Assemblies\UnityEngine.VehiclesModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>..\..\Assemblies\Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="Mirror">
      <HintPath>..\..\Assemblies\Mirror.dll</HintPath>
    </Reference>
    <Reference Include="GameCreator.Runtime.Core">
      <HintPath>..\..\Assemblies\GameCreator.Runtime.Core.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\Assemblies\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Splines">
      <HintPath>..\..\Assemblies\Unity.Splines.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>..\..\Assemblies\Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="Digger.Core">
      <HintPath>..\..\Assemblies\Digger.Core.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\..\Assemblies\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>..\..\Assemblies\com.rlabrecque.steamworks.net.dll</HintPath>
    </Reference>
    <Reference Include="Heathen.Steamworks">
      <HintPath>..\..\Assemblies\Heathen.Steamworks.dll</HintPath>
    </Reference>
    <Reference Include="Kamgam.UGUIComponentsForSettings">
      <HintPath>..\..\Assemblies\Kamgam.UGUIComponentsForSettings.dll</HintPath>
    </Reference>
    <Reference Include="Kamgam.SettingsGenerator">
      <HintPath>..\..\Assemblies\Kamgam.SettingsGenerator.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>..\..\Assemblies\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\Assemblies\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\..\Assemblies\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="Mirror.Components">
      <HintPath>..\..\Assemblies\Mirror.Components.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\..\Assemblies\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="Digger.Runtime">
      <HintPath>..\..\Assemblies\Digger.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>..\..\Assemblies\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>..\..\Assemblies\UnityEngine.TerrainModule.dll</HintPath>
    </Reference>
    <Reference Include="LocalizationsForSettings">
      <HintPath>..\..\Assemblies\LocalizationsForSettings.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Runtime">
      <HintPath>..\..\Assemblies\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="com.cqf.urpvolumetricfog.runtime">
      <HintPath>..\..\Assemblies\com.cqf.urpvolumetricfog.runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>..\..\Assemblies\UnityEngine.VideoModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\Assemblies\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="Enviro3.Runtime">
      <HintPath>..\..\Assemblies\Enviro3.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Fullscreen.NanoSave">
      <HintPath>..\..\Assemblies\Fullscreen.NanoSave.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>