namespace Kitchen
{
	public enum TutorialStage
	{
		Null = 0,
		Setup = 1,
		PickUpFish = 2,
		CookFish = 3,
		WaitFishCook = 4,
		PlateFish = 5,
		SpawnTable = 6,
		SpawnCustomer = 7,
		TakeCustomerOrder = 8,
		DeliverFish = 9,
		PickUpDish = 10,
		WashDish = 11,
		SpawnPotato = 12,
		Completed = 13,
		ChopPotato = 14,
		CookPotato = 15,
		CookFishForSide = 16,
		TakeCustomerOrderSide = 17,
		SpawnCustomerSide = 18,
		DeliverSide = 19,
		PickUpPotato = 20,
		SpawnMess = 21,
		CleanMess = 22,
		SpawnCustomerPair = 23,
		TakeCustomerOrderPair = 24,
		DeliverPair = 25,
		PickUpDishMess = 26,
		WashDishMess = 27,
		SpawnCustomerImpatient = 28,
		TakeCustomerOrderImpatient = 29,
		DeliverImpatient = 30,
		PairEating = 31,
		CleanTables = 32,
		Skip = 33,
		SetupAdvanced = 34,
		Finish = 35,
		Splittable = 36,
		SpawnMash = 37,
		Fire = 38,
		TipRedecorate = 39,
		TipProgression = 40,
		TipLosing = 41
	}
}
