using System;
using UnityEngine;

namespace VRM
{
	public static class EnumExtensions
	{
		public static HumanBodyBones ToUnityBone(this VRMBone val)
		{
			return val switch
			{
				VRMBone.hips => HumanBodyBones.Hips, 
				VRMBone.leftUpperLeg => HumanBodyBones.LeftUpperLeg, 
				VRMBone.rightUpperLeg => HumanBodyBones.RightUpperLeg, 
				VRMBone.leftLowerLeg => HumanBodyBones.LeftLowerLeg, 
				VRMBone.rightLowerLeg => HumanBodyBones.RightLowerLeg, 
				VRMBone.leftFoot => HumanBodyBones.LeftFoot, 
				VRMBone.rightFoot => HumanBodyBones.RightFoot, 
				VRMBone.spine => HumanBodyBones.Spine, 
				VRMBone.chest => HumanBodyBones.Chest, 
				VRMBone.neck => HumanBodyBones.Neck, 
				VRMBone.head => HumanBodyBones.Head, 
				VRMBone.leftShoulder => HumanBodyBones.LeftShoulder, 
				VRMBone.rightShoulder => HumanBodyBones.RightShoulder, 
				VRMBone.leftUpperArm => HumanBodyBones.LeftUpperArm, 
				VRMBone.rightUpperArm => HumanBodyBones.RightUpperArm, 
				VRMBone.leftLowerArm => HumanBodyBones.LeftLowerArm, 
				VRMBone.rightLowerArm => HumanBodyBones.RightLowerArm, 
				VRMBone.leftHand => HumanBodyBones.LeftHand, 
				VRMBone.rightHand => HumanBodyBones.RightHand, 
				VRMBone.leftToes => HumanBodyBones.LeftToes, 
				VRMBone.rightToes => HumanBodyBones.RightToes, 
				VRMBone.leftEye => HumanBodyBones.LeftEye, 
				VRMBone.rightEye => HumanBodyBones.RightEye, 
				VRMBone.jaw => HumanBodyBones.Jaw, 
				VRMBone.leftThumbProximal => HumanBodyBones.LeftThumbProximal, 
				VRMBone.leftThumbIntermediate => HumanBodyBones.LeftThumbIntermediate, 
				VRMBone.leftThumbDistal => HumanBodyBones.LeftThumbDistal, 
				VRMBone.leftIndexProximal => HumanBodyBones.LeftIndexProximal, 
				VRMBone.leftIndexIntermediate => HumanBodyBones.LeftIndexIntermediate, 
				VRMBone.leftIndexDistal => HumanBodyBones.LeftIndexDistal, 
				VRMBone.leftMiddleProximal => HumanBodyBones.LeftMiddleProximal, 
				VRMBone.leftMiddleIntermediate => HumanBodyBones.LeftMiddleIntermediate, 
				VRMBone.leftMiddleDistal => HumanBodyBones.LeftMiddleDistal, 
				VRMBone.leftRingProximal => HumanBodyBones.LeftRingProximal, 
				VRMBone.leftRingIntermediate => HumanBodyBones.LeftRingIntermediate, 
				VRMBone.leftRingDistal => HumanBodyBones.LeftRingDistal, 
				VRMBone.leftLittleProximal => HumanBodyBones.LeftLittleProximal, 
				VRMBone.leftLittleIntermediate => HumanBodyBones.LeftLittleIntermediate, 
				VRMBone.leftLittleDistal => HumanBodyBones.LeftLittleDistal, 
				VRMBone.rightThumbProximal => HumanBodyBones.RightThumbProximal, 
				VRMBone.rightThumbIntermediate => HumanBodyBones.RightThumbIntermediate, 
				VRMBone.rightThumbDistal => HumanBodyBones.RightThumbDistal, 
				VRMBone.rightIndexProximal => HumanBodyBones.RightIndexProximal, 
				VRMBone.rightIndexIntermediate => HumanBodyBones.RightIndexIntermediate, 
				VRMBone.rightIndexDistal => HumanBodyBones.RightIndexDistal, 
				VRMBone.rightMiddleProximal => HumanBodyBones.RightMiddleProximal, 
				VRMBone.rightMiddleIntermediate => HumanBodyBones.RightMiddleIntermediate, 
				VRMBone.rightMiddleDistal => HumanBodyBones.RightMiddleDistal, 
				VRMBone.rightRingProximal => HumanBodyBones.RightRingProximal, 
				VRMBone.rightRingIntermediate => HumanBodyBones.RightRingIntermediate, 
				VRMBone.rightRingDistal => HumanBodyBones.RightRingDistal, 
				VRMBone.rightLittleProximal => HumanBodyBones.RightLittleProximal, 
				VRMBone.rightLittleIntermediate => HumanBodyBones.RightLittleIntermediate, 
				VRMBone.rightLittleDistal => HumanBodyBones.RightLittleDistal, 
				VRMBone.upperChest => HumanBodyBones.UpperChest, 
				_ => throw new InvalidOperationException(), 
			};
		}

		public static VRMBone ToVrmBone(this HumanBodyBones val)
		{
			return val switch
			{
				HumanBodyBones.Hips => VRMBone.hips, 
				HumanBodyBones.LeftUpperLeg => VRMBone.leftUpperLeg, 
				HumanBodyBones.RightUpperLeg => VRMBone.rightUpperLeg, 
				HumanBodyBones.LeftLowerLeg => VRMBone.leftLowerLeg, 
				HumanBodyBones.RightLowerLeg => VRMBone.rightLowerLeg, 
				HumanBodyBones.LeftFoot => VRMBone.leftFoot, 
				HumanBodyBones.RightFoot => VRMBone.rightFoot, 
				HumanBodyBones.Spine => VRMBone.spine, 
				HumanBodyBones.Chest => VRMBone.chest, 
				HumanBodyBones.Neck => VRMBone.neck, 
				HumanBodyBones.Head => VRMBone.head, 
				HumanBodyBones.LeftShoulder => VRMBone.leftShoulder, 
				HumanBodyBones.RightShoulder => VRMBone.rightShoulder, 
				HumanBodyBones.LeftUpperArm => VRMBone.leftUpperArm, 
				HumanBodyBones.RightUpperArm => VRMBone.rightUpperArm, 
				HumanBodyBones.LeftLowerArm => VRMBone.leftLowerArm, 
				HumanBodyBones.RightLowerArm => VRMBone.rightLowerArm, 
				HumanBodyBones.LeftHand => VRMBone.leftHand, 
				HumanBodyBones.RightHand => VRMBone.rightHand, 
				HumanBodyBones.LeftToes => VRMBone.leftToes, 
				HumanBodyBones.RightToes => VRMBone.rightToes, 
				HumanBodyBones.LeftEye => VRMBone.leftEye, 
				HumanBodyBones.RightEye => VRMBone.rightEye, 
				HumanBodyBones.Jaw => VRMBone.jaw, 
				HumanBodyBones.LeftThumbProximal => VRMBone.leftThumbProximal, 
				HumanBodyBones.LeftThumbIntermediate => VRMBone.leftThumbIntermediate, 
				HumanBodyBones.LeftThumbDistal => VRMBone.leftThumbDistal, 
				HumanBodyBones.LeftIndexProximal => VRMBone.leftIndexProximal, 
				HumanBodyBones.LeftIndexIntermediate => VRMBone.leftIndexIntermediate, 
				HumanBodyBones.LeftIndexDistal => VRMBone.leftIndexDistal, 
				HumanBodyBones.LeftMiddleProximal => VRMBone.leftMiddleProximal, 
				HumanBodyBones.LeftMiddleIntermediate => VRMBone.leftMiddleIntermediate, 
				HumanBodyBones.LeftMiddleDistal => VRMBone.leftMiddleDistal, 
				HumanBodyBones.LeftRingProximal => VRMBone.leftRingProximal, 
				HumanBodyBones.LeftRingIntermediate => VRMBone.leftRingIntermediate, 
				HumanBodyBones.LeftRingDistal => VRMBone.leftRingDistal, 
				HumanBodyBones.LeftLittleProximal => VRMBone.leftLittleProximal, 
				HumanBodyBones.LeftLittleIntermediate => VRMBone.leftLittleIntermediate, 
				HumanBodyBones.LeftLittleDistal => VRMBone.leftLittleDistal, 
				HumanBodyBones.RightThumbProximal => VRMBone.rightThumbProximal, 
				HumanBodyBones.RightThumbIntermediate => VRMBone.rightThumbIntermediate, 
				HumanBodyBones.RightThumbDistal => VRMBone.rightThumbDistal, 
				HumanBodyBones.RightIndexProximal => VRMBone.rightIndexProximal, 
				HumanBodyBones.RightIndexIntermediate => VRMBone.rightIndexIntermediate, 
				HumanBodyBones.RightIndexDistal => VRMBone.rightIndexDistal, 
				HumanBodyBones.RightMiddleProximal => VRMBone.rightMiddleProximal, 
				HumanBodyBones.RightMiddleIntermediate => VRMBone.rightMiddleIntermediate, 
				HumanBodyBones.RightMiddleDistal => VRMBone.rightMiddleDistal, 
				HumanBodyBones.RightRingProximal => VRMBone.rightRingProximal, 
				HumanBodyBones.RightRingIntermediate => VRMBone.rightRingIntermediate, 
				HumanBodyBones.RightRingDistal => VRMBone.rightRingDistal, 
				HumanBodyBones.RightLittleProximal => VRMBone.rightLittleProximal, 
				HumanBodyBones.RightLittleIntermediate => VRMBone.rightLittleIntermediate, 
				HumanBodyBones.RightLittleDistal => VRMBone.rightLittleDistal, 
				HumanBodyBones.UpperChest => VRMBone.upperChest, 
				_ => throw new InvalidOperationException(), 
			};
		}
	}
}
