using System.Collections.Generic;
using UniGLTF;
using UniJSON;
using UnityEngine;

namespace VRM
{
	public static class VRMAOTCall
	{
		private static void glTF()
		{
			JsonFormatter f = new JsonFormatter();
			f.Serialize<string>(null);
			string value = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value);
			f.Serialize(arg: false);
			bool value2 = false;
			default(ListTreeNode<JsonValue>).Deserialize(ref value2);
			((IFormatter)f).Serialize((byte)0);
			byte value3 = 0;
			default(ListTreeNode<JsonValue>).Deserialize(ref value3);
			((IFormatter)f).Serialize((ushort)0);
			ushort value4 = 0;
			default(ListTreeNode<JsonValue>).Deserialize(ref value4);
			f.Serialize(0u);
			uint value5 = 0u;
			default(ListTreeNode<JsonValue>).Deserialize(ref value5);
			f.Serialize(0uL);
			ulong value6 = 0uL;
			default(ListTreeNode<JsonValue>).Deserialize(ref value6);
			((IFormatter)f).Serialize((sbyte)0);
			sbyte value7 = 0;
			default(ListTreeNode<JsonValue>).Deserialize(ref value7);
			((IFormatter)f).Serialize((short)0);
			short value8 = 0;
			default(ListTreeNode<JsonValue>).Deserialize(ref value8);
			f.Serialize(0);
			int value9 = 0;
			default(ListTreeNode<JsonValue>).Deserialize(ref value9);
			f.Serialize(0L);
			long value10 = 0L;
			default(ListTreeNode<JsonValue>).Deserialize(ref value10);
			f.Serialize(0f);
			float value11 = 0f;
			default(ListTreeNode<JsonValue>).Deserialize(ref value11);
			f.Serialize(0.0);
			double value12 = 0.0;
			default(ListTreeNode<JsonValue>).Deserialize(ref value12);
			f.Serialize(default(Vector2));
			Vector2 value13 = default(Vector2);
			default(ListTreeNode<JsonValue>).Deserialize(ref value13);
			JsonObjectValidator.GenericDeserializer<JsonValue, Vector2>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, Vector2>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			f.Serialize(default(Vector3));
			Vector3 value14 = default(Vector3);
			default(ListTreeNode<JsonValue>).Deserialize(ref value14);
			JsonObjectValidator.GenericDeserializer<JsonValue, Vector3>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, Vector3>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, Vector3>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			f.Serialize(default(Vector4));
			Vector4 value15 = default(Vector4);
			default(ListTreeNode<JsonValue>).Deserialize(ref value15);
			JsonObjectValidator.GenericDeserializer<JsonValue, Vector4>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, Vector4>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, Vector4>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, Vector4>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			f.Serialize(default(Quaternion));
			Quaternion value16 = default(Quaternion);
			default(ListTreeNode<JsonValue>).Deserialize(ref value16);
			JsonObjectValidator.GenericDeserializer<JsonValue, Quaternion>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, Quaternion>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, Quaternion>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, Quaternion>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTF>(null);
			glTF value17 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value17);
			JsonObjectValidator.GenericDeserializer<JsonValue, UniGLTF.glTF>.DeserializeField<glTFAssets>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFAssets>(null);
			glTFAssets value18 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value18);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAssets>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAssets>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAssets>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAssets>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAssets>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAssets>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, UniGLTF.glTF>.DeserializeField<List<glTFBuffer>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTFBuffer>>(null);
			List<glTFBuffer> value19 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value19);
			GenericDeserializer<JsonValue, List<glTFBuffer>>.GenericListDeserializer<glTFBuffer>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTFBuffer>(null);
			glTFBuffer value20 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value20);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFBuffer>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFBuffer>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFBuffer>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFBuffer>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFBuffer>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, UniGLTF.glTF>.DeserializeField<List<glTFBufferView>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTFBufferView>>(null);
			List<glTFBufferView> value21 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value21);
			GenericDeserializer<JsonValue, List<glTFBufferView>>.GenericListDeserializer<glTFBufferView>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTFBufferView>(null);
			glTFBufferView value22 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value22);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFBufferView>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFBufferView>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFBufferView>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFBufferView>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFBufferView>.DeserializeField<glBufferTarget>(null, default(ListTreeNode<JsonValue>));
			f.Serialize(glBufferTarget.NONE);
			glBufferTarget value23 = glBufferTarget.NONE;
			default(ListTreeNode<JsonValue>).Deserialize(ref value23);
			JsonObjectValidator.GenericDeserializer<JsonValue, glBufferTarget>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFBufferView>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFBufferView>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFBufferView>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, UniGLTF.glTF>.DeserializeField<List<glTFAccessor>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTFAccessor>>(null);
			List<glTFAccessor> value24 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value24);
			GenericDeserializer<JsonValue, List<glTFAccessor>>.GenericListDeserializer<glTFAccessor>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTFAccessor>(null);
			glTFAccessor value25 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value25);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAccessor>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAccessor>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAccessor>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAccessor>.DeserializeField<glComponentType>(null, default(ListTreeNode<JsonValue>));
			f.Serialize((glComponentType)0);
			glComponentType value26 = (glComponentType)0;
			default(ListTreeNode<JsonValue>).Deserialize(ref value26);
			JsonObjectValidator.GenericDeserializer<JsonValue, glComponentType>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAccessor>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAccessor>.DeserializeField<float[]>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<float[]>(null);
			float[] value27 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value27);
			GenericDeserializer<JsonValue, float[]>.GenericArrayDeserializer<float>(default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAccessor>.DeserializeField<float[]>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAccessor>.DeserializeField<bool>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAccessor>.DeserializeField<glTFSparse>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFSparse>(null);
			glTFSparse value28 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value28);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSparse>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSparse>.DeserializeField<glTFSparseIndices>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFSparseIndices>(null);
			glTFSparseIndices value29 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value29);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSparseIndices>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSparseIndices>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSparseIndices>.DeserializeField<glComponentType>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSparseIndices>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSparseIndices>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSparse>.DeserializeField<glTFSparseValues>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFSparseValues>(null);
			glTFSparseValues value30 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value30);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSparseValues>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSparseValues>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSparseValues>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSparseValues>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSparse>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSparse>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAccessor>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAccessor>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAccessor>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, UniGLTF.glTF>.DeserializeField<List<glTFTexture>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTFTexture>>(null);
			List<glTFTexture> value31 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value31);
			GenericDeserializer<JsonValue, List<glTFTexture>>.GenericListDeserializer<glTFTexture>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTFTexture>(null);
			glTFTexture value32 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value32);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFTexture>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFTexture>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFTexture>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFTexture>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFTexture>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, UniGLTF.glTF>.DeserializeField<List<glTFTextureSampler>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTFTextureSampler>>(null);
			List<glTFTextureSampler> value33 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value33);
			GenericDeserializer<JsonValue, List<glTFTextureSampler>>.GenericListDeserializer<glTFTextureSampler>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTFTextureSampler>(null);
			glTFTextureSampler value34 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value34);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFTextureSampler>.DeserializeField<glFilter>(null, default(ListTreeNode<JsonValue>));
			f.Serialize(glFilter.NONE);
			glFilter value35 = glFilter.NONE;
			default(ListTreeNode<JsonValue>).Deserialize(ref value35);
			JsonObjectValidator.GenericDeserializer<JsonValue, glFilter>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFTextureSampler>.DeserializeField<glFilter>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFTextureSampler>.DeserializeField<glWrap>(null, default(ListTreeNode<JsonValue>));
			f.Serialize(glWrap.NONE);
			glWrap value36 = glWrap.NONE;
			default(ListTreeNode<JsonValue>).Deserialize(ref value36);
			JsonObjectValidator.GenericDeserializer<JsonValue, glWrap>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFTextureSampler>.DeserializeField<glWrap>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFTextureSampler>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFTextureSampler>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFTextureSampler>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, UniGLTF.glTF>.DeserializeField<List<glTFImage>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTFImage>>(null);
			List<glTFImage> value37 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value37);
			GenericDeserializer<JsonValue, List<glTFImage>>.GenericListDeserializer<glTFImage>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTFImage>(null);
			glTFImage value38 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value38);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFImage>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFImage>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFImage>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFImage>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFImage>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFImage>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, UniGLTF.glTF>.DeserializeField<List<glTFMaterial>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTFMaterial>>(null);
			List<glTFMaterial> value39 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value39);
			GenericDeserializer<JsonValue, List<glTFMaterial>>.GenericListDeserializer<glTFMaterial>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTFMaterial>(null);
			glTFMaterial value40 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value40);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterial>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterial>.DeserializeField<glTFPbrMetallicRoughness>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFPbrMetallicRoughness>(null);
			glTFPbrMetallicRoughness value41 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value41);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPbrMetallicRoughness>.DeserializeField<glTFMaterialBaseColorTextureInfo>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFMaterialBaseColorTextureInfo>(null);
			glTFMaterialBaseColorTextureInfo value42 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value42);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialBaseColorTextureInfo>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialBaseColorTextureInfo>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialBaseColorTextureInfo>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialBaseColorTextureInfo>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPbrMetallicRoughness>.DeserializeField<float[]>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPbrMetallicRoughness>.DeserializeField<glTFMaterialMetallicRoughnessTextureInfo>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFMaterialMetallicRoughnessTextureInfo>(null);
			glTFMaterialMetallicRoughnessTextureInfo value43 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value43);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialMetallicRoughnessTextureInfo>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialMetallicRoughnessTextureInfo>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialMetallicRoughnessTextureInfo>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialMetallicRoughnessTextureInfo>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPbrMetallicRoughness>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPbrMetallicRoughness>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPbrMetallicRoughness>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPbrMetallicRoughness>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterial>.DeserializeField<glTFMaterialNormalTextureInfo>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFMaterialNormalTextureInfo>(null);
			glTFMaterialNormalTextureInfo value44 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value44);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialNormalTextureInfo>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialNormalTextureInfo>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialNormalTextureInfo>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialNormalTextureInfo>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialNormalTextureInfo>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterial>.DeserializeField<glTFMaterialOcclusionTextureInfo>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFMaterialOcclusionTextureInfo>(null);
			glTFMaterialOcclusionTextureInfo value45 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value45);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialOcclusionTextureInfo>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialOcclusionTextureInfo>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialOcclusionTextureInfo>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialOcclusionTextureInfo>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialOcclusionTextureInfo>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterial>.DeserializeField<glTFMaterialEmissiveTextureInfo>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFMaterialEmissiveTextureInfo>(null);
			glTFMaterialEmissiveTextureInfo value46 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value46);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialEmissiveTextureInfo>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialEmissiveTextureInfo>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialEmissiveTextureInfo>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterialEmissiveTextureInfo>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterial>.DeserializeField<float[]>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterial>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterial>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterial>.DeserializeField<bool>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterial>.DeserializeField<glTFMaterial_extensions>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFMaterial_extensions>(null);
			glTFMaterial_extensions value47 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value47);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterial_extensions>.DeserializeField<glTF_KHR_materials_unlit>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTF_KHR_materials_unlit>(null);
			glTF_KHR_materials_unlit value48 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value48);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMaterial>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, UniGLTF.glTF>.DeserializeField<List<glTFMesh>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTFMesh>>(null);
			List<glTFMesh> value49 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value49);
			GenericDeserializer<JsonValue, List<glTFMesh>>.GenericListDeserializer<glTFMesh>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTFMesh>(null);
			glTFMesh value50 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value50);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMesh>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMesh>.DeserializeField<List<glTFPrimitives>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTFPrimitives>>(null);
			List<glTFPrimitives> value51 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value51);
			GenericDeserializer<JsonValue, List<glTFPrimitives>>.GenericListDeserializer<glTFPrimitives>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTFPrimitives>(null);
			glTFPrimitives value52 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value52);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPrimitives>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPrimitives>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPrimitives>.DeserializeField<glTFAttributes>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFAttributes>(null);
			glTFAttributes value53 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value53);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAttributes>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAttributes>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAttributes>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAttributes>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAttributes>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAttributes>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAttributes>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPrimitives>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPrimitives>.DeserializeField<List<gltfMorphTarget>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<gltfMorphTarget>>(null);
			List<gltfMorphTarget> value54 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value54);
			GenericDeserializer<JsonValue, List<gltfMorphTarget>>.GenericListDeserializer<gltfMorphTarget>(default(ListTreeNode<JsonValue>));
			f.Serialize<gltfMorphTarget>(null);
			gltfMorphTarget value55 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value55);
			JsonObjectValidator.GenericDeserializer<JsonValue, gltfMorphTarget>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, gltfMorphTarget>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, gltfMorphTarget>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPrimitives>.DeserializeField<glTFPrimitives_extras>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFPrimitives_extras>(null);
			glTFPrimitives_extras value56 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value56);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPrimitives_extras>.DeserializeField<List<string>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<string>>(null);
			List<string> value57 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value57);
			GenericDeserializer<JsonValue, List<string>>.GenericListDeserializer<string>(default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPrimitives>.DeserializeField<glTFPrimitives_extensions>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFPrimitives_extensions>(null);
			glTFPrimitives_extensions value58 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value58);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMesh>.DeserializeField<float[]>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMesh>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFMesh>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, UniGLTF.glTF>.DeserializeField<List<glTFNode>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTFNode>>(null);
			List<glTFNode> value59 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value59);
			GenericDeserializer<JsonValue, List<glTFNode>>.GenericListDeserializer<glTFNode>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTFNode>(null);
			glTFNode value60 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value60);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFNode>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFNode>.DeserializeField<int[]>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<int[]>(null);
			int[] value61 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value61);
			GenericDeserializer<JsonValue, int[]>.GenericArrayDeserializer<int>(default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFNode>.DeserializeField<float[]>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFNode>.DeserializeField<float[]>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFNode>.DeserializeField<float[]>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFNode>.DeserializeField<float[]>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFNode>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFNode>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFNode>.DeserializeField<float[]>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFNode>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFNode>.DeserializeField<glTFNode_extensions>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFNode_extensions>(null);
			glTFNode_extensions value62 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value62);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFNode>.DeserializeField<glTFNode_extra>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFNode_extra>(null);
			glTFNode_extra value63 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value63);
			JsonObjectValidator.GenericDeserializer<JsonValue, UniGLTF.glTF>.DeserializeField<List<glTFSkin>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTFSkin>>(null);
			List<glTFSkin> value64 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value64);
			GenericDeserializer<JsonValue, List<glTFSkin>>.GenericListDeserializer<glTFSkin>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTFSkin>(null);
			glTFSkin value65 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value65);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSkin>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSkin>.DeserializeField<int[]>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSkin>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSkin>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSkin>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFSkin>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, UniGLTF.glTF>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, UniGLTF.glTF>.DeserializeField<List<gltfScene>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<gltfScene>>(null);
			List<gltfScene> value66 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value66);
			GenericDeserializer<JsonValue, List<gltfScene>>.GenericListDeserializer<gltfScene>(default(ListTreeNode<JsonValue>));
			f.Serialize<gltfScene>(null);
			gltfScene value67 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value67);
			JsonObjectValidator.GenericDeserializer<JsonValue, gltfScene>.DeserializeField<int[]>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, gltfScene>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, gltfScene>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, gltfScene>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, UniGLTF.glTF>.DeserializeField<List<glTFAnimation>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTFAnimation>>(null);
			List<glTFAnimation> value68 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value68);
			GenericDeserializer<JsonValue, List<glTFAnimation>>.GenericListDeserializer<glTFAnimation>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTFAnimation>(null);
			glTFAnimation value69 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value69);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAnimation>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAnimation>.DeserializeField<List<glTFAnimationChannel>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTFAnimationChannel>>(null);
			List<glTFAnimationChannel> value70 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value70);
			GenericDeserializer<JsonValue, List<glTFAnimationChannel>>.GenericListDeserializer<glTFAnimationChannel>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTFAnimationChannel>(null);
			glTFAnimationChannel value71 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value71);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAnimationChannel>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAnimationChannel>.DeserializeField<glTFAnimationTarget>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFAnimationTarget>(null);
			glTFAnimationTarget value72 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value72);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAnimationTarget>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAnimationTarget>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAnimationTarget>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAnimationTarget>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAnimationChannel>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAnimationChannel>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAnimation>.DeserializeField<List<glTFAnimationSampler>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTFAnimationSampler>>(null);
			List<glTFAnimationSampler> value73 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value73);
			GenericDeserializer<JsonValue, List<glTFAnimationSampler>>.GenericListDeserializer<glTFAnimationSampler>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTFAnimationSampler>(null);
			glTFAnimationSampler value74 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value74);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAnimationSampler>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAnimationSampler>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAnimationSampler>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAnimationSampler>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAnimationSampler>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAnimation>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFAnimation>.DeserializeField<object>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, UniGLTF.glTF>.DeserializeField<List<glTFCamera>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTFCamera>>(null);
			List<glTFCamera> value75 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value75);
			GenericDeserializer<JsonValue, List<glTFCamera>>.GenericListDeserializer<glTFCamera>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTFCamera>(null);
			glTFCamera value76 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value76);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFCamera>.DeserializeField<glTFOrthographic>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFOrthographic>(null);
			glTFOrthographic value77 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value77);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFOrthographic>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFOrthographic>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFOrthographic>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFOrthographic>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFOrthographic>.DeserializeField<glTFOrthographic_extensions>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFOrthographic_extensions>(null);
			glTFOrthographic_extensions value78 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value78);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFOrthographic>.DeserializeField<glTFOrthographic_extras>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFOrthographic_extras>(null);
			glTFOrthographic_extras value79 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value79);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFCamera>.DeserializeField<glTFPerspective>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFPerspective>(null);
			glTFPerspective value80 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value80);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPerspective>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPerspective>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPerspective>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPerspective>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPerspective>.DeserializeField<glTFPerspective_extensions>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFPerspective_extensions>(null);
			glTFPerspective_extensions value81 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value81);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFPerspective>.DeserializeField<glTFPerspective_extras>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFPerspective_extras>(null);
			glTFPerspective_extras value82 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value82);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFCamera>.DeserializeField<ProjectionType>(null, default(ListTreeNode<JsonValue>));
			f.Serialize(ProjectionType.Perspective);
			ProjectionType value83 = ProjectionType.Perspective;
			default(ListTreeNode<JsonValue>).Deserialize(ref value83);
			JsonObjectValidator.GenericDeserializer<JsonValue, ProjectionType>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFCamera>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFCamera>.DeserializeField<glTFCamera_extensions>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFCamera_extensions>(null);
			glTFCamera_extensions value84 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value84);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTFCamera>.DeserializeField<glTFCamera_extras>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTFCamera_extras>(null);
			glTFCamera_extras value85 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value85);
			JsonObjectValidator.GenericDeserializer<JsonValue, UniGLTF.glTF>.DeserializeField<List<string>>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, UniGLTF.glTF>.DeserializeField<List<string>>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, UniGLTF.glTF>.DeserializeField<glTF_extensions>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTF_extensions>(null);
			glTF_extensions value86 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value86);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_extensions>.DeserializeField<glTF_VRM_extensions>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTF_VRM_extensions>(null);
			glTF_VRM_extensions value87 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value87);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_extensions>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_extensions>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_extensions>.DeserializeField<glTF_VRM_Meta>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTF_VRM_Meta>(null);
			glTF_VRM_Meta value88 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value88);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Meta>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Meta>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Meta>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Meta>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Meta>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Meta>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Meta>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Meta>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Meta>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Meta>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Meta>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Meta>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Meta>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_extensions>.DeserializeField<glTF_VRM_Humanoid>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTF_VRM_Humanoid>(null);
			glTF_VRM_Humanoid value89 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value89);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Humanoid>.DeserializeField<List<glTF_VRM_HumanoidBone>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTF_VRM_HumanoidBone>>(null);
			List<glTF_VRM_HumanoidBone> value90 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value90);
			GenericDeserializer<JsonValue, List<glTF_VRM_HumanoidBone>>.GenericListDeserializer<glTF_VRM_HumanoidBone>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTF_VRM_HumanoidBone>(null);
			glTF_VRM_HumanoidBone value91 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value91);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_HumanoidBone>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_HumanoidBone>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_HumanoidBone>.DeserializeField<bool>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_HumanoidBone>.DeserializeField<Vector3>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_HumanoidBone>.DeserializeField<Vector3>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_HumanoidBone>.DeserializeField<Vector3>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_HumanoidBone>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Humanoid>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Humanoid>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Humanoid>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Humanoid>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Humanoid>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Humanoid>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Humanoid>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Humanoid>.DeserializeField<bool>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_extensions>.DeserializeField<glTF_VRM_Firstperson>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTF_VRM_Firstperson>(null);
			glTF_VRM_Firstperson value92 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value92);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Firstperson>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Firstperson>.DeserializeField<Vector3>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Firstperson>.DeserializeField<List<glTF_VRM_MeshAnnotation>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTF_VRM_MeshAnnotation>>(null);
			List<glTF_VRM_MeshAnnotation> value93 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value93);
			GenericDeserializer<JsonValue, List<glTF_VRM_MeshAnnotation>>.GenericListDeserializer<glTF_VRM_MeshAnnotation>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTF_VRM_MeshAnnotation>(null);
			glTF_VRM_MeshAnnotation value94 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value94);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_MeshAnnotation>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_MeshAnnotation>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Firstperson>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Firstperson>.DeserializeField<glTF_VRM_DegreeMap>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTF_VRM_DegreeMap>(null);
			glTF_VRM_DegreeMap value95 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value95);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_DegreeMap>.DeserializeField<float[]>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_DegreeMap>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_DegreeMap>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Firstperson>.DeserializeField<glTF_VRM_DegreeMap>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Firstperson>.DeserializeField<glTF_VRM_DegreeMap>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Firstperson>.DeserializeField<glTF_VRM_DegreeMap>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_extensions>.DeserializeField<glTF_VRM_BlendShapeMaster>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTF_VRM_BlendShapeMaster>(null);
			glTF_VRM_BlendShapeMaster value96 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value96);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_BlendShapeMaster>.DeserializeField<List<glTF_VRM_BlendShapeGroup>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTF_VRM_BlendShapeGroup>>(null);
			List<glTF_VRM_BlendShapeGroup> value97 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value97);
			GenericDeserializer<JsonValue, List<glTF_VRM_BlendShapeGroup>>.GenericListDeserializer<glTF_VRM_BlendShapeGroup>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTF_VRM_BlendShapeGroup>(null);
			glTF_VRM_BlendShapeGroup value98 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value98);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_BlendShapeGroup>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_BlendShapeGroup>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_BlendShapeGroup>.DeserializeField<List<glTF_VRM_BlendShapeBind>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTF_VRM_BlendShapeBind>>(null);
			List<glTF_VRM_BlendShapeBind> value99 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value99);
			GenericDeserializer<JsonValue, List<glTF_VRM_BlendShapeBind>>.GenericListDeserializer<glTF_VRM_BlendShapeBind>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTF_VRM_BlendShapeBind>(null);
			glTF_VRM_BlendShapeBind value100 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value100);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_BlendShapeBind>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_BlendShapeBind>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_BlendShapeBind>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_BlendShapeGroup>.DeserializeField<List<glTF_VRM_MaterialValueBind>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTF_VRM_MaterialValueBind>>(null);
			List<glTF_VRM_MaterialValueBind> value101 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value101);
			GenericDeserializer<JsonValue, List<glTF_VRM_MaterialValueBind>>.GenericListDeserializer<glTF_VRM_MaterialValueBind>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTF_VRM_MaterialValueBind>(null);
			glTF_VRM_MaterialValueBind value102 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value102);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_MaterialValueBind>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_MaterialValueBind>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_MaterialValueBind>.DeserializeField<float[]>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_BlendShapeGroup>.DeserializeField<bool>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_extensions>.DeserializeField<glTF_VRM_SecondaryAnimation>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<glTF_VRM_SecondaryAnimation>(null);
			glTF_VRM_SecondaryAnimation value103 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value103);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_SecondaryAnimation>.DeserializeField<List<glTF_VRM_SecondaryAnimationGroup>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTF_VRM_SecondaryAnimationGroup>>(null);
			List<glTF_VRM_SecondaryAnimationGroup> value104 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value104);
			GenericDeserializer<JsonValue, List<glTF_VRM_SecondaryAnimationGroup>>.GenericListDeserializer<glTF_VRM_SecondaryAnimationGroup>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTF_VRM_SecondaryAnimationGroup>(null);
			glTF_VRM_SecondaryAnimationGroup value105 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value105);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_SecondaryAnimationGroup>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_SecondaryAnimationGroup>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_SecondaryAnimationGroup>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_SecondaryAnimationGroup>.DeserializeField<Vector3>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_SecondaryAnimationGroup>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_SecondaryAnimationGroup>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_SecondaryAnimationGroup>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_SecondaryAnimationGroup>.DeserializeField<int[]>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_SecondaryAnimationGroup>.DeserializeField<int[]>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_SecondaryAnimation>.DeserializeField<List<glTF_VRM_SecondaryAnimationColliderGroup>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTF_VRM_SecondaryAnimationColliderGroup>>(null);
			List<glTF_VRM_SecondaryAnimationColliderGroup> value106 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value106);
			GenericDeserializer<JsonValue, List<glTF_VRM_SecondaryAnimationColliderGroup>>.GenericListDeserializer<glTF_VRM_SecondaryAnimationColliderGroup>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTF_VRM_SecondaryAnimationColliderGroup>(null);
			glTF_VRM_SecondaryAnimationColliderGroup value107 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value107);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_SecondaryAnimationColliderGroup>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_SecondaryAnimationColliderGroup>.DeserializeField<List<glTF_VRM_SecondaryAnimationCollider>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTF_VRM_SecondaryAnimationCollider>>(null);
			List<glTF_VRM_SecondaryAnimationCollider> value108 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value108);
			GenericDeserializer<JsonValue, List<glTF_VRM_SecondaryAnimationCollider>>.GenericListDeserializer<glTF_VRM_SecondaryAnimationCollider>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTF_VRM_SecondaryAnimationCollider>(null);
			glTF_VRM_SecondaryAnimationCollider value109 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value109);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_SecondaryAnimationCollider>.DeserializeField<Vector3>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_SecondaryAnimationCollider>.DeserializeField<float>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_extensions>.DeserializeField<List<glTF_VRM_Material>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<List<glTF_VRM_Material>>(null);
			List<glTF_VRM_Material> value110 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value110);
			GenericDeserializer<JsonValue, List<glTF_VRM_Material>>.GenericListDeserializer<glTF_VRM_Material>(default(ListTreeNode<JsonValue>));
			f.Serialize<glTF_VRM_Material>(null);
			glTF_VRM_Material value111 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value111);
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Material>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Material>.DeserializeField<string>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Material>.DeserializeField<int>(null, default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Material>.DeserializeField<Dictionary<string, float>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<Dictionary<string, float>>(null);
			Dictionary<string, float> value112 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value112);
			GenericDeserializer<JsonValue, Dictionary<string, float>>.DictionaryDeserializer<float>(default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Material>.DeserializeField<Dictionary<string, float[]>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<Dictionary<string, float[]>>(null);
			Dictionary<string, float[]> value113 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value113);
			GenericDeserializer<JsonValue, Dictionary<string, float[]>>.DictionaryDeserializer<float[]>(default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Material>.DeserializeField<Dictionary<string, int>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<Dictionary<string, int>>(null);
			Dictionary<string, int> value114 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value114);
			GenericDeserializer<JsonValue, Dictionary<string, int>>.DictionaryDeserializer<int>(default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Material>.DeserializeField<Dictionary<string, bool>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<Dictionary<string, bool>>(null);
			Dictionary<string, bool> value115 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value115);
			GenericDeserializer<JsonValue, Dictionary<string, bool>>.DictionaryDeserializer<bool>(default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, glTF_VRM_Material>.DeserializeField<Dictionary<string, string>>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<Dictionary<string, string>>(null);
			Dictionary<string, string> value116 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value116);
			GenericDeserializer<JsonValue, Dictionary<string, string>>.DictionaryDeserializer<string>(default(ListTreeNode<JsonValue>));
			JsonObjectValidator.GenericDeserializer<JsonValue, UniGLTF.glTF>.DeserializeField<gltf_extras>(null, default(ListTreeNode<JsonValue>));
			f.Serialize<gltf_extras>(null);
			gltf_extras value117 = null;
			default(ListTreeNode<JsonValue>).Deserialize(ref value117);
			MsgPackFormatter f2 = new MsgPackFormatter();
			f2.Serialize<string>(null);
			string value118 = null;
			default(ListTreeNode<MsgPackValue>).Deserialize(ref value118);
			f2.Serialize(arg: false);
			bool value119 = false;
			default(ListTreeNode<MsgPackValue>).Deserialize(ref value119);
			((IFormatter)f2).Serialize((byte)0);
			byte value120 = 0;
			default(ListTreeNode<MsgPackValue>).Deserialize(ref value120);
			((IFormatter)f2).Serialize((ushort)0);
			ushort value121 = 0;
			default(ListTreeNode<MsgPackValue>).Deserialize(ref value121);
			f2.Serialize(0u);
			uint value122 = 0u;
			default(ListTreeNode<MsgPackValue>).Deserialize(ref value122);
			f2.Serialize(0uL);
			ulong value123 = 0uL;
			default(ListTreeNode<MsgPackValue>).Deserialize(ref value123);
			((IFormatter)f2).Serialize((sbyte)0);
			sbyte value124 = 0;
			default(ListTreeNode<MsgPackValue>).Deserialize(ref value124);
			((IFormatter)f2).Serialize((short)0);
			short value125 = 0;
			default(ListTreeNode<MsgPackValue>).Deserialize(ref value125);
			f2.Serialize(0);
			int value126 = 0;
			default(ListTreeNode<MsgPackValue>).Deserialize(ref value126);
			f2.Serialize(0L);
			long value127 = 0L;
			default(ListTreeNode<MsgPackValue>).Deserialize(ref value127);
			f2.Serialize(0f);
			float value128 = 0f;
			default(ListTreeNode<MsgPackValue>).Deserialize(ref value128);
			f2.Serialize(0.0);
			double value129 = 0.0;
			default(ListTreeNode<MsgPackValue>).Deserialize(ref value129);
			f2.Serialize(default(Vector2));
			Vector2 value130 = default(Vector2);
			default(ListTreeNode<MsgPackValue>).Deserialize(ref value130);
			JsonObjectValidator.GenericDeserializer<MsgPackValue, Vector2>.DeserializeField<float>(null, default(ListTreeNode<MsgPackValue>));
			JsonObjectValidator.GenericDeserializer<MsgPackValue, Vector2>.DeserializeField<float>(null, default(ListTreeNode<MsgPackValue>));
			f2.Serialize(default(Vector3));
			Vector3 value131 = default(Vector3);
			default(ListTreeNode<MsgPackValue>).Deserialize(ref value131);
			JsonObjectValidator.GenericDeserializer<MsgPackValue, Vector3>.DeserializeField<float>(null, default(ListTreeNode<MsgPackValue>));
			JsonObjectValidator.GenericDeserializer<MsgPackValue, Vector3>.DeserializeField<float>(null, default(ListTreeNode<MsgPackValue>));
			JsonObjectValidator.GenericDeserializer<MsgPackValue, Vector3>.DeserializeField<float>(null, default(ListTreeNode<MsgPackValue>));
			f2.Serialize(default(Vector4));
			Vector4 value132 = default(Vector4);
			default(ListTreeNode<MsgPackValue>).Deserialize(ref value132);
			JsonObjectValidator.GenericDeserializer<MsgPackValue, Vector4>.DeserializeField<float>(null, default(ListTreeNode<MsgPackValue>));
			JsonObjectValidator.GenericDeserializer<MsgPackValue, Vector4>.DeserializeField<float>(null, default(ListTreeNode<MsgPackValue>));
			JsonObjectValidator.GenericDeserializer<MsgPackValue, Vector4>.DeserializeField<float>(null, default(ListTreeNode<MsgPackValue>));
			JsonObjectValidator.GenericDeserializer<MsgPackValue, Vector4>.DeserializeField<float>(null, default(ListTreeNode<MsgPackValue>));
			f2.Serialize(default(Quaternion));
			Quaternion value133 = default(Quaternion);
			default(ListTreeNode<MsgPackValue>).Deserialize(ref value133);
			JsonObjectValidator.GenericDeserializer<MsgPackValue, Quaternion>.DeserializeField<float>(null, default(ListTreeNode<MsgPackValue>));
			JsonObjectValidator.GenericDeserializer<MsgPackValue, Quaternion>.DeserializeField<float>(null, default(ListTreeNode<MsgPackValue>));
			JsonObjectValidator.GenericDeserializer<MsgPackValue, Quaternion>.DeserializeField<float>(null, default(ListTreeNode<MsgPackValue>));
			JsonObjectValidator.GenericDeserializer<MsgPackValue, Quaternion>.DeserializeField<float>(null, default(ListTreeNode<MsgPackValue>));
		}
	}
}
