<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>WaveHarmonic.Crest.Splines</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Splines">
      <HintPath>..\..\Assemblies\Unity.Splines.dll</HintPath>
    </Reference>
    <Reference Include="WaveHarmonic.Crest">
      <HintPath>..\..\Assemblies\WaveHarmonic.Crest.dll</HintPath>
    </Reference>
    <Reference Include="WaveHarmonic.Crest.Shared">
      <HintPath>..\..\Assemblies\WaveHarmonic.Crest.Shared.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>..\..\Assemblies\Unity.Mathematics.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>