internal sealed class NkcKYvpmWiToUUnkSELpKtsYoLaS
{
	public static readonly FzkesOdlmEKeUoFPBrNHWqaVXvon SWtzVMnDvtaZxcceFdpkEADwHdQe = JSnuuYqTWjnVNJDwWLtBLGuASxDb.xOOUDJxPSVMpgqGRoGnCNwaoCHpgA(BWGNXeiqHfFsxVNGOvPjUuaUAOJc.DeviceNotConnected);
}
