namespace UI
{
	public enum eDialog
	{
		None = 0,
		SettingDialog = 1,
		ConfirmDialog = 2,
		CollectionDialog = 3,
		ShopDialog = 4,
		RewardDialog = 5,
		TreeDialog = 6,
		OutShopDialog = 7,
		ResultDialog = 8,
		HistoryDialog = 9,
		MessageDialog = 10,
		InventoryDialog = 11,
		WaveResultDialog = 12,
		RouteShopDialog = 13,
		UpgradeShopDialog = 14,
		ChoiceRouteDialog = 15,
		RouteEventDialog = 16,
		ResearchDialog = 17,
		MapExtendDialog = 18,
		GreaterKnowledgeDialog = 19,
		ShortCutListDialog = 20,
		PauseDialog = 21,
		LargeTipsDialog = 22,
		WaveRewardResultDialog = 23,
		RouteConfirmDialog = 24,
		LevelUpDialog = 25,
		EndCardDialog = 26,
		MasterMemoDialog = 27,
		TutorialSelectDialog = 28,
		TutorialSectionSelectDialog = 29,
		ChangeLogDialog = 30,
		StaffrollDialog = 31,
		RemoveMachineDialog = 32,
		PutMachineDialog = 33,
		ConfirmRequireDialog = 34,
		PlayLogDialog = 35,
		SelectChallengeDialog = 36,
		SelectMasterDialog = 37,
		ChangeProfileDialog = 38,
		SelectMachineDialog = 39,
		AchievementDialog = 40,
		InGameShopDialog = 41,
		EndingDialog = 42,
		AltarOfSpiritSelectDialog = 43,
		DebugBattleDialog = 1000
	}
}
