<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Timberborn.SimpleOutputBuildingsUI</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Timberborn.CoreUI">
      <HintPath>..\..\Assemblies\Timberborn.CoreUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.InventorySystemUI">
      <HintPath>..\..\Assemblies\Timberborn.InventorySystemUI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BaseComponentSystem">
      <HintPath>..\..\Assemblies\Timberborn.BaseComponentSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EntityPanelSystem">
      <HintPath>..\..\Assemblies\Timberborn.EntityPanelSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SimpleOutputBuildings">
      <HintPath>..\..\Assemblies\Timberborn.SimpleOutputBuildings.dll</HintPath>
    </Reference>
    <Reference Include="Bindito.Core">
      <HintPath>..\..\Assemblies\Bindito.Core.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.InventorySystem">
      <HintPath>..\..\Assemblies\Timberborn.InventorySystem.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>