<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>RandomWalkState</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Unity.Entities">
      <HintPath>..\..\Assemblies\Unity.Entities.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Pug.ECS.Components">
      <HintPath>..\..\Assemblies\Pug.ECS.Components.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Physics">
      <HintPath>..\..\Assemblies\Unity.Physics.dll</HintPath>
    </Reference>
    <Reference Include="RandomWalkState.Components">
      <HintPath>..\..\Assemblies\RandomWalkState.Components.dll</HintPath>
    </Reference>
    <Reference Include="Animation.Components">
      <HintPath>..\..\Assemblies\Animation.Components.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Transforms">
      <HintPath>..\..\Assemblies\Unity.Transforms.dll</HintPath>
    </Reference>
    <Reference Include="PugProperties">
      <HintPath>..\..\Assemblies\PugProperties.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>..\..\Assemblies\Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>..\..\Assemblies\Unity.Collections.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Burst">
      <HintPath>..\..\Assemblies\Unity.Burst.dll</HintPath>
    </Reference>
    <Reference Include="Pug.Other">
      <HintPath>..\..\Assemblies\Pug.Other.dll</HintPath>
    </Reference>
    <Reference Include="Unity.NetCode">
      <HintPath>..\..\Assemblies\Unity.NetCode.dll</HintPath>
    </Reference>
    <Reference Include="Pug.Base">
      <HintPath>..\..\Assemblies\Pug.Base.dll</HintPath>
    </Reference>
    <Reference Include="Pug.UnityExtensions">
      <HintPath>..\..\Assemblies\Pug.UnityExtensions.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>