namespace Rewired
{
	[CustomObfuscation(rename = false)]
	internal enum InputPlatform
	{
		eDgdySKclHgXmmILffzdHPvUtEi = 0,
		zjuIGPllhlPcayeppPtHSewObGXj = 1,
		HnmsmUSKysdUvrNYWdqtigLcwDX = 2,
		JeLygDdKjPUUTKlZIRIVKzQWCev = 3,
		IiYVPhkBQDWUFMBZApvaoSmlpUY = 4,
		AbkfUMwvaoaiMbXSNFohhLPkNN = 5,
		sBofcNEzKnXaIaEyuhnelqHavQub = 6,
		BNAbWQOUmbdcYxSUpDXHIqmUlal = 7,
		CmFFcHIXHWioiDacpcofVIqIKnki = 8,
		ZYWfhkfXgXmhbJlTbCJAdwyQeaH = 9,
		TEpWdhwRUlPPNMVISBllNtGtAwO = 10,
		oAAdVztUZvdWxWVPVNKSOWxscse = 11,
		EbajLkpIZkVaaIwzohnttmAUeHL = 12,
		eHhNCClyhXeSmfduxhLRRekLYkE = 13,
		ZiBWcaNXtPGLSnkUxOJdDDUWWor = 14,
		ckuBQjUvyuRajhNeuGaJdHHWMHdh = 15,
		tQmIVvHeoAjpHcrHmqhbtoDzCxvS = 16,
		oeLZvcnfCfVnAFmcanoXJuovCEw = 17,
		OEzyclRgujgSqgLXmiwVeSqTQsAQ = 18,
		ZBWPjlQilGRCnkuNNPOjNuWuAB = 19,
		scaTCaHtkQSzDycyRVnaiRcAFrbe = 20,
		YxuRbqPXGbsbLAmYlsdkeorSxSG = 21,
		oHbUlMhdtaLAdpCdsbKhGJFyFgFC = 22,
		PSNJwwaztDiNMFjGOjvxIFDLyJd = 23,
		IPIEqoqwGyabCFWBzLpseQSeKot = 24,
		SzozMXAyeBkOriEcFEvEHiSppTj = 25,
		UWCdqzyTIJIwgNgaWEfbEXrlPLun = 26,
		VVFNMnuwjQktQBuzllCpFfiGHnU = 27,
		MKsYfylcxroUpkqMsmDQAiXKRGk = 28,
		GVKDbJYxOtlxBEEweJFxfiMGZit = 29,
		ZSmWcBJLZPZDkzrSGqQUcIqQUvG = 30,
		qCrCYaIeXKGNOmBWGyRNKAkvERYH = 31,
		KmXpwJBmIkvUmMjyMwPhIQVKxxP = 32,
		WYunjAzoyopjiumJTeXqFSFzDjv = 33,
		rjPPkipWWuRRnodJLIuVKeUPVmE = 34,
		zInSlzrVBVvwyryGfBwBMWVhNHQ = 35,
		FhqZiqCHhXxQXjCHQDlDqwTlgOd = 36,
		fMohdktunNVwcKFhaCaZcTOyeuLa = 37,
		ejbZpTduacoBQDFXwcokcPpTjtgc = 38,
		DYWhIWXGcQZOVzzgoZhUkCHdMAk = 39,
		VfWORDGmzGhvteBfFSusLWDehlE = 40,
		mvEFVuWpoGVttlHIJFrEMLtxqDF = 41,
		sCyBKEhljbhCCaYpdxJkaTHaPFqk = 42
	}
}
