<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Oculus.Avatar</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>7.3</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Oculus.VR">
      <HintPath>..\..\Assemblies\Oculus.VR.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="Oculus.LipSync">
      <HintPath>..\..\Assemblies\Oculus.LipSync.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\..\Assemblies\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="Oculus.Spatializer">
      <HintPath>..\..\Assemblies\Oculus.Spatializer.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.XRModule">
      <HintPath>..\..\Assemblies\UnityEngine.XRModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>