<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Timberborn.InventorySystemUI</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.CoreUI">
      <HintPath>..\..\Assemblies\Timberborn.CoreUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.GoodsUI">
      <HintPath>..\..\Assemblies\Timberborn.GoodsUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.InventorySystem">
      <HintPath>..\..\Assemblies\Timberborn.InventorySystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Goods">
      <HintPath>..\..\Assemblies\Timberborn.Goods.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EntityPanelSystem">
      <HintPath>..\..\Assemblies\Timberborn.EntityPanelSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BaseComponentSystem">
      <HintPath>..\..\Assemblies\Timberborn.BaseComponentSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EntitySystem">
      <HintPath>..\..\Assemblies\Timberborn.EntitySystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Debugging">
      <HintPath>..\..\Assemblies\Timberborn.Debugging.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BlueprintSystem">
      <HintPath>..\..\Assemblies\Timberborn.BlueprintSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Workshops">
      <HintPath>..\..\Assemblies\Timberborn.Workshops.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.InputSystem">
      <HintPath>..\..\Assemblies\Timberborn.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.GoodConsumingBuildingSystem">
      <HintPath>..\..\Assemblies\Timberborn.GoodConsumingBuildingSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Reproduction">
      <HintPath>..\..\Assemblies\Timberborn.Reproduction.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Common">
      <HintPath>..\..\Assemblies\Timberborn.Common.dll</HintPath>
    </Reference>
    <Reference Include="Bindito.Core">
      <HintPath>..\..\Assemblies\Bindito.Core.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SingletonSystem">
      <HintPath>..\..\Assemblies\Timberborn.SingletonSystem.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections.Immutable">
      <HintPath>..\..\Assemblies\System.Collections.Immutable.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.GameDistricts">
      <HintPath>..\..\Assemblies\Timberborn.GameDistricts.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>