namespace Rewired
{
	[CustomObfuscation(rename = false)]
	internal enum InputPlatform
	{
		SLijuJurzICotICZCDOrjLbrdfLh = 0,
		ZPoCOMXVngbGrIrfUeENoWyzTdo = 1,
		dJonwHeMqbuRwRIElCSzYWNNXQo = 2,
		nVZEkCPtYQZoSwLjlGiBigdnTnS = 3,
		qEKXNuGtYKlqCokNbwAqKacALSz = 4,
		kLnCiuwUmbaYpdinxUkXwNrcQBwd = 5,
		WxaqjOLAMuYBSgiHFQgvSZfZrED = 6,
		fiAEIHuZiiBQFJpMOHqJcgklCDU = 7,
		sNRoIYcNVFEfzQqcYTmtucrfQQL = 8,
		xQAzktRyySJBatBNYcySLRyfFjy = 9,
		hihoAuAFMuqzKuQOhdgxnZYUxHp = 10,
		YYObhYDLAGmZLswVeaeOiaOIKBJE = 11,
		gliwvxPuSpFvhaMiJOQrNEoluJw = 12,
		AedWABNpfSEtpTKkIciVzGowEBt = 13,
		nDPelhflHYbRRXOkWolobSbjRJM = 14,
		CDukMkckixEQsKNiBBJJNjFhRsOa = 15,
		FIqcJwpNcJHDGDJZJtArJAHMWAYL = 16,
		CUTvChJKSkRnTnxyZDMZfHoUpMT = 17,
		kifuLopdwagzdhOTVNtXaEcyNlf = 18,
		nkBCYmLpymvwDDDeutgKRpqvTBc = 19,
		STuWqfxScDPeWMeqeAKkGJgnLIK = 20,
		uYqNJltjMqAEOqvEKATycOdbBWbv = 21,
		KfbfdRTHtnosaVibTnHjbQNTJBe = 22,
		rULKBjYLtKMKJjpQxOAbgJXifVOb = 23,
		ewUoptMZErVKDnBTOIRuYbORLeE = 24,
		gPcUAIiAsYuIyABoyBAGEzYSjqI = 25,
		yrOGewMiKWWGhzmivdGjabrSKmHQ = 26,
		beLuPoKnzDEKNCtjYuWnbSgpYSl = 27,
		gDkEGrJTyytSoYUwLaFCfmsbgkTC = 28,
		wcYvWUsxWuHRWkgoTgStNEKdFSG = 29,
		nvesoYfLpOzHdPGObbeEOemlbKx = 30,
		OKtIUjmLTRHvFEQGtngJgyuENmr = 31,
		acTRtSrIAdlJhqbglFFnBaHtXIuU = 32,
		uXkjaXLgwdBVfQgBofoedbJEXOAg = 33,
		BFBMPtVNMjXdkSjToLdJaaYuLux = 34,
		RgddFgBdHUHnpTAUAyBTcTKWcrd = 35,
		lsmYPjqAxIvVWJHRfdeHIWJAfVS = 36,
		TKuhFnDBlSJGdoLvXdLVBfULOJyG = 37,
		EFjlBCXMgpFYHHtVLhTqcUvBiWPm = 38,
		xqAhbLbRYTbzHaLzNVeleKSUvdbg = 39,
		jQSXVEidvFVCoYHvcJPoxwZBAej = 40,
		CcQTUjwIeHkBmFoAkhGIwMrMXeo = 41,
		UKqkSPPWzyPoHkVfMAeinMLVLaJ = 42,
		BkHeUIznJVOonHdrBgAShNpvnGPD = 43
	}
}
