using System.Collections.Generic;

public class ProfanityFilter
{
	public Dictionary<char, List<string>> ProfanityMap = new Dictionary<char, List<string>>();

	public static ProfanityFilter Instance = new ProfanityFilter(new string[632]
	{
		"ACROTOMOPHILIA", "AEOLUS", "AHOLE", "ANAL", "ANILINGUS", "ANGRYDRAGON", "ANUS", "ARIAN", "ARRSE", "ARSE",
		"ARYAN", "ASS", "AXWOUND", "AXEWOUND", "AZAZEL", "AZZ", "BABELAND", "BALLBAG", "BALLS", "BAMPOT",
		"BANGBROS", "BAREBACK", "BASTINADO", "BAWDY", "BBW", "BDSM", "BEANER", "BEARDEDCLAM", "BEASTIAL", "BEATCH",
		"BEAVER", "BEEYOTCH", "BELLEND", "BENDER", "BEOTCH", "BESTIAL", "BIATCH", "BIMBO", "BIRDLOCK", "BITCH",
		"BLOODCLAAT", "BLOODY", "BLOWJOB", "BLUMPKIN", "BODILY", "BOIOLAS", "BOLLOCKS", "BOLLOK", "BOLLOX", "BONDAGE",
		"BONED", "BONER", "BOOB", "BOOGER", "BOOKIE", "BOONG", "BOOOBS", "BOOOOBS", "BOOOOOBS", "BOOOOOOOBS",
		"BOOTEE", "BOOTIE", "BOOTY", "BOSOM", "BREASTS", "BREEDER", "BUCETA", "BUGGER", "BUKKAKE", "BUMCLAT",
		"BUMMER", "BUNCOMBE", "BUNGHOLE", "BUSTY", "CACA", "CAHONE", "CAMELTOE", "CAMGIRL", "CARPETMUNCHER", "CAWK",
		"CERVIX", "CHESTICLE", "CHINC", "CHINK", "CHOAD", "CHODE", "CLIMAX", "CLIT", "CLUNGE", "CNUT",
		"COCAIN", "COCCYDYNIA", "COCK", "COITAL", "COKMUNCHER", "COMMIE", "CONDOM", "COOCHIE", "COOCHY", "COON",
		"COOTER", "COPROLAGNIA", "COPROPHILIA", "CORNHOLE", "CORPULENT", "CRABS", "CRACK", "CREAMPIE", "CRETIN", "CRIKEY",
		"CRIPPLE", "CROTTE", "CUMBUBBLE", "CUMDUMP", "CUMGUZZLER", "CUMJOCKEY", "CUMMER", "CUMMIN", "CUMSHOT", "CUMSTAIN",
		"CUMTART", "CUNILINGUS", "CUNILLINGUS", "CUNNIE", "CUNNILINGUS", "CUNNY", "CUNT", "CYALIS", "CYBERFUC", "DAMMIT",
		"DAMN", "DARKIE", "DARN", "DEEPTHROAT", "DEGGO", "DENDROPHILIA", "DICK", "DIDDLE", "DIKE", "DILDO",
		"DILIGAF", "DIMWIT", "DINGLE", "DINK", "DIPSHIP", "DIRSA", "DIRTY", "DLCK", "DOGGIESTYLE", "DOGGIN",
		"DOGGYSTYLE", "DOLCETT", "DOMINATION", "DOMINATRIX", "DOMMES", "DONG", "DONKEYPUNCH", "DONKEYRIBBER", "DOOCHBAG", "DOOFUS",
		"DOOKIE", "DOOSH", "DOPEY", "DOUBLELIFT", "DOUCHE", "DRUNK", "DUCHE", "DUMASS", "DUMBASS", "DUMMY",
		"DYKE", "ECCHI", "EJACULATE", "EJACULATING", "EJACULATION", "EJAKULATE", "ERECT", "EROTIC", "EROTISM", "ESCORT",
		"ESSOHBEE", "EUNUCH", "EXTACY", "EXTASY", "FACIAL", "FACK", "FAG", "FAIG", "FANNY", "FANYY",
		"FARTKNOCKER", "FATASS", "FCUK", "FECAL", "FECK", "FEIST", "FELCH", "FELLATE", "FELLATIO", "FELTCH",
		"FEMDOM", "FENIAN", "FIGGING", "FINGERBANG", "FINGERING", "FISTED", "FISTING", "FISTY", "FLAMER", "FLANGE",
		"FLAPS", "FLESHFLUTE", "FLOOZY", "FOAD", "FOAH", "FONDLE", "FOOBAR", "FOOK", "FOOTJOB", "FORESKIN",
		"FREEX", "FRENCHIFY", "FRIGG", "FROTTING", "FUBAR", "FUCK", "FUDGEPACKER", "FUKER", "FUKKER", "FUKKIN",
		"FUKS", "FUKWHIT", "FUKWIT", "FUQ", "FUTANARI", "FUX", "FVCK", "FXCK", "GANGBANG", "GANJA",
		"GASH", "GAY", "GENITALS", "GEY", "GHAY", "GHEY", "GIGOLO", "GINGER", "GIPPO", "GLANS",
		"GOATCX", "GOATSE", "GODDAM", "GOKKUN", "GOLDENSHOWER", "GOLLIWOG", "GONAD", "GOOCH", "GOOK", "GOREGASM",
		"GRINGO", "GROPE", "GSPOT", "GUIDO", "GURO", "HANDJOB", "HARDCORE", "HEEB", "HEMP", "HENTAI",
		"HEROIN", "HERPES", "HERPY", "HESHE", "HIRCISMUS", "HITLER", "HIV", "HOBAG", "HOE", "HOMEY",
		"HOMO", "HONKEY", "HONKY", "HOOCH", "HOOKAH", "HOOKER", "HOOR", "HOOTCH", "HOOTER", "HORNIEST",
		"HORNY", "HUMP", "HUSSY", "HYMEN", "INBRED", "INCEST", "INJUN", "INTERCOURSE", "JACKASS", "JACKHOLE",
		"JACKOFF", "JAGGI", "JAGOFF", "JAILBAIT", "JAPS", "JERK", "JIGABOO", "JIGGABOO", "JIGGERBOO", "JISM",
		"JIZ", "JUGGS", "JUNGLEBUNNY", "JUNKIE", "JUNKY", "KAFIR", "KAWK", "KIKE", "KINBAKU", "KINKSTER",
		"KINKY", "KLAN", "KNOB", "KOCK", "KONDUM", "KOOCH", "KOOTCH", "KRAUT", "KUMMER", "KUMMING",
		"KUMS", "KUNILINGUS", "KUNJA", "KUNT", "KWIF", "KYKE", "LABIA", "LAMEASS", "LARDASS", "LEPER",
		"LESBIAN", "LESBO", "LEZZIE", "LOIN", "LOLITA", "LOONEY", "LOVEMAKING", "LUBE", "LUST", "MASOCHIST",
		"MASTERBATE", "MASTERBATING", "MASTERBATION", "MASTURBATE", "MASTURBATING", "MASTURBATION", "MAXI", "MENSES", "METH", "MICK",
		"MICROPHALLUS", "MIDGET", "MILF", "MINGE", "MOFO", "MOLEST", "MOOLIE", "MUFF", "MUNGING", "MURDER",
		"NAKED", "NAMBLA", "NAPALM", "NAPPY", "NAWASHI", "NAZI", "NEGRO", "NIGABOO", "NIGG", "NIGLET",
		"NIMPHOMANIA", "NIMROD", "NINNY", "NIPPLE", "NOBHEAD", "NOBJOCKY", "NOBJOKEY", "NONCE", "NUDITY", "NUMBNUTS",
		"NUTSACK", "NUTTER", "NYMPHO", "OMORASHI", "OPIATE", "OPIUM", "ORALLY", "ORGASIM", "ORGASM", "ORGIES",
		"ORGY", "OVARY", "PAEDOPHILE", "PAKI", "PANOOCH", "PANSY", "PANTIE", "PANTY", "PAWN", "PECKER",
		"PEDO", "PEEN", "PEEPEE", "PEGGING", "PENETRATE", "PENETRATION", "PENIAL", "PENILE", "PENIS", "PERVERSION",
		"PHALLIC", "PHUCK", "PHUK", "PHUQ", "PIKEY", "PILLOWBITER", "PIMP", "PINKO", "PISS", "PLAYBOY",
		"POLACK", "POLESMOKER", "POLLOCK", "PONYPLAY", "POOF", "POON", "POOP", "PORCHMONKEY", "PORN", "POTTY",
		"PRICK", "PRONEBONE", "PROSTITUTE", "PRUDE", "PSYCHO", "PTHC", "PUBE", "PUBIC", "PUBIS", "PUNANI",
		"PUNANNY", "PUNANY", "PUNKASS", "PUSS", "PUTO", "QUEAF", "QUEEF", "QUEER", "QUICKY", "QUIM",
		"RACY", "RAGHEAD", "RAPE", "RAPING", "RAPIST", "RAUNCH", "RECTAL", "RECTUM", "RECTUS", "REEFER",
		"REICH", "RENOB", "REVUE", "RIMJAW", "RIMJOB", "RIMMING", "RUBBISH", "RUSKI", "SADISM", "SADIST",
		"SAMBO", "SANDBAR", "SANDLER", "SANGER", "SANTORUM", "SCAG", "SCANTILY", "SCAT", "SCHIZO", "SCHLONG",
		"SCISSORING", "SCREW", "SCROAT", "SCROG", "SCROTE", "SCROTUM", "SCRUD", "SCUM", "SEAMAN", "SEDUCE",
		"SEKS", "SEMEN", "SEX", "SHAG", "SHAMEDAME", "SHEMALE", "SHIBARI", "SHIT", "SHIZNIT", "SHOTA",
		"SHRIMPING", "SISSY", "SKAG", "SKANK", "SKEET", "SLAG", "SLANTEYE", "SLAVE", "SLEAZE", "SLEAZY",
		"SLUT", "SMARTASS", "SMEGMA", "SMUT", "SNATCH", "SNOWBALLING", "SNUFF", "SODOM", "SPERM", "SPIC",
		"SPIK", "SPLOOGE", "SPOOGE", "SPOOK", "SPUNK", "STIFFY", "STONED", "STRAPON", "STRAPPADO", "STRIP",
		"STUPID", "SUCK", "SWASTIKAV", "SWINGER", "TAMPON", "TARD", "TAWDRY", "TEABAGGING", "TEAT", "TEETS",
		"TEEZ", "TESTE", "TESTICAL", "TESTICLE", "TESTIS", "THREESOME", "THROATING", "THRUST", "THUG", "TINKLE",
		"TITI", "TITS", "TITTIES", "TITTY", "TOOTS", "TOPLESS", "TOSSER", "TOWELHEAD", "TRAMP", "TRANNY",
		"TRASHY", "TRIBADISM", "TUBGIRL", "TURD", "TUSH", "TWAT", "TWINK", "TWUNT", "UGLY", "UNDIES",
		"UNDRESSING", "UNWED", "UPSKIRT", "URINAL", "URINE", "UROPHILIA", "UTERUS", "VAG", "VAJAYJAY", "VALIUM",
		"VEQTABLE", "VIAGRA", "VIBRATOR", "VIRGIN", "VIXEN", "VJAYJAY", "VODKA", "VOMIT", "VORAREPHILIA", "VOYEUR",
		"VULGAR", "VULVA", "WANG", "WANK", "WAZOO", "WEDGIE", "WEED", "WEENIE", "WEEWEE", "WEINER",
		"WEIRDO", "WENCH", "WETBACK", "WHIZ", "WHOAR", "WHORALICIOUS", "WHORE", "WHORING", "WIGGER", "WILLIES",
		"WILLY", "WISEASS", "WOMB", "XRATED", "XXX", "YAOI", "YEASTY", "YIFFY", "YOBBO", "ZIBBI",
		"ZOOPHILIA", "ZUBB"
	});

	public static HashSet<string> ProfanityStatic = new HashSet<string>
	{
		"AHOLE", "ANAL", "ANUS", "ARIAN", "ARRSE", "ARSE", "ARSES", "ARYAN", "ASSES", "BALLS",
		"BARF", "BAWDY", "BDSM", "BIMBO", "BINT", "BITCH", "BOINK", "BONED", "BONER", "BOOB",
		"BOOBS", "BOOBY", "BOONG", "BOOTY", "BOOZE", "BOOZY", "BOSOM", "BUNG", "BUSTY", "CACA",
		"CAWK", "CHINC", "CHINK", "CHOAD", "CHODE", "CIPA", "CLIT", "CLITS", "CNUT", "COCK",
		"COCKS", "COON", "COONS", "CRABS", "CRACK", "CUMS", "CUNNY", "CUNT", "CUNTS", "DAGO",
		"DAGOS", "DAMN", "DARN", "DEGGO", "DICK", "DICKS", "DIKE", "DILDO", "DINK", "DINKS",
		"DIRSA", "DLCK", "DONG", "DOOSH", "DOPEY", "DUCHE", "DVDA", "DYKE", "DYKES", "ECCHI",
		"ERECT", "FACK", "FAGG", "FAGGS", "FAGOT", "FAGS", "FAIG", "FAIGT", "FANNY", "FANYY",
		"FCUK", "FECAL", "FECK", "FEIST", "FELCH", "FICE", "FISTY", "FLAPS", "FOAD", "FOAH",
		"FOOK", "FREEX", "FUBAR", "FUCK", "FUCKA", "FUCKS", "FUKER", "FUKS", "FVCK", "FXCK",
		"GANJA", "GASH", "GAYDO", "GAYS", "GHAY", "GHEY", "GIPPO", "GLANS", "GONAD", "GOOCH",
		"GOOK", "GOOKS", "GSPOT", "GTFO", "GUIDO", "GURO", "HEBE", "HEEB", "HEMP", "HERP",
		"HERPY", "HESHE", "HOAR", "HOARE", "HOBAG", "HOER", "HOMEY", "HOMO", "HONKY", "HOOCH",
		"HOOR", "HORE", "HORNY", "HUSSY", "HYMEN", "INJUN", "JAGGI", "JAPS", "JISM", "JIZM",
		"JIZZ", "JUGGS", "KAFIR", "KAWK", "KIKE", "KIKES", "KINKY", "KLAN", "KNOB", "KOCK",
		"KOOCH", "KRAUT", "KUMS", "KUNJA", "KUNT", "KWIF", "KYKE", "LABIA", "LECH", "LEPER",
		"LESBO", "LEZZA", "LMAO", "LMFAO", "LUBE", "MAMS", "MASSA", "MAXI", "METH", "MICK",
		"MILF", "MINGE", "MOFO", "MONG", "MUFF", "MUTHA", "NAKED", "NAPPY", "NAZI", "NIGA",
		"NIGAR", "NIGER", "NEGRO", "NIGGA", "NINNY", "NONCE", "OPIUM", "ORGY", "OVARY", "OVUM",
		"OVUMS", "PAKI", "PANSY", "PEDO", "PENIS", "PHUCK", "PHUK", "PHUKS", "PHUQ", "PIKEY",
		"PINKO", "PISS", "POOF", "POON", "POOP", "PORN", "PORNO", "PRICK", "PRIG", "PROD",
		"PRON", "PTHC", "PUBIC", "PUBIS", "PUNKY", "PUNTA", "PUSS", "PUSSE", "PUSSI", "PUSSY",
		"PUST", "PUTO", "QUEAF", "QUEEF", "QUEER", "QUIM", "RACY", "RAPE", "RAPED", "RAPER",
		"RAPEY", "REICH", "RENOB", "REVUE", "RTARD", "RUMP", "RUSKI", "SAMBO", "SCAG", "SCAT",
		"SCROG", "SCROT", "SCRUD", "SCUM", "SEKS", "SEMEN", "SEXO", "SEXY", "SHAG", "SHIT",
		"SHITE", "SHITS", "SHITT", "SHIZ", "SHOTA", "SISSY", "SKAG", "SKANK", "SKEET", "SLAG",
		"SLAVE", "SLUT", "SLUTS", "SMEG", "SMUT", "SNUFF", "SODOM", "SPAC", "SPERM", "SPIC",
		"SPICK", "SPIK", "SPIKS", "SPOOK", "SPUNK", "STFU", "TAFF", "TAIG", "TARD", "TART",
		"TEAT", "TEETS", "TEEZ", "TESTE", "THUG", "TITI", "TITS", "TITT", "TITTY", "TOKE",
		"TOOTS", "TRAMP", "TROON", "TUSH", "TUSHY", "TWAT", "TWATS", "TWINK", "TWUNT", "URINE",
		"VIXEN", "VULVA", "WANG", "WANK", "WANKY", "WAZOO", "WEED", "WENCH", "WHIZ", "WHOAR",
		"WHORE", "WILLY", "WOMB", "YAOI", "YIFFY", "YOBBO", "ZIBBI", "ZUBB"
	};

	public ProfanityFilter(string[] profanity)
	{
		for (int i = 0; i < profanity.Length; i++)
		{
			char key = profanity[i][0];
			List<string> value;
			if (!ProfanityMap.TryGetValue(key, out value))
			{
				value = new List<string>();
				ProfanityMap[key] = value;
			}
			value.Add(profanity[i]);
		}
	}

	public bool ContainsProfanity(string word)
	{
		for (int i = 0; i < word.Length - 3; i++)
		{
			List<string> value;
			if (!ProfanityMap.TryGetValue(word[i], out value))
			{
				continue;
			}
			for (int j = 0; j < value.Count; j++)
			{
				if (CheckSub(word, i, value[j]))
				{
					return true;
				}
			}
		}
		return false;
	}

	private bool CheckSub(string word, int offset, string against)
	{
		if (offset + against.Length > word.Length)
		{
			return false;
		}
		for (int i = 0; i < against.Length; i++)
		{
			if (word[offset + i] != against[i])
			{
				return false;
			}
		}
		return true;
	}
}
