using System;
using System.Collections;
using UnityEngine;

namespace UMA
{
	[Serializable]
	public class OverlayDataAsset : ScriptableObject, ISerializationCallbackReceiver, IUMAIndexOptions
	{
		public enum OverlayType
		{
			Normal = 0,
			Cutout = 1
		}

		public enum OverlayBlend
		{
			Normal = 0,
			Multiply = 21,
			Overlay = 23,
			Screen = 22,
			Darken = 24,
			Lighten = 25,
			ColorDodge = 26,
			ColorBurn = 27,
			SoftLight = 29,
			HardLight = 28,
			Subtract = 1
		}

		[Serializable]
		public class OcclusionEntry
		{
			[Serializable]
			public struct SubMeshOcclusion
			{
				public int[] occlusion;
			}

			public class OcclusionEntryComparer : IComparer
			{
				private static OcclusionEntryComparer _instance;

				public static OcclusionEntryComparer Instance => null;

				private OcclusionEntryComparer()
				{
				}

				public int Compare(object x, object y)
				{
					return 0;
				}
			}

			public int slotNameHash;

			public SubMeshOcclusion[] occlusion;
		}

		[Tooltip("The name of this overlay.")]
		public string overlayName;

		[NonSerialized]
		public int nameHash;

		[Tooltip("Normal or Cutout overlay type. This determines whether or not to use a cutout shader during the texture merging process.")]
		public OverlayType overlayType;

		[Tooltip("Destination rectangle for drawing overlay textures.")]
		public Rect rect;

		[Tooltip("Optional Alpha mask, if alpha mask is not set the texture[0].alpha is used instead.")]
		public Texture alphaMask;

		[Tooltip("Array of textures required for the overlay material.")]
		public Texture[] textureList;

		[Tooltip("Overlay Blend Mode. Not used on the base overlay. Similar to standard blend modes on paint apps. Use the alpha channel ")]
		public OverlayBlend[] overlayBlend;

		[Tooltip("Use this to identify what kind of overlay this is and what it fits.")]
		public string[] tags;

		[Tooltip("The UMA material contains both a reference to the Unity material used for drawing and information needed for matching the textures and colors to the various material properties.")]
		[UMAAssetFieldVisible]
		public UMAMaterial material;

		public string materialName;

		[SerializeField]
		[HideInInspector]
		public bool autoGeneratedLOD;

		public bool forceKeep;

		[Tooltip("If true, this overlay will not be added to the index when adding all")]
		public bool noAutoAdd;

		private bool labelLocalFiles;

		[Tooltip("Occlusion Entries for occluding triangles, currently only supported by powertools.")]
		public OcclusionEntry[] OcclusionEntries;

		public int textureCount => 0;

		public bool ForceKeep
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		public bool NoAutoAdd
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		public bool LabelLocalFiles
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		public OverlayBlend GetBlend(int channel)
		{
			return default(OverlayBlend);
		}

		public void ValidateBlendList()
		{
		}

		public void OnAfterDeserialize()
		{
		}

		public void OnBeforeSerialize()
		{
		}

		public Texture GetAlphaMask()
		{
			return null;
		}

		public void SortOcclusion()
		{
		}
	}
}
