using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Serialization;

namespace UMA
{
	[Serializable]
	[PreferBinarySerialization]
	public class SlotDataAsset : ScriptableObject, ISerializationCallbackReceiver, INameProvider, IUMAIndexOptions
	{
		public enum BlendshapeCopyMode
		{
			UpdateAndAdd = 0,
			ClearAndReplace = 1,
			AddNewOnly = 2
		}

		public enum NormalCopyMode
		{
			CopyNormals = 0,
			AverageNormals = 1
		}

		public string slotName;

		[NonSerialized]
		public int nameHash;

		public bool forceKeep;

		[Tooltip("If true, this Slot will not be added to the index when adding all")]
		public bool noAutoAdd;

		[SerializeField]
		private UMARendererAsset _rendererAsset;

		[UMAAssetFieldVisible]
		[SerializeField]
		public UMAMaterial material;

		public string materialName;

		[Tooltip("If you are using an LOD system, this is the maximum LOD that this slot will be displayed. After that, it will be discarded during mesh generation. a value of -1 will never be dropped.")]
		public int maxLOD;

		public bool useAtlasOverlay;

		public float overlayScale;

		public string[] animatedBoneNames;

		[HideInInspector]
		public int[] animatedBoneHashes;

		[Tooltip("This object is a clipping plane, and is not added to the model.")]
		public bool isClippingPlane;

		[Tooltip("You can adjust the corners of the clipping plane here. Do not make the plane non-planar!")]
		public Vector3[] clippingPlaneOffset;

		[Tooltip("This object is a smooshable. Any overriden vertexes will be cleared before smooshing.")]
		public bool isSmooshable;

		[Tooltip("This is used to offset the slot for some reason")]
		public Vector3 smooshOffset;

		[Tooltip("This is used to grow around the center. Negative values subtract. Positive values add.")]
		public Vector3 smooshExpand;

		[Tooltip("This object can process events ")]
		public GameObject SlotObject;

		private bool SlotObjectHookedUp;

		[FormerlySerializedAs("slotDNA")]
		[SerializeField]
		private DnaConverterBehaviour _slotDNALegacy;

		[SerializeField]
		[Tooltip("Optional DNA converter specific to the slot. Accepts a DNAConverterController asset or a legacy DNAConverterBehaviour prefab.")]
		private DNAConverterField _slotDNA;

		[Tooltip("If isWildCardSlot = true, then the overlays on this slot are applied to any slot or overlay with a matching tag when the recipe is built. This is used in Wardrobe Recipes to apply overlays to other slots.")]
		public bool isWildCardSlot;

		private bool labelLocalFiles;

		public UMAMeshData meshData;

		public int subMeshIndex;

		public int sourceSubmeshIndex;

		public string slotGroup;

		public string[] tags;

		public string[] Races;

		[NonSerialized]
		public Vector3[] TransformedLocalVertexes;

		public UMADataEvent CharacterBegun;

		public UMADataSlotMaterialRectEvent SlotAtlassed;

		public UMADataEvent DNAApplied;

		public UMADataEvent CharacterCompleted;

		public UMADataSlotProcessedEvent SlotProcessed;

		public UMADataSlotProcessedEvent SlotBeginProcessing;

		[SerializeField]
		[HideInInspector]
		public bool autoGeneratedLOD;

		private List<IUMAEventHookup> EventHookups;

		public bool ForceKeep
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		public bool NoAutoAdd
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		public UMARendererAsset RendererAsset => null;

		public IDNAConverter slotDNA
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		public bool isUtilitySlot => false;

		public bool LabelLocalFiles
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		public string GetAssetName()
		{
			return null;
		}

		public int GetNameHash()
		{
			return 0;
		}

		public void LoadFromIndex()
		{
		}

		public void Awake()
		{
		}

		public void Begin(UMAData umaData)
		{
		}

		public void Completed(UMAData umaData)
		{
		}

		private void HookupObjectEvents()
		{
		}

		public void OnDestroy()
		{
		}

		public void OnDisable()
		{
		}

		public int GetTextureChannelCount(UMAGeneratorBase generator)
		{
			return 0;
		}

		public override string ToString()
		{
			return null;
		}

		public void UpdateMeshData(SkinnedMeshRenderer meshRenderer, string rootBoneName, bool udimAdjustment, int submeshIndex)
		{
		}

		public void OnEnable()
		{
		}

		public void EnsureBoneWeights()
		{
		}

		public void UpdateMeshData()
		{
		}

		public void OnAfterDeserialize()
		{
		}

		public void OnBeforeSerialize()
		{
		}

		public void Assign(SlotDataAsset source)
		{
		}
	}
}
