<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Timberborn.RuinsUI</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Timberborn.CoreUI">
      <HintPath>..\..\Assemblies\Timberborn.CoreUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Goods">
      <HintPath>..\..\Assemblies\Timberborn.Goods.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BaseComponentSystem">
      <HintPath>..\..\Assemblies\Timberborn.BaseComponentSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TemplateInstantiation">
      <HintPath>..\..\Assemblies\Timberborn.TemplateInstantiation.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EntityPanelSystem">
      <HintPath>..\..\Assemblies\Timberborn.EntityPanelSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Ruins">
      <HintPath>..\..\Assemblies\Timberborn.Ruins.dll</HintPath>
    </Reference>
    <Reference Include="Bindito.Core">
      <HintPath>..\..\Assemblies\Bindito.Core.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Yielding">
      <HintPath>..\..\Assemblies\Timberborn.Yielding.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.LocalizationSerialization">
      <HintPath>..\..\Assemblies\Timberborn.LocalizationSerialization.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SpriteOperations">
      <HintPath>..\..\Assemblies\Timberborn.SpriteOperations.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.YielderFinding">
      <HintPath>..\..\Assemblies\Timberborn.YielderFinding.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SimpleOutputBuildingsUI">
      <HintPath>..\..\Assemblies\Timberborn.SimpleOutputBuildingsUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Rendering">
      <HintPath>..\..\Assemblies\Timberborn.Rendering.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>