<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Timberborn.MapThumbnailCapturingUI</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Timberborn.SingletonSystem">
      <HintPath>..\..\Assemblies\Timberborn.SingletonSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.ThumbnailCapturing">
      <HintPath>..\..\Assemblies\Timberborn.ThumbnailCapturing.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.CoreUI">
      <HintPath>..\..\Assemblies\Timberborn.CoreUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.FileBrowsing">
      <HintPath>..\..\Assemblies\Timberborn.FileBrowsing.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.ToolSystem">
      <HintPath>..\..\Assemblies\Timberborn.ToolSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.MapThumbnailOverlaySystem">
      <HintPath>..\..\Assemblies\Timberborn.MapThumbnailOverlaySystem.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.MapThumbnail">
      <HintPath>..\..\Assemblies\Timberborn.MapThumbnail.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Localization">
      <HintPath>..\..\Assemblies\Timberborn.Localization.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.MapThumbnailCapturing">
      <HintPath>..\..\Assemblies\Timberborn.MapThumbnailCapturing.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.ToolSystemUI">
      <HintPath>..\..\Assemblies\Timberborn.ToolSystemUI.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.ToolPanelSystem">
      <HintPath>..\..\Assemblies\Timberborn.ToolPanelSystem.dll</HintPath>
    </Reference>
    <Reference Include="Bindito.Core">
      <HintPath>..\..\Assemblies\Bindito.Core.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>