<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SokLoc</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Google.Apis.Auth">
      <HintPath>..\..\Assemblies\Google.Apis.Auth.dll</HintPath>
    </Reference>
    <Reference Include="Google.Apis.Sheets.v4">
      <HintPath>..\..\Assemblies\Google.Apis.Sheets.v4.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>..\..\Assemblies\Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="Google.Apis">
      <HintPath>..\..\Assemblies\Google.Apis.dll</HintPath>
    </Reference>
    <Reference Include="Google.Apis.Core">
      <HintPath>..\..\Assemblies\Google.Apis.Core.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>..\..\Assemblies\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\Assemblies\Unity.TextMeshPro.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>