using System;
using UnityEngine;

namespace Rewired
{
	[Serializable]
	public sealed class InputAction : wIxbseuklfiqWWWBQZHScHgHHXwA, cfLjOhjLYeBVSqIGSwIBARCebRsBb
	{
		private const string keyCategory = "action";

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private int _id;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _name;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private InputActionType _type;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _descriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _positiveDescriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _negativeDescriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _key;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _positiveKey;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _negativeKey;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private int _behaviorId;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private bool _userAssignable;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private int _categoryId;

		[NonSerialized]
		private ezyPxEPfUBPhLnSJpkTEMlypYbLj MYyCgQPDeqHZryOEzbZdgcxbdnGyA;

		[NonSerialized]
		private int NPLqiOLHRcrflGynFfGQZHwwDcLj;

		public int id
		{
			get
			{
				return 0;
			}
			internal set
			{
			}
		}

		public string name
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public InputActionType type
		{
			get
			{
				return default(InputActionType);
			}
			internal set
			{
			}
		}

		public string descriptiveName
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public string positiveDescriptiveName
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public string negativeDescriptiveName
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public int behaviorId
		{
			get
			{
				return 0;
			}
			internal set
			{
			}
		}

		public int categoryId
		{
			get
			{
				return 0;
			}
			internal set
			{
			}
		}

		public bool userAssignable
		{
			get
			{
				return false;
			}
			internal set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string positiveKey
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string negativeKey
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedPositiveDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedNegativeDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string cfLjOhjLYeBVSqIGSwIBARCebRsBb.keyCategory => null;

		string cfLjOhjLYeBVSqIGSwIBARCebRsBb.scriptingName => null;

		string cfLjOhjLYeBVSqIGSwIBARCebRsBb.nonLocalizedDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string wIxbseuklfiqWWWBQZHScHgHHXwA.nonLocalizedPositiveDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string wIxbseuklfiqWWWBQZHScHgHHXwA.nonLocalizedNegativeDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string cfLjOhjLYeBVSqIGSwIBARCebRsBb.key => null;

		string wIxbseuklfiqWWWBQZHScHgHHXwA.positiveKey
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string wIxbseuklfiqWWWBQZHScHgHHXwA.negativeKey
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		int cfLjOhjLYeBVSqIGSwIBARCebRsBb.autoGeneratedValueFlags
		{
			get
			{
				return 0;
			}
			set
			{
			}
		}

		public InputAction()
		{
		}

		public InputAction(InputAction P_0)
		{
		}

		public InputAction Clone()
		{
			return null;
		}

		public string GetDisplayName(AxisRange axisRange)
		{
			return null;
		}

		internal void XmZcABBqkKPwNDRkErmQfFSmLEQDb()
		{
		}

		internal void oarKegEjdyroQMkSTBogZTzvUkZO()
		{
		}

		private static EsuVeemXUvWofQMkRaJhZlyFnkvC.biWlvcDDuuegaGBVXYTfOjCYMXCeb nLBCfwTzUvjmZKbpeHPGqmyTmMHV(InputActionType P_0)
		{
			return default(EsuVeemXUvWofQMkRaJhZlyFnkvC.biWlvcDDuuegaGBVXYTfOjCYMXCeb);
		}
	}
}
