using System;
using UnityEngine;

namespace Rewired
{
	[Serializable]
	public sealed class InputLayout : cfLjOhjLYeBVSqIGSwIBARCebRsBb
	{
		private const string keyCategory = "controller_map/layout";

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _name;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _descriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _key;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private int _id;

		[NonSerialized]
		private hBdBPTFfODwAjjJlnJTKaJqqNCMYA gYUnHHySocmacoevzZimALQGfNxhA;

		[NonSerialized]
		private int DHqUWAgHcrPTsbneSGinqnqNVvFA;

		public string name
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public string descriptiveName
		{
			get
			{
				return null;
			}
			internal set
			{
			}
		}

		public int id
		{
			get
			{
				return 0;
			}
			internal set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string cfLjOhjLYeBVSqIGSwIBARCebRsBb.keyCategory => null;

		string cfLjOhjLYeBVSqIGSwIBARCebRsBb.scriptingName => null;

		string cfLjOhjLYeBVSqIGSwIBARCebRsBb.nonLocalizedDescriptiveName
		{
			get
			{
				return null;
			}
			set
			{
			}
		}

		string cfLjOhjLYeBVSqIGSwIBARCebRsBb.key => null;

		int cfLjOhjLYeBVSqIGSwIBARCebRsBb.autoGeneratedValueFlags
		{
			get
			{
				return 0;
			}
			set
			{
			}
		}

		public InputLayout()
		{
		}

		public InputLayout(InputLayout P_0)
		{
		}

		public InputLayout Clone()
		{
			return null;
		}

		internal void buSbVCpKUxfdFuORkJDtqCufBjAN()
		{
		}

		internal void khVChNgewZDmaCJNQbPdEMFtWjMjA()
		{
		}
	}
}
