namespace Rewired
{
	[CustomObfuscation(rename = false)]
	internal enum InputPlatform
	{
		Unknown = 0,
		WindowsDirectInput = 1,
		WindowsRawInput = 2,
		WindowsXInput = 3,
		WindowsFallback = 4,
		WindowsUWP = 5,
		WindowsUWPFallback = 6,
		WindowsWGI = 7,
		OSXNative = 8,
		OSXFallback = 9,
		LinuxNative = 10,
		LinuxFallback = 11,
		LinuxFallback_PreConfigured = 12,
		AndroidFallback = 13,
		AmazonFireTVFallback = 14,
		RazerForgeTVFallback = 15,
		iOSFallback = 16,
		WindowsPhone8Fallback = 17,
		BlackberryFallback = 18,
		PS3Fallback = 19,
		PS4Fallback = 20,
		PSMFallback = 21,
		PSVitaFallback = 22,
		XBox360Fallback = 23,
		XBoxOneFallback = 24,
		WiiFallback = 25,
		WiiUFallback = 26,
		Fallback = 27,
		Ouya = 28,
		XboxOne = 29,
		GameCore = 30,
		PS4 = 31,
		PS5 = 32,
		NintendoSwitch = 33,
		NintendoSwitchFallback = 34,
		Custom = 35,
		InternalDriver = 36,
		SDL2 = 37,
		SDL2Windows = 38,
		SDL2OSX = 39,
		SDL2Linux = 40,
		Steam = 41,
		WebGL = 42,
		AppleGameController = 43
	}
}
