internal sealed class IxPNXkOFogymWdamCyLczBGdcOPr
{
	public static readonly EjRzaRKGYKofIRZTFuJKtdAsBqBO NmATcQAgftiaVADgBMMkvhsJPCfjA = CptXvdNahKtjTczDcEsqiEgXFTEeA.sVlSIYSuNHpAeNPhoEwPuMRNSCYD(SqjZUSRuEtOXusSPIGUWlDSpFNdQ.DeviceNotConnected);
}
