<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>io.sentry.unity.runtime</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Sentry.Unity">
      <HintPath>..\..\Assemblies\Sentry.Unity.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Sentry">
      <HintPath>..\..\Assemblies\Sentry.dll</HintPath>
    </Reference>
    <Reference Include="Sentry.Unity.Native">
      <HintPath>..\..\Assemblies\Sentry.Unity.Native.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>