namespace Rewired
{
	[CustomObfuscation(rename = false)]
	internal enum InputPlatform
	{
		XYhwUwaOlrfFTKoMRqftWpJVYyOD = 0,
		GqzyAlVbsTJEJeHcVvIVueUVgOh = 1,
		cZjaGiccoOfQMydNsMdhkKrlxCba = 2,
		ovCPWlBsEvuzkIMqmgTZqxNDFgV = 3,
		lcPnzROWQvkxuEjIsRvoYRWoVXg = 4,
		lVqnUVyYsKsHZMKeqoJPZENWgClF = 5,
		JAzQtbHLOTHOvWCjKBtuYzhnFoW = 6,
		qzTTwsqmkFsXzptVNiHLyLYTdWR = 7,
		zqQYkhsnXyLqDuhSVwAvqSUVNyY = 8,
		enTXCIFwxjKGOTdUNPCUNyQZEQr = 9,
		eUabiPKSSDjieZEJgxLjddewVcsF = 10,
		PlRoHlHsMxRUbOLKpRxEuAkedAG = 11,
		hvteJOJvIYNkPQjlYMlvRYELJCj = 12,
		BcegoeXnuzLZifdCXJVBpApAEkl = 13,
		keUAQKhzfbmmrvWZLLVpjBiRDILF = 14,
		VdrZcVyweUFNIzNbSheVCltJDtNo = 15,
		GwzdkTbFocQuylCSAbRrAldwZoB = 16,
		PLWBZITRYDmOzPwdONuXhmYqiiY = 17,
		pvkAQXroaTtXJRXQEyCZuMOIYDy = 18,
		sUEnaBPRoRGbjFzftPXWNFCTHYrT = 19,
		BipyCxjgAgSAqipXvprsKMIDFLB = 20,
		hqtGxMrtQLDZyGfXPXekSiBPTBa = 21,
		JRyVneHjlMIxElqiQLQdnWbbsMb = 22,
		ohIXpWWVnrVVdZSDmnrfcFpOiWJc = 23,
		lGRAMGWQvEWJrLMuXvesWaypSQD = 24,
		lQxcglqwyjmvSaspdllCCCoyxtP = 25,
		lQJYCJKxUxlRFVSnejxjlgJeAjCe = 26,
		gGGEnVSWvgaFbdVaVnlfMbOTkJsO = 27,
		pZrRySJpwHiBEaxxGokWuXWJhUS = 28,
		ehbCQljLDvgiNbFTeUQYWfWVaDsb = 29,
		nbOhDhcnKQfYJsEjsPifPczVJFzj = 30,
		dyrBgdFyTIOJPuQBhTiunpcmXkX = 31,
		OSoXKRRBZfHUVjWFHAZRkYacHta = 32,
		sstGbYqotnUAodZSsTwHEEbgiSR = 33,
		IxbHVCPxPdNPRUkNUofPdkkhUmv = 34,
		DgoezzHncQDPzHHSCxmmfWPYyHIt = 35,
		cbXqDazhCoFsbbpgQKVvBGuIuqco = 36,
		keTnnOorxoGUZamFnuifvhvdNeE = 37,
		ZANtQEkaOaQcYhPlpfZCiDwahfr = 38,
		TxrUiyPjtJdznKpsXcVgtexpIzI = 39
	}
}
