<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CTS.BBT</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="PixelCrushers">
      <HintPath>..\..\Assemblies\PixelCrushers.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\Assemblies\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="CTS.Core">
      <HintPath>..\..\Assemblies\CTS.Core.dll</HintPath>
    </Reference>
    <Reference Include="Unity.AI.Navigation">
      <HintPath>..\..\Assemblies\Unity.AI.Navigation.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>..\..\Assemblies\Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="CTS.UI">
      <HintPath>..\..\Assemblies\CTS.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>..\..\Assemblies\UnityEngine.AIModule.dll</HintPath>
    </Reference>
    <Reference Include="CTS.ScriptableSettings">
      <HintPath>..\..\Assemblies\CTS.ScriptableSettings.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Localization">
      <HintPath>..\..\Assemblies\Unity.Localization.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\Assemblies\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\..\Assemblies\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\..\Assemblies\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Runtime">
      <HintPath>..\..\Assemblies\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="CTS.Utilities">
      <HintPath>..\..\Assemblies\CTS.Utilities.dll</HintPath>
    </Reference>
    <Reference Include="CTS.StockInventory">
      <HintPath>..\..\Assemblies\CTS.StockInventory.dll</HintPath>
    </Reference>
    <Reference Include="CTS.TechTree">
      <HintPath>..\..\Assemblies\CTS.TechTree.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\Assemblies\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="EasySave3">
      <HintPath>..\..\Assemblies\EasySave3.dll</HintPath>
    </Reference>
    <Reference Include="Eflatun.SceneReference">
      <HintPath>..\..\Assemblies\Eflatun.SceneReference.dll</HintPath>
    </Reference>
    <Reference Include="CTS.DevConsole">
      <HintPath>..\..\Assemblies\CTS.DevConsole.dll</HintPath>
    </Reference>
    <Reference Include="DOTween">
      <HintPath>..\..\Assemblies\DOTween.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>..\..\Assemblies\UnityEngine.VideoModule.dll</HintPath>
    </Reference>
    <Reference Include="Animancer">
      <HintPath>..\..\Assemblies\Animancer.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\..\Assemblies\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="CTS.Emotes.Runtime">
      <HintPath>..\..\Assemblies\CTS.Emotes.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="RootMotion">
      <HintPath>..\..\Assemblies\RootMotion.dll</HintPath>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>..\..\Assemblies\com.rlabrecque.steamworks.net.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\..\Assemblies\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>..\..\Assemblies\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="XCharts.Runtime">
      <HintPath>..\..\Assemblies\XCharts.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ResourceManager">
      <HintPath>..\..\Assemblies\Unity.ResourceManager.dll</HintPath>
    </Reference>
    <Reference Include="CareBoo.Serially">
      <HintPath>..\..\Assemblies\CareBoo.Serially.dll</HintPath>
    </Reference>
    <Reference Include="Cinemachine">
      <HintPath>..\..\Assemblies\Cinemachine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>..\..\Assemblies\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="NaughtyAttributes.Core">
      <HintPath>..\..\Assemblies\NaughtyAttributes.Core.dll</HintPath>
    </Reference>
    <Reference Include="AssetIcons">
      <HintPath>..\..\Assemblies\AssetIcons.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\..\Assemblies\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\Assemblies\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>..\..\Assemblies\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Addressables">
      <HintPath>..\..\Assemblies\Unity.Addressables.dll</HintPath>
    </Reference>
    <Reference Include="AGameAnalytics">
      <HintPath>..\..\Assemblies\AGameAnalytics.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\Assemblies\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="CTS.Report">
      <HintPath>..\..\Assemblies\CTS.Report.dll</HintPath>
    </Reference>
    <Reference Include="DOTween.Modules">
      <HintPath>..\..\Assemblies\DOTween.Modules.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>