<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>com.alekrus.universal-platform.steam</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="com.alekrus.universal-platform">
      <HintPath>..\..\Assemblies\com.alekrus.universal-platform.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>