public class VariableDataPrizes
{
	public void Init()
	{
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerWhistleCrude, "PrizeCost", 10);
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerWhistleGood, "PrizeCost", 10);
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerWhistleSuper, "PrizeCost", 10);
		VariableManager.Instance.SetVariable(ObjectType.Castanets, "PrizeCost", 10);
		VariableManager.Instance.SetVariable(ObjectType.Guiro, "PrizeCost", 10);
		VariableManager.Instance.SetVariable(ObjectType.Maracas, "PrizeCost", 10);
		VariableManager.Instance.SetVariable(ObjectType.Guitar, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.Triangle, "PrizeCost", 30);
		VariableManager.Instance.SetVariable(ObjectType.Cowbell, "PrizeCost", 30);
		VariableManager.Instance.SetVariable(ObjectType.JawHarp, "PrizeCost", 30);
		VariableManager.Instance.SetVariable(ObjectType.AnimalPetDog, "PrizeCost", 300);
		VariableManager.Instance.SetVariable(ObjectType.AnimalPetDog2, "PrizeCost", 300);
		VariableManager.Instance.SetVariable(ObjectType.HatFrog, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.HatPanda, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.HatPenguin, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.HatBearskin, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.HatCaptain, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.HatCowboy, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.HatBoater, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.HatCatintheHat, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.HatDrumMajor, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.HatGat, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.HatFedora, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.HatSombrero, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.HatSmurf, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.HatTrafficCone, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.HatWig02, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.TopFrog, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.TopPanda, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.TopPenguin, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.TopRoyalGuard, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.TopSuit02, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.TrojanRabbit, "PrizeCost", 50);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveROB, "PrizeCost", 10);
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadROB, "PrizeCost", 10);
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameROB, "PrizeCost", 10);
		VariableManager.Instance.SetVariable(ObjectType.FlooringChequer, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.BrickArchway, "PrizeCost", 10);
		VariableManager.Instance.SetVariable(ObjectType.BrickArchwayDoor, "PrizeCost", 10);
		VariableManager.Instance.SetVariable(ObjectType.HedgeArchway, "PrizeCost", 10);
		VariableManager.Instance.SetVariable(ObjectType.Sandcastle, "PrizeCost", 10);
		VariableManager.Instance.SetVariable(ObjectType.CastleWall, "PrizeCost", 10);
		VariableManager.Instance.SetVariable(ObjectType.CastlePlainTower, "PrizeCost", 10);
		VariableManager.Instance.SetVariable(ObjectType.CastleFancyTower, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.CastleGate, "PrizeCost", 20);
		VariableManager.Instance.SetVariable(ObjectType.CastleDrawbridge, "PrizeCost", 30);
		VariableManager.Instance.SetVariable(ObjectType.StreetLamp, "PrizeCost", 30);
		VariableManager.Instance.SetVariable(ObjectType.AquariumGood, "PrizeCost", 50);
		VariableManager.Instance.SetVariable(ObjectType.Nothing, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.Empty, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.Plot, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.FarmerPlayer, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.BasicWorker, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.Worker, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.TutorBot, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.Weed, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.Grass, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropWheat, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropCotton, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropCarrot, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.TreeCoconut, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.TreePine, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.TreeApple, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.TreeMulberry, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.TreeStump, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropPumpkin, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.Bush, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.Hedge, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.Mushroom, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.FlowerWild, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.Bullrushes, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.AnimalBird, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.AnimalBee, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.AnimalSilkmoth, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.Boulder, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.TallBoulder, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.BeesNest, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart2, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart3, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart4, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart5, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart6, "DisableMission", 1);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart7, "DisableMission", 1);
		VariableManager.Instance.SetVariable("MissionAmountTier0", 50);
		VariableManager.Instance.SetVariable("MissionAmountTier1", 45);
		VariableManager.Instance.SetVariable("MissionAmountTier2", 40);
		VariableManager.Instance.SetVariable("MissionAmountTier3", 35);
		VariableManager.Instance.SetVariable("MissionAmountTier4", 30);
		VariableManager.Instance.SetVariable("MissionAmountTier5", 25);
		VariableManager.Instance.SetVariable("MissionAmountTier6", 20);
		VariableManager.Instance.SetVariable("MissionAmountTier7", 10);
		VariableManager.Instance.SetVariable(ObjectType.Canoe, "MissionAmount", 20);
		VariableManager.Instance.SetVariable(ObjectType.Cart, "MissionAmount", 20);
		VariableManager.Instance.SetVariable(ObjectType.WheelBarrow, "MissionAmount", 20);
		VariableManager.Instance.SetVariable(ObjectType.Carriage, "MissionAmount", 10);
		VariableManager.Instance.SetVariable(ObjectType.CarriageLiquid, "MissionAmount", 10);
		VariableManager.Instance.SetVariable(ObjectType.CarriageTrain, "MissionAmount", 10);
		VariableManager.Instance.SetVariable(ObjectType.CartLiquid, "MissionAmount", 10);
		VariableManager.Instance.SetVariable(ObjectType.Minecart, "MissionAmount", 10);
		VariableManager.Instance.SetVariable(ObjectType.Train, "MissionAmount", 10);
		VariableManager.Instance.SetVariable(ObjectType.CraneCrude, "MissionAmount", 10);
		VariableManager.Instance.SetVariable(ObjectType.FishCarp, "MissionAmount", 3);
		VariableManager.Instance.SetVariable(ObjectType.FishOrangeRoughy, "MissionAmount", 3);
		VariableManager.Instance.SetVariable(ObjectType.FishMonkfish, "MissionAmount", 3);
		VariableManager.Instance.SetVariable(ObjectType.FishPerch, "MissionAmount", 3);
		VariableManager.Instance.SetVariable(ObjectType.FishCatFish, "MissionAmount", 1);
		VariableManager.Instance.SetVariable(ObjectType.FishGar, "MissionAmount", 1);
		VariableManager.Instance.SetVariable(ObjectType.FishMarlin, "MissionAmount", 1);
		VariableManager.Instance.SetVariable(ObjectType.FishMahiMahi, "MissionAmount", 1);
		VariableManager.Instance.SetVariable(ObjectType.TopFrog, "Weight", 1);
		VariableManager.Instance.SetVariable(ObjectType.TopFrog, "Tier", 2);
		VariableManager.Instance.SetVariable(ObjectType.TopFrog, "MaxUsage", 1000);
		VariableManager.Instance.SetVariable(ObjectType.TopPanda, "Weight", 1);
		VariableManager.Instance.SetVariable(ObjectType.TopPanda, "Tier", 2);
		VariableManager.Instance.SetVariable(ObjectType.TopPanda, "MaxUsage", 1000);
		VariableManager.Instance.SetVariable(ObjectType.TopPenguin, "Weight", 1);
		VariableManager.Instance.SetVariable(ObjectType.TopPenguin, "Tier", 2);
		VariableManager.Instance.SetVariable(ObjectType.TopPenguin, "MaxUsage", 1000);
		VariableManager.Instance.SetVariable(ObjectType.TopRoyalGuard, "Weight", 1);
		VariableManager.Instance.SetVariable(ObjectType.TopRoyalGuard, "Tier", 2);
		VariableManager.Instance.SetVariable(ObjectType.TopRoyalGuard, "MaxUsage", 1000);
		VariableManager.Instance.SetVariable(ObjectType.TopSuit02, "Weight", 1);
		VariableManager.Instance.SetVariable(ObjectType.TopSuit02, "Tier", 2);
		VariableManager.Instance.SetVariable(ObjectType.TopSuit02, "MaxUsage", 1000);
		VariableManager.Instance.SetVariable(ObjectType.TrojanRabbit, "WeightCapacity", 100);
		VariableManager.Instance.SetVariable(ObjectType.FlooringChequer, "BuildDelay", 2f);
		VariableManager.Instance.SetVariable(ObjectType.BrickArchway, "BuildDelay", 2f);
		VariableManager.Instance.SetVariable(ObjectType.BrickArchwayDoor, "BuildDelay", 2f);
		VariableManager.Instance.SetVariable(ObjectType.HedgeArchway, "BuildDelay", 2f);
		VariableManager.Instance.SetVariable(ObjectType.Sandcastle, "BuildDelay", 2f);
		VariableManager.Instance.SetVariable(ObjectType.CastleWall, "BuildDelay", 2f);
		VariableManager.Instance.SetVariable(ObjectType.CastlePlainTower, "BuildDelay", 2f);
		VariableManager.Instance.SetVariable(ObjectType.CastleFancyTower, "BuildDelay", 2f);
		VariableManager.Instance.SetVariable(ObjectType.CastleGate, "BuildDelay", 2f);
		VariableManager.Instance.SetVariable(ObjectType.CastleDrawbridge, "BuildDelay", 2f);
		VariableManager.Instance.SetVariable(ObjectType.StreetLamp, "BuildDelay", 2f);
		VariableManager.Instance.SetVariable(ObjectType.AquariumGood, "BuildDelay", 5f);
		VariableManager.Instance.SetVariable(ObjectType.CastleGate, "Width", 3);
		VariableManager.Instance.SetVariable(ObjectType.CastleGate, "Height", 1);
		VariableManager.Instance.SetVariable(ObjectType.CastleGate, "Walkable", 1);
		VariableManager.Instance.SetVariable(ObjectType.CastleDrawbridge, "Width", 3);
		VariableManager.Instance.SetVariable(ObjectType.CastleDrawbridge, "Height", 3);
		VariableManager.Instance.SetVariable(ObjectType.BrickArchway, "Walkable", 1);
		VariableManager.Instance.SetVariable(ObjectType.HedgeArchway, "Walkable", 1);
		VariableManager.Instance.SetVariable("RegularMissionTickets", 10);
		VariableManager.Instance.SetVariable("DailyMissionTickets", 100);
		VariableManager.Instance.SetVariable("MissionAmountVariation", 50);
		VariableManager.Instance.SetVariable("ReputationPointsRegular", 1);
		VariableManager.Instance.SetVariable("ReputationPointsDaily", 10);
		VariableManager.Instance.SetVariable(ObjectType.Castanets, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.Guiro, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.Maracas, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.Guitar, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.Triangle, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.Cowbell, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.JawHarp, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.AnimalPetDog, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.AnimalPetDog2, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerWhistleCrude, "CallSound", "WhistleBlown2");
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerWhistleCrude, "CancelSound", "WhistleCancel2");
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerWhistleCrude, "DropAllSound", "WhistleDropAll2");
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerWhistleCrude, "ToMeSound", "WhistleToMe2");
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerWhistleGood, "CallSound", "WhistleBlown3");
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerWhistleGood, "CancelSound", "WhistleCancel3");
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerWhistleGood, "DropAllSound", "WhistleDropAll3");
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerWhistleGood, "ToMeSound", "WhistleToMe3");
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerWhistleSuper, "CallSound", "WhistleBlown4");
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerWhistleSuper, "CancelSound", "WhistleCancel4");
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerWhistleSuper, "DropAllSound", "WhistleDropAll4");
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerWhistleSuper, "ToMeSound", "WhistleToMe4");
		VariableManager.Instance.SetVariable(ObjectType.AquariumGood, "Capacity", 20);
	}
}
