public class VariableData
{
	public void Init()
	{
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.TreePine, ObjectType.Rock, 32);
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.TreePine, ObjectType.ToolAxeStone, 24);
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.TreePine, ObjectType.ToolAxe, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.TreeApple, ObjectType.Rock, 32);
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.TreeApple, ObjectType.ToolAxeStone, 24);
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.TreeApple, ObjectType.ToolAxe, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.TreeCoconut, ObjectType.Rock, 32);
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.TreeCoconut, ObjectType.ToolAxeStone, 24);
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.TreeCoconut, ObjectType.ToolAxe, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.TreeMulberry, ObjectType.Rock, 32);
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.TreeMulberry, ObjectType.ToolAxeStone, 24);
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.TreeMulberry, ObjectType.ToolAxe, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.Log, ObjectType.ToolAxeStone, 16);
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.Log, ObjectType.ToolAxe, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.Plank, ObjectType.ToolAxeStone, 16);
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.Plank, ObjectType.ToolAxe, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.Pole, ObjectType.ToolAxeStone, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.Pole, ObjectType.ToolAxe, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Flail, ObjectType.Wheat, ObjectType.Stick, 18);
		VariableManager.Instance.SetVariable(Farmer.State.Flail, ObjectType.Wheat, ObjectType.ToolFlailCrude, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Flail, ObjectType.Wheat, ObjectType.ToolFlail, 3);
		VariableManager.Instance.SetVariable(Farmer.State.Flail, ObjectType.Bush, ObjectType.Stick, 15);
		VariableManager.Instance.SetVariable(Farmer.State.Flail, ObjectType.Bush, ObjectType.ToolFlailCrude, 9);
		VariableManager.Instance.SetVariable(Farmer.State.Flail, ObjectType.Bush, ObjectType.ToolFlail, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Flail, ObjectType.Pumpkin, ObjectType.Stick, 15);
		VariableManager.Instance.SetVariable(Farmer.State.Flail, ObjectType.Pumpkin, ObjectType.ToolFlailCrude, 9);
		VariableManager.Instance.SetVariable(Farmer.State.Flail, ObjectType.Pumpkin, ObjectType.ToolFlail, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Hammering, ObjectType.TreePine, ObjectType.Stick, 16);
		VariableManager.Instance.SetVariable(Farmer.State.Hammering, ObjectType.TreePine, ObjectType.ToolMallet, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Hammering, ObjectType.TreeApple, ObjectType.Stick, 16);
		VariableManager.Instance.SetVariable(Farmer.State.Hammering, ObjectType.TreeApple, ObjectType.ToolMallet, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Hammering, ObjectType.TreeCoconut, ObjectType.Stick, 16);
		VariableManager.Instance.SetVariable(Farmer.State.Hammering, ObjectType.TreeCoconut, ObjectType.ToolMallet, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Hammering, ObjectType.TreeMulberry, ObjectType.Stick, 16);
		VariableManager.Instance.SetVariable(Farmer.State.Hammering, ObjectType.TreeMulberry, ObjectType.ToolMallet, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Hammering, ObjectType.Pumpkin, ObjectType.Stick, 16);
		VariableManager.Instance.SetVariable(Farmer.State.Hammering, ObjectType.Pumpkin, ObjectType.ToolMallet, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Hoe, ObjectType.Plot, ObjectType.ToolHoeStone, 16);
		VariableManager.Instance.SetVariable(Farmer.State.Hoe, ObjectType.Plot, ObjectType.ToolHoe, 8);
		VariableManager.Instance.SetVariable(Farmer.State.Milking, ObjectType.AnimalCow, ObjectType.ToolBucketCrude, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Milking, ObjectType.AnimalCow, ObjectType.ToolBucket, 8);
		VariableManager.Instance.SetVariable(Farmer.State.Milking, ObjectType.AnimalCow, ObjectType.ToolBucketMetal, 4);
		VariableManager.Instance.SetVariable(Farmer.State.Milking, ObjectType.AnimalCowHighland, ObjectType.ToolBucketCrude, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Milking, ObjectType.AnimalCowHighland, ObjectType.ToolBucket, 8);
		VariableManager.Instance.SetVariable(Farmer.State.Milking, ObjectType.AnimalCowHighland, ObjectType.ToolBucketMetal, 4);
		VariableManager.Instance.SetVariable(Farmer.State.Milking, ObjectType.MilkingShedCrude, ObjectType.ToolBucketCrude, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Milking, ObjectType.MilkingShedCrude, ObjectType.ToolBucket, 8);
		VariableManager.Instance.SetVariable(Farmer.State.Milking, ObjectType.MilkingShedCrude, ObjectType.ToolBucketMetal, 4);
		VariableManager.Instance.SetVariable(Farmer.State.Mining, ObjectType.Plot, ObjectType.ToolPickStone, 20);
		VariableManager.Instance.SetVariable(Farmer.State.Mining, ObjectType.Plot, ObjectType.ToolPick, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Mining, ObjectType.Boulder, ObjectType.Rock, 32);
		VariableManager.Instance.SetVariable(Farmer.State.Mining, ObjectType.Boulder, ObjectType.ToolPickStone, 24);
		VariableManager.Instance.SetVariable(Farmer.State.Mining, ObjectType.Boulder, ObjectType.ToolPick, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Mining, ObjectType.TallBoulder, ObjectType.Rock, 32);
		VariableManager.Instance.SetVariable(Farmer.State.Mining, ObjectType.TallBoulder, ObjectType.ToolPickStone, 24);
		VariableManager.Instance.SetVariable(Farmer.State.Mining, ObjectType.TallBoulder, ObjectType.ToolPick, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Mining, Tile.TileType.Iron, ObjectType.ToolPickStone, 20);
		VariableManager.Instance.SetVariable(Farmer.State.Mining, Tile.TileType.Iron, ObjectType.ToolPick, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Mining, Tile.TileType.Coal, ObjectType.ToolPickStone, 20);
		VariableManager.Instance.SetVariable(Farmer.State.Mining, Tile.TileType.Coal, ObjectType.ToolPick, 12);
		VariableManager.Instance.SetVariable(Farmer.State.StoneCutting, ObjectType.Plot, ObjectType.ToolChiselCrude, 40);
		VariableManager.Instance.SetVariable(Farmer.State.StoneCutting, ObjectType.Plot, ObjectType.ToolChisel, 20);
		VariableManager.Instance.SetVariable(Farmer.State.StoneCutting, ObjectType.TallBoulder, ObjectType.ToolChiselCrude, 40);
		VariableManager.Instance.SetVariable(Farmer.State.StoneCutting, ObjectType.TallBoulder, ObjectType.ToolChisel, 20);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.CropWheat, ObjectType.RockSharp, 18);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.CropWheat, ObjectType.ToolScytheStone, 10);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.CropWheat, ObjectType.ToolScythe, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.CropWheat, ObjectType.ToolBlade, 8);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.CropCotton, ObjectType.RockSharp, 18);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.CropCotton, ObjectType.ToolScytheStone, 10);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.CropCotton, ObjectType.ToolScythe, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.CropCotton, ObjectType.ToolBlade, 8);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.Bullrushes, ObjectType.RockSharp, 18);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.Bullrushes, ObjectType.ToolScytheStone, 10);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.Bullrushes, ObjectType.ToolScythe, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.Bullrushes, ObjectType.ToolBlade, 8);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.Grass, ObjectType.RockSharp, 16);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.Grass, ObjectType.ToolScytheStone, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.Grass, ObjectType.ToolScythe, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.Grass, ObjectType.ToolBlade, 10);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.FlowerWild, ObjectType.ToolScytheStone, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.FlowerWild, ObjectType.ToolScythe, 4);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.FlowerWild, ObjectType.ToolBlade, 5);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.FlowerPot, ObjectType.ToolScytheStone, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.FlowerPot, ObjectType.ToolScythe, 4);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.FlowerPot, ObjectType.ToolBlade, 5);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.CropPumpkin, ObjectType.ToolScytheStone, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.CropPumpkin, ObjectType.ToolScythe, 4);
		VariableManager.Instance.SetVariable(Farmer.State.Scythe, ObjectType.CropPumpkin, ObjectType.ToolBlade, 5);
		VariableManager.Instance.SetVariable(Farmer.State.Shearing, ObjectType.AnimalSheep, ObjectType.ToolShears, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Shearing, ObjectType.AnimalAlpaca, ObjectType.ToolShears, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Shearing, ObjectType.Bush, ObjectType.ToolShears, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Shearing, ObjectType.ShearingShedCrude, ObjectType.ToolShears, 8);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.Plot, ObjectType.Stick, 20);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.Plot, ObjectType.ToolShovelStone, 16);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.Plot, ObjectType.ToolShovel, 8);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.Weed, ObjectType.Stick, 24);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.Weed, ObjectType.ToolShovelStone, 16);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.Weed, ObjectType.ToolShovel, 8);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.CropCarrot, ObjectType.Stick, 24);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.CropCarrot, ObjectType.ToolShovelStone, 16);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.CropCarrot, ObjectType.ToolShovel, 8);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.Bush, ObjectType.Stick, 32);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.Bush, ObjectType.ToolShovelStone, 24);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.Bush, ObjectType.ToolShovel, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.Hedge, ObjectType.Stick, 32);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.Hedge, ObjectType.ToolShovelStone, 24);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.Hedge, ObjectType.ToolShovel, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.Mushroom, ObjectType.Stick, 20);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.Mushroom, ObjectType.ToolShovelStone, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.Mushroom, ObjectType.ToolShovel, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.FlowerWild, ObjectType.Stick, 20);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.FlowerWild, ObjectType.ToolShovelStone, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.FlowerWild, ObjectType.ToolShovel, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.Grass, ObjectType.Stick, 20);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.Grass, ObjectType.ToolShovelStone, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.Grass, ObjectType.ToolShovel, 6);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.TreeStump, ObjectType.ToolShovelStone, 20);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, ObjectType.TreeStump, ObjectType.ToolShovel, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, Tile.TileType.Empty, ObjectType.ToolShovelStone, 16);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, Tile.TileType.Empty, ObjectType.ToolShovel, 8);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, Tile.TileType.Clay, ObjectType.ToolShovelStone, 20);
		VariableManager.Instance.SetVariable(Farmer.State.Shovel, Tile.TileType.Clay, ObjectType.ToolShovel, 12);
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.FishAny, ObjectType.RockSharp, 10);
		VariableManager.Instance.SetVariable(Farmer.State.Chopping, ObjectType.FishAny, ObjectType.ToolBlade, 5);
		VariableManager.Instance.SetVariable(Farmer.State.Fishing, ObjectType.Plot, ObjectType.ToolFishingStick, 20);
		VariableManager.Instance.SetVariable(Farmer.State.Dredging, ObjectType.Plot, ObjectType.ToolDredgerCrude, 20);
		VariableManager.Instance.SetVariable(Farmer.State.Netting, ObjectType.Plot, ObjectType.ToolNetCrude, 20);
		VariableManager.Instance.SetVariable(Farmer.State.Netting, ObjectType.Plot, ObjectType.ToolNet, 10);
		VariableManager.Instance.SetVariable(Farmer.State.DroppingSoil, ObjectType.Plot, ObjectType.ToolBucketCrude, 4);
		VariableManager.Instance.SetVariable(Farmer.State.DroppingSoil, ObjectType.Plot, ObjectType.ToolBucket, 4);
		VariableManager.Instance.SetVariable(Farmer.State.DroppingSoil, ObjectType.Plot, ObjectType.ToolBucketMetal, 4);
		VariableManager.Instance.SetVariable(ObjectType.ToolShovelStone, "MaxUsage", 20);
		VariableManager.Instance.SetVariable(ObjectType.ToolShovel, "MaxUsage", 50);
		VariableManager.Instance.SetVariable(ObjectType.ToolAxeStone, "MaxUsage", 20);
		VariableManager.Instance.SetVariable(ObjectType.ToolAxe, "MaxUsage", 50);
		VariableManager.Instance.SetVariable(ObjectType.ToolHoeStone, "MaxUsage", 20);
		VariableManager.Instance.SetVariable(ObjectType.ToolHoe, "MaxUsage", 50);
		VariableManager.Instance.SetVariable(ObjectType.ToolScytheStone, "MaxUsage", 40);
		VariableManager.Instance.SetVariable(ObjectType.ToolScythe, "MaxUsage", 100);
		VariableManager.Instance.SetVariable(ObjectType.ToolPickStone, "MaxUsage", 20);
		VariableManager.Instance.SetVariable(ObjectType.ToolPick, "MaxUsage", 50);
		VariableManager.Instance.SetVariable(ObjectType.ToolBucketCrude, "MaxUsage", 21);
		VariableManager.Instance.SetVariable(ObjectType.ToolBucket, "MaxUsage", 51);
		VariableManager.Instance.SetVariable(ObjectType.ToolBucketMetal, "MaxUsage", 200);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingStick, "MaxUsage", 10);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRod, "MaxUsage", 40);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRodGood, "MaxUsage", 90);
		VariableManager.Instance.SetVariable(ObjectType.ToolFlailCrude, "MaxUsage", 40);
		VariableManager.Instance.SetVariable(ObjectType.ToolFlail, "MaxUsage", 100);
		VariableManager.Instance.SetVariable(ObjectType.ToolBroom, "MaxUsage", 50);
		VariableManager.Instance.SetVariable(ObjectType.ToolChiselCrude, "MaxUsage", 5);
		VariableManager.Instance.SetVariable(ObjectType.ToolChisel, "MaxUsage", 20);
		VariableManager.Instance.SetVariable(ObjectType.ToolTorchCrude, "MaxUsage", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolMallet, "MaxUsage", 20);
		VariableManager.Instance.SetVariable(ObjectType.ToolPitchfork, "MaxUsage", 20);
		VariableManager.Instance.SetVariable(ObjectType.ToolShears, "MaxUsage", 20);
		VariableManager.Instance.SetVariable(ObjectType.ToolWateringCan, "MaxUsage", 100);
		VariableManager.Instance.SetVariable(ObjectType.ToolDredgerCrude, "MaxUsage", 20);
		VariableManager.Instance.SetVariable(ObjectType.ToolNetCrude, "MaxUsage", 20);
		VariableManager.Instance.SetVariable(ObjectType.ToolNet, "MaxUsage", 40);
		VariableManager.Instance.SetVariable(ObjectType.ToolBlade, "MaxUsage", 50);
		VariableManager.Instance.SetVariable(ObjectType.Stick, "MaxUsage", 10);
		VariableManager.Instance.SetVariable(ObjectType.Rock, "MaxUsage", 5);
		VariableManager.Instance.SetVariable(ObjectType.RockSharp, "MaxUsage", 5);
		VariableManager.Instance.SetVariable(ObjectType.ToolBucketCrude, "Capacity", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolBucket, "Capacity", 3);
		VariableManager.Instance.SetVariable(ObjectType.ToolBucketMetal, "Capacity", 5);
		VariableManager.Instance.SetVariable(ObjectType.ToolWateringCan, "Capacity", 10);
		VariableManager.Instance.SetVariable(ObjectType.ToolPitchfork, "Capacity", 5);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingStick, "Capacity", 10);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRod, "Capacity", 20);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRodGood, "Capacity", 30);
		VariableManager.Instance.SetVariable(ObjectType.ToolBucketCrude, "FillScoops", 7);
		VariableManager.Instance.SetVariable(ObjectType.ToolBucket, "FillScoops", 5);
		VariableManager.Instance.SetVariable(ObjectType.ToolBucketMetal, "FillScoops", 3);
		VariableManager.Instance.SetVariable(ObjectType.ToolWateringCan, "FillScoops", 3);
		VariableManager.Instance.SetVariable(ObjectType.ToolPitchfork, "FillScoops", 3);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingStick, "FillScoops", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRod, "FillScoops", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRodGood, "FillScoops", 1);
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk0, "WorkingSoundName", "WorkerWorkingClockwork");
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk0, "CarrySize", 3);
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk0, "InventorySize", 0);
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk0, "UpgradeSize", 1);
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk0, "FrameScale", 1f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk0, "MaxInstructions", 12);
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk0, "SerialPrefix", "Mk0");
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk0, "FindNearestRange", 12);
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk0, "FindNearestDelay", 40);
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk0, "HeadScale", 1f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk0, "MoveSoundName", "WorkerCrudeMove");
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk0, "MoveStoneSoundName", "WorkerCrudeStoneMove");
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk0, "MoveClaySoundName", "WorkerCrudeClayMove");
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk0, "SpeedScale", 0.5f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk0, "MoveInitialDelay", 60);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk0, "RechargeDelay", 3f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk0, "DriveEnergy", 90f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk0, "DriveScale", 1f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk1, "WorkingSoundName", "WorkerWorkingClockwork");
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk1, "CarrySize", 4);
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk1, "InventorySize", 1);
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk1, "UpgradeSize", 2);
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk1, "FrameScale", 1f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk1, "MaxInstructions", 16);
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk1, "SerialPrefix", "Mk1");
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk1, "FindNearestRange", 16);
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk1, "FindNearestDelay", 30);
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk1, "HeadScale", 1f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk1, "MoveSoundName", "WorkerCrudeMove");
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk1, "MoveStoneSoundName", "WorkerCrudeStoneMove");
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk1, "MoveClaySoundName", "WorkerCrudeClayMove");
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk1, "SpeedScale", 0.5f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk1, "MoveInitialDelay", 40);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk1, "RechargeDelay", 2f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk1, "DriveEnergy", 150f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk1, "DriveScale", 1f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk2, "WorkingSoundName", "WorkerWorkingClockwork");
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk2, "CarrySize", 6);
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk2, "InventorySize", 2);
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk2, "UpgradeSize", 2);
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk2, "FrameScale", 1f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk2, "MaxInstructions", 20);
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk2, "SerialPrefix", "Mk2");
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk2, "FindNearestRange", 30);
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk2, "FindNearestDelay", 20);
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk2, "HeadScale", 1f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk2, "MoveSoundName", "WorkerMove");
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk2, "MoveStoneSoundName", "WorkerStoneMove");
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk2, "MoveClaySoundName", "WorkerClayMove");
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk2, "SpeedScale", 0.75f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk2, "MoveInitialDelay", 30);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk2, "RechargeDelay", 1.5f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk2, "DriveEnergy", 200f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk2, "DriveScale", 1f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk3, "WorkingSoundName", "WorkerWorking");
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk3, "CarrySize", 8);
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk3, "InventorySize", 4);
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk3, "UpgradeSize", 3);
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameMk3, "FrameScale", 1f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk3, "MaxInstructions", 32);
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk3, "SerialPrefix", "Mk3");
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk3, "FindNearestRange", 35);
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk3, "FindNearestDelay", 10);
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadMk3, "HeadScale", 1f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk3, "MoveSoundName", "WorkerSteamMove");
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk3, "MoveStoneSoundName", "WorkerMoveStone");
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk3, "MoveClaySoundName", "WorkerMoveClay");
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk3, "SpeedScale", 1f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk3, "MoveInitialDelay", 20);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk3, "RechargeDelay", 1.5f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk3, "DriveEnergy", 500f);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveMk3, "DriveScale", 1f);
		VariableManager.Instance.SetVariable(ObjectType.Bush, "GrowSeedDelay", 5f);
		VariableManager.Instance.SetVariable(ObjectType.Bush, "GrowBushDelay", 20f);
		VariableManager.Instance.SetVariable(ObjectType.Bush, "GrowBerriesDelay", 120f);
		VariableManager.Instance.SetVariable(ObjectType.TreeApple, "GrowFruitDelay", 120f);
		VariableManager.Instance.SetVariable(ObjectType.TreeCoconut, "GrowFruitDelay", 120f);
		VariableManager.Instance.SetVariable(ObjectType.TreeMulberry, "GrowFruitDelay", 5f);
		VariableManager.Instance.SetVariable(ObjectType.CropWheat, "GrowDelay", 180f);
		VariableManager.Instance.SetVariable(ObjectType.CropWheat, "MaxYield", 5);
		VariableManager.Instance.SetVariable(ObjectType.CropWheat, "TilledBoost", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropWheat, "FertiliserBoost", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropWheat, "WaterBoost", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropWheat, "MaxHeight", 1f);
		VariableManager.Instance.SetVariable(ObjectType.CropCotton, "GrowDelay", 180f);
		VariableManager.Instance.SetVariable(ObjectType.CropCotton, "MaxYield", 5);
		VariableManager.Instance.SetVariable(ObjectType.CropCotton, "TilledBoost", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropCotton, "FertiliserBoost", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropCotton, "WaterBoost", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropCotton, "MaxHeight", 1f);
		VariableManager.Instance.SetVariable(ObjectType.CropCarrot, "GrowDelay", 180f);
		VariableManager.Instance.SetVariable(ObjectType.CropCarrot, "MaxYield", 5);
		VariableManager.Instance.SetVariable(ObjectType.CropCarrot, "TilledBoost", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropCarrot, "FertiliserBoost", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropCarrot, "WaterBoost", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropCarrot, "MaxHeight", 1f);
		VariableManager.Instance.SetVariable(ObjectType.Grass, "GrowDelay", 45f);
		VariableManager.Instance.SetVariable(ObjectType.Weed, "GrowDelay", 20f);
		VariableManager.Instance.SetVariable(ObjectType.Mushroom, "GrowDelay", 180f);
		VariableManager.Instance.SetVariable(ObjectType.Bullrushes, "GrowDelay", 180f);
		VariableManager.Instance.SetVariable("ClaySoilChance", 50);
		VariableManager.Instance.SetVariable("IronSoilChance", 20);
		VariableManager.Instance.SetVariable("IronSoil2Chance", 50);
		VariableManager.Instance.SetVariable("CoalSoilChance", 20);
		VariableManager.Instance.SetVariable("CoalSoil2Chance", 40);
		VariableManager.Instance.SetVariable("CoalSoil3Chance", 60);
		VariableManager.Instance.SetVariable("StoneSoilChance", 50);
		VariableManager.Instance.SetVariable("TurfChance", 30);
		VariableManager.Instance.SetVariable(ObjectType.BrickWall, "SearchArea", 400);
		VariableManager.Instance.SetVariable(ObjectType.FarmerPlayer, "BaseDelay", 0.2f);
		VariableManager.Instance.SetVariable(ObjectType.FarmerPlayer, "CarrySize", 4);
		VariableManager.Instance.SetVariable(ObjectType.FarmerPlayer, "InventoryCapacity", 1);
		VariableManager.Instance.SetVariable(ObjectType.Worker, "BaseDelay", 0.2f);
		VariableManager.Instance.SetVariable(ObjectType.Folk, "MaxEnergy", 180f);
		VariableManager.Instance.SetVariable(ObjectType.Folk, "HappinessDelay", 15f);
		VariableManager.Instance.SetVariable(ObjectType.Folk, "Weight0", 1);
		VariableManager.Instance.SetVariable(ObjectType.Folk, "Weight1", 2);
		VariableManager.Instance.SetVariable(ObjectType.Folk, "Weight2", 8);
		VariableManager.Instance.SetVariable(ObjectType.Folk, "Weight3", 16);
		VariableManager.Instance.SetVariable(ObjectType.Folk, "Weight4", 32);
		VariableManager.Instance.SetVariable(ObjectType.Folk, "Weight5", 48);
		VariableManager.Instance.SetVariable(ObjectType.Folk, "Weight6", 64);
		VariableManager.Instance.SetVariable(ObjectType.Folk, "Weight7", 80);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart, "Value", 1);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart2, "Value", 10);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart3, "Value", 100);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart4, "Value", 1000);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart5, "Value", 10000);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart6, "Value", 100000);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart7, "Value", 1000000);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart, "Usage", 1);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart2, "Usage", 10);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart3, "Usage", 100);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart4, "Usage", 1000);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart5, "Usage", 10000);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart6, "Usage", 100000);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart7, "Usage", 1000000);
		VariableManager.Instance.SetVariable(ObjectType.MushroomSoup, "FuelRequired", 10f);
		VariableManager.Instance.SetVariable(ObjectType.MushroomStew, "FuelRequired", 30f);
		VariableManager.Instance.SetVariable(ObjectType.MushroomPie, "FuelRequired", 50f);
		VariableManager.Instance.SetVariable(ObjectType.MushroomPudding, "FuelRequired", 100f);
		VariableManager.Instance.SetVariable(ObjectType.MushroomBurger, "FuelRequired", 150f);
		VariableManager.Instance.SetVariable(ObjectType.BerriesStew, "FuelRequired", 10f);
		VariableManager.Instance.SetVariable(ObjectType.BerriesJam, "FuelRequired", 30f);
		VariableManager.Instance.SetVariable(ObjectType.BerriesPie, "FuelRequired", 50f);
		VariableManager.Instance.SetVariable(ObjectType.BerriesCake, "FuelRequired", 100f);
		VariableManager.Instance.SetVariable(ObjectType.BerryDanish, "FuelRequired", 150f);
		VariableManager.Instance.SetVariable(ObjectType.BreadCrude, "FuelRequired", 40f);
		VariableManager.Instance.SetVariable(ObjectType.Bread, "FuelRequired", 50f);
		VariableManager.Instance.SetVariable(ObjectType.BreadPudding, "FuelRequired", 100f);
		VariableManager.Instance.SetVariable(ObjectType.CreamBrioche, "FuelRequired", 150f);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinSoup, "FuelRequired", 10f);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinStew, "FuelRequired", 30f);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinPie, "FuelRequired", 50f);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinCake, "FuelRequired", 100f);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinBurger, "FuelRequired", 150f);
		VariableManager.Instance.SetVariable(ObjectType.AppleStew, "FuelRequired", 10f);
		VariableManager.Instance.SetVariable(ObjectType.AppleJam, "FuelRequired", 30f);
		VariableManager.Instance.SetVariable(ObjectType.ApplePie, "FuelRequired", 50f);
		VariableManager.Instance.SetVariable(ObjectType.AppleCake, "FuelRequired", 100f);
		VariableManager.Instance.SetVariable(ObjectType.AppleDanish, "FuelRequired", 150f);
		VariableManager.Instance.SetVariable(ObjectType.FishSoup, "FuelRequired", 20f);
		VariableManager.Instance.SetVariable(ObjectType.FishStew, "FuelRequired", 30f);
		VariableManager.Instance.SetVariable(ObjectType.FishPie, "FuelRequired", 50f);
		VariableManager.Instance.SetVariable(ObjectType.FishCake, "FuelRequired", 100f);
		VariableManager.Instance.SetVariable(ObjectType.FishBurger, "FuelRequired", 150f);
		VariableManager.Instance.SetVariable(ObjectType.CarrotStirFry, "FuelRequired", 20f);
		VariableManager.Instance.SetVariable(ObjectType.CarrotHoney, "FuelRequired", 30f);
		VariableManager.Instance.SetVariable(ObjectType.CarrotCurry, "FuelRequired", 50f);
		VariableManager.Instance.SetVariable(ObjectType.Naan, "FuelRequired", 20f);
		VariableManager.Instance.SetVariable(ObjectType.CarrotCake, "FuelRequired", 100f);
		VariableManager.Instance.SetVariable(ObjectType.CarrotBurger, "FuelRequired", 150f);
		VariableManager.Instance.SetVariable(ObjectType.MilkPorridge, "FuelRequired", 10f);
		VariableManager.Instance.SetVariable(ObjectType.FruitPorridge, "FuelRequired", 20f);
		VariableManager.Instance.SetVariable(ObjectType.HoneyPorridge, "FuelRequired", 20f);
		VariableManager.Instance.SetVariable(ObjectType.AppleBerryPie, "FuelRequired", 100f);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinMushroomPie, "FuelRequired", 100f);
		VariableManager.Instance.SetVariable(ObjectType.Charcoal, "FuelRequired", 0f);
		VariableManager.Instance.SetVariable(ObjectType.IronCrude, "FuelRequired", 80f);
		VariableManager.Instance.SetVariable(ObjectType.PotClay, "FuelRequired", 20f);
		VariableManager.Instance.SetVariable(ObjectType.LargeBowlClay, "FuelRequired", 20f);
		VariableManager.Instance.SetVariable(ObjectType.FlowerPot, "FuelRequired", 20f);
		VariableManager.Instance.SetVariable(ObjectType.BricksCrude, "FuelRequired", 20f);
		VariableManager.Instance.SetVariable(ObjectType.Gnome, "FuelRequired", 20f);
		VariableManager.Instance.SetVariable(ObjectType.Gnome2, "FuelRequired", 20f);
		VariableManager.Instance.SetVariable(ObjectType.Gnome3, "FuelRequired", 20f);
		VariableManager.Instance.SetVariable(ObjectType.Gnome4, "FuelRequired", 20f);
		VariableManager.Instance.SetVariable(ObjectType.Gnome5, "FuelRequired", 20f);
		VariableManager.Instance.SetVariable(ObjectType.Gnome6, "FuelRequired", 20f);
		VariableManager.Instance.SetVariable(ObjectType.RoofTiles, "FuelRequired", 20f);
		VariableManager.Instance.SetVariable(ObjectType.JarClay, "FuelRequired", 20f);
		VariableManager.Instance.SetVariable(ObjectType.Ink, "FuelRequired", 20f);
		VariableManager.Instance.SetVariable(ObjectType.Seedling, "FuelRequired", 1f);
		VariableManager.Instance.SetVariable(ObjectType.SeedlingMulberry, "FuelRequired", 1f);
		VariableManager.Instance.SetVariable(ObjectType.MushroomDug, "Energy", 20f);
		VariableManager.Instance.SetVariable(ObjectType.MushroomDug, "Tier", 0);
		VariableManager.Instance.SetVariable(ObjectType.MushroomHerb, "Energy", 30f);
		VariableManager.Instance.SetVariable(ObjectType.MushroomHerb, "Tier", 1);
		VariableManager.Instance.SetVariable(ObjectType.MushroomSoup, "Energy", 40f);
		VariableManager.Instance.SetVariable(ObjectType.MushroomSoup, "Tier", 2);
		VariableManager.Instance.SetVariable(ObjectType.MushroomStew, "Energy", 50f);
		VariableManager.Instance.SetVariable(ObjectType.MushroomStew, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.MushroomPie, "Energy", 60f);
		VariableManager.Instance.SetVariable(ObjectType.MushroomPie, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.MushroomPuddingRaw, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.MushroomPudding, "Energy", 70f);
		VariableManager.Instance.SetVariable(ObjectType.MushroomPudding, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.MushroomBurger, "Energy", 80f);
		VariableManager.Instance.SetVariable(ObjectType.MushroomBurger, "Tier", 6);
		VariableManager.Instance.SetVariable(ObjectType.Berries, "Energy", 20f);
		VariableManager.Instance.SetVariable(ObjectType.Berries, "Tier", 0);
		VariableManager.Instance.SetVariable(ObjectType.BerriesSpice, "Energy", 30f);
		VariableManager.Instance.SetVariable(ObjectType.BerriesSpice, "Tier", 1);
		VariableManager.Instance.SetVariable(ObjectType.BerriesStew, "Energy", 40f);
		VariableManager.Instance.SetVariable(ObjectType.BerriesStew, "Tier", 2);
		VariableManager.Instance.SetVariable(ObjectType.BerriesJam, "Energy", 50f);
		VariableManager.Instance.SetVariable(ObjectType.BerriesJam, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.BerriesPie, "Energy", 60f);
		VariableManager.Instance.SetVariable(ObjectType.BerriesPie, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.BerriesCake, "Energy", 70f);
		VariableManager.Instance.SetVariable(ObjectType.BerriesCake, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.BerryDanish, "Energy", 80f);
		VariableManager.Instance.SetVariable(ObjectType.BerryDanish, "Tier", 6);
		VariableManager.Instance.SetVariable(ObjectType.Porridge, "Energy", 30f);
		VariableManager.Instance.SetVariable(ObjectType.Porridge, "Tier", 1);
		VariableManager.Instance.SetVariable(ObjectType.BreadCrude, "Energy", 40f);
		VariableManager.Instance.SetVariable(ObjectType.BreadCrude, "Tier", 2);
		VariableManager.Instance.SetVariable(ObjectType.Bread, "Energy", 50f);
		VariableManager.Instance.SetVariable(ObjectType.Bread, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.BreadButtered, "Energy", 60f);
		VariableManager.Instance.SetVariable(ObjectType.BreadButtered, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.BreadPudding, "Energy", 70f);
		VariableManager.Instance.SetVariable(ObjectType.BreadPudding, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.CreamBrioche, "Energy", 80f);
		VariableManager.Instance.SetVariable(ObjectType.CreamBrioche, "Tier", 6);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinRaw, "Energy", 20f);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinRaw, "Tier", 0);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinSeeds, "Energy", 20f);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinSeeds, "Tier", 0);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinHerb, "Energy", 30f);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinHerb, "Tier", 1);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinSoup, "Energy", 40f);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinSoup, "Tier", 2);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinStew, "Energy", 50f);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinStew, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinPie, "Energy", 60f);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinPie, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinCakeRaw, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinCake, "Energy", 70f);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinCake, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinBurger, "Energy", 80f);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinBurger, "Tier", 6);
		VariableManager.Instance.SetVariable(ObjectType.FishRaw, "Energy", 20f);
		VariableManager.Instance.SetVariable(ObjectType.FishRaw, "Tier", 0);
		VariableManager.Instance.SetVariable(ObjectType.FishHerb, "Energy", 30f);
		VariableManager.Instance.SetVariable(ObjectType.FishHerb, "Tier", 1);
		VariableManager.Instance.SetVariable(ObjectType.FishSoup, "Energy", 40f);
		VariableManager.Instance.SetVariable(ObjectType.FishSoup, "Tier", 2);
		VariableManager.Instance.SetVariable(ObjectType.FishStew, "Energy", 50f);
		VariableManager.Instance.SetVariable(ObjectType.FishStew, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.FishPie, "Energy", 60f);
		VariableManager.Instance.SetVariable(ObjectType.FishPie, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.FishCakeRaw, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.FishCake, "Energy", 70f);
		VariableManager.Instance.SetVariable(ObjectType.FishCake, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.FishBurger, "Energy", 80f);
		VariableManager.Instance.SetVariable(ObjectType.FishBurger, "Tier", 6);
		VariableManager.Instance.SetVariable(ObjectType.Apple, "Energy", 20f);
		VariableManager.Instance.SetVariable(ObjectType.Apple, "Tier", 0);
		VariableManager.Instance.SetVariable(ObjectType.AppleSpice, "Energy", 30f);
		VariableManager.Instance.SetVariable(ObjectType.AppleSpice, "Tier", 1);
		VariableManager.Instance.SetVariable(ObjectType.AppleStew, "Energy", 40f);
		VariableManager.Instance.SetVariable(ObjectType.AppleStew, "Tier", 2);
		VariableManager.Instance.SetVariable(ObjectType.AppleJam, "Energy", 50f);
		VariableManager.Instance.SetVariable(ObjectType.AppleJam, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.ApplePie, "Energy", 60f);
		VariableManager.Instance.SetVariable(ObjectType.ApplePie, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.AppleCakeRaw, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.AppleCake, "Energy", 70f);
		VariableManager.Instance.SetVariable(ObjectType.AppleCake, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.AppleDanish, "Energy", 80f);
		VariableManager.Instance.SetVariable(ObjectType.AppleDanish, "Tier", 6);
		VariableManager.Instance.SetVariable(ObjectType.Carrot, "Energy", 20f);
		VariableManager.Instance.SetVariable(ObjectType.Carrot, "Tier", 0);
		VariableManager.Instance.SetVariable(ObjectType.CarrotSalad, "Energy", 30f);
		VariableManager.Instance.SetVariable(ObjectType.CarrotSalad, "Tier", 1);
		VariableManager.Instance.SetVariable(ObjectType.CarrotStirFry, "Energy", 40f);
		VariableManager.Instance.SetVariable(ObjectType.CarrotStirFry, "Tier", 2);
		VariableManager.Instance.SetVariable(ObjectType.CarrotHoney, "Energy", 50f);
		VariableManager.Instance.SetVariable(ObjectType.CarrotHoney, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.CarrotCurry, "Energy", 60f);
		VariableManager.Instance.SetVariable(ObjectType.CarrotCurry, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.CarrotCakeRaw, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.CarrotCake, "Energy", 70f);
		VariableManager.Instance.SetVariable(ObjectType.CarrotCake, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.CarrotBurger, "Energy", 80f);
		VariableManager.Instance.SetVariable(ObjectType.CarrotBurger, "Tier", 6);
		VariableManager.Instance.SetVariable(ObjectType.MilkPorridge, "Energy", 40f);
		VariableManager.Instance.SetVariable(ObjectType.MilkPorridge, "Tier", 2);
		VariableManager.Instance.SetVariable(ObjectType.FruitPorridge, "Energy", 50f);
		VariableManager.Instance.SetVariable(ObjectType.FruitPorridge, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.HoneyPorridge, "Energy", 50f);
		VariableManager.Instance.SetVariable(ObjectType.HoneyPorridge, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.AppleBerryPie, "Energy", 70f);
		VariableManager.Instance.SetVariable(ObjectType.AppleBerryPie, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinMushroomPie, "Energy", 70f);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinMushroomPie, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.Naan, "Energy", 20f);
		VariableManager.Instance.SetVariable(ObjectType.Naan, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.Water, "Energy", 10f);
		VariableManager.Instance.SetVariable(ObjectType.Water, "Tier", 0);
		VariableManager.Instance.SetVariable(ObjectType.Milk, "Energy", 10f);
		VariableManager.Instance.SetVariable(ObjectType.Milk, "Tier", 0);
		VariableManager.Instance.SetVariable(ObjectType.Egg, "Energy", 10f);
		VariableManager.Instance.SetVariable(ObjectType.Egg, "Tier", 0);
		VariableManager.Instance.SetVariable(ObjectType.Butter, "Energy", 10f);
		VariableManager.Instance.SetVariable(ObjectType.Butter, "Tier", 0);
		VariableManager.Instance.SetVariable(ObjectType.Honey, "Energy", 10f);
		VariableManager.Instance.SetVariable(ObjectType.Honey, "Tier", 1);
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerInventoryCrude, "Capacity", 1);
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerInventoryGood, "Capacity", 3);
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerInventorySuper, "Capacity", 5);
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerMovementCrude, "Delay", 0.05f);
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerMovementGood, "Delay", 0.075f);
		VariableManager.Instance.SetVariable(ObjectType.UpgradePlayerMovementSuper, "Delay", 0.1f);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerInventoryCrude, "Capacity", 1);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerInventoryGood, "Capacity", 2);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerInventorySuper, "Capacity", 4);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerCarryCrude, "Capacity", 1);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerCarryGood, "Capacity", 2);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerCarrySuper, "Capacity", 4);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerEnergyCrude, "DriveEnergy", 0.2f);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerEnergyGood, "DriveEnergy", 0.4f);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerEnergySuper, "DriveEnergy", 0.6f);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerMemoryCrude, "Size", 4);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerMemoryGood, "Size", 8);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerMemorySuper, "Size", 32);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerMovementCrude, "InitialDelay", 20);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerMovementCrude, "MoveScale", 0.1f);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerMovementGood, "InitialDelay", 40);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerMovementGood, "MoveScale", 0.2f);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerMovementSuper, "InitialDelay", 60);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerMovementSuper, "MoveScale", 0.3f);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerSearchCrude, "InitialDelay", 10);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerSearchCrude, "Range", 5);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerSearchGood, "InitialDelay", 20);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerSearchGood, "Range", 10);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerSearchSuper, "InitialDelay", 30);
		VariableManager.Instance.SetVariable(ObjectType.UpgradeWorkerSearchSuper, "Range", 15);
		VariableManager.Instance.SetVariable(ObjectType.Plank, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Pole, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Stick, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Rock, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Log, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Clay, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.IronOre, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Coal, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.BeesNest, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Apple, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.TreeSeed, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.TreeMulberry, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.SeedlingMulberry, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.SilkRaw, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.AnimalSilkmoth, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Pumpkin, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinSeeds, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinRaw, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Berries, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.GrassCut, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.AnimalBee, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.AnimalBird, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.AnimalChicken, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.AnimalCow, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.AnimalSheep, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.AnimalLeech, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FishBait, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FishingJunkFresh, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FishingJunkSalt, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FishCatFish, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FishMahiMahi, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FishOrangeRoughy, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FishPerch, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FishSalmon, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FishCarp, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FishGar, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FishMonkfish, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FishMarlin, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Egg, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.MushroomDug, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Water, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Milk, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.SeaWater, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Sand, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Soil, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Manure, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.WheatSeed, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Wheat, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Straw, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Wool, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.WeedDug, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Turf, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FlowerSeeds01, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FlowerSeeds02, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FlowerSeeds03, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FlowerSeeds04, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FlowerSeeds05, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FlowerSeeds06, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FlowerSeeds07, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FlowerBunch01, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FlowerBunch02, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FlowerBunch03, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FlowerBunch04, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FlowerBunch05, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FlowerBunch06, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FlowerBunch07, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Folk, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart2, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart3, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart4, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart5, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart6, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart7, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FishAny, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.HatAny, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.TopAny, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.HeartAny, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.WorkerFrameAny, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.WorkerHeadAny, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.WorkerDriveAny, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Fuel, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.StoneBlockCrude, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Fleece, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FishRaw, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.CottonSeeds, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.CottonBall, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.CottonLint, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.BullrushesSeeds, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.BullrushesStems, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.BullrushesFibre, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Weed, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Grass, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropWheat, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropCotton, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.TreePine, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.TreeApple, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.TreeStump, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropPumpkin, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Bush, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Hedge, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Mushroom, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.FlowerWild, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Bullrushes, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Honey, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.Charcoal, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.HayBale, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.Pumpkin, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.IronCrude, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.IronOre, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.MetalCog, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.MetalWheel, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.MetalAxle, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.MetalPoleCrude, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.MetalPlateCrude, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.LargeBowlClayRaw, "Weight", 3);
		VariableManager.Instance.SetVariable(ObjectType.LargeBowlClay, "Weight", 3);
		VariableManager.Instance.SetVariable(ObjectType.BricksCrude, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.BricksCrudeRaw, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.RoofTiles, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.RoofTilesRaw, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.Axle, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.Cog, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.CogCrude, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart3, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart4, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.Scarecrow, "Weight", 3);
		VariableManager.Instance.SetVariable(ObjectType.Log, "Weight", 3);
		VariableManager.Instance.SetVariable(ObjectType.Worker, "Weight", 3);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart5, "Weight", 3);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart6, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.FolkHeart7, "Weight", 5);
		VariableManager.Instance.SetVariable(ObjectType.Boiler, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.ConnectingRod, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.Flywheel, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.Piston, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.MetalGirder, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.Firebox, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.Rivets, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.Chimney, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.Fireplace, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.Millstone, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.StoneBlock, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.StoneBlockCrude, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.FrameBox, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.FrameDoor, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.FrameSquare, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.FrameTriangle, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.FrameWindow, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.Panel, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.WoodenBeam, "Weight", 3);
		VariableManager.Instance.SetVariable(ObjectType.MushroomSoup, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.MushroomStew, "Weight", 6);
		VariableManager.Instance.SetVariable(ObjectType.MushroomPieRaw, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.MushroomPie, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.MushroomPuddingRaw, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.MushroomPudding, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.MushroomBurger, "Weight", 16);
		VariableManager.Instance.SetVariable(ObjectType.BerriesStew, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.BerriesJam, "Weight", 6);
		VariableManager.Instance.SetVariable(ObjectType.BerriesPieRaw, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.BerriesPie, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.BerriesCakeRaw, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.BerriesCake, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.BerryDanish, "Weight", 16);
		VariableManager.Instance.SetVariable(ObjectType.BreadCrude, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.Bread, "Weight", 6);
		VariableManager.Instance.SetVariable(ObjectType.BreadButtered, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.BreadPuddingRaw, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.BreadPudding, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.CreamBrioche, "Weight", 16);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinSoup, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinStew, "Weight", 6);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinPieRaw, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinPie, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinCake, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinCakeRaw, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinBurger, "Weight", 16);
		VariableManager.Instance.SetVariable(ObjectType.AppleStew, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.AppleJam, "Weight", 6);
		VariableManager.Instance.SetVariable(ObjectType.ApplePieRaw, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.ApplePie, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.AppleCakeRaw, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.AppleCake, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.AppleDanish, "Weight", 16);
		VariableManager.Instance.SetVariable(ObjectType.FishSoup, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.FishStew, "Weight", 6);
		VariableManager.Instance.SetVariable(ObjectType.FishPieRaw, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.FishPie, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.FishCakeRaw, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.FishCake, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.FishBurger, "Weight", 16);
		VariableManager.Instance.SetVariable(ObjectType.CarrotStirFry, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.CarrotHoney, "Weight", 6);
		VariableManager.Instance.SetVariable(ObjectType.CarrotCurry, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.CarrotCakeRaw, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.CarrotCake, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.CarrotBurger, "Weight", 16);
		VariableManager.Instance.SetVariable(ObjectType.MilkPorridge, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.FruitPorridge, "Weight", 6);
		VariableManager.Instance.SetVariable(ObjectType.HoneyPorridge, "Weight", 6);
		VariableManager.Instance.SetVariable(ObjectType.AppleBerryPieRaw, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.AppleBerryPie, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinMushroomPieRaw, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinMushroomPie, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.Naan, "Weight", 6);
		VariableManager.Instance.SetVariable(ObjectType.NaanRaw, "Weight", 6);
		VariableManager.Instance.SetVariable(ObjectType.CakeBatter, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.TopJumper, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopJacket, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.TopBlazer, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.TopTuxedo, "Weight", 16);
		VariableManager.Instance.SetVariable(ObjectType.TopDress, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopShirt, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.TopShirtTie, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.TopGown, "Weight", 16);
		VariableManager.Instance.SetVariable(ObjectType.TopRobe, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopCoat, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.TopCoatScarf, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.TopSuit, "Weight", 16);
		VariableManager.Instance.SetVariable(ObjectType.TopLumberjack, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.TopDungarees, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.Doll, "Weight", 6);
		VariableManager.Instance.SetVariable(ObjectType.JackInTheBox, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.DollHouse, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.Spaceship, "Weight", 16);
		VariableManager.Instance.SetVariable(ObjectType.TopMac, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.TopPlumber, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.TopTree, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.TopWally, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopJumper02, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopDungarees, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.TopDungareesClown, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.TopSanta, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.TopFox, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.TopDinosaur, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.TopBunny, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.TopDuck, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.TopTShirt02, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopTShirtShow, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopApron, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopAdventurer, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.ToyHorse, "Weight", 6);
		VariableManager.Instance.SetVariable(ObjectType.ToyHorseCart, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.ToyHorseCarriage, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.ToyTrain, "Weight", 16);
		VariableManager.Instance.SetVariable(ObjectType.AnimalChicken, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.AnimalCow, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.AnimalSheep, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.AnimalAlpaca, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.AnimalCowHighland, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.Worker, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.Folk, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.Sign, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.Sign2, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.Sign3, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.Billboard, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolShovel, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolShovelStone, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolHoe, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolHoeStone, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolAxe, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolAxeStone, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolScythe, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolScytheStone, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolPick, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolPickStone, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolBucketCrude, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolBucket, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolBucketMetal, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolMallet, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolChiselCrude, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolChisel, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolFlailCrude, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolFlail, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolShears, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolWateringCan, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingStick, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRod, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRodGood, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolBroom, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolPitchfork, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolTorchCrude, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolDredgerCrude, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolNetCrude, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolNet, "NoMultiple", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolBlade, "NoMultiple", 1);
		VariableManager.Instance.SetVariable("SunRiseDelay", 3);
		VariableManager.Instance.SetVariable("DayTimeDelay", 12);
		VariableManager.Instance.SetVariable("SunSetDelay", 3);
		VariableManager.Instance.SetVariable("NightTimeDelay", 3);
		VariableManager.Instance.SetVariable(ObjectType.WheelBarrow, "WeightCapacity", 20);
		VariableManager.Instance.SetVariable(ObjectType.Cart, "WeightCapacity", 32);
		VariableManager.Instance.SetVariable(ObjectType.CartLiquid, "WeightCapacity", 50);
		VariableManager.Instance.SetVariable(ObjectType.Carriage, "WeightCapacity", 50);
		VariableManager.Instance.SetVariable(ObjectType.CarriageLiquid, "WeightCapacity", 100);
		VariableManager.Instance.SetVariable(ObjectType.CarriageTrain, "WeightCapacity", 200);
		VariableManager.Instance.SetVariable(ObjectType.Train, "MaxCarriages", 2);
		VariableManager.Instance.SetVariable(ObjectType.Train, "BaseDelay", 0.15f);
		VariableManager.Instance.SetVariable(ObjectType.Train, "MaxWater", 10f);
		VariableManager.Instance.SetVariable(ObjectType.Train, "MaxFuel", 1500f);
		VariableManager.Instance.SetVariable(ObjectType.Train, "WaterUsePerSecond", 0.1f);
		VariableManager.Instance.SetVariable(ObjectType.Train, "FuelUsePerSecond", 6f);
		VariableManager.Instance.SetVariable(ObjectType.Train, "RefuellingTime", 2f);
		VariableManager.Instance.SetVariable(ObjectType.Minecart, "MaxCarriages", 1);
		VariableManager.Instance.SetVariable(ObjectType.Minecart, "BaseDelay", 0.15f);
		VariableManager.Instance.SetVariable(ObjectType.GiantWaterWheel, "EnergyCapacity", 150);
		VariableManager.Instance.SetVariable(ObjectType.Windmill, "EnergyCapacity", 50);
		VariableManager.Instance.SetVariable(ObjectType.StationaryEngine, "EnergyCapacity", 1000);
		VariableManager.Instance.SetVariable(ObjectType.StationaryEngine, "WaterCapacity", 20);
		VariableManager.Instance.SetVariable("FertiliserValueFood", 0.25f);
		VariableManager.Instance.SetVariable(ObjectType.Fertiliser, "FertiliserValue", 1);
		VariableManager.Instance.SetVariable(ObjectType.Manure, "FertiliserValue", 4);
		VariableManager.Instance.SetVariable(ObjectType.Straw, "FertiliserValue", 0.25f);
		VariableManager.Instance.SetVariable(ObjectType.TreeSeed, "FertiliserValue", 0.25f);
		VariableManager.Instance.SetVariable(ObjectType.MulberrySeed, "FertiliserValue", 0.25f);
		VariableManager.Instance.SetVariable(ObjectType.WheatSeed, "FertiliserValue", 0.25f);
		VariableManager.Instance.SetVariable(ObjectType.CarrotSeed, "FertiliserValue", 0.25f);
		VariableManager.Instance.SetVariable(ObjectType.Coconut, "FertiliserValue", 0.25f);
		VariableManager.Instance.SetVariable(ObjectType.CottonSeeds, "FertiliserValue", 0.25f);
		VariableManager.Instance.SetVariable(ObjectType.BullrushesSeeds, "FertiliserValue", 0.25f);
		VariableManager.Instance.SetVariable(ObjectType.WeedDug, "FertiliserValue", 0.5f);
		VariableManager.Instance.SetVariable(ObjectType.Pumpkin, "FertiliserValue", 1);
		VariableManager.Instance.SetVariable(ObjectType.GrassCut, "FertiliserValue", 0.25f);
		VariableManager.Instance.SetVariable(ObjectType.Turf, "FertiliserValue", 1);
		VariableManager.Instance.SetVariable(ObjectType.Seedling, "FertiliserValue", 0.25f);
		VariableManager.Instance.SetVariable(ObjectType.SeedlingMulberry, "FertiliserValue", 0.25f);
		VariableManager.Instance.SetVariable(ObjectType.HayBale, "FertiliserValue", 1);
		VariableManager.Instance.SetVariable(ObjectType.Dough, "FertiliserValue", 0.5f);
		VariableManager.Instance.SetVariable(ObjectType.DoughGood, "FertiliserValue", 1f);
		VariableManager.Instance.SetVariable(ObjectType.Stick, "Fuel", 10);
		VariableManager.Instance.SetVariable(ObjectType.Pole, "Fuel", 30);
		VariableManager.Instance.SetVariable(ObjectType.Plank, "Fuel", 60);
		VariableManager.Instance.SetVariable(ObjectType.Log, "Fuel", 120);
		VariableManager.Instance.SetVariable(ObjectType.Charcoal, "Fuel", 240);
		VariableManager.Instance.SetVariable(ObjectType.Coal, "Fuel", 500);
		VariableManager.Instance.SetVariable(ObjectType.HayBale, "Fuel", 10);
		VariableManager.Instance.SetVariable(ObjectType.Fertiliser, "Fuel", 3);
		VariableManager.Instance.SetVariable("FirstTopTier", 2);
		VariableManager.Instance.SetVariable(ObjectType.TopPoncho, "Tier", 2);
		VariableManager.Instance.SetVariable(ObjectType.TopJumper, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.TopJacket, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopBlazer, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.TopTuxedo, "Tier", 6);
		VariableManager.Instance.SetVariable(ObjectType.TopTunic, "Tier", 2);
		VariableManager.Instance.SetVariable(ObjectType.TopDress, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.TopShirt, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopShirtTie, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.TopGown, "Tier", 6);
		VariableManager.Instance.SetVariable(ObjectType.TopToga, "Tier", 2);
		VariableManager.Instance.SetVariable(ObjectType.TopRobe, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.TopCoat, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopCoatScarf, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.TopSuit, "Tier", 6);
		VariableManager.Instance.SetVariable(ObjectType.TopTShirtShow, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.TopLumberjack, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopDungarees, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopAdventurer, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.TopMac, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopPlumber, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopTree, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopDungareesClown, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopJumper02, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.TopApron, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.TopSanta, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopWally, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.TopTShirt02, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.TopFox, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopDinosaur, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopBunny, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopDuck, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.TopPoncho, "MaxUsage", 1000);
		VariableManager.Instance.SetVariable(ObjectType.TopJumper, "MaxUsage", 10000);
		VariableManager.Instance.SetVariable(ObjectType.TopJacket, "MaxUsage", 100000);
		VariableManager.Instance.SetVariable(ObjectType.TopBlazer, "MaxUsage", 1000000);
		VariableManager.Instance.SetVariable(ObjectType.TopTuxedo, "MaxUsage", 10000000);
		VariableManager.Instance.SetVariable(ObjectType.TopTunic, "MaxUsage", 1000);
		VariableManager.Instance.SetVariable(ObjectType.TopDress, "MaxUsage", 10000);
		VariableManager.Instance.SetVariable(ObjectType.TopShirt, "MaxUsage", 100000);
		VariableManager.Instance.SetVariable(ObjectType.TopShirtTie, "MaxUsage", 1000000);
		VariableManager.Instance.SetVariable(ObjectType.TopGown, "MaxUsage", 10000000);
		VariableManager.Instance.SetVariable(ObjectType.TopToga, "MaxUsage", 1000);
		VariableManager.Instance.SetVariable(ObjectType.TopRobe, "MaxUsage", 10000);
		VariableManager.Instance.SetVariable(ObjectType.TopCoat, "MaxUsage", 100000);
		VariableManager.Instance.SetVariable(ObjectType.TopCoatScarf, "MaxUsage", 1000000);
		VariableManager.Instance.SetVariable(ObjectType.TopSuit, "MaxUsage", 10000000);
		VariableManager.Instance.SetVariable(ObjectType.TopTShirtShow, "MaxUsage", 10000);
		VariableManager.Instance.SetVariable(ObjectType.TopLumberjack, "MaxUsage", 100000);
		VariableManager.Instance.SetVariable(ObjectType.TopDungarees, "MaxUsage", 100000);
		VariableManager.Instance.SetVariable(ObjectType.TopAdventurer, "MaxUsage", 10000);
		VariableManager.Instance.SetVariable(ObjectType.TopMac, "MaxUsage", 100000);
		VariableManager.Instance.SetVariable(ObjectType.TopPlumber, "MaxUsage", 100000);
		VariableManager.Instance.SetVariable(ObjectType.TopTree, "MaxUsage", 100000);
		VariableManager.Instance.SetVariable(ObjectType.TopDungareesClown, "MaxUsage", 100000);
		VariableManager.Instance.SetVariable(ObjectType.TopJumper02, "MaxUsage", 10000);
		VariableManager.Instance.SetVariable(ObjectType.TopApron, "MaxUsage", 10000);
		VariableManager.Instance.SetVariable(ObjectType.TopSanta, "MaxUsage", 100000);
		VariableManager.Instance.SetVariable(ObjectType.TopWally, "MaxUsage", 10000);
		VariableManager.Instance.SetVariable(ObjectType.TopTShirt02, "MaxUsage", 10000);
		VariableManager.Instance.SetVariable(ObjectType.TopFox, "MaxUsage", 100000);
		VariableManager.Instance.SetVariable(ObjectType.TopDinosaur, "MaxUsage", 100000);
		VariableManager.Instance.SetVariable(ObjectType.TopBunny, "MaxUsage", 100000);
		VariableManager.Instance.SetVariable(ObjectType.TopDuck, "MaxUsage", 100000);
		VariableManager.Instance.SetVariable("FirstToyTier", 3);
		VariableManager.Instance.SetVariable(ObjectType.Doll, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.JackInTheBox, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.DollHouse, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.Spaceship, "Tier", 6);
		VariableManager.Instance.SetVariable(ObjectType.ToyHorse, "Tier", 3);
		VariableManager.Instance.SetVariable(ObjectType.ToyHorseCart, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.ToyHorseCarriage, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.ToyTrain, "Tier", 6);
		VariableManager.Instance.SetVariable(ObjectType.Doll, "MaxUsage", 10000);
		VariableManager.Instance.SetVariable(ObjectType.JackInTheBox, "MaxUsage", 100000);
		VariableManager.Instance.SetVariable(ObjectType.DollHouse, "MaxUsage", 1000000);
		VariableManager.Instance.SetVariable(ObjectType.Spaceship, "MaxUsage", 10000000);
		VariableManager.Instance.SetVariable(ObjectType.ToyHorse, "MaxUsage", 10000);
		VariableManager.Instance.SetVariable(ObjectType.ToyHorseCart, "MaxUsage", 100000);
		VariableManager.Instance.SetVariable(ObjectType.ToyHorseCarriage, "MaxUsage", 1000000);
		VariableManager.Instance.SetVariable(ObjectType.ToyTrain, "MaxUsage", 10000000);
		VariableManager.Instance.SetVariable("FirstMedicineTier", 4);
		VariableManager.Instance.SetVariable(ObjectType.MedicineLeeches, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.MedicineLeeches, "Weight", 8);
		VariableManager.Instance.SetVariable(ObjectType.MedicineLeeches, "MaxUsage", 100000);
		VariableManager.Instance.SetVariable(ObjectType.MedicineFlowers, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.MedicineFlowers, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.MedicineFlowers, "MaxUsage", 1000000);
		VariableManager.Instance.SetVariable(ObjectType.MedicinePills, "Tier", 6);
		VariableManager.Instance.SetVariable(ObjectType.MedicinePills, "Weight", 16);
		VariableManager.Instance.SetVariable(ObjectType.MedicinePills, "MaxUsage", 10000000);
		VariableManager.Instance.SetVariable("FirstEducationTier", 5);
		VariableManager.Instance.SetVariable(ObjectType.EducationBook1, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.EducationBook1, "Weight", 12);
		VariableManager.Instance.SetVariable(ObjectType.EducationBook1, "MaxUsage", 1000000);
		VariableManager.Instance.SetVariable(ObjectType.EducationEncyclopedia, "Tier", 6);
		VariableManager.Instance.SetVariable(ObjectType.EducationEncyclopedia, "Weight", 16);
		VariableManager.Instance.SetVariable(ObjectType.EducationEncyclopedia, "MaxUsage", 10000000);
		VariableManager.Instance.SetVariable(ObjectType.Ink, "Weight", 4);
		VariableManager.Instance.SetVariable(ObjectType.Paper, "Weight", 4);
		VariableManager.Instance.SetVariable("FirstArtTier", 6);
		VariableManager.Instance.SetVariable(ObjectType.ArtPortrait, "Tier", 6);
		VariableManager.Instance.SetVariable(ObjectType.ArtPortrait, "Weight", 16);
		VariableManager.Instance.SetVariable(ObjectType.ArtPortrait, "MaxUsage", 10000000);
		VariableManager.Instance.SetVariable(ObjectType.ArtStillLife, "Tier", 6);
		VariableManager.Instance.SetVariable(ObjectType.ArtStillLife, "Weight", 16);
		VariableManager.Instance.SetVariable(ObjectType.ArtStillLife, "MaxUsage", 10000000);
		VariableManager.Instance.SetVariable(ObjectType.ArtAbstract, "Tier", 6);
		VariableManager.Instance.SetVariable(ObjectType.ArtAbstract, "Weight", 16);
		VariableManager.Instance.SetVariable(ObjectType.ArtAbstract, "MaxUsage", 10000000);
		VariableManager.Instance.SetVariable(ObjectType.Canvas, "Weight", 2);
		VariableManager.Instance.SetVariable(ObjectType.AnimalCow, "MaxFullTime", 60);
		VariableManager.Instance.SetVariable(ObjectType.AnimalSheep, "MaxFullTime", 60);
		VariableManager.Instance.SetVariable(ObjectType.AnimalCowHighland, "MaxFullTime", 60);
		VariableManager.Instance.SetVariable(ObjectType.AnimalAlpaca, "MaxFullTime", 60);
		VariableManager.Instance.SetVariable(ObjectType.MushroomPieRaw, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.BerriesPieRaw, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.FishPieRaw, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.ApplePieRaw, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinPieRaw, "Tier", 4);
		VariableManager.Instance.SetVariable(ObjectType.BerriesCakeRaw, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.AppleCakeRaw, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.BreadPuddingRaw, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.AppleBerryPieRaw, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.PumpkinMushroomPieRaw, "Tier", 5);
		VariableManager.Instance.SetVariable(ObjectType.Folk, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.Worker, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.Water, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.Milk, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.Honey, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.SeaWater, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.Sand, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.Soil, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.Mortar, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.Weed, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.Grass, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropWheat, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropCotton, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropCarrot, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.TreePine, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.TreeApple, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.TreeCoconut, "Unlocked", 1);
		VariableManager.Instance.SetVariable(ObjectType.TreeMulberry, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.TreeStump, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.CropPumpkin, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.Bush, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.Hedge, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.Mushroom, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.FlowerWild, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.Bullrushes, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.AnimalBird, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.AnimalBee, "Hidden", 1);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRod, "MinDelay", 4f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRod, "MaxDelay", 8f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRod, "UseRange", 5);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRodGood, "MinDelay", 4f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRodGood, "MaxDelay", 8f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRodGood, "UseRange", 10);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingStick, "FishChance", 20f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingStick, "FishChanceRare", 0f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingStick, "FishChanceSuperRare", 0f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingStick, "FishChanceBait", 40f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingStick, "FishChanceBaitRare", 0f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingStick, "FishChanceBaitSuperRare", 0f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRod, "FishChance", 40f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRod, "FishChanceRare", 0f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRod, "FishChanceSuperRare", 0f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRod, "FishChanceBait", 60f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRod, "FishChanceBaitRare", 1f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRod, "FishChanceBaitSuperRare", 0f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRodGood, "FishChance", 60f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRodGood, "FishChanceRare", 1f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRodGood, "FishChanceSuperRare", 0f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRodGood, "FishChanceBait", 80f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRodGood, "FishChanceBaitRare", 10f);
		VariableManager.Instance.SetVariable(ObjectType.ToolFishingRodGood, "FishChanceBaitSuperRare", 1f);
		VariableManager.Instance.AddVariable("ShallowNormalFreshFish", "FishSalmon");
		VariableManager.Instance.AddVariable("DeepNormalFreshFish", "FishSalmon");
		VariableManager.Instance.AddVariable("DeepRareFreshFish", "FishPerch");
		VariableManager.Instance.AddVariable("DeepSuperRareFreshFish", "FishCatFish");
		VariableManager.Instance.AddVariable("ShallowNormalSaltFish", "FishSalmon");
		VariableManager.Instance.AddVariable("DeepNormalSaltFish", "FishSalmon");
		VariableManager.Instance.AddVariable("DeepRareSaltFish", "FishOrangeRoughy");
		VariableManager.Instance.AddVariable("DeepSuperRareSaltFish", "FishMahiMahi");
		VariableManager.Instance.AddVariable("DeepRareFreshFish", "FishCarp");
		VariableManager.Instance.AddVariable("DeepSuperRareFreshFish", "FishGar");
		VariableManager.Instance.AddVariable("DeepRareSaltFish", "FishMonkfish");
		VariableManager.Instance.AddVariable("DeepSuperRareSaltFish", "FishMarlin");
		VariableManager.Instance.SetVariable(ObjectType.Triangle, "Sound", "InstrumentTriangle");
		VariableManager.Instance.SetVariable(ObjectType.Castanets, "Sound", "InstrumentCastanets");
		VariableManager.Instance.SetVariable(ObjectType.Cowbell, "Sound", "InstrumentCowbell");
		VariableManager.Instance.SetVariable(ObjectType.Guiro, "Sound", "InstrumentGuiro");
		VariableManager.Instance.SetVariable(ObjectType.Maracas, "Sound", "InstrumentMaracas");
		VariableManager.Instance.SetVariable(ObjectType.JawHarp, "Sound", "InstrumentJawHarp");
		VariableManager.Instance.SetVariable(ObjectType.Guitar, "Sound", "InstrumentGuitar");
		VariableManager.Instance.SetVariable(ObjectType.HayBale, "MaxEats", 10);
		VariableManager.Instance.SetVariable(ObjectType.Boulder, "MaxMined", 20);
		VariableManager.Instance.SetVariable(ObjectType.TallBoulder, "MaxMined1", 20);
		VariableManager.Instance.SetVariable(ObjectType.TallBoulder, "MaxMined2", 30);
		VariableManager.Instance.SetVariable(ObjectType.TallBoulder, "MaxMined3", 40);
		VariableManager.Instance.SetVariable(ObjectType.PotClay, "MaxUsage", 5);
		VariableManager.Instance.SetVariable(ObjectType.LargeBowlClay, "MaxUsage", 5);
		VariableManager.Instance.SetVariable(ObjectType.JarClay, "MaxUsage", 1);
		VariableManager.Instance.SetVariable("CrudeStoneBlockCost", 10);
		VariableManager.Instance.SetVariable(ObjectType.Sign, "Range", 16);
		VariableManager.Instance.SetVariable(ObjectType.Sign2, "Range", 16);
		VariableManager.Instance.SetVariable(ObjectType.Sign3, "Range", 35);
		VariableManager.Instance.SetVariable(ObjectType.Billboard, "Range", 20);
		VariableManager.Instance.SetVariable(ObjectType.AnimalSilkworm, "ConversionDelay", 10f);
	}
}
