namespace Synty.SidekickCharacters.Enums
{
	public enum CharacterPartType
	{
		Head = 1,
		Hair = 2,
		EyebrowLeft = 3,
		EyebrowRight = 4,
		EyeLeft = 5,
		EyeRight = 6,
		EarLeft = 7,
		EarRight = 8,
		FacialHair = 9,
		Torso = 10,
		ArmUpperLeft = 11,
		ArmUpperRight = 12,
		ArmLowerLeft = 13,
		ArmLowerRight = 14,
		HandLeft = 15,
		HandRight = 16,
		Hips = 17,
		LegLeft = 18,
		LegRight = 19,
		FootLeft = 20,
		FootRight = 21,
		AttachmentHead = 22,
		AttachmentFace = 23,
		AttachmentBack = 24,
		AttachmentHipsFront = 25,
		AttachmentHipsBack = 26,
		AttachmentHipsLeft = 27,
		AttachmentHipsRight = 28,
		AttachmentShoulderLeft = 29,
		AttachmentShoulderRight = 30,
		AttachmentElbowLeft = 31,
		AttachmentElbowRight = 32,
		AttachmentKneeLeft = 33,
		AttachmentKneeRight = 34,
		Nose = 35,
		Teeth = 36,
		Tongue = 37,
		Wrap = 38
	}
}
