namespace Synty.SidekickCharacters.Enums
{
	public enum ColorPartType
	{
		AllParts = 0,
		Species = 1,
		Outfit = 2,
		Attachments = 3,
		Materials = 4,
		Elements = 5,
		CharacterHead = 6,
		CharacterUpperBody = 7,
		CharacterLowerBody = 8,
		Head = 9,
		Hair = 10,
		EyebrowLeft = 11,
		EyebrowRight = 12,
		EyeLeft = 13,
		EyeRight = 14,
		EarLeft = 15,
		EarRight = 16,
		FacialHair = 17,
		Torso = 18,
		ArmUpperLeft = 19,
		ArmUpperRight = 20,
		ArmLowerLeft = 21,
		ArmLowerRight = 22,
		HandLeft = 23,
		HandRight = 24,
		Hips = 25,
		LegLeft = 26,
		LegRight = 27,
		FootLeft = 28,
		FootRight = 29,
		AttachmentHead = 30,
		AttachmentFace = 31,
		AttachmentBack = 32,
		AttachmentHipsFront = 33,
		AttachmentHipsBack = 34,
		AttachmentHipsLeft = 35,
		AttachmentHipsRight = 36,
		AttachmentShoulderLeft = 37,
		AttachmentShoulderRight = 38,
		AttachmentElbowLeft = 39,
		AttachmentElbowRight = 40,
		AttachmentKneeLeft = 41,
		AttachmentKneeRight = 42,
		Nose = 43,
		Teeth = 44,
		Tongue = 45,
		Wrap = 46
	}
}
