<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MoreMountains.Feedbacks.NiceVibrations</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Lofelt.NiceVibrations">
      <HintPath>..\..\Assemblies\Lofelt.NiceVibrations.dll</HintPath>
    </Reference>
    <Reference Include="MoreMountains.Feedbacks">
      <HintPath>..\..\Assemblies\MoreMountains.Feedbacks.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>