namespace Rewired
{
	[CustomObfuscation(rename = false)]
	internal enum InputPlatform
	{
		CxIBFsnaOMTSettXyfvwFIXcUdA = 0,
		LVWvrxQsAqeVkjNRwnuKIXNmUpb = 1,
		tMjFoInTdjUdFsuvBdkJykAOcxK = 2,
		jrnFQnITnGfYJNGJRNiKSjWmCIN = 3,
		uyyCuFFGfWXjTVaxBDjdJkTZQbyH = 4,
		wqLNeLjtHtVluXnZTJwGzgQjorp = 5,
		SEOqTpQSfePVCDAYtbxjiPuQrCI = 6,
		pxovqkpZvuHNCmiViTgMQLMwwHI = 7,
		yVbNNtreuNSZwnPKmvggSbNcobE = 8,
		lpwwOMUqLQXOtUNfuiBPhnLwSonE = 9,
		jVmfTNFtgoyNIJsZvTaEJhTeMwM = 10,
		IhaMKnCTbEIKQXWdGDxNCIjTkBY = 11,
		qrGUjOYIhrHekXCSfwpijqVuKox = 12,
		WeNdtmCQIExDgJkCoDLQpTBhNuuA = 13,
		xBhiVUoBMExsSwpiclFcBlxedyD = 14,
		QXUdlJbFXtBMbcsQrkVUBjacRYF = 15,
		PWSyuDmlNRtIDqcfbUdkiPiBKnJ = 16,
		SozjCSEUdqKUAOrSbOkERpTFYUM = 17,
		wXNiNZooHoUdeIOblemSQxFvgku = 18,
		tupteVOnTotMWcaGSTKHjCDgaod = 19,
		SpQEtAgXFFDOVgbUYmjrNgVoefPl = 20,
		cHAuJKinokTlVFkxsepriQlefVs = 21,
		UvVEGkUkChajfkvZxKAoXPsCfyv = 22,
		dGfqJONDIELvIIawBjEeWdmrgHL = 23,
		smeSBEZPrdMxQWGfufzvyMpGsaD = 24,
		otOkfjhuDYihdlQWCVdXkltPtFH = 25,
		uPuBOBVhbURNcWzCBfNiRgIRgZU = 26,
		bZxcHpZATnVAaWHfixkPHBnwnyh = 27,
		aAEdsOEBVaLVplFMjkUFGCXqhZQ = 28,
		oIytUlfPdeYEHJmYzpVercdqpuJ = 29,
		hgCkNzqqeApugcykJkWRyoRcehu = 30,
		EWZbFSlhmVoPEpBgVdJUImDNSFs = 31,
		czpOAhqnclCbiROXDeDoOccchYf = 32,
		qfGFMgITFjAOeJxlUgLrRJwBPtRC = 33,
		RcnaIBEzPhyzJrntOCQgWpPtTwx = 34,
		NWLeGVMpwYQrycduyLxSAFfLdRo = 35,
		ztGaXYrZUAGOJsEfXRsYwkwVeDN = 36,
		HzEUSSCMOAGDmIPBhFeSCXxGOclT = 37,
		CCNmvMENYvDMTItbpchmkUhftQp = 38,
		dVsSGeiWnJmFCqnHjRhmoOxXKea = 39,
		zleeezFbWVDWxafXfIqdeXeBCfCg = 40,
		WHguuYtSPLUAdmGmSVxDSpOFIRr = 41,
		YwSzYyKIymjNIVPIuVTjNuHOToA = 42
	}
}
