namespace Brewery.Quest
{
	public enum QuestEventType
	{
		None = 0,
		MapOpened = 1,
		MapClosed = 2,
		MapLocationHovered = 3,
		TradeCompleted = 4,
		TradedWithNPC = 5,
		StationStepCompleted = 6,
		StationUsed = 7,
		BoilingStarted = 8,
		FermentationStarted = 9,
		BrewingCompleted = 10,
		TalkedToNPC = 11,
		EnemyKilled = 12,
		ItemPickedUp = 13,
		ItemCollected = 14,
		ItemCrafted = 15,
		ItemSold = 16,
		ItemDelivered = 17,
		ShopItemPurchased = 18,
		ItemPlacedOnShelf = 19,
		BottlingCompleted = 20,
		BarPurchased = 21,
		BarInventoryOpened = 22,
		ItemAddedToCrate = 23,
		ItemAddedToVehicle = 24,
		VehicleEntered = 25,
		StationTabOpened = 26,
		StationItemLoaded = 27,
		BoilingConvertStarted = 28,
		BoilingConvertCompleted = 29,
		BoilingSterilizeStarted = 30,
		BoilingSterilizeCompleted = 31,
		BoilingCooldownStarted = 32,
		BoilingCooldownCompleted = 33,
		BoilingYeastPitched = 34,
		CornGrinderOutputCollected = 35,
		BoilingOutputCollected = 36,
		ItemDropped = 37,
		InventoryItemHovered = 38,
		ZoneEntered = 39,
		Custom = 40,
		StandZoneEntered = 41,
		StandInventoryOpened = 42,
		StandItemDeposited = 43,
		StandOpened = 44,
		StandSaleCompleted = 45,
		StandUpgradePurchased = 46,
		QuestChainCompleted = 47,
		StandClosed = 48,
		QuestChainAccepted = 49,
		CatalystApplied = 50
	}
}
