<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Coherence.Serializer</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Coherence.Entities">
      <HintPath>..\..\Assemblies\Coherence.Entities.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.SimulationFrame">
      <HintPath>..\..\Assemblies\Coherence.SimulationFrame.dll</HintPath>
    </Reference>
    <Reference Include="System.Numerics" />
    <Reference Include="Coherence.ProtocolDef">
      <HintPath>..\..\Assemblies\Coherence.ProtocolDef.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Brook">
      <HintPath>..\..\Assemblies\Coherence.Brook.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Log">
      <HintPath>..\..\Assemblies\Coherence.Log.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Common">
      <HintPath>..\..\Assemblies\Coherence.Common.dll</HintPath>
    </Reference>
    <Reference Include="Coherence.Cram">
      <HintPath>..\..\Assemblies\Coherence.Cram.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>