internal class URUqgJYVEGsJrTTZacgCSjzPllKh : cfLjOhjLYeBVSqIGSwIBARCebRsBb
{
	protected readonly EsuVeemXUvWofQMkRaJhZlyFnkvC gxIFldXPTVTCluaLveAAOEnwCGZjA;

	private readonly string XOuOcJpenNYfRqGsObOHsGqruLCS;

	private readonly string ABSqftSYBQjAYaihZfrTItmQDyHGA;

	private string KAxDvhoHDvdkVfrnNDNreLqkxdDfb;

	private readonly string HSHQwkNRBZzjfOBufznAOccBgtsJ;

	private int APxbGXWgDxpHCnFmRAeuoPpEFmye;

	public EsuVeemXUvWofQMkRaJhZlyFnkvC BUDOLyXwAKroHfNFKOjXKbCSzlYf => null;

	string cfLjOhjLYeBVSqIGSwIBARCebRsBb.keyCategory => null;

	string cfLjOhjLYeBVSqIGSwIBARCebRsBb.scriptingName => null;

	string cfLjOhjLYeBVSqIGSwIBARCebRsBb.nonLocalizedDescriptiveName
	{
		get
		{
			return null;
		}
		set
		{
		}
	}

	string cfLjOhjLYeBVSqIGSwIBARCebRsBb.key => null;

	int cfLjOhjLYeBVSqIGSwIBARCebRsBb.autoGeneratedValueFlags
	{
		get
		{
			return 0;
		}
		set
		{
		}
	}

	public string keyCategory => null;

	public string scriptingName => null;

	public string iKFEMKcXEVbvGRfWxSuYJGNPcuSgA => null;

	public string nonLocalizedDescriptiveName => null;

	public string key => null;

	public URUqgJYVEGsJrTTZacgCSjzPllKh(EsuVeemXUvWofQMkRaJhZlyFnkvC P_0, string P_1, string P_2, string P_3, string P_4)
	{
	}

	public virtual bool QsHtWxfjoPQQqCMviXqRrkdauffq(URUqgJYVEGsJrTTZacgCSjzPllKh P_0, bool P_1)
	{
		return false;
	}
}
