using System;
using Rewired;
using Rewired.Internal.Glyphs;
using Rewired.Internal.Localization;

internal abstract class NmOuKbGbUrCRsVFvWatfJvTwnsgEb : CnLKLdvrkwwcGfIoKweJxFIiKujS
{
	protected readonly KeyedGlyph YJZaGzNbenFIGCXFHBLMEfjmmqVfA;

	protected readonly KeyedGlyph HWKojdCWSVBlwTrDJvmOfFhEaVec;

	public abstract object EBxaYzPLdxoxLqFaNNMWpbWdpkgR { get; }

	public abstract object YeRcGxxxJJipYymqMgCYYEGVveXO { get; }

	public abstract string wYCljqJRutqoTlDqRfxkTLpvwHBU { get; }

	public abstract string tEWSURZAlPhPJAgqSaWlcYfzQVGEb { get; }

	protected NmOuKbGbUrCRsVFvWatfJvTwnsgEb(jjEiJGkdrKfqxJAsceTeoFkgoNMlA.AqybaYFDSFEDwBRnsokwpBTdIblQ P_0, jjEiJGkdrKfqxJAsceTeoFkgoNMlA.veVjxECKraSLRuRJUJeBWprfCtQDb P_1)
		: base(P_0, P_1)
	{
		YJZaGzNbenFIGCXFHBLMEfjmmqVfA = new KeyedGlyph();
		HWKojdCWSVBlwTrDJvmOfFhEaVec = new KeyedGlyph();
	}

	protected NmOuKbGbUrCRsVFvWatfJvTwnsgEb(ZhCqPBFhNKEpWHuMwXbLVCWahcjab P_0, jjEiJGkdrKfqxJAsceTeoFkgoNMlA.AqybaYFDSFEDwBRnsokwpBTdIblQ P_1, jjEiJGkdrKfqxJAsceTeoFkgoNMlA.veVjxECKraSLRuRJUJeBWprfCtQDb P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
		YJZaGzNbenFIGCXFHBLMEfjmmqVfA = new KeyedGlyph();
		HWKojdCWSVBlwTrDJvmOfFhEaVec = new KeyedGlyph();
	}

	protected virtual void AheIkoNSuPQptxpFnxrwMzfNmTwB()
	{
		GyvVuNpmOrQDAjpmjMcKZjKXHjHx();
	}

	public virtual void QQQBFnsupsawqiEDOmrVemSlbcVHb(ZhCqPBFhNKEpWHuMwXbLVCWahcjab P_0)
	{
		wrVdvyaMppSpOxPfMIMhdQJhfgZHA(P_0);
	}

	public virtual void AKROQamdJYPqGQAXORfuQGZVQyLR(vfRBokPaPPEWJRenHDjJaOGZJkR P_0)
	{
		base.wrVdvyaMppSpOxPfMIMhdQJhfgZHA(P_0);
		if (!(P_0 is ZhCqPBFhNKEpWHuMwXbLVCWahcjab))
		{
			throw new ArgumentException("value must implement " + typeof(ZhCqPBFhNKEpWHuMwXbLVCWahcjab));
		}
	}

	public virtual void SRlJeDNOLQgBKpUiKcEzHpemJJcVA()
	{
		gJuABohBdpRbYcPPGjzZMkOBbNcFe();
		YJZaGzNbenFIGCXFHBLMEfjmmqVfA.Clear();
		HWKojdCWSVBlwTrDJvmOfFhEaVec.Clear();
	}

	public void QMixFKFegiphgopTygHNWVEAdkfi()
	{
		YJZaGzNbenFIGCXFHBLMEfjmmqVfA.Clear();
		RCnuQGEZevjVGhQRlnERuzInQmqe(jjEiJGkdrKfqxJAsceTeoFkgoNMlA.QtSxnZYSjrgthBpvYZqvQdRfKXUE.Keys);
	}

	public void DttKrOmTKKJSYPPobmuhCulHvSMR()
	{
		HWKojdCWSVBlwTrDJvmOfFhEaVec.Clear();
		RCnuQGEZevjVGhQRlnERuzInQmqe(jjEiJGkdrKfqxJAsceTeoFkgoNMlA.QtSxnZYSjrgthBpvYZqvQdRfKXUE.Keys);
	}

	public virtual bool qLLIDftymAfNuspeQYWEOMktjvNm(tSkGCPxidsRshBOpBnQicfGGOeto P_0)
	{
		if (!(P_0 is NmOuKbGbUrCRsVFvWatfJvTwnsgEb nmOuKbGbUrCRsVFvWatfJvTwnsgEb))
		{
			return false;
		}
		if (!mlqZuQkYZfHtGHypfzSZjaiiOeHG(P_0))
		{
			return false;
		}
		ZhCqPBFhNKEpWHuMwXbLVCWahcjab zhCqPBFhNKEpWHuMwXbLVCWahcjab = mzXBcOhkqTjtfkPHecVQelrGTOWnA();
		ZhCqPBFhNKEpWHuMwXbLVCWahcjab zhCqPBFhNKEpWHuMwXbLVCWahcjab2 = nmOuKbGbUrCRsVFvWatfJvTwnsgEb.mzXBcOhkqTjtfkPHecVQelrGTOWnA();
		if (zhCqPBFhNKEpWHuMwXbLVCWahcjab == null != (zhCqPBFhNKEpWHuMwXbLVCWahcjab2 == null))
		{
			return false;
		}
		if (zhCqPBFhNKEpWHuMwXbLVCWahcjab != null && (!string.Equals(zhCqPBFhNKEpWHuMwXbLVCWahcjab.positiveKey, zhCqPBFhNKEpWHuMwXbLVCWahcjab2.positiveKey, StringComparison.Ordinal) || !string.Equals(zhCqPBFhNKEpWHuMwXbLVCWahcjab.negativeKey, zhCqPBFhNKEpWHuMwXbLVCWahcjab2.negativeKey, StringComparison.Ordinal)))
		{
			return false;
		}
		return true;
	}

	protected virtual void lhndkhDsNwibnjEuYZmFDIvhISMlA()
	{
		CHyiRkqsEJpAPoRxIgWYILFdOSfm();
		YJZaGzNbenFIGCXFHBLMEfjmmqVfA.Clear();
		HWKojdCWSVBlwTrDJvmOfFhEaVec.Clear();
	}

	protected virtual void BFwyvGFSJiQjpImPpkAulUdtLMOQ(jjEiJGkdrKfqxJAsceTeoFkgoNMlA.QtSxnZYSjrgthBpvYZqvQdRfKXUE P_0)
	{
		base.RCnuQGEZevjVGhQRlnERuzInQmqe(P_0);
		ZhCqPBFhNKEpWHuMwXbLVCWahcjab zhCqPBFhNKEpWHuMwXbLVCWahcjab = mzXBcOhkqTjtfkPHecVQelrGTOWnA();
		if (zhCqPBFhNKEpWHuMwXbLVCWahcjab == null || string.IsNullOrEmpty(zhCqPBFhNKEpWHuMwXbLVCWahcjab.key))
		{
			return;
		}
		if ((zhCqPBFhNKEpWHuMwXbLVCWahcjab.autoGeneratedValueFlags & 8) == 0 && string.IsNullOrEmpty(zhCqPBFhNKEpWHuMwXbLVCWahcjab.positiveKey) && JCMiKjadAGCFMgoYjEfWSrwDjadme(Pole.Positive))
		{
			zhCqPBFhNKEpWHuMwXbLVCWahcjab.positiveKey = zhCqPBFhNKEpWHuMwXbLVCWahcjab.key;
			if (bhpLJQXUotIbjWPzfIwAYHvLSCah(Pole.Positive))
			{
				zhCqPBFhNKEpWHuMwXbLVCWahcjab.positiveKey = LocalizationManager.AppendToKeyAxisPole(zhCqPBFhNKEpWHuMwXbLVCWahcjab.positiveKey, Pole.Positive);
			}
			zhCqPBFhNKEpWHuMwXbLVCWahcjab.autoGeneratedValueFlags |= 8;
			khJGmLkqmPYzNLVRuANYwNIWGmgd(8);
		}
		if ((zhCqPBFhNKEpWHuMwXbLVCWahcjab.autoGeneratedValueFlags & 0x10) == 0 && string.IsNullOrEmpty(zhCqPBFhNKEpWHuMwXbLVCWahcjab.negativeKey) && JCMiKjadAGCFMgoYjEfWSrwDjadme(Pole.Negative))
		{
			zhCqPBFhNKEpWHuMwXbLVCWahcjab.negativeKey = zhCqPBFhNKEpWHuMwXbLVCWahcjab.key;
			if (bhpLJQXUotIbjWPzfIwAYHvLSCah(Pole.Negative))
			{
				zhCqPBFhNKEpWHuMwXbLVCWahcjab.negativeKey = LocalizationManager.AppendToKeyAxisPole(zhCqPBFhNKEpWHuMwXbLVCWahcjab.negativeKey, Pole.Negative);
			}
			zhCqPBFhNKEpWHuMwXbLVCWahcjab.autoGeneratedValueFlags |= 16;
			khJGmLkqmPYzNLVRuANYwNIWGmgd(16);
		}
	}

	protected virtual void ttmeEAglpQClUKUsDQTAEcgbaWdKA(jjEiJGkdrKfqxJAsceTeoFkgoNMlA.oTYnvuyaZmGssrtKlgjPUrEEwolk P_0)
	{
		base.XHzbXuCXybtTHzrgGGfkFjJcNcteA(P_0);
		ZhCqPBFhNKEpWHuMwXbLVCWahcjab zhCqPBFhNKEpWHuMwXbLVCWahcjab = mzXBcOhkqTjtfkPHecVQelrGTOWnA();
		if (zhCqPBFhNKEpWHuMwXbLVCWahcjab != null && ((uint)zhCqPBFhNKEpWHuMwXbLVCWahcjab.autoGeneratedValueFlags & (uint)P_0) != 0)
		{
			if ((P_0 & jjEiJGkdrKfqxJAsceTeoFkgoNMlA.oTYnvuyaZmGssrtKlgjPUrEEwolk.PositiveKey) != jjEiJGkdrKfqxJAsceTeoFkgoNMlA.oTYnvuyaZmGssrtKlgjPUrEEwolk.None && (zhCqPBFhNKEpWHuMwXbLVCWahcjab.autoGeneratedValueFlags & 8) != 0)
			{
				zhCqPBFhNKEpWHuMwXbLVCWahcjab.positiveKey = null;
				khJGmLkqmPYzNLVRuANYwNIWGmgd(8);
				zhCqPBFhNKEpWHuMwXbLVCWahcjab.autoGeneratedValueFlags &= -9;
			}
			if ((P_0 & jjEiJGkdrKfqxJAsceTeoFkgoNMlA.oTYnvuyaZmGssrtKlgjPUrEEwolk.NegativeKey) != jjEiJGkdrKfqxJAsceTeoFkgoNMlA.oTYnvuyaZmGssrtKlgjPUrEEwolk.None && (zhCqPBFhNKEpWHuMwXbLVCWahcjab.autoGeneratedValueFlags & 0x10) != 0)
			{
				zhCqPBFhNKEpWHuMwXbLVCWahcjab.negativeKey = null;
				khJGmLkqmPYzNLVRuANYwNIWGmgd(16);
				zhCqPBFhNKEpWHuMwXbLVCWahcjab.autoGeneratedValueFlags &= -17;
			}
		}
	}

	protected virtual jjEiJGkdrKfqxJAsceTeoFkgoNMlA.oTYnvuyaZmGssrtKlgjPUrEEwolk QfRdmNmbmYaWBGoqchawzbKSrtAL(jjEiJGkdrKfqxJAsceTeoFkgoNMlA.QtSxnZYSjrgthBpvYZqvQdRfKXUE P_0)
	{
		jjEiJGkdrKfqxJAsceTeoFkgoNMlA.oTYnvuyaZmGssrtKlgjPUrEEwolk oTYnvuyaZmGssrtKlgjPUrEEwolk = base.iAYJjunKxgfxQgfzQTqMbfKBuIJqA(P_0);
		if ((P_0 & jjEiJGkdrKfqxJAsceTeoFkgoNMlA.QtSxnZYSjrgthBpvYZqvQdRfKXUE.Keys) != jjEiJGkdrKfqxJAsceTeoFkgoNMlA.QtSxnZYSjrgthBpvYZqvQdRfKXUE.None)
		{
			oTYnvuyaZmGssrtKlgjPUrEEwolk |= (jjEiJGkdrKfqxJAsceTeoFkgoNMlA.oTYnvuyaZmGssrtKlgjPUrEEwolk)24;
		}
		return oTYnvuyaZmGssrtKlgjPUrEEwolk;
	}

	protected ZhCqPBFhNKEpWHuMwXbLVCWahcjab mzXBcOhkqTjtfkPHecVQelrGTOWnA()
	{
		return SCQsEZHFBGaOGHdrLNaADiCIdlJUB() as ZhCqPBFhNKEpWHuMwXbLVCWahcjab;
	}

	protected virtual bool bhpLJQXUotIbjWPzfIwAYHvLSCah(Pole P_0)
	{
		return base.EBtqAXtODeZFPNkhxWrjaFttagr switch
		{
			jjEiJGkdrKfqxJAsceTeoFkgoNMlA.AqybaYFDSFEDwBRnsokwpBTdIblQ.Axis => true, 
			jjEiJGkdrKfqxJAsceTeoFkgoNMlA.AqybaYFDSFEDwBRnsokwpBTdIblQ.Button => false, 
			_ => false, 
		};
	}

	protected virtual bool JCMiKjadAGCFMgoYjEfWSrwDjadme(Pole P_0)
	{
		return base.EBtqAXtODeZFPNkhxWrjaFttagr switch
		{
			jjEiJGkdrKfqxJAsceTeoFkgoNMlA.AqybaYFDSFEDwBRnsokwpBTdIblQ.Axis => true, 
			jjEiJGkdrKfqxJAsceTeoFkgoNMlA.AqybaYFDSFEDwBRnsokwpBTdIblQ.Button => P_0 switch
			{
				Pole.Positive => true, 
				Pole.Negative => false, 
				_ => false, 
			}, 
			_ => false, 
		};
	}

	protected virtual void xJDlOIJDoOftwrNjHcuPCUJVohHhb()
	{
		base.DvBuhkbmxtOGnvpgTZDWNzIWvVT();
		_ = EBxaYzPLdxoxLqFaNNMWpbWdpkgR;
		_ = YeRcGxxxJJipYymqMgCYYEGVveXO;
	}

	protected virtual void MrMNxzCrLzBGdQqILlSvnjnJckiH()
	{
		bttZnJQoTaBSPdAchiSDHbcuJNXL();
		HOpcQSeuuNAfGMIjSqLRfSQlBZpmA(8, new dLGaeuATPVHVASryTWPoHITyuTipA
		{
			FAjCKlDimUZZNmVvyPdWiFiLMaeY = YJZaGzNbenFIGCXFHBLMEfjmmqVfA
		});
		HOpcQSeuuNAfGMIjSqLRfSQlBZpmA(16, new dLGaeuATPVHVASryTWPoHITyuTipA
		{
			FAjCKlDimUZZNmVvyPdWiFiLMaeY = HWKojdCWSVBlwTrDJvmOfFhEaVec
		});
	}
}
