using System;
using Rewired.Internal.Localization;

internal abstract class UALPDVwKlaWvzBmvcCkXuwKZFpdj : jjEiJGkdrKfqxJAsceTeoFkgoNMlA
{
	protected LocalizedString[] LncLyoofGJjkWktCWxMpDhEWRXph;

	public int iKMpMPYbCeMTYyywlDwWOMTGxkgI => jjEiJGkdrKfqxJAsceTeoFkgoNMlA.zIFHYKIYFbwXaLMpuqkDbbnkpdiD(base.LJXAbEKxmDHBiYmUZFbAJTxfIUxj, base.VsFDlKfYzzTTInlpCbOWcKKrmFZDA);

	public abstract string cQwbtPkKbuvPqNcLgcikLIlJcUUG(int P_0);

	protected UALPDVwKlaWvzBmvcCkXuwKZFpdj(AqybaYFDSFEDwBRnsokwpBTdIblQ P_0, veVjxECKraSLRuRJUJeBWprfCtQDb P_1)
		: base(P_0, P_1)
	{
	}

	protected UALPDVwKlaWvzBmvcCkXuwKZFpdj(DEOLSCnqecUoFqpsMneIWaoyXVqt P_0, AqybaYFDSFEDwBRnsokwpBTdIblQ P_1, veVjxECKraSLRuRJUJeBWprfCtQDb P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
	}

	protected virtual void BcebqtLXJwoXDcCvyFgokErhEnqu()
	{
		int num = iKMpMPYbCeMTYyywlDwWOMTGxkgI;
		LncLyoofGJjkWktCWxMpDhEWRXph = null;
		if (num > 0)
		{
			LncLyoofGJjkWktCWxMpDhEWRXph = new LocalizedString[num];
			for (int i = 0; i < num; i++)
			{
				LncLyoofGJjkWktCWxMpDhEWRXph[i] = new LocalizedString();
			}
		}
		ocwkkmZurlqfuKPEalGIqdmTGdXI();
	}

	public virtual void BSpSJRoWADGkpBSPdKJxtsrjeVjg(DEOLSCnqecUoFqpsMneIWaoyXVqt P_0)
	{
		robwaoxSKinucgPcyrfEovhcOMTl(P_0);
	}

	public virtual void GwpYNZfXUuECKOpiDQwnvmYAMVNb(LnhaMJXLiFbdSGpizhhMTtFDjtXy P_0)
	{
		base.robwaoxSKinucgPcyrfEovhcOMTl(P_0);
		if (!(P_0 is DEOLSCnqecUoFqpsMneIWaoyXVqt))
		{
			throw new ArgumentException("value must implement " + typeof(DEOLSCnqecUoFqpsMneIWaoyXVqt));
		}
	}

	public virtual void eQMOgLDUpQNEJXMnPMCsjRZlfQBY()
	{
		uogVoxebOaalYvSMFHpEhkktkqiEA();
	}

	public virtual void ZhSeyWorrKdBYmyHZLrGFawuvcxm()
	{
		URVTChhdPhlphEvyvsHKScBWvFun();
		if (LncLyoofGJjkWktCWxMpDhEWRXph != null)
		{
			for (int i = 0; i < iKMpMPYbCeMTYyywlDwWOMTGxkgI; i++)
			{
				LncLyoofGJjkWktCWxMpDhEWRXph[i].Clear();
			}
		}
	}

	public virtual bool NypQjVFPpZoXpmgEkjSHxNkebUBgA(xhsfjMHWBKokSPBLxdeojZhcJxoeA P_0, bool P_1)
	{
		if (!(P_0 is UALPDVwKlaWvzBmvcCkXuwKZFpdj uALPDVwKlaWvzBmvcCkXuwKZFpdj))
		{
			return false;
		}
		if (!buRpSpFySsnOwisfqOOesjuLfQTJ(P_0, P_1))
		{
			return false;
		}
		DEOLSCnqecUoFqpsMneIWaoyXVqt dEOLSCnqecUoFqpsMneIWaoyXVqt = vVErTYAbdFRRLfXjyMdwNEqFAmnGA();
		DEOLSCnqecUoFqpsMneIWaoyXVqt dEOLSCnqecUoFqpsMneIWaoyXVqt2 = uALPDVwKlaWvzBmvcCkXuwKZFpdj.vVErTYAbdFRRLfXjyMdwNEqFAmnGA();
		if (dEOLSCnqecUoFqpsMneIWaoyXVqt == null != (dEOLSCnqecUoFqpsMneIWaoyXVqt2 == null))
		{
			return false;
		}
		if (dEOLSCnqecUoFqpsMneIWaoyXVqt != null && P_1)
		{
			int num = iKMpMPYbCeMTYyywlDwWOMTGxkgI;
			for (int i = 0; i < num; i++)
			{
				if (!string.Equals(dEOLSCnqecUoFqpsMneIWaoyXVqt.GetSpecialElementKey(i), dEOLSCnqecUoFqpsMneIWaoyXVqt2.GetSpecialElementKey(i), StringComparison.Ordinal))
				{
					return false;
				}
				if (!string.Equals(dEOLSCnqecUoFqpsMneIWaoyXVqt.GetSpecialElementNonLocalizedDescriptiveName(i), dEOLSCnqecUoFqpsMneIWaoyXVqt2.GetSpecialElementNonLocalizedDescriptiveName(i), StringComparison.Ordinal))
				{
					return false;
				}
			}
		}
		return true;
	}

	protected virtual void dsxxbGaGuFaHFGkWaNbuoQWPsLKbA()
	{
		UMcCdLWmjevbDnqFgUwpyXSLsnWp();
		if (LncLyoofGJjkWktCWxMpDhEWRXph != null)
		{
			for (int i = 0; i < LncLyoofGJjkWktCWxMpDhEWRXph.Length; i++)
			{
				LncLyoofGJjkWktCWxMpDhEWRXph[i].Clear();
			}
		}
	}

	protected virtual void wSLUOhqWBzDdPgegrMpQdDSQDafT(QtSxnZYSjrgthBpvYZqvQdRfKXUE P_0)
	{
		base.ZkeNHOSKcvJlBczdcxBaeQXQJqfE(P_0);
		DEOLSCnqecUoFqpsMneIWaoyXVqt dEOLSCnqecUoFqpsMneIWaoyXVqt = vVErTYAbdFRRLfXjyMdwNEqFAmnGA();
		if (dEOLSCnqecUoFqpsMneIWaoyXVqt == null || string.IsNullOrEmpty(dEOLSCnqecUoFqpsMneIWaoyXVqt.key) || base.LJXAbEKxmDHBiYmUZFbAJTxfIUxj != AqybaYFDSFEDwBRnsokwpBTdIblQ.CompoundElement || !jjEiJGkdrKfqxJAsceTeoFkgoNMlA.BYUvlRLHXoZMeceCTjMMIYmbtBMmA(base.VsFDlKfYzzTTInlpCbOWcKKrmFZDA, out var pEZtEoWUXFickyhTPzxGMRoQswOL))
		{
			return;
		}
		for (int i = 0; i < pEZtEoWUXFickyhTPzxGMRoQswOL.PewIUhZMyGUcqMDJtzetvXdUpuqS; i++)
		{
			int num = 8388608 << i;
			if ((dEOLSCnqecUoFqpsMneIWaoyXVqt.autoGeneratedValueFlags & num) == 0 && !string.IsNullOrEmpty(dEOLSCnqecUoFqpsMneIWaoyXVqt.key) && string.IsNullOrEmpty(dEOLSCnqecUoFqpsMneIWaoyXVqt.GetSpecialElementKey(i)))
			{
				string text = dEOLSCnqecUoFqpsMneIWaoyXVqt.key;
				if (pEZtEoWUXFickyhTPzxGMRoQswOL.IaedbspyldSLenBPDisowZTAxgvk(i).XdrIyCHSvCOtelgsOknkTmjdPjQPA.HasValue)
				{
					text = LocalizationManager.AppendToKeyAxisDirection(text, pEZtEoWUXFickyhTPzxGMRoQswOL.IaedbspyldSLenBPDisowZTAxgvk(i).XdrIyCHSvCOtelgsOknkTmjdPjQPA.Value);
				}
				dEOLSCnqecUoFqpsMneIWaoyXVqt.SetSpecialElementKey(i, text);
				dEOLSCnqecUoFqpsMneIWaoyXVqt.autoGeneratedValueFlags |= num;
				yEJKXEtRylKddSbgoiIxUFVZUTMX(num);
			}
			int num2 = 16384 << i;
			if ((dEOLSCnqecUoFqpsMneIWaoyXVqt.autoGeneratedValueFlags & num2) == 0 && !string.IsNullOrEmpty(dEOLSCnqecUoFqpsMneIWaoyXVqt.nonLocalizedDescriptiveName) && string.IsNullOrEmpty(dEOLSCnqecUoFqpsMneIWaoyXVqt.GetSpecialElementNonLocalizedDescriptiveName(i)))
			{
				string text2 = dEOLSCnqecUoFqpsMneIWaoyXVqt.nonLocalizedDescriptiveName;
				if (pEZtEoWUXFickyhTPzxGMRoQswOL.IaedbspyldSLenBPDisowZTAxgvk(i).XdrIyCHSvCOtelgsOknkTmjdPjQPA.HasValue)
				{
					text2 = LocalizationManager.AppendToNameAxisDirection(text2, pEZtEoWUXFickyhTPzxGMRoQswOL.IaedbspyldSLenBPDisowZTAxgvk(i).XdrIyCHSvCOtelgsOknkTmjdPjQPA.Value);
				}
				dEOLSCnqecUoFqpsMneIWaoyXVqt.SetSpecialElementNonLocalizedDescriptiveName(i, text2);
				dEOLSCnqecUoFqpsMneIWaoyXVqt.autoGeneratedValueFlags |= num2;
				yEJKXEtRylKddSbgoiIxUFVZUTMX(num2);
			}
		}
	}

	protected virtual void WvSDjkZiHZuEWAvsEpOeHJhYHEfCA(oTYnvuyaZmGssrtKlgjPUrEEwolk P_0)
	{
		base.yDzbfaLEJphcSkTjzHYGsryjYvCjA(P_0);
		DEOLSCnqecUoFqpsMneIWaoyXVqt dEOLSCnqecUoFqpsMneIWaoyXVqt = vVErTYAbdFRRLfXjyMdwNEqFAmnGA();
		if (dEOLSCnqecUoFqpsMneIWaoyXVqt == null || ((uint)dEOLSCnqecUoFqpsMneIWaoyXVqt.autoGeneratedValueFlags & (uint)P_0) == 0 || base.LJXAbEKxmDHBiYmUZFbAJTxfIUxj != AqybaYFDSFEDwBRnsokwpBTdIblQ.CompoundElement || !jjEiJGkdrKfqxJAsceTeoFkgoNMlA.BYUvlRLHXoZMeceCTjMMIYmbtBMmA(base.VsFDlKfYzzTTInlpCbOWcKKrmFZDA, out var pEZtEoWUXFickyhTPzxGMRoQswOL))
		{
			return;
		}
		for (int i = 0; i < pEZtEoWUXFickyhTPzxGMRoQswOL.PewIUhZMyGUcqMDJtzetvXdUpuqS; i++)
		{
			int num = 8388608 << i;
			if ((dEOLSCnqecUoFqpsMneIWaoyXVqt.autoGeneratedValueFlags & num) != 0)
			{
				dEOLSCnqecUoFqpsMneIWaoyXVqt.SetSpecialElementKey(i, null);
				dEOLSCnqecUoFqpsMneIWaoyXVqt.autoGeneratedValueFlags &= ~num;
				yEJKXEtRylKddSbgoiIxUFVZUTMX(num);
			}
			int num2 = 16384 << i;
			if ((dEOLSCnqecUoFqpsMneIWaoyXVqt.autoGeneratedValueFlags & num2) != 0)
			{
				dEOLSCnqecUoFqpsMneIWaoyXVqt.SetSpecialElementNonLocalizedDescriptiveName(i, null);
				dEOLSCnqecUoFqpsMneIWaoyXVqt.autoGeneratedValueFlags &= ~num2;
				yEJKXEtRylKddSbgoiIxUFVZUTMX(num2);
			}
		}
	}

	protected virtual oTYnvuyaZmGssrtKlgjPUrEEwolk mGnDkSpDAKJMGZCrJvLcsyEFrrqA(QtSxnZYSjrgthBpvYZqvQdRfKXUE P_0)
	{
		oTYnvuyaZmGssrtKlgjPUrEEwolk oTYnvuyaZmGssrtKlgjPUrEEwolk = base.yaKwzIfaeqvJqzbBTjbIPAiLOtPd(P_0);
		int num = iKMpMPYbCeMTYyywlDwWOMTGxkgI;
		if ((P_0 & QtSxnZYSjrgthBpvYZqvQdRfKXUE.Keys) != QtSxnZYSjrgthBpvYZqvQdRfKXUE.None)
		{
			for (int i = 0; i < num; i++)
			{
				oTYnvuyaZmGssrtKlgjPUrEEwolk = (oTYnvuyaZmGssrtKlgjPUrEEwolk)((int)oTYnvuyaZmGssrtKlgjPUrEEwolk | (8388608 << i));
			}
		}
		if ((P_0 & QtSxnZYSjrgthBpvYZqvQdRfKXUE.Names) != QtSxnZYSjrgthBpvYZqvQdRfKXUE.None)
		{
			for (int j = 0; j < num; j++)
			{
				oTYnvuyaZmGssrtKlgjPUrEEwolk = (oTYnvuyaZmGssrtKlgjPUrEEwolk)((int)oTYnvuyaZmGssrtKlgjPUrEEwolk | (16384 << j));
			}
		}
		return oTYnvuyaZmGssrtKlgjPUrEEwolk;
	}

	protected DEOLSCnqecUoFqpsMneIWaoyXVqt vVErTYAbdFRRLfXjyMdwNEqFAmnGA()
	{
		return RZKDbaDlqKvZBfkLJCkUzoaxqLAwA() as DEOLSCnqecUoFqpsMneIWaoyXVqt;
	}

	protected virtual void PEMJeHPrCdECwYEdoINSWRVjZhGW()
	{
		base.WWbQWIkCrHILkmvtSGPWgKBbHyFQ();
		int num = iKMpMPYbCeMTYyywlDwWOMTGxkgI;
		for (int i = 0; i < num; i++)
		{
			cQwbtPkKbuvPqNcLgcikLIlJcUUG(i);
		}
	}

	protected virtual void jWjxsOxjwOwCqogSYFSUtCsuMsem()
	{
		aZzOkurvWhsbADLEqQAdGQZVlQRx();
		if (base.LJXAbEKxmDHBiYmUZFbAJTxfIUxj != AqybaYFDSFEDwBRnsokwpBTdIblQ.CompoundElement)
		{
			return;
		}
		veVjxECKraSLRuRJUJeBWprfCtQDb veVjxECKraSLRuRJUJeBWprfCtQDb = base.VsFDlKfYzzTTInlpCbOWcKKrmFZDA;
		if ((veVjxECKraSLRuRJUJeBWprfCtQDb == veVjxECKraSLRuRJUJeBWprfCtQDb.Axis2D || (uint)(veVjxECKraSLRuRJUJeBWprfCtQDb - 3) <= 2u) && LncLyoofGJjkWktCWxMpDhEWRXph != null)
		{
			int num = iKMpMPYbCeMTYyywlDwWOMTGxkgI;
			for (int i = 0; i < num; i++)
			{
				WfYxlWKheRqSPhxWVoclUcggslZQ(1, new eHmaJdrNOVirmgtpoujzQtBnLiexA(LncLyoofGJjkWktCWxMpDhEWRXph[i], 16384 << i));
			}
		}
	}
}
