using System;
using System.Collections.Generic;
using Rewired.ComponentControls.Data;
using Rewired.Internal;
using Rewired.Utils.Attributes;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.Events;
using UnityEngine.UI;

namespace Rewired.ComponentControls
{
	[Serializable]
	[AddComponentMenu("Rewired/Touch Controls/Touch Pad")]
	[DisallowMultipleComponent]
	[RequireComponent(typeof(Image))]
	public sealed class TouchPad : TouchInteractable, IPointerDownHandler, IEventSystemHandler, IPointerUpHandler
	{
		public enum AxisDirection
		{
			Both = 0,
			Horizontal = 1,
			Vertical = 2
		}

		public enum TouchPadMode
		{
			Delta = 0,
			ScreenPosition = 1,
			VectorFromCenter = 2,
			VectorFromInitialTouch = 3
		}

		public enum ValueFormat
		{
			Pixels = 0,
			Screen = 1,
			Physical = 2,
			Direction = 3
		}

		private class zWMWSdLNLniwrjUFoyBotYPtUQKw
		{
			private class IKZCuYDiidhNaMfRXXaHYWAngcWQ
			{
				public float yoOgneAOmWXfRVqkmpnMCHrRBntQA;

				public float uCbuehafagMnEizHfbgZqqODGusf;

				public uint fxfkKcAGhpxAzpGBubjVjRWMtySs;
			}

			private int TrzUslyxoULFGurezGQlhddQtPaj;

			private IKZCuYDiidhNaMfRXXaHYWAngcWQ[] wdwpJorZisPwGJleypmfmqnEBtuEA;

			private int kQAAeeShGyiOSJSEYLcCheYhuBOYb;

			public zWMWSdLNLniwrjUFoyBotYPtUQKw(int P_0)
			{
			}

			public void KIXILCGGgSKJaFmMEwzBVpmTOtmi(float P_0, float P_1)
			{
			}

			public Vector2 DhVgddluGkEFcwjgobnbEKELzNCGA()
			{
				return default(Vector2);
			}

			private void jydFfstQXmETDEzEvoHisVMvJfDEb()
			{
			}

			private static int NkEEdWUvTKdGqbgDeJNBHbGbJkohb(int P_0, int P_1)
			{
				return 0;
			}

			private int KEeXsuafWNVnkzCRuhjfwwiOwInk(int P_0, int P_1)
			{
				return 0;
			}

			private static bool fhiNAFRfituLyrCTBFAlfqFPhNLkA(uint P_0, uint P_1)
			{
				return false;
			}
		}

		[Serializable]
		public class ValueChangedEventHandler : UnityEvent<Vector2>
		{
		}

		[Serializable]
		public class TapEventHandler : UnityEvent
		{
		}

		[Serializable]
		public class PressDownEventHandler : UnityEvent
		{
		}

		[Serializable]
		public class PressUpEventHandler : UnityEvent
		{
		}

		private const int SMOOTH_DELTA_FRAME_COUNT = 3;

		[SerializeField]
		[Tooltip("The Custom Controller element that will receive input values from the touch pad's X axis.")]
		[CustomObfuscation(rename = false)]
		private CustomControllerElementTargetSetForFloat _horizontalAxisCustomControllerElement;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		[Tooltip("The Custom Controller element that will receive input values from the touch pad's Y axis.")]
		private CustomControllerElementTargetSetForFloat _verticalAxisCustomControllerElement;

		[Tooltip("The Custom Controller element that will receive input values from touch pad taps.")]
		[SerializeField]
		[CustomObfuscation(rename = false)]
		private CustomControllerElementTargetSetForBoolean _tapCustomControllerElement;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		[Tooltip("The Custom Controller element that will receive input values from touch pad presses.")]
		private CustomControllerElementTargetSetForBoolean _pressCustomControllerElement;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		[Tooltip("The axis directions in which movement is allowed. You can restrict movement to one or both axes.")]
		private AxisDirection _axesToUse;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		[Tooltip("The mode of the touch pad.\n\nDelta - Returns the change in position of the touch from the previous to the current frame.\n\nScreen Position - Returns the absolute position of the touch  on the screen.\n\nVector From Center - Returns a vector from the center of the Touch Pad to the current touch position.\n\nVector From Initial Touch - Returns a vector from the intial touch position to the current touch position.")]
		private TouchPadMode _touchPadMode;

		[SerializeField]
		[Tooltip("The format of the resulting data generated by the touch pad.\n\nPixels - Screen pixels.\n\nScreen - The proportion of the value to screen size in the corresponding dimension. 1 unit = 1 screen length (width for X, height for Y).\n\nPhysical - 1 unit = 1/100th of an inch. The resulting value will be consistent across different screen resolutions and sizes. IMPORTANT: This relies on the value returned by UnityEngine.Screen.dpi. If the device does not return a value, a reference resolution of 96 dpi will be used.\n\nDirection - A normalized direction vector.")]
		[CustomObfuscation(rename = false)]
		private ValueFormat _valueFormat;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		[Tooltip("If enabled, when swiped and released, the value will slowly fall toward zero based on the Friction value. This only has an effect if Touch Pad Mode is set to Position Delta.")]
		private bool _useInertia;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		[Tooltip("Determines how quickly a swipe value will fall toward zero when Use Inertia is enabled.")]
		[FieldRange(0f, float.MaxValue)]
		private float _inertiaFriction;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		[Tooltip("If true, the touch pad can be activated by a touch swipe that began in an area outside the touch pad region. If false, the touch pad can only be activated by a direct touch.")]
		private bool _activateOnSwipeIn;

		[CustomObfuscation(rename = false)]
		[Tooltip("If true, the touch pad will stay engaged even if the touch that activated it moves outside the touch pad region. If false, the touch pad will be released once the touch that activated it moves outside the touch pad region.")]
		[SerializeField]
		private bool _stayActiveOnSwipeOut;

		[SerializeField]
		[Tooltip("Should taps on the touch pad be processed?")]
		[CustomObfuscation(rename = false)]
		private bool _allowTap;

		[CustomObfuscation(rename = false)]
		[FieldRange(0f, float.MaxValue)]
		[Tooltip("The maximum touch duration allowed for the touch to be considered a tap. A touch that lasts longer than this value will not trigger a tap when released.")]
		[SerializeField]
		private float _tapTimeout;

		[FieldRange(-1, int.MaxValue)]
		[SerializeField]
		[CustomObfuscation(rename = false)]
		[Tooltip("The maximum movement distance allowed in pixels since the touch began for the touch to be considered a tap. [-1 = no limit]")]
		private int _tapDistanceLimit;

		[Tooltip("Should presses (continual press like a button) on the touch pad be processed?")]
		[CustomObfuscation(rename = false)]
		[SerializeField]
		private bool _allowPress;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		[Tooltip("Time the touch pad must be touched before it will be considered a press.")]
		private float _pressStartDelay;

		[FieldRange(-1, int.MaxValue)]
		[CustomObfuscation(rename = false)]
		[SerializeField]
		[Tooltip("The maximum movement distance allowed in pixels since the touch began for the touch to be considered a press. Any movement beyond this value will cancel the press. [-1 = no limit]")]
		private int _pressDistanceLimit;

		[Tooltip("If enabled, the control will be hidden when gameplay starts.")]
		[CustomObfuscation(rename = false)]
		[SerializeField]
		private bool _hideAtRuntime;

		[SerializeField]
		[Tooltip("The underlying Axis 2D.")]
		[CustomObfuscation(rename = false)]
		private StandaloneAxis2D _axis2D;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		[Tooltip("Event sent when the value changes.")]
		private ValueChangedEventHandler _onValueChanged;

		[Tooltip("Event sent when the touch pad is tapped. This event will only be sent if allowTap is True.")]
		[SerializeField]
		[CustomObfuscation(rename = false)]
		private TapEventHandler _onTap;

		[CustomObfuscation(rename = false)]
		[SerializeField]
		[Tooltip("Event sent when the touch pad is initally pressed. This event is for the Press button simulation which must be enabled by setting Press Allowed to True. This event will only be sent if allowPress is True.")]
		private PressDownEventHandler _onPressDown;

		[Tooltip("Event sent when the touch pad is released after a press. This event is for the Press button simulation which must be enabled by setting Press Allowed to True. This event will only be sent if allowPress is True.")]
		[CustomObfuscation(rename = false)]
		[SerializeField]
		private PressUpEventHandler _onPressUp;

		private bool _useXAxis;

		private bool _useYAxis;

		private int _pointerId;

		private int _realMousePointerId;

		[NonSerialized]
		private bool cOVGNKhjbgxwKCllnRGrxkoLarDBA;

		[NonSerialized]
		private bool CQXWqgKaqlyhpYoCNMgBJzRcfLDL;

		private bool _pointerDownIsFake;

		private Vector2 _touchStartPosition;

		private float _touchStartTime;

		private Vector3 _currentCenter;

		private Vector2 _previousTouchPosition;

		private int _lastTapFrame;

		private bool _isEligibleForTap;

		private bool _isEligibleForPress;

		private bool _pressValue;

		private zWMWSdLNLniwrjUFoyBotYPtUQKw _smoothDelta;

		private Dictionary<int, PointerEventData> __fakePointerEventData;

		public CustomControllerElementTargetSetForFloat horizontalAxisCustomControllerElement => null;

		public CustomControllerElementTargetSetForFloat verticalAxisCustomControllerElement => null;

		public CustomControllerElementTargetSetForBoolean tapCustomControllerElement => null;

		public CustomControllerElementTargetSetForBoolean pressCustomControllerElement => null;

		public AxisDirection axesToUse
		{
			get
			{
				return default(AxisDirection);
			}
			set
			{
			}
		}

		public TouchPadMode touchPadMode
		{
			get
			{
				return default(TouchPadMode);
			}
			set
			{
			}
		}

		public ValueFormat valueFormat
		{
			get
			{
				return default(ValueFormat);
			}
			set
			{
			}
		}

		public bool useInertia
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		public float inertiaFriction
		{
			get
			{
				return 0f;
			}
			set
			{
			}
		}

		public bool activateOnSwipeIn
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		public bool stayActiveOnSwipeOut
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		public bool allowTap
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		public float tapTimeout
		{
			get
			{
				return 0f;
			}
			set
			{
			}
		}

		public int tapDistanceLimit
		{
			get
			{
				return 0;
			}
			set
			{
			}
		}

		public bool allowPress
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		public float pressStartDelay
		{
			get
			{
				return 0f;
			}
			set
			{
			}
		}

		public int pressDistanceLimit
		{
			get
			{
				return 0;
			}
			set
			{
			}
		}

		public bool hideAtRuntime
		{
			get
			{
				return false;
			}
			set
			{
			}
		}

		public int pointerId
		{
			get
			{
				return 0;
			}
			set
			{
			}
		}

		public bool hasPointer => false;

		public Vector2 touchStartPosition => default(Vector2);

		public Vector2 touchPosition => default(Vector2);

		public AxisCalibration horizontalAxisCalibration => null;

		public AxisCalibration verticalAxisCalibration => null;

		public Axis2DCalibration axis2DCalibration => null;

		internal StandaloneAxis2D XjwNzvjGCTqUwsgUmcfwANLgQtNV => null;

		private int hmMwHvWDaEbRDhCurEogtsMmSaJR => 0;

		private bool kBcxXYqfTRVpbxUeRFgGIqYYUsob => false;

		public event UnityAction<Vector2> ValueChangedEvent
		{
			add
			{
			}
			remove
			{
			}
		}

		public event UnityAction TapEvent
		{
			add
			{
			}
			remove
			{
			}
		}

		public event UnityAction PressDownEvent
		{
			add
			{
			}
			remove
			{
			}
		}

		public event UnityAction PressUpEvent
		{
			add
			{
			}
			remove
			{
			}
		}

		[CustomObfuscation(rename = false)]
		private TouchPad()
		{
		}

		[CustomObfuscation(rename = false)]
		internal override void Awake()
		{
		}

		[CustomObfuscation(rename = false)]
		internal override void OnValidate()
		{
		}

		internal override bool qAgXOZxzQNKqPAuHppaSytuDgzcg()
		{
			return false;
		}

		internal override void TaJJysfcXGOLIYrzfRlEkosEbnMcA()
		{
		}

		internal override void UQizGkdUUglAlSKLFhpOGRJTqnpDb()
		{
		}

		internal override void MPxPpCPVtBLCgEKzdjWmMHtdnZGk()
		{
		}

		internal override void bFeVhzFgykusySbDzeNuCRErjfHH()
		{
		}

		public override void ClearValue()
		{
		}

		private void hvKKuewFYiMnoDhgXmsJjELTrRuR()
		{
		}

		private void huTpfGQAOZCDYBUwALzOMfdaBwKQA()
		{
		}

		private void xBmeSObDNEIMxzozwHnyeqwIgwhC(AxisDirection P_0)
		{
		}

		private void AllhdrtKAaQigyovZnNleLWbfnwQ()
		{
		}

		private void pihXDITNVEqzlWiuHsduScIUsXku()
		{
		}

		private void oOkCbYeOzlahyKtYSjEeXmevnKHB()
		{
		}

		private void DHHzNggxamcCRvnKSObiCcVjxSel()
		{
		}

		private void opaplSmxgMMLpVOswkdFdYFmWYiR(ref Vector2 P_0)
		{
		}

		private void RoLPkDDABDbXjzqhPqoYICgdDeKh(ref Vector2 P_0)
		{
		}

		private void JUcCKuCwHmJRhvQvyLfvibLlTZBab()
		{
		}

		private Vector2 TyjnlpcCrMbIJMUhDGTwnljgXyTA(Vector2 P_0)
		{
			return default(Vector2);
		}

		private void qyYBtMMdLjjuUURQRJAOssVYVyog(bool P_0)
		{
		}

		private void kMNflQRBOdrlrtbkVhJpJSmWcQVxA(PointerEventData P_0)
		{
		}

		private void JRSklfkfyJOVrTKKlLEkJblHUqgE(PointerEventData P_0)
		{
		}

		private void xsIJmGqLmUPjOBkRyDnGgeJLJMiaA(PointerEventData P_0)
		{
		}

		private void GYJsiFJUeuliilYckXwAiHHUjxJP(PointerEventData P_0)
		{
		}

		private void GIGjVciILviIdECmDLGzschJtlBgA(int P_0, Vector2 P_1)
		{
		}

		private void yDLMImpCVoIrnfDFhxHPIjTqXFsD()
		{
		}

		internal override void OnPointerUp(PointerEventData eventData)
		{
		}

		internal override void OnPointerDown(PointerEventData eventData)
		{
		}

		internal override void OnPointerEnter(PointerEventData eventData)
		{
		}

		internal override void OnPointerExit(PointerEventData eventData)
		{
		}

		private void BHRyBnOlSqlgVrMVNbDTJCHegHFAb()
		{
		}

		private bool phlIFZPXlerHulrMRJgJAjCSTTBF(int P_0)
		{
			return false;
		}

		private PointerEventData gTYGOpVcWpRLtMYhcICpeXLCnhdp(int P_0, GameObject P_1)
		{
			return null;
		}

		private PointerEventData giMhZuJpgyqOpkawIYZtDYHaxwUc(int P_0, GameObject P_1)
		{
			return null;
		}

		private PointerEventData mCzRjUcrWnKoLZMFJVTDuxqWhsEP(int P_0)
		{
			return null;
		}

		private void HYzqSjRWkJezxzKZnKSJWAZasbBw(PointerEventData P_0)
		{
		}

		private PointerEventData oZAQIfcLIyqdsmOEahisTIScPnmL(int P_0)
		{
			return null;
		}
	}
}
