public enum ECustomerState
{
	None = -1,
	Idle = 0,
	WantToBuyItem = 1,
	WalkToShelf = 2,
	TakingItemFromShelf = 3,
	WantToPay = 4,
	QueuingToPay = 5,
	ReadyToPay = 6,
	ExitingShop = 7,
	ShopNotOpen = 8,
	WantToBuyCard = 9,
	WalkToCardShelf = 10,
	TakingItemFromCardShelf = 11,
	WantToPlayGame = 12,
	WalkToPlayTable = 13,
	PlayingAtTable = 14,
	EndingPlayTableGame = 15,
	QueueingPlayTable = 16,
	WantToTradeCard = 17,
	WaitingToTradeCard = 18,
	WantToTakeBulkDonationCard = 19,
	WalkToBulkDonationBox = 20,
	TakingItemFromBulkDonationBox = 21
}
