<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Timberborn.WalkingSystemUI</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Timberborn.SingletonSystem">
      <HintPath>..\..\Assemblies\Timberborn.SingletonSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Debugging">
      <HintPath>..\..\Assemblies\Timberborn.Debugging.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.AssetSystem">
      <HintPath>..\..\Assemblies\Timberborn.AssetSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.RootProviders">
      <HintPath>..\..\Assemblies\Timberborn.RootProviders.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BlueprintSystem">
      <HintPath>..\..\Assemblies\Timberborn.BlueprintSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SelectionSystem">
      <HintPath>..\..\Assemblies\Timberborn.SelectionSystem.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.WalkingSystem">
      <HintPath>..\..\Assemblies\Timberborn.WalkingSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Common">
      <HintPath>..\..\Assemblies\Timberborn.Common.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.CharacterModelSystem">
      <HintPath>..\..\Assemblies\Timberborn.CharacterModelSystem.dll</HintPath>
    </Reference>
    <Reference Include="Bindito.Core">
      <HintPath>..\..\Assemblies\Bindito.Core.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BaseComponentSystem">
      <HintPath>..\..\Assemblies\Timberborn.BaseComponentSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Navigation">
      <HintPath>..\..\Assemblies\Timberborn.Navigation.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>