<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Kitchen.MessagePack</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>8.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="MessagePack">
      <HintPath>..\..\Assemblies\MessagePack.dll</HintPath>
    </Reference>
    <Reference Include="System.Memory">
      <HintPath>..\..\Assemblies\System.Memory.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>