using NodeCanvas.Framework;
using NodeCanvas.Framework.Internal;
using NodeCanvas.Tasks.Actions;
using NodeCanvas.Tasks.Conditions;
using UnityEngine;

namespace ParadoxNotion.Internal
{
	internal class AOTDummy
	{
		private object o;

		private BBParameter<bool> NodeCanvas_Framework_BBParameter_System_Boolean;

		private BBParameter<float> NodeCanvas_Framework_BBParameter_System_Single;

		private BBParameter<int> NodeCanvas_Framework_BBParameter_System_Int32;

		private BBParameter<Vector2> NodeCanvas_Framework_BBParameter_UnityEngine_Vector2;

		private BBParameter<Vector3> NodeCanvas_Framework_BBParameter_UnityEngine_Vector3;

		private BBParameter<Vector4> NodeCanvas_Framework_BBParameter_UnityEngine_Vector4;

		private BBParameter<Quaternion> NodeCanvas_Framework_BBParameter_UnityEngine_Quaternion;

		private BBParameter<Keyframe> NodeCanvas_Framework_BBParameter_UnityEngine_Keyframe;

		private BBParameter<Bounds> NodeCanvas_Framework_BBParameter_UnityEngine_Bounds;

		private BBParameter<Color> NodeCanvas_Framework_BBParameter_UnityEngine_Color;

		private BBParameter<Rect> NodeCanvas_Framework_BBParameter_UnityEngine_Rect;

		private BBParameter<ContactPoint> NodeCanvas_Framework_BBParameter_UnityEngine_ContactPoint;

		private BBParameter<ContactPoint2D> NodeCanvas_Framework_BBParameter_UnityEngine_ContactPoint2D;

		private BBParameter<RaycastHit> NodeCanvas_Framework_BBParameter_UnityEngine_RaycastHit;

		private BBParameter<RaycastHit2D> NodeCanvas_Framework_BBParameter_UnityEngine_RaycastHit2D;

		private BBParameter<Ray> NodeCanvas_Framework_BBParameter_UnityEngine_Ray;

		private BBParameter<Space> NodeCanvas_Framework_BBParameter_UnityEngine_Space;

		private BBParameter<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Framework_BBParameter_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private BBParameter<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Framework_BBParameter_SceneManager_DestroyGadgetEventArgs;

		private BBParameter<SceneManager.GetGadgetEventArgs> NodeCanvas_Framework_BBParameter_SceneManager_GetGadgetEventArgs;

		private BBParameter<ModuleId> NodeCanvas_Framework_BBParameter_ModuleId;

		private BBParameter<SceneManager.PrintGadgetEventArgs> NodeCanvas_Framework_BBParameter_SceneManager_PrintGadgetEventArgs;

		private BBParameter<Workbench.SpawnModuleEventArgs> NodeCanvas_Framework_BBParameter_Workbench_SpawnModuleEventArgs;

		private BBParameter<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Framework_BBParameter_Workbench_SpawnMotherboardEventArgs;

		private BBParameter<ActionList.ActionsExecutionMode> NodeCanvas_Framework_BBParameter_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private BBParameter<ConditionList.ConditionsCheckMode> NodeCanvas_Framework_BBParameter_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private BBParameter<uint> NodeCanvas_Framework_BBParameter_System_UInt32;

		private BBParameter<LayerMask> NodeCanvas_Framework_BBParameter_UnityEngine_LayerMask;

		private ExposedParameter<bool> NodeCanvas_Framework_ExposedParameter_System_Boolean;

		private ExposedParameter<float> NodeCanvas_Framework_ExposedParameter_System_Single;

		private ExposedParameter<int> NodeCanvas_Framework_ExposedParameter_System_Int32;

		private ExposedParameter<Vector2> NodeCanvas_Framework_ExposedParameter_UnityEngine_Vector2;

		private ExposedParameter<Vector3> NodeCanvas_Framework_ExposedParameter_UnityEngine_Vector3;

		private ExposedParameter<Vector4> NodeCanvas_Framework_ExposedParameter_UnityEngine_Vector4;

		private ExposedParameter<Quaternion> NodeCanvas_Framework_ExposedParameter_UnityEngine_Quaternion;

		private ExposedParameter<Keyframe> NodeCanvas_Framework_ExposedParameter_UnityEngine_Keyframe;

		private ExposedParameter<Bounds> NodeCanvas_Framework_ExposedParameter_UnityEngine_Bounds;

		private ExposedParameter<Color> NodeCanvas_Framework_ExposedParameter_UnityEngine_Color;

		private ExposedParameter<Rect> NodeCanvas_Framework_ExposedParameter_UnityEngine_Rect;

		private ExposedParameter<ContactPoint> NodeCanvas_Framework_ExposedParameter_UnityEngine_ContactPoint;

		private ExposedParameter<ContactPoint2D> NodeCanvas_Framework_ExposedParameter_UnityEngine_ContactPoint2D;

		private ExposedParameter<RaycastHit> NodeCanvas_Framework_ExposedParameter_UnityEngine_RaycastHit;

		private ExposedParameter<RaycastHit2D> NodeCanvas_Framework_ExposedParameter_UnityEngine_RaycastHit2D;

		private ExposedParameter<Ray> NodeCanvas_Framework_ExposedParameter_UnityEngine_Ray;

		private ExposedParameter<Space> NodeCanvas_Framework_ExposedParameter_UnityEngine_Space;

		private ExposedParameter<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Framework_ExposedParameter_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private ExposedParameter<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Framework_ExposedParameter_SceneManager_DestroyGadgetEventArgs;

		private ExposedParameter<SceneManager.GetGadgetEventArgs> NodeCanvas_Framework_ExposedParameter_SceneManager_GetGadgetEventArgs;

		private ExposedParameter<ModuleId> NodeCanvas_Framework_ExposedParameter_ModuleId;

		private ExposedParameter<SceneManager.PrintGadgetEventArgs> NodeCanvas_Framework_ExposedParameter_SceneManager_PrintGadgetEventArgs;

		private ExposedParameter<Workbench.SpawnModuleEventArgs> NodeCanvas_Framework_ExposedParameter_Workbench_SpawnModuleEventArgs;

		private ExposedParameter<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Framework_ExposedParameter_Workbench_SpawnMotherboardEventArgs;

		private ExposedParameter<ActionList.ActionsExecutionMode> NodeCanvas_Framework_ExposedParameter_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private ExposedParameter<ConditionList.ConditionsCheckMode> NodeCanvas_Framework_ExposedParameter_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private ExposedParameter<uint> NodeCanvas_Framework_ExposedParameter_System_UInt32;

		private ExposedParameter<LayerMask> NodeCanvas_Framework_ExposedParameter_UnityEngine_LayerMask;

		private Variable<bool> NodeCanvas_Framework_Variable_System_Boolean;

		private Variable<float> NodeCanvas_Framework_Variable_System_Single;

		private Variable<int> NodeCanvas_Framework_Variable_System_Int32;

		private Variable<Vector2> NodeCanvas_Framework_Variable_UnityEngine_Vector2;

		private Variable<Vector3> NodeCanvas_Framework_Variable_UnityEngine_Vector3;

		private Variable<Vector4> NodeCanvas_Framework_Variable_UnityEngine_Vector4;

		private Variable<Quaternion> NodeCanvas_Framework_Variable_UnityEngine_Quaternion;

		private Variable<Keyframe> NodeCanvas_Framework_Variable_UnityEngine_Keyframe;

		private Variable<Bounds> NodeCanvas_Framework_Variable_UnityEngine_Bounds;

		private Variable<Color> NodeCanvas_Framework_Variable_UnityEngine_Color;

		private Variable<Rect> NodeCanvas_Framework_Variable_UnityEngine_Rect;

		private Variable<ContactPoint> NodeCanvas_Framework_Variable_UnityEngine_ContactPoint;

		private Variable<ContactPoint2D> NodeCanvas_Framework_Variable_UnityEngine_ContactPoint2D;

		private Variable<RaycastHit> NodeCanvas_Framework_Variable_UnityEngine_RaycastHit;

		private Variable<RaycastHit2D> NodeCanvas_Framework_Variable_UnityEngine_RaycastHit2D;

		private Variable<Ray> NodeCanvas_Framework_Variable_UnityEngine_Ray;

		private Variable<Space> NodeCanvas_Framework_Variable_UnityEngine_Space;

		private Variable<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Framework_Variable_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private Variable<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Framework_Variable_SceneManager_DestroyGadgetEventArgs;

		private Variable<SceneManager.GetGadgetEventArgs> NodeCanvas_Framework_Variable_SceneManager_GetGadgetEventArgs;

		private Variable<ModuleId> NodeCanvas_Framework_Variable_ModuleId;

		private Variable<SceneManager.PrintGadgetEventArgs> NodeCanvas_Framework_Variable_SceneManager_PrintGadgetEventArgs;

		private Variable<Workbench.SpawnModuleEventArgs> NodeCanvas_Framework_Variable_Workbench_SpawnModuleEventArgs;

		private Variable<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Framework_Variable_Workbench_SpawnMotherboardEventArgs;

		private Variable<ActionList.ActionsExecutionMode> NodeCanvas_Framework_Variable_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private Variable<ConditionList.ConditionsCheckMode> NodeCanvas_Framework_Variable_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private Variable<uint> NodeCanvas_Framework_Variable_System_UInt32;

		private Variable<LayerMask> NodeCanvas_Framework_Variable_UnityEngine_LayerMask;

		private ReflectedAction<bool> NodeCanvas_Framework_Internal_ReflectedAction_System_Boolean;

		private ReflectedAction<float> NodeCanvas_Framework_Internal_ReflectedAction_System_Single;

		private ReflectedAction<int> NodeCanvas_Framework_Internal_ReflectedAction_System_Int32;

		private ReflectedAction<Vector2> NodeCanvas_Framework_Internal_ReflectedAction_UnityEngine_Vector2;

		private ReflectedAction<Vector3> NodeCanvas_Framework_Internal_ReflectedAction_UnityEngine_Vector3;

		private ReflectedAction<Vector4> NodeCanvas_Framework_Internal_ReflectedAction_UnityEngine_Vector4;

		private ReflectedAction<Quaternion> NodeCanvas_Framework_Internal_ReflectedAction_UnityEngine_Quaternion;

		private ReflectedAction<Keyframe> NodeCanvas_Framework_Internal_ReflectedAction_UnityEngine_Keyframe;

		private ReflectedAction<Bounds> NodeCanvas_Framework_Internal_ReflectedAction_UnityEngine_Bounds;

		private ReflectedAction<Color> NodeCanvas_Framework_Internal_ReflectedAction_UnityEngine_Color;

		private ReflectedAction<Rect> NodeCanvas_Framework_Internal_ReflectedAction_UnityEngine_Rect;

		private ReflectedAction<ContactPoint> NodeCanvas_Framework_Internal_ReflectedAction_UnityEngine_ContactPoint;

		private ReflectedAction<ContactPoint2D> NodeCanvas_Framework_Internal_ReflectedAction_UnityEngine_ContactPoint2D;

		private ReflectedAction<RaycastHit> NodeCanvas_Framework_Internal_ReflectedAction_UnityEngine_RaycastHit;

		private ReflectedAction<RaycastHit2D> NodeCanvas_Framework_Internal_ReflectedAction_UnityEngine_RaycastHit2D;

		private ReflectedAction<Ray> NodeCanvas_Framework_Internal_ReflectedAction_UnityEngine_Ray;

		private ReflectedAction<Space> NodeCanvas_Framework_Internal_ReflectedAction_UnityEngine_Space;

		private ReflectedAction<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Framework_Internal_ReflectedAction_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private ReflectedAction<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Framework_Internal_ReflectedAction_SceneManager_DestroyGadgetEventArgs;

		private ReflectedAction<SceneManager.GetGadgetEventArgs> NodeCanvas_Framework_Internal_ReflectedAction_SceneManager_GetGadgetEventArgs;

		private ReflectedAction<ModuleId> NodeCanvas_Framework_Internal_ReflectedAction_ModuleId;

		private ReflectedAction<SceneManager.PrintGadgetEventArgs> NodeCanvas_Framework_Internal_ReflectedAction_SceneManager_PrintGadgetEventArgs;

		private ReflectedAction<Workbench.SpawnModuleEventArgs> NodeCanvas_Framework_Internal_ReflectedAction_Workbench_SpawnModuleEventArgs;

		private ReflectedAction<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Framework_Internal_ReflectedAction_Workbench_SpawnMotherboardEventArgs;

		private ReflectedAction<ActionList.ActionsExecutionMode> NodeCanvas_Framework_Internal_ReflectedAction_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private ReflectedAction<ConditionList.ConditionsCheckMode> NodeCanvas_Framework_Internal_ReflectedAction_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private ReflectedAction<uint> NodeCanvas_Framework_Internal_ReflectedAction_System_UInt32;

		private ReflectedAction<LayerMask> NodeCanvas_Framework_Internal_ReflectedAction_UnityEngine_LayerMask;

		private ReflectedFunction<bool> NodeCanvas_Framework_Internal_ReflectedFunction_System_Boolean;

		private ReflectedFunction<float> NodeCanvas_Framework_Internal_ReflectedFunction_System_Single;

		private ReflectedFunction<int> NodeCanvas_Framework_Internal_ReflectedFunction_System_Int32;

		private ReflectedFunction<Vector2> NodeCanvas_Framework_Internal_ReflectedFunction_UnityEngine_Vector2;

		private ReflectedFunction<Vector3> NodeCanvas_Framework_Internal_ReflectedFunction_UnityEngine_Vector3;

		private ReflectedFunction<Vector4> NodeCanvas_Framework_Internal_ReflectedFunction_UnityEngine_Vector4;

		private ReflectedFunction<Quaternion> NodeCanvas_Framework_Internal_ReflectedFunction_UnityEngine_Quaternion;

		private ReflectedFunction<Keyframe> NodeCanvas_Framework_Internal_ReflectedFunction_UnityEngine_Keyframe;

		private ReflectedFunction<Bounds> NodeCanvas_Framework_Internal_ReflectedFunction_UnityEngine_Bounds;

		private ReflectedFunction<Color> NodeCanvas_Framework_Internal_ReflectedFunction_UnityEngine_Color;

		private ReflectedFunction<Rect> NodeCanvas_Framework_Internal_ReflectedFunction_UnityEngine_Rect;

		private ReflectedFunction<ContactPoint> NodeCanvas_Framework_Internal_ReflectedFunction_UnityEngine_ContactPoint;

		private ReflectedFunction<ContactPoint2D> NodeCanvas_Framework_Internal_ReflectedFunction_UnityEngine_ContactPoint2D;

		private ReflectedFunction<RaycastHit> NodeCanvas_Framework_Internal_ReflectedFunction_UnityEngine_RaycastHit;

		private ReflectedFunction<RaycastHit2D> NodeCanvas_Framework_Internal_ReflectedFunction_UnityEngine_RaycastHit2D;

		private ReflectedFunction<Ray> NodeCanvas_Framework_Internal_ReflectedFunction_UnityEngine_Ray;

		private ReflectedFunction<Space> NodeCanvas_Framework_Internal_ReflectedFunction_UnityEngine_Space;

		private ReflectedFunction<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Framework_Internal_ReflectedFunction_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private ReflectedFunction<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Framework_Internal_ReflectedFunction_SceneManager_DestroyGadgetEventArgs;

		private ReflectedFunction<SceneManager.GetGadgetEventArgs> NodeCanvas_Framework_Internal_ReflectedFunction_SceneManager_GetGadgetEventArgs;

		private ReflectedFunction<ModuleId> NodeCanvas_Framework_Internal_ReflectedFunction_ModuleId;

		private ReflectedFunction<SceneManager.PrintGadgetEventArgs> NodeCanvas_Framework_Internal_ReflectedFunction_SceneManager_PrintGadgetEventArgs;

		private ReflectedFunction<Workbench.SpawnModuleEventArgs> NodeCanvas_Framework_Internal_ReflectedFunction_Workbench_SpawnModuleEventArgs;

		private ReflectedFunction<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Framework_Internal_ReflectedFunction_Workbench_SpawnMotherboardEventArgs;

		private ReflectedFunction<ActionList.ActionsExecutionMode> NodeCanvas_Framework_Internal_ReflectedFunction_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private ReflectedFunction<ConditionList.ConditionsCheckMode> NodeCanvas_Framework_Internal_ReflectedFunction_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private ReflectedFunction<uint> NodeCanvas_Framework_Internal_ReflectedFunction_System_UInt32;

		private ReflectedFunction<LayerMask> NodeCanvas_Framework_Internal_ReflectedFunction_UnityEngine_LayerMask;

		private AddElementToDictionary<bool> NodeCanvas_Tasks_Actions_AddElementToDictionary_System_Boolean;

		private AddElementToDictionary<float> NodeCanvas_Tasks_Actions_AddElementToDictionary_System_Single;

		private AddElementToDictionary<int> NodeCanvas_Tasks_Actions_AddElementToDictionary_System_Int32;

		private AddElementToDictionary<Vector2> NodeCanvas_Tasks_Actions_AddElementToDictionary_UnityEngine_Vector2;

		private AddElementToDictionary<Vector3> NodeCanvas_Tasks_Actions_AddElementToDictionary_UnityEngine_Vector3;

		private AddElementToDictionary<Vector4> NodeCanvas_Tasks_Actions_AddElementToDictionary_UnityEngine_Vector4;

		private AddElementToDictionary<Quaternion> NodeCanvas_Tasks_Actions_AddElementToDictionary_UnityEngine_Quaternion;

		private AddElementToDictionary<Keyframe> NodeCanvas_Tasks_Actions_AddElementToDictionary_UnityEngine_Keyframe;

		private AddElementToDictionary<Bounds> NodeCanvas_Tasks_Actions_AddElementToDictionary_UnityEngine_Bounds;

		private AddElementToDictionary<Color> NodeCanvas_Tasks_Actions_AddElementToDictionary_UnityEngine_Color;

		private AddElementToDictionary<Rect> NodeCanvas_Tasks_Actions_AddElementToDictionary_UnityEngine_Rect;

		private AddElementToDictionary<ContactPoint> NodeCanvas_Tasks_Actions_AddElementToDictionary_UnityEngine_ContactPoint;

		private AddElementToDictionary<ContactPoint2D> NodeCanvas_Tasks_Actions_AddElementToDictionary_UnityEngine_ContactPoint2D;

		private AddElementToDictionary<RaycastHit> NodeCanvas_Tasks_Actions_AddElementToDictionary_UnityEngine_RaycastHit;

		private AddElementToDictionary<RaycastHit2D> NodeCanvas_Tasks_Actions_AddElementToDictionary_UnityEngine_RaycastHit2D;

		private AddElementToDictionary<Ray> NodeCanvas_Tasks_Actions_AddElementToDictionary_UnityEngine_Ray;

		private AddElementToDictionary<Space> NodeCanvas_Tasks_Actions_AddElementToDictionary_UnityEngine_Space;

		private AddElementToDictionary<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Actions_AddElementToDictionary_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private AddElementToDictionary<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Actions_AddElementToDictionary_SceneManager_DestroyGadgetEventArgs;

		private AddElementToDictionary<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Actions_AddElementToDictionary_SceneManager_GetGadgetEventArgs;

		private AddElementToDictionary<ModuleId> NodeCanvas_Tasks_Actions_AddElementToDictionary_ModuleId;

		private AddElementToDictionary<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Actions_AddElementToDictionary_SceneManager_PrintGadgetEventArgs;

		private AddElementToDictionary<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Actions_AddElementToDictionary_Workbench_SpawnModuleEventArgs;

		private AddElementToDictionary<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Actions_AddElementToDictionary_Workbench_SpawnMotherboardEventArgs;

		private AddElementToDictionary<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Actions_AddElementToDictionary_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private AddElementToDictionary<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Actions_AddElementToDictionary_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private AddElementToDictionary<uint> NodeCanvas_Tasks_Actions_AddElementToDictionary_System_UInt32;

		private AddElementToDictionary<LayerMask> NodeCanvas_Tasks_Actions_AddElementToDictionary_UnityEngine_LayerMask;

		private AddElementToList<bool> NodeCanvas_Tasks_Actions_AddElementToList_System_Boolean;

		private AddElementToList<float> NodeCanvas_Tasks_Actions_AddElementToList_System_Single;

		private AddElementToList<int> NodeCanvas_Tasks_Actions_AddElementToList_System_Int32;

		private AddElementToList<Vector2> NodeCanvas_Tasks_Actions_AddElementToList_UnityEngine_Vector2;

		private AddElementToList<Vector3> NodeCanvas_Tasks_Actions_AddElementToList_UnityEngine_Vector3;

		private AddElementToList<Vector4> NodeCanvas_Tasks_Actions_AddElementToList_UnityEngine_Vector4;

		private AddElementToList<Quaternion> NodeCanvas_Tasks_Actions_AddElementToList_UnityEngine_Quaternion;

		private AddElementToList<Keyframe> NodeCanvas_Tasks_Actions_AddElementToList_UnityEngine_Keyframe;

		private AddElementToList<Bounds> NodeCanvas_Tasks_Actions_AddElementToList_UnityEngine_Bounds;

		private AddElementToList<Color> NodeCanvas_Tasks_Actions_AddElementToList_UnityEngine_Color;

		private AddElementToList<Rect> NodeCanvas_Tasks_Actions_AddElementToList_UnityEngine_Rect;

		private AddElementToList<ContactPoint> NodeCanvas_Tasks_Actions_AddElementToList_UnityEngine_ContactPoint;

		private AddElementToList<ContactPoint2D> NodeCanvas_Tasks_Actions_AddElementToList_UnityEngine_ContactPoint2D;

		private AddElementToList<RaycastHit> NodeCanvas_Tasks_Actions_AddElementToList_UnityEngine_RaycastHit;

		private AddElementToList<RaycastHit2D> NodeCanvas_Tasks_Actions_AddElementToList_UnityEngine_RaycastHit2D;

		private AddElementToList<Ray> NodeCanvas_Tasks_Actions_AddElementToList_UnityEngine_Ray;

		private AddElementToList<Space> NodeCanvas_Tasks_Actions_AddElementToList_UnityEngine_Space;

		private AddElementToList<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Actions_AddElementToList_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private AddElementToList<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Actions_AddElementToList_SceneManager_DestroyGadgetEventArgs;

		private AddElementToList<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Actions_AddElementToList_SceneManager_GetGadgetEventArgs;

		private AddElementToList<ModuleId> NodeCanvas_Tasks_Actions_AddElementToList_ModuleId;

		private AddElementToList<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Actions_AddElementToList_SceneManager_PrintGadgetEventArgs;

		private AddElementToList<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Actions_AddElementToList_Workbench_SpawnModuleEventArgs;

		private AddElementToList<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Actions_AddElementToList_Workbench_SpawnMotherboardEventArgs;

		private AddElementToList<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Actions_AddElementToList_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private AddElementToList<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Actions_AddElementToList_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private AddElementToList<uint> NodeCanvas_Tasks_Actions_AddElementToList_System_UInt32;

		private AddElementToList<LayerMask> NodeCanvas_Tasks_Actions_AddElementToList_UnityEngine_LayerMask;

		private GetDictionaryElement<bool> NodeCanvas_Tasks_Actions_GetDictionaryElement_System_Boolean;

		private GetDictionaryElement<float> NodeCanvas_Tasks_Actions_GetDictionaryElement_System_Single;

		private GetDictionaryElement<int> NodeCanvas_Tasks_Actions_GetDictionaryElement_System_Int32;

		private GetDictionaryElement<Vector2> NodeCanvas_Tasks_Actions_GetDictionaryElement_UnityEngine_Vector2;

		private GetDictionaryElement<Vector3> NodeCanvas_Tasks_Actions_GetDictionaryElement_UnityEngine_Vector3;

		private GetDictionaryElement<Vector4> NodeCanvas_Tasks_Actions_GetDictionaryElement_UnityEngine_Vector4;

		private GetDictionaryElement<Quaternion> NodeCanvas_Tasks_Actions_GetDictionaryElement_UnityEngine_Quaternion;

		private GetDictionaryElement<Keyframe> NodeCanvas_Tasks_Actions_GetDictionaryElement_UnityEngine_Keyframe;

		private GetDictionaryElement<Bounds> NodeCanvas_Tasks_Actions_GetDictionaryElement_UnityEngine_Bounds;

		private GetDictionaryElement<Color> NodeCanvas_Tasks_Actions_GetDictionaryElement_UnityEngine_Color;

		private GetDictionaryElement<Rect> NodeCanvas_Tasks_Actions_GetDictionaryElement_UnityEngine_Rect;

		private GetDictionaryElement<ContactPoint> NodeCanvas_Tasks_Actions_GetDictionaryElement_UnityEngine_ContactPoint;

		private GetDictionaryElement<ContactPoint2D> NodeCanvas_Tasks_Actions_GetDictionaryElement_UnityEngine_ContactPoint2D;

		private GetDictionaryElement<RaycastHit> NodeCanvas_Tasks_Actions_GetDictionaryElement_UnityEngine_RaycastHit;

		private GetDictionaryElement<RaycastHit2D> NodeCanvas_Tasks_Actions_GetDictionaryElement_UnityEngine_RaycastHit2D;

		private GetDictionaryElement<Ray> NodeCanvas_Tasks_Actions_GetDictionaryElement_UnityEngine_Ray;

		private GetDictionaryElement<Space> NodeCanvas_Tasks_Actions_GetDictionaryElement_UnityEngine_Space;

		private GetDictionaryElement<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Actions_GetDictionaryElement_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private GetDictionaryElement<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Actions_GetDictionaryElement_SceneManager_DestroyGadgetEventArgs;

		private GetDictionaryElement<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Actions_GetDictionaryElement_SceneManager_GetGadgetEventArgs;

		private GetDictionaryElement<ModuleId> NodeCanvas_Tasks_Actions_GetDictionaryElement_ModuleId;

		private GetDictionaryElement<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Actions_GetDictionaryElement_SceneManager_PrintGadgetEventArgs;

		private GetDictionaryElement<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Actions_GetDictionaryElement_Workbench_SpawnModuleEventArgs;

		private GetDictionaryElement<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Actions_GetDictionaryElement_Workbench_SpawnMotherboardEventArgs;

		private GetDictionaryElement<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Actions_GetDictionaryElement_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private GetDictionaryElement<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Actions_GetDictionaryElement_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private GetDictionaryElement<uint> NodeCanvas_Tasks_Actions_GetDictionaryElement_System_UInt32;

		private GetDictionaryElement<LayerMask> NodeCanvas_Tasks_Actions_GetDictionaryElement_UnityEngine_LayerMask;

		private GetIndexOfElement<bool> NodeCanvas_Tasks_Actions_GetIndexOfElement_System_Boolean;

		private GetIndexOfElement<float> NodeCanvas_Tasks_Actions_GetIndexOfElement_System_Single;

		private GetIndexOfElement<int> NodeCanvas_Tasks_Actions_GetIndexOfElement_System_Int32;

		private GetIndexOfElement<Vector2> NodeCanvas_Tasks_Actions_GetIndexOfElement_UnityEngine_Vector2;

		private GetIndexOfElement<Vector3> NodeCanvas_Tasks_Actions_GetIndexOfElement_UnityEngine_Vector3;

		private GetIndexOfElement<Vector4> NodeCanvas_Tasks_Actions_GetIndexOfElement_UnityEngine_Vector4;

		private GetIndexOfElement<Quaternion> NodeCanvas_Tasks_Actions_GetIndexOfElement_UnityEngine_Quaternion;

		private GetIndexOfElement<Keyframe> NodeCanvas_Tasks_Actions_GetIndexOfElement_UnityEngine_Keyframe;

		private GetIndexOfElement<Bounds> NodeCanvas_Tasks_Actions_GetIndexOfElement_UnityEngine_Bounds;

		private GetIndexOfElement<Color> NodeCanvas_Tasks_Actions_GetIndexOfElement_UnityEngine_Color;

		private GetIndexOfElement<Rect> NodeCanvas_Tasks_Actions_GetIndexOfElement_UnityEngine_Rect;

		private GetIndexOfElement<ContactPoint> NodeCanvas_Tasks_Actions_GetIndexOfElement_UnityEngine_ContactPoint;

		private GetIndexOfElement<ContactPoint2D> NodeCanvas_Tasks_Actions_GetIndexOfElement_UnityEngine_ContactPoint2D;

		private GetIndexOfElement<RaycastHit> NodeCanvas_Tasks_Actions_GetIndexOfElement_UnityEngine_RaycastHit;

		private GetIndexOfElement<RaycastHit2D> NodeCanvas_Tasks_Actions_GetIndexOfElement_UnityEngine_RaycastHit2D;

		private GetIndexOfElement<Ray> NodeCanvas_Tasks_Actions_GetIndexOfElement_UnityEngine_Ray;

		private GetIndexOfElement<Space> NodeCanvas_Tasks_Actions_GetIndexOfElement_UnityEngine_Space;

		private GetIndexOfElement<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Actions_GetIndexOfElement_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private GetIndexOfElement<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Actions_GetIndexOfElement_SceneManager_DestroyGadgetEventArgs;

		private GetIndexOfElement<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Actions_GetIndexOfElement_SceneManager_GetGadgetEventArgs;

		private GetIndexOfElement<ModuleId> NodeCanvas_Tasks_Actions_GetIndexOfElement_ModuleId;

		private GetIndexOfElement<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Actions_GetIndexOfElement_SceneManager_PrintGadgetEventArgs;

		private GetIndexOfElement<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Actions_GetIndexOfElement_Workbench_SpawnModuleEventArgs;

		private GetIndexOfElement<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Actions_GetIndexOfElement_Workbench_SpawnMotherboardEventArgs;

		private GetIndexOfElement<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Actions_GetIndexOfElement_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private GetIndexOfElement<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Actions_GetIndexOfElement_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private GetIndexOfElement<uint> NodeCanvas_Tasks_Actions_GetIndexOfElement_System_UInt32;

		private GetIndexOfElement<LayerMask> NodeCanvas_Tasks_Actions_GetIndexOfElement_UnityEngine_LayerMask;

		private InsertElementToList<bool> NodeCanvas_Tasks_Actions_InsertElementToList_System_Boolean;

		private InsertElementToList<float> NodeCanvas_Tasks_Actions_InsertElementToList_System_Single;

		private InsertElementToList<int> NodeCanvas_Tasks_Actions_InsertElementToList_System_Int32;

		private InsertElementToList<Vector2> NodeCanvas_Tasks_Actions_InsertElementToList_UnityEngine_Vector2;

		private InsertElementToList<Vector3> NodeCanvas_Tasks_Actions_InsertElementToList_UnityEngine_Vector3;

		private InsertElementToList<Vector4> NodeCanvas_Tasks_Actions_InsertElementToList_UnityEngine_Vector4;

		private InsertElementToList<Quaternion> NodeCanvas_Tasks_Actions_InsertElementToList_UnityEngine_Quaternion;

		private InsertElementToList<Keyframe> NodeCanvas_Tasks_Actions_InsertElementToList_UnityEngine_Keyframe;

		private InsertElementToList<Bounds> NodeCanvas_Tasks_Actions_InsertElementToList_UnityEngine_Bounds;

		private InsertElementToList<Color> NodeCanvas_Tasks_Actions_InsertElementToList_UnityEngine_Color;

		private InsertElementToList<Rect> NodeCanvas_Tasks_Actions_InsertElementToList_UnityEngine_Rect;

		private InsertElementToList<ContactPoint> NodeCanvas_Tasks_Actions_InsertElementToList_UnityEngine_ContactPoint;

		private InsertElementToList<ContactPoint2D> NodeCanvas_Tasks_Actions_InsertElementToList_UnityEngine_ContactPoint2D;

		private InsertElementToList<RaycastHit> NodeCanvas_Tasks_Actions_InsertElementToList_UnityEngine_RaycastHit;

		private InsertElementToList<RaycastHit2D> NodeCanvas_Tasks_Actions_InsertElementToList_UnityEngine_RaycastHit2D;

		private InsertElementToList<Ray> NodeCanvas_Tasks_Actions_InsertElementToList_UnityEngine_Ray;

		private InsertElementToList<Space> NodeCanvas_Tasks_Actions_InsertElementToList_UnityEngine_Space;

		private InsertElementToList<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Actions_InsertElementToList_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private InsertElementToList<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Actions_InsertElementToList_SceneManager_DestroyGadgetEventArgs;

		private InsertElementToList<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Actions_InsertElementToList_SceneManager_GetGadgetEventArgs;

		private InsertElementToList<ModuleId> NodeCanvas_Tasks_Actions_InsertElementToList_ModuleId;

		private InsertElementToList<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Actions_InsertElementToList_SceneManager_PrintGadgetEventArgs;

		private InsertElementToList<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Actions_InsertElementToList_Workbench_SpawnModuleEventArgs;

		private InsertElementToList<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Actions_InsertElementToList_Workbench_SpawnMotherboardEventArgs;

		private InsertElementToList<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Actions_InsertElementToList_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private InsertElementToList<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Actions_InsertElementToList_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private InsertElementToList<uint> NodeCanvas_Tasks_Actions_InsertElementToList_System_UInt32;

		private InsertElementToList<LayerMask> NodeCanvas_Tasks_Actions_InsertElementToList_UnityEngine_LayerMask;

		private PickListElement<bool> NodeCanvas_Tasks_Actions_PickListElement_System_Boolean;

		private PickListElement<float> NodeCanvas_Tasks_Actions_PickListElement_System_Single;

		private PickListElement<int> NodeCanvas_Tasks_Actions_PickListElement_System_Int32;

		private PickListElement<Vector2> NodeCanvas_Tasks_Actions_PickListElement_UnityEngine_Vector2;

		private PickListElement<Vector3> NodeCanvas_Tasks_Actions_PickListElement_UnityEngine_Vector3;

		private PickListElement<Vector4> NodeCanvas_Tasks_Actions_PickListElement_UnityEngine_Vector4;

		private PickListElement<Quaternion> NodeCanvas_Tasks_Actions_PickListElement_UnityEngine_Quaternion;

		private PickListElement<Keyframe> NodeCanvas_Tasks_Actions_PickListElement_UnityEngine_Keyframe;

		private PickListElement<Bounds> NodeCanvas_Tasks_Actions_PickListElement_UnityEngine_Bounds;

		private PickListElement<Color> NodeCanvas_Tasks_Actions_PickListElement_UnityEngine_Color;

		private PickListElement<Rect> NodeCanvas_Tasks_Actions_PickListElement_UnityEngine_Rect;

		private PickListElement<ContactPoint> NodeCanvas_Tasks_Actions_PickListElement_UnityEngine_ContactPoint;

		private PickListElement<ContactPoint2D> NodeCanvas_Tasks_Actions_PickListElement_UnityEngine_ContactPoint2D;

		private PickListElement<RaycastHit> NodeCanvas_Tasks_Actions_PickListElement_UnityEngine_RaycastHit;

		private PickListElement<RaycastHit2D> NodeCanvas_Tasks_Actions_PickListElement_UnityEngine_RaycastHit2D;

		private PickListElement<Ray> NodeCanvas_Tasks_Actions_PickListElement_UnityEngine_Ray;

		private PickListElement<Space> NodeCanvas_Tasks_Actions_PickListElement_UnityEngine_Space;

		private PickListElement<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Actions_PickListElement_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private PickListElement<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Actions_PickListElement_SceneManager_DestroyGadgetEventArgs;

		private PickListElement<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Actions_PickListElement_SceneManager_GetGadgetEventArgs;

		private PickListElement<ModuleId> NodeCanvas_Tasks_Actions_PickListElement_ModuleId;

		private PickListElement<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Actions_PickListElement_SceneManager_PrintGadgetEventArgs;

		private PickListElement<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Actions_PickListElement_Workbench_SpawnModuleEventArgs;

		private PickListElement<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Actions_PickListElement_Workbench_SpawnMotherboardEventArgs;

		private PickListElement<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Actions_PickListElement_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private PickListElement<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Actions_PickListElement_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private PickListElement<uint> NodeCanvas_Tasks_Actions_PickListElement_System_UInt32;

		private PickListElement<LayerMask> NodeCanvas_Tasks_Actions_PickListElement_UnityEngine_LayerMask;

		private PickRandomListElement<bool> NodeCanvas_Tasks_Actions_PickRandomListElement_System_Boolean;

		private PickRandomListElement<float> NodeCanvas_Tasks_Actions_PickRandomListElement_System_Single;

		private PickRandomListElement<int> NodeCanvas_Tasks_Actions_PickRandomListElement_System_Int32;

		private PickRandomListElement<Vector2> NodeCanvas_Tasks_Actions_PickRandomListElement_UnityEngine_Vector2;

		private PickRandomListElement<Vector3> NodeCanvas_Tasks_Actions_PickRandomListElement_UnityEngine_Vector3;

		private PickRandomListElement<Vector4> NodeCanvas_Tasks_Actions_PickRandomListElement_UnityEngine_Vector4;

		private PickRandomListElement<Quaternion> NodeCanvas_Tasks_Actions_PickRandomListElement_UnityEngine_Quaternion;

		private PickRandomListElement<Keyframe> NodeCanvas_Tasks_Actions_PickRandomListElement_UnityEngine_Keyframe;

		private PickRandomListElement<Bounds> NodeCanvas_Tasks_Actions_PickRandomListElement_UnityEngine_Bounds;

		private PickRandomListElement<Color> NodeCanvas_Tasks_Actions_PickRandomListElement_UnityEngine_Color;

		private PickRandomListElement<Rect> NodeCanvas_Tasks_Actions_PickRandomListElement_UnityEngine_Rect;

		private PickRandomListElement<ContactPoint> NodeCanvas_Tasks_Actions_PickRandomListElement_UnityEngine_ContactPoint;

		private PickRandomListElement<ContactPoint2D> NodeCanvas_Tasks_Actions_PickRandomListElement_UnityEngine_ContactPoint2D;

		private PickRandomListElement<RaycastHit> NodeCanvas_Tasks_Actions_PickRandomListElement_UnityEngine_RaycastHit;

		private PickRandomListElement<RaycastHit2D> NodeCanvas_Tasks_Actions_PickRandomListElement_UnityEngine_RaycastHit2D;

		private PickRandomListElement<Ray> NodeCanvas_Tasks_Actions_PickRandomListElement_UnityEngine_Ray;

		private PickRandomListElement<Space> NodeCanvas_Tasks_Actions_PickRandomListElement_UnityEngine_Space;

		private PickRandomListElement<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Actions_PickRandomListElement_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private PickRandomListElement<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Actions_PickRandomListElement_SceneManager_DestroyGadgetEventArgs;

		private PickRandomListElement<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Actions_PickRandomListElement_SceneManager_GetGadgetEventArgs;

		private PickRandomListElement<ModuleId> NodeCanvas_Tasks_Actions_PickRandomListElement_ModuleId;

		private PickRandomListElement<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Actions_PickRandomListElement_SceneManager_PrintGadgetEventArgs;

		private PickRandomListElement<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Actions_PickRandomListElement_Workbench_SpawnModuleEventArgs;

		private PickRandomListElement<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Actions_PickRandomListElement_Workbench_SpawnMotherboardEventArgs;

		private PickRandomListElement<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Actions_PickRandomListElement_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private PickRandomListElement<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Actions_PickRandomListElement_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private PickRandomListElement<uint> NodeCanvas_Tasks_Actions_PickRandomListElement_System_UInt32;

		private PickRandomListElement<LayerMask> NodeCanvas_Tasks_Actions_PickRandomListElement_UnityEngine_LayerMask;

		private RemoveElementFromList<bool> NodeCanvas_Tasks_Actions_RemoveElementFromList_System_Boolean;

		private RemoveElementFromList<float> NodeCanvas_Tasks_Actions_RemoveElementFromList_System_Single;

		private RemoveElementFromList<int> NodeCanvas_Tasks_Actions_RemoveElementFromList_System_Int32;

		private RemoveElementFromList<Vector2> NodeCanvas_Tasks_Actions_RemoveElementFromList_UnityEngine_Vector2;

		private RemoveElementFromList<Vector3> NodeCanvas_Tasks_Actions_RemoveElementFromList_UnityEngine_Vector3;

		private RemoveElementFromList<Vector4> NodeCanvas_Tasks_Actions_RemoveElementFromList_UnityEngine_Vector4;

		private RemoveElementFromList<Quaternion> NodeCanvas_Tasks_Actions_RemoveElementFromList_UnityEngine_Quaternion;

		private RemoveElementFromList<Keyframe> NodeCanvas_Tasks_Actions_RemoveElementFromList_UnityEngine_Keyframe;

		private RemoveElementFromList<Bounds> NodeCanvas_Tasks_Actions_RemoveElementFromList_UnityEngine_Bounds;

		private RemoveElementFromList<Color> NodeCanvas_Tasks_Actions_RemoveElementFromList_UnityEngine_Color;

		private RemoveElementFromList<Rect> NodeCanvas_Tasks_Actions_RemoveElementFromList_UnityEngine_Rect;

		private RemoveElementFromList<ContactPoint> NodeCanvas_Tasks_Actions_RemoveElementFromList_UnityEngine_ContactPoint;

		private RemoveElementFromList<ContactPoint2D> NodeCanvas_Tasks_Actions_RemoveElementFromList_UnityEngine_ContactPoint2D;

		private RemoveElementFromList<RaycastHit> NodeCanvas_Tasks_Actions_RemoveElementFromList_UnityEngine_RaycastHit;

		private RemoveElementFromList<RaycastHit2D> NodeCanvas_Tasks_Actions_RemoveElementFromList_UnityEngine_RaycastHit2D;

		private RemoveElementFromList<Ray> NodeCanvas_Tasks_Actions_RemoveElementFromList_UnityEngine_Ray;

		private RemoveElementFromList<Space> NodeCanvas_Tasks_Actions_RemoveElementFromList_UnityEngine_Space;

		private RemoveElementFromList<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Actions_RemoveElementFromList_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private RemoveElementFromList<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Actions_RemoveElementFromList_SceneManager_DestroyGadgetEventArgs;

		private RemoveElementFromList<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Actions_RemoveElementFromList_SceneManager_GetGadgetEventArgs;

		private RemoveElementFromList<ModuleId> NodeCanvas_Tasks_Actions_RemoveElementFromList_ModuleId;

		private RemoveElementFromList<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Actions_RemoveElementFromList_SceneManager_PrintGadgetEventArgs;

		private RemoveElementFromList<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Actions_RemoveElementFromList_Workbench_SpawnModuleEventArgs;

		private RemoveElementFromList<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Actions_RemoveElementFromList_Workbench_SpawnMotherboardEventArgs;

		private RemoveElementFromList<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Actions_RemoveElementFromList_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private RemoveElementFromList<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Actions_RemoveElementFromList_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private RemoveElementFromList<uint> NodeCanvas_Tasks_Actions_RemoveElementFromList_System_UInt32;

		private RemoveElementFromList<LayerMask> NodeCanvas_Tasks_Actions_RemoveElementFromList_UnityEngine_LayerMask;

		private SendEvent<bool> NodeCanvas_Tasks_Actions_SendEvent_System_Boolean;

		private SendEvent<float> NodeCanvas_Tasks_Actions_SendEvent_System_Single;

		private SendEvent<int> NodeCanvas_Tasks_Actions_SendEvent_System_Int32;

		private SendEvent<Vector2> NodeCanvas_Tasks_Actions_SendEvent_UnityEngine_Vector2;

		private SendEvent<Vector3> NodeCanvas_Tasks_Actions_SendEvent_UnityEngine_Vector3;

		private SendEvent<Vector4> NodeCanvas_Tasks_Actions_SendEvent_UnityEngine_Vector4;

		private SendEvent<Quaternion> NodeCanvas_Tasks_Actions_SendEvent_UnityEngine_Quaternion;

		private SendEvent<Keyframe> NodeCanvas_Tasks_Actions_SendEvent_UnityEngine_Keyframe;

		private SendEvent<Bounds> NodeCanvas_Tasks_Actions_SendEvent_UnityEngine_Bounds;

		private SendEvent<Color> NodeCanvas_Tasks_Actions_SendEvent_UnityEngine_Color;

		private SendEvent<Rect> NodeCanvas_Tasks_Actions_SendEvent_UnityEngine_Rect;

		private SendEvent<ContactPoint> NodeCanvas_Tasks_Actions_SendEvent_UnityEngine_ContactPoint;

		private SendEvent<ContactPoint2D> NodeCanvas_Tasks_Actions_SendEvent_UnityEngine_ContactPoint2D;

		private SendEvent<RaycastHit> NodeCanvas_Tasks_Actions_SendEvent_UnityEngine_RaycastHit;

		private SendEvent<RaycastHit2D> NodeCanvas_Tasks_Actions_SendEvent_UnityEngine_RaycastHit2D;

		private SendEvent<Ray> NodeCanvas_Tasks_Actions_SendEvent_UnityEngine_Ray;

		private SendEvent<Space> NodeCanvas_Tasks_Actions_SendEvent_UnityEngine_Space;

		private SendEvent<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Actions_SendEvent_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private SendEvent<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Actions_SendEvent_SceneManager_DestroyGadgetEventArgs;

		private SendEvent<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Actions_SendEvent_SceneManager_GetGadgetEventArgs;

		private SendEvent<ModuleId> NodeCanvas_Tasks_Actions_SendEvent_ModuleId;

		private SendEvent<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Actions_SendEvent_SceneManager_PrintGadgetEventArgs;

		private SendEvent<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Actions_SendEvent_Workbench_SpawnModuleEventArgs;

		private SendEvent<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Actions_SendEvent_Workbench_SpawnMotherboardEventArgs;

		private SendEvent<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Actions_SendEvent_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private SendEvent<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Actions_SendEvent_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private SendEvent<uint> NodeCanvas_Tasks_Actions_SendEvent_System_UInt32;

		private SendEvent<LayerMask> NodeCanvas_Tasks_Actions_SendEvent_UnityEngine_LayerMask;

		private SendEventToObjects<bool> NodeCanvas_Tasks_Actions_SendEventToObjects_System_Boolean;

		private SendEventToObjects<float> NodeCanvas_Tasks_Actions_SendEventToObjects_System_Single;

		private SendEventToObjects<int> NodeCanvas_Tasks_Actions_SendEventToObjects_System_Int32;

		private SendEventToObjects<Vector2> NodeCanvas_Tasks_Actions_SendEventToObjects_UnityEngine_Vector2;

		private SendEventToObjects<Vector3> NodeCanvas_Tasks_Actions_SendEventToObjects_UnityEngine_Vector3;

		private SendEventToObjects<Vector4> NodeCanvas_Tasks_Actions_SendEventToObjects_UnityEngine_Vector4;

		private SendEventToObjects<Quaternion> NodeCanvas_Tasks_Actions_SendEventToObjects_UnityEngine_Quaternion;

		private SendEventToObjects<Keyframe> NodeCanvas_Tasks_Actions_SendEventToObjects_UnityEngine_Keyframe;

		private SendEventToObjects<Bounds> NodeCanvas_Tasks_Actions_SendEventToObjects_UnityEngine_Bounds;

		private SendEventToObjects<Color> NodeCanvas_Tasks_Actions_SendEventToObjects_UnityEngine_Color;

		private SendEventToObjects<Rect> NodeCanvas_Tasks_Actions_SendEventToObjects_UnityEngine_Rect;

		private SendEventToObjects<ContactPoint> NodeCanvas_Tasks_Actions_SendEventToObjects_UnityEngine_ContactPoint;

		private SendEventToObjects<ContactPoint2D> NodeCanvas_Tasks_Actions_SendEventToObjects_UnityEngine_ContactPoint2D;

		private SendEventToObjects<RaycastHit> NodeCanvas_Tasks_Actions_SendEventToObjects_UnityEngine_RaycastHit;

		private SendEventToObjects<RaycastHit2D> NodeCanvas_Tasks_Actions_SendEventToObjects_UnityEngine_RaycastHit2D;

		private SendEventToObjects<Ray> NodeCanvas_Tasks_Actions_SendEventToObjects_UnityEngine_Ray;

		private SendEventToObjects<Space> NodeCanvas_Tasks_Actions_SendEventToObjects_UnityEngine_Space;

		private SendEventToObjects<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Actions_SendEventToObjects_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private SendEventToObjects<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Actions_SendEventToObjects_SceneManager_DestroyGadgetEventArgs;

		private SendEventToObjects<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Actions_SendEventToObjects_SceneManager_GetGadgetEventArgs;

		private SendEventToObjects<ModuleId> NodeCanvas_Tasks_Actions_SendEventToObjects_ModuleId;

		private SendEventToObjects<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Actions_SendEventToObjects_SceneManager_PrintGadgetEventArgs;

		private SendEventToObjects<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Actions_SendEventToObjects_Workbench_SpawnModuleEventArgs;

		private SendEventToObjects<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Actions_SendEventToObjects_Workbench_SpawnMotherboardEventArgs;

		private SendEventToObjects<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Actions_SendEventToObjects_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private SendEventToObjects<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Actions_SendEventToObjects_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private SendEventToObjects<uint> NodeCanvas_Tasks_Actions_SendEventToObjects_System_UInt32;

		private SendEventToObjects<LayerMask> NodeCanvas_Tasks_Actions_SendEventToObjects_UnityEngine_LayerMask;

		private SendMessage<bool> NodeCanvas_Tasks_Actions_SendMessage_System_Boolean;

		private SendMessage<float> NodeCanvas_Tasks_Actions_SendMessage_System_Single;

		private SendMessage<int> NodeCanvas_Tasks_Actions_SendMessage_System_Int32;

		private SendMessage<Vector2> NodeCanvas_Tasks_Actions_SendMessage_UnityEngine_Vector2;

		private SendMessage<Vector3> NodeCanvas_Tasks_Actions_SendMessage_UnityEngine_Vector3;

		private SendMessage<Vector4> NodeCanvas_Tasks_Actions_SendMessage_UnityEngine_Vector4;

		private SendMessage<Quaternion> NodeCanvas_Tasks_Actions_SendMessage_UnityEngine_Quaternion;

		private SendMessage<Keyframe> NodeCanvas_Tasks_Actions_SendMessage_UnityEngine_Keyframe;

		private SendMessage<Bounds> NodeCanvas_Tasks_Actions_SendMessage_UnityEngine_Bounds;

		private SendMessage<Color> NodeCanvas_Tasks_Actions_SendMessage_UnityEngine_Color;

		private SendMessage<Rect> NodeCanvas_Tasks_Actions_SendMessage_UnityEngine_Rect;

		private SendMessage<ContactPoint> NodeCanvas_Tasks_Actions_SendMessage_UnityEngine_ContactPoint;

		private SendMessage<ContactPoint2D> NodeCanvas_Tasks_Actions_SendMessage_UnityEngine_ContactPoint2D;

		private SendMessage<RaycastHit> NodeCanvas_Tasks_Actions_SendMessage_UnityEngine_RaycastHit;

		private SendMessage<RaycastHit2D> NodeCanvas_Tasks_Actions_SendMessage_UnityEngine_RaycastHit2D;

		private SendMessage<Ray> NodeCanvas_Tasks_Actions_SendMessage_UnityEngine_Ray;

		private SendMessage<Space> NodeCanvas_Tasks_Actions_SendMessage_UnityEngine_Space;

		private SendMessage<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Actions_SendMessage_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private SendMessage<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Actions_SendMessage_SceneManager_DestroyGadgetEventArgs;

		private SendMessage<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Actions_SendMessage_SceneManager_GetGadgetEventArgs;

		private SendMessage<ModuleId> NodeCanvas_Tasks_Actions_SendMessage_ModuleId;

		private SendMessage<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Actions_SendMessage_SceneManager_PrintGadgetEventArgs;

		private SendMessage<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Actions_SendMessage_Workbench_SpawnModuleEventArgs;

		private SendMessage<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Actions_SendMessage_Workbench_SpawnMotherboardEventArgs;

		private SendMessage<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Actions_SendMessage_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private SendMessage<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Actions_SendMessage_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private SendMessage<uint> NodeCanvas_Tasks_Actions_SendMessage_System_UInt32;

		private SendMessage<LayerMask> NodeCanvas_Tasks_Actions_SendMessage_UnityEngine_LayerMask;

		private SetListElement<bool> NodeCanvas_Tasks_Actions_SetListElement_System_Boolean;

		private SetListElement<float> NodeCanvas_Tasks_Actions_SetListElement_System_Single;

		private SetListElement<int> NodeCanvas_Tasks_Actions_SetListElement_System_Int32;

		private SetListElement<Vector2> NodeCanvas_Tasks_Actions_SetListElement_UnityEngine_Vector2;

		private SetListElement<Vector3> NodeCanvas_Tasks_Actions_SetListElement_UnityEngine_Vector3;

		private SetListElement<Vector4> NodeCanvas_Tasks_Actions_SetListElement_UnityEngine_Vector4;

		private SetListElement<Quaternion> NodeCanvas_Tasks_Actions_SetListElement_UnityEngine_Quaternion;

		private SetListElement<Keyframe> NodeCanvas_Tasks_Actions_SetListElement_UnityEngine_Keyframe;

		private SetListElement<Bounds> NodeCanvas_Tasks_Actions_SetListElement_UnityEngine_Bounds;

		private SetListElement<Color> NodeCanvas_Tasks_Actions_SetListElement_UnityEngine_Color;

		private SetListElement<Rect> NodeCanvas_Tasks_Actions_SetListElement_UnityEngine_Rect;

		private SetListElement<ContactPoint> NodeCanvas_Tasks_Actions_SetListElement_UnityEngine_ContactPoint;

		private SetListElement<ContactPoint2D> NodeCanvas_Tasks_Actions_SetListElement_UnityEngine_ContactPoint2D;

		private SetListElement<RaycastHit> NodeCanvas_Tasks_Actions_SetListElement_UnityEngine_RaycastHit;

		private SetListElement<RaycastHit2D> NodeCanvas_Tasks_Actions_SetListElement_UnityEngine_RaycastHit2D;

		private SetListElement<Ray> NodeCanvas_Tasks_Actions_SetListElement_UnityEngine_Ray;

		private SetListElement<Space> NodeCanvas_Tasks_Actions_SetListElement_UnityEngine_Space;

		private SetListElement<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Actions_SetListElement_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private SetListElement<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Actions_SetListElement_SceneManager_DestroyGadgetEventArgs;

		private SetListElement<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Actions_SetListElement_SceneManager_GetGadgetEventArgs;

		private SetListElement<ModuleId> NodeCanvas_Tasks_Actions_SetListElement_ModuleId;

		private SetListElement<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Actions_SetListElement_SceneManager_PrintGadgetEventArgs;

		private SetListElement<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Actions_SetListElement_Workbench_SpawnModuleEventArgs;

		private SetListElement<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Actions_SetListElement_Workbench_SpawnMotherboardEventArgs;

		private SetListElement<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Actions_SetListElement_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private SetListElement<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Actions_SetListElement_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private SetListElement<uint> NodeCanvas_Tasks_Actions_SetListElement_System_UInt32;

		private SetListElement<LayerMask> NodeCanvas_Tasks_Actions_SetListElement_UnityEngine_LayerMask;

		private SetVariable<bool> NodeCanvas_Tasks_Actions_SetVariable_System_Boolean;

		private SetVariable<float> NodeCanvas_Tasks_Actions_SetVariable_System_Single;

		private SetVariable<int> NodeCanvas_Tasks_Actions_SetVariable_System_Int32;

		private SetVariable<Vector2> NodeCanvas_Tasks_Actions_SetVariable_UnityEngine_Vector2;

		private SetVariable<Vector3> NodeCanvas_Tasks_Actions_SetVariable_UnityEngine_Vector3;

		private SetVariable<Vector4> NodeCanvas_Tasks_Actions_SetVariable_UnityEngine_Vector4;

		private SetVariable<Quaternion> NodeCanvas_Tasks_Actions_SetVariable_UnityEngine_Quaternion;

		private SetVariable<Keyframe> NodeCanvas_Tasks_Actions_SetVariable_UnityEngine_Keyframe;

		private SetVariable<Bounds> NodeCanvas_Tasks_Actions_SetVariable_UnityEngine_Bounds;

		private SetVariable<Color> NodeCanvas_Tasks_Actions_SetVariable_UnityEngine_Color;

		private SetVariable<Rect> NodeCanvas_Tasks_Actions_SetVariable_UnityEngine_Rect;

		private SetVariable<ContactPoint> NodeCanvas_Tasks_Actions_SetVariable_UnityEngine_ContactPoint;

		private SetVariable<ContactPoint2D> NodeCanvas_Tasks_Actions_SetVariable_UnityEngine_ContactPoint2D;

		private SetVariable<RaycastHit> NodeCanvas_Tasks_Actions_SetVariable_UnityEngine_RaycastHit;

		private SetVariable<RaycastHit2D> NodeCanvas_Tasks_Actions_SetVariable_UnityEngine_RaycastHit2D;

		private SetVariable<Ray> NodeCanvas_Tasks_Actions_SetVariable_UnityEngine_Ray;

		private SetVariable<Space> NodeCanvas_Tasks_Actions_SetVariable_UnityEngine_Space;

		private SetVariable<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Actions_SetVariable_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private SetVariable<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Actions_SetVariable_SceneManager_DestroyGadgetEventArgs;

		private SetVariable<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Actions_SetVariable_SceneManager_GetGadgetEventArgs;

		private SetVariable<ModuleId> NodeCanvas_Tasks_Actions_SetVariable_ModuleId;

		private SetVariable<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Actions_SetVariable_SceneManager_PrintGadgetEventArgs;

		private SetVariable<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Actions_SetVariable_Workbench_SpawnModuleEventArgs;

		private SetVariable<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Actions_SetVariable_Workbench_SpawnMotherboardEventArgs;

		private SetVariable<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Actions_SetVariable_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private SetVariable<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Actions_SetVariable_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private SetVariable<uint> NodeCanvas_Tasks_Actions_SetVariable_System_UInt32;

		private SetVariable<LayerMask> NodeCanvas_Tasks_Actions_SetVariable_UnityEngine_LayerMask;

		private CheckCSharpEvent<bool> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_System_Boolean;

		private CheckCSharpEvent<float> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_System_Single;

		private CheckCSharpEvent<int> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_System_Int32;

		private CheckCSharpEvent<Vector2> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_UnityEngine_Vector2;

		private CheckCSharpEvent<Vector3> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_UnityEngine_Vector3;

		private CheckCSharpEvent<Vector4> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_UnityEngine_Vector4;

		private CheckCSharpEvent<Quaternion> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_UnityEngine_Quaternion;

		private CheckCSharpEvent<Keyframe> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_UnityEngine_Keyframe;

		private CheckCSharpEvent<Bounds> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_UnityEngine_Bounds;

		private CheckCSharpEvent<Color> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_UnityEngine_Color;

		private CheckCSharpEvent<Rect> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_UnityEngine_Rect;

		private CheckCSharpEvent<ContactPoint> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_UnityEngine_ContactPoint;

		private CheckCSharpEvent<ContactPoint2D> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_UnityEngine_ContactPoint2D;

		private CheckCSharpEvent<RaycastHit> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_UnityEngine_RaycastHit;

		private CheckCSharpEvent<RaycastHit2D> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_UnityEngine_RaycastHit2D;

		private CheckCSharpEvent<Ray> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_UnityEngine_Ray;

		private CheckCSharpEvent<Space> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_UnityEngine_Space;

		private CheckCSharpEvent<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private CheckCSharpEvent<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_SceneManager_DestroyGadgetEventArgs;

		private CheckCSharpEvent<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_SceneManager_GetGadgetEventArgs;

		private CheckCSharpEvent<ModuleId> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_ModuleId;

		private CheckCSharpEvent<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_SceneManager_PrintGadgetEventArgs;

		private CheckCSharpEvent<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_Workbench_SpawnModuleEventArgs;

		private CheckCSharpEvent<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_Workbench_SpawnMotherboardEventArgs;

		private CheckCSharpEvent<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private CheckCSharpEvent<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private CheckCSharpEvent<uint> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_System_UInt32;

		private CheckCSharpEvent<LayerMask> NodeCanvas_Tasks_Conditions_CheckCSharpEvent_UnityEngine_LayerMask;

		private CheckCSharpEventValue<bool> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_System_Boolean;

		private CheckCSharpEventValue<float> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_System_Single;

		private CheckCSharpEventValue<int> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_System_Int32;

		private CheckCSharpEventValue<Vector2> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_UnityEngine_Vector2;

		private CheckCSharpEventValue<Vector3> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_UnityEngine_Vector3;

		private CheckCSharpEventValue<Vector4> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_UnityEngine_Vector4;

		private CheckCSharpEventValue<Quaternion> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_UnityEngine_Quaternion;

		private CheckCSharpEventValue<Keyframe> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_UnityEngine_Keyframe;

		private CheckCSharpEventValue<Bounds> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_UnityEngine_Bounds;

		private CheckCSharpEventValue<Color> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_UnityEngine_Color;

		private CheckCSharpEventValue<Rect> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_UnityEngine_Rect;

		private CheckCSharpEventValue<ContactPoint> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_UnityEngine_ContactPoint;

		private CheckCSharpEventValue<ContactPoint2D> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_UnityEngine_ContactPoint2D;

		private CheckCSharpEventValue<RaycastHit> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_UnityEngine_RaycastHit;

		private CheckCSharpEventValue<RaycastHit2D> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_UnityEngine_RaycastHit2D;

		private CheckCSharpEventValue<Ray> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_UnityEngine_Ray;

		private CheckCSharpEventValue<Space> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_UnityEngine_Space;

		private CheckCSharpEventValue<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private CheckCSharpEventValue<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_SceneManager_DestroyGadgetEventArgs;

		private CheckCSharpEventValue<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_SceneManager_GetGadgetEventArgs;

		private CheckCSharpEventValue<ModuleId> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_ModuleId;

		private CheckCSharpEventValue<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_SceneManager_PrintGadgetEventArgs;

		private CheckCSharpEventValue<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_Workbench_SpawnModuleEventArgs;

		private CheckCSharpEventValue<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_Workbench_SpawnMotherboardEventArgs;

		private CheckCSharpEventValue<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private CheckCSharpEventValue<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private CheckCSharpEventValue<uint> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_System_UInt32;

		private CheckCSharpEventValue<LayerMask> NodeCanvas_Tasks_Conditions_CheckCSharpEventValue_UnityEngine_LayerMask;

		private CheckEvent<bool> NodeCanvas_Tasks_Conditions_CheckEvent_System_Boolean;

		private CheckEvent<float> NodeCanvas_Tasks_Conditions_CheckEvent_System_Single;

		private CheckEvent<int> NodeCanvas_Tasks_Conditions_CheckEvent_System_Int32;

		private CheckEvent<Vector2> NodeCanvas_Tasks_Conditions_CheckEvent_UnityEngine_Vector2;

		private CheckEvent<Vector3> NodeCanvas_Tasks_Conditions_CheckEvent_UnityEngine_Vector3;

		private CheckEvent<Vector4> NodeCanvas_Tasks_Conditions_CheckEvent_UnityEngine_Vector4;

		private CheckEvent<Quaternion> NodeCanvas_Tasks_Conditions_CheckEvent_UnityEngine_Quaternion;

		private CheckEvent<Keyframe> NodeCanvas_Tasks_Conditions_CheckEvent_UnityEngine_Keyframe;

		private CheckEvent<Bounds> NodeCanvas_Tasks_Conditions_CheckEvent_UnityEngine_Bounds;

		private CheckEvent<Color> NodeCanvas_Tasks_Conditions_CheckEvent_UnityEngine_Color;

		private CheckEvent<Rect> NodeCanvas_Tasks_Conditions_CheckEvent_UnityEngine_Rect;

		private CheckEvent<ContactPoint> NodeCanvas_Tasks_Conditions_CheckEvent_UnityEngine_ContactPoint;

		private CheckEvent<ContactPoint2D> NodeCanvas_Tasks_Conditions_CheckEvent_UnityEngine_ContactPoint2D;

		private CheckEvent<RaycastHit> NodeCanvas_Tasks_Conditions_CheckEvent_UnityEngine_RaycastHit;

		private CheckEvent<RaycastHit2D> NodeCanvas_Tasks_Conditions_CheckEvent_UnityEngine_RaycastHit2D;

		private CheckEvent<Ray> NodeCanvas_Tasks_Conditions_CheckEvent_UnityEngine_Ray;

		private CheckEvent<Space> NodeCanvas_Tasks_Conditions_CheckEvent_UnityEngine_Space;

		private CheckEvent<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Conditions_CheckEvent_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private CheckEvent<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckEvent_SceneManager_DestroyGadgetEventArgs;

		private CheckEvent<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckEvent_SceneManager_GetGadgetEventArgs;

		private CheckEvent<ModuleId> NodeCanvas_Tasks_Conditions_CheckEvent_ModuleId;

		private CheckEvent<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckEvent_SceneManager_PrintGadgetEventArgs;

		private CheckEvent<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Conditions_CheckEvent_Workbench_SpawnModuleEventArgs;

		private CheckEvent<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Conditions_CheckEvent_Workbench_SpawnMotherboardEventArgs;

		private CheckEvent<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Conditions_CheckEvent_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private CheckEvent<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Conditions_CheckEvent_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private CheckEvent<uint> NodeCanvas_Tasks_Conditions_CheckEvent_System_UInt32;

		private CheckEvent<LayerMask> NodeCanvas_Tasks_Conditions_CheckEvent_UnityEngine_LayerMask;

		private CheckEventValue<bool> NodeCanvas_Tasks_Conditions_CheckEventValue_System_Boolean;

		private CheckEventValue<float> NodeCanvas_Tasks_Conditions_CheckEventValue_System_Single;

		private CheckEventValue<int> NodeCanvas_Tasks_Conditions_CheckEventValue_System_Int32;

		private CheckEventValue<Vector2> NodeCanvas_Tasks_Conditions_CheckEventValue_UnityEngine_Vector2;

		private CheckEventValue<Vector3> NodeCanvas_Tasks_Conditions_CheckEventValue_UnityEngine_Vector3;

		private CheckEventValue<Vector4> NodeCanvas_Tasks_Conditions_CheckEventValue_UnityEngine_Vector4;

		private CheckEventValue<Quaternion> NodeCanvas_Tasks_Conditions_CheckEventValue_UnityEngine_Quaternion;

		private CheckEventValue<Keyframe> NodeCanvas_Tasks_Conditions_CheckEventValue_UnityEngine_Keyframe;

		private CheckEventValue<Bounds> NodeCanvas_Tasks_Conditions_CheckEventValue_UnityEngine_Bounds;

		private CheckEventValue<Color> NodeCanvas_Tasks_Conditions_CheckEventValue_UnityEngine_Color;

		private CheckEventValue<Rect> NodeCanvas_Tasks_Conditions_CheckEventValue_UnityEngine_Rect;

		private CheckEventValue<ContactPoint> NodeCanvas_Tasks_Conditions_CheckEventValue_UnityEngine_ContactPoint;

		private CheckEventValue<ContactPoint2D> NodeCanvas_Tasks_Conditions_CheckEventValue_UnityEngine_ContactPoint2D;

		private CheckEventValue<RaycastHit> NodeCanvas_Tasks_Conditions_CheckEventValue_UnityEngine_RaycastHit;

		private CheckEventValue<RaycastHit2D> NodeCanvas_Tasks_Conditions_CheckEventValue_UnityEngine_RaycastHit2D;

		private CheckEventValue<Ray> NodeCanvas_Tasks_Conditions_CheckEventValue_UnityEngine_Ray;

		private CheckEventValue<Space> NodeCanvas_Tasks_Conditions_CheckEventValue_UnityEngine_Space;

		private CheckEventValue<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Conditions_CheckEventValue_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private CheckEventValue<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckEventValue_SceneManager_DestroyGadgetEventArgs;

		private CheckEventValue<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckEventValue_SceneManager_GetGadgetEventArgs;

		private CheckEventValue<ModuleId> NodeCanvas_Tasks_Conditions_CheckEventValue_ModuleId;

		private CheckEventValue<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckEventValue_SceneManager_PrintGadgetEventArgs;

		private CheckEventValue<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Conditions_CheckEventValue_Workbench_SpawnModuleEventArgs;

		private CheckEventValue<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Conditions_CheckEventValue_Workbench_SpawnMotherboardEventArgs;

		private CheckEventValue<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Conditions_CheckEventValue_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private CheckEventValue<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Conditions_CheckEventValue_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private CheckEventValue<uint> NodeCanvas_Tasks_Conditions_CheckEventValue_System_UInt32;

		private CheckEventValue<LayerMask> NodeCanvas_Tasks_Conditions_CheckEventValue_UnityEngine_LayerMask;

		private CheckUnityEvent<bool> NodeCanvas_Tasks_Conditions_CheckUnityEvent_System_Boolean;

		private CheckUnityEvent<float> NodeCanvas_Tasks_Conditions_CheckUnityEvent_System_Single;

		private CheckUnityEvent<int> NodeCanvas_Tasks_Conditions_CheckUnityEvent_System_Int32;

		private CheckUnityEvent<Vector2> NodeCanvas_Tasks_Conditions_CheckUnityEvent_UnityEngine_Vector2;

		private CheckUnityEvent<Vector3> NodeCanvas_Tasks_Conditions_CheckUnityEvent_UnityEngine_Vector3;

		private CheckUnityEvent<Vector4> NodeCanvas_Tasks_Conditions_CheckUnityEvent_UnityEngine_Vector4;

		private CheckUnityEvent<Quaternion> NodeCanvas_Tasks_Conditions_CheckUnityEvent_UnityEngine_Quaternion;

		private CheckUnityEvent<Keyframe> NodeCanvas_Tasks_Conditions_CheckUnityEvent_UnityEngine_Keyframe;

		private CheckUnityEvent<Bounds> NodeCanvas_Tasks_Conditions_CheckUnityEvent_UnityEngine_Bounds;

		private CheckUnityEvent<Color> NodeCanvas_Tasks_Conditions_CheckUnityEvent_UnityEngine_Color;

		private CheckUnityEvent<Rect> NodeCanvas_Tasks_Conditions_CheckUnityEvent_UnityEngine_Rect;

		private CheckUnityEvent<ContactPoint> NodeCanvas_Tasks_Conditions_CheckUnityEvent_UnityEngine_ContactPoint;

		private CheckUnityEvent<ContactPoint2D> NodeCanvas_Tasks_Conditions_CheckUnityEvent_UnityEngine_ContactPoint2D;

		private CheckUnityEvent<RaycastHit> NodeCanvas_Tasks_Conditions_CheckUnityEvent_UnityEngine_RaycastHit;

		private CheckUnityEvent<RaycastHit2D> NodeCanvas_Tasks_Conditions_CheckUnityEvent_UnityEngine_RaycastHit2D;

		private CheckUnityEvent<Ray> NodeCanvas_Tasks_Conditions_CheckUnityEvent_UnityEngine_Ray;

		private CheckUnityEvent<Space> NodeCanvas_Tasks_Conditions_CheckUnityEvent_UnityEngine_Space;

		private CheckUnityEvent<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Conditions_CheckUnityEvent_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private CheckUnityEvent<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckUnityEvent_SceneManager_DestroyGadgetEventArgs;

		private CheckUnityEvent<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckUnityEvent_SceneManager_GetGadgetEventArgs;

		private CheckUnityEvent<ModuleId> NodeCanvas_Tasks_Conditions_CheckUnityEvent_ModuleId;

		private CheckUnityEvent<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckUnityEvent_SceneManager_PrintGadgetEventArgs;

		private CheckUnityEvent<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Conditions_CheckUnityEvent_Workbench_SpawnModuleEventArgs;

		private CheckUnityEvent<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Conditions_CheckUnityEvent_Workbench_SpawnMotherboardEventArgs;

		private CheckUnityEvent<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Conditions_CheckUnityEvent_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private CheckUnityEvent<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Conditions_CheckUnityEvent_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private CheckUnityEvent<uint> NodeCanvas_Tasks_Conditions_CheckUnityEvent_System_UInt32;

		private CheckUnityEvent<LayerMask> NodeCanvas_Tasks_Conditions_CheckUnityEvent_UnityEngine_LayerMask;

		private CheckUnityEventValue<bool> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_System_Boolean;

		private CheckUnityEventValue<float> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_System_Single;

		private CheckUnityEventValue<int> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_System_Int32;

		private CheckUnityEventValue<Vector2> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_UnityEngine_Vector2;

		private CheckUnityEventValue<Vector3> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_UnityEngine_Vector3;

		private CheckUnityEventValue<Vector4> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_UnityEngine_Vector4;

		private CheckUnityEventValue<Quaternion> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_UnityEngine_Quaternion;

		private CheckUnityEventValue<Keyframe> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_UnityEngine_Keyframe;

		private CheckUnityEventValue<Bounds> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_UnityEngine_Bounds;

		private CheckUnityEventValue<Color> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_UnityEngine_Color;

		private CheckUnityEventValue<Rect> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_UnityEngine_Rect;

		private CheckUnityEventValue<ContactPoint> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_UnityEngine_ContactPoint;

		private CheckUnityEventValue<ContactPoint2D> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_UnityEngine_ContactPoint2D;

		private CheckUnityEventValue<RaycastHit> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_UnityEngine_RaycastHit;

		private CheckUnityEventValue<RaycastHit2D> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_UnityEngine_RaycastHit2D;

		private CheckUnityEventValue<Ray> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_UnityEngine_Ray;

		private CheckUnityEventValue<Space> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_UnityEngine_Space;

		private CheckUnityEventValue<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private CheckUnityEventValue<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_SceneManager_DestroyGadgetEventArgs;

		private CheckUnityEventValue<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_SceneManager_GetGadgetEventArgs;

		private CheckUnityEventValue<ModuleId> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_ModuleId;

		private CheckUnityEventValue<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_SceneManager_PrintGadgetEventArgs;

		private CheckUnityEventValue<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_Workbench_SpawnModuleEventArgs;

		private CheckUnityEventValue<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_Workbench_SpawnMotherboardEventArgs;

		private CheckUnityEventValue<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private CheckUnityEventValue<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private CheckUnityEventValue<uint> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_System_UInt32;

		private CheckUnityEventValue<LayerMask> NodeCanvas_Tasks_Conditions_CheckUnityEventValue_UnityEngine_LayerMask;

		private CheckVariable<bool> NodeCanvas_Tasks_Conditions_CheckVariable_System_Boolean;

		private CheckVariable<float> NodeCanvas_Tasks_Conditions_CheckVariable_System_Single;

		private CheckVariable<int> NodeCanvas_Tasks_Conditions_CheckVariable_System_Int32;

		private CheckVariable<Vector2> NodeCanvas_Tasks_Conditions_CheckVariable_UnityEngine_Vector2;

		private CheckVariable<Vector3> NodeCanvas_Tasks_Conditions_CheckVariable_UnityEngine_Vector3;

		private CheckVariable<Vector4> NodeCanvas_Tasks_Conditions_CheckVariable_UnityEngine_Vector4;

		private CheckVariable<Quaternion> NodeCanvas_Tasks_Conditions_CheckVariable_UnityEngine_Quaternion;

		private CheckVariable<Keyframe> NodeCanvas_Tasks_Conditions_CheckVariable_UnityEngine_Keyframe;

		private CheckVariable<Bounds> NodeCanvas_Tasks_Conditions_CheckVariable_UnityEngine_Bounds;

		private CheckVariable<Color> NodeCanvas_Tasks_Conditions_CheckVariable_UnityEngine_Color;

		private CheckVariable<Rect> NodeCanvas_Tasks_Conditions_CheckVariable_UnityEngine_Rect;

		private CheckVariable<ContactPoint> NodeCanvas_Tasks_Conditions_CheckVariable_UnityEngine_ContactPoint;

		private CheckVariable<ContactPoint2D> NodeCanvas_Tasks_Conditions_CheckVariable_UnityEngine_ContactPoint2D;

		private CheckVariable<RaycastHit> NodeCanvas_Tasks_Conditions_CheckVariable_UnityEngine_RaycastHit;

		private CheckVariable<RaycastHit2D> NodeCanvas_Tasks_Conditions_CheckVariable_UnityEngine_RaycastHit2D;

		private CheckVariable<Ray> NodeCanvas_Tasks_Conditions_CheckVariable_UnityEngine_Ray;

		private CheckVariable<Space> NodeCanvas_Tasks_Conditions_CheckVariable_UnityEngine_Space;

		private CheckVariable<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Conditions_CheckVariable_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private CheckVariable<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckVariable_SceneManager_DestroyGadgetEventArgs;

		private CheckVariable<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckVariable_SceneManager_GetGadgetEventArgs;

		private CheckVariable<ModuleId> NodeCanvas_Tasks_Conditions_CheckVariable_ModuleId;

		private CheckVariable<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Conditions_CheckVariable_SceneManager_PrintGadgetEventArgs;

		private CheckVariable<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Conditions_CheckVariable_Workbench_SpawnModuleEventArgs;

		private CheckVariable<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Conditions_CheckVariable_Workbench_SpawnMotherboardEventArgs;

		private CheckVariable<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Conditions_CheckVariable_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private CheckVariable<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Conditions_CheckVariable_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private CheckVariable<uint> NodeCanvas_Tasks_Conditions_CheckVariable_System_UInt32;

		private CheckVariable<LayerMask> NodeCanvas_Tasks_Conditions_CheckVariable_UnityEngine_LayerMask;

		private ListContainsElement<bool> NodeCanvas_Tasks_Conditions_ListContainsElement_System_Boolean;

		private ListContainsElement<float> NodeCanvas_Tasks_Conditions_ListContainsElement_System_Single;

		private ListContainsElement<int> NodeCanvas_Tasks_Conditions_ListContainsElement_System_Int32;

		private ListContainsElement<Vector2> NodeCanvas_Tasks_Conditions_ListContainsElement_UnityEngine_Vector2;

		private ListContainsElement<Vector3> NodeCanvas_Tasks_Conditions_ListContainsElement_UnityEngine_Vector3;

		private ListContainsElement<Vector4> NodeCanvas_Tasks_Conditions_ListContainsElement_UnityEngine_Vector4;

		private ListContainsElement<Quaternion> NodeCanvas_Tasks_Conditions_ListContainsElement_UnityEngine_Quaternion;

		private ListContainsElement<Keyframe> NodeCanvas_Tasks_Conditions_ListContainsElement_UnityEngine_Keyframe;

		private ListContainsElement<Bounds> NodeCanvas_Tasks_Conditions_ListContainsElement_UnityEngine_Bounds;

		private ListContainsElement<Color> NodeCanvas_Tasks_Conditions_ListContainsElement_UnityEngine_Color;

		private ListContainsElement<Rect> NodeCanvas_Tasks_Conditions_ListContainsElement_UnityEngine_Rect;

		private ListContainsElement<ContactPoint> NodeCanvas_Tasks_Conditions_ListContainsElement_UnityEngine_ContactPoint;

		private ListContainsElement<ContactPoint2D> NodeCanvas_Tasks_Conditions_ListContainsElement_UnityEngine_ContactPoint2D;

		private ListContainsElement<RaycastHit> NodeCanvas_Tasks_Conditions_ListContainsElement_UnityEngine_RaycastHit;

		private ListContainsElement<RaycastHit2D> NodeCanvas_Tasks_Conditions_ListContainsElement_UnityEngine_RaycastHit2D;

		private ListContainsElement<Ray> NodeCanvas_Tasks_Conditions_ListContainsElement_UnityEngine_Ray;

		private ListContainsElement<Space> NodeCanvas_Tasks_Conditions_ListContainsElement_UnityEngine_Space;

		private ListContainsElement<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Conditions_ListContainsElement_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private ListContainsElement<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Conditions_ListContainsElement_SceneManager_DestroyGadgetEventArgs;

		private ListContainsElement<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Conditions_ListContainsElement_SceneManager_GetGadgetEventArgs;

		private ListContainsElement<ModuleId> NodeCanvas_Tasks_Conditions_ListContainsElement_ModuleId;

		private ListContainsElement<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Conditions_ListContainsElement_SceneManager_PrintGadgetEventArgs;

		private ListContainsElement<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Conditions_ListContainsElement_Workbench_SpawnModuleEventArgs;

		private ListContainsElement<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Conditions_ListContainsElement_Workbench_SpawnMotherboardEventArgs;

		private ListContainsElement<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Conditions_ListContainsElement_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private ListContainsElement<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Conditions_ListContainsElement_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private ListContainsElement<uint> NodeCanvas_Tasks_Conditions_ListContainsElement_System_UInt32;

		private ListContainsElement<LayerMask> NodeCanvas_Tasks_Conditions_ListContainsElement_UnityEngine_LayerMask;

		private TryGetValue<bool> NodeCanvas_Tasks_Conditions_TryGetValue_System_Boolean;

		private TryGetValue<float> NodeCanvas_Tasks_Conditions_TryGetValue_System_Single;

		private TryGetValue<int> NodeCanvas_Tasks_Conditions_TryGetValue_System_Int32;

		private TryGetValue<Vector2> NodeCanvas_Tasks_Conditions_TryGetValue_UnityEngine_Vector2;

		private TryGetValue<Vector3> NodeCanvas_Tasks_Conditions_TryGetValue_UnityEngine_Vector3;

		private TryGetValue<Vector4> NodeCanvas_Tasks_Conditions_TryGetValue_UnityEngine_Vector4;

		private TryGetValue<Quaternion> NodeCanvas_Tasks_Conditions_TryGetValue_UnityEngine_Quaternion;

		private TryGetValue<Keyframe> NodeCanvas_Tasks_Conditions_TryGetValue_UnityEngine_Keyframe;

		private TryGetValue<Bounds> NodeCanvas_Tasks_Conditions_TryGetValue_UnityEngine_Bounds;

		private TryGetValue<Color> NodeCanvas_Tasks_Conditions_TryGetValue_UnityEngine_Color;

		private TryGetValue<Rect> NodeCanvas_Tasks_Conditions_TryGetValue_UnityEngine_Rect;

		private TryGetValue<ContactPoint> NodeCanvas_Tasks_Conditions_TryGetValue_UnityEngine_ContactPoint;

		private TryGetValue<ContactPoint2D> NodeCanvas_Tasks_Conditions_TryGetValue_UnityEngine_ContactPoint2D;

		private TryGetValue<RaycastHit> NodeCanvas_Tasks_Conditions_TryGetValue_UnityEngine_RaycastHit;

		private TryGetValue<RaycastHit2D> NodeCanvas_Tasks_Conditions_TryGetValue_UnityEngine_RaycastHit2D;

		private TryGetValue<Ray> NodeCanvas_Tasks_Conditions_TryGetValue_UnityEngine_Ray;

		private TryGetValue<Space> NodeCanvas_Tasks_Conditions_TryGetValue_UnityEngine_Space;

		private TryGetValue<SceneManager.ChangeGadgetCoverMaterialEventArgs> NodeCanvas_Tasks_Conditions_TryGetValue_SceneManager_ChangeGadgetCoverMaterialEventArgs;

		private TryGetValue<SceneManager.DestroyGadgetEventArgs> NodeCanvas_Tasks_Conditions_TryGetValue_SceneManager_DestroyGadgetEventArgs;

		private TryGetValue<SceneManager.GetGadgetEventArgs> NodeCanvas_Tasks_Conditions_TryGetValue_SceneManager_GetGadgetEventArgs;

		private TryGetValue<ModuleId> NodeCanvas_Tasks_Conditions_TryGetValue_ModuleId;

		private TryGetValue<SceneManager.PrintGadgetEventArgs> NodeCanvas_Tasks_Conditions_TryGetValue_SceneManager_PrintGadgetEventArgs;

		private TryGetValue<Workbench.SpawnModuleEventArgs> NodeCanvas_Tasks_Conditions_TryGetValue_Workbench_SpawnModuleEventArgs;

		private TryGetValue<Workbench.SpawnMotherboardEventArgs> NodeCanvas_Tasks_Conditions_TryGetValue_Workbench_SpawnMotherboardEventArgs;

		private TryGetValue<ActionList.ActionsExecutionMode> NodeCanvas_Tasks_Conditions_TryGetValue_NodeCanvas_Framework_ActionList_ActionsExecutionMode;

		private TryGetValue<ConditionList.ConditionsCheckMode> NodeCanvas_Tasks_Conditions_TryGetValue_NodeCanvas_Framework_ConditionList_ConditionsCheckMode;

		private TryGetValue<uint> NodeCanvas_Tasks_Conditions_TryGetValue_System_UInt32;

		private TryGetValue<LayerMask> NodeCanvas_Tasks_Conditions_TryGetValue_UnityEngine_LayerMask;

		private void NodeCanvas_Framework_Blackboard_GetVariable_1()
		{
		}

		private void NodeCanvas_Framework_Blackboard_GetVariableValue_2()
		{
		}

		private void NodeCanvas_Framework_IBlackboardExtensions_AddVariable_1()
		{
		}

		private void NodeCanvas_Framework_IBlackboardExtensions_AddVariable_2()
		{
		}

		private void NodeCanvas_Framework_IBlackboardExtensions_GetVariableValue_3()
		{
		}

		private void NodeCanvas_Framework_IBlackboardExtensions_GetVariable_4()
		{
		}

		private void CustomSpoof()
		{
		}
	}
}
