<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Timberborn.NeedApplication</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Timberborn.TimeSystem">
      <HintPath>..\..\Assemblies\Timberborn.TimeSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Characters">
      <HintPath>..\..\Assemblies\Timberborn.Characters.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.WorldPersistence">
      <HintPath>..\..\Assemblies\Timberborn.WorldPersistence.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Common">
      <HintPath>..\..\Assemblies\Timberborn.Common.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections.Immutable">
      <HintPath>..\..\Assemblies\System.Collections.Immutable.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BlueprintSystem">
      <HintPath>..\..\Assemblies\Timberborn.BlueprintSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Demolishing">
      <HintPath>..\..\Assemblies\Timberborn.Demolishing.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.ReservableSystem">
      <HintPath>..\..\Assemblies\Timberborn.ReservableSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SceneLoading">
      <HintPath>..\..\Assemblies\Timberborn.SceneLoading.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.GameFactionSystem">
      <HintPath>..\..\Assemblies\Timberborn.GameFactionSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.TemplateInstantiation">
      <HintPath>..\..\Assemblies\Timberborn.TemplateInstantiation.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Effects">
      <HintPath>..\..\Assemblies\Timberborn.Effects.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.WorkSystem">
      <HintPath>..\..\Assemblies\Timberborn.WorkSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Yielding">
      <HintPath>..\..\Assemblies\Timberborn.Yielding.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Persistence">
      <HintPath>..\..\Assemblies\Timberborn.Persistence.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BlockSystem">
      <HintPath>..\..\Assemblies\Timberborn.BlockSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.NeedSystem">
      <HintPath>..\..\Assemblies\Timberborn.NeedSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Workshops">
      <HintPath>..\..\Assemblies\Timberborn.Workshops.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.EnterableSystem">
      <HintPath>..\..\Assemblies\Timberborn.EnterableSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.BaseComponentSystem">
      <HintPath>..\..\Assemblies\Timberborn.BaseComponentSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.SingletonSystem">
      <HintPath>..\..\Assemblies\Timberborn.SingletonSystem.dll</HintPath>
    </Reference>
    <Reference Include="Bindito.Core">
      <HintPath>..\..\Assemblies\Bindito.Core.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Coordinates">
      <HintPath>..\..\Assemblies\Timberborn.Coordinates.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.GameSceneLoading">
      <HintPath>..\..\Assemblies\Timberborn.GameSceneLoading.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.NewGameConfigurationSystem">
      <HintPath>..\..\Assemblies\Timberborn.NewGameConfigurationSystem.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.NeedSpecs">
      <HintPath>..\..\Assemblies\Timberborn.NeedSpecs.dll</HintPath>
    </Reference>
    <Reference Include="Timberborn.Goods">
      <HintPath>..\..\Assemblies\Timberborn.Goods.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>