internal enum dkzSnwtCxjCBgzTFJuuuLMvlAfvk
{
	aoZSLYGXKOuXhcUCxsheAmOnhGP = 0,
	rltpHhGKiTgPBpjUSIiQrnenhmVG = 1,
	CMAMfKWuyMkybrBiLAcZcmGyIszG = 2,
	xhqrprClGhJEsmXLtuApVWnQRpk = 3,
	oznsRWmVOkRNWMgVkLIdEhpbELG = 4,
	oisFPLcsyFQVXzRXycFYlvKYTZT = 5,
	VZWpHcujIQpVwYtXcHKikULuJWt = 6,
	wfnQtvjUnMkyySSnNKEdyoqHLrX = 7,
	KRqkupszLekWneSYaJRgWgcUhKXj = 8,
	HVQgujGrHLyhqmLdRObELGXCBvSC = 9,
	ysVNtUYVNGIUyuzmboiyuHJRrNj = 10,
	WCabXNeehThmGAHiBuqehgnmXIDw = 11,
	alOReLqcdEihtcekvuGKlnjOAfFe = 12,
	bFRVXaRvWMjdSVjhfJaehfYtGJN = 13,
	RYgsPqGkpWxKDhGCOlzqFWDlLnD = 14,
	SZFnGqfxlbLlpdTbaepEmdFhVzR = 15,
	GcUGZJOtnulOkwwjvhFvcJCVAGk = 16,
	PJlJGGkbAhuATkazDDtetKaRWR = 64,
	cYpQwYHpPQdekVplKwsIMFcqvku = 65,
	PlvAPuITVhzOqEErQtfmUTveNeNC = 66,
	gvhLQdcSdeDnMigoljvdrTgCVCgh = 67,
	zqRyiLnjNNiiPUPIVbIdTILpDQDg = 68
}
