[RKWutUoCqAxmbOvZeWzZlPmCapH(FceqCyjYBeSmKLyjPGuuoczjFQY.ETWRIlcrWkrbRYxCLOcuXqlSjCm)]
internal struct WjjYlXmXAfHcHTWLwEMCGqvGlYK
{
	[EBEcFoxOQjUZkVlTojjnLzfpHQb(sYsgBUbIeCqiDecxLLTsFJMgrgyP = "a36d02e0-c9f3-11cf-bfc7-444553540000", OJEPRQuqoFhmyaveIKijJUjyxaI = (pYDUQtFWywMKELdMLkqFCiEuGzi.vgNuKhdRbopODNVDFxuIEgEOHOhe | pYDUQtFWywMKELdMLkqFCiEuGzi.UAwdzUChrEKCiSlcRUpBPrHWtId))]
	internal int aKhnJLPlzQqMJcsXANqZDKcXdkvk;

	[EBEcFoxOQjUZkVlTojjnLzfpHQb(sYsgBUbIeCqiDecxLLTsFJMgrgyP = "a36d02e1-c9f3-11cf-bfc7-444553540000", OJEPRQuqoFhmyaveIKijJUjyxaI = (pYDUQtFWywMKELdMLkqFCiEuGzi.vgNuKhdRbopODNVDFxuIEgEOHOhe | pYDUQtFWywMKELdMLkqFCiEuGzi.UAwdzUChrEKCiSlcRUpBPrHWtId))]
	internal int CfrGUAcJZiBIgrKhIOoWYteVjgS;

	[EBEcFoxOQjUZkVlTojjnLzfpHQb(sYsgBUbIeCqiDecxLLTsFJMgrgyP = "a36d02e2-c9f3-11cf-bfc7-444553540000", OJEPRQuqoFhmyaveIKijJUjyxaI = (pYDUQtFWywMKELdMLkqFCiEuGzi.bnlwsefczUhSOjmQsXCWoppoUQo | pYDUQtFWywMKELdMLkqFCiEuGzi.vgNuKhdRbopODNVDFxuIEgEOHOhe | pYDUQtFWywMKELdMLkqFCiEuGzi.UAwdzUChrEKCiSlcRUpBPrHWtId))]
	internal int WXjeIOAoewOQIscExpKoNuKQHmwy;

	[EBEcFoxOQjUZkVlTojjnLzfpHQb(pYDUQtFWywMKELdMLkqFCiEuGzi.vgNuKhdRbopODNVDFxuIEgEOHOhe | pYDUQtFWywMKELdMLkqFCiEuGzi.TqdtkUxqfNjhGvosXmMgOFSZRoc)]
	internal byte iBuknEloRUrWSskvjaWhGBuFECf;

	[EBEcFoxOQjUZkVlTojjnLzfpHQb(pYDUQtFWywMKELdMLkqFCiEuGzi.vgNuKhdRbopODNVDFxuIEgEOHOhe | pYDUQtFWywMKELdMLkqFCiEuGzi.TqdtkUxqfNjhGvosXmMgOFSZRoc)]
	internal byte qfWQLZwjmyyZuKGymaeiWGsRBDo;

	[EBEcFoxOQjUZkVlTojjnLzfpHQb(pYDUQtFWywMKELdMLkqFCiEuGzi.bnlwsefczUhSOjmQsXCWoppoUQo | pYDUQtFWywMKELdMLkqFCiEuGzi.vgNuKhdRbopODNVDFxuIEgEOHOhe | pYDUQtFWywMKELdMLkqFCiEuGzi.TqdtkUxqfNjhGvosXmMgOFSZRoc)]
	internal byte DlvhmxZgjxlTWfLVIVFcGeEXEqrd;

	[EBEcFoxOQjUZkVlTojjnLzfpHQb(pYDUQtFWywMKELdMLkqFCiEuGzi.bnlwsefczUhSOjmQsXCWoppoUQo | pYDUQtFWywMKELdMLkqFCiEuGzi.vgNuKhdRbopODNVDFxuIEgEOHOhe | pYDUQtFWywMKELdMLkqFCiEuGzi.TqdtkUxqfNjhGvosXmMgOFSZRoc)]
	internal byte LeJJFmmZnxKUyoFNNoxfwSokoYx;

	[EBEcFoxOQjUZkVlTojjnLzfpHQb(pYDUQtFWywMKELdMLkqFCiEuGzi.bnlwsefczUhSOjmQsXCWoppoUQo | pYDUQtFWywMKELdMLkqFCiEuGzi.vgNuKhdRbopODNVDFxuIEgEOHOhe | pYDUQtFWywMKELdMLkqFCiEuGzi.TqdtkUxqfNjhGvosXmMgOFSZRoc)]
	internal byte oGXEsVXMQECytvOkGzeKVLzOBus;

	[EBEcFoxOQjUZkVlTojjnLzfpHQb(pYDUQtFWywMKELdMLkqFCiEuGzi.bnlwsefczUhSOjmQsXCWoppoUQo | pYDUQtFWywMKELdMLkqFCiEuGzi.vgNuKhdRbopODNVDFxuIEgEOHOhe | pYDUQtFWywMKELdMLkqFCiEuGzi.TqdtkUxqfNjhGvosXmMgOFSZRoc)]
	internal byte aCJXOkLBFktPXxyglUerWzTstxp;

	[EBEcFoxOQjUZkVlTojjnLzfpHQb(pYDUQtFWywMKELdMLkqFCiEuGzi.bnlwsefczUhSOjmQsXCWoppoUQo | pYDUQtFWywMKELdMLkqFCiEuGzi.vgNuKhdRbopODNVDFxuIEgEOHOhe | pYDUQtFWywMKELdMLkqFCiEuGzi.TqdtkUxqfNjhGvosXmMgOFSZRoc)]
	internal byte kYCEKvaFwkudwvFsagLiQblVSBvm;

	[EBEcFoxOQjUZkVlTojjnLzfpHQb(pYDUQtFWywMKELdMLkqFCiEuGzi.bnlwsefczUhSOjmQsXCWoppoUQo | pYDUQtFWywMKELdMLkqFCiEuGzi.vgNuKhdRbopODNVDFxuIEgEOHOhe | pYDUQtFWywMKELdMLkqFCiEuGzi.TqdtkUxqfNjhGvosXmMgOFSZRoc)]
	internal byte NKQbnazyWNMsYfRdTmFPcXaIbwi;
}
