public enum AkAttenuationCurveType
{
	AttenuationCurveID_VolumeDry = 0,
	AttenuationCurveID_VolumeAuxGameDef = 1,
	AttenuationCurveID_VolumeAuxUserDef = 2,
	AttenuationCurveID_LowPassFilter = 3,
	AttenuationCurveID_HighPassFilter = 4,
	AttenuationCurveID_Spread = 5,
	AttenuationCurveID_Focus = 6,
	AttenuationCurveID_ObstructionVolume = 7,
	AttenuationCurveID_ObstructionLPF = 8,
	AttenuationCurveID_ObstructionHPF = 9,
	AttenuationCurveID_OcclusionVolume = 10,
	AttenuationCurveID_OcclusionLPF = 11,
	AttenuationCurveID_OcclusionHPF = 12,
	AttenuationCurveID_DiffractionVolume = 13,
	AttenuationCurveID_DiffractionLPF = 14,
	AttenuationCurveID_DiffractionHPF = 15,
	AttenuationCurveID_TransmissionVolume = 16,
	AttenuationCurveID_TransmissionLPF = 17,
	AttenuationCurveID_TransmissionHPF = 18,
	AttenuationCurveID_MaxCount = 19,
	AttenuationCurveID_Project = 254,
	AttenuationCurveID_None = 255
}
