<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TwitchLib.Api.V5.Models</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>8.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\Assemblies\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="TwitchLib.Api.Core.Interfaces">
      <HintPath>..\..\Assemblies\TwitchLib.Api.Core.Interfaces.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>