<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Castle.Core</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Castle.DynamicProxy.DynProxy.snk" />
    <EmbeddedResource Include="Castle.DynamicProxy.DynProxy.snk" LogicalName="Castle.DynamicProxy.DynProxy.snk" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Diagnostics.EventLog">
      <HintPath>..\..\Assemblies\System.Diagnostics.EventLog.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>