using System;
using System.Xml.Linq;
using ModApi.Craft.Parts;
using ModApi.Craft.Parts.Attributes;
using ModApi.Design.PartProperties;
using UnityEngine;

namespace Assets.Scripts.Craft.Parts.Modifiers
{
	[Serializable]
	[DesignerPartModifier("Flight Program", PanelOrder = 2000)]
	public class FlightProgramData : PartModifierData<FlightProgramScript>
	{
		[DesignerPropertyCenterButton(Label = "Edit Flight Program", Order = 3, Tooltip = "Edit this part's flight program.")]
		private bool _editFlightProgramButton;

		[SerializeField]
		[PartModifierProperty(true, false)]
		private int _maxCallStackSize = 100;

		[SerializeField]
		[DesignerPropertySlider(25f, 200f, 8, Label = "Instructions per Frame", Order = 2, Tooltip = "Increasing it lets the program run more instructions per frame. Increasing the slider will greatly increase the power consumption.")]
		private int _maxInstructionsPerFrame = 25;

		[SerializeField]
		[PartModifierProperty(true, false)]
		private int _maxThreads = 50;

		[SerializeField]
		[DesignerPropertyToggleButton(Label = "Output to Dev Console", Order = 1, Tooltip = "If enabled, log messages generated by this program will be redirected to the Dev Console.")]
		private bool _outputToDevConsole;

		[SerializeField]
		[PartModifierProperty(true, false)]
		private double _timeSinceLaunch;

		[SerializeField]
		[PartModifierProperty(true, false)]
		private float _powerConsumptionPerInstruction;

		[SerializeField]
		[PartModifierProperty(true, false)]
		private float _broadcastPowerConsumptionPerByte;

		public XElement FlightProgramXml { get; set; }

		public bool HideEditButton { get; set; }

		public int MaxCallStackSize => _maxCallStackSize;

		public int MaxInstructionsPerFrame => _maxInstructionsPerFrame;

		public int MaxThreads => _maxThreads;

		public bool OutputToDevConsole
		{
			get
			{
				return _outputToDevConsole;
			}
			set
			{
				_outputToDevConsole = value;
			}
		}

		public XElement ProcessXml { get; set; }

		public bool SaveFlightProgram { get; set; } = true;

		public double TimeSinceLaunch
		{
			get
			{
				return _timeSinceLaunch;
			}
			set
			{
				_timeSinceLaunch = value;
			}
		}

		public float PowerConsumptionPerInstruction
		{
			get
			{
				return _powerConsumptionPerInstruction * 0.04f * (float)MaxInstructionsPerFrame;
			}
			set
			{
				_powerConsumptionPerInstruction = value;
			}
		}

		public float BroadcastPowerConsumptionPerByte
		{
			get
			{
				return _broadcastPowerConsumptionPerByte;
			}
			set
			{
				_broadcastPowerConsumptionPerByte = value;
			}
		}

		public static FlightProgramData Create(PartData partData)
		{
			FlightProgramData flightProgramData = PartModifierData.CreateFromDefaultXml<FlightProgramData>(partData);
			flightProgramData.CreateScript();
			return flightProgramData;
		}

		public void CareerLimits()
		{
			_maxInstructionsPerFrame = ((_maxInstructionsPerFrame > 200) ? 200 : 25);
			_maxCallStackSize = 100;
			_maxThreads = 50;
			_powerConsumptionPerInstruction = 0.1f;
			_broadcastPowerConsumptionPerByte = 0.01f;
		}

		public override XElement GenerateStateXml(bool optimizeXml = true)
		{
			XElement xElement = base.GenerateStateXml(optimizeXml);
			if (base.Script != null)
			{
				base.Script.UpdateXml();
			}
			if (FlightProgramXml != null && SaveFlightProgram)
			{
				xElement.Add(FlightProgramXml);
			}
			if (ProcessXml != null && SaveFlightProgram)
			{
				xElement.Add(ProcessXml);
			}
			return xElement;
		}

		public override void RestoreFromState(XElement stateElement, bool restoreAll)
		{
			base.RestoreFromState(stateElement, restoreAll);
			FlightProgramXml = stateElement.Element("Program");
			ProcessXml = stateElement.Element("Process");
		}

		protected override void OnDesignerInitialization(IDesignerPartPropertiesModifierInterface d)
		{
			base.OnDesignerInitialization(d);
			d.OnVisibilityRequested(() => _editFlightProgramButton, (bool x) => !HideEditButton);
			d.OnVisibilityRequested(() => _maxInstructionsPerFrame, (bool x) => !HideEditButton);
			d.OnPropertyChanged(() => _editFlightProgramButton, delegate
			{
				Game.Instance.Designer.DesignerUi.EditFlightProgram(base.Part);
			});
		}
	}
}
