<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Kitchen.Persistence</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>8.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="PlatformSettings">
      <HintPath>..\..\Assemblies\PlatformSettings.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Entities">
      <HintPath>..\..\Assemblies\Unity.Entities.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\Assemblies\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="MessagePack.Annotations">
      <HintPath>..\..\Assemblies\MessagePack.Annotations.dll</HintPath>
    </Reference>
    <Reference Include="Utility">
      <HintPath>..\..\Assemblies\Utility.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>..\..\Assemblies\Unity.Collections.dll</HintPath>
    </Reference>
    <Reference Include="Kitchen.MessagePack">
      <HintPath>..\..\Assemblies\Kitchen.MessagePack.dll</HintPath>
    </Reference>
    <Reference Include="MessagePack">
      <HintPath>..\..\Assemblies\MessagePack.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>